require "../foundation.cr"
require "../system/com.cr"
require "../security/cryptography.cr"

@[Link("delayimp")]
@[Link("user32")]
@[Link(ldflags: "/IGNORE:4199")]
@[Link(ldflags: "/DELAYLOAD:rpcproxy.dll")]
lib LibWin32
  ADMINDATA_MAX_NAME_LEN = 256_u32
  CLSID_MSAdminBase_W = "a9e69610-b80d-11d0-b9b9-00a0c922e750"
  IMGCHG_SIZE = 1_u32
  IMGCHG_VIEW = 2_u32
  IMGCHG_COMPLETE = 4_u32
  IMGCHG_ANIMATE = 8_u32
  IMGCHG_MASK = 15_u32
  IMGLOAD_NOTLOADED = 1048576_u32
  IMGLOAD_LOADING = 2097152_u32
  IMGLOAD_STOPPED = 4194304_u32
  IMGLOAD_ERROR = 8388608_u32
  IMGLOAD_COMPLETE = 16777216_u32
  IMGLOAD_MASK = 32505856_u32
  IMGBITS_NONE = 33554432_u32
  IMGBITS_PARTIAL = 67108864_u32
  IMGBITS_TOTAL = 134217728_u32
  IMGBITS_MASK = 234881024_u32
  IMGANIM_ANIMATED = 268435456_u32
  IMGANIM_MASK = 268435456_u32
  IMGTRANS_OPAQUE = 536870912_u32
  IMGTRANS_MASK = 536870912_u32
  DWN_COLORMODE = 63_u32
  DWN_DOWNLOADONLY = 64_u32
  DWN_FORCEDITHER = 128_u32
  DWN_RAWIMAGE = 256_u32
  DWN_MIRRORIMAGE = 512_u32
  CLSID_IImgCtx = "3050f3d6-98b5-11cf-bb82-00aa00bdce0b"
  IIS_MD_ADSI_METAID_BEGIN = 130000_u32
  IIS_MD_UT_SERVER = 1_u32
  IIS_MD_UT_FILE = 2_u32
  IIS_MD_UT_WAM = 100_u32
  ASP_MD_UT_APP = 101_u32
  IIS_MD_UT_END_RESERVED = 2000_u32
  IIS_MD_ID_BEGIN_RESERVED = 1_u32
  IIS_MD_ID_END_RESERVED = 32767_u32
  ASP_MD_ID_BEGIN_RESERVED = 28672_u32
  ASP_MD_ID_END_RESERVED = 29951_u32
  WAM_MD_ID_BEGIN_RESERVED = 29952_u32
  WAM_MD_ID_END_RESERVED = 32767_u32
  FP_MD_ID_BEGIN_RESERVED = 32768_u32
  FP_MD_ID_END_RESERVED = 36863_u32
  SMTP_MD_ID_BEGIN_RESERVED = 36864_u32
  SMTP_MD_ID_END_RESERVED = 40959_u32
  POP3_MD_ID_BEGIN_RESERVED = 40960_u32
  POP3_MD_ID_END_RESERVED = 45055_u32
  NNTP_MD_ID_BEGIN_RESERVED = 45056_u32
  NNTP_MD_ID_END_RESERVED = 49151_u32
  IMAP_MD_ID_BEGIN_RESERVED = 49152_u32
  IMAP_MD_ID_END_RESERVED = 53247_u32
  MSCS_MD_ID_BEGIN_RESERVED = 53248_u32
  MSCS_MD_ID_END_RESERVED = 57343_u32
  APPCTR_MD_ID_BEGIN_RESERVED = 57344_u32
  APPCTR_MD_ID_END_RESERVED = 61439_u32
  USER_MD_ID_BASE_RESERVED = 65535_u32
  IIS_MD_SERVER_BASE = 1000_u32
  MD_MAX_BANDWIDTH = 1000_u32
  MD_KEY_TYPE = 1002_u32
  MD_MAX_BANDWIDTH_BLOCKED = 1003_u32
  MD_SCHEMA_METAID = 1004_u32
  MD_SERVER_COMMAND = 1012_u32
  MD_CONNECTION_TIMEOUT = 1013_u32
  MD_MAX_CONNECTIONS = 1014_u32
  MD_SERVER_COMMENT = 1015_u32
  MD_SERVER_STATE = 1016_u32
  MD_SERVER_AUTOSTART = 1017_u32
  MD_SERVER_SIZE = 1018_u32
  MD_SERVER_LISTEN_BACKLOG = 1019_u32
  MD_SERVER_LISTEN_TIMEOUT = 1020_u32
  MD_DOWNLEVEL_ADMIN_INSTANCE = 1021_u32
  MD_LEVELS_TO_SCAN = 1022_u32
  MD_SERVER_BINDINGS = 1023_u32
  MD_MAX_ENDPOINT_CONNECTIONS = 1024_u32
  MD_SERVER_CONFIGURATION_INFO = 1027_u32
  MD_IISADMIN_EXTENSIONS = 1028_u32
  MD_DISABLE_SOCKET_POOLING = 1029_u32
  MD_METADATA_ID_REGISTRATION = 1030_u32
  IIS_MD_HTTP_BASE = 2000_u32
  MD_SECURE_BINDINGS = 2021_u32
  MD_BINDINGS = 2022_u32
  MD_ENABLEDPROTOCOLS = 2023_u32
  MD_FILTER_LOAD_ORDER = 2040_u32
  MD_FILTER_IMAGE_PATH = 2041_u32
  MD_FILTER_STATE = 2042_u32
  MD_FILTER_ENABLED = 2043_u32
  MD_FILTER_FLAGS = 2044_u32
  MD_FILTER_DESCRIPTION = 2045_u32
  MD_FILTER_ENABLE_CACHE = 2046_u32
  MD_ADV_NOTIFY_PWD_EXP_IN_DAYS = 2063_u32
  MD_ADV_CACHE_TTL = 2064_u32
  MD_NET_LOGON_WKS = 2065_u32
  MD_USE_HOST_NAME = 2066_u32
  MD_AUTH_CHANGE_FLAGS = 2068_u32
  MD_PROCESS_NTCR_IF_LOGGED_ON = 2070_u32
  MD_FRONTPAGE_WEB = 2072_u32
  MD_IN_PROCESS_ISAPI_APPS = 2073_u32
  MD_AUTH_CHANGE_URL = 2060_u32
  MD_AUTH_EXPIRED_URL = 2061_u32
  MD_AUTH_EXPIRED_UNSECUREURL = 2067_u32
  MD_ALLOW_PATH_INFO_FOR_SCRIPT_MAPPINGS = 2095_u32
  MD_APP_FRIENDLY_NAME = 2102_u32
  MD_APP_ROOT = 2103_u32
  MD_APP_ISOLATED = 2104_u32
  MD_APP_WAM_CLSID = 2105_u32
  MD_APP_PACKAGE_ID = 2106_u32
  MD_APP_PACKAGE_NAME = 2107_u32
  MD_APP_OOP_RECOVER_LIMIT = 2110_u32
  MD_APP_PERIODIC_RESTART_TIME = 2111_u32
  MD_APP_PERIODIC_RESTART_REQUESTS = 2112_u32
  MD_APP_PERIODIC_RESTART_SCHEDULE = 2113_u32
  MD_APP_SHUTDOWN_TIME_LIMIT = 2114_u32
  MD_ADMIN_INSTANCE = 2115_u32
  MD_NOT_DELETABLE = 2116_u32
  MD_APP_TRACE_URL_LIST = 2118_u32
  MD_CENTRAL_W3C_LOGGING_ENABLED = 2119_u32
  MD_CUSTOM_ERROR_DESC = 2120_u32
  MD_CAL_VC_PER_CONNECT = 2130_u32
  MD_CAL_AUTH_RESERVE_TIMEOUT = 2131_u32
  MD_CAL_SSL_RESERVE_TIMEOUT = 2132_u32
  MD_CAL_W3_ERROR = 2133_u32
  MD_CPU_CGI_ENABLED = 2140_u32
  MD_CPU_APP_ENABLED = 2141_u32
  MD_CPU_LIMITS_ENABLED = 2143_u32
  MD_CPU_RESET_INTERVAL = 2144_u32
  MD_CPU_LOGGING_INTERVAL = 2145_u32
  MD_CPU_LOGGING_OPTIONS = 2146_u32
  MD_CPU_CGI_LIMIT = 2148_u32
  MD_CPU_LIMIT_LOGEVENT = 2149_u32
  MD_CPU_LIMIT_PRIORITY = 2150_u32
  MD_CPU_LIMIT_PROCSTOP = 2151_u32
  MD_CPU_LIMIT_PAUSE = 2152_u32
  MD_SET_HOST_NAME = 2154_u32
  MD_CPU_DISABLE_ALL_LOGGING = 0_u32
  MD_CPU_ENABLE_ALL_PROC_LOGGING = 1_u32
  MD_CPU_ENABLE_CGI_LOGGING = 2_u32
  MD_CPU_ENABLE_APP_LOGGING = 4_u32
  MD_CPU_ENABLE_EVENT = 1_u32
  MD_CPU_ENABLE_PROC_TYPE = 2_u32
  MD_CPU_ENABLE_USER_TIME = 4_u32
  MD_CPU_ENABLE_KERNEL_TIME = 8_u32
  MD_CPU_ENABLE_PAGE_FAULTS = 16_u32
  MD_CPU_ENABLE_TOTAL_PROCS = 32_u32
  MD_CPU_ENABLE_ACTIVE_PROCS = 64_u32
  MD_CPU_ENABLE_TERMINATED_PROCS = 128_u32
  MD_CPU_ENABLE_LOGGING = 2147483648_u32
  MD_ISAPI_RESTRICTION_LIST = 2163_u32
  MD_CGI_RESTRICTION_LIST = 2164_u32
  MD_RESTRICTION_LIST_CUSTOM_DESC = 2165_u32
  MD_SECURITY_SETUP_REQUIRED = 2166_u32
  MD_APP_DEPENDENCIES = 2167_u32
  MD_WEB_SVC_EXT_RESTRICTION_LIST = 2168_u32
  MD_MD_SERVER_SS_AUTH_MAPPING = 2200_u32
  MD_CERT_NO_REVOC_CHECK = 1_u32
  MD_CERT_CACHE_RETRIEVAL_ONLY = 2_u32
  MD_CERT_CHECK_REVOCATION_FRESHNESS_TIME = 4_u32
  MD_CERT_NO_USAGE_CHECK = 65536_u32
  MD_HC_COMPRESSION_DIRECTORY = 2210_u32
  MD_HC_CACHE_CONTROL_HEADER = 2211_u32
  MD_HC_EXPIRES_HEADER = 2212_u32
  MD_HC_DO_DYNAMIC_COMPRESSION = 2213_u32
  MD_HC_DO_STATIC_COMPRESSION = 2214_u32
  MD_HC_DO_ON_DEMAND_COMPRESSION = 2215_u32
  MD_HC_DO_DISK_SPACE_LIMITING = 2216_u32
  MD_HC_NO_COMPRESSION_FOR_HTTP_10 = 2217_u32
  MD_HC_NO_COMPRESSION_FOR_PROXIES = 2218_u32
  MD_HC_NO_COMPRESSION_FOR_RANGE = 2219_u32
  MD_HC_SEND_CACHE_HEADERS = 2220_u32
  MD_HC_MAX_DISK_SPACE_USAGE = 2221_u32
  MD_HC_IO_BUFFER_SIZE = 2222_u32
  MD_HC_COMPRESSION_BUFFER_SIZE = 2223_u32
  MD_HC_MAX_QUEUE_LENGTH = 2224_u32
  MD_HC_FILES_DELETED_PER_DISK_FREE = 2225_u32
  MD_HC_MIN_FILE_SIZE_FOR_COMP = 2226_u32
  MD_HC_COMPRESSION_DLL = 2237_u32
  MD_HC_FILE_EXTENSIONS = 2238_u32
  MD_HC_MIME_TYPE = 2239_u32
  MD_HC_PRIORITY = 2240_u32
  MD_HC_DYNAMIC_COMPRESSION_LEVEL = 2241_u32
  MD_HC_ON_DEMAND_COMP_LEVEL = 2242_u32
  MD_HC_CREATE_FLAGS = 2243_u32
  MD_HC_SCRIPT_FILE_EXTENSIONS = 2244_u32
  MD_HC_DO_NAMESPACE_DYNAMIC_COMPRESSION = 2255_u32
  MD_HC_DO_NAMESPACE_STATIC_COMPRESSION = 2256_u32
  MD_WIN32_ERROR = 1099_u32
  IIS_MD_VR_BASE = 3000_u32
  MD_VR_PATH = 3001_u32
  MD_VR_USERNAME = 3002_u32
  MD_VR_PASSWORD = 3003_u32
  MD_VR_PASSTHROUGH = 3006_u32
  MD_VR_NO_CACHE = 3007_u32
  MD_VR_IGNORE_TRANSLATE = 3008_u32
  IIS_MD_LOG_BASE = 4000_u32
  MD_LOG_TYPE = 4000_u32
  MD_LOGFILE_DIRECTORY = 4001_u32
  MD_LOG_UNUSED1 = 4002_u32
  MD_LOGFILE_PERIOD = 4003_u32
  MD_LOGFILE_TRUNCATE_SIZE = 4004_u32
  MD_LOG_PLUGIN_MOD_ID = 4005_u32
  MD_LOG_PLUGIN_UI_ID = 4006_u32
  MD_LOGSQL_DATA_SOURCES = 4007_u32
  MD_LOGSQL_TABLE_NAME = 4008_u32
  MD_LOGSQL_USER_NAME = 4009_u32
  MD_LOGSQL_PASSWORD = 4010_u32
  MD_LOG_PLUGIN_ORDER = 4011_u32
  MD_LOG_PLUGINS_AVAILABLE = 4012_u32
  MD_LOGEXT_FIELD_MASK = 4013_u32
  MD_LOGEXT_FIELD_MASK2 = 4014_u32
  MD_LOGFILE_LOCALTIME_ROLLOVER = 4015_u32
  IIS_MD_LOG_LAST = 4015_u32
  MD_GLOBAL_BINARY_LOGGING_ENABLED = 4016_u32
  MD_LOG_TYPE_DISABLED = 0_u32
  MD_LOG_TYPE_ENABLED = 1_u32
  MD_LOGFILE_PERIOD_NONE = 0_u32
  MD_LOGFILE_PERIOD_MAXSIZE = 0_u32
  MD_LOGFILE_PERIOD_DAILY = 1_u32
  MD_LOGFILE_PERIOD_WEEKLY = 2_u32
  MD_LOGFILE_PERIOD_MONTHLY = 3_u32
  MD_LOGFILE_PERIOD_HOURLY = 4_u32
  MD_EXTLOG_DATE = 1_u32
  MD_EXTLOG_TIME = 2_u32
  MD_EXTLOG_CLIENT_IP = 4_u32
  MD_EXTLOG_USERNAME = 8_u32
  MD_EXTLOG_SITE_NAME = 16_u32
  MD_EXTLOG_COMPUTER_NAME = 32_u32
  MD_EXTLOG_SERVER_IP = 64_u32
  MD_EXTLOG_METHOD = 128_u32
  MD_EXTLOG_URI_STEM = 256_u32
  MD_EXTLOG_URI_QUERY = 512_u32
  MD_EXTLOG_HTTP_STATUS = 1024_u32
  MD_EXTLOG_WIN32_STATUS = 2048_u32
  MD_EXTLOG_BYTES_SENT = 4096_u32
  MD_EXTLOG_BYTES_RECV = 8192_u32
  MD_EXTLOG_TIME_TAKEN = 16384_u32
  MD_EXTLOG_SERVER_PORT = 32768_u32
  MD_EXTLOG_USER_AGENT = 65536_u32
  MD_EXTLOG_COOKIE = 131072_u32
  MD_EXTLOG_REFERER = 262144_u32
  MD_EXTLOG_PROTOCOL_VERSION = 524288_u32
  MD_EXTLOG_HOST = 1048576_u32
  MD_EXTLOG_HTTP_SUB_STATUS = 2097152_u32
  IIS_MD_LOGCUSTOM_BASE = 4500_u32
  MD_LOGCUSTOM_PROPERTY_NAME = 4501_u32
  MD_LOGCUSTOM_PROPERTY_HEADER = 4502_u32
  MD_LOGCUSTOM_PROPERTY_ID = 4503_u32
  MD_LOGCUSTOM_PROPERTY_MASK = 4504_u32
  MD_LOGCUSTOM_PROPERTY_DATATYPE = 4505_u32
  MD_LOGCUSTOM_SERVICES_STRING = 4506_u32
  MD_CPU_LOGGING_MASK = 4507_u32
  MD_LOGCUSTOM_PROPERTY_NODE_ID = 4508_u32
  IIS_MD_LOGCUSTOM_LAST = 4508_u32
  MD_LOGCUSTOM_DATATYPE_INT = 0_u32
  MD_LOGCUSTOM_DATATYPE_UINT = 1_u32
  MD_LOGCUSTOM_DATATYPE_LONG = 2_u32
  MD_LOGCUSTOM_DATATYPE_ULONG = 3_u32
  MD_LOGCUSTOM_DATATYPE_FLOAT = 4_u32
  MD_LOGCUSTOM_DATATYPE_DOUBLE = 5_u32
  MD_LOGCUSTOM_DATATYPE_LPSTR = 6_u32
  MD_LOGCUSTOM_DATATYPE_LPWSTR = 7_u32
  MD_NOTIFY_SECURE_PORT = 1_u32
  MD_NOTIFY_NONSECURE_PORT = 2_u32
  MD_NOTIFY_READ_RAW_DATA = 32768_u32
  MD_NOTIFY_PREPROC_HEADERS = 16384_u32
  MD_NOTIFY_AUTHENTICATION = 8192_u32
  MD_NOTIFY_URL_MAP = 4096_u32
  MD_NOTIFY_ACCESS_DENIED = 2048_u32
  MD_NOTIFY_SEND_RESPONSE = 64_u32
  MD_NOTIFY_SEND_RAW_DATA = 1024_u32
  MD_NOTIFY_LOG = 512_u32
  MD_NOTIFY_END_OF_REQUEST = 128_u32
  MD_NOTIFY_END_OF_NET_SESSION = 256_u32
  MD_NOTIFY_AUTH_COMPLETE = 67108864_u32
  MD_NOTIFY_ORDER_HIGH = 524288_u32
  MD_NOTIFY_ORDER_MEDIUM = 262144_u32
  MD_NOTIFY_ORDER_LOW = 131072_u32
  MD_NOTIFY_ORDER_DEFAULT = 131072_u32
  IIS_MD_FTP_BASE = 5000_u32
  MD_EXIT_MESSAGE = 5001_u32
  MD_GREETING_MESSAGE = 5002_u32
  MD_MAX_CLIENTS_MESSAGE = 5003_u32
  MD_MSDOS_DIR_OUTPUT = 5004_u32
  MD_ALLOW_ANONYMOUS = 5005_u32
  MD_ANONYMOUS_ONLY = 5006_u32
  MD_LOG_ANONYMOUS = 5007_u32
  MD_LOG_NONANONYMOUS = 5008_u32
  MD_ALLOW_REPLACE_ON_RENAME = 5009_u32
  MD_SHOW_4_DIGIT_YEAR = 5010_u32
  MD_BANNER_MESSAGE = 5011_u32
  MD_USER_ISOLATION = 5012_u32
  MD_FTP_LOG_IN_UTF_8 = 5013_u32
  MD_AD_CONNECTIONS_USERNAME = 5014_u32
  MD_AD_CONNECTIONS_PASSWORD = 5015_u32
  MD_PASSIVE_PORT_RANGE = 5016_u32
  MD_SUPPRESS_DEFAULT_BANNER = 5017_u32
  MD_FTP_PASV_RESPONSE_IP = 5018_u32
  MD_FTP_KEEP_PARTIAL_UPLOADS = 5019_u32
  MD_FTP_UTF8_FILE_NAMES = 5020_u32
  MD_FTPS_SECURE_CONTROL_CHANNEL = 5050_u32
  MD_FTPS_SECURE_DATA_CHANNEL = 5051_u32
  MD_FTPS_SECURE_ANONYMOUS = 5052_u32
  MD_FTPS_128_BITS = 5053_u32
  MD_FTPS_ALLOW_CCC = 5054_u32
  IIS_MD_SSL_BASE = 5500_u32
  MD_SSL_PUBLIC_KEY = 5500_u32
  MD_SSL_PRIVATE_KEY = 5501_u32
  MD_SSL_KEY_PASSWORD = 5502_u32
  MD_SSL_KEY_REQUEST = 5503_u32
  MD_SSL_USE_DS_MAPPER = 5519_u32
  MD_SSL_ALWAYS_NEGO_CLIENT_CERT = 5521_u32
  IIS_MD_FILE_PROP_BASE = 6000_u32
  MD_AUTHORIZATION = 6000_u32
  MD_REALM = 6001_u32
  MD_HTTP_EXPIRES = 6002_u32
  MD_HTTP_PICS = 6003_u32
  MD_HTTP_CUSTOM = 6004_u32
  MD_DIRECTORY_BROWSING = 6005_u32
  MD_DEFAULT_LOAD_FILE = 6006_u32
  MD_CUSTOM_ERROR = 6008_u32
  MD_FOOTER_DOCUMENT = 6009_u32
  MD_FOOTER_ENABLED = 6010_u32
  MD_HTTP_REDIRECT = 6011_u32
  MD_DEFAULT_LOGON_DOMAIN = 6012_u32
  MD_LOGON_METHOD = 6013_u32
  MD_SCRIPT_MAPS = 6014_u32
  MD_MIME_MAP = 6015_u32
  MD_ACCESS_PERM = 6016_u32
  MD_IP_SEC = 6019_u32
  MD_ANONYMOUS_USER_NAME = 6020_u32
  MD_ANONYMOUS_PWD = 6021_u32
  MD_ANONYMOUS_USE_SUBAUTH = 6022_u32
  MD_DONT_LOG = 6023_u32
  MD_ADMIN_ACL = 6027_u32
  MD_SSI_EXEC_DISABLED = 6028_u32
  MD_DO_REVERSE_DNS = 6029_u32
  MD_SSL_ACCESS_PERM = 6030_u32
  MD_AUTHORIZATION_PERSISTENCE = 6031_u32
  MD_NTAUTHENTICATION_PROVIDERS = 6032_u32
  MD_SCRIPT_TIMEOUT = 6033_u32
  MD_CACHE_EXTENSIONS = 6034_u32
  MD_CREATE_PROCESS_AS_USER = 6035_u32
  MD_CREATE_PROC_NEW_CONSOLE = 6036_u32
  MD_POOL_IDC_TIMEOUT = 6037_u32
  MD_ALLOW_KEEPALIVES = 6038_u32
  MD_IS_CONTENT_INDEXED = 6039_u32
  MD_CC_NO_CACHE = 6041_u32
  MD_CC_MAX_AGE = 6042_u32
  MD_CC_OTHER = 6043_u32
  MD_REDIRECT_HEADERS = 6044_u32
  MD_UPLOAD_READAHEAD_SIZE = 6045_u32
  MD_PUT_READ_SIZE = 6046_u32
  MD_USE_DIGEST_SSP = 6047_u32
  MD_ENABLE_URL_AUTHORIZATION = 6048_u32
  MD_URL_AUTHORIZATION_STORE_NAME = 6049_u32
  MD_URL_AUTHORIZATION_SCOPE_NAME = 6050_u32
  MD_MAX_REQUEST_ENTITY_ALLOWED = 6051_u32
  MD_PASSPORT_REQUIRE_AD_MAPPING = 6052_u32
  MD_URL_AUTHORIZATION_IMPERSONATION_LEVEL = 6053_u32
  MD_HTTP_FORWARDER_CUSTOM = 6054_u32
  MD_CUSTOM_DEPLOYMENT_DATA = 6055_u32
  MD_HTTPERRORS_EXISTING_RESPONSE = 6056_u32
  ASP_MD_SERVER_BASE = 7000_u32
  MD_ASP_BUFFERINGON = 7000_u32
  MD_ASP_LOGERRORREQUESTS = 7001_u32
  MD_ASP_SCRIPTERRORSSENTTOBROWSER = 7002_u32
  MD_ASP_SCRIPTERRORMESSAGE = 7003_u32
  MD_ASP_SCRIPTFILECACHESIZE = 7004_u32
  MD_ASP_SCRIPTENGINECACHEMAX = 7005_u32
  MD_ASP_SCRIPTTIMEOUT = 7006_u32
  MD_ASP_SESSIONTIMEOUT = 7007_u32
  MD_ASP_ENABLEPARENTPATHS = 7008_u32
  MD_ASP_MEMFREEFACTOR = 7009_u32
  MD_ASP_MINUSEDBLOCKS = 7010_u32
  MD_ASP_ALLOWSESSIONSTATE = 7011_u32
  MD_ASP_SCRIPTLANGUAGE = 7012_u32
  MD_ASP_QUEUETIMEOUT = 7013_u32
  MD_ASP_ALLOWOUTOFPROCCOMPONENTS = 7014_u32
  MD_ASP_ALLOWOUTOFPROCCMPNTS = 7014_u32
  MD_ASP_EXCEPTIONCATCHENABLE = 7015_u32
  MD_ASP_CODEPAGE = 7016_u32
  MD_ASP_SCRIPTLANGUAGELIST = 7017_u32
  MD_ASP_ENABLESERVERDEBUG = 7018_u32
  MD_ASP_ENABLECLIENTDEBUG = 7019_u32
  MD_ASP_TRACKTHREADINGMODEL = 7020_u32
  MD_ASP_ENABLEASPHTMLFALLBACK = 7021_u32
  MD_ASP_ENABLECHUNKEDENCODING = 7022_u32
  MD_ASP_ENABLETYPELIBCACHE = 7023_u32
  MD_ASP_ERRORSTONTLOG = 7024_u32
  MD_ASP_PROCESSORTHREADMAX = 7025_u32
  MD_ASP_REQEUSTQUEUEMAX = 7026_u32
  MD_ASP_ENABLEAPPLICATIONRESTART = 7027_u32
  MD_ASP_QUEUECONNECTIONTESTTIME = 7028_u32
  MD_ASP_SESSIONMAX = 7029_u32
  MD_ASP_THREADGATEENABLED = 7030_u32
  MD_ASP_THREADGATETIMESLICE = 7031_u32
  MD_ASP_THREADGATESLEEPDELAY = 7032_u32
  MD_ASP_THREADGATESLEEPMAX = 7033_u32
  MD_ASP_THREADGATELOADLOW = 7034_u32
  MD_ASP_THREADGATELOADHIGH = 7035_u32
  MD_ASP_DISKTEMPLATECACHEDIRECTORY = 7036_u32
  MD_ASP_MAXDISKTEMPLATECACHEFILES = 7040_u32
  MD_ASP_EXECUTEINMTA = 7041_u32
  MD_ASP_LCID = 7042_u32
  MD_ASP_KEEPSESSIONIDSECURE = 7043_u32
  MD_ASP_SERVICE_FLAGS = 7044_u32
  MD_ASP_SERVICE_FLAG_TRACKER = 7045_u32
  MD_ASP_SERVICE_FLAG_FUSION = 7046_u32
  MD_ASP_SERVICE_FLAG_PARTITIONS = 7047_u32
  MD_ASP_SERVICE_PARTITION_ID = 7048_u32
  MD_ASP_SERVICE_SXS_NAME = 7049_u32
  MD_ASP_SERVICE_ENABLE_TRACKER = 1_u32
  MD_ASP_SERVICE_ENABLE_SXS = 2_u32
  MD_ASP_SERVICE_USE_PARTITION = 4_u32
  MD_ASP_CALCLINENUMBER = 7050_u32
  MD_ASP_RUN_ONEND_ANON = 7051_u32
  MD_ASP_BUFFER_LIMIT = 7052_u32
  MD_ASP_MAX_REQUEST_ENTITY_ALLOWED = 7053_u32
  MD_ASP_MAXREQUESTENTITY = 7053_u32
  MD_ASP_ID_LAST = 7053_u32
  WAM_MD_SERVER_BASE = 7500_u32
  MD_WAM_USER_NAME = 7501_u32
  MD_WAM_PWD = 7502_u32
  WEBDAV_MD_SERVER_BASE = 8500_u32
  MD_WEBDAV_MAX_ATTRIBUTES_PER_ELEMENT = 8501_u32
  IIS_MD_APPPOOL_BASE = 9000_u32
  MD_APPPOOL_PERIODIC_RESTART_TIME = 9001_u32
  MD_APPPOOL_PERIODIC_RESTART_REQUEST_COUNT = 9002_u32
  MD_APPPOOL_MAX_PROCESS_COUNT = 9003_u32
  MD_APPPOOL_PINGING_ENABLED = 9004_u32
  MD_APPPOOL_IDLE_TIMEOUT = 9005_u32
  MD_APPPOOL_RAPID_FAIL_PROTECTION_ENABLED = 9006_u32
  MD_APPPOOL_SMP_AFFINITIZED = 9007_u32
  MD_APPPOOL_SMP_AFFINITIZED_PROCESSOR_MASK = 9008_u32
  MD_APPPOOL_ORPHAN_PROCESSES_FOR_DEBUGGING = 9009_u32
  MD_APPPOOL_STARTUP_TIMELIMIT = 9011_u32
  MD_APPPOOL_SHUTDOWN_TIMELIMIT = 9012_u32
  MD_APPPOOL_PING_INTERVAL = 9013_u32
  MD_APPPOOL_PING_RESPONSE_TIMELIMIT = 9014_u32
  MD_APPPOOL_DISALLOW_OVERLAPPING_ROTATION = 9015_u32
  MD_APPPOOL_UL_APPPOOL_QUEUE_LENGTH = 9017_u32
  MD_APPPOOL_DISALLOW_ROTATION_ON_CONFIG_CHANGE = 9018_u32
  MD_APPPOOL_PERIODIC_RESTART_SCHEDULE = 9020_u32
  MD_APPPOOL_IDENTITY_TYPE = 9021_u32
  MD_CPU_ACTION = 9022_u32
  MD_CPU_LIMIT = 9023_u32
  MD_APPPOOL_PERIODIC_RESTART_MEMORY = 9024_u32
  MD_APPPOOL_COMMAND = 9026_u32
  MD_APPPOOL_STATE = 9027_u32
  MD_APPPOOL_AUTO_START = 9028_u32
  MD_RAPID_FAIL_PROTECTION_INTERVAL = 9029_u32
  MD_RAPID_FAIL_PROTECTION_MAX_CRASHES = 9030_u32
  MD_APPPOOL_ORPHAN_ACTION_EXE = 9031_u32
  MD_APPPOOL_ORPHAN_ACTION_PARAMS = 9032_u32
  MB_DONT_IMPERSONATE = 9033_u32
  MD_LOAD_BALANCER_CAPABILITIES = 9034_u32
  MD_APPPOOL_AUTO_SHUTDOWN_EXE = 9035_u32
  MD_APPPOOL_AUTO_SHUTDOWN_PARAMS = 9036_u32
  MD_APP_POOL_LOG_EVENT_ON_RECYCLE = 9037_u32
  MD_APPPOOL_PERIODIC_RESTART_PRIVATE_MEMORY = 9038_u32
  MD_APPPOOL_MANAGED_RUNTIME_VERSION = 9039_u32
  MD_APPPOOL_32_BIT_APP_ON_WIN64 = 9040_u32
  MD_APPPOOL_MANAGED_PIPELINE_MODE = 9041_u32
  MD_APP_POOL_LOG_EVENT_ON_PROCESSMODEL = 9042_u32
  MD_APP_POOL_PROCESSMODEL_IDLE_TIMEOUT = 1_u32
  MD_APP_POOL_RECYCLE_TIME = 1_u32
  MD_APP_POOL_RECYCLE_REQUESTS = 2_u32
  MD_APP_POOL_RECYCLE_SCHEDULE = 4_u32
  MD_APP_POOL_RECYCLE_MEMORY = 8_u32
  MD_APP_POOL_RECYCLE_ISAPI_UNHEALTHY = 16_u32
  MD_APP_POOL_RECYCLE_ON_DEMAND = 32_u32
  MD_APP_POOL_RECYCLE_CONFIG_CHANGE = 64_u32
  MD_APP_POOL_RECYCLE_PRIVATE_MEMORY = 128_u32
  MD_CPU_NO_ACTION = 0_u32
  MD_CPU_KILL_W3WP = 1_u32
  MD_CPU_TRACE = 2_u32
  MD_CPU_THROTTLE = 3_u32
  MD_APPPOOL_COMMAND_START = 1_u32
  MD_APPPOOL_COMMAND_STOP = 2_u32
  MD_APPPOOL_STATE_STARTING = 1_u32
  MD_APPPOOL_STATE_STARTED = 2_u32
  MD_APPPOOL_STATE_STOPPING = 3_u32
  MD_APPPOOL_STATE_STOPPED = 4_u32
  MD_APPPOOL_IDENTITY_TYPE_LOCALSYSTEM = 0_u32
  MD_APPPOOL_IDENTITY_TYPE_LOCALSERVICE = 1_u32
  MD_APPPOOL_IDENTITY_TYPE_NETWORKSERVICE = 2_u32
  MD_APPPOOL_IDENTITY_TYPE_SPECIFICUSER = 3_u32
  MD_LOAD_BALANCER_CAPABILITIES_BASIC = 1_u32
  MD_LOAD_BALANCER_CAPABILITIES_SOPHISTICATED = 2_u32
  IIS_MD_APP_BASE = 9100_u32
  MD_APP_APPPOOL_ID = 9101_u32
  MD_APP_ALLOW_TRANSIENT_REGISTRATION = 9102_u32
  MD_APP_AUTO_START = 9103_u32
  MD_APPPOOL_PERIODIC_RESTART_CONNECTIONS = 9104_u32
  MD_APPPOOL_APPPOOL_ID = 9201_u32
  MD_APPPOOL_ALLOW_TRANSIENT_REGISTRATION = 9202_u32
  IIS_MD_GLOBAL_BASE = 9200_u32
  MD_MAX_GLOBAL_BANDWIDTH = 9201_u32
  MD_MAX_GLOBAL_CONNECTIONS = 9202_u32
  MD_GLOBAL_STANDARD_APP_MODE_ENABLED = 9203_u32
  MD_HEADER_WAIT_TIMEOUT = 9204_u32
  MD_MIN_FILE_BYTES_PER_SEC = 9205_u32
  MD_GLOBAL_LOG_IN_UTF_8 = 9206_u32
  MD_DEMAND_START_THRESHOLD = 9207_u32
  MD_GLOBAL_SESSIONKEY = 9999_u32
  MD_ROOT_ENABLE_EDIT_WHILE_RUNNING = 9998_u32
  MD_GLOBAL_CHANGE_NUMBER = 9997_u32
  MD_ROOT_ENABLE_HISTORY = 9996_u32
  MD_ROOT_MAX_HISTORY_FILES = 9995_u32
  MD_GLOBAL_EDIT_WHILE_RUNNING_MAJOR_VERSION_NUMBER = 9994_u32
  MD_GLOBAL_EDIT_WHILE_RUNNING_MINOR_VERSION_NUMBER = 9993_u32
  MD_GLOBAL_XMLSCHEMATIMESTAMP = 9992_u32
  MD_GLOBAL_BINSCHEMATIMESTAMP = 9991_u32
  MD_COMMENTS = 9990_u32
  MD_LOCATION = 9989_u32
  MD_MAX_ERROR_FILES = 9988_u32
  MD_STOP_LISTENING = 9987_u32
  MD_AUTH_ANONYMOUS = 1_u32
  MD_AUTH_BASIC = 2_u32
  MD_AUTH_NT = 4_u32
  MD_AUTH_MD5 = 16_u32
  MD_AUTH_PASSPORT = 64_u32
  MD_AUTH_SINGLEREQUEST = 64_u32
  MD_AUTH_SINGLEREQUESTIFPROXY = 128_u32
  MD_AUTH_SINGLEREQUESTALWAYSIFPROXY = 256_u32
  MD_ACCESS_READ = 1_u32
  MD_ACCESS_WRITE = 2_u32
  MD_ACCESS_EXECUTE = 4_u32
  MD_ACCESS_SOURCE = 16_u32
  MD_ACCESS_SCRIPT = 512_u32
  MD_ACCESS_NO_REMOTE_WRITE = 1024_u32
  MD_ACCESS_NO_REMOTE_READ = 4096_u32
  MD_ACCESS_NO_REMOTE_EXECUTE = 8192_u32
  MD_ACCESS_NO_REMOTE_SCRIPT = 16384_u32
  MD_ACCESS_NO_PHYSICAL_DIR = 32768_u32
  MD_ACCESS_SSL = 8_u32
  MD_ACCESS_NEGO_CERT = 32_u32
  MD_ACCESS_REQUIRE_CERT = 64_u32
  MD_ACCESS_MAP_CERT = 128_u32
  MD_ACCESS_SSL128 = 256_u32
  MD_ACCESS_MASK = 65535_u32
  MD_DIRBROW_SHOW_DATE = 2_u32
  MD_DIRBROW_SHOW_TIME = 4_u32
  MD_DIRBROW_SHOW_SIZE = 8_u32
  MD_DIRBROW_SHOW_EXTENSION = 16_u32
  MD_DIRBROW_LONG_DATE = 32_u32
  MD_DIRBROW_ENABLED = 2147483648_u32
  MD_DIRBROW_LOADDEFAULT = 1073741824_u32
  MD_LOGON_INTERACTIVE = 0_u32
  MD_LOGON_BATCH = 1_u32
  MD_LOGON_NETWORK = 2_u32
  MD_LOGON_NETWORK_CLEARTEXT = 3_u32
  MD_PASSPORT_NO_MAPPING = 0_u32
  MD_PASSPORT_TRY_MAPPING = 1_u32
  MD_PASSPORT_NEED_MAPPING = 2_u32
  MD_NOTIFEXAUTH_NTLMSSL = 1_u32
  MD_FILTER_STATE_LOADED = 1_u32
  MD_FILTER_STATE_UNLOADED = 4_u32
  MD_SERVER_STATE_STARTING = 1_u32
  MD_SERVER_STATE_STARTED = 2_u32
  MD_SERVER_STATE_STOPPING = 3_u32
  MD_SERVER_STATE_STOPPED = 4_u32
  MD_SERVER_STATE_PAUSING = 5_u32
  MD_SERVER_STATE_PAUSED = 6_u32
  MD_SERVER_STATE_CONTINUING = 7_u32
  MD_SERVER_COMMAND_START = 1_u32
  MD_SERVER_COMMAND_STOP = 2_u32
  MD_SERVER_COMMAND_PAUSE = 3_u32
  MD_SERVER_COMMAND_CONTINUE = 4_u32
  MD_SERVER_SIZE_SMALL = 0_u32
  MD_SERVER_SIZE_MEDIUM = 1_u32
  MD_SERVER_SIZE_LARGE = 2_u32
  MD_SERVER_CONFIG_SSL_40 = 1_u32
  MD_SERVER_CONFIG_SSL_128 = 2_u32
  MD_SERVER_CONFIG_ALLOW_ENCRYPT = 4_u32
  MD_SERVER_CONFIG_AUTO_PW_SYNC = 8_u32
  MD_SCRIPTMAPFLAG_SCRIPT = 1_u32
  MD_SCRIPTMAPFLAG_CHECK_PATH_INFO = 4_u32
  MD_SCRIPTMAPFLAG_ALLOWED_ON_READ_DIR = 1_u32
  MD_AUTH_CHANGE_UNSECURE = 1_u32
  MD_AUTH_CHANGE_DISABLE = 2_u32
  MD_AUTH_ADVNOTIFY_DISABLE = 4_u32
  MD_NETLOGON_WKS_NONE = 0_u32
  MD_NETLOGON_WKS_IP = 1_u32
  MD_NETLOGON_WKS_DNS = 2_u32
  MD_ERROR_SUB400_INVALID_DESTINATION = 1_u32
  MD_ERROR_SUB400_INVALID_DEPTH = 2_u32
  MD_ERROR_SUB400_INVALID_IF = 3_u32
  MD_ERROR_SUB400_INVALID_OVERWRITE = 4_u32
  MD_ERROR_SUB400_INVALID_TRANSLATE = 5_u32
  MD_ERROR_SUB400_INVALID_REQUEST_BODY = 6_u32
  MD_ERROR_SUB400_INVALID_CONTENT_LENGTH = 7_u32
  MD_ERROR_SUB400_INVALID_TIMEOUT = 8_u32
  MD_ERROR_SUB400_INVALID_LOCK_TOKEN = 9_u32
  MD_ERROR_SUB400_INVALID_XFF_HEADER = 10_u32
  MD_ERROR_SUB400_INVALID_WEBSOCKET_REQUEST = 11_u32
  MD_ERROR_SUB401_LOGON = 1_u32
  MD_ERROR_SUB401_LOGON_CONFIG = 2_u32
  MD_ERROR_SUB401_LOGON_ACL = 3_u32
  MD_ERROR_SUB401_FILTER = 4_u32
  MD_ERROR_SUB401_APPLICATION = 5_u32
  MD_ERROR_SUB401_URLAUTH_POLICY = 7_u32
  MD_ERROR_SUB403_EXECUTE_ACCESS_DENIED = 1_u32
  MD_ERROR_SUB403_READ_ACCESS_DENIED = 2_u32
  MD_ERROR_SUB403_WRITE_ACCESS_DENIED = 3_u32
  MD_ERROR_SUB403_SSL_REQUIRED = 4_u32
  MD_ERROR_SUB403_SSL128_REQUIRED = 5_u32
  MD_ERROR_SUB403_ADDR_REJECT = 6_u32
  MD_ERROR_SUB403_CERT_REQUIRED = 7_u32
  MD_ERROR_SUB403_SITE_ACCESS_DENIED = 8_u32
  MD_ERROR_SUB403_TOO_MANY_USERS = 9_u32
  MD_ERROR_SUB403_INVALID_CNFG = 10_u32
  MD_ERROR_SUB403_PWD_CHANGE = 11_u32
  MD_ERROR_SUB403_MAPPER_DENY_ACCESS = 12_u32
  MD_ERROR_SUB403_CERT_REVOKED = 13_u32
  MD_ERROR_SUB403_DIR_LIST_DENIED = 14_u32
  MD_ERROR_SUB403_CAL_EXCEEDED = 15_u32
  MD_ERROR_SUB403_CERT_BAD = 16_u32
  MD_ERROR_SUB403_CERT_TIME_INVALID = 17_u32
  MD_ERROR_SUB403_APPPOOL_DENIED = 18_u32
  MD_ERROR_SUB403_INSUFFICIENT_PRIVILEGE_FOR_CGI = 19_u32
  MD_ERROR_SUB403_PASSPORT_LOGIN_FAILURE = 20_u32
  MD_ERROR_SUB403_SOURCE_ACCESS_DENIED = 21_u32
  MD_ERROR_SUB403_INFINITE_DEPTH_DENIED = 22_u32
  MD_ERROR_SUB403_LOCK_TOKEN_REQUIRED = 23_u32
  MD_ERROR_SUB403_VALIDATION_FAILURE = 24_u32
  MD_ERROR_SUB404_SITE_NOT_FOUND = 1_u32
  MD_ERROR_SUB404_DENIED_BY_POLICY = 2_u32
  MD_ERROR_SUB404_DENIED_BY_MIMEMAP = 3_u32
  MD_ERROR_SUB404_NO_HANDLER = 4_u32
  MD_ERROR_SUB404_URL_SEQUENCE_DENIED = 5_u32
  MD_ERROR_SUB404_VERB_DENIED = 6_u32
  MD_ERROR_SUB404_FILE_EXTENSION_DENIED = 7_u32
  MD_ERROR_SUB404_HIDDEN_SEGMENT = 8_u32
  MD_ERROR_SUB404_FILE_ATTRIBUTE_HIDDEN = 9_u32
  MD_ERROR_SUB404_URL_DOUBLE_ESCAPED = 11_u32
  MD_ERROR_SUB404_URL_HAS_HIGH_BIT_CHARS = 12_u32
  MD_ERROR_SUB404_URL_TOO_LONG = 14_u32
  MD_ERROR_SUB404_QUERY_STRING_TOO_LONG = 15_u32
  MD_ERROR_SUB404_STATICFILE_DAV = 16_u32
  MD_ERROR_SUB404_PRECONDITIONED_HANDLER = 17_u32
  MD_ERROR_SUB404_QUERY_STRING_SEQUENCE_DENIED = 18_u32
  MD_ERROR_SUB404_DENIED_BY_FILTERING_RULE = 19_u32
  MD_ERROR_SUB404_TOO_MANY_URL_SEGMENTS = 20_u32
  MD_ERROR_SUB413_CONTENT_LENGTH_TOO_LARGE = 1_u32
  MD_ERROR_SUB423_LOCK_TOKEN_SUBMITTED = 1_u32
  MD_ERROR_SUB423_NO_CONFLICTING_LOCK = 2_u32
  MD_ERROR_SUB500_UNC_ACCESS = 16_u32
  MD_ERROR_SUB500_URLAUTH_NO_STORE = 17_u32
  MD_ERROR_SUB500_URLAUTH_STORE_ERROR = 18_u32
  MD_ERROR_SUB500_BAD_METADATA = 19_u32
  MD_ERROR_SUB500_URLAUTH_NO_SCOPE = 20_u32
  MD_ERROR_SUB500_HANDLERS_MODULE = 21_u32
  MD_ERROR_SUB500_ASPNET_MODULES = 22_u32
  MD_ERROR_SUB500_ASPNET_HANDLERS = 23_u32
  MD_ERROR_SUB500_ASPNET_IMPERSONATION = 24_u32
  MD_ERROR_SUB502_TIMEOUT = 1_u32
  MD_ERROR_SUB502_PREMATURE_EXIT = 2_u32
  MD_ERROR_SUB502_ARR_CONNECTION_ERROR = 3_u32
  MD_ERROR_SUB502_ARR_NO_SERVER = 4_u32
  MD_ERROR_SUB503_CPU_LIMIT = 1_u32
  MD_ERROR_SUB503_APP_CONCURRENT = 2_u32
  MD_ERROR_SUB503_ASPNET_QUEUE_FULL = 3_u32
  MD_ERROR_SUB503_FASTCGI_QUEUE_FULL = 4_u32
  MD_ERROR_SUB503_CONNECTION_LIMIT = 5_u32
  MD_ACR_READ = 1_u32
  MD_ACR_WRITE = 2_u32
  MD_ACR_RESTRICTED_WRITE = 32_u32
  MD_ACR_UNSECURE_PROPS_READ = 128_u32
  MD_ACR_ENUM_KEYS = 8_u32
  MD_ACR_WRITE_DAC = 262144_u32
  MD_USER_ISOLATION_NONE = 0_u32
  MD_USER_ISOLATION_BASIC = 1_u32
  MD_USER_ISOLATION_AD = 2_u32
  MD_USER_ISOLATION_LAST = 2_u32
  CLSID_IisServiceControl = "e8fb8621-588f-11d2-9d61-00c04f79c5fe"
  LIBID_IISRSTALib = "e8fb8614-588f-11d2-9d61-00c04f79c5fe"
  LIBID_WAMREGLib = "29822aa8-f302-11d0-9953-00c04fd919c1"
  CLSID_WamAdmin = "61738644-f196-11d0-9953-00c04fd919c1"
  APPSTATUS_STOPPED = 0_u32
  APPSTATUS_RUNNING = 1_u32
  APPSTATUS_NOTDEFINED = 2_u32
  METADATA_MAX_NAME_LEN = 256_u32
  METADATA_PERMISSION_READ = 1_u32
  METADATA_PERMISSION_WRITE = 2_u32
  METADATA_NO_ATTRIBUTES = 0_u32
  METADATA_INHERIT = 1_u32
  METADATA_PARTIAL_PATH = 2_u32
  METADATA_SECURE = 4_u32
  METADATA_REFERENCE = 8_u32
  METADATA_VOLATILE = 16_u32
  METADATA_ISINHERITED = 32_u32
  METADATA_INSERT_PATH = 64_u32
  METADATA_LOCAL_MACHINE_ONLY = 128_u32
  METADATA_NON_SECURE_ONLY = 256_u32
  METADATA_DONT_EXPAND = 512_u32
  MD_BACKUP_OVERWRITE = 1_u32
  MD_BACKUP_SAVE_FIRST = 2_u32
  MD_BACKUP_FORCE_BACKUP = 4_u32
  MD_BACKUP_NEXT_VERSION = 4294967295_u32
  MD_BACKUP_HIGHEST_VERSION = 4294967294_u32
  MD_BACKUP_MAX_VERSION = 9999_u32
  MD_BACKUP_MAX_LEN = 100_u32
  MD_HISTORY_LATEST = 1_u32
  MD_EXPORT_INHERITED = 1_u32
  MD_EXPORT_NODE_ONLY = 2_u32
  MD_IMPORT_INHERITED = 1_u32
  MD_IMPORT_NODE_ONLY = 2_u32
  MD_IMPORT_MERGE = 4_u32
  METADATA_MASTER_ROOT_HANDLE = 0_u32
  MD_CHANGE_TYPE_DELETE_OBJECT = 1_u32
  MD_CHANGE_TYPE_ADD_OBJECT = 2_u32
  MD_CHANGE_TYPE_SET_DATA = 4_u32
  MD_CHANGE_TYPE_DELETE_DATA = 8_u32
  MD_CHANGE_TYPE_RENAME_OBJECT = 16_u32
  MD_CHANGE_TYPE_RESTORE = 32_u32
  MD_MAX_CHANGE_ENTRIES = 100_u32
  MD_ERROR_NOT_INITIALIZED = -2146646016_i32
  MD_ERROR_DATA_NOT_FOUND = -2146646015_i32
  MD_ERROR_INVALID_VERSION = -2146646014_i32
  MD_WARNING_PATH_NOT_FOUND = 837635_i32
  MD_WARNING_DUP_NAME = 837636_i32
  MD_WARNING_INVALID_DATA = 837637_i32
  MD_ERROR_SECURE_CHANNEL_FAILURE = -2146646010_i32
  MD_WARNING_PATH_NOT_INSERTED = 837639_i32
  MD_ERROR_CANNOT_REMOVE_SECURE_ATTRIBUTE = -2146646008_i32
  MD_WARNING_SAVE_FAILED = 837641_i32
  MD_ERROR_IISAO_INVALID_SCHEMA = -2146646000_i32
  MD_ERROR_READ_METABASE_FILE = -2146645991_i32
  MD_ERROR_NO_SESSION_KEY = -2146645987_i32
  LIBID_ASPTypeLibrary = "d97a6da0-a85c-11cf-83ae-00a0c90c2bd8"
  CLSID_Request = "920c25d0-25d9-11d0-a55f-00a0c90c2091"
  CLSID_Response = "46e19ba0-25dd-11d0-a55f-00a0c90c2091"
  CLSID_Session = "509f8f20-25de-11d0-a55f-00a0c90c2091"
  CLSID_Server = "a506d160-25e0-11d0-a55f-00a0c90c2091"
  CLSID_ScriptingContext = "d97a6da0-a868-11cf-83ae-11b0c90c2bd8"
  HSE_VERSION_MAJOR = 8_u32
  HSE_VERSION_MINOR = 0_u32
  HSE_LOG_BUFFER_LEN = 80_u32
  HSE_MAX_EXT_DLL_NAME_LEN = 256_u32
  HSE_STATUS_SUCCESS = 1_u32
  HSE_STATUS_SUCCESS_AND_KEEP_CONN = 2_u32
  HSE_STATUS_PENDING = 3_u32
  HSE_STATUS_ERROR = 4_u32
  HSE_REQ_BASE = 0_u32
  HSE_REQ_SEND_URL_REDIRECT_RESP = 1_u32
  HSE_REQ_SEND_URL = 2_u32
  HSE_REQ_SEND_RESPONSE_HEADER = 3_u32
  HSE_REQ_DONE_WITH_SESSION = 4_u32
  HSE_REQ_END_RESERVED = 1000_u32
  HSE_REQ_MAP_URL_TO_PATH = 1001_u32
  HSE_REQ_GET_SSPI_INFO = 1002_u32
  HSE_APPEND_LOG_PARAMETER = 1003_u32
  HSE_REQ_IO_COMPLETION = 1005_u32
  HSE_REQ_TRANSMIT_FILE = 1006_u32
  HSE_REQ_REFRESH_ISAPI_ACL = 1007_u32
  HSE_REQ_IS_KEEP_CONN = 1008_u32
  HSE_REQ_ASYNC_READ_CLIENT = 1010_u32
  HSE_REQ_GET_IMPERSONATION_TOKEN = 1011_u32
  HSE_REQ_MAP_URL_TO_PATH_EX = 1012_u32
  HSE_REQ_ABORTIVE_CLOSE = 1014_u32
  HSE_REQ_GET_CERT_INFO_EX = 1015_u32
  HSE_REQ_SEND_RESPONSE_HEADER_EX = 1016_u32
  HSE_REQ_CLOSE_CONNECTION = 1017_u32
  HSE_REQ_IS_CONNECTED = 1018_u32
  HSE_REQ_MAP_UNICODE_URL_TO_PATH = 1023_u32
  HSE_REQ_MAP_UNICODE_URL_TO_PATH_EX = 1024_u32
  HSE_REQ_EXEC_UNICODE_URL = 1025_u32
  HSE_REQ_EXEC_URL = 1026_u32
  HSE_REQ_GET_EXEC_URL_STATUS = 1027_u32
  HSE_REQ_SEND_CUSTOM_ERROR = 1028_u32
  HSE_REQ_IS_IN_PROCESS = 1030_u32
  HSE_REQ_REPORT_UNHEALTHY = 1032_u32
  HSE_REQ_NORMALIZE_URL = 1033_u32
  HSE_REQ_VECTOR_SEND = 1037_u32
  HSE_REQ_GET_ANONYMOUS_TOKEN = 1038_u32
  HSE_REQ_GET_CACHE_INVALIDATION_CALLBACK = 1040_u32
  HSE_REQ_GET_UNICODE_ANONYMOUS_TOKEN = 1041_u32
  HSE_REQ_GET_TRACE_INFO = 1042_u32
  HSE_REQ_SET_FLUSH_FLAG = 1043_u32
  HSE_REQ_GET_TRACE_INFO_EX = 1044_u32
  HSE_REQ_RAISE_TRACE_EVENT = 1045_u32
  HSE_REQ_GET_CONFIG_OBJECT = 1046_u32
  HSE_REQ_GET_WORKER_PROCESS_SETTINGS = 1047_u32
  HSE_REQ_GET_PROTOCOL_MANAGER_CUSTOM_INTERFACE_CALLBACK = 1048_u32
  HSE_REQ_CANCEL_IO = 1049_u32
  HSE_REQ_GET_CHANNEL_BINDING_TOKEN = 1050_u32
  HSE_TERM_ADVISORY_UNLOAD = 1_u32
  HSE_TERM_MUST_UNLOAD = 2_u32
  HSE_URL_FLAGS_READ = 1_u32
  HSE_URL_FLAGS_WRITE = 2_u32
  HSE_URL_FLAGS_EXECUTE = 4_u32
  HSE_URL_FLAGS_SSL = 8_u32
  HSE_URL_FLAGS_DONT_CACHE = 16_u32
  HSE_URL_FLAGS_NEGO_CERT = 32_u32
  HSE_URL_FLAGS_REQUIRE_CERT = 64_u32
  HSE_URL_FLAGS_MAP_CERT = 128_u32
  HSE_URL_FLAGS_SSL128 = 256_u32
  HSE_URL_FLAGS_SCRIPT = 512_u32
  HSE_URL_FLAGS_MASK = 1023_u32
  HSE_EXEC_URL_NO_HEADERS = 2_u32
  HSE_EXEC_URL_IGNORE_CURRENT_INTERCEPTOR = 4_u32
  HSE_EXEC_URL_IGNORE_VALIDATION_AND_RANGE = 16_u32
  HSE_EXEC_URL_DISABLE_CUSTOM_ERROR = 32_u32
  HSE_EXEC_URL_SSI_CMD = 64_u32
  HSE_EXEC_URL_HTTP_CACHE_ELIGIBLE = 128_u32
  HSE_VECTOR_ELEMENT_TYPE_MEMORY_BUFFER = 0_u32
  HSE_VECTOR_ELEMENT_TYPE_FILE_HANDLE = 1_u32
  HSE_APP_FLAG_IN_PROCESS = 0_u32
  HSE_APP_FLAG_ISOLATED_OOP = 1_u32
  HSE_APP_FLAG_POOLED_OOP = 2_u32
  SF_MAX_USERNAME = 257_u32
  SF_MAX_PASSWORD = 257_u32
  SF_MAX_AUTH_TYPE = 33_u32
  SF_MAX_FILTER_DESC_LEN = 257_u32
  SF_DENIED_LOGON = 1_u32
  SF_DENIED_RESOURCE = 2_u32
  SF_DENIED_FILTER = 4_u32
  SF_DENIED_APPLICATION = 8_u32
  SF_DENIED_BY_CONFIG = 65536_u32
  SF_NOTIFY_SECURE_PORT = 1_u32
  SF_NOTIFY_NONSECURE_PORT = 2_u32
  SF_NOTIFY_READ_RAW_DATA = 32768_u32
  SF_NOTIFY_PREPROC_HEADERS = 16384_u32
  SF_NOTIFY_AUTHENTICATION = 8192_u32
  SF_NOTIFY_URL_MAP = 4096_u32
  SF_NOTIFY_ACCESS_DENIED = 2048_u32
  SF_NOTIFY_SEND_RESPONSE = 64_u32
  SF_NOTIFY_SEND_RAW_DATA = 1024_u32
  SF_NOTIFY_LOG = 512_u32
  SF_NOTIFY_END_OF_REQUEST = 128_u32
  SF_NOTIFY_END_OF_NET_SESSION = 256_u32
  SF_NOTIFY_AUTH_COMPLETE = 67108864_u32
  SF_NOTIFY_ORDER_HIGH = 524288_u32
  SF_NOTIFY_ORDER_MEDIUM = 262144_u32
  SF_NOTIFY_ORDER_LOW = 131072_u32
  SF_NOTIFY_ORDER_DEFAULT = 131072_u32
  DISPID_HTTPREQUEST_BASE = 1_u32
  DISPID_HTTPREQUEST_OPEN = 1_u32
  DISPID_HTTPREQUEST_SETREQUESTHEADER = 2_u32
  DISPID_HTTPREQUEST_GETRESPONSEHEADER = 3_u32
  DISPID_HTTPREQUEST_GETALLRESPONSEHEADERS = 4_u32
  DISPID_HTTPREQUEST_SEND = 5_u32
  DISPID_HTTPREQUEST_OPTION = 6_u32
  DISPID_HTTPREQUEST_STATUS = 7_u32
  DISPID_HTTPREQUEST_STATUSTEXT = 8_u32
  DISPID_HTTPREQUEST_RESPONSETEXT = 9_u32
  DISPID_HTTPREQUEST_RESPONSEBODY = 10_u32
  DISPID_HTTPREQUEST_RESPONSESTREAM = 11_u32
  DISPID_HTTPREQUEST_ABORT = 12_u32
  DISPID_HTTPREQUEST_SETPROXY = 13_u32
  DISPID_HTTPREQUEST_SETCREDENTIALS = 14_u32
  DISPID_HTTPREQUEST_WAITFORRESPONSE = 15_u32
  DISPID_HTTPREQUEST_SETTIMEOUTS = 16_u32
  DISPID_HTTPREQUEST_SETCLIENTCERTIFICATE = 17_u32
  DISPID_HTTPREQUEST_SETAUTOLOGONPOLICY = 18_u32
  HTTP_TRACE_EVENT_FLAG_STATIC_DESCRIPTIVE_FIELDS = 1_u32
  HTTP_TRACE_LEVEL_START = 6_u32
  HTTP_TRACE_LEVEL_END = 7_u32
  GUID_IIS_ALL_TRACE_PROVIDERS = "00000000-0000-0000-0000-000000000000"
  GUID_IIS_WWW_SERVER_TRACE_PROVIDER = "3a2a4e84-4c21-4981-ae10-3fda0d9b0f83"
  GUID_IIS_WWW_SERVER_V2_TRACE_PROVIDER = "de4649c9-15e8-4fea-9d85-1cdda520c334"
  GUID_IIS_ASPNET_TRACE_PROVIDER = "aff081fe-0247-4275-9c4e-021f3dc1da35"
  GUID_IIS_ASP_TRACE_TRACE_PROVIDER = "06b94d9a-b15e-456e-a4ef-37c984a2cb4b"
  GUID_IIS_WWW_GLOBAL_TRACE_PROVIDER = "d55d3bc9-cba9-44df-827e-132d3a4596c2"
  GUID_IIS_ISAPI_TRACE_PROVIDER = "a1c2040e-8840-4c31-ba11-9871031a19ea"
  FtpProvider = LibC::GUID.new(0x70bdc667_u32, 0x33b2_u16, 0x45f0_u16, StaticArray[0xac_u8, 0x52_u8, 0xc3_u8, 0xca_u8, 0x46_u8, 0xf7_u8, 0xa6_u8, 0x56_u8])

  type IIS_CRYPTO_BLOB = Void

  alias PFN_HSE_IO_COMPLETION = Proc(EXTENSION_CONTROL_BLOCK*, Void*, UInt32, UInt32, Void)
  alias PFN_HSE_CACHE_INVALIDATION_CALLBACK = Proc(LibC::LPWSTR, HRESULT)
  alias PFN_HSE_GET_PROTOCOL_MANAGER_CUSTOM_INTERFACE_CALLBACK = Proc(LibC::LPWSTR, LibC::LPWSTR, UInt32, Void**, HRESULT)
  alias PFN_GETEXTENSIONVERSION = Proc(HSE_VERSION_INFO*, LibC::BOOL)
  alias PFN_HTTPEXTENSIONPROC = Proc(EXTENSION_CONTROL_BLOCK*, UInt32)
  alias PFN_TERMINATEEXTENSION = Proc(UInt32, LibC::BOOL)
  alias PFN_WEB_CORE_SET_METADATA_DLL_ENTRY = Proc(LibC::LPWSTR, LibC::LPWSTR, HRESULT)
  alias PFN_WEB_CORE_ACTIVATE = Proc(LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, HRESULT)
  alias PFN_WEB_CORE_SHUTDOWN = Proc(UInt32, HRESULT)


  enum FTP_ACCESS : Int32
    FTP_ACCESS_NONE = 0
    FTP_ACCESS_READ = 1
    FTP_ACCESS_WRITE = 2
    FTP_ACCESS_READ_WRITE = 3
  end

  enum FTP_PROCESS_STATUS : Int32
    FTP_PROCESS_CONTINUE = 0
    FTP_PROCESS_CLOSE_SESSION = 1
    FTP_PROCESS_TERMINATE_SESSION = 2
    FTP_PROCESS_REJECT_COMMAND = 3
  end

  enum METADATATYPES : Int32
    ALL_METADATA = 0
    DWORD_METADATA = 1
    STRING_METADATA = 2
    BINARY_METADATA = 3
    EXPANDSZ_METADATA = 4
    MULTISZ_METADATA = 5
    INVALID_END_METADATA = 6
  end

  enum SF_REQ_TYPE : Int32
    SF_REQ_SEND_RESPONSE_HEADER = 0
    SF_REQ_ADD_HEADERS_ON_DENIAL = 1
    SF_REQ_SET_NEXT_READ_SIZE = 2
    SF_REQ_SET_PROXY_INFO = 3
    SF_REQ_GET_CONNID = 4
    SF_REQ_SET_CERTIFICATE_INFO = 5
    SF_REQ_GET_PROPERTY = 6
    SF_REQ_NORMALIZE_URL = 7
    SF_REQ_DISABLE_NOTIFICATIONS = 8
  end

  enum SF_PROPERTY_IIS : Int32
    SF_PROPERTY_SSL_CTXT = 0
    SF_PROPERTY_INSTANCE_NUM_ID = 1
  end

  enum SF_STATUS_TYPE : Int32
    SF_STATUS_REQ_FINISHED = 134217728
    SF_STATUS_REQ_FINISHED_KEEP_CONN = 134217729
    SF_STATUS_REQ_NEXT_NOTIFICATION = 134217730
    SF_STATUS_REQ_HANDLED_NOTIFICATION = 134217731
    SF_STATUS_REQ_ERROR = 134217732
    SF_STATUS_REQ_READ_NEXT = 134217733
  end

  enum HTTP_TRACE_TYPE : Int32
    HTTP_TRACE_TYPE_BYTE = 17
    HTTP_TRACE_TYPE_USHORT = 18
    HTTP_TRACE_TYPE_ULONG = 19
    HTTP_TRACE_TYPE_ULONGLONG = 21
    HTTP_TRACE_TYPE_CHAR = 16
    HTTP_TRACE_TYPE_SHORT = 2
    HTTP_TRACE_TYPE_LONG = 3
    HTTP_TRACE_TYPE_LONGLONG = 20
    HTTP_TRACE_TYPE_LPCWSTR = 31
    HTTP_TRACE_TYPE_LPCSTR = 30
    HTTP_TRACE_TYPE_LPCGUID = 72
    HTTP_TRACE_TYPE_BOOL = 11
  end

union METADATA_GETALL_INTERNAL_RECORD_Anonymous_e__Union
  dw_md_data_offset : LibC::UINT_PTR
  pb_md_data : UInt8*
end

  struct CONFIGURATION_ENTRY
    bstr_key : UInt8
    bstr_value : UInt8
  end
  struct LOGGING_PARAMETERS
    psz_session_id : LibC::LPWSTR
    psz_site_name : LibC::LPWSTR
    psz_user_name : LibC::LPWSTR
    psz_host_name : LibC::LPWSTR
    psz_remote_ip_address : LibC::LPWSTR
    dw_remote_ip_port : UInt32
    psz_local_ip_address : LibC::LPWSTR
    dw_local_ip_port : UInt32
    bytes_sent : UInt64
    bytes_received : UInt64
    psz_command : LibC::LPWSTR
    psz_command_parameters : LibC::LPWSTR
    psz_full_path : LibC::LPWSTR
    dw_elapsed_milliseconds : UInt32
    ftp_status : UInt32
    ftp_sub_status : UInt32
    hr_status : HRESULT
    psz_information : LibC::LPWSTR
  end
  struct PRE_PROCESS_PARAMETERS
    psz_session_id : LibC::LPWSTR
    psz_site_name : LibC::LPWSTR
    psz_user_name : LibC::LPWSTR
    psz_host_name : LibC::LPWSTR
    psz_remote_ip_address : LibC::LPWSTR
    dw_remote_ip_port : UInt32
    psz_local_ip_address : LibC::LPWSTR
    dw_local_ip_port : UInt32
    psz_command : LibC::LPWSTR
    psz_command_parameters : LibC::LPWSTR
    session_start_time : FILETIME
    bytes_sent_per_session : UInt64
    bytes_received_per_session : UInt64
  end
  struct POST_PROCESS_PARAMETERS
    psz_session_id : LibC::LPWSTR
    psz_site_name : LibC::LPWSTR
    psz_user_name : LibC::LPWSTR
    psz_host_name : LibC::LPWSTR
    psz_remote_ip_address : LibC::LPWSTR
    dw_remote_ip_port : UInt32
    psz_local_ip_address : LibC::LPWSTR
    dw_local_ip_port : UInt32
    bytes_sent : UInt64
    bytes_received : UInt64
    psz_command : LibC::LPWSTR
    psz_command_parameters : LibC::LPWSTR
    psz_full_path : LibC::LPWSTR
    psz_physical_path : LibC::LPWSTR
    ftp_status : UInt32
    ftp_sub_status : UInt32
    hr_status : HRESULT
    session_start_time : FILETIME
    bytes_sent_per_session : UInt64
    bytes_received_per_session : UInt64
  end
  struct METADATA_RECORD
    dw_md_identifier : UInt32
    dw_md_attributes : UInt32
    dw_md_user_type : UInt32
    dw_md_data_type : UInt32
    dw_md_data_len : UInt32
    pb_md_data : UInt8*
    dw_md_data_tag : UInt32
  end
  struct METADATA_GETALL_RECORD
    dw_md_identifier : UInt32
    dw_md_attributes : UInt32
    dw_md_user_type : UInt32
    dw_md_data_type : UInt32
    dw_md_data_len : UInt32
    dw_md_data_offset : UInt32
    dw_md_data_tag : UInt32
  end
  struct METADATA_GETALL_INTERNAL_RECORD
    dw_md_identifier : UInt32
    dw_md_attributes : UInt32
    dw_md_user_type : UInt32
    dw_md_data_type : UInt32
    dw_md_data_len : UInt32
    anonymous : METADATA_GETALL_INTERNAL_RECORD_Anonymous_e__Union
    dw_md_data_tag : UInt32
  end
  struct METADATA_HANDLE_INFO
    dw_md_permissions : UInt32
    dw_md_system_change_number : UInt32
  end
  struct MD_CHANGE_OBJECT_W
    psz_md_path : LibC::LPWSTR
    dw_md_change_type : UInt32
    dw_md_num_data_i_ds : UInt32
    pdw_md_data_i_ds : UInt32*
  end
  struct HSE_VERSION_INFO
    dw_extension_version : UInt32
    lpsz_extension_desc : CHAR[256]*
  end
  struct EXTENSION_CONTROL_BLOCK
    cb_size : UInt32
    dw_version : UInt32
    conn_id : Void*
    dw_http_status_code : UInt32
    lpsz_log_data : CHAR[80]*
    lpsz_method : PSTR
    lpsz_query_string : PSTR
    lpsz_path_info : PSTR
    lpsz_path_translated : PSTR
    cb_total_bytes : UInt32
    cb_available : UInt32
    lpb_data : UInt8*
    lpsz_content_type : PSTR
    get_server_variable : LibC::IntPtrT
    write_client : LibC::IntPtrT
    read_client : LibC::IntPtrT
    server_support_function : LibC::IntPtrT
  end
  struct HSE_URL_MAPEX_INFO
    lpsz_path : CHAR[260]*
    dw_flags : UInt32
    cch_matching_path : UInt32
    cch_matching_url : UInt32
    dw_reserved1 : UInt32
    dw_reserved2 : UInt32
  end
  struct HSE_UNICODE_URL_MAPEX_INFO
    lpsz_path : Char[260]*
    dw_flags : UInt32
    cch_matching_path : UInt32
    cch_matching_url : UInt32
  end
  struct HSE_TF_INFO
    pfn_hse_io : PFN_HSE_IO_COMPLETION
    p_context : Void*
    h_file : LibC::HANDLE
    psz_status_code : PSTR
    bytes_to_write : UInt32
    offset : UInt32
    p_head : Void*
    head_length : UInt32
    p_tail : Void*
    tail_length : UInt32
    dw_flags : UInt32
  end
  struct HSE_SEND_HEADER_EX_INFO
    psz_status : PSTR
    psz_header : PSTR
    cch_status : UInt32
    cch_header : UInt32
    f_keep_conn : LibC::BOOL
  end
  struct HSE_EXEC_URL_USER_INFO
    h_impersonation_token : LibC::HANDLE
    psz_custom_user_name : PSTR
    psz_custom_auth_type : PSTR
  end
  struct HSE_EXEC_URL_ENTITY_INFO
    cb_available : UInt32
    lpb_data : Void*
  end
  struct HSE_EXEC_URL_STATUS
    u_http_status_code : UInt16
    u_http_sub_status : UInt16
    dw_win32_error : UInt32
  end
  struct HSE_EXEC_URL_INFO
    psz_url : PSTR
    psz_method : PSTR
    psz_child_headers : PSTR
    p_user_info : HSE_EXEC_URL_USER_INFO*
    p_entity : HSE_EXEC_URL_ENTITY_INFO*
    dw_exec_url_flags : UInt32
  end
  struct HSE_EXEC_UNICODE_URL_USER_INFO
    h_impersonation_token : LibC::HANDLE
    psz_custom_user_name : LibC::LPWSTR
    psz_custom_auth_type : PSTR
  end
  struct HSE_EXEC_UNICODE_URL_INFO
    psz_url : LibC::LPWSTR
    psz_method : PSTR
    psz_child_headers : PSTR
    p_user_info : HSE_EXEC_UNICODE_URL_USER_INFO*
    p_entity : HSE_EXEC_URL_ENTITY_INFO*
    dw_exec_url_flags : UInt32
  end
  struct HSE_CUSTOM_ERROR_INFO
    psz_status : PSTR
    u_http_sub_error : UInt16
    f_async : LibC::BOOL
  end
  struct HSE_VECTOR_ELEMENT
    element_type : UInt32
    pv_context : Void*
    cb_offset : UInt64
    cb_size : UInt64
  end
  struct HSE_RESPONSE_VECTOR
    dw_flags : UInt32
    psz_status : PSTR
    psz_headers : PSTR
    n_element_count : UInt32
    lp_element_array : HSE_VECTOR_ELEMENT*
  end
  struct CERT_CONTEXT_EX
    cert_context : CERT_CONTEXT
    cb_allocated : UInt32
    dw_certificate_flags : UInt32
  end
  struct HSE_TRACE_INFO
    f_trace_request : LibC::BOOL
    trace_context_id : UInt8[16]*
    dw_reserved1 : UInt32
    dw_reserved2 : UInt32
  end
  struct HTTP_FILTER_CONTEXT
    cb_size : UInt32
    revision : UInt32
    server_context : Void*
    ul_reserved : UInt32
    f_is_secure_port : LibC::BOOL
    p_filter_context : Void*
    get_server_variable : LibC::IntPtrT
    add_response_headers : LibC::IntPtrT
    write_client : LibC::IntPtrT
    alloc_mem : LibC::IntPtrT
    server_support_function : LibC::IntPtrT
  end
  struct HTTP_FILTER_RAW_DATA
    pv_in_data : Void*
    cb_in_data : UInt32
    cb_in_buffer : UInt32
    dw_reserved : UInt32
  end
  struct HTTP_FILTER_PREPROC_HEADERS
    get_header : LibC::IntPtrT
    set_header : LibC::IntPtrT
    add_header : LibC::IntPtrT
    http_status : UInt32
    dw_reserved : UInt32
  end
  struct HTTP_FILTER_AUTHENT
    psz_user : PSTR
    cb_user_buff : UInt32
    psz_password : PSTR
    cb_password_buff : UInt32
  end
  struct HTTP_FILTER_URL_MAP
    psz_url : PSTR
    psz_physical_path : PSTR
    cb_path_buff : UInt32
  end
  struct HTTP_FILTER_URL_MAP_EX
    psz_url : PSTR
    psz_physical_path : PSTR
    cb_path_buff : UInt32
    dw_flags : UInt32
    cch_matching_path : UInt32
    cch_matching_url : UInt32
    psz_script_map_entry : PSTR
  end
  struct HTTP_FILTER_ACCESS_DENIED
    psz_url : PSTR
    psz_physical_path : PSTR
    dw_reason : UInt32
  end
  struct HTTP_FILTER_LOG
    psz_client_host_name : PSTR
    psz_client_user_name : PSTR
    psz_server_name : PSTR
    psz_operation : PSTR
    psz_target : PSTR
    psz_parameters : PSTR
    dw_http_status : UInt32
    dw_win32_status : UInt32
    dw_bytes_sent : UInt32
    dw_bytes_recvd : UInt32
    ms_time_for_processing : UInt32
  end
  struct HTTP_FILTER_AUTH_COMPLETE_INFO
    get_header : LibC::IntPtrT
    set_header : LibC::IntPtrT
    add_header : LibC::IntPtrT
    get_user_token : LibC::IntPtrT
    http_status : UInt32
    f_reset_auth : LibC::BOOL
    dw_reserved : UInt32
  end
  struct HTTP_FILTER_VERSION
    dw_server_filter_version : UInt32
    dw_filter_version : UInt32
    lpsz_filter_desc : CHAR[257]*
    dw_flags : UInt32
  end
  struct HTTP_TRACE_EVENT
    p_provider_guid : Guid*
    dw_area : UInt32
    p_area_guid : Guid*
    dw_event : UInt32
    psz_event_name : LibC::LPWSTR
    dw_event_version : UInt32
    dw_verbosity : UInt32
    p_activity_guid : Guid*
    p_related_activity_guid : Guid*
    dw_time_stamp : UInt32
    dw_flags : UInt32
    c_event_items : UInt32
    p_event_items : HTTP_TRACE_EVENT_ITEM*
  end
  struct HTTP_TRACE_EVENT_ITEM
    psz_name : LibC::LPWSTR
    dw_data_type : HTTP_TRACE_TYPE
    pb_data : UInt8*
    cb_data : UInt32
    psz_data_description : LibC::LPWSTR
  end
  struct HTTP_TRACE_CONFIGURATION
    p_provider_guid : Guid*
    dw_areas : UInt32
    dw_verbosity : UInt32
    f_provider_enabled : LibC::BOOL
  end


  struct IFtpProviderConstructVTbl
    query_interface : Proc(IFtpProviderConstruct*, Guid*, Void**, HRESULT)
    add_ref : Proc(IFtpProviderConstruct*, UInt32)
    release : Proc(IFtpProviderConstruct*, UInt32)
    construct : Proc(IFtpProviderConstruct*, SAFEARRAY*, HRESULT)
  end

  struct IFtpProviderConstruct
    lpVtbl : IFtpProviderConstructVTbl*
  end

  struct IFtpAuthenticationProviderVTbl
    query_interface : Proc(IFtpAuthenticationProvider*, Guid*, Void**, HRESULT)
    add_ref : Proc(IFtpAuthenticationProvider*, UInt32)
    release : Proc(IFtpAuthenticationProvider*, UInt32)
    authenticate_user : Proc(IFtpAuthenticationProvider*, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR*, LibC::BOOL*, HRESULT)
  end

  struct IFtpAuthenticationProvider
    lpVtbl : IFtpAuthenticationProviderVTbl*
  end

  struct AsyncIFtpAuthenticationProviderVTbl
    query_interface : Proc(AsyncIFtpAuthenticationProvider*, Guid*, Void**, HRESULT)
    add_ref : Proc(AsyncIFtpAuthenticationProvider*, UInt32)
    release : Proc(AsyncIFtpAuthenticationProvider*, UInt32)
    begin_authenticate_user : Proc(AsyncIFtpAuthenticationProvider*, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, HRESULT)
    finish_authenticate_user : Proc(AsyncIFtpAuthenticationProvider*, LibC::LPWSTR*, LibC::BOOL*, HRESULT)
  end

  struct AsyncIFtpAuthenticationProvider
    lpVtbl : AsyncIFtpAuthenticationProviderVTbl*
  end

  struct IFtpRoleProviderVTbl
    query_interface : Proc(IFtpRoleProvider*, Guid*, Void**, HRESULT)
    add_ref : Proc(IFtpRoleProvider*, UInt32)
    release : Proc(IFtpRoleProvider*, UInt32)
    is_user_in_role : Proc(IFtpRoleProvider*, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, LibC::BOOL*, HRESULT)
  end

  struct IFtpRoleProvider
    lpVtbl : IFtpRoleProviderVTbl*
  end

  struct AsyncIFtpRoleProviderVTbl
    query_interface : Proc(AsyncIFtpRoleProvider*, Guid*, Void**, HRESULT)
    add_ref : Proc(AsyncIFtpRoleProvider*, UInt32)
    release : Proc(AsyncIFtpRoleProvider*, UInt32)
    begin_is_user_in_role : Proc(AsyncIFtpRoleProvider*, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, HRESULT)
    finish_is_user_in_role : Proc(AsyncIFtpRoleProvider*, LibC::BOOL*, HRESULT)
  end

  struct AsyncIFtpRoleProvider
    lpVtbl : AsyncIFtpRoleProviderVTbl*
  end

  struct IFtpHomeDirectoryProviderVTbl
    query_interface : Proc(IFtpHomeDirectoryProvider*, Guid*, Void**, HRESULT)
    add_ref : Proc(IFtpHomeDirectoryProvider*, UInt32)
    release : Proc(IFtpHomeDirectoryProvider*, UInt32)
    get_user_home_directory_data : Proc(IFtpHomeDirectoryProvider*, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR*, HRESULT)
  end

  struct IFtpHomeDirectoryProvider
    lpVtbl : IFtpHomeDirectoryProviderVTbl*
  end

  struct AsyncIFtpHomeDirectoryProviderVTbl
    query_interface : Proc(AsyncIFtpHomeDirectoryProvider*, Guid*, Void**, HRESULT)
    add_ref : Proc(AsyncIFtpHomeDirectoryProvider*, UInt32)
    release : Proc(AsyncIFtpHomeDirectoryProvider*, UInt32)
    begin_get_user_home_directory_data : Proc(AsyncIFtpHomeDirectoryProvider*, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, HRESULT)
    finish_get_user_home_directory_data : Proc(AsyncIFtpHomeDirectoryProvider*, LibC::LPWSTR*, HRESULT)
  end

  struct AsyncIFtpHomeDirectoryProvider
    lpVtbl : AsyncIFtpHomeDirectoryProviderVTbl*
  end

  struct IFtpLogProviderVTbl
    query_interface : Proc(IFtpLogProvider*, Guid*, Void**, HRESULT)
    add_ref : Proc(IFtpLogProvider*, UInt32)
    release : Proc(IFtpLogProvider*, UInt32)
    log : Proc(IFtpLogProvider*, LOGGING_PARAMETERS*, HRESULT)
  end

  struct IFtpLogProvider
    lpVtbl : IFtpLogProviderVTbl*
  end

  struct AsyncIFtpLogProviderVTbl
    query_interface : Proc(AsyncIFtpLogProvider*, Guid*, Void**, HRESULT)
    add_ref : Proc(AsyncIFtpLogProvider*, UInt32)
    release : Proc(AsyncIFtpLogProvider*, UInt32)
    begin_log : Proc(AsyncIFtpLogProvider*, LOGGING_PARAMETERS*, HRESULT)
    finish_log : Proc(AsyncIFtpLogProvider*, HRESULT)
  end

  struct AsyncIFtpLogProvider
    lpVtbl : AsyncIFtpLogProviderVTbl*
  end

  struct IFtpAuthorizationProviderVTbl
    query_interface : Proc(IFtpAuthorizationProvider*, Guid*, Void**, HRESULT)
    add_ref : Proc(IFtpAuthorizationProvider*, UInt32)
    release : Proc(IFtpAuthorizationProvider*, UInt32)
    get_user_access_permission : Proc(IFtpAuthorizationProvider*, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, FTP_ACCESS*, HRESULT)
  end

  struct IFtpAuthorizationProvider
    lpVtbl : IFtpAuthorizationProviderVTbl*
  end

  struct AsyncIFtpAuthorizationProviderVTbl
    query_interface : Proc(AsyncIFtpAuthorizationProvider*, Guid*, Void**, HRESULT)
    add_ref : Proc(AsyncIFtpAuthorizationProvider*, UInt32)
    release : Proc(AsyncIFtpAuthorizationProvider*, UInt32)
    begin_get_user_access_permission : Proc(AsyncIFtpAuthorizationProvider*, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, HRESULT)
    finish_get_user_access_permission : Proc(AsyncIFtpAuthorizationProvider*, FTP_ACCESS*, HRESULT)
  end

  struct AsyncIFtpAuthorizationProvider
    lpVtbl : AsyncIFtpAuthorizationProviderVTbl*
  end

  struct IFtpPreprocessProviderVTbl
    query_interface : Proc(IFtpPreprocessProvider*, Guid*, Void**, HRESULT)
    add_ref : Proc(IFtpPreprocessProvider*, UInt32)
    release : Proc(IFtpPreprocessProvider*, UInt32)
    handle_preprocess : Proc(IFtpPreprocessProvider*, PRE_PROCESS_PARAMETERS*, FTP_PROCESS_STATUS*, HRESULT)
  end

  struct IFtpPreprocessProvider
    lpVtbl : IFtpPreprocessProviderVTbl*
  end

  struct AsyncIFtpPreprocessProviderVTbl
    query_interface : Proc(AsyncIFtpPreprocessProvider*, Guid*, Void**, HRESULT)
    add_ref : Proc(AsyncIFtpPreprocessProvider*, UInt32)
    release : Proc(AsyncIFtpPreprocessProvider*, UInt32)
    begin_handle_preprocess : Proc(AsyncIFtpPreprocessProvider*, PRE_PROCESS_PARAMETERS*, HRESULT)
    finish_handle_preprocess : Proc(AsyncIFtpPreprocessProvider*, FTP_PROCESS_STATUS*, HRESULT)
  end

  struct AsyncIFtpPreprocessProvider
    lpVtbl : AsyncIFtpPreprocessProviderVTbl*
  end

  struct IFtpPostprocessProviderVTbl
    query_interface : Proc(IFtpPostprocessProvider*, Guid*, Void**, HRESULT)
    add_ref : Proc(IFtpPostprocessProvider*, UInt32)
    release : Proc(IFtpPostprocessProvider*, UInt32)
    handle_postprocess : Proc(IFtpPostprocessProvider*, POST_PROCESS_PARAMETERS*, FTP_PROCESS_STATUS*, HRESULT)
  end

  struct IFtpPostprocessProvider
    lpVtbl : IFtpPostprocessProviderVTbl*
  end

  struct AsyncIFtpPostprocessProviderVTbl
    query_interface : Proc(AsyncIFtpPostprocessProvider*, Guid*, Void**, HRESULT)
    add_ref : Proc(AsyncIFtpPostprocessProvider*, UInt32)
    release : Proc(AsyncIFtpPostprocessProvider*, UInt32)
    begin_handle_postprocess : Proc(AsyncIFtpPostprocessProvider*, POST_PROCESS_PARAMETERS*, HRESULT)
    finish_handle_postprocess : Proc(AsyncIFtpPostprocessProvider*, FTP_PROCESS_STATUS*, HRESULT)
  end

  struct AsyncIFtpPostprocessProvider
    lpVtbl : AsyncIFtpPostprocessProviderVTbl*
  end

  struct IADMEXTVTbl
    query_interface : Proc(IADMEXT*, Guid*, Void**, HRESULT)
    add_ref : Proc(IADMEXT*, UInt32)
    release : Proc(IADMEXT*, UInt32)
    initialize : Proc(IADMEXT*, HRESULT)
    enum_dcom_clsi_ds : Proc(IADMEXT*, Guid*, UInt32, HRESULT)
    terminate : Proc(IADMEXT*, HRESULT)
  end

  struct IADMEXT
    lpVtbl : IADMEXTVTbl*
  end

  struct IMSAdminBaseWVTbl
    query_interface : Proc(IMSAdminBaseW*, Guid*, Void**, HRESULT)
    add_ref : Proc(IMSAdminBaseW*, UInt32)
    release : Proc(IMSAdminBaseW*, UInt32)
    add_key : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, HRESULT)
    delete_key : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, HRESULT)
    delete_child_keys : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, HRESULT)
    enum_keys : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, Char*, UInt32, HRESULT)
    copy_key : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, UInt32, LibC::LPWSTR, LibC::BOOL, LibC::BOOL, HRESULT)
    rename_key : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, LibC::LPWSTR, HRESULT)
    set_data : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, METADATA_RECORD*, HRESULT)
    get_data : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, METADATA_RECORD*, UInt32*, HRESULT)
    delete_data : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, UInt32, UInt32, HRESULT)
    enum_data : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, METADATA_RECORD*, UInt32, UInt32*, HRESULT)
    get_all_data : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, UInt32, UInt32, UInt32, UInt32*, UInt32*, UInt32, UInt8*, UInt32*, HRESULT)
    delete_all_data : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, UInt32, UInt32, HRESULT)
    copy_data : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, UInt32, LibC::LPWSTR, UInt32, UInt32, UInt32, LibC::BOOL, HRESULT)
    get_data_paths : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, UInt32, UInt32, UInt32, Char*, UInt32*, HRESULT)
    open_key : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, UInt32, UInt32, UInt32*, HRESULT)
    close_key : Proc(IMSAdminBaseW*, UInt32, HRESULT)
    change_permissions : Proc(IMSAdminBaseW*, UInt32, UInt32, UInt32, HRESULT)
    save_data : Proc(IMSAdminBaseW*, HRESULT)
    get_handle_info : Proc(IMSAdminBaseW*, UInt32, METADATA_HANDLE_INFO*, HRESULT)
    get_system_change_number : Proc(IMSAdminBaseW*, UInt32*, HRESULT)
    get_data_set_number : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, UInt32*, HRESULT)
    set_last_change_time : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, FILETIME*, LibC::BOOL, HRESULT)
    get_last_change_time : Proc(IMSAdminBaseW*, UInt32, LibC::LPWSTR, FILETIME*, LibC::BOOL, HRESULT)
    key_exchange_phase1 : Proc(IMSAdminBaseW*, HRESULT)
    key_exchange_phase2 : Proc(IMSAdminBaseW*, HRESULT)
    backup : Proc(IMSAdminBaseW*, LibC::LPWSTR, UInt32, UInt32, HRESULT)
    restore : Proc(IMSAdminBaseW*, LibC::LPWSTR, UInt32, UInt32, HRESULT)
    enum_backups : Proc(IMSAdminBaseW*, Char*, UInt32*, FILETIME*, UInt32, HRESULT)
    delete_backup : Proc(IMSAdminBaseW*, LibC::LPWSTR, UInt32, HRESULT)
    unmarshal_interface : Proc(IMSAdminBaseW*, IMSAdminBaseW*, HRESULT)
    get_server_guid : Proc(IMSAdminBaseW*, HRESULT)
  end

  struct IMSAdminBaseW
    lpVtbl : IMSAdminBaseWVTbl*
  end

  struct IMSAdminBase2WVTbl
    query_interface : Proc(IMSAdminBase2W*, Guid*, Void**, HRESULT)
    add_ref : Proc(IMSAdminBase2W*, UInt32)
    release : Proc(IMSAdminBase2W*, UInt32)
    add_key : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, HRESULT)
    delete_key : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, HRESULT)
    delete_child_keys : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, HRESULT)
    enum_keys : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, Char*, UInt32, HRESULT)
    copy_key : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, UInt32, LibC::LPWSTR, LibC::BOOL, LibC::BOOL, HRESULT)
    rename_key : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, LibC::LPWSTR, HRESULT)
    set_data : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, METADATA_RECORD*, HRESULT)
    get_data : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, METADATA_RECORD*, UInt32*, HRESULT)
    delete_data : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, UInt32, UInt32, HRESULT)
    enum_data : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, METADATA_RECORD*, UInt32, UInt32*, HRESULT)
    get_all_data : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, UInt32, UInt32, UInt32, UInt32*, UInt32*, UInt32, UInt8*, UInt32*, HRESULT)
    delete_all_data : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, UInt32, UInt32, HRESULT)
    copy_data : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, UInt32, LibC::LPWSTR, UInt32, UInt32, UInt32, LibC::BOOL, HRESULT)
    get_data_paths : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, UInt32, UInt32, UInt32, Char*, UInt32*, HRESULT)
    open_key : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, UInt32, UInt32, UInt32*, HRESULT)
    close_key : Proc(IMSAdminBase2W*, UInt32, HRESULT)
    change_permissions : Proc(IMSAdminBase2W*, UInt32, UInt32, UInt32, HRESULT)
    save_data : Proc(IMSAdminBase2W*, HRESULT)
    get_handle_info : Proc(IMSAdminBase2W*, UInt32, METADATA_HANDLE_INFO*, HRESULT)
    get_system_change_number : Proc(IMSAdminBase2W*, UInt32*, HRESULT)
    get_data_set_number : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, UInt32*, HRESULT)
    set_last_change_time : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, FILETIME*, LibC::BOOL, HRESULT)
    get_last_change_time : Proc(IMSAdminBase2W*, UInt32, LibC::LPWSTR, FILETIME*, LibC::BOOL, HRESULT)
    key_exchange_phase1 : Proc(IMSAdminBase2W*, HRESULT)
    key_exchange_phase2 : Proc(IMSAdminBase2W*, HRESULT)
    backup : Proc(IMSAdminBase2W*, LibC::LPWSTR, UInt32, UInt32, HRESULT)
    restore : Proc(IMSAdminBase2W*, LibC::LPWSTR, UInt32, UInt32, HRESULT)
    enum_backups : Proc(IMSAdminBase2W*, Char*, UInt32*, FILETIME*, UInt32, HRESULT)
    delete_backup : Proc(IMSAdminBase2W*, LibC::LPWSTR, UInt32, HRESULT)
    unmarshal_interface : Proc(IMSAdminBase2W*, IMSAdminBaseW*, HRESULT)
    get_server_guid : Proc(IMSAdminBase2W*, HRESULT)
    backup_with_passwd : Proc(IMSAdminBase2W*, LibC::LPWSTR, UInt32, UInt32, LibC::LPWSTR, HRESULT)
    restore_with_passwd : Proc(IMSAdminBase2W*, LibC::LPWSTR, UInt32, UInt32, LibC::LPWSTR, HRESULT)
    export : Proc(IMSAdminBase2W*, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, UInt32, HRESULT)
    import : Proc(IMSAdminBase2W*, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, UInt32, HRESULT)
    restore_history : Proc(IMSAdminBase2W*, LibC::LPWSTR, UInt32, UInt32, UInt32, HRESULT)
    enum_history : Proc(IMSAdminBase2W*, Char*, UInt32*, UInt32*, FILETIME*, UInt32, HRESULT)
  end

  struct IMSAdminBase2W
    lpVtbl : IMSAdminBase2WVTbl*
  end

  struct IMSAdminBase3WVTbl
    query_interface : Proc(IMSAdminBase3W*, Guid*, Void**, HRESULT)
    add_ref : Proc(IMSAdminBase3W*, UInt32)
    release : Proc(IMSAdminBase3W*, UInt32)
    add_key : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, HRESULT)
    delete_key : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, HRESULT)
    delete_child_keys : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, HRESULT)
    enum_keys : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, Char*, UInt32, HRESULT)
    copy_key : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, UInt32, LibC::LPWSTR, LibC::BOOL, LibC::BOOL, HRESULT)
    rename_key : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, LibC::LPWSTR, HRESULT)
    set_data : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, METADATA_RECORD*, HRESULT)
    get_data : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, METADATA_RECORD*, UInt32*, HRESULT)
    delete_data : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, UInt32, UInt32, HRESULT)
    enum_data : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, METADATA_RECORD*, UInt32, UInt32*, HRESULT)
    get_all_data : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, UInt32, UInt32, UInt32, UInt32*, UInt32*, UInt32, UInt8*, UInt32*, HRESULT)
    delete_all_data : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, UInt32, UInt32, HRESULT)
    copy_data : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, UInt32, LibC::LPWSTR, UInt32, UInt32, UInt32, LibC::BOOL, HRESULT)
    get_data_paths : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, UInt32, UInt32, UInt32, Char*, UInt32*, HRESULT)
    open_key : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, UInt32, UInt32, UInt32*, HRESULT)
    close_key : Proc(IMSAdminBase3W*, UInt32, HRESULT)
    change_permissions : Proc(IMSAdminBase3W*, UInt32, UInt32, UInt32, HRESULT)
    save_data : Proc(IMSAdminBase3W*, HRESULT)
    get_handle_info : Proc(IMSAdminBase3W*, UInt32, METADATA_HANDLE_INFO*, HRESULT)
    get_system_change_number : Proc(IMSAdminBase3W*, UInt32*, HRESULT)
    get_data_set_number : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, UInt32*, HRESULT)
    set_last_change_time : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, FILETIME*, LibC::BOOL, HRESULT)
    get_last_change_time : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, FILETIME*, LibC::BOOL, HRESULT)
    key_exchange_phase1 : Proc(IMSAdminBase3W*, HRESULT)
    key_exchange_phase2 : Proc(IMSAdminBase3W*, HRESULT)
    backup : Proc(IMSAdminBase3W*, LibC::LPWSTR, UInt32, UInt32, HRESULT)
    restore : Proc(IMSAdminBase3W*, LibC::LPWSTR, UInt32, UInt32, HRESULT)
    enum_backups : Proc(IMSAdminBase3W*, Char*, UInt32*, FILETIME*, UInt32, HRESULT)
    delete_backup : Proc(IMSAdminBase3W*, LibC::LPWSTR, UInt32, HRESULT)
    unmarshal_interface : Proc(IMSAdminBase3W*, IMSAdminBaseW*, HRESULT)
    get_server_guid : Proc(IMSAdminBase3W*, HRESULT)
    backup_with_passwd : Proc(IMSAdminBase3W*, LibC::LPWSTR, UInt32, UInt32, LibC::LPWSTR, HRESULT)
    restore_with_passwd : Proc(IMSAdminBase3W*, LibC::LPWSTR, UInt32, UInt32, LibC::LPWSTR, HRESULT)
    export : Proc(IMSAdminBase3W*, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, UInt32, HRESULT)
    import : Proc(IMSAdminBase3W*, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR, UInt32, HRESULT)
    restore_history : Proc(IMSAdminBase3W*, LibC::LPWSTR, UInt32, UInt32, UInt32, HRESULT)
    enum_history : Proc(IMSAdminBase3W*, Char*, UInt32*, UInt32*, FILETIME*, UInt32, HRESULT)
    get_child_paths : Proc(IMSAdminBase3W*, UInt32, LibC::LPWSTR, UInt32, Char*, UInt32*, HRESULT)
  end

  struct IMSAdminBase3W
    lpVtbl : IMSAdminBase3WVTbl*
  end

  struct IMSImpExpHelpWVTbl
    query_interface : Proc(IMSImpExpHelpW*, Guid*, Void**, HRESULT)
    add_ref : Proc(IMSImpExpHelpW*, UInt32)
    release : Proc(IMSImpExpHelpW*, UInt32)
    enumerate_paths_in_file : Proc(IMSImpExpHelpW*, LibC::LPWSTR, LibC::LPWSTR, UInt32, Char*, UInt32*, HRESULT)
  end

  struct IMSImpExpHelpW
    lpVtbl : IMSImpExpHelpWVTbl*
  end

  struct IMSAdminBaseSinkWVTbl
    query_interface : Proc(IMSAdminBaseSinkW*, Guid*, Void**, HRESULT)
    add_ref : Proc(IMSAdminBaseSinkW*, UInt32)
    release : Proc(IMSAdminBaseSinkW*, UInt32)
    sink_notify : Proc(IMSAdminBaseSinkW*, UInt32, MD_CHANGE_OBJECT_W*, HRESULT)
    shutdown_notify : Proc(IMSAdminBaseSinkW*, HRESULT)
  end

  struct IMSAdminBaseSinkW
    lpVtbl : IMSAdminBaseSinkWVTbl*
  end

  struct AsyncIMSAdminBaseSinkWVTbl
    query_interface : Proc(AsyncIMSAdminBaseSinkW*, Guid*, Void**, HRESULT)
    add_ref : Proc(AsyncIMSAdminBaseSinkW*, UInt32)
    release : Proc(AsyncIMSAdminBaseSinkW*, UInt32)
    begin_sink_notify : Proc(AsyncIMSAdminBaseSinkW*, UInt32, MD_CHANGE_OBJECT_W*, HRESULT)
    finish_sink_notify : Proc(AsyncIMSAdminBaseSinkW*, HRESULT)
    begin_shutdown_notify : Proc(AsyncIMSAdminBaseSinkW*, HRESULT)
    finish_shutdown_notify : Proc(AsyncIMSAdminBaseSinkW*, HRESULT)
  end

  struct AsyncIMSAdminBaseSinkW
    lpVtbl : AsyncIMSAdminBaseSinkWVTbl*
  end


  # Params # pver : HSE_VERSION_INFO* [In]
  fun GetExtensionVersion(pver : HSE_VERSION_INFO*) : LibC::BOOL

  # Params # pecb : EXTENSION_CONTROL_BLOCK* [In]
  fun HttpExtensionProc(pecb : EXTENSION_CONTROL_BLOCK*) : UInt32

  # Params # pfc : HTTP_FILTER_CONTEXT* [In],notificationtype : UInt32 [In],pvnotification : Void* [In]
  fun HttpFilterProc(pfc : HTTP_FILTER_CONTEXT*, notificationtype : UInt32, pvnotification : Void*) : UInt32

  # Params # pver : HTTP_FILTER_VERSION* [In]
  fun GetFilterVersion(pver : HTTP_FILTER_VERSION*) : LibC::BOOL
end
