require "./../foundation.cr"

module Win32cr::Devices::Bluetooth
  alias HANDLE_SDP_TYPE = UInt64
  alias PFN_DEVICE_CALLBACK = Proc(Void*, Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO*, Win32cr::Foundation::BOOL)

  alias PFN_AUTHENTICATION_CALLBACK = Proc(Void*, Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO*, Win32cr::Foundation::BOOL)

  alias PFN_AUTHENTICATION_CALLBACK_EX = Proc(Void*, Win32cr::Devices::Bluetooth::BLUETOOTH_AUTHENTICATION_CALLBACK_PARAMS*, Win32cr::Foundation::BOOL)

  alias PFN_BLUETOOTH_ENUM_ATTRIBUTES_CALLBACK = Proc(UInt32, UInt8*, UInt32, Void*, Win32cr::Foundation::BOOL)

  alias PFNBLUETOOTH_GATT_EVENT_CALLBACK = Proc(Win32cr::Devices::Bluetooth::BTH_LE_GATT_EVENT_TYPE, Void*, Void*, Void)

  BTH_MAJORVERSION = 2_u32
  BTH_MINORVERSION = 1_u32
  GUID_BTHPORT_DEVICE_INTERFACE = "0850302a-b344-4fda-9be9-90576b8d46f0"
  GUID_BTH_RFCOMM_SERVICE_DEVICE_INTERFACE = "b142fc3e-fa4e-460b-8abc-072b628b3c70"
  GUID_BLUETOOTH_RADIO_IN_RANGE = "ea3b5b82-26ee-450e-b0d8-d26fe30a3869"
  GUID_BLUETOOTH_RADIO_OUT_OF_RANGE = "e28867c9-c2aa-4ced-b969-4570866037c4"
  GUID_BLUETOOTH_L2CAP_EVENT = "7eae4030-b709-4aa8-ac55-e953829c9daa"
  GUID_BLUETOOTH_HCI_EVENT = "fc240062-1541-49be-b463-84c4dcd7bf7f"
  GUID_BLUETOOTH_AUTHENTICATION_REQUEST = "5dc9136d-996c-46db-84f5-32c0a3f47352"
  GUID_BLUETOOTH_KEYPRESS_EVENT = "d668dfcd-0f4e-4efc-bfe0-392eeec5109c"
  GUID_BLUETOOTH_HCI_VENDOR_EVENT = "547247e6-45bb-4c33-af8c-c00efe15a71d"
  Bluetooth_Base_UUID = "00000000-0000-1000-8000-00805f9b34fb"
  SDP_PROTOCOL_UUID16 = 1_u32
  UDP_PROTOCOL_UUID16 = 2_u32
  RFCOMM_PROTOCOL_UUID16 = 3_u32
  TCP_PROTOCOL_UUID16 = 4_u32
  TCSBIN_PROTOCOL_UUID16 = 5_u32
  TCSAT_PROTOCOL_UUID16 = 6_u32
  ATT_PROTOCOL_UUID16 = 7_u32
  OBEX_PROTOCOL_UUID16 = 8_u32
  IP_PROTOCOL_UUID16 = 9_u32
  FTP_PROTOCOL_UUID16 = 10_u32
  HTTP_PROTOCOL_UUID16 = 12_u32
  WSP_PROTOCOL_UUID16 = 14_u32
  BNEP_PROTOCOL_UUID16 = 15_u32
  UPNP_PROTOCOL_UUID16 = 16_u32
  HID_PROTOCOL_UUID16 = 17_u32
  HCCC_PROTOCOL_UUID16 = 18_u32
  HCDC_PROTOCOL_UUID16 = 20_u32
  HCN_PROTOCOL_UUID16 = 22_u32
  AVCTP_PROTOCOL_UUID16 = 23_u32
  AVDTP_PROTOCOL_UUID16 = 25_u32
  CMPT_PROTOCOL_UUID16 = 27_u32
  UDI_C_PLANE_PROTOCOL_UUID16 = 29_u32
  L2CAP_PROTOCOL_UUID16 = 256_u32
  ServiceDiscoveryServerServiceClassID_UUID16 = 4096_u32
  BrowseGroupDescriptorServiceClassID_UUID16 = 4097_u32
  PublicBrowseGroupServiceClassID_UUID16 = 4098_u32
  SerialPortServiceClassID_UUID16 = 4353_u32
  LANAccessUsingPPPServiceClassID_UUID16 = 4354_u32
  DialupNetworkingServiceClassID_UUID16 = 4355_u32
  IrMCSyncServiceClassID_UUID16 = 4356_u32
  OBEXObjectPushServiceClassID_UUID16 = 4357_u32
  OBEXFileTransferServiceClassID_UUID16 = 4358_u32
  IrMcSyncCommandServiceClassID_UUID16 = 4359_u32
  HeadsetServiceClassID_UUID16 = 4360_u32
  CordlessTelephonyServiceClassID_UUID16 = 4361_u32
  AudioSourceServiceClassID_UUID16 = 4362_u32
  AudioSinkServiceClassID_UUID16 = 4363_u32
  AVRemoteControlTargetServiceClassID_UUID16 = 4364_u32
  AVRemoteControlServiceClassID_UUID16 = 4366_u32
  AVRemoteControlControllerServiceClass_UUID16 = 4367_u32
  IntercomServiceClassID_UUID16 = 4368_u32
  FaxServiceClassID_UUID16 = 4369_u32
  HeadsetAudioGatewayServiceClassID_UUID16 = 4370_u32
  WAPServiceClassID_UUID16 = 4371_u32
  WAPClientServiceClassID_UUID16 = 4372_u32
  PANUServiceClassID_UUID16 = 4373_u32
  NAPServiceClassID_UUID16 = 4374_u32
  GNServiceClassID_UUID16 = 4375_u32
  DirectPrintingServiceClassID_UUID16 = 4376_u32
  ReferencePrintingServiceClassID_UUID16 = 4377_u32
  ImagingResponderServiceClassID_UUID16 = 4379_u32
  ImagingAutomaticArchiveServiceClassID_UUID16 = 4380_u32
  ImagingReferenceObjectsServiceClassID_UUID16 = 4381_u32
  HandsfreeServiceClassID_UUID16 = 4382_u32
  HandsfreeAudioGatewayServiceClassID_UUID16 = 4383_u32
  DirectPrintingReferenceObjectsServiceClassID_UUID16 = 4384_u32
  ReflectsUIServiceClassID_UUID16 = 4385_u32
  PrintingStatusServiceClassID_UUID16 = 4387_u32
  HumanInterfaceDeviceServiceClassID_UUID16 = 4388_u32
  HCRPrintServiceClassID_UUID16 = 4390_u32
  HCRScanServiceClassID_UUID16 = 4391_u32
  CommonISDNAccessServiceClassID_UUID16 = 4392_u32
  VideoConferencingGWServiceClassID_UUID16 = 4393_u32
  UDIMTServiceClassID_UUID16 = 4394_u32
  UDITAServiceClassID_UUID16 = 4395_u32
  AudioVideoServiceClassID_UUID16 = 4396_u32
  SimAccessServiceClassID_UUID16 = 4397_u32
  PhonebookAccessPceServiceClassID_UUID16 = 4398_u32
  PhonebookAccessPseServiceClassID_UUID16 = 4399_u32
  HeadsetHSServiceClassID_UUID16 = 4401_u32
  MessageAccessServerServiceClassID_UUID16 = 4402_u32
  MessageNotificationServerServiceClassID_UUID16 = 4403_u32
  GNSSServerServiceClassID_UUID16 = 4406_u32
  ThreeDimensionalDisplayServiceClassID_UUID16 = 4407_u32
  ThreeDimensionalGlassesServiceClassID_UUID16 = 4408_u32
  MPSServiceClassID_UUID16 = 4411_u32
  CTNAccessServiceClassID_UUID16 = 4412_u32
  CTNNotificationServiceClassID_UUID16 = 4413_u32
  PnPInformationServiceClassID_UUID16 = 4608_u32
  GenericNetworkingServiceClassID_UUID16 = 4609_u32
  GenericFileTransferServiceClassID_UUID16 = 4610_u32
  GenericAudioServiceClassID_UUID16 = 4611_u32
  GenericTelephonyServiceClassID_UUID16 = 4612_u32
  UPnpServiceClassID_UUID16 = 4613_u32
  UPnpIpServiceClassID_UUID16 = 4614_u32
  ESdpUpnpIpPanServiceClassID_UUID16 = 4864_u32
  ESdpUpnpIpLapServiceClassID_UUID16 = 4865_u32
  ESdpUpnpL2capServiceClassID_UUID16 = 4866_u32
  VideoSourceServiceClassID_UUID16 = 4867_u32
  VideoSinkServiceClassID_UUID16 = 4868_u32
  HealthDeviceProfileSourceServiceClassID_UUID16 = 5121_u32
  HealthDeviceProfileSinkServiceClassID_UUID16 = 5122_u32
  AdvancedAudioDistributionProfileID_UUID16 = 4365_u32
  ImagingServiceProfileID_UUID16 = 4378_u32
  BasicPrintingProfileID_UUID16 = 4386_u32
  HardcopyCableReplacementProfileID_UUID16 = 4389_u32
  PhonebookAccessProfileID_UUID16 = 4400_u32
  MessageAccessProfileID_UUID16 = 4404_u32
  GNSSProfileID_UUID16 = 4405_u32
  ThreeDimensionalSynchronizationProfileID_UUID16 = 4409_u32
  MPSProfileID_UUID16 = 4410_u32
  CTNProfileID_UUID16 = 4414_u32
  VideoDistributionProfileID_UUID16 = 4869_u32
  HealthDeviceProfileID_UUID16 = 5120_u32
  VideoConferencingServiceClassID_UUID16 = 4367_u32
  CommonISDNAccessServiceClass_UUID16 = 4392_u32
  VideoConferencingGWServiceClass_UUID16 = 4393_u32
  UDIMTServiceClass_UUID16 = 4394_u32
  UDITAServiceClass_UUID16 = 4395_u32
  AudioVideoServiceClass_UUID16 = 4396_u32
  CordlessServiceClassID_UUID16 = 4361_u32
  AudioSinkSourceServiceClassID_UUID16 = 4363_u32
  AdvancedAudioDistributionServiceClassID_UUID16 = 4365_u32
  ImagingServiceClassID_UUID16 = 4378_u32
  BasicPrintingServiceClassID_UUID16 = 4386_u32
  HardcopyCableReplacementServiceClassID_UUID16 = 4389_u32
  BTH_MAX_NAME_SIZE = 248_u32
  BTH_MAX_PIN_SIZE = 16_u32
  BTH_LINK_KEY_LENGTH = 16_u32
  BTH_MFG_ERICSSON = 0_u32
  BTH_MFG_NOKIA = 1_u32
  BTH_MFG_INTEL = 2_u32
  BTH_MFG_IBM = 3_u32
  BTH_MFG_TOSHIBA = 4_u32
  BTH_MFG_3COM = 5_u32
  BTH_MFG_MICROSOFT = 6_u32
  BTH_MFG_LUCENT = 7_u32
  BTH_MFG_MOTOROLA = 8_u32
  BTH_MFG_INFINEON = 9_u32
  BTH_MFG_CSR = 10_u32
  BTH_MFG_SILICONWAVE = 11_u32
  BTH_MFG_DIGIANSWER = 12_u32
  BTH_MFG_TI = 13_u32
  BTH_MFG_PARTHUS = 14_u32
  BTH_MFG_BROADCOM = 15_u32
  BTH_MFG_MITEL = 16_u32
  BTH_MFG_WIDCOMM = 17_u32
  BTH_MFG_ZEEVO = 18_u32
  BTH_MFG_ATMEL = 19_u32
  BTH_MFG_MITSIBUSHI = 20_u32
  BTH_MFG_RTX_TELECOM = 21_u32
  BTH_MFG_KC_TECHNOLOGY = 22_u32
  BTH_MFG_NEWLOGIC = 23_u32
  BTH_MFG_TRANSILICA = 24_u32
  BTH_MFG_ROHDE_SCHWARZ = 25_u32
  BTH_MFG_TTPCOM = 26_u32
  BTH_MFG_SIGNIA = 27_u32
  BTH_MFG_CONEXANT = 28_u32
  BTH_MFG_QUALCOMM = 29_u32
  BTH_MFG_INVENTEL = 30_u32
  BTH_MFG_AVM_BERLIN = 31_u32
  BTH_MFG_BANDSPEED = 32_u32
  BTH_MFG_MANSELLA = 33_u32
  BTH_MFG_NEC = 34_u32
  BTH_MFG_WAVEPLUS_TECHNOLOGY_CO = 35_u32
  BTH_MFG_ALCATEL = 36_u32
  BTH_MFG_PHILIPS_SEMICONDUCTOR = 37_u32
  BTH_MFG_C_TECHNOLOGIES = 38_u32
  BTH_MFG_OPEN_INTERFACE = 39_u32
  BTH_MFG_RF_MICRO_DEVICES = 40_u32
  BTH_MFG_HITACHI = 41_u32
  BTH_MFG_SYMBOL_TECHNOLOGIES = 42_u32
  BTH_MFG_TENOVIS = 43_u32
  BTH_MFG_MACRONIX_INTERNATIONAL = 44_u32
  BTH_MFG_MARVELL = 72_u32
  BTH_MFG_APPLE = 76_u32
  BTH_MFG_NORDIC_SEMICONDUCTORS_ASA = 89_u32
  BTH_MFG_ARUBA_NETWORKS = 283_u32
  BTH_MFG_INTERNAL_USE = 65535_u32
  SAP_BIT_OFFSET = 0_u32
  COD_FORMAT_BIT_OFFSET = 0_u32
  COD_MINOR_BIT_OFFSET = 2_u32
  COD_FORMAT_MASK = 3_u32
  COD_MINOR_MASK = 252_u32
  COD_MAJOR_MASK = 7936_u32
  COD_SERVICE_MASK = 16769024_u32
  COD_VERSION = 0_u32
  COD_SERVICE_LIMITED = 1_u32
  COD_SERVICE_POSITIONING = 8_u32
  COD_SERVICE_NETWORKING = 16_u32
  COD_SERVICE_RENDERING = 32_u32
  COD_SERVICE_CAPTURING = 64_u32
  COD_SERVICE_OBJECT_XFER = 128_u32
  COD_SERVICE_AUDIO = 256_u32
  COD_SERVICE_TELEPHONY = 512_u32
  COD_SERVICE_INFORMATION = 1024_u32
  COD_SERVICE_MAX_COUNT = 9_u32
  COD_MAJOR_MISCELLANEOUS = 0_u32
  COD_MAJOR_COMPUTER = 1_u32
  COD_MAJOR_PHONE = 2_u32
  COD_MAJOR_LAN_ACCESS = 3_u32
  COD_MAJOR_AUDIO = 4_u32
  COD_MAJOR_PERIPHERAL = 5_u32
  COD_MAJOR_IMAGING = 6_u32
  COD_MAJOR_WEARABLE = 7_u32
  COD_MAJOR_TOY = 8_u32
  COD_MAJOR_HEALTH = 9_u32
  COD_MAJOR_UNCLASSIFIED = 31_u32
  COD_COMPUTER_MINOR_UNCLASSIFIED = 0_u32
  COD_COMPUTER_MINOR_DESKTOP = 1_u32
  COD_COMPUTER_MINOR_SERVER = 2_u32
  COD_COMPUTER_MINOR_LAPTOP = 3_u32
  COD_COMPUTER_MINOR_HANDHELD = 4_u32
  COD_COMPUTER_MINOR_PALM = 5_u32
  COD_COMPUTER_MINOR_WEARABLE = 6_u32
  COD_PHONE_MINOR_UNCLASSIFIED = 0_u32
  COD_PHONE_MINOR_CELLULAR = 1_u32
  COD_PHONE_MINOR_CORDLESS = 2_u32
  COD_PHONE_MINOR_SMART = 3_u32
  COD_PHONE_MINOR_WIRED_MODEM = 4_u32
  COD_AUDIO_MINOR_UNCLASSIFIED = 0_u32
  COD_AUDIO_MINOR_HEADSET = 1_u32
  COD_AUDIO_MINOR_HANDS_FREE = 2_u32
  COD_AUDIO_MINOR_HEADSET_HANDS_FREE = 3_u32
  COD_AUDIO_MINOR_MICROPHONE = 4_u32
  COD_AUDIO_MINOR_LOUDSPEAKER = 5_u32
  COD_AUDIO_MINOR_HEADPHONES = 6_u32
  COD_AUDIO_MINOR_PORTABLE_AUDIO = 7_u32
  COD_AUDIO_MINOR_CAR_AUDIO = 8_u32
  COD_AUDIO_MINOR_SET_TOP_BOX = 9_u32
  COD_AUDIO_MINOR_HIFI_AUDIO = 10_u32
  COD_AUDIO_MINOR_VCR = 11_u32
  COD_AUDIO_MINOR_VIDEO_CAMERA = 12_u32
  COD_AUDIO_MINOR_CAMCORDER = 13_u32
  COD_AUDIO_MINOR_VIDEO_MONITOR = 14_u32
  COD_AUDIO_MINOR_VIDEO_DISPLAY_LOUDSPEAKER = 15_u32
  COD_AUDIO_MINOR_VIDEO_DISPLAY_CONFERENCING = 16_u32
  COD_AUDIO_MINOR_GAMING_TOY = 18_u32
  COD_PERIPHERAL_MINOR_KEYBOARD_MASK = 16_u32
  COD_PERIPHERAL_MINOR_POINTER_MASK = 32_u32
  COD_PERIPHERAL_MINOR_NO_CATEGORY = 0_u32
  COD_PERIPHERAL_MINOR_JOYSTICK = 1_u32
  COD_PERIPHERAL_MINOR_GAMEPAD = 2_u32
  COD_PERIPHERAL_MINOR_REMOTE_CONTROL = 3_u32
  COD_PERIPHERAL_MINOR_SENSING = 4_u32
  COD_IMAGING_MINOR_DISPLAY_MASK = 4_u32
  COD_IMAGING_MINOR_CAMERA_MASK = 8_u32
  COD_IMAGING_MINOR_SCANNER_MASK = 16_u32
  COD_IMAGING_MINOR_PRINTER_MASK = 32_u32
  COD_WEARABLE_MINOR_WRIST_WATCH = 1_u32
  COD_WEARABLE_MINOR_PAGER = 2_u32
  COD_WEARABLE_MINOR_JACKET = 3_u32
  COD_WEARABLE_MINOR_HELMET = 4_u32
  COD_WEARABLE_MINOR_GLASSES = 5_u32
  COD_TOY_MINOR_ROBOT = 1_u32
  COD_TOY_MINOR_VEHICLE = 2_u32
  COD_TOY_MINOR_DOLL_ACTION_FIGURE = 3_u32
  COD_TOY_MINOR_CONTROLLER = 4_u32
  COD_TOY_MINOR_GAME = 5_u32
  COD_HEALTH_MINOR_BLOOD_PRESSURE_MONITOR = 1_u32
  COD_HEALTH_MINOR_THERMOMETER = 2_u32
  COD_HEALTH_MINOR_WEIGHING_SCALE = 3_u32
  COD_HEALTH_MINOR_GLUCOSE_METER = 4_u32
  COD_HEALTH_MINOR_PULSE_OXIMETER = 5_u32
  COD_HEALTH_MINOR_HEART_PULSE_MONITOR = 6_u32
  COD_HEALTH_MINOR_HEALTH_DATA_DISPLAY = 7_u32
  COD_HEALTH_MINOR_STEP_COUNTER = 8_u32
  COD_LAN_ACCESS_BIT_OFFSET = 5_u32
  COD_LAN_MINOR_MASK = 28_u32
  COD_LAN_ACCESS_MASK = 224_u32
  COD_LAN_MINOR_UNCLASSIFIED = 0_u32
  COD_LAN_ACCESS_0_USED = 0_u32
  COD_LAN_ACCESS_17_USED = 1_u32
  COD_LAN_ACCESS_33_USED = 2_u32
  COD_LAN_ACCESS_50_USED = 3_u32
  COD_LAN_ACCESS_67_USED = 4_u32
  COD_LAN_ACCESS_83_USED = 5_u32
  COD_LAN_ACCESS_99_USED = 6_u32
  COD_LAN_ACCESS_FULL = 7_u32
  BTH_EIR_FLAGS_ID = 1_u32
  BTH_EIR_16_UUIDS_PARTIAL_ID = 2_u32
  BTH_EIR_16_UUIDS_COMPLETE_ID = 3_u32
  BTH_EIR_32_UUIDS_PARTIAL_ID = 4_u32
  BTH_EIR_32_UUIDS_COMPLETE_ID = 5_u32
  BTH_EIR_128_UUIDS_PARTIAL_ID = 6_u32
  BTH_EIR_128_UUIDS_COMPLETE_ID = 7_u32
  BTH_EIR_LOCAL_NAME_PARTIAL_ID = 8_u32
  BTH_EIR_LOCAL_NAME_COMPLETE_ID = 9_u32
  BTH_EIR_TX_POWER_LEVEL_ID = 10_u32
  BTH_EIR_OOB_OPT_DATA_LEN_ID = 11_u32
  BTH_EIR_OOB_BD_ADDR_ID = 12_u32
  BTH_EIR_OOB_COD_ID = 13_u32
  BTH_EIR_OOB_SP_HASH_ID = 14_u32
  BTH_EIR_OOB_SP_RANDOMIZER_ID = 15_u32
  BTH_EIR_MANUFACTURER_ID = 255_u32
  BTH_EIR_SIZE = 240_u32
  LAP_GIAC_VALUE = 10390323_u32
  LAP_LIAC_VALUE = 10390272_u32
  BTH_ADDR_IAC_FIRST = 10390272_u32
  BTH_ADDR_IAC_LAST = 10390335_u32
  BTH_ADDR_LIAC = 10390272_u32
  BTH_ADDR_GIAC = 10390323_u32
  BTH_ERROR_SUCCESS = 0_u32
  BTH_ERROR_UNKNOWN_HCI_COMMAND = 1_u32
  BTH_ERROR_NO_CONNECTION = 2_u32
  BTH_ERROR_HARDWARE_FAILURE = 3_u32
  BTH_ERROR_PAGE_TIMEOUT = 4_u32
  BTH_ERROR_AUTHENTICATION_FAILURE = 5_u32
  BTH_ERROR_KEY_MISSING = 6_u32
  BTH_ERROR_MEMORY_FULL = 7_u32
  BTH_ERROR_CONNECTION_TIMEOUT = 8_u32
  BTH_ERROR_MAX_NUMBER_OF_CONNECTIONS = 9_u32
  BTH_ERROR_MAX_NUMBER_OF_SCO_CONNECTIONS = 10_u32
  BTH_ERROR_ACL_CONNECTION_ALREADY_EXISTS = 11_u32
  BTH_ERROR_COMMAND_DISALLOWED = 12_u32
  BTH_ERROR_HOST_REJECTED_LIMITED_RESOURCES = 13_u32
  BTH_ERROR_HOST_REJECTED_SECURITY_REASONS = 14_u32
  BTH_ERROR_HOST_REJECTED_PERSONAL_DEVICE = 15_u32
  BTH_ERROR_HOST_TIMEOUT = 16_u32
  BTH_ERROR_UNSUPPORTED_FEATURE_OR_PARAMETER = 17_u32
  BTH_ERROR_INVALID_HCI_PARAMETER = 18_u32
  BTH_ERROR_REMOTE_USER_ENDED_CONNECTION = 19_u32
  BTH_ERROR_REMOTE_LOW_RESOURCES = 20_u32
  BTH_ERROR_REMOTE_POWERING_OFF = 21_u32
  BTH_ERROR_LOCAL_HOST_TERMINATED_CONNECTION = 22_u32
  BTH_ERROR_REPEATED_ATTEMPTS = 23_u32
  BTH_ERROR_PAIRING_NOT_ALLOWED = 24_u32
  BTH_ERROR_UKNOWN_LMP_PDU = 25_u32
  BTH_ERROR_UNSUPPORTED_REMOTE_FEATURE = 26_u32
  BTH_ERROR_SCO_OFFSET_REJECTED = 27_u32
  BTH_ERROR_SCO_INTERVAL_REJECTED = 28_u32
  BTH_ERROR_SCO_AIRMODE_REJECTED = 29_u32
  BTH_ERROR_INVALID_LMP_PARAMETERS = 30_u32
  BTH_ERROR_UNSPECIFIED_ERROR = 31_u32
  BTH_ERROR_UNSUPPORTED_LMP_PARM_VALUE = 32_u32
  BTH_ERROR_ROLE_CHANGE_NOT_ALLOWED = 33_u32
  BTH_ERROR_LMP_RESPONSE_TIMEOUT = 34_u32
  BTH_ERROR_LMP_TRANSACTION_COLLISION = 35_u32
  BTH_ERROR_LMP_PDU_NOT_ALLOWED = 36_u32
  BTH_ERROR_ENCRYPTION_MODE_NOT_ACCEPTABLE = 37_u32
  BTH_ERROR_UNIT_KEY_NOT_USED = 38_u32
  BTH_ERROR_QOS_IS_NOT_SUPPORTED = 39_u32
  BTH_ERROR_INSTANT_PASSED = 40_u32
  BTH_ERROR_PAIRING_WITH_UNIT_KEY_NOT_SUPPORTED = 41_u32
  BTH_ERROR_DIFFERENT_TRANSACTION_COLLISION = 42_u32
  BTH_ERROR_QOS_UNACCEPTABLE_PARAMETER = 44_u32
  BTH_ERROR_QOS_REJECTED = 45_u32
  BTH_ERROR_CHANNEL_CLASSIFICATION_NOT_SUPPORTED = 46_u32
  BTH_ERROR_INSUFFICIENT_SECURITY = 47_u32
  BTH_ERROR_PARAMETER_OUT_OF_MANDATORY_RANGE = 48_u32
  BTH_ERROR_ROLE_SWITCH_PENDING = 50_u32
  BTH_ERROR_RESERVED_SLOT_VIOLATION = 52_u32
  BTH_ERROR_ROLE_SWITCH_FAILED = 53_u32
  BTH_ERROR_EXTENDED_INQUIRY_RESPONSE_TOO_LARGE = 54_u32
  BTH_ERROR_SECURE_SIMPLE_PAIRING_NOT_SUPPORTED_BY_HOST = 55_u32
  BTH_ERROR_HOST_BUSY_PAIRING = 56_u32
  BTH_ERROR_CONNECTION_REJECTED_DUE_TO_NO_SUITABLE_CHANNEL_FOUND = 57_u32
  BTH_ERROR_CONTROLLER_BUSY = 58_u32
  BTH_ERROR_UNACCEPTABLE_CONNECTION_INTERVAL = 59_u32
  BTH_ERROR_DIRECTED_ADVERTISING_TIMEOUT = 60_u32
  BTH_ERROR_CONNECTION_TERMINATED_DUE_TO_MIC_FAILURE = 61_u32
  BTH_ERROR_CONNECTION_FAILED_TO_BE_ESTABLISHED = 62_u32
  BTH_ERROR_MAC_CONNECTION_FAILED = 63_u32
  BTH_ERROR_COARSE_CLOCK_ADJUSTMENT_REJECTED = 64_u32
  BTH_ERROR_TYPE_0_SUBMAP_NOT_DEFINED = 65_u32
  BTH_ERROR_UNKNOWN_ADVERTISING_IDENTIFIER = 66_u32
  BTH_ERROR_LIMIT_REACHED = 67_u32
  BTH_ERROR_OPERATION_CANCELLED_BY_HOST = 68_u32
  BTH_ERROR_PACKET_TOO_LONG = 69_u32
  BTH_ERROR_UNSPECIFIED = 255_u32
  L2CAP_MIN_MTU = 48_u32
  L2CAP_MAX_MTU = 65535_u32
  L2CAP_DEFAULT_MTU = 672_u32
  MAX_L2CAP_PING_DATA_LENGTH = 44_u32
  MAX_L2CAP_INFO_DATA_LENGTH = 44_u32
  BDIF_ADDRESS = 1_u32
  BDIF_COD = 2_u32
  BDIF_NAME = 4_u32
  BDIF_PAIRED = 8_u32
  BDIF_PERSONAL = 16_u32
  BDIF_CONNECTED = 32_u32
  BDIF_SHORT_NAME = 64_u32
  BDIF_VISIBLE = 128_u32
  BDIF_SSP_SUPPORTED = 256_u32
  BDIF_SSP_PAIRED = 512_u32
  BDIF_SSP_MITM_PROTECTED = 1024_u32
  BDIF_RSSI = 4096_u32
  BDIF_EIR = 8192_u32
  BDIF_BR = 16384_u32
  BDIF_LE = 32768_u32
  BDIF_LE_PAIRED = 65536_u32
  BDIF_LE_PERSONAL = 131072_u32
  BDIF_LE_MITM_PROTECTED = 262144_u32
  BDIF_LE_PRIVACY_ENABLED = 524288_u32
  BDIF_LE_RANDOM_ADDRESS_TYPE = 1048576_u32
  BDIF_LE_DISCOVERABLE = 2097152_u32
  BDIF_LE_NAME = 4194304_u32
  BDIF_LE_VISIBLE = 8388608_u32
  BDIF_LE_CONNECTED = 16777216_u32
  BDIF_LE_CONNECTABLE = 33554432_u32
  BDIF_CONNECTION_INBOUND = 67108864_u32
  BDIF_BR_SECURE_CONNECTION_PAIRED = 134217728_u32
  BDIF_LE_SECURE_CONNECTION_PAIRED = 268435456_u32
  BDIF_DEBUGKEY = 536870912_u32
  BDIF_LE_DEBUGKEY = 1073741824_u32
  BDIF_TX_POWER = 2147483648_u32
  HCI_CONNECTION_TYPE_ACL = 1_u32
  HCI_CONNECTION_TYPE_SCO = 2_u32
  HCI_CONNECTION_TYPE_LE = 3_u32
  HCI_CONNNECTION_TYPE_ACL = 1_u32
  HCI_CONNNECTION_TYPE_SCO = 2_u32
  BTH_MAX_SERVICE_NAME_SIZE = 256_u32
  MAX_UUIDS_IN_QUERY = 12_u32
  BTH_VID_DEFAULT_VALUE = 65535_u32
  SDP_ERROR_INVALID_SDP_VERSION = 1_u32
  SDP_ERROR_INVALID_RECORD_HANDLE = 2_u32
  SDP_ERROR_INVALID_REQUEST_SYNTAX = 3_u32
  SDP_ERROR_INVALID_PDU_SIZE = 4_u32
  SDP_ERROR_INVALID_CONTINUATION_STATE = 5_u32
  SDP_ERROR_INSUFFICIENT_RESOURCES = 6_u32
  SDP_ATTRIB_RECORD_HANDLE = 0_u32
  SDP_ATTRIB_CLASS_ID_LIST = 1_u32
  SDP_ATTRIB_RECORD_STATE = 2_u32
  SDP_ATTRIB_SERVICE_ID = 3_u32
  SDP_ATTRIB_PROTOCOL_DESCRIPTOR_LIST = 4_u32
  SDP_ATTRIB_BROWSE_GROUP_LIST = 5_u32
  SDP_ATTRIB_LANG_BASE_ATTRIB_ID_LIST = 6_u32
  SDP_ATTRIB_INFO_TIME_TO_LIVE = 7_u32
  SDP_ATTRIB_AVAILABILITY = 8_u32
  SDP_ATTRIB_PROFILE_DESCRIPTOR_LIST = 9_u32
  SDP_ATTRIB_DOCUMENTATION_URL = 10_u32
  SDP_ATTRIB_CLIENT_EXECUTABLE_URL = 11_u32
  SDP_ATTRIB_ICON_URL = 12_u32
  SDP_ATTRIB_ADDITIONAL_PROTOCOL_DESCRIPTOR_LIST = 13_u32
  SDP_ATTRIB_PROFILE_SPECIFIC = 512_u32
  LANG_BASE_LANGUAGE_INDEX = 0_u32
  LANG_BASE_ENCODING_INDEX = 1_u32
  LANG_BASE_OFFSET_INDEX = 2_u32
  LANG_DEFAULT_ID = 256_u32
  LANGUAGE_EN_US = 25966_u32
  ENCODING_UTF_8 = 106_u32
  STRING_NAME_OFFSET = 0_u32
  STRING_DESCRIPTION_OFFSET = 1_u32
  STRING_PROVIDER_NAME_OFFSET = 2_u32
  SDP_ATTRIB_SDP_VERSION_NUMBER_LIST = 512_u32
  SDP_ATTRIB_SDP_DATABASE_STATE = 513_u32
  SDP_ATTRIB_BROWSE_GROUP_ID = 512_u32
  SDP_ATTRIB_CORDLESS_EXTERNAL_NETWORK = 769_u32
  SDP_ATTRIB_FAX_CLASS_1_SUPPORT = 770_u32
  SDP_ATTRIB_FAX_CLASS_2_0_SUPPORT = 771_u32
  SDP_ATTRIB_FAX_CLASS_2_SUPPORT = 772_u32
  SDP_ATTRIB_FAX_AUDIO_FEEDBACK_SUPPORT = 773_u32
  SDP_ATTRIB_HEADSET_REMOTE_AUDIO_VOLUME_CONTROL = 770_u32
  SDP_ATTRIB_LAN_LPSUBNET = 512_u32
  SDP_ATTRIB_OBJECT_PUSH_SUPPORTED_FORMATS_LIST = 771_u32
  SDP_ATTRIB_SYNCH_SUPPORTED_DATA_STORES_LIST = 769_u32
  SDP_ATTRIB_SERVICE_VERSION = 768_u32
  SDP_ATTRIB_PAN_NETWORK_ADDRESS = 774_u32
  SDP_ATTRIB_PAN_WAP_GATEWAY = 775_u32
  SDP_ATTRIB_PAN_HOME_PAGE_URL = 776_u32
  SDP_ATTRIB_PAN_WAP_STACK_TYPE = 777_u32
  SDP_ATTRIB_PAN_SECURITY_DESCRIPTION = 778_u32
  SDP_ATTRIB_PAN_NET_ACCESS_TYPE = 779_u32
  SDP_ATTRIB_PAN_MAX_NET_ACCESS_RATE = 780_u32
  SDP_ATTRIB_IMAGING_SUPPORTED_CAPABILITIES = 784_u32
  SDP_ATTRIB_IMAGING_SUPPORTED_FEATURES = 785_u32
  SDP_ATTRIB_IMAGING_SUPPORTED_FUNCTIONS = 786_u32
  SDP_ATTRIB_IMAGING_TOTAL_DATA_CAPACITY = 787_u32
  SDP_ATTRIB_DI_SPECIFICATION_ID = 512_u32
  SDP_ATTRIB_DI_VENDOR_ID = 513_u32
  SDP_ATTRIB_DI_PRODUCT_ID = 514_u32
  SDP_ATTRIB_DI_VERSION = 515_u32
  SDP_ATTRIB_DI_PRIMARY_RECORD = 516_u32
  SDP_ATTRIB_DI_VENDOR_ID_SOURCE = 517_u32
  SDP_ATTRIB_HID_DEVICE_RELEASE_NUMBER = 512_u32
  SDP_ATTRIB_HID_PARSER_VERSION = 513_u32
  SDP_ATTRIB_HID_DEVICE_SUBCLASS = 514_u32
  SDP_ATTRIB_HID_COUNTRY_CODE = 515_u32
  SDP_ATTRIB_HID_VIRTUAL_CABLE = 516_u32
  SDP_ATTRIB_HID_RECONNECT_INITIATE = 517_u32
  SDP_ATTRIB_HID_DESCRIPTOR_LIST = 518_u32
  SDP_ATTRIB_HID_LANG_ID_BASE_LIST = 519_u32
  SDP_ATTRIB_HID_SDP_DISABLE = 520_u32
  SDP_ATTRIB_HID_BATTERY_POWER = 521_u32
  SDP_ATTRIB_HID_REMOTE_WAKE = 522_u32
  SDP_ATTRIB_HID_PROFILE_VERSION = 523_u32
  SDP_ATTRIB_HID_SUPERVISION_TIMEOUT = 524_u32
  SDP_ATTRIB_HID_NORMALLY_CONNECTABLE = 525_u32
  SDP_ATTRIB_HID_BOOT_DEVICE = 526_u32
  SDP_ATTRIB_HID_SSR_HOST_MAX_LATENCY = 527_u32
  SDP_ATTRIB_HID_SSR_HOST_MIN_TIMEOUT = 528_u32
  SDP_ATTRIB_A2DP_SUPPORTED_FEATURES = 785_u32
  SDP_ATTRIB_AVRCP_SUPPORTED_FEATURES = 785_u32
  SDP_ATTRIB_HFP_SUPPORTED_FEATURES = 785_u32
  AVRCP_SUPPORTED_FEATURES_CATEGORY_1 = 1_u32
  AVRCP_SUPPORTED_FEATURES_CATEGORY_2 = 2_u32
  AVRCP_SUPPORTED_FEATURES_CATEGORY_3 = 4_u32
  AVRCP_SUPPORTED_FEATURES_CATEGORY_4 = 8_u32
  AVRCP_SUPPORTED_FEATURES_CT_BROWSING = 64_u32
  AVRCP_SUPPORTED_FEATURES_CT_COVER_ART_IMAGE_PROPERTIES = 128_u32
  AVRCP_SUPPORTED_FEATURES_CT_COVER_ART_IMAGE = 256_u32
  AVRCP_SUPPORTED_FEATURES_CT_COVER_ART_LINKED_THUMBNAIL = 512_u32
  AVRCP_SUPPORTED_FEATURES_TG_PLAYER_APPLICATION_SETTINGS = 16_u32
  AVRCP_SUPPORTED_FEATURES_TG_GROUP_NAVIGATION = 32_u32
  AVRCP_SUPPORTED_FEATURES_TG_BROWSING = 64_u32
  AVRCP_SUPPORTED_FEATURES_TG_MULTIPLE_PLAYER_APPLICATIONS = 128_u32
  AVRCP_SUPPORTED_FEATURES_TG_COVER_ART = 256_u32
  A2DP_SINK_SUPPORTED_FEATURES_HEADPHONE = 1_u32
  A2DP_SINK_SUPPORTED_FEATURES_SPEAKER = 2_u32
  A2DP_SINK_SUPPORTED_FEATURES_RECORDER = 4_u32
  A2DP_SINK_SUPPORTED_FEATURES_AMPLIFIER = 8_u32
  A2DP_SOURCE_SUPPORTED_FEATURES_PLAYER = 1_u32
  A2DP_SOURCE_SUPPORTED_FEATURES_MICROPHONE = 2_u32
  A2DP_SOURCE_SUPPORTED_FEATURES_TUNER = 4_u32
  A2DP_SOURCE_SUPPORTED_FEATURES_MIXER = 8_u32
  CORDLESS_EXTERNAL_NETWORK_PSTN = 1_u32
  CORDLESS_EXTERNAL_NETWORK_ISDN = 2_u32
  CORDLESS_EXTERNAL_NETWORK_GSM = 3_u32
  CORDLESS_EXTERNAL_NETWORK_CDMA = 4_u32
  CORDLESS_EXTERNAL_NETWORK_ANALOG_CELLULAR = 5_u32
  CORDLESS_EXTERNAL_NETWORK_PACKET_SWITCHED = 6_u32
  CORDLESS_EXTERNAL_NETWORK_OTHER = 7_u32
  OBJECT_PUSH_FORMAT_VCARD_2_1 = 1_u32
  OBJECT_PUSH_FORMAT_VCARD_3_0 = 2_u32
  OBJECT_PUSH_FORMAT_VCAL_1_0 = 3_u32
  OBJECT_PUSH_FORMAT_ICAL_2_0 = 4_u32
  OBJECT_PUSH_FORMAT_VNOTE = 5_u32
  OBJECT_PUSH_FORMAT_VMESSAGE = 6_u32
  OBJECT_PUSH_FORMAT_ANY = 255_u32
  SYNCH_DATA_STORE_PHONEBOOK = 1_u32
  SYNCH_DATA_STORE_CALENDAR = 3_u32
  SYNCH_DATA_STORE_NOTES = 5_u32
  SYNCH_DATA_STORE_MESSAGES = 6_u32
  DI_VENDOR_ID_SOURCE_BLUETOOTH_SIG = 1_u32
  DI_VENDOR_ID_SOURCE_USB_IF = 2_u32
  PSM_SDP = 1_u32
  PSM_RFCOMM = 3_u32
  PSM_TCS_BIN = 5_u32
  PSM_TCS_BIN_CORDLESS = 7_u32
  PSM_BNEP = 15_u32
  PSM_HID_CONTROL = 17_u32
  PSM_HID_INTERRUPT = 19_u32
  PSM_UPNP = 21_u32
  PSM_AVCTP = 23_u32
  PSM_AVDTP = 25_u32
  PSM_AVCTP_BROWSE = 27_u32
  PSM_UDI_C_PLANE = 29_u32
  PSM_ATT = 31_u32
  PSM_3DSP = 33_u32
  PSM_LE_IPSP = 35_u32
  STR_ADDR_FMTA = "(%02x:%02x:%02x:%02x:%02x:%02x)"
  STR_ADDR_FMTW = "(%02x:%02x:%02x:%02x:%02x:%02x)"
  STR_ADDR_SHORT_FMTA = "%04x%08x"
  STR_ADDR_SHORT_FMTW = "%04x%08x"
  STR_USBHCI_CLASS_HARDWAREIDA = "USB\\Class_E0&SubClass_01&Prot_01"
  STR_USBHCI_CLASS_HARDWAREIDW = "USB\\Class_E0&SubClass_01&Prot_01"
  STR_ADDR_FMT = "(%02x:%02x:%02x:%02x:%02x:%02x)"
  STR_ADDR_SHORT_FMT = "%04x%08x"
  STR_USBHCI_CLASS_HARDWAREID = "USB\\Class_E0&SubClass_01&Prot_01"
  BTH_IOCTL_BASE = 0_u32
  SDP_CONNECT_CACHE = 1_u32
  SDP_CONNECT_ALLOW_PIN = 2_u32
  SDP_REQUEST_TO_DEFAULT = 0_u32
  SDP_REQUEST_TO_MIN = 10_u32
  SDP_REQUEST_TO_MAX = 45_u32
  SERVICE_OPTION_DO_NOT_PUBLISH = 2_u32
  SERVICE_OPTION_NO_PUBLIC_BROWSE = 4_u32
  SERVICE_OPTION_DO_NOT_PUBLISH_EIR = 8_u32
  SERVICE_SECURITY_USE_DEFAULTS = 0_u32
  SERVICE_SECURITY_NONE = 1_u32
  SERVICE_SECURITY_AUTHORIZE = 2_u32
  SERVICE_SECURITY_AUTHENTICATE = 4_u32
  SERVICE_SECURITY_ENCRYPT_REQUIRED = 16_u32
  SERVICE_SECURITY_ENCRYPT_OPTIONAL = 32_u32
  SERVICE_SECURITY_DISABLED = 268435456_u32
  SERVICE_SECURITY_NO_ASK = 536870912_u32
  SDP_SEARCH_NO_PARSE_CHECK = 1_u32
  SDP_SEARCH_NO_FORMAT_CHECK = 2_u32
  BTH_HOST_FEATURE_ENHANCED_RETRANSMISSION_MODE = 1_u64
  BTH_HOST_FEATURE_STREAMING_MODE = 2_u64
  BTH_HOST_FEATURE_LOW_ENERGY = 4_u64
  BTH_HOST_FEATURE_SCO_HCI = 8_u64
  BTH_HOST_FEATURE_SCO_HCIBYPASS = 16_u64
  BLUETOOTH_MAX_NAME_SIZE = 248_u32
  BLUETOOTH_MAX_PASSKEY_SIZE = 16_u32
  BLUETOOTH_MAX_PASSKEY_BUFFER_SIZE = 17_u32
  BLUETOOTH_MAX_SERVICE_NAME_SIZE = 256_u32
  BLUETOOTH_DEVICE_NAME_SIZE = 256_u32
  BLUETOOTH_SERVICE_DISABLE = 0_u32
  BLUETOOTH_SERVICE_ENABLE = 1_u32
  GUID_BLUETOOTHLE_DEVICE_INTERFACE = "781aee18-7733-4ce4-add0-91f41c67b592"
  GUID_BLUETOOTH_GATT_SERVICE_DEVICE_INTERFACE = "6e3bb679-4372-40c8-9eaa-4509df260cd8"
  BTH_LE_ATT_BLUETOOTH_BASE_GUID = "00000000-0000-1000-8000-00805f9b34fb"
  BTH_LE_SERVICE_GAP = 6144_u32
  BTH_LE_SERVICE_GATT = 6145_u32
  BTH_LE_GATT_ATTRIBUTE_TYPE_PRIMARY_SERVICE = 10240_u32
  BTH_LE_GATT_ATTRIBUTE_TYPE_SECONDARY_SERVICE = 10241_u32
  BTH_LE_GATT_ATTRIBUTE_TYPE_INCLUDE = 10242_u32
  BTH_LE_GATT_ATTRIBUTE_TYPE_CHARACTERISTIC = 10243_u32
  BTH_LE_GATT_CHARACTERISTIC_DESCRIPTOR_EXTENDED_PROPERTIES = 10496_u32
  BTH_LE_GATT_CHARACTERISTIC_DESCRIPTOR_USER_DESCRIPTION = 10497_u32
  BTH_LE_GATT_CHARACTERISTIC_DESCRIPTOR_CLIENT_CONFIGURATION = 10498_u32
  BTH_LE_GATT_CHARACTERISTIC_DESCRIPTOR_SERVER_CONFIGURATION = 10499_u32
  BTH_LE_GATT_CHARACTERISTIC_DESCRIPTOR_FORMAT = 10500_u32
  BTH_LE_GATT_CHARACTERISTIC_DESCRIPTOR_AGGREGATE_FORMAT = 10501_u32
  BTH_LE_GATT_CHARACTERISTIC_TYPE_DEVICE_NAME = 10752_u32
  BTH_LE_GATT_CHARACTERISTIC_TYPE_APPEARANCE = 10753_u32
  BTH_LE_GATT_CHARACTERISTIC_TYPE_PERIPHERAL_PRIVACY_FLAG = 10754_u32
  BTH_LE_GATT_CHARACTERISTIC_TYPE_RECONNECTION_ADDRESS = 10755_u32
  BTH_LE_GATT_CHARACTERISTIC_TYPE_PERIPHERAL_PREFERED_CONNECTION_PARAMETER = 10756_u32
  BTH_LE_GATT_CHARACTERISTIC_TYPE_SERVICE_CHANGED = 10757_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_OFFSET = 6_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_MASK = 1023_u32
  BTH_LE_GAP_APPEARANCE_SUB_CATEGORY_MASK = 63_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_UNCATEGORIZED = 0_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_PHONE = 1_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_COMPUTER = 2_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_WATCH = 3_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_CLOCK = 4_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_DISPLAY = 5_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_REMOTE_CONTROL = 6_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_EYE_GLASSES = 7_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_TAG = 8_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_KEYRING = 9_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_MEDIA_PLAYER = 10_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_BARCODE_SCANNER = 11_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_THERMOMETER = 12_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_HEART_RATE = 13_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_BLOOD_PRESSURE = 14_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_HID = 15_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_GLUCOSE_METER = 16_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_RUNNING_WALKING_SENSOR = 17_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_CYCLING = 18_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_PLUSE_OXIMETER = 49_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_WEIGHT_SCALE = 50_u32
  BTH_LE_GAP_APPEARANCE_CATEGORY_OUTDOOR_SPORTS_ACTIVITY = 81_u32
  BTH_LE_GAP_APPEARANCE_SUBCATEGORY_GENERIC = 0_u32
  BTH_LE_GAP_APPEARANCE_WATCH_SUBCATEGORY_SPORTS_WATCH = 1_u32
  BTH_LE_GAP_APPEARANCE_THERMOMETER_SUBCATEGORY_EAR = 1_u32
  BTH_LE_GAP_APPEARANCE_HEART_RATE_SUBCATEGORY_HEART_RATE_BELT = 1_u32
  BTH_LE_GAP_APPEARANCE_BLOOD_PRESSURE_SUBCATEGORY_ARM = 1_u32
  BTH_LE_GAP_APPEARANCE_BLOOD_PRESSURE_SUBCATEGORY_WRIST = 2_u32
  BTH_LE_GAP_APPEARANCE_HID_SUBCATEGORY_KEYBOARD = 1_u32
  BTH_LE_GAP_APPEARANCE_HID_SUBCATEGORY_MOUSE = 2_u32
  BTH_LE_GAP_APPEARANCE_HID_SUBCATEGORY_JOYSTICK = 3_u32
  BTH_LE_GAP_APPEARANCE_HID_SUBCATEGORY_GAMEPAD = 4_u32
  BTH_LE_GAP_APPEARANCE_HID_SUBCATEGORY_DIGITIZER_TABLET = 5_u32
  BTH_LE_GAP_APPEARANCE_HID_SUBCATEGORY_CARD_READER = 6_u32
  BTH_LE_GAP_APPEARANCE_HID_SUBCATEGORY_DIGITAL_PEN = 7_u32
  BTH_LE_GAP_APPEARANCE_HID_SUBCATEGORY_BARCODE_SCANNER = 8_u32
  BTH_LE_GAP_APPEARANCE_RUNNING_WALKING_SENSOR_SUBCATEGORY_IN_SHOE = 1_u32
  BTH_LE_GAP_APPEARANCE_RUNNING_WALKING_SENSOR_SUBCATEGORY_ON_SHOE = 2_u32
  BTH_LE_GAP_APPEARANCE_RUNNING_WALKING_SENSOR_SUBCATEGORY_ON_HIP = 3_u32
  BTH_LE_GAP_APPEARANCE_CYCLING_SUBCATEGORY_CYCLING_COMPUTER = 1_u32
  BTH_LE_GAP_APPEARANCE_CYCLING_SUBCATEGORY_SPEED_SENSOR = 2_u32
  BTH_LE_GAP_APPEARANCE_CYCLING_SUBCATEGORY_CADENCE_SENSOR = 3_u32
  BTH_LE_GAP_APPEARANCE_CYCLING_SUBCATEGORY_POWER_SENSOR = 4_u32
  BTH_LE_GAP_APPEARANCE_CYCLING_SUBCATEGORY_SPEED_AND_CADENCE_SENSOR = 5_u32
  BTH_LE_GAP_APPEARANCE_PULSE_OXIMETER_SUBCATEGORY_FINGERTIP = 1_u32
  BTH_LE_GAP_APPEARANCE_PULSE_OXIMETER_SUBCATEGORY_WRIST_WORN = 2_u32
  BTH_LE_GAP_APPEARANCE_OUTDOOR_SPORTS_ACTIVITY_SUBCATEGORY_LOCATION_DISPLAY_DEVICE = 1_u32
  BTH_LE_GAP_APPEARANCE_OUTDOOR_SPORTS_ACTIVITY_SUBCATEGORY_LOCATION_NAVIGATION_DISPLAY_DEVICE = 2_u32
  BTH_LE_GAP_APPEARANCE_OUTDOOR_SPORTS_ACTIVITY_SUBCATEGORY_LOCATION_POD = 3_u32
  BTH_LE_GAP_APPEARANCE_OUTDOOR_SPORTS_ACTIVITY_SUBCATEGORY_LOCATION_NAVIGATION_POD = 4_u32
  BTH_LE_GATT_DEFAULT_MAX_INCLUDED_SERVICES_DEPTH = 3_u32
  BTH_LE_ATT_TRANSACTION_TIMEOUT = 30_u32
  BTH_LE_ATT_MAX_VALUE_SIZE = 512_u32
  BTH_LE_ATT_CID = 4_u32
  BTHLEENUM_ATT_MTU_MIN = 23_u32
  BTHLEENUM_ATT_MTU_MAX = 65535_u32
  BTHLEENUM_ATT_MTU_DEFAULT = 23_u32
  BTHLEENUM_ATT_MTU_INITIAL_NEGOTIATION = 525_u32
  BTH_LE_ERROR_INVALID_HANDLE = 1_u32
  BTH_LE_ERROR_READ_NOT_PERMITTED = 2_u32
  BTH_LE_ERROR_WRITE_NOT_PERMITTED = 3_u32
  BTH_LE_ERROR_INVALID_PDU = 4_u32
  BTH_LE_ERROR_INSUFFICIENT_AUTHENTICATION = 5_u32
  BTH_LE_ERROR_REQUEST_NOT_SUPPORTED = 6_u32
  BTH_LE_ERROR_INVALID_OFFSET = 7_u32
  BTH_LE_ERROR_INSUFFICIENT_AUTHORIZATION = 8_u32
  BTH_LE_ERROR_PREPARE_QUEUE_FULL = 9_u32
  BTH_LE_ERROR_ATTRIBUTE_NOT_FOUND = 10_u32
  BTH_LE_ERROR_ATTRIBUTE_NOT_LONG = 11_u32
  BTH_LE_ERROR_INSUFFICIENT_ENCRYPTION_KEY_SIZE = 12_u32
  BTH_LE_ERROR_INVALID_ATTRIBUTE_VALUE_LENGTH = 13_u32
  BTH_LE_ERROR_UNLIKELY = 14_u32
  BTH_LE_ERROR_INSUFFICIENT_ENCRYPTION = 15_u32
  BTH_LE_ERROR_UNSUPPORTED_GROUP_TYPE = 16_u32
  BTH_LE_ERROR_INSUFFICIENT_RESOURCES = 17_u32
  BTH_LE_ERROR_UNKNOWN = 4096_u32
  BLUETOOTH_GATT_FLAG_NONE = 0_u32
  BLUETOOTH_GATT_FLAG_CONNECTION_ENCRYPTED = 1_u32
  BLUETOOTH_GATT_FLAG_CONNECTION_AUTHENTICATED = 2_u32
  BLUETOOTH_GATT_FLAG_FORCE_READ_FROM_DEVICE = 4_u32
  BLUETOOTH_GATT_FLAG_FORCE_READ_FROM_CACHE = 8_u32
  BLUETOOTH_GATT_FLAG_SIGNED_WRITE = 16_u32
  BLUETOOTH_GATT_FLAG_WRITE_WITHOUT_RESPONSE = 32_u32
  BLUETOOTH_GATT_FLAG_RETURN_ALL = 64_u32
  BT_PORT_MIN = 1_u32
  BT_PORT_MAX = 65535_u32
  BT_PORT_DYN_FIRST = 4097_u32
  AF_BTH = 32_u16
  PF_BTH = 32_u16
  NS_BTH = 16_u32
  SVCID_BTH_PROVIDER = "06aa63e0-7d60-41ff-afb2-3ee6d2d9392d"
  BTH_ADDR_STRING_SIZE = 12_u32
  BTHPROTO_RFCOMM = 3_u32
  BTHPROTO_L2CAP = 256_u32
  SOL_RFCOMM = 3_u32
  SOL_L2CAP = 256_u32
  SOL_SDP = 257_u32
  SO_BTH_AUTHENTICATE = 2147483649_u32
  SO_BTH_ENCRYPT = 2_u32
  SO_BTH_MTU = 2147483655_u32
  SO_BTH_MTU_MAX = 2147483656_u32
  SO_BTH_MTU_MIN = 2147483658_u32
  RFCOMM_MAX_MTU = 1011_u32
  RFCOMM_MIN_MTU = 23_u32
  BTH_SDP_VERSION = 1_u32
  SDP_DEFAULT_INQUIRY_SECONDS = 6_u32
  SDP_MAX_INQUIRY_SECONDS = 60_u32
  SDP_DEFAULT_INQUIRY_MAX_RESPONSES = 255_u32
  SDP_SERVICE_SEARCH_REQUEST = 1_u32
  SDP_SERVICE_ATTRIBUTE_REQUEST = 2_u32
  SDP_SERVICE_SEARCH_ATTRIBUTE_REQUEST = 3_u32
  BTHNS_RESULT_DEVICE_CONNECTED = 65536_u32
  BTHNS_RESULT_DEVICE_REMEMBERED = 131072_u32
  BTHNS_RESULT_DEVICE_AUTHENTICATED = 262144_u32
  RLS_ERROR = 1_u32
  RLS_OVERRUN = 2_u32
  RLS_PARITY = 4_u32
  RLS_FRAMING = 8_u32
  RPN_BAUD_2400 = 0_u32
  RPN_BAUD_4800 = 1_u32
  RPN_BAUD_7200 = 2_u32
  RPN_BAUD_9600 = 3_u32
  RPN_BAUD_19200 = 4_u32
  RPN_BAUD_38400 = 5_u32
  RPN_BAUD_57600 = 6_u32
  RPN_BAUD_115200 = 7_u32
  RPN_BAUD_230400 = 8_u32
  RPN_DATA_5 = 0_u32
  RPN_DATA_6 = 1_u32
  RPN_DATA_7 = 2_u32
  RPN_DATA_8 = 3_u32
  RPN_STOP_1 = 0_u32
  RPN_STOP_1_5 = 4_u32
  RPN_PARITY_NONE = 0_u32
  RPN_PARITY_ODD = 8_u32
  RPN_PARITY_EVEN = 24_u32
  RPN_PARITY_MARK = 40_u32
  RPN_PARITY_SPACE = 56_u32
  RPN_FLOW_X_IN = 1_u32
  RPN_FLOW_X_OUT = 2_u32
  RPN_FLOW_RTR_IN = 4_u32
  RPN_FLOW_RTR_OUT = 8_u32
  RPN_FLOW_RTC_IN = 16_u32
  RPN_FLOW_RTC_OUT = 32_u32
  RPN_PARAM_BAUD = 1_u32
  RPN_PARAM_DATA = 2_u32
  RPN_PARAM_STOP = 4_u32
  RPN_PARAM_PARITY = 8_u32
  RPN_PARAM_P_TYPE = 16_u32
  RPN_PARAM_XON = 32_u32
  RPN_PARAM_XOFF = 64_u32
  RPN_PARAM_X_IN = 1_u32
  RPN_PARAM_X_OUT = 2_u32
  RPN_PARAM_RTR_IN = 4_u32
  RPN_PARAM_RTR_OUT = 8_u32
  RPN_PARAM_RTC_IN = 16_u32
  RPN_PARAM_RTC_OUT = 32_u32
  RFCOMM_CMD_NONE = 0_u32
  RFCOMM_CMD_MSC = 1_u32
  RFCOMM_CMD_RLS = 2_u32
  RFCOMM_CMD_RPN = 3_u32
  RFCOMM_CMD_RPN_REQUEST = 4_u32
  RFCOMM_CMD_RPN_RESPONSE = 5_u32

  enum NodeContainerType
    NodeContainerTypeSequence = 0_i32
    NodeContainerTypeAlternative = 1_i32
  end
  enum SDP_TYPE
    SDP_TYPE_NIL = 0_i32
    SDP_TYPE_UINT = 1_i32
    SDP_TYPE_INT = 2_i32
    SDP_TYPE_UUID = 3_i32
    SDP_TYPE_STRING = 4_i32
    SDP_TYPE_BOOLEAN = 5_i32
    SDP_TYPE_SEQUENCE = 6_i32
    SDP_TYPE_ALTERNATIVE = 7_i32
    SDP_TYPE_URL = 8_i32
    SDP_TYPE_CONTAINER = 32_i32
  end
  enum SDP_SPECIFICTYPE
    SDP_ST_NONE = 0_i32
    SDP_ST_UINT8 = 16_i32
    SDP_ST_UINT16 = 272_i32
    SDP_ST_UINT32 = 528_i32
    SDP_ST_UINT64 = 784_i32
    SDP_ST_UINT128 = 1040_i32
    SDP_ST_INT8 = 32_i32
    SDP_ST_INT16 = 288_i32
    SDP_ST_INT32 = 544_i32
    SDP_ST_INT64 = 800_i32
    SDP_ST_INT128 = 1056_i32
    SDP_ST_UUID16 = 304_i32
    SDP_ST_UUID32 = 544_i32
    SDP_ST_UUID128 = 1072_i32
  end
  enum IO_CAPABILITY
    IoCaps_DisplayOnly = 0_i32
    IoCaps_DisplayYesNo = 1_i32
    IoCaps_KeyboardOnly = 2_i32
    IoCaps_NoInputNoOutput = 3_i32
    IoCaps_Undefined = 255_i32
  end
  enum AUTHENTICATION_REQUIREMENTS
    MITMProtectionNotRequired = 0_i32
    MITMProtectionRequired = 1_i32
    MITMProtectionNotRequiredBonding = 2_i32
    MITMProtectionRequiredBonding = 3_i32
    MITMProtectionNotRequiredGeneralBonding = 4_i32
    MITMProtectionRequiredGeneralBonding = 5_i32
    MITMProtectionNotDefined = 255_i32
  end
  enum BLUETOOTH_AUTHENTICATION_METHOD
    BLUETOOTH_AUTHENTICATION_METHOD_LEGACY = 1_i32
    BLUETOOTH_AUTHENTICATION_METHOD_OOB = 2_i32
    BLUETOOTH_AUTHENTICATION_METHOD_NUMERIC_COMPARISON = 3_i32
    BLUETOOTH_AUTHENTICATION_METHOD_PASSKEY_NOTIFICATION = 4_i32
    BLUETOOTH_AUTHENTICATION_METHOD_PASSKEY = 5_i32
  end
  enum BLUETOOTH_IO_CAPABILITY
    BLUETOOTH_IO_CAPABILITY_DISPLAYONLY = 0_i32
    BLUETOOTH_IO_CAPABILITY_DISPLAYYESNO = 1_i32
    BLUETOOTH_IO_CAPABILITY_KEYBOARDONLY = 2_i32
    BLUETOOTH_IO_CAPABILITY_NOINPUTNOOUTPUT = 3_i32
    BLUETOOTH_IO_CAPABILITY_UNDEFINED = 255_i32
  end
  enum BLUETOOTH_AUTHENTICATION_REQUIREMENTS
    BLUETOOTH_MITM_ProtectionNotRequired = 0_i32
    BLUETOOTH_MITM_ProtectionRequired = 1_i32
    BLUETOOTH_MITM_ProtectionNotRequiredBonding = 2_i32
    BLUETOOTH_MITM_ProtectionRequiredBonding = 3_i32
    BLUETOOTH_MITM_ProtectionNotRequiredGeneralBonding = 4_i32
    BLUETOOTH_MITM_ProtectionRequiredGeneralBonding = 5_i32
    BLUETOOTH_MITM_ProtectionNotDefined = 255_i32
  end
  enum BTH_LE_GATT_DESCRIPTOR_TYPE
    CharacteristicExtendedProperties = 0_i32
    CharacteristicUserDescription = 1_i32
    ClientCharacteristicConfiguration = 2_i32
    ServerCharacteristicConfiguration = 3_i32
    CharacteristicFormat = 4_i32
    CharacteristicAggregateFormat = 5_i32
    CustomDescriptor = 6_i32
  end
  enum BTH_LE_GATT_EVENT_TYPE
    CharacteristicValueChangedEvent = 0_i32
  end

  @[Extern]
  struct SDP_LARGE_INTEGER_16
    property low_part : UInt64
    property high_part : Int64
    def initialize(@low_part : UInt64, @high_part : Int64)
    end
  end

  @[Extern]
  struct SDP_ULARGE_INTEGER_16
    property low_part : UInt64
    property high_part : UInt64
    def initialize(@low_part : UInt64, @high_part : UInt64)
    end
  end

  @[Extern]
  struct SdpAttributeRange
    property minAttribute : UInt16
    property maxAttribute : UInt16
    def initialize(@minAttribute : UInt16, @maxAttribute : UInt16)
    end
  end

  @[Extern(union: true)]
  struct SdpQueryUuidUnion
    property uuid128 : LibC::GUID
    property uuid32 : UInt32
    property uuid16 : UInt16
    def initialize(@uuid128 : LibC::GUID, @uuid32 : UInt32, @uuid16 : UInt16)
    end
  end

  @[Extern]
  struct SdpQueryUuid
    property u : Win32cr::Devices::Bluetooth::SdpQueryUuidUnion
    property uuidType : UInt16
    def initialize(@u : Win32cr::Devices::Bluetooth::SdpQueryUuidUnion, @uuidType : UInt16)
    end
  end

  @[Extern]
  struct BTH_DEVICE_INFO
    property flags : UInt32
    property address : UInt64
    property classOfDevice : UInt32
    property name : Win32cr::Foundation::CHAR[248]
    def initialize(@flags : UInt32, @address : UInt64, @classOfDevice : UInt32, @name : Win32cr::Foundation::CHAR[248])
    end
  end

  @[Extern]
  struct BTH_RADIO_IN_RANGE
    property deviceInfo : Win32cr::Devices::Bluetooth::BTH_DEVICE_INFO
    property previousDeviceFlags : UInt32
    def initialize(@deviceInfo : Win32cr::Devices::Bluetooth::BTH_DEVICE_INFO, @previousDeviceFlags : UInt32)
    end
  end

  @[Extern]
  struct BTH_L2CAP_EVENT_INFO
    property bthAddress : UInt64
    property psm : UInt16
    property connected : UInt8
    property initiated : UInt8
    def initialize(@bthAddress : UInt64, @psm : UInt16, @connected : UInt8, @initiated : UInt8)
    end
  end

  @[Extern]
  struct BTH_HCI_EVENT_INFO
    property bthAddress : UInt64
    property connectionType : UInt8
    property connected : UInt8
    def initialize(@bthAddress : UInt64, @connectionType : UInt8, @connected : UInt8)
    end
  end

  @[Extern]
  struct BLUETOOTH_ADDRESS
    property anonymous : Anonymous_e__Union_

    # Nested Type Anonymous_e__Union_
    @[Extern(union: true)]
    struct Anonymous_e__Union_
    property ullLong : UInt64
    property rgBytes : UInt8[6]
    def initialize(@ullLong : UInt64, @rgBytes : UInt8[6])
    end
    end

    def initialize(@anonymous : Anonymous_e__Union_)
    end
  end

  @[Extern]
  struct BLUETOOTH_LOCAL_SERVICE_INFO
    property enabled : Win32cr::Foundation::BOOL
    property btAddr : Win32cr::Devices::Bluetooth::BLUETOOTH_ADDRESS
    property szName : UInt16[256]
    property szDeviceString : UInt16[256]
    def initialize(@enabled : Win32cr::Foundation::BOOL, @btAddr : Win32cr::Devices::Bluetooth::BLUETOOTH_ADDRESS, @szName : UInt16[256], @szDeviceString : UInt16[256])
    end
  end

  @[Extern]
  struct BLUETOOTH_FIND_RADIO_PARAMS
    property dwSize : UInt32
    def initialize(@dwSize : UInt32)
    end
  end

  @[Extern]
  struct BLUETOOTH_RADIO_INFO
    property dwSize : UInt32
    property address : Win32cr::Devices::Bluetooth::BLUETOOTH_ADDRESS
    property szName : UInt16[248]
    property ulClassofDevice : UInt32
    property lmpSubversion : UInt16
    property manufacturer : UInt16
    def initialize(@dwSize : UInt32, @address : Win32cr::Devices::Bluetooth::BLUETOOTH_ADDRESS, @szName : UInt16[248], @ulClassofDevice : UInt32, @lmpSubversion : UInt16, @manufacturer : UInt16)
    end
  end

  @[Extern]
  struct BLUETOOTH_DEVICE_INFO
    property dwSize : UInt32
    property address : Win32cr::Devices::Bluetooth::BLUETOOTH_ADDRESS
    property ulClassofDevice : UInt32
    property fConnected : Win32cr::Foundation::BOOL
    property fRemembered : Win32cr::Foundation::BOOL
    property fAuthenticated : Win32cr::Foundation::BOOL
    property stLastSeen : Win32cr::Foundation::SYSTEMTIME
    property stLastUsed : Win32cr::Foundation::SYSTEMTIME
    property szName : UInt16[248]
    def initialize(@dwSize : UInt32, @address : Win32cr::Devices::Bluetooth::BLUETOOTH_ADDRESS, @ulClassofDevice : UInt32, @fConnected : Win32cr::Foundation::BOOL, @fRemembered : Win32cr::Foundation::BOOL, @fAuthenticated : Win32cr::Foundation::BOOL, @stLastSeen : Win32cr::Foundation::SYSTEMTIME, @stLastUsed : Win32cr::Foundation::SYSTEMTIME, @szName : UInt16[248])
    end
  end

  @[Extern]
  struct BLUETOOTH_AUTHENTICATION_CALLBACK_PARAMS
    property deviceInfo : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO
    property authenticationMethod : Win32cr::Devices::Bluetooth::BLUETOOTH_AUTHENTICATION_METHOD
    property ioCapability : Win32cr::Devices::Bluetooth::BLUETOOTH_IO_CAPABILITY
    property authenticationRequirements : Win32cr::Devices::Bluetooth::BLUETOOTH_AUTHENTICATION_REQUIREMENTS
    property anonymous : Anonymous_e__Union_

    # Nested Type Anonymous_e__Union_
    @[Extern(union: true)]
    struct Anonymous_e__Union_
    property numeric_value : UInt32
    property passkey : UInt32
    def initialize(@numeric_value : UInt32, @passkey : UInt32)
    end
    end

    def initialize(@deviceInfo : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO, @authenticationMethod : Win32cr::Devices::Bluetooth::BLUETOOTH_AUTHENTICATION_METHOD, @ioCapability : Win32cr::Devices::Bluetooth::BLUETOOTH_IO_CAPABILITY, @authenticationRequirements : Win32cr::Devices::Bluetooth::BLUETOOTH_AUTHENTICATION_REQUIREMENTS, @anonymous : Anonymous_e__Union_)
    end
  end

  @[Extern]
  struct BLUETOOTH_DEVICE_SEARCH_PARAMS
    property dwSize : UInt32
    property fReturnAuthenticated : Win32cr::Foundation::BOOL
    property fReturnRemembered : Win32cr::Foundation::BOOL
    property fReturnUnknown : Win32cr::Foundation::BOOL
    property fReturnConnected : Win32cr::Foundation::BOOL
    property fIssueInquiry : Win32cr::Foundation::BOOL
    property cTimeoutMultiplier : UInt8
    property hRadio : Win32cr::Foundation::HANDLE
    def initialize(@dwSize : UInt32, @fReturnAuthenticated : Win32cr::Foundation::BOOL, @fReturnRemembered : Win32cr::Foundation::BOOL, @fReturnUnknown : Win32cr::Foundation::BOOL, @fReturnConnected : Win32cr::Foundation::BOOL, @fIssueInquiry : Win32cr::Foundation::BOOL, @cTimeoutMultiplier : UInt8, @hRadio : Win32cr::Foundation::HANDLE)
    end
  end

  @[Extern]
  struct BLUETOOTH_COD_PAIRS
    property ulCODMask : UInt32
    property pcszDescription : Win32cr::Foundation::PWSTR
    def initialize(@ulCODMask : UInt32, @pcszDescription : Win32cr::Foundation::PWSTR)
    end
  end

  @[Extern]
  struct BLUETOOTH_SELECT_DEVICE_PARAMS
    property dwSize : UInt32
    property cNumOfClasses : UInt32
    property prgClassOfDevices : Win32cr::Devices::Bluetooth::BLUETOOTH_COD_PAIRS*
    property pszInfo : Win32cr::Foundation::PWSTR
    property hwndParent : Win32cr::Foundation::HWND
    property fForceAuthentication : Win32cr::Foundation::BOOL
    property fShowAuthenticated : Win32cr::Foundation::BOOL
    property fShowRemembered : Win32cr::Foundation::BOOL
    property fShowUnknown : Win32cr::Foundation::BOOL
    property fAddNewDeviceWizard : Win32cr::Foundation::BOOL
    property fSkipServicesPage : Win32cr::Foundation::BOOL
    property pfnDeviceCallback : Win32cr::Devices::Bluetooth::PFN_DEVICE_CALLBACK
    property pvParam : Void*
    property cNumDevices : UInt32
    property pDevices : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO*
    def initialize(@dwSize : UInt32, @cNumOfClasses : UInt32, @prgClassOfDevices : Win32cr::Devices::Bluetooth::BLUETOOTH_COD_PAIRS*, @pszInfo : Win32cr::Foundation::PWSTR, @hwndParent : Win32cr::Foundation::HWND, @fForceAuthentication : Win32cr::Foundation::BOOL, @fShowAuthenticated : Win32cr::Foundation::BOOL, @fShowRemembered : Win32cr::Foundation::BOOL, @fShowUnknown : Win32cr::Foundation::BOOL, @fAddNewDeviceWizard : Win32cr::Foundation::BOOL, @fSkipServicesPage : Win32cr::Foundation::BOOL, @pfnDeviceCallback : Win32cr::Devices::Bluetooth::PFN_DEVICE_CALLBACK, @pvParam : Void*, @cNumDevices : UInt32, @pDevices : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO*)
    end
  end

  @[Extern]
  struct BLUETOOTH_PIN_INFO
    property pin : UInt8[16]
    property pinLength : UInt8
    def initialize(@pin : UInt8[16], @pinLength : UInt8)
    end
  end

  @[Extern]
  struct BLUETOOTH_OOB_DATA_INFO
    property c : UInt8[16]
    property r : UInt8[16]
    def initialize(@c : UInt8[16], @r : UInt8[16])
    end
  end

  @[Extern]
  struct BLUETOOTH_NUMERIC_COMPARISON_INFO
    property numeric_value : UInt32
    def initialize(@numeric_value : UInt32)
    end
  end

  @[Extern]
  struct BLUETOOTH_PASSKEY_INFO
    property passkey : UInt32
    def initialize(@passkey : UInt32)
    end
  end

  @[Extern]
  struct BLUETOOTH_AUTHENTICATE_RESPONSE
    property bthAddressRemote : Win32cr::Devices::Bluetooth::BLUETOOTH_ADDRESS
    property authMethod : Win32cr::Devices::Bluetooth::BLUETOOTH_AUTHENTICATION_METHOD
    property anonymous : Anonymous_e__Union_
    property negativeResponse : UInt8

    # Nested Type Anonymous_e__Union_
    @[Extern(union: true)]
    struct Anonymous_e__Union_
    property pinInfo : Win32cr::Devices::Bluetooth::BLUETOOTH_PIN_INFO
    property oobInfo : Win32cr::Devices::Bluetooth::BLUETOOTH_OOB_DATA_INFO
    property numericCompInfo : Win32cr::Devices::Bluetooth::BLUETOOTH_NUMERIC_COMPARISON_INFO
    property passkeyInfo : Win32cr::Devices::Bluetooth::BLUETOOTH_PASSKEY_INFO
    def initialize(@pinInfo : Win32cr::Devices::Bluetooth::BLUETOOTH_PIN_INFO, @oobInfo : Win32cr::Devices::Bluetooth::BLUETOOTH_OOB_DATA_INFO, @numericCompInfo : Win32cr::Devices::Bluetooth::BLUETOOTH_NUMERIC_COMPARISON_INFO, @passkeyInfo : Win32cr::Devices::Bluetooth::BLUETOOTH_PASSKEY_INFO)
    end
    end

    def initialize(@bthAddressRemote : Win32cr::Devices::Bluetooth::BLUETOOTH_ADDRESS, @authMethod : Win32cr::Devices::Bluetooth::BLUETOOTH_AUTHENTICATION_METHOD, @anonymous : Anonymous_e__Union_, @negativeResponse : UInt8)
    end
  end

  @[Extern]
  struct SDP_ELEMENT_DATA
    property type__ : Win32cr::Devices::Bluetooth::SDP_TYPE
    property specificType : Win32cr::Devices::Bluetooth::SDP_SPECIFICTYPE
    property data : Data_e__union_

    # Nested Type Data_e__union_
    @[Extern(union: true)]
    struct Data_e__union_
    property int128 : Win32cr::Devices::Bluetooth::SDP_LARGE_INTEGER_16
    property int64 : Int64
    property int32 : Int32
    property int16 : Int16
    property int8 : Win32cr::Foundation::CHAR
    property uint128 : Win32cr::Devices::Bluetooth::SDP_ULARGE_INTEGER_16
    property uint64 : UInt64
    property uint32 : UInt32
    property uint16 : UInt16
    property uint8 : UInt8
    property booleanVal : UInt8
    property uuid128 : LibC::GUID
    property uuid32 : UInt32
    property uuid16 : UInt16
    property string : String_e__struct_
    property url : Url_e__struct_
    property sequence : Sequence_e__struct_
    property alternative : Alternative_e__struct_

      # Nested Type Alternative_e__struct_
      @[Extern]
      struct Alternative_e__struct_
    property value : UInt8*
    property length : UInt32
    def initialize(@value : UInt8*, @length : UInt32)
    end
      end


      # Nested Type Url_e__struct_
      @[Extern]
      struct Url_e__struct_
    property value : UInt8*
    property length : UInt32
    def initialize(@value : UInt8*, @length : UInt32)
    end
      end


      # Nested Type String_e__struct_
      @[Extern]
      struct String_e__struct_
    property value : UInt8*
    property length : UInt32
    def initialize(@value : UInt8*, @length : UInt32)
    end
      end


      # Nested Type Sequence_e__struct_
      @[Extern]
      struct Sequence_e__struct_
    property value : UInt8*
    property length : UInt32
    def initialize(@value : UInt8*, @length : UInt32)
    end
      end

    def initialize(@int128 : Win32cr::Devices::Bluetooth::SDP_LARGE_INTEGER_16, @int64 : Int64, @int32 : Int32, @int16 : Int16, @int8 : Win32cr::Foundation::CHAR, @uint128 : Win32cr::Devices::Bluetooth::SDP_ULARGE_INTEGER_16, @uint64 : UInt64, @uint32 : UInt32, @uint16 : UInt16, @uint8 : UInt8, @booleanVal : UInt8, @uuid128 : LibC::GUID, @uuid32 : UInt32, @uuid16 : UInt16, @string : String_e__struct_, @url : Url_e__struct_, @sequence : Sequence_e__struct_, @alternative : Alternative_e__struct_)
    end
    end

    def initialize(@type__ : Win32cr::Devices::Bluetooth::SDP_TYPE, @specificType : Win32cr::Devices::Bluetooth::SDP_SPECIFICTYPE, @data : Data_e__union_)
    end
  end

  @[Extern]
  struct SDP_STRING_TYPE_DATA
    property encoding : UInt16
    property mibeNum : UInt16
    property attributeId : UInt16
    def initialize(@encoding : UInt16, @mibeNum : UInt16, @attributeId : UInt16)
    end
  end

  @[Extern]
  struct BTH_LE_UUID
    property is_short_uuid : Win32cr::Foundation::BOOLEAN
    property value : Value_e__Union_

    # Nested Type Value_e__Union_
    @[Extern(union: true)]
    struct Value_e__Union_
    property short_uuid : UInt16
    property long_uuid : LibC::GUID
    def initialize(@short_uuid : UInt16, @long_uuid : LibC::GUID)
    end
    end

    def initialize(@is_short_uuid : Win32cr::Foundation::BOOLEAN, @value : Value_e__Union_)
    end
  end

  @[Extern]
  struct BTH_LE_GATT_SERVICE
    property service_uuid : Win32cr::Devices::Bluetooth::BTH_LE_UUID
    property attribute_handle : UInt16
    def initialize(@service_uuid : Win32cr::Devices::Bluetooth::BTH_LE_UUID, @attribute_handle : UInt16)
    end
  end

  @[Extern]
  struct BTH_LE_GATT_CHARACTERISTIC
    property service_handle : UInt16
    property characteristic_uuid : Win32cr::Devices::Bluetooth::BTH_LE_UUID
    property attribute_handle : UInt16
    property characteristic_value_handle : UInt16
    property is_broadcastable : Win32cr::Foundation::BOOLEAN
    property is_readable : Win32cr::Foundation::BOOLEAN
    property is_writable : Win32cr::Foundation::BOOLEAN
    property is_writable_without_response : Win32cr::Foundation::BOOLEAN
    property is_signed_writable : Win32cr::Foundation::BOOLEAN
    property is_notifiable : Win32cr::Foundation::BOOLEAN
    property is_indicatable : Win32cr::Foundation::BOOLEAN
    property has_extended_properties : Win32cr::Foundation::BOOLEAN
    def initialize(@service_handle : UInt16, @characteristic_uuid : Win32cr::Devices::Bluetooth::BTH_LE_UUID, @attribute_handle : UInt16, @characteristic_value_handle : UInt16, @is_broadcastable : Win32cr::Foundation::BOOLEAN, @is_readable : Win32cr::Foundation::BOOLEAN, @is_writable : Win32cr::Foundation::BOOLEAN, @is_writable_without_response : Win32cr::Foundation::BOOLEAN, @is_signed_writable : Win32cr::Foundation::BOOLEAN, @is_notifiable : Win32cr::Foundation::BOOLEAN, @is_indicatable : Win32cr::Foundation::BOOLEAN, @has_extended_properties : Win32cr::Foundation::BOOLEAN)
    end
  end

  @[Extern]
  struct BTH_LE_GATT_CHARACTERISTIC_VALUE
    property data_size : UInt32
    property data : UInt8*
    def initialize(@data_size : UInt32, @data : UInt8*)
    end
  end

  @[Extern]
  struct BTH_LE_GATT_DESCRIPTOR
    property service_handle : UInt16
    property characteristic_handle : UInt16
    property descriptor_type : Win32cr::Devices::Bluetooth::BTH_LE_GATT_DESCRIPTOR_TYPE
    property descriptor_uuid : Win32cr::Devices::Bluetooth::BTH_LE_UUID
    property attribute_handle : UInt16
    def initialize(@service_handle : UInt16, @characteristic_handle : UInt16, @descriptor_type : Win32cr::Devices::Bluetooth::BTH_LE_GATT_DESCRIPTOR_TYPE, @descriptor_uuid : Win32cr::Devices::Bluetooth::BTH_LE_UUID, @attribute_handle : UInt16)
    end
  end

  @[Extern]
  struct BTH_LE_GATT_DESCRIPTOR_VALUE
    property descriptor_type : Win32cr::Devices::Bluetooth::BTH_LE_GATT_DESCRIPTOR_TYPE
    property descriptor_uuid : Win32cr::Devices::Bluetooth::BTH_LE_UUID
    property anonymous : Anonymous_e__Union_
    property data_size : UInt32
    property data : UInt8*

    # Nested Type Anonymous_e__Union_
    @[Extern(union: true)]
    struct Anonymous_e__Union_
    property characteristic_extended_properties : CharacteristicExtendedProperties_e__Struct_
    property client_characteristic_configuration : ClientCharacteristicConfiguration_e__Struct_
    property server_characteristic_configuration : ServerCharacteristicConfiguration_e__Struct_
    property characteristic_format : CharacteristicFormat_e__Struct_

      # Nested Type ServerCharacteristicConfiguration_e__Struct_
      @[Extern]
      struct ServerCharacteristicConfiguration_e__Struct_
    property is_broadcast : Win32cr::Foundation::BOOLEAN
    def initialize(@is_broadcast : Win32cr::Foundation::BOOLEAN)
    end
      end


      # Nested Type CharacteristicExtendedProperties_e__Struct_
      @[Extern]
      struct CharacteristicExtendedProperties_e__Struct_
    property is_reliable_write_enabled : Win32cr::Foundation::BOOLEAN
    property is_auxiliaries_writable : Win32cr::Foundation::BOOLEAN
    def initialize(@is_reliable_write_enabled : Win32cr::Foundation::BOOLEAN, @is_auxiliaries_writable : Win32cr::Foundation::BOOLEAN)
    end
      end


      # Nested Type CharacteristicFormat_e__Struct_
      @[Extern]
      struct CharacteristicFormat_e__Struct_
    property format : UInt8
    property exponent : UInt8
    property unit : Win32cr::Devices::Bluetooth::BTH_LE_UUID
    property name_space : UInt8
    property description : Win32cr::Devices::Bluetooth::BTH_LE_UUID
    def initialize(@format : UInt8, @exponent : UInt8, @unit : Win32cr::Devices::Bluetooth::BTH_LE_UUID, @name_space : UInt8, @description : Win32cr::Devices::Bluetooth::BTH_LE_UUID)
    end
      end


      # Nested Type ClientCharacteristicConfiguration_e__Struct_
      @[Extern]
      struct ClientCharacteristicConfiguration_e__Struct_
    property is_subscribe_to_notification : Win32cr::Foundation::BOOLEAN
    property is_subscribe_to_indication : Win32cr::Foundation::BOOLEAN
    def initialize(@is_subscribe_to_notification : Win32cr::Foundation::BOOLEAN, @is_subscribe_to_indication : Win32cr::Foundation::BOOLEAN)
    end
      end

    def initialize(@characteristic_extended_properties : CharacteristicExtendedProperties_e__Struct_, @client_characteristic_configuration : ClientCharacteristicConfiguration_e__Struct_, @server_characteristic_configuration : ServerCharacteristicConfiguration_e__Struct_, @characteristic_format : CharacteristicFormat_e__Struct_)
    end
    end

    def initialize(@descriptor_type : Win32cr::Devices::Bluetooth::BTH_LE_GATT_DESCRIPTOR_TYPE, @descriptor_uuid : Win32cr::Devices::Bluetooth::BTH_LE_UUID, @anonymous : Anonymous_e__Union_, @data_size : UInt32, @data : UInt8*)
    end
  end

  @[Extern]
  struct BLUETOOTH_GATT_VALUE_CHANGED_EVENT_REGISTRATION
    property num_characteristics : UInt16
    property characteristics : Win32cr::Devices::Bluetooth::BTH_LE_GATT_CHARACTERISTIC*
    def initialize(@num_characteristics : UInt16, @characteristics : Win32cr::Devices::Bluetooth::BTH_LE_GATT_CHARACTERISTIC*)
    end
  end

  @[Extern]
  struct BLUETOOTH_GATT_VALUE_CHANGED_EVENT
    property changed_attribute_handle : UInt16
    property characteristic_value_data_size : LibC::UIntPtrT
    property characteristic_value : Win32cr::Devices::Bluetooth::BTH_LE_GATT_CHARACTERISTIC_VALUE*
    def initialize(@changed_attribute_handle : UInt16, @characteristic_value_data_size : LibC::UIntPtrT, @characteristic_value : Win32cr::Devices::Bluetooth::BTH_LE_GATT_CHARACTERISTIC_VALUE*)
    end
  end

  @[Extern]
  struct SOCKADDR_BTH
    property addressFamily : UInt16
    property btAddr : UInt64
    property serviceClassId : LibC::GUID
    property port : UInt32
    def initialize(@addressFamily : UInt16, @btAddr : UInt64, @serviceClassId : LibC::GUID, @port : UInt32)
    end
  end

  @[Extern]
  struct BTH_SET_SERVICE
    property pSdpVersion : UInt32*
    property pRecordHandle : Win32cr::Foundation::HANDLE*
    property fCodService : UInt32
    property reserved : UInt32[5]
    property ulRecordLength : UInt32
    property pRecord : UInt8*
    def initialize(@pSdpVersion : UInt32*, @pRecordHandle : Win32cr::Foundation::HANDLE*, @fCodService : UInt32, @reserved : UInt32[5], @ulRecordLength : UInt32, @pRecord : UInt8*)
    end
  end

  @[Extern]
  struct BTH_QUERY_DEVICE
    property lap : UInt32
    property length : UInt8
    def initialize(@lap : UInt32, @length : UInt8)
    end
  end

  @[Extern]
  struct BTH_QUERY_SERVICE
    property type__ : UInt32
    property serviceHandle : UInt32
    property uuids : Win32cr::Devices::Bluetooth::SdpQueryUuid[12]
    property numRange : UInt32
    property pRange : Win32cr::Devices::Bluetooth::SdpAttributeRange*
    def initialize(@type__ : UInt32, @serviceHandle : UInt32, @uuids : Win32cr::Devices::Bluetooth::SdpQueryUuid[12], @numRange : UInt32, @pRange : Win32cr::Devices::Bluetooth::SdpAttributeRange*)
    end
  end

  @[Extern]
  struct RFCOMM_MSC_DATA
    property signals : UInt8
    property break__ : UInt8
    def initialize(@signals : UInt8, @break__ : UInt8)
    end
  end

  @[Extern]
  struct RFCOMM_RLS_DATA
    property line_status : UInt8
    def initialize(@line_status : UInt8)
    end
  end

  @[Extern]
  struct RFCOMM_RPN_DATA
    property baud : UInt8
    property data : UInt8
    property flow_control : UInt8
    property xon_char : UInt8
    property xoff_char : UInt8
    property parameter_mask1 : UInt8
    property parameter_mask2 : UInt8
    def initialize(@baud : UInt8, @data : UInt8, @flow_control : UInt8, @xon_char : UInt8, @xoff_char : UInt8, @parameter_mask1 : UInt8, @parameter_mask2 : UInt8)
    end
  end

  @[Extern]
  struct RFCOMM_COMMAND
    property cmd_type : UInt32
    property data : Data_e__Union_

    # Nested Type Data_e__Union_
    @[Extern(union: true)]
    struct Data_e__Union_
    property msc : Win32cr::Devices::Bluetooth::RFCOMM_MSC_DATA
    property rls : Win32cr::Devices::Bluetooth::RFCOMM_RLS_DATA
    property rpn : Win32cr::Devices::Bluetooth::RFCOMM_RPN_DATA
    def initialize(@msc : Win32cr::Devices::Bluetooth::RFCOMM_MSC_DATA, @rls : Win32cr::Devices::Bluetooth::RFCOMM_RLS_DATA, @rpn : Win32cr::Devices::Bluetooth::RFCOMM_RPN_DATA)
    end
    end

    def initialize(@cmd_type : UInt32, @data : Data_e__Union_)
    end
  end

  @[Extern]
  struct BTH_PING_REQ
    property btAddr : UInt64
    property dataLen : UInt8
    property data : UInt8[44]
    def initialize(@btAddr : UInt64, @dataLen : UInt8, @data : UInt8[44])
    end
  end

  @[Extern]
  struct BTH_PING_RSP
    property dataLen : UInt8
    property data : UInt8[44]
    def initialize(@dataLen : UInt8, @data : UInt8[44])
    end
  end

  @[Extern]
  struct BTH_INFO_REQ
    property btAddr : UInt64
    property infoType : UInt16
    def initialize(@btAddr : UInt64, @infoType : UInt16)
    end
  end

  @[Extern]
  struct BTH_INFO_RSP
    property result : UInt16
    property dataLen : UInt8
    property anonymous : Anonymous_e__Union_

    # Nested Type Anonymous_e__Union_
    @[Extern(union: true)]
    struct Anonymous_e__Union_
    property connectionlessMTU : UInt16
    property data : UInt8[44]
    def initialize(@connectionlessMTU : UInt16, @data : UInt8[44])
    end
    end

    def initialize(@result : UInt16, @dataLen : UInt8, @anonymous : Anonymous_e__Union_)
    end
  end

  @[Link("bluetoothapis")]
  @[Link("bthprops.cpl")]
  lib C
    fun BluetoothFindFirstRadio(pbtfrp : Win32cr::Devices::Bluetooth::BLUETOOTH_FIND_RADIO_PARAMS*, phRadio : Win32cr::Foundation::HANDLE*) : LibC::IntPtrT

    fun BluetoothFindNextRadio(hFind : LibC::IntPtrT, phRadio : Win32cr::Foundation::HANDLE*) : Win32cr::Foundation::BOOL

    fun BluetoothFindRadioClose(hFind : LibC::IntPtrT) : Win32cr::Foundation::BOOL

    fun BluetoothGetRadioInfo(hRadio : Win32cr::Foundation::HANDLE, pRadioInfo : Win32cr::Devices::Bluetooth::BLUETOOTH_RADIO_INFO*) : UInt32

    fun BluetoothFindFirstDevice(pbtsp : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_SEARCH_PARAMS*, pbtdi : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO*) : LibC::IntPtrT

    fun BluetoothFindNextDevice(hFind : LibC::IntPtrT, pbtdi : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO*) : Win32cr::Foundation::BOOL

    fun BluetoothFindDeviceClose(hFind : LibC::IntPtrT) : Win32cr::Foundation::BOOL

    fun BluetoothGetDeviceInfo(hRadio : Win32cr::Foundation::HANDLE, pbtdi : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO*) : UInt32

    fun BluetoothUpdateDeviceRecord(pbtdi : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO*) : UInt32

    fun BluetoothRemoveDevice(pAddress : Win32cr::Devices::Bluetooth::BLUETOOTH_ADDRESS*) : UInt32

    fun BluetoothSelectDevices(pbtsdp : Win32cr::Devices::Bluetooth::BLUETOOTH_SELECT_DEVICE_PARAMS*) : Win32cr::Foundation::BOOL

    fun BluetoothSelectDevicesFree(pbtsdp : Win32cr::Devices::Bluetooth::BLUETOOTH_SELECT_DEVICE_PARAMS*) : Win32cr::Foundation::BOOL

    fun BluetoothDisplayDeviceProperties(hwndParent : Win32cr::Foundation::HWND, pbtdi : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO*) : Win32cr::Foundation::BOOL

    fun BluetoothAuthenticateDevice(hwndParent : Win32cr::Foundation::HWND, hRadio : Win32cr::Foundation::HANDLE, pbtbi : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO*, pszPasskey : UInt16*, ulPasskeyLength : UInt32) : UInt32

    fun BluetoothAuthenticateDeviceEx(hwndParentIn : Win32cr::Foundation::HWND, hRadioIn : Win32cr::Foundation::HANDLE, pbtdiInout : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO*, pbtOobData : Win32cr::Devices::Bluetooth::BLUETOOTH_OOB_DATA_INFO*, authenticationRequirement : Win32cr::Devices::Bluetooth::AUTHENTICATION_REQUIREMENTS) : UInt32

    fun BluetoothAuthenticateMultipleDevices(hwndParent : Win32cr::Foundation::HWND, hRadio : Win32cr::Foundation::HANDLE, cDevices : UInt32, rgbtdi : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO*) : UInt32

    fun BluetoothSetServiceState(hRadio : Win32cr::Foundation::HANDLE, pbtdi : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO*, pGuidService : LibC::GUID*, dwServiceFlags : UInt32) : UInt32

    fun BluetoothEnumerateInstalledServices(hRadio : Win32cr::Foundation::HANDLE, pbtdi : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO*, pcServiceInout : UInt32*, pGuidServices : LibC::GUID*) : UInt32

    fun BluetoothEnableDiscovery(hRadio : Win32cr::Foundation::HANDLE, fEnabled : Win32cr::Foundation::BOOL) : Win32cr::Foundation::BOOL

    fun BluetoothIsDiscoverable(hRadio : Win32cr::Foundation::HANDLE) : Win32cr::Foundation::BOOL

    fun BluetoothEnableIncomingConnections(hRadio : Win32cr::Foundation::HANDLE, fEnabled : Win32cr::Foundation::BOOL) : Win32cr::Foundation::BOOL

    fun BluetoothIsConnectable(hRadio : Win32cr::Foundation::HANDLE) : Win32cr::Foundation::BOOL

    fun BluetoothRegisterForAuthentication(pbtdi : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO*, phRegHandle : LibC::IntPtrT*, pfnCallback : Win32cr::Devices::Bluetooth::PFN_AUTHENTICATION_CALLBACK, pvParam : Void*) : UInt32

    fun BluetoothRegisterForAuthenticationEx(pbtdiIn : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO*, phRegHandleOut : LibC::IntPtrT*, pfnCallbackIn : Win32cr::Devices::Bluetooth::PFN_AUTHENTICATION_CALLBACK_EX, pvParam : Void*) : UInt32

    fun BluetoothUnregisterAuthentication(hRegHandle : LibC::IntPtrT) : Win32cr::Foundation::BOOL

    fun BluetoothSendAuthenticationResponse(hRadio : Win32cr::Foundation::HANDLE, pbtdi : Win32cr::Devices::Bluetooth::BLUETOOTH_DEVICE_INFO*, pszPasskey : Win32cr::Foundation::PWSTR) : UInt32

    fun BluetoothSendAuthenticationResponseEx(hRadioIn : Win32cr::Foundation::HANDLE, pauthResponse : Win32cr::Devices::Bluetooth::BLUETOOTH_AUTHENTICATE_RESPONSE*) : UInt32

    fun BluetoothSdpGetElementData(pSdpStream : UInt8*, cbSdpStreamLength : UInt32, pData : Win32cr::Devices::Bluetooth::SDP_ELEMENT_DATA*) : UInt32

    fun BluetoothSdpGetContainerElementData(pContainerStream : UInt8*, cbContainerLength : UInt32, pElement : LibC::IntPtrT*, pData : Win32cr::Devices::Bluetooth::SDP_ELEMENT_DATA*) : UInt32

    fun BluetoothSdpGetAttributeValue(pRecordStream : UInt8*, cbRecordLength : UInt32, usAttributeId : UInt16, pAttributeData : Win32cr::Devices::Bluetooth::SDP_ELEMENT_DATA*) : UInt32

    fun BluetoothSdpGetString(pRecordStream : UInt8*, cbRecordLength : UInt32, pStringData : Win32cr::Devices::Bluetooth::SDP_STRING_TYPE_DATA*, usStringOffset : UInt16, pszString : UInt16*, pcchStringLength : UInt32*) : UInt32

    fun BluetoothSdpEnumAttributes(pSDPStream : UInt8*, cbStreamSize : UInt32, pfnCallback : Win32cr::Devices::Bluetooth::PFN_BLUETOOTH_ENUM_ATTRIBUTES_CALLBACK, pvParam : Void*) : Win32cr::Foundation::BOOL

    fun BluetoothSetLocalServiceInfo(hRadioIn : Win32cr::Foundation::HANDLE, pClassGuid : LibC::GUID*, ulInstance : UInt32, pServiceInfoIn : Win32cr::Devices::Bluetooth::BLUETOOTH_LOCAL_SERVICE_INFO*) : UInt32

    fun BluetoothIsVersionAvailable(major_version : UInt8, minor_version : UInt8) : Win32cr::Foundation::BOOL

    fun BluetoothGATTGetServices(hDevice : Win32cr::Foundation::HANDLE, services_buffer_count : UInt16, services_buffer : Win32cr::Devices::Bluetooth::BTH_LE_GATT_SERVICE*, services_buffer_actual : UInt16*, flags : UInt32) : Win32cr::Foundation::HRESULT

    fun BluetoothGATTGetIncludedServices(hDevice : Win32cr::Foundation::HANDLE, parent_service : Win32cr::Devices::Bluetooth::BTH_LE_GATT_SERVICE*, included_services_buffer_count : UInt16, included_services_buffer : Win32cr::Devices::Bluetooth::BTH_LE_GATT_SERVICE*, included_services_buffer_actual : UInt16*, flags : UInt32) : Win32cr::Foundation::HRESULT

    fun BluetoothGATTGetCharacteristics(hDevice : Win32cr::Foundation::HANDLE, service : Win32cr::Devices::Bluetooth::BTH_LE_GATT_SERVICE*, characteristics_buffer_count : UInt16, characteristics_buffer : Win32cr::Devices::Bluetooth::BTH_LE_GATT_CHARACTERISTIC*, characteristics_buffer_actual : UInt16*, flags : UInt32) : Win32cr::Foundation::HRESULT

    fun BluetoothGATTGetDescriptors(hDevice : Win32cr::Foundation::HANDLE, characteristic : Win32cr::Devices::Bluetooth::BTH_LE_GATT_CHARACTERISTIC*, descriptors_buffer_count : UInt16, descriptors_buffer : Win32cr::Devices::Bluetooth::BTH_LE_GATT_DESCRIPTOR*, descriptors_buffer_actual : UInt16*, flags : UInt32) : Win32cr::Foundation::HRESULT

    fun BluetoothGATTGetCharacteristicValue(hDevice : Win32cr::Foundation::HANDLE, characteristic : Win32cr::Devices::Bluetooth::BTH_LE_GATT_CHARACTERISTIC*, characteristic_value_data_size : UInt32, characteristic_value : Win32cr::Devices::Bluetooth::BTH_LE_GATT_CHARACTERISTIC_VALUE*, characteristic_value_size_required : UInt16*, flags : UInt32) : Win32cr::Foundation::HRESULT

    fun BluetoothGATTGetDescriptorValue(hDevice : Win32cr::Foundation::HANDLE, descriptor : Win32cr::Devices::Bluetooth::BTH_LE_GATT_DESCRIPTOR*, descriptor_value_data_size : UInt32, descriptor_value : Win32cr::Devices::Bluetooth::BTH_LE_GATT_DESCRIPTOR_VALUE*, descriptor_value_size_required : UInt16*, flags : UInt32) : Win32cr::Foundation::HRESULT

    fun BluetoothGATTBeginReliableWrite(hDevice : Win32cr::Foundation::HANDLE, reliable_write_context : UInt64*, flags : UInt32) : Win32cr::Foundation::HRESULT

    fun BluetoothGATTSetCharacteristicValue(hDevice : Win32cr::Foundation::HANDLE, characteristic : Win32cr::Devices::Bluetooth::BTH_LE_GATT_CHARACTERISTIC*, characteristic_value : Win32cr::Devices::Bluetooth::BTH_LE_GATT_CHARACTERISTIC_VALUE*, reliable_write_context : UInt64, flags : UInt32) : Win32cr::Foundation::HRESULT

    fun BluetoothGATTEndReliableWrite(hDevice : Win32cr::Foundation::HANDLE, reliable_write_context : UInt64, flags : UInt32) : Win32cr::Foundation::HRESULT

    fun BluetoothGATTAbortReliableWrite(hDevice : Win32cr::Foundation::HANDLE, reliable_write_context : UInt64, flags : UInt32) : Win32cr::Foundation::HRESULT

    fun BluetoothGATTSetDescriptorValue(hDevice : Win32cr::Foundation::HANDLE, descriptor : Win32cr::Devices::Bluetooth::BTH_LE_GATT_DESCRIPTOR*, descriptor_value : Win32cr::Devices::Bluetooth::BTH_LE_GATT_DESCRIPTOR_VALUE*, flags : UInt32) : Win32cr::Foundation::HRESULT

    fun BluetoothGATTRegisterEvent(hService : Win32cr::Foundation::HANDLE, event_type : Win32cr::Devices::Bluetooth::BTH_LE_GATT_EVENT_TYPE, event_parameter_in : Void*, callback : Win32cr::Devices::Bluetooth::PFNBLUETOOTH_GATT_EVENT_CALLBACK, callback_context : Void*, pEventHandle : LibC::IntPtrT*, flags : UInt32) : Win32cr::Foundation::HRESULT

    fun BluetoothGATTUnregisterEvent(event_handle : LibC::IntPtrT, flags : UInt32) : Win32cr::Foundation::HRESULT

  end
end