require "../foundation.cr"
require "../system/io.cr"

@[Link("delayimp")]
@[Link("user32")]
@[Link(ldflags: "/IGNORE:4199")]
@[Link(ldflags: "/DELAYLOAD:winusb.dll")]
lib LibWin32
  SHORT_PACKET_TERMINATE = 1_u32
  AUTO_CLEAR_STALL = 2_u32
  PIPE_TRANSFER_TIMEOUT = 3_u32
  IGNORE_SHORT_PACKETS = 4_u32
  ALLOW_PARTIAL_READS = 5_u32
  AUTO_FLUSH = 6_u32
  RAW_IO = 7_u32
  MAXIMUM_TRANSFER_SIZE = 8_u32
  RESET_PIPE_ON_RESUME = 9_u32
  AUTO_SUSPEND = 129_u32
  SUSPEND_DELAY = 131_u32
  DEVICE_SPEED = 1_u32
  LowSpeed = 1_u32
  FullSpeed = 2_u32
  HighSpeed = 3_u32
  IOCTL_GENERICUSBFN_TRANSFER_IN = 2277389_u32
  IOCTL_GENERICUSBFN_TRANSFER_IN_APPEND_ZERO_PKT = 2277393_u32
  IOCTL_GENERICUSBFN_TRANSFER_OUT = 2277398_u32
  IOCTL_GENERICUSBFN_CONTROL_STATUS_HANDSHAKE_IN = 2277400_u32
  IOCTL_GENERICUSBFN_CONTROL_STATUS_HANDSHAKE_OUT = 2277404_u32
  IOCTL_GENERICUSBFN_GET_CLASS_INFO = 2277410_u32
  IOCTL_GENERICUSBFN_GET_PIPE_STATE = 2277414_u32
  IOCTL_GENERICUSBFN_SET_PIPE_STATE = 2277417_u32
  IOCTL_GENERICUSBFN_ACTIVATE_USB_BUS = 2277420_u32
  IOCTL_GENERICUSBFN_DEACTIVATE_USB_BUS = 2277424_u32
  IOCTL_GENERICUSBFN_BUS_EVENT_NOTIFICATION = 2277430_u32
  IOCTL_GENERICUSBFN_GET_CLASS_INFO_EX = 2277434_u32
  IOCTL_GENERICUSBFN_GET_INTERFACE_DESCRIPTOR_SET = 2277438_u32
  IOCTL_GENERICUSBFN_REGISTER_USB_STRING = 2277441_u32
  USBUSER_VERSION = 4_u32
  USBUSER_GET_CONTROLLER_INFO_0 = 1_u32
  USBUSER_GET_CONTROLLER_DRIVER_KEY = 2_u32
  USBUSER_PASS_THRU = 3_u32
  USBUSER_GET_POWER_STATE_MAP = 4_u32
  USBUSER_GET_BANDWIDTH_INFORMATION = 5_u32
  USBUSER_GET_BUS_STATISTICS_0 = 6_u32
  USBUSER_GET_ROOTHUB_SYMBOLIC_NAME = 7_u32
  USBUSER_GET_USB_DRIVER_VERSION = 8_u32
  USBUSER_GET_USB2_HW_VERSION = 9_u32
  USBUSER_USB_REFRESH_HCT_REG = 10_u32
  USBUSER_OP_SEND_ONE_PACKET = 268435457_u32
  USBUSER_OP_RAW_RESET_PORT = 536870913_u32
  USBUSER_OP_OPEN_RAW_DEVICE = 536870914_u32
  USBUSER_OP_CLOSE_RAW_DEVICE = 536870915_u32
  USBUSER_OP_SEND_RAW_COMMAND = 536870916_u32
  USBUSER_SET_ROOTPORT_FEATURE = 536870917_u32
  USBUSER_CLEAR_ROOTPORT_FEATURE = 536870918_u32
  USBUSER_GET_ROOTPORT_STATUS = 536870919_u32
  USBUSER_INVALID_REQUEST = 4294967280_u32
  USBUSER_OP_MASK_DEVONLY_API = 268435456_u32
  USBUSER_OP_MASK_HCTEST_API = 536870912_u32
  USB_PACKETFLAG_LOW_SPEED = 1_u32
  USB_PACKETFLAG_FULL_SPEED = 2_u32
  USB_PACKETFLAG_HIGH_SPEED = 4_u32
  USB_PACKETFLAG_ASYNC_IN = 8_u32
  USB_PACKETFLAG_ASYNC_OUT = 16_u32
  USB_PACKETFLAG_ISO_IN = 32_u32
  USB_PACKETFLAG_ISO_OUT = 64_u32
  USB_PACKETFLAG_SETUP = 128_u32
  USB_PACKETFLAG_TOGGLE0 = 256_u32
  USB_PACKETFLAG_TOGGLE1 = 512_u32
  USB_HC_FEATURE_FLAG_PORT_POWER_SWITCHING = 1_u32
  USB_HC_FEATURE_FLAG_SEL_SUSPEND = 2_u32
  USB_HC_FEATURE_LEGACY_BIOS = 4_u32
  USB_HC_FEATURE_TIME_SYNC_API = 8_u32
  USB_SUBMIT_URB = 0_u32
  USB_RESET_PORT = 1_u32
  USB_GET_ROOTHUB_PDO = 3_u32
  USB_GET_PORT_STATUS = 4_u32
  USB_ENABLE_PORT = 5_u32
  USB_GET_HUB_COUNT = 6_u32
  USB_CYCLE_PORT = 7_u32
  USB_GET_HUB_NAME = 8_u32
  USB_IDLE_NOTIFICATION = 9_u32
  USB_RECORD_FAILURE = 10_u32
  USB_GET_BUS_INFO = 264_u32
  USB_GET_CONTROLLER_NAME = 265_u32
  USB_GET_BUSGUID_INFO = 266_u32
  USB_GET_PARENT_HUB_INFO = 267_u32
  USB_GET_DEVICE_HANDLE = 268_u32
  USB_GET_DEVICE_HANDLE_EX = 269_u32
  USB_GET_TT_DEVICE_HANDLE = 270_u32
  USB_GET_TOPOLOGY_ADDRESS = 271_u32
  USB_IDLE_NOTIFICATION_EX = 272_u32
  USB_REQ_GLOBAL_SUSPEND = 273_u32
  USB_REQ_GLOBAL_RESUME = 274_u32
  USB_GET_HUB_CONFIG_INFO = 275_u32
  USB_FAIL_GET_STATUS = 280_u32
  USB_REGISTER_COMPOSITE_DEVICE = 0_u32
  USB_UNREGISTER_COMPOSITE_DEVICE = 1_u32
  USB_REQUEST_REMOTE_WAKE_NOTIFICATION = 2_u32
  HCD_GET_STATS_1 = 255_u32
  HCD_DIAGNOSTIC_MODE_ON = 256_u32
  HCD_DIAGNOSTIC_MODE_OFF = 257_u32
  HCD_GET_ROOT_HUB_NAME = 258_u32
  HCD_GET_DRIVERKEY_NAME = 265_u32
  HCD_GET_STATS_2 = 266_u32
  HCD_DISABLE_PORT = 268_u32
  HCD_ENABLE_PORT = 269_u32
  HCD_USER_REQUEST = 270_u32
  HCD_TRACE_READ_REQUEST = 275_u32
  USB_GET_NODE_INFORMATION = 258_u32
  USB_GET_NODE_CONNECTION_INFORMATION = 259_u32
  USB_GET_DESCRIPTOR_FROM_NODE_CONNECTION = 260_u32
  USB_GET_NODE_CONNECTION_NAME = 261_u32
  USB_DIAG_IGNORE_HUBS_ON = 262_u32
  USB_DIAG_IGNORE_HUBS_OFF = 263_u32
  USB_GET_NODE_CONNECTION_DRIVERKEY_NAME = 264_u32
  USB_GET_HUB_CAPABILITIES = 271_u32
  USB_GET_NODE_CONNECTION_ATTRIBUTES = 272_u32
  USB_HUB_CYCLE_PORT = 273_u32
  USB_GET_NODE_CONNECTION_INFORMATION_EX = 274_u32
  USB_RESET_HUB = 275_u32
  USB_GET_HUB_CAPABILITIES_EX = 276_u32
  USB_GET_HUB_INFORMATION_EX = 277_u32
  USB_GET_PORT_CONNECTOR_PROPERTIES = 278_u32
  USB_GET_NODE_CONNECTION_INFORMATION_EX_V2 = 279_u32
  USB_GET_TRANSPORT_CHARACTERISTICS = 281_u32
  USB_REGISTER_FOR_TRANSPORT_CHARACTERISTICS_CHANGE = 282_u32
  USB_NOTIFY_ON_TRANSPORT_CHARACTERISTICS_CHANGE = 283_u32
  USB_UNREGISTER_FOR_TRANSPORT_CHARACTERISTICS_CHANGE = 284_u32
  USB_START_TRACKING_FOR_TIME_SYNC = 285_u32
  USB_GET_FRAME_NUMBER_AND_QPC_FOR_TIME_SYNC = 286_u32
  USB_STOP_TRACKING_FOR_TIME_SYNC = 287_u32
  USB_GET_DEVICE_CHARACTERISTICS = 288_u32
  GUID_DEVINTERFACE_USB_HUB = "f18a0e88-c30c-11d0-8815-00a0c906bed8"
  GUID_DEVINTERFACE_USB_BILLBOARD = "5e9adaef-f879-473f-b807-4e5ea77d1b1c"
  GUID_DEVINTERFACE_USB_DEVICE = "a5dcbf10-6530-11d2-901f-00c04fb951ed"
  GUID_DEVINTERFACE_USB_HOST_CONTROLLER = "3abf6f2d-71c4-462a-8a92-1e6861e6af27"
  GUID_USB_WMI_STD_DATA = "4e623b20-cb14-11d1-b331-00a0c959bbd2"
  GUID_USB_WMI_STD_NOTIFICATION = "4e623b20-cb14-11d1-b331-00a0c959bbd2"
  GUID_USB_WMI_DEVICE_PERF_INFO = "66c1aa3c-499f-49a0-a9a5-61e2359f6407"
  GUID_USB_WMI_NODE_INFO = "9c179357-dc7a-4f41-b66b-323b9ddcb5b1"
  GUID_USB_WMI_TRACING = "3a61881b-b4e6-4bf9-ae0f-3cd8f394e52f"
  GUID_USB_TRANSFER_TRACING = "681eb8aa-403d-452c-9f8a-f0616fac9540"
  GUID_USB_PERFORMANCE_TRACING = "d5de77a6-6ae9-425c-b1e2-f5615fd348a9"
  GUID_USB_WMI_SURPRISE_REMOVAL_NOTIFICATION = "9bbbf831-a2f2-43b4-96d1-86944b5914b3"
  FILE_DEVICE_USB = 34_u32
  BMREQUEST_HOST_TO_DEVICE = 0_u32
  BMREQUEST_DEVICE_TO_HOST = 1_u32
  BMREQUEST_STANDARD = 0_u32
  BMREQUEST_CLASS = 1_u32
  BMREQUEST_VENDOR = 2_u32
  BMREQUEST_TO_DEVICE = 0_u32
  BMREQUEST_TO_INTERFACE = 1_u32
  BMREQUEST_TO_ENDPOINT = 2_u32
  BMREQUEST_TO_OTHER = 3_u32
  USB_REQUEST_GET_STATUS = 0_u32
  USB_REQUEST_CLEAR_FEATURE = 1_u32
  USB_REQUEST_SET_FEATURE = 3_u32
  USB_REQUEST_SET_ADDRESS = 5_u32
  USB_REQUEST_GET_DESCRIPTOR = 6_u32
  USB_REQUEST_SET_DESCRIPTOR = 7_u32
  USB_REQUEST_GET_CONFIGURATION = 8_u32
  USB_REQUEST_SET_CONFIGURATION = 9_u32
  USB_REQUEST_GET_INTERFACE = 10_u32
  USB_REQUEST_SET_INTERFACE = 11_u32
  USB_REQUEST_SYNC_FRAME = 12_u32
  USB_REQUEST_GET_FIRMWARE_STATUS = 26_u32
  USB_REQUEST_SET_FIRMWARE_STATUS = 27_u32
  USB_GET_FIRMWARE_ALLOWED_OR_DISALLOWED_STATE = 0_u32
  USB_GET_FIRMWARE_HASH = 1_u32
  USB_DEVICE_FIRMWARE_HASH_LENGTH = 32_u32
  USB_DISALLOW_FIRMWARE_UPDATE = 0_u32
  USB_ALLOW_FIRMWARE_UPDATE = 1_u32
  USB_REQUEST_SET_SEL = 48_u32
  USB_REQUEST_ISOCH_DELAY = 49_u32
  USB_DEVICE_DESCRIPTOR_TYPE = 1_u32
  USB_CONFIGURATION_DESCRIPTOR_TYPE = 2_u32
  USB_STRING_DESCRIPTOR_TYPE = 3_u32
  USB_INTERFACE_DESCRIPTOR_TYPE = 4_u32
  USB_ENDPOINT_DESCRIPTOR_TYPE = 5_u32
  USB_DEVICE_QUALIFIER_DESCRIPTOR_TYPE = 6_u32
  USB_OTHER_SPEED_CONFIGURATION_DESCRIPTOR_TYPE = 7_u32
  USB_INTERFACE_POWER_DESCRIPTOR_TYPE = 8_u32
  USB_OTG_DESCRIPTOR_TYPE = 9_u32
  USB_DEBUG_DESCRIPTOR_TYPE = 10_u32
  USB_INTERFACE_ASSOCIATION_DESCRIPTOR_TYPE = 11_u32
  USB_BOS_DESCRIPTOR_TYPE = 15_u32
  USB_DEVICE_CAPABILITY_DESCRIPTOR_TYPE = 16_u32
  USB_SUPERSPEED_ENDPOINT_COMPANION_DESCRIPTOR_TYPE = 48_u32
  USB_SUPERSPEEDPLUS_ISOCH_ENDPOINT_COMPANION_DESCRIPTOR_TYPE = 49_u32
  USB_RESERVED_DESCRIPTOR_TYPE = 6_u32
  USB_CONFIG_POWER_DESCRIPTOR_TYPE = 7_u32
  USB_FEATURE_ENDPOINT_STALL = 0_u32
  USB_FEATURE_REMOTE_WAKEUP = 1_u32
  USB_FEATURE_TEST_MODE = 2_u32
  USB_FEATURE_FUNCTION_SUSPEND = 0_u32
  USB_FEATURE_U1_ENABLE = 48_u32
  USB_FEATURE_U2_ENABLE = 49_u32
  USB_FEATURE_LTM_ENABLE = 50_u32
  USB_FEATURE_LDM_ENABLE = 53_u32
  USB_FEATURE_BATTERY_WAKE_MASK = 40_u32
  USB_FEATURE_OS_IS_PD_AWARE = 41_u32
  USB_FEATURE_POLICY_MODE = 42_u32
  USB_FEATURE_CHARGING_POLICY = 54_u32
  USB_CHARGING_POLICY_DEFAULT = 0_u32
  USB_CHARGING_POLICY_ICCHPF = 1_u32
  USB_CHARGING_POLICY_ICCLPF = 2_u32
  USB_CHARGING_POLICY_NO_POWER = 3_u32
  USB_STATUS_PORT_STATUS = 0_u32
  USB_STATUS_PD_STATUS = 1_u32
  USB_STATUS_EXT_PORT_STATUS = 2_u32
  USB_GETSTATUS_SELF_POWERED = 1_u32
  USB_GETSTATUS_REMOTE_WAKEUP_ENABLED = 2_u32
  USB_GETSTATUS_U1_ENABLE = 4_u32
  USB_GETSTATUS_U2_ENABLE = 8_u32
  USB_GETSTATUS_LTM_ENABLE = 16_u32
  USB_DEVICE_CLASS_RESERVED = 0_u32
  USB_DEVICE_CLASS_AUDIO = 1_u32
  USB_DEVICE_CLASS_COMMUNICATIONS = 2_u32
  USB_DEVICE_CLASS_HUMAN_INTERFACE = 3_u32
  USB_DEVICE_CLASS_MONITOR = 4_u32
  USB_DEVICE_CLASS_PHYSICAL_INTERFACE = 5_u32
  USB_DEVICE_CLASS_POWER = 6_u32
  USB_DEVICE_CLASS_IMAGE = 6_u32
  USB_DEVICE_CLASS_PRINTER = 7_u32
  USB_DEVICE_CLASS_STORAGE = 8_u32
  USB_DEVICE_CLASS_HUB = 9_u32
  USB_DEVICE_CLASS_CDC_DATA = 10_u32
  USB_DEVICE_CLASS_SMART_CARD = 11_u32
  USB_DEVICE_CLASS_CONTENT_SECURITY = 13_u32
  USB_DEVICE_CLASS_VIDEO = 14_u32
  USB_DEVICE_CLASS_PERSONAL_HEALTHCARE = 15_u32
  USB_DEVICE_CLASS_AUDIO_VIDEO = 16_u32
  USB_DEVICE_CLASS_BILLBOARD = 17_u32
  USB_DEVICE_CLASS_DIAGNOSTIC_DEVICE = 220_u32
  USB_DEVICE_CLASS_WIRELESS_CONTROLLER = 224_u32
  USB_DEVICE_CLASS_MISCELLANEOUS = 239_u32
  USB_DEVICE_CLASS_APPLICATION_SPECIFIC = 254_u32
  USB_DEVICE_CLASS_VENDOR_SPECIFIC = 255_u32
  USB_DEVICE_CAPABILITY_WIRELESS_USB = 1_u32
  USB_DEVICE_CAPABILITY_USB20_EXTENSION = 2_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_USB = 3_u32
  USB_DEVICE_CAPABILITY_CONTAINER_ID = 4_u32
  USB_DEVICE_CAPABILITY_PLATFORM = 5_u32
  USB_DEVICE_CAPABILITY_POWER_DELIVERY = 6_u32
  USB_DEVICE_CAPABILITY_BATTERY_INFO = 7_u32
  USB_DEVICE_CAPABILITY_PD_CONSUMER_PORT = 8_u32
  USB_DEVICE_CAPABILITY_PD_PROVIDER_PORT = 9_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_USB = 10_u32
  USB_DEVICE_CAPABILITY_PRECISION_TIME_MEASUREMENT = 11_u32
  USB_DEVICE_CAPABILITY_BILLBOARD = 13_u32
  USB_DEVICE_CAPABILITY_FIRMWARE_STATUS = 17_u32
  USB_DEVICE_CAPABILITY_USB20_EXTENSION_BMATTRIBUTES_RESERVED_MASK = 4294901985_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_BMATTRIBUTES_RESERVED_MASK = 253_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_BMATTRIBUTES_LTM_CAPABLE = 2_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_SPEEDS_SUPPORTED_RESERVED_MASK = 65520_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_SPEEDS_SUPPORTED_LOW = 1_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_SPEEDS_SUPPORTED_FULL = 2_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_SPEEDS_SUPPORTED_HIGH = 4_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_SPEEDS_SUPPORTED_SUPER = 8_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_U1_DEVICE_EXIT_MAX_VALUE = 10_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_U2_DEVICE_EXIT_MAX_VALUE = 2047_u32
  USB_DEVICE_CAPABILITY_MAX_U1_LATENCY = 10_u32
  USB_DEVICE_CAPABILITY_MAX_U2_LATENCY = 2047_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_LSE_BPS = 0_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_LSE_KBPS = 1_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_LSE_MBPS = 2_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_LSE_GBPS = 3_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_MODE_SYMMETRIC = 0_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_MODE_ASYMMETRIC = 1_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_DIR_RX = 0_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_DIR_TX = 1_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_PROTOCOL_SS = 0_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_PROTOCOL_SSP = 1_u32
  GUID_USB_MSOS20_PLATFORM_CAPABILITY_ID = "d8dd60df-4589-4cc7-9cd2-659d9e648a9f"
  USB_CONFIG_POWERED_MASK = 192_u32
  USB_CONFIG_BUS_POWERED = 128_u32
  USB_CONFIG_SELF_POWERED = 64_u32
  USB_CONFIG_REMOTE_WAKEUP = 32_u32
  USB_CONFIG_RESERVED = 31_u32
  USB_ENDPOINT_DIRECTION_MASK = 128_u32
  USB_ENDPOINT_ADDRESS_MASK = 15_u32
  USB_ENDPOINT_TYPE_MASK = 3_u32
  USB_ENDPOINT_TYPE_CONTROL = 0_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS = 1_u32
  USB_ENDPOINT_TYPE_BULK = 2_u32
  USB_ENDPOINT_TYPE_INTERRUPT = 3_u32
  USB_ENDPOINT_TYPE_BULK_RESERVED_MASK = 252_u32
  USB_ENDPOINT_TYPE_CONTROL_RESERVED_MASK = 252_u32
  USB_20_ENDPOINT_TYPE_INTERRUPT_RESERVED_MASK = 252_u32
  USB_30_ENDPOINT_TYPE_INTERRUPT_RESERVED_MASK = 204_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_RESERVED_MASK = 192_u32
  USB_30_ENDPOINT_TYPE_INTERRUPT_USAGE_MASK = 48_u32
  USB_30_ENDPOINT_TYPE_INTERRUPT_USAGE_PERIODIC = 0_u32
  USB_30_ENDPOINT_TYPE_INTERRUPT_USAGE_NOTIFICATION = 16_u32
  USB_30_ENDPOINT_TYPE_INTERRUPT_USAGE_RESERVED10 = 32_u32
  USB_30_ENDPOINT_TYPE_INTERRUPT_USAGE_RESERVED11 = 48_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_SYNCHRONIZATION_MASK = 12_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_SYNCHRONIZATION_NO_SYNCHRONIZATION = 0_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_SYNCHRONIZATION_ASYNCHRONOUS = 4_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_SYNCHRONIZATION_ADAPTIVE = 8_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_SYNCHRONIZATION_SYNCHRONOUS = 12_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_USAGE_MASK = 48_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_USAGE_DATA_ENDOINT = 0_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_USAGE_FEEDBACK_ENDPOINT = 16_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_USAGE_IMPLICIT_FEEDBACK_DATA_ENDPOINT = 32_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_USAGE_RESERVED = 48_u32
  USB_ENDPOINT_SUPERSPEED_BULK_MAX_PACKET_SIZE = 1024_u32
  USB_ENDPOINT_SUPERSPEED_CONTROL_MAX_PACKET_SIZE = 512_u32
  USB_ENDPOINT_SUPERSPEED_ISO_MAX_PACKET_SIZE = 1024_u32
  USB_ENDPOINT_SUPERSPEED_INTERRUPT_MAX_PACKET_SIZE = 1024_u32
  MAXIMUM_USB_STRING_LENGTH = 255_u32
  USB_SUPERSPEED_ISOCHRONOUS_MAX_MULTIPLIER = 2_u32
  USB_SUPERSPEEDPLUS_ISOCHRONOUS_MIN_BYTESPERINTERVAL = 49153_u32
  USB_SUPERSPEEDPLUS_ISOCHRONOUS_MAX_BYTESPERINTERVAL = 16777215_u32
  USB_20_HUB_DESCRIPTOR_TYPE = 41_u32
  USB_30_HUB_DESCRIPTOR_TYPE = 42_u32
  USB_REQUEST_GET_STATE = 2_u32
  USB_REQUEST_CLEAR_TT_BUFFER = 8_u32
  USB_REQUEST_RESET_TT = 9_u32
  USB_REQUEST_GET_TT_STATE = 10_u32
  USB_REQUEST_STOP_TT = 11_u32
  USB_REQUEST_SET_HUB_DEPTH = 12_u32
  USB_REQUEST_GET_PORT_ERR_COUNT = 13_u32
  USB_PORT_STATUS_CONNECT = 1_u32
  USB_PORT_STATUS_ENABLE = 2_u32
  USB_PORT_STATUS_SUSPEND = 4_u32
  USB_PORT_STATUS_OVER_CURRENT = 8_u32
  USB_PORT_STATUS_RESET = 16_u32
  USB_PORT_STATUS_POWER = 256_u32
  USB_PORT_STATUS_LOW_SPEED = 512_u32
  USB_PORT_STATUS_HIGH_SPEED = 1024_u32
  PORT_LINK_STATE_U0 = 0_u32
  PORT_LINK_STATE_U1 = 1_u32
  PORT_LINK_STATE_U2 = 2_u32
  PORT_LINK_STATE_U3 = 3_u32
  PORT_LINK_STATE_DISABLED = 4_u32
  PORT_LINK_STATE_RX_DETECT = 5_u32
  PORT_LINK_STATE_INACTIVE = 6_u32
  PORT_LINK_STATE_POLLING = 7_u32
  PORT_LINK_STATE_RECOVERY = 8_u32
  PORT_LINK_STATE_HOT_RESET = 9_u32
  PORT_LINK_STATE_COMPLIANCE_MODE = 10_u32
  PORT_LINK_STATE_LOOPBACK = 11_u32
  PORT_LINK_STATE_TEST_MODE = 11_u32
  USB_FEATURE_INTERFACE_POWER_D0 = 2_u32
  USB_FEATURE_INTERFACE_POWER_D1 = 3_u32
  USB_FEATURE_INTERFACE_POWER_D2 = 4_u32
  USB_FEATURE_INTERFACE_POWER_D3 = 5_u32
  USB_SUPPORT_D0_COMMAND = 1_u32
  USB_SUPPORT_D1_COMMAND = 2_u32
  USB_SUPPORT_D2_COMMAND = 4_u32
  USB_SUPPORT_D3_COMMAND = 8_u32
  USB_SUPPORT_D1_WAKEUP = 16_u32
  USB_SUPPORT_D2_WAKEUP = 32_u32
  USBDI_VERSION = 1536_u32
  USB_PORTATTR_NO_CONNECTOR = 1_u32
  USB_PORTATTR_SHARED_USB2 = 2_u32
  USB_PORTATTR_MINI_CONNECTOR = 4_u32
  USB_PORTATTR_OEM_CONNECTOR = 8_u32
  USB_PORTATTR_OWNED_BY_CC = 16777216_u32
  USB_PORTATTR_NO_OVERCURRENT_UI = 33554432_u32
  USB_DEFAULT_DEVICE_ADDRESS = 0_u32
  USB_DEFAULT_ENDPOINT_ADDRESS = 0_u32
  USB_DEFAULT_MAX_PACKET = 64_u32
  URB_FUNCTION_SELECT_CONFIGURATION = 0_u32
  URB_FUNCTION_SELECT_INTERFACE = 1_u32
  URB_FUNCTION_ABORT_PIPE = 2_u32
  URB_FUNCTION_TAKE_FRAME_LENGTH_CONTROL = 3_u32
  URB_FUNCTION_RELEASE_FRAME_LENGTH_CONTROL = 4_u32
  URB_FUNCTION_GET_FRAME_LENGTH = 5_u32
  URB_FUNCTION_SET_FRAME_LENGTH = 6_u32
  URB_FUNCTION_GET_CURRENT_FRAME_NUMBER = 7_u32
  URB_FUNCTION_CONTROL_TRANSFER = 8_u32
  URB_FUNCTION_BULK_OR_INTERRUPT_TRANSFER = 9_u32
  URB_FUNCTION_ISOCH_TRANSFER = 10_u32
  URB_FUNCTION_GET_DESCRIPTOR_FROM_DEVICE = 11_u32
  URB_FUNCTION_SET_DESCRIPTOR_TO_DEVICE = 12_u32
  URB_FUNCTION_SET_FEATURE_TO_DEVICE = 13_u32
  URB_FUNCTION_SET_FEATURE_TO_INTERFACE = 14_u32
  URB_FUNCTION_SET_FEATURE_TO_ENDPOINT = 15_u32
  URB_FUNCTION_CLEAR_FEATURE_TO_DEVICE = 16_u32
  URB_FUNCTION_CLEAR_FEATURE_TO_INTERFACE = 17_u32
  URB_FUNCTION_CLEAR_FEATURE_TO_ENDPOINT = 18_u32
  URB_FUNCTION_GET_STATUS_FROM_DEVICE = 19_u32
  URB_FUNCTION_GET_STATUS_FROM_INTERFACE = 20_u32
  URB_FUNCTION_GET_STATUS_FROM_ENDPOINT = 21_u32
  URB_FUNCTION_RESERVED_0X0016 = 22_u32
  URB_FUNCTION_VENDOR_DEVICE = 23_u32
  URB_FUNCTION_VENDOR_INTERFACE = 24_u32
  URB_FUNCTION_VENDOR_ENDPOINT = 25_u32
  URB_FUNCTION_CLASS_DEVICE = 26_u32
  URB_FUNCTION_CLASS_INTERFACE = 27_u32
  URB_FUNCTION_CLASS_ENDPOINT = 28_u32
  URB_FUNCTION_RESERVE_0X001D = 29_u32
  URB_FUNCTION_SYNC_RESET_PIPE_AND_CLEAR_STALL = 30_u32
  URB_FUNCTION_CLASS_OTHER = 31_u32
  URB_FUNCTION_VENDOR_OTHER = 32_u32
  URB_FUNCTION_GET_STATUS_FROM_OTHER = 33_u32
  URB_FUNCTION_CLEAR_FEATURE_TO_OTHER = 34_u32
  URB_FUNCTION_SET_FEATURE_TO_OTHER = 35_u32
  URB_FUNCTION_GET_DESCRIPTOR_FROM_ENDPOINT = 36_u32
  URB_FUNCTION_SET_DESCRIPTOR_TO_ENDPOINT = 37_u32
  URB_FUNCTION_GET_CONFIGURATION = 38_u32
  URB_FUNCTION_GET_INTERFACE = 39_u32
  URB_FUNCTION_GET_DESCRIPTOR_FROM_INTERFACE = 40_u32
  URB_FUNCTION_SET_DESCRIPTOR_TO_INTERFACE = 41_u32
  URB_FUNCTION_RESERVE_0X002B = 43_u32
  URB_FUNCTION_RESERVE_0X002C = 44_u32
  URB_FUNCTION_RESERVE_0X002D = 45_u32
  URB_FUNCTION_RESERVE_0X002E = 46_u32
  URB_FUNCTION_RESERVE_0X002F = 47_u32
  URB_FUNCTION_GET_MS_FEATURE_DESCRIPTOR = 42_u32
  URB_FUNCTION_SYNC_RESET_PIPE = 48_u32
  URB_FUNCTION_SYNC_CLEAR_STALL = 49_u32
  URB_FUNCTION_CONTROL_TRANSFER_EX = 50_u32
  URB_FUNCTION_RESERVE_0X0033 = 51_u32
  URB_FUNCTION_RESERVE_0X0034 = 52_u32
  URB_FUNCTION_OPEN_STATIC_STREAMS = 53_u32
  URB_FUNCTION_CLOSE_STATIC_STREAMS = 54_u32
  URB_FUNCTION_BULK_OR_INTERRUPT_TRANSFER_USING_CHAINED_MDL = 55_u32
  URB_FUNCTION_ISOCH_TRANSFER_USING_CHAINED_MDL = 56_u32
  URB_FUNCTION_GET_ISOCH_PIPE_TRANSFER_PATH_DELAYS = 61_u32
  URB_FUNCTION_RESET_PIPE = 30_u32
  USBD_SHORT_TRANSFER_OK = 2_u32
  USBD_START_ISO_TRANSFER_ASAP = 4_u32
  USBD_DEFAULT_PIPE_TRANSFER = 8_u32
  USBD_TRANSFER_DIRECTION_OUT = 0_u32
  USBD_TRANSFER_DIRECTION_IN = 1_u32
  USBD_TRANSFER_DIRECTION = 1_u32
  USBD_ISO_START_FRAME_RANGE = 1024_u32
  USBD_DEFAULT_MAXIMUM_TRANSFER_SIZE = 4294967295_u32
  USBD_PF_CHANGE_MAX_PACKET = 1_u32
  USBD_PF_SHORT_PACKET_OPT = 2_u32
  USBD_PF_ENABLE_RT_THREAD_ACCESS = 4_u32
  USBD_PF_MAP_ADD_TRANSFERS = 8_u32
  USBD_PF_VIDEO_PRIORITY = 16_u32
  USBD_PF_VOICE_PRIORITY = 32_u32
  USBD_PF_INTERACTIVE_PRIORITY = 48_u32
  USBD_PF_PRIORITY_MASK = 240_u32
  USBD_PF_HANDLES_SSP_HIGH_BANDWIDTH_ISOCH = 256_u32
  USBD_PF_SSP_HIGH_BANDWIDTH_ISOCH = 65536_u32
  OS_STRING_DESCRIPTOR_INDEX = 238_u32
  MS_GENRE_DESCRIPTOR_INDEX = 1_u32
  MS_POWER_DESCRIPTOR_INDEX = 2_u32
  MS_OS_FLAGS_CONTAINERID = 2_u32
  URB_OPEN_STATIC_STREAMS_VERSION_100 = 256_u32
  MAX_NUM_USBFN_ENDPOINTS = 15_u32
  MAX_CONFIGURATION_NAME_LENGTH = 40_u32
  MAX_USB_STRING_LENGTH = 255_u32
  MAX_SUPPORTED_CONFIGURATIONS = 12_u32
  USBFN_INTERRUPT_ENDPOINT_SIZE_NOT_UPDATEABLE_MASK = 128_u32
  USB_TEST_MODE_TEST_J = 1_u32
  USB_TEST_MODE_TEST_K = 2_u32
  USB_TEST_MODE_TEST_SE0_NAK = 3_u32
  USB_TEST_MODE_TEST_PACKET = 4_u32
  USB_TEST_MODE_TEST_FORCE_ENABLE = 5_u32
  MAX_INTERFACE_NAME_LENGTH = 40_u32
  MAX_ALTERNATE_NAME_LENGTH = 40_u32
  MAX_ASSOCIATION_NAME_LENGTH = 40_u32
  IOCTL_INTERNAL_USB_SUBMIT_URB = 2228227_u32
  IOCTL_INTERNAL_USB_RESET_PORT = 2228231_u32
  IOCTL_INTERNAL_USB_GET_ROOTHUB_PDO = 2228239_u32
  USBD_PORT_ENABLED = 1_u32
  USBD_PORT_CONNECTED = 2_u32
  IOCTL_INTERNAL_USB_GET_PORT_STATUS = 2228243_u32
  IOCTL_INTERNAL_USB_ENABLE_PORT = 2228247_u32
  IOCTL_INTERNAL_USB_GET_HUB_COUNT = 2228251_u32
  IOCTL_INTERNAL_USB_CYCLE_PORT = 2228255_u32
  IOCTL_INTERNAL_USB_GET_HUB_NAME = 2228256_u32
  IOCTL_INTERNAL_USB_GET_BUS_INFO = 2229280_u32
  IOCTL_INTERNAL_USB_GET_CONTROLLER_NAME = 2229284_u32
  IOCTL_INTERNAL_USB_GET_BUSGUID_INFO = 2229288_u32
  IOCTL_INTERNAL_USB_GET_PARENT_HUB_INFO = 2229292_u32
  IOCTL_INTERNAL_USB_SUBMIT_IDLE_NOTIFICATION = 2228263_u32
  IOCTL_INTERNAL_USB_GET_DEVICE_HANDLE = 2229299_u32
  IOCTL_INTERNAL_USB_NOTIFY_IDLE_READY = 2229315_u32
  IOCTL_INTERNAL_USB_REQ_GLOBAL_SUSPEND = 2229319_u32
  IOCTL_INTERNAL_USB_REQ_GLOBAL_RESUME = 2229323_u32
  IOCTL_INTERNAL_USB_RECORD_FAILURE = 2228267_u32
  IOCTL_INTERNAL_USB_GET_DEVICE_HANDLE_EX = 2229303_u32
  IOCTL_INTERNAL_USB_GET_TT_DEVICE_HANDLE = 2229307_u32
  IOCTL_INTERNAL_USB_GET_TOPOLOGY_ADDRESS = 2229311_u32
  IOCTL_INTERNAL_USB_GET_DEVICE_CONFIG_INFO = 2229327_u32
  IOCTL_INTERNAL_USB_REGISTER_COMPOSITE_DEVICE = 4784131_u32
  IOCTL_INTERNAL_USB_UNREGISTER_COMPOSITE_DEVICE = 4784135_u32
  IOCTL_INTERNAL_USB_REQUEST_REMOTE_WAKE_NOTIFICATION = 4784139_u32
  IOCTL_INTERNAL_USB_FAIL_GET_STATUS_FROM_DEVICE = 2229347_u32
  IOCTL_USB_HCD_GET_STATS_1 = 2229244_u32
  IOCTL_USB_HCD_GET_STATS_2 = 2229288_u32
  IOCTL_USB_HCD_DISABLE_PORT = 2229296_u32
  IOCTL_USB_HCD_ENABLE_PORT = 2229300_u32
  IOCTL_USB_DIAGNOSTIC_MODE_ON = 2229248_u32
  IOCTL_USB_DIAGNOSTIC_MODE_OFF = 2229252_u32
  IOCTL_USB_GET_ROOT_HUB_NAME = 2229256_u32
  IOCTL_GET_HCD_DRIVERKEY_NAME = 2229284_u32
  IOCTL_USB_GET_NODE_INFORMATION = 2229256_u32
  IOCTL_USB_GET_NODE_CONNECTION_INFORMATION = 2229260_u32
  IOCTL_USB_GET_DESCRIPTOR_FROM_NODE_CONNECTION = 2229264_u32
  IOCTL_USB_GET_NODE_CONNECTION_NAME = 2229268_u32
  IOCTL_USB_DIAG_IGNORE_HUBS_ON = 2229272_u32
  IOCTL_USB_DIAG_IGNORE_HUBS_OFF = 2229276_u32
  IOCTL_USB_GET_NODE_CONNECTION_DRIVERKEY_NAME = 2229280_u32
  IOCTL_USB_GET_HUB_CAPABILITIES = 2229308_u32
  IOCTL_USB_HUB_CYCLE_PORT = 2229316_u32
  IOCTL_USB_GET_NODE_CONNECTION_ATTRIBUTES = 2229312_u32
  IOCTL_USB_GET_NODE_CONNECTION_INFORMATION_EX = 2229320_u32
  IOCTL_USB_RESET_HUB = 2229324_u32
  IOCTL_USB_GET_HUB_CAPABILITIES_EX = 2229328_u32
  IOCTL_USB_GET_HUB_INFORMATION_EX = 2229332_u32
  IOCTL_USB_GET_PORT_CONNECTOR_PROPERTIES = 2229336_u32
  IOCTL_USB_GET_NODE_CONNECTION_INFORMATION_EX_V2 = 2229340_u32
  IOCTL_USB_GET_TRANSPORT_CHARACTERISTICS = 2229348_u32
  IOCTL_USB_REGISTER_FOR_TRANSPORT_CHARACTERISTICS_CHANGE = 2229352_u32
  IOCTL_USB_NOTIFY_ON_TRANSPORT_CHARACTERISTICS_CHANGE = 2229356_u32
  IOCTL_USB_UNREGISTER_FOR_TRANSPORT_CHARACTERISTICS_CHANGE = 2229360_u32
  IOCTL_USB_START_TRACKING_FOR_TIME_SYNC = 2229364_u32
  IOCTL_USB_GET_FRAME_NUMBER_AND_QPC_FOR_TIME_SYNC = 2229368_u32
  IOCTL_USB_STOP_TRACKING_FOR_TIME_SYNC = 2229372_u32
  IOCTL_USB_GET_DEVICE_CHARACTERISTICS = 2229376_u32
  WMI_USB_DRIVER_INFORMATION = 0_u32
  WMI_USB_DRIVER_NOTIFICATION = 1_u32
  WMI_USB_POWER_DEVICE_ENABLE = 2_u32
  WMI_USB_HUB_NODE_INFORMATION = 4_u32
  WMI_USB_PERFORMANCE_INFORMATION = 1_u32
  WMI_USB_DEVICE_NODE_INFORMATION = 2_u32
  USB_TRANSPORT_CHARACTERISTICS_VERSION_1 = 1_u32
  USB_TRANSPORT_CHARACTERISTICS_LATENCY_AVAILABLE = 1_u32
  USB_TRANSPORT_CHARACTERISTICS_BANDWIDTH_AVAILABLE = 2_u32
  USB_REGISTER_FOR_TRANSPORT_LATENCY_CHANGE = 1_u32
  USB_REGISTER_FOR_TRANSPORT_BANDWIDTH_CHANGE = 2_u32
  USB_DEVICE_CHARACTERISTICS_VERSION_1 = 1_u32
  USB_DEVICE_CHARACTERISTICS_MAXIMUM_PATH_DELAYS_AVAILABLE = 1_u32
  MAX_NUM_PIPES = 8_u32
  BULKIN_FLAG = 128_u32
  FILE_DEVICE_USB_SCAN = 32768_u32
  IOCTL_INDEX = 2048_u32
  IOCTL_GET_VERSION = 2147491840_u32
  IOCTL_CANCEL_IO = 2147491844_u32
  IOCTL_WAIT_ON_DEVICE_EVENT = 2147491848_u32
  IOCTL_READ_REGISTERS = 2147491852_u32
  IOCTL_WRITE_REGISTERS = 2147491856_u32
  IOCTL_GET_CHANNEL_ALIGN_RQST = 2147491860_u32
  IOCTL_GET_DEVICE_DESCRIPTOR = 2147491864_u32
  IOCTL_RESET_PIPE = 2147491868_u32
  IOCTL_GET_USB_DESCRIPTOR = 2147491872_u32
  IOCTL_SEND_USB_REQUEST = 2147491876_u32
  IOCTL_GET_PIPE_CONFIGURATION = 2147491880_u32
  IOCTL_SET_TIMEOUT = 2147491884_u32
  IOCTL_ABORT_PIPE = 2147491844_u32
  WinUSB_TestGuid = "da812bff-12c3-46a2-8e2b-dbd3b7834c43"

  alias USB_IDLE_CALLBACK = Proc(Void*, Void)


  enum USB_DEVICE_SPEED : Int32
    UsbLowSpeed = 0
    UsbFullSpeed = 1
    UsbHighSpeed = 2
    UsbSuperSpeed = 3
  end

  enum USB_DEVICE_TYPE : Int32
    Usb11Device = 0
    Usb20Device = 1
  end

  enum USB_CONTROLLER_FLAVOR : Int32
    USB_HcGeneric = 0
    OHCI_Generic = 100
    OHCI_Hydra = 101
    OHCI_NEC = 102
    UHCI_Generic = 200
    UHCI_Piix4 = 201
    UHCI_Piix3 = 202
    UHCI_Ich2 = 203
    UHCI_Reserved204 = 204
    UHCI_Ich1 = 205
    UHCI_Ich3m = 206
    UHCI_Ich4 = 207
    UHCI_Ich5 = 208
    UHCI_Ich6 = 209
    UHCI_Intel = 249
    UHCI_VIA = 250
    UHCI_VIA_x01 = 251
    UHCI_VIA_x02 = 252
    UHCI_VIA_x03 = 253
    UHCI_VIA_x04 = 254
    UHCI_VIA_x0E_FIFO = 264
    EHCI_Generic = 1000
    EHCI_NEC = 2000
    EHCI_Lucent = 3000
    EHCI_NVIDIA_Tegra2 = 4000
    EHCI_NVIDIA_Tegra3 = 4001
    EHCI_Intel_Medfield = 5001
  end

  enum USBD_PIPE_TYPE : Int32
    UsbdPipeTypeControl = 0
    UsbdPipeTypeIsochronous = 1
    UsbdPipeTypeBulk = 2
    UsbdPipeTypeInterrupt = 3
  end

  enum USBD_ENDPOINT_OFFLOAD_MODE : Int32
    UsbdEndpointOffloadModeNotSupported = 0
    UsbdEndpointOffloadSoftwareAssisted = 1
    UsbdEndpointOffloadHardwareAssisted = 2
  end

  enum USB_USER_ERROR_CODE : Int32
    UsbUserSuccess = 0
    UsbUserNotSupported = 1
    UsbUserInvalidRequestCode = 2
    UsbUserFeatureDisabled = 3
    UsbUserInvalidHeaderParameter = 4
    UsbUserInvalidParameter = 5
    UsbUserMiniportError = 6
    UsbUserBufferTooSmall = 7
    UsbUserErrorNotMapped = 8
    UsbUserDeviceNotStarted = 9
    UsbUserNoDeviceConnected = 10
  end

  enum WDMUSB_POWER_STATE : Int32
    WdmUsbPowerNotMapped = 0
    WdmUsbPowerSystemUnspecified = 100
    WdmUsbPowerSystemWorking = 101
    WdmUsbPowerSystemSleeping1 = 102
    WdmUsbPowerSystemSleeping2 = 103
    WdmUsbPowerSystemSleeping3 = 104
    WdmUsbPowerSystemHibernate = 105
    WdmUsbPowerSystemShutdown = 106
    WdmUsbPowerDeviceUnspecified = 200
    WdmUsbPowerDeviceD0 = 201
    WdmUsbPowerDeviceD1 = 202
    WdmUsbPowerDeviceD2 = 203
    WdmUsbPowerDeviceD3 = 204
  end

  enum USBFN_EVENT : Int32
    UsbfnEventMinimum = 0
    UsbfnEventAttach = 1
    UsbfnEventReset = 2
    UsbfnEventDetach = 3
    UsbfnEventSuspend = 4
    UsbfnEventResume = 5
    UsbfnEventSetupPacket = 6
    UsbfnEventConfigured = 7
    UsbfnEventUnConfigured = 8
    UsbfnEventPortType = 9
    UsbfnEventBusTearDown = 10
    UsbfnEventSetInterface = 11
    UsbfnEventMaximum = 12
  end

  enum USBFN_PORT_TYPE : Int32
    UsbfnUnknownPort = 0
    UsbfnStandardDownstreamPort = 1
    UsbfnChargingDownstreamPort = 2
    UsbfnDedicatedChargingPort = 3
    UsbfnInvalidDedicatedChargingPort = 4
    UsbfnProprietaryDedicatedChargingPort = 5
    UsbfnPortTypeMaximum = 6
  end

  enum USBFN_BUS_SPEED : Int32
    UsbfnBusSpeedLow = 0
    UsbfnBusSpeedFull = 1
    UsbfnBusSpeedHigh = 2
    UsbfnBusSpeedSuper = 3
    UsbfnBusSpeedMaximum = 4
  end

  enum USBFN_DIRECTION : Int32
    UsbfnDirectionMinimum = 0
    UsbfnDirectionIn = 1
    UsbfnDirectionOut = 2
    UsbfnDirectionTx = 1
    UsbfnDirectionRx = 2
    UsbfnDirectionMaximum = 3
  end

  enum USBFN_DEVICE_STATE : Int32
    UsbfnDeviceStateMinimum = 0
    UsbfnDeviceStateAttached = 1
    UsbfnDeviceStateDefault = 2
    UsbfnDeviceStateDetached = 3
    UsbfnDeviceStateAddressed = 4
    UsbfnDeviceStateConfigured = 5
    UsbfnDeviceStateSuspended = 6
    UsbfnDeviceStateStateMaximum = 7
  end

  enum PIPE_TYPE : Int32
    EVENT_PIPE = 0
    READ_DATA_PIPE = 1
    WRITE_DATA_PIPE = 2
    ALL_PIPE = 3
  end

  enum RAW_PIPE_TYPE : Int32
    USBSCAN_PIPE_CONTROL = 0
    USBSCAN_PIPE_ISOCHRONOUS = 1
    USBSCAN_PIPE_BULK = 2
    USBSCAN_PIPE_INTERRUPT = 3
  end

union BM_REQUEST_TYPE
  s : BM_REQUEST_TYPE_BM
  b : UInt8
end
union USB_DEFAULT_PIPE_SETUP_PACKET_wIndex
  anonymous : USB_DEFAULT_PIPE_SETUP_PACKET_wIndex_Anonymous_e__Struct
  w : UInt16
end
union USB_DEFAULT_PIPE_SETUP_PACKET_wValue
  anonymous : USB_DEFAULT_PIPE_SETUP_PACKET_wValue_Anonymous_e__Struct
  w : UInt16
end
union USB_DEVICE_STATUS
  as_ushort16 : UInt16
  anonymous : USB_DEVICE_STATUS_Anonymous_e__Struct
end
union USB_INTERFACE_STATUS
  as_ushort16 : UInt16
  anonymous : USB_INTERFACE_STATUS_Anonymous_e__Struct
end
union USB_ENDPOINT_STATUS
  as_ushort16 : UInt16
  anonymous : USB_ENDPOINT_STATUS_Anonymous_e__Struct
end
union USB_DEVICE_CAPABILITY_USB20_EXTENSION_DESCRIPTOR_bmAttributes_e__Union
  as_ulong : UInt32
  anonymous : USB_DEVICE_CAPABILITY_USB20_EXTENSION_DESCRIPTOR_bmAttributes_e__Union_Anonymous_e__Struct
end
union USB_DEVICE_CAPABILITY_POWER_DELIVERY_DESCRIPTOR_bmAttributes_e__Union
  as_ulong : UInt32
  anonymous : USB_DEVICE_CAPABILITY_POWER_DELIVERY_DESCRIPTOR_bmAttributes_e__Union_Anonymous_e__Struct
end
union USB_DEVICE_CAPABILITY_PD_CONSUMER_PORT_DESCRIPTOR_bmCapabilities_e__Union
  as_ushort : UInt16
  anonymous : USB_DEVICE_CAPABILITY_PD_CONSUMER_PORT_DESCRIPTOR_bmCapabilities_e__Union_Anonymous_e__Struct
end
union USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED
  as_ulong32 : UInt32
  anonymous : USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_Anonymous_e__Struct
end
union USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_USB_DESCRIPTOR_wFunctionalitySupport_e__Union
  as_ushort : UInt16
  anonymous : USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_USB_DESCRIPTOR_wFunctionalitySupport_e__Union_Anonymous_e__Struct
end
union USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_USB_DESCRIPTOR_bmAttributes_e__Union
  as_ulong : UInt32
  anonymous : USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_USB_DESCRIPTOR_bmAttributes_e__Union_Anonymous_e__Struct
end
union USB_DEVICE_CAPABILITY_BILLBOARD_DESCRIPTOR_VconnPower_e__Union
  as_ushort : UInt16
  anonymous : USB_DEVICE_CAPABILITY_BILLBOARD_DESCRIPTOR_VconnPower_e__Union_Anonymous_e__Struct
end
union USB_DEVICE_CAPABILITY_FIRMWARE_STATUS_DESCRIPTOR_bmAttributes_e__Union
  as_ulong : UInt32
  anonymous : USB_DEVICE_CAPABILITY_FIRMWARE_STATUS_DESCRIPTOR_bmAttributes_e__Union_Anonymous_e__Struct
end
union USB_HIGH_SPEED_MAXPACKET
  us : UInt16
end
union USB_SUPERSPEED_ENDPOINT_COMPANION_DESCRIPTOR_bmAttributes_e__Union
  as_uchar : UInt8
  bulk : USB_SUPERSPEED_ENDPOINT_COMPANION_DESCRIPTOR_bmAttributes_e__Union_Bulk_e__Struct
  isochronous : USB_SUPERSPEED_ENDPOINT_COMPANION_DESCRIPTOR_bmAttributes_e__Union_Isochronous_e__Struct
end
union USB_HUB_STATUS
  as_ushort16 : UInt16
  anonymous : USB_HUB_STATUS_Anonymous_e__Struct
end
union USB_HUB_CHANGE
  as_ushort16 : UInt16
  anonymous : USB_HUB_CHANGE_Anonymous_e__Struct
end
union USB_HUB_STATUS_AND_CHANGE
  as_ulong32 : UInt32
  anonymous : USB_HUB_STATUS_AND_CHANGE_Anonymous_e__Struct
end
union USB_20_PORT_STATUS
  as_ushort16 : UInt16
  anonymous : USB_20_PORT_STATUS_Anonymous_e__Struct
end
union USB_20_PORT_CHANGE
  as_ushort16 : UInt16
  anonymous : USB_20_PORT_CHANGE_Anonymous_e__Struct
end
union USB_30_PORT_STATUS
  as_ushort16 : UInt16
  anonymous : USB_30_PORT_STATUS_Anonymous_e__Struct
end
union USB_30_PORT_CHANGE
  as_ushort16 : UInt16
  anonymous : USB_30_PORT_CHANGE_Anonymous_e__Struct
end
union USB_PORT_STATUS
  as_ushort16 : UInt16
  usb20_port_status : USB_20_PORT_STATUS
  usb30_port_status : USB_30_PORT_STATUS
end
union USB_PORT_CHANGE
  as_ushort16 : UInt16
  usb20_port_change : USB_20_PORT_CHANGE
  usb30_port_change : USB_30_PORT_CHANGE
end
union USB_PORT_EXT_STATUS
  as_ulong32 : UInt32
  anonymous : USB_PORT_EXT_STATUS_Anonymous_e__Struct
end
union USB_PORT_STATUS_AND_CHANGE
  as_ulong32 : UInt32
  anonymous : USB_PORT_STATUS_AND_CHANGE_Anonymous_e__Struct
end
union USB_PORT_EXT_STATUS_AND_CHANGE
  as_ulong64 : UInt64
  anonymous : USB_PORT_EXT_STATUS_AND_CHANGE_Anonymous_e__Struct
end
union USB_HUB_30_PORT_REMOTE_WAKE_MASK
  as_uchar8 : UInt8
  anonymous : USB_HUB_30_PORT_REMOTE_WAKE_MASK_Anonymous_e__Struct
end
union USB_FUNCTION_SUSPEND_OPTIONS
  as_uchar : UInt8
  anonymous : USB_FUNCTION_SUSPEND_OPTIONS_Anonymous_e__Struct
end
union OS_STRING_Anonymous_e__Union
  b_pad : UInt8
  b_flags : UInt8
end
union URB_Anonymous_e__Union
  urb_header : URB_HEADER
  urb_select_interface : URB_SELECT_INTERFACE
  urb_select_configuration : URB_SELECT_CONFIGURATION
  urb_pipe_request : URB_PIPE_REQUEST
  urb_frame_length_control : URB_FRAME_LENGTH_CONTROL
  urb_get_frame_length : URB_GET_FRAME_LENGTH
  urb_set_frame_length : URB_SET_FRAME_LENGTH
  urb_get_current_frame_number : URB_GET_CURRENT_FRAME_NUMBER
  urb_control_transfer : URB_CONTROL_TRANSFER
  urb_control_transfer_ex : URB_CONTROL_TRANSFER_EX
  urb_bulk_or_interrupt_transfer : URB_BULK_OR_INTERRUPT_TRANSFER
  urb_isochronous_transfer : URB_ISOCH_TRANSFER
  urb_control_descriptor_request : URB_CONTROL_DESCRIPTOR_REQUEST
  urb_control_get_status_request : URB_CONTROL_GET_STATUS_REQUEST
  urb_control_feature_request : URB_CONTROL_FEATURE_REQUEST
  urb_control_vendor_class_request : URB_CONTROL_VENDOR_OR_CLASS_REQUEST
  urb_control_get_interface_request : URB_CONTROL_GET_INTERFACE_REQUEST
  urb_control_get_configuration_request : URB_CONTROL_GET_CONFIGURATION_REQUEST
  urb_os_feature_descriptor_request : URB_OS_FEATURE_DESCRIPTOR_REQUEST
  urb_open_static_streams : URB_OPEN_STATIC_STREAMS
  urb_get_isoch_pipe_transfer_path_delays : URB_GET_ISOCH_PIPE_TRANSFER_PATH_DELAYS
end
union USBFN_NOTIFICATION_u_e__Union
  bus_speed : USBFN_BUS_SPEED
  setup_packet : USB_DEFAULT_PIPE_SETUP_PACKET
  configuration_value : UInt16
  port_type : USBFN_PORT_TYPE
  alternate_interface : ALTERNATE_INTERFACE
end

  struct BM_REQUEST_TYPE_BM
    _bitfield : UInt8
  end
  struct USB_DEFAULT_PIPE_SETUP_PACKET
    bm_request_type : BM_REQUEST_TYPE
    b_request : UInt8
    w_value : USB_DEFAULT_PIPE_SETUP_PACKET_wValue
    w_index : USB_DEFAULT_PIPE_SETUP_PACKET_wIndex
    w_length : UInt16
  end
  struct USB_DEFAULT_PIPE_SETUP_PACKET_wIndex_Anonymous_e__Struct
    low_byte : UInt8
    hi_byte : UInt8
  end
  struct USB_DEFAULT_PIPE_SETUP_PACKET_wValue_Anonymous_e__Struct
    low_byte : UInt8
    hi_byte : UInt8
  end
  struct USB_DEVICE_STATUS_Anonymous_e__Struct
    _bitfield : UInt16
  end
  struct USB_INTERFACE_STATUS_Anonymous_e__Struct
    _bitfield : UInt16
  end
  struct USB_ENDPOINT_STATUS_Anonymous_e__Struct
    _bitfield : UInt16
  end
  struct USB_COMMON_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
  end
  struct USB_DEVICE_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    bcd_usb : UInt16
    b_device_class : UInt8
    b_device_sub_class : UInt8
    b_device_protocol : UInt8
    b_max_packet_size0 : UInt8
    id_vendor : UInt16
    id_product : UInt16
    bcd_device : UInt16
    i_manufacturer : UInt8
    i_product : UInt8
    i_serial_number : UInt8
    b_num_configurations : UInt8
  end
  struct USB_DEVICE_QUALIFIER_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    bcd_usb : UInt16
    b_device_class : UInt8
    b_device_sub_class : UInt8
    b_device_protocol : UInt8
    b_max_packet_size0 : UInt8
    b_num_configurations : UInt8
    b_reserved : UInt8
  end
  struct USB_BOS_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    w_total_length : UInt16
    b_num_device_caps : UInt8
  end
  struct USB_DEVICE_CAPABILITY_USB20_EXTENSION_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    b_dev_capability_type : UInt8
    bm_attributes : USB_DEVICE_CAPABILITY_USB20_EXTENSION_DESCRIPTOR_bmAttributes_e__Union
  end
  struct USB_DEVICE_CAPABILITY_USB20_EXTENSION_DESCRIPTOR_bmAttributes_e__Union_Anonymous_e__Struct
    _bitfield : UInt32
  end
  struct USB_DEVICE_CAPABILITY_POWER_DELIVERY_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    b_dev_capability_type : UInt8
    b_reserved : UInt8
    bm_attributes : USB_DEVICE_CAPABILITY_POWER_DELIVERY_DESCRIPTOR_bmAttributes_e__Union
    bm_provider_ports : UInt16
    bm_consumer_ports : UInt16
    bcd_bc_version : UInt16
    bcd_pd_version : UInt16
    bcd_usb_type_c_version : UInt16
  end
  struct USB_DEVICE_CAPABILITY_POWER_DELIVERY_DESCRIPTOR_bmAttributes_e__Union_Anonymous_e__Struct
    _bitfield : UInt32
  end
  struct USB_DEVICE_CAPABILITY_PD_CONSUMER_PORT_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    b_dev_capability_type : UInt8
    b_reserved : UInt8
    bm_capabilities : USB_DEVICE_CAPABILITY_PD_CONSUMER_PORT_DESCRIPTOR_bmCapabilities_e__Union
    w_min_voltage : UInt16
    w_max_voltage : UInt16
    w_reserved : UInt16
    dw_max_operating_power : UInt32
    dw_max_peak_power : UInt32
    dw_max_peak_power_time : UInt32
  end
  struct USB_DEVICE_CAPABILITY_PD_CONSUMER_PORT_DESCRIPTOR_bmCapabilities_e__Union_Anonymous_e__Struct
    _bitfield : UInt16
  end
  struct USB_DEVICE_CAPABILITY_SUPERSPEED_USB_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    b_dev_capability_type : UInt8
    bm_attributes : UInt8
    w_speeds_supported : UInt16
    b_functionality_support : UInt8
    b_u1_dev_exit_lat : UInt8
    w_u2_dev_exit_lat : UInt16
  end
  struct USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_Anonymous_e__Struct
    _bitfield : UInt32
  end
  struct USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_USB_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    b_dev_capability_type : UInt8
    b_reserved : UInt8
    bm_attributes : USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_USB_DESCRIPTOR_bmAttributes_e__Union
    w_functionality_support : USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_USB_DESCRIPTOR_wFunctionalitySupport_e__Union
    w_reserved : UInt16
    bm_sublink_speed_attr : USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED[0]*
  end
  struct USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_USB_DESCRIPTOR_wFunctionalitySupport_e__Union_Anonymous_e__Struct
    _bitfield : UInt16
  end
  struct USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_USB_DESCRIPTOR_bmAttributes_e__Union_Anonymous_e__Struct
    _bitfield : UInt32
  end
  struct USB_DEVICE_CAPABILITY_CONTAINER_ID_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    b_dev_capability_type : UInt8
    b_reserved : UInt8
    container_id : UInt8[16]*
  end
  struct USB_DEVICE_CAPABILITY_PLATFORM_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    b_dev_capability_type : UInt8
    b_reserved : UInt8
    platform_capability_uuid : Guid
    capabilility_data : UInt8[0]*
  end
  struct USB_DEVICE_CAPABILITY_BILLBOARD_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    b_dev_capability_type : UInt8
    i_addtional_info_url : UInt8
    b_number_of_alternate_modes : UInt8
    b_preferred_alternate_mode : UInt8
    vconn_power : USB_DEVICE_CAPABILITY_BILLBOARD_DESCRIPTOR_VconnPower_e__Union
    bm_configured : UInt8[32]*
    b_reserved : UInt32
    alternate_mode : USB_DEVICE_CAPABILITY_BILLBOARD_DESCRIPTOR_Anonymous_e__Struct[0]*
  end
  struct USB_DEVICE_CAPABILITY_BILLBOARD_DESCRIPTOR_VconnPower_e__Union_Anonymous_e__Struct
    _bitfield : UInt16
  end
  struct USB_DEVICE_CAPABILITY_BILLBOARD_DESCRIPTOR_Anonymous_e__Struct
    w_svid : UInt16
    b_alternate_mode : UInt8
    i_alternate_mode_setting : UInt8
  end
  struct USB_DEVICE_CAPABILITY_FIRMWARE_STATUS_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    b_dev_capability_type : UInt8
    bcd_descriptor_version : UInt8
    bm_attributes : USB_DEVICE_CAPABILITY_FIRMWARE_STATUS_DESCRIPTOR_bmAttributes_e__Union
  end
  struct USB_DEVICE_CAPABILITY_FIRMWARE_STATUS_DESCRIPTOR_bmAttributes_e__Union_Anonymous_e__Struct
    _bitfield : UInt32
  end
  struct USB_DEVICE_CAPABILITY_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    b_dev_capability_type : UInt8
  end
  struct USB_CONFIGURATION_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    w_total_length : UInt16
    b_num_interfaces : UInt8
    b_configuration_value : UInt8
    i_configuration : UInt8
    bm_attributes : UInt8
    max_power : UInt8
  end
  struct USB_INTERFACE_ASSOCIATION_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    b_first_interface : UInt8
    b_interface_count : UInt8
    b_function_class : UInt8
    b_function_sub_class : UInt8
    b_function_protocol : UInt8
    i_function : UInt8
  end
  struct USB_INTERFACE_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    b_interface_number : UInt8
    b_alternate_setting : UInt8
    b_num_endpoints : UInt8
    b_interface_class : UInt8
    b_interface_sub_class : UInt8
    b_interface_protocol : UInt8
    i_interface : UInt8
  end
  struct USB_ENDPOINT_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    b_endpoint_address : UInt8
    bm_attributes : UInt8
    w_max_packet_size : UInt16
    b_interval : UInt8
  end
  struct USB_HIGH_SPEED_MAXPACKET_MP
    _bitfield : UInt16
  end
  struct USB_STRING_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    b_string : Char[0]*
  end
  struct USB_SUPERSPEED_ENDPOINT_COMPANION_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    b_max_burst : UInt8
    bm_attributes : USB_SUPERSPEED_ENDPOINT_COMPANION_DESCRIPTOR_bmAttributes_e__Union
    w_bytes_per_interval : UInt16
  end
  struct USB_SUPERSPEED_ENDPOINT_COMPANION_DESCRIPTOR_bmAttributes_e__Union_Bulk_e__Struct
    _bitfield : UInt8
  end
  struct USB_SUPERSPEED_ENDPOINT_COMPANION_DESCRIPTOR_bmAttributes_e__Union_Isochronous_e__Struct
    _bitfield : UInt8
  end
  struct USB_SUPERSPEEDPLUS_ISOCH_ENDPOINT_COMPANION_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    w_reserved : UInt16
    dw_bytes_per_interval : UInt32
  end
  struct USB_HUB_DESCRIPTOR
    b_descriptor_length : UInt8
    b_descriptor_type : UInt8
    b_number_of_ports : UInt8
    w_hub_characteristics : UInt16
    b_power_on_to_power_good : UInt8
    b_hub_control_current : UInt8
    b_remove_and_power_mask : UInt8[64]*
  end
  struct USB_30_HUB_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    b_number_of_ports : UInt8
    w_hub_characteristics : UInt16
    b_power_on_to_power_good : UInt8
    b_hub_control_current : UInt8
    b_hub_hdr_dec_lat : UInt8
    w_hub_delay : UInt16
    device_removable : UInt16
  end
  struct USB_HUB_STATUS_Anonymous_e__Struct
    _bitfield : UInt16
  end
  struct USB_HUB_CHANGE_Anonymous_e__Struct
    _bitfield : UInt16
  end
  struct USB_HUB_STATUS_AND_CHANGE_Anonymous_e__Struct
    hub_status : USB_HUB_STATUS
    hub_change : USB_HUB_CHANGE
  end
  struct USB_20_PORT_STATUS_Anonymous_e__Struct
    _bitfield : UInt16
  end
  struct USB_20_PORT_CHANGE_Anonymous_e__Struct
    _bitfield : UInt16
  end
  struct USB_30_PORT_STATUS_Anonymous_e__Struct
    _bitfield : UInt16
  end
  struct USB_30_PORT_CHANGE_Anonymous_e__Struct
    _bitfield : UInt16
  end
  struct USB_PORT_EXT_STATUS_Anonymous_e__Struct
    _bitfield : UInt32
  end
  struct USB_PORT_STATUS_AND_CHANGE_Anonymous_e__Struct
    port_status : USB_PORT_STATUS
    port_change : USB_PORT_CHANGE
  end
  struct USB_PORT_EXT_STATUS_AND_CHANGE_Anonymous_e__Struct
    port_status_change : USB_PORT_STATUS_AND_CHANGE
    port_ext_status : USB_PORT_EXT_STATUS
  end
  struct USB_HUB_30_PORT_REMOTE_WAKE_MASK_Anonymous_e__Struct
    _bitfield : UInt8
  end
  struct USB_FUNCTION_SUSPEND_OPTIONS_Anonymous_e__Struct
    _bitfield : UInt8
  end
  struct USB_CONFIGURATION_POWER_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    self_power_consumed_d0 : UInt8[3]*
    b_power_summary_id : UInt8
    b_bus_power_saving_d1 : UInt8
    b_self_power_saving_d1 : UInt8
    b_bus_power_saving_d2 : UInt8
    b_self_power_saving_d2 : UInt8
    b_bus_power_saving_d3 : UInt8
    b_self_power_saving_d3 : UInt8
    transition_time_from_d1 : UInt16
    transition_time_from_d2 : UInt16
    transition_time_from_d3 : UInt16
  end
  struct USB_INTERFACE_POWER_DESCRIPTOR
    b_length : UInt8
    b_descriptor_type : UInt8
    bm_capabilities_flags : UInt8
    b_bus_power_saving_d1 : UInt8
    b_self_power_saving_d1 : UInt8
    b_bus_power_saving_d2 : UInt8
    b_self_power_saving_d2 : UInt8
    b_bus_power_saving_d3 : UInt8
    b_self_power_saving_d3 : UInt8
    transition_time_from_d1 : UInt16
    transition_time_from_d2 : UInt16
    transition_time_from_d3 : UInt16
  end
  struct USBD_VERSION_INFORMATION
    usbdi_version : UInt32
    supported_usb_version : UInt32
  end
  struct USBD_DEVICE_INFORMATION
    offset_next : UInt32
    usbd_device_handle : Void*
    device_descriptor : USB_DEVICE_DESCRIPTOR
  end
  struct USBD_PIPE_INFORMATION
    maximum_packet_size : UInt16
    endpoint_address : UInt8
    interval : UInt8
    pipe_type : USBD_PIPE_TYPE
    pipe_handle : Void*
    maximum_transfer_size : UInt32
    pipe_flags : UInt32
  end
  struct USBD_ENDPOINT_OFFLOAD_INFORMATION
    size : UInt32
    endpoint_address : UInt16
    resource_id : UInt32
    mode : USBD_ENDPOINT_OFFLOAD_MODE
    _bitfield1 : UInt32
    _bitfield2 : UInt32
    transfer_segment_la : LARGE_INTEGER
    transfer_segment_va : Void*
    transfer_ring_size : LibC::UINT_PTR
    transfer_ring_initial_cycle_bit : UInt32
    message_number : UInt32
    event_ring_segment_la : LARGE_INTEGER
    event_ring_segment_va : Void*
    event_ring_size : LibC::UINT_PTR
    event_ring_initial_cycle_bit : UInt32
  end
  struct USBD_INTERFACE_INFORMATION
    length : UInt16
    interface_number : UInt8
    alternate_setting : UInt8
    class : UInt8
    sub_class : UInt8
    protocol : UInt8
    reserved : UInt8
    interface_handle : Void*
    number_of_pipes : UInt32
    pipes : USBD_PIPE_INFORMATION[0]*
  end
  struct URB_HCD_AREA
    reserved8 : Void[8]**
  end
  struct URB_HEADER
    length : UInt16
    function : UInt16
    status : Int32
    usbd_device_handle : Void*
    usbd_flags : UInt32
  end
  struct URB_SELECT_INTERFACE
    hdr : URB_HEADER
    configuration_handle : Void*
    interface : USBD_INTERFACE_INFORMATION
  end
  struct URB_SELECT_CONFIGURATION
    hdr : URB_HEADER
    configuration_descriptor : USB_CONFIGURATION_DESCRIPTOR*
    configuration_handle : Void*
    interface : USBD_INTERFACE_INFORMATION
  end
  struct URB_PIPE_REQUEST
    hdr : URB_HEADER
    pipe_handle : Void*
    reserved : UInt32
  end
  struct URB_FRAME_LENGTH_CONTROL
    hdr : URB_HEADER
  end
  struct URB_GET_FRAME_LENGTH
    hdr : URB_HEADER
    frame_length : UInt32
    frame_number : UInt32
  end
  struct URB_SET_FRAME_LENGTH
    hdr : URB_HEADER
    frame_length_delta : Int32
  end
  struct URB_GET_CURRENT_FRAME_NUMBER
    hdr : URB_HEADER
    frame_number : UInt32
  end
  struct URB_CONTROL_DESCRIPTOR_REQUEST
    hdr : URB_HEADER
    reserved : Void*
    reserved0 : UInt32
    transfer_buffer_length : UInt32
    transfer_buffer : Void*
    transfer_buffer_mdl : Void*
    urb_link : URB*
    hca : URB_HCD_AREA
    reserved1 : UInt16
    index : UInt8
    descriptor_type : UInt8
    language_id : UInt16
    reserved2 : UInt16
  end
  struct URB_CONTROL_GET_STATUS_REQUEST
    hdr : URB_HEADER
    reserved : Void*
    reserved0 : UInt32
    transfer_buffer_length : UInt32
    transfer_buffer : Void*
    transfer_buffer_mdl : Void*
    urb_link : URB*
    hca : URB_HCD_AREA
    reserved1 : UInt8[4]*
    index : UInt16
    reserved2 : UInt16
  end
  struct URB_CONTROL_FEATURE_REQUEST
    hdr : URB_HEADER
    reserved : Void*
    reserved2 : UInt32
    reserved3 : UInt32
    reserved4 : Void*
    reserved5 : Void*
    urb_link : URB*
    hca : URB_HCD_AREA
    reserved0 : UInt16
    feature_selector : UInt16
    index : UInt16
    reserved1 : UInt16
  end
  struct URB_CONTROL_VENDOR_OR_CLASS_REQUEST
    hdr : URB_HEADER
    reserved : Void*
    transfer_flags : UInt32
    transfer_buffer_length : UInt32
    transfer_buffer : Void*
    transfer_buffer_mdl : Void*
    urb_link : URB*
    hca : URB_HCD_AREA
    request_type_reserved_bits : UInt8
    request : UInt8
    value : UInt16
    index : UInt16
    reserved1 : UInt16
  end
  struct URB_CONTROL_GET_INTERFACE_REQUEST
    hdr : URB_HEADER
    reserved : Void*
    reserved0 : UInt32
    transfer_buffer_length : UInt32
    transfer_buffer : Void*
    transfer_buffer_mdl : Void*
    urb_link : URB*
    hca : URB_HCD_AREA
    reserved1 : UInt8[4]*
    interface : UInt16
    reserved2 : UInt16
  end
  struct URB_CONTROL_GET_CONFIGURATION_REQUEST
    hdr : URB_HEADER
    reserved : Void*
    reserved0 : UInt32
    transfer_buffer_length : UInt32
    transfer_buffer : Void*
    transfer_buffer_mdl : Void*
    urb_link : URB*
    hca : URB_HCD_AREA
    reserved1 : UInt8[8]*
  end
  struct OS_STRING
    b_length : UInt8
    b_descriptor_type : UInt8
    microsoft_string : Char[7]*
    b_vendor_code : UInt8
    anonymous : OS_STRING_Anonymous_e__Union
  end
  struct URB_OS_FEATURE_DESCRIPTOR_REQUEST
    hdr : URB_HEADER
    reserved : Void*
    reserved0 : UInt32
    transfer_buffer_length : UInt32
    transfer_buffer : Void*
    transfer_buffer_mdl : Void*
    urb_link : URB*
    hca : URB_HCD_AREA
    _bitfield : UInt8
    reserved2 : UInt8
    interface_number : UInt8
    ms_page_index : UInt8
    ms_feature_descriptor_index : UInt16
    reserved3 : UInt16
  end
  struct URB_CONTROL_TRANSFER
    hdr : URB_HEADER
    pipe_handle : Void*
    transfer_flags : UInt32
    transfer_buffer_length : UInt32
    transfer_buffer : Void*
    transfer_buffer_mdl : Void*
    urb_link : URB*
    hca : URB_HCD_AREA
    setup_packet : UInt8[8]*
  end
  struct URB_CONTROL_TRANSFER_EX
    hdr : URB_HEADER
    pipe_handle : Void*
    transfer_flags : UInt32
    transfer_buffer_length : UInt32
    transfer_buffer : Void*
    transfer_buffer_mdl : Void*
    timeout : UInt32
    hca : URB_HCD_AREA
    setup_packet : UInt8[8]*
  end
  struct URB_BULK_OR_INTERRUPT_TRANSFER
    hdr : URB_HEADER
    pipe_handle : Void*
    transfer_flags : UInt32
    transfer_buffer_length : UInt32
    transfer_buffer : Void*
    transfer_buffer_mdl : Void*
    urb_link : URB*
    hca : URB_HCD_AREA
  end
  struct USBD_ISO_PACKET_DESCRIPTOR
    offset : UInt32
    length : UInt32
    status : Int32
  end
  struct URB_ISOCH_TRANSFER
    hdr : URB_HEADER
    pipe_handle : Void*
    transfer_flags : UInt32
    transfer_buffer_length : UInt32
    transfer_buffer : Void*
    transfer_buffer_mdl : Void*
    urb_link : URB*
    hca : URB_HCD_AREA
    start_frame : UInt32
    number_of_packets : UInt32
    error_count : UInt32
    iso_packet : USBD_ISO_PACKET_DESCRIPTOR[0]*
  end
  struct USBD_STREAM_INFORMATION
    pipe_handle : Void*
    stream_id : UInt32
    maximum_transfer_size : UInt32
    pipe_flags : UInt32
  end
  struct URB_OPEN_STATIC_STREAMS
    hdr : URB_HEADER
    pipe_handle : Void*
    number_of_streams : UInt32
    stream_info_version : UInt16
    stream_info_size : UInt16
    streams : USBD_STREAM_INFORMATION*
  end
  struct URB_GET_ISOCH_PIPE_TRANSFER_PATH_DELAYS
    hdr : URB_HEADER
    pipe_handle : Void*
    maximum_send_path_delay_in_milli_seconds : UInt32
    maximum_completion_path_delay_in_milli_seconds : UInt32
  end
  struct URB
    anonymous : URB_Anonymous_e__Union
  end
  struct USB_IDLE_CALLBACK_INFO
    idle_callback : USB_IDLE_CALLBACK
    idle_context : Void*
  end
  struct USBUSER_REQUEST_HEADER
    usb_user_request : UInt32
    usb_user_status_code : USB_USER_ERROR_CODE
    request_buffer_length : UInt32
    actual_buffer_length : UInt32
  end
  struct PACKET_PARAMETERS
    device_address : UInt8
    endpoint_address : UInt8
    maximum_packet_size : UInt16
    timeout : UInt32
    flags : UInt32
    data_length : UInt32
    hub_device_address : UInt16
    port_tt_number : UInt16
    error_count : UInt8
    pad : UInt8[3]*
    usbd_status_code : Int32
    data : UInt8[4]*
  end
  struct USBUSER_SEND_ONE_PACKET
    header : USBUSER_REQUEST_HEADER
    packet_parameters : PACKET_PARAMETERS
  end
  struct RAW_RESET_PORT_PARAMETERS
    port_number : UInt16
    port_status : UInt16
  end
  struct USBUSER_RAW_RESET_ROOT_PORT
    header : USBUSER_REQUEST_HEADER
    parameters : RAW_RESET_PORT_PARAMETERS
  end
  struct RAW_ROOTPORT_FEATURE
    port_number : UInt16
    port_feature : UInt16
    port_status : UInt16
  end
  struct USBUSER_ROOTPORT_FEATURE_REQUEST
    header : USBUSER_REQUEST_HEADER
    parameters : RAW_ROOTPORT_FEATURE
  end
  struct RAW_ROOTPORT_PARAMETERS
    port_number : UInt16
    port_status : UInt16
  end
  struct USBUSER_ROOTPORT_PARAMETERS
    header : USBUSER_REQUEST_HEADER
    parameters : RAW_ROOTPORT_PARAMETERS
  end
  struct USB_CONTROLLER_INFO_0
    pci_vendor_id : UInt32
    pci_device_id : UInt32
    pci_revision : UInt32
    number_of_root_ports : UInt32
    controller_flavor : USB_CONTROLLER_FLAVOR
    hc_feature_flags : UInt32
  end
  struct USBUSER_CONTROLLER_INFO_0
    header : USBUSER_REQUEST_HEADER
    info0 : USB_CONTROLLER_INFO_0
  end
  struct USB_UNICODE_NAME
    length : UInt32
    string : Char[0]*
  end
  struct USBUSER_CONTROLLER_UNICODE_NAME
    header : USBUSER_REQUEST_HEADER
    unicode_name : USB_UNICODE_NAME
  end
  struct USB_PASS_THRU_PARAMETERS
    function_guid : Guid
    parameter_length : UInt32
    parameters : UInt8[4]*
  end
  struct USBUSER_PASS_THRU_REQUEST
    header : USBUSER_REQUEST_HEADER
    pass_thru : USB_PASS_THRU_PARAMETERS
  end
  struct USB_POWER_INFO
    system_state : WDMUSB_POWER_STATE
    hc_device_power_state : WDMUSB_POWER_STATE
    hc_device_wake : WDMUSB_POWER_STATE
    hc_system_wake : WDMUSB_POWER_STATE
    rh_device_power_state : WDMUSB_POWER_STATE
    rh_device_wake : WDMUSB_POWER_STATE
    rh_system_wake : WDMUSB_POWER_STATE
    last_system_sleep_state : WDMUSB_POWER_STATE
    can_wakeup : BOOLEAN
    is_powered : BOOLEAN
  end
  struct USBUSER_POWER_INFO_REQUEST
    header : USBUSER_REQUEST_HEADER
    power_information : USB_POWER_INFO
  end
  struct USB_OPEN_RAW_DEVICE_PARAMETERS
    port_status : UInt16
    max_packet_ep0 : UInt16
  end
  struct USBUSER_OPEN_RAW_DEVICE
    header : USBUSER_REQUEST_HEADER
    parameters : USB_OPEN_RAW_DEVICE_PARAMETERS
  end
  struct USB_CLOSE_RAW_DEVICE_PARAMETERS
    xxx : UInt32
  end
  struct USBUSER_CLOSE_RAW_DEVICE
    header : USBUSER_REQUEST_HEADER
    parameters : USB_CLOSE_RAW_DEVICE_PARAMETERS
  end
  struct USB_SEND_RAW_COMMAND_PARAMETERS
    usb_bm_request : UInt8
    usb_b_request : UInt8
    usb_w_vlaue : UInt16
    usb_w_index : UInt16
    usb_w_length : UInt16
    device_address : UInt16
    maximum_packet_size : UInt16
    timeout : UInt32
    data_length : UInt32
    usbd_status_code : Int32
    data : UInt8[4]*
  end
  struct USBUSER_SEND_RAW_COMMAND
    header : USBUSER_REQUEST_HEADER
    parameters : USB_SEND_RAW_COMMAND_PARAMETERS
  end
  struct USB_BANDWIDTH_INFO
    device_count : UInt32
    total_bus_bandwidth : UInt32
    total32sec_bandwidth : UInt32
    alloced_bulk_and_control : UInt32
    alloced_iso : UInt32
    alloced_interrupt_1ms : UInt32
    alloced_interrupt_2ms : UInt32
    alloced_interrupt_4ms : UInt32
    alloced_interrupt_8ms : UInt32
    alloced_interrupt_16ms : UInt32
    alloced_interrupt_32ms : UInt32
  end
  struct USBUSER_BANDWIDTH_INFO_REQUEST
    header : USBUSER_REQUEST_HEADER
    bandwidth_information : USB_BANDWIDTH_INFO
  end
  struct USB_BUS_STATISTICS_0
    device_count : UInt32
    current_system_time : LARGE_INTEGER
    current_usb_frame : UInt32
    bulk_bytes : UInt32
    iso_bytes : UInt32
    interrupt_bytes : UInt32
    control_data_bytes : UInt32
    pci_interrupt_count : UInt32
    hard_reset_count : UInt32
    worker_signal_count : UInt32
    common_buffer_bytes : UInt32
    worker_idle_time_ms : UInt32
    root_hub_enabled : BOOLEAN
    root_hub_device_power_state : UInt8
    unused : UInt8
    name_index : UInt8
  end
  struct USBUSER_BUS_STATISTICS_0_REQUEST
    header : USBUSER_REQUEST_HEADER
    bus_statistics0 : USB_BUS_STATISTICS_0
  end
  struct USB_DRIVER_VERSION_PARAMETERS
    driver_tracking_code : UInt32
    usbdi_version : UInt32
    usbuser_version : UInt32
    checked_port_driver : BOOLEAN
    checked_miniport_driver : BOOLEAN
    usb_version : UInt16
  end
  struct USBUSER_GET_DRIVER_VERSION
    header : USBUSER_REQUEST_HEADER
    parameters : USB_DRIVER_VERSION_PARAMETERS
  end
  struct USB_USB2HW_VERSION_PARAMETERS
    usb2_hw_revision : UInt8
  end
  struct USBUSER_GET_USB2HW_VERSION
    header : USBUSER_REQUEST_HEADER
    parameters : USB_USB2HW_VERSION_PARAMETERS
  end
  struct USBUSER_REFRESH_HCT_REG
    header : USBUSER_REQUEST_HEADER
    flags : UInt32
  end
  struct WINUSB_PIPE_INFORMATION
    pipe_type : USBD_PIPE_TYPE
    pipe_id : UInt8
    maximum_packet_size : UInt16
    interval : UInt8
  end
  struct WINUSB_PIPE_INFORMATION_EX
    pipe_type : USBD_PIPE_TYPE
    pipe_id : UInt8
    maximum_packet_size : UInt16
    interval : UInt8
    maximum_bytes_per_interval : UInt32
  end
  struct WINUSB_SETUP_PACKET
    request_type : UInt8
    request : UInt8
    value : UInt16
    index : UInt16
    length : UInt16
  end
  struct USB_START_TRACKING_FOR_TIME_SYNC_INFORMATION
    time_tracking_handle : LibC::HANDLE
    is_startup_delay_tolerable : BOOLEAN
  end
  struct USB_STOP_TRACKING_FOR_TIME_SYNC_INFORMATION
    time_tracking_handle : LibC::HANDLE
  end
  struct USB_FRAME_NUMBER_AND_QPC_FOR_TIME_SYNC_INFORMATION
    time_tracking_handle : LibC::HANDLE
    input_frame_number : UInt32
    input_micro_frame_number : UInt32
    query_performance_counter_at_input_frame_or_micro_frame : LARGE_INTEGER
    query_performance_counter_frequency : LARGE_INTEGER
    predicted_accuracy_in_micro_seconds : UInt32
    current_generation_id : UInt32
    current_query_performance_counter : LARGE_INTEGER
    current_hardware_frame_number : UInt32
    current_hardware_micro_frame_number : UInt32
    current_usb_frame_number : UInt32
  end
  struct ALTERNATE_INTERFACE
    interface_number : UInt16
    alternate_interface_number : UInt16
  end
  struct USBFN_NOTIFICATION
    event : USBFN_EVENT
    u : USBFN_NOTIFICATION_u_e__Union
  end
  struct USBFN_PIPE_INFORMATION
    ep_desc : USB_ENDPOINT_DESCRIPTOR
    pipe_id : UInt32
  end
  struct USBFN_CLASS_INTERFACE
    interface_number : UInt8
    pipe_count : UInt8
    pipe_arr : USBFN_PIPE_INFORMATION[16]*
  end
  struct USBFN_CLASS_INFORMATION_PACKET
    full_speed_class_interface : USBFN_CLASS_INTERFACE
    high_speed_class_interface : USBFN_CLASS_INTERFACE
    interface_name : Char[40]*
    interface_guid : Char[39]*
    has_interface_guid : BOOLEAN
    super_speed_class_interface : USBFN_CLASS_INTERFACE
  end
  struct USBFN_CLASS_INTERFACE_EX
    base_interface_number : UInt8
    interface_count : UInt8
    pipe_count : UInt8
    pipe_arr : USBFN_PIPE_INFORMATION[16]*
  end
  struct USBFN_CLASS_INFORMATION_PACKET_EX
    full_speed_class_interface_ex : USBFN_CLASS_INTERFACE_EX
    high_speed_class_interface_ex : USBFN_CLASS_INTERFACE_EX
    super_speed_class_interface_ex : USBFN_CLASS_INTERFACE_EX
    interface_name : Char[40]*
    interface_guid : Char[39]*
    has_interface_guid : BOOLEAN
  end
  struct USBFN_INTERFACE_INFO
    interface_number : UInt8
    speed : USBFN_BUS_SPEED
    size : UInt16
    interface_descriptor_set : UInt8[0]*
  end
  struct USBFN_USB_STRING
    string_index : UInt8
    usb_string : Char[255]*
  end
  struct USBFN_BUS_CONFIGURATION_INFO
    configuration_name : Char[40]*
    is_current : BOOLEAN
    is_active : BOOLEAN
  end
  struct DRV_VERSION
    major : UInt32
    minor : UInt32
    internal : UInt32
  end
  struct IO_BLOCK
    u_offset : UInt32
    u_length : UInt32
    pby_data : UInt8*
    u_index : UInt32
  end
  struct IO_BLOCK_EX
    u_offset : UInt32
    u_length : UInt32
    pby_data : UInt8*
    u_index : UInt32
    b_request : UInt8
    bm_request_type : UInt8
    f_transfer_direction_in : UInt8
  end
  struct CHANNEL_INFO
    event_channel_size : UInt32
    u_read_data_alignment : UInt32
    u_write_data_alignment : UInt32
  end
  struct USBSCAN_GET_DESCRIPTOR
    descriptor_type : UInt8
    index : UInt8
    language_id : UInt16
  end
  struct DEVICE_DESCRIPTOR
    us_vendor_id : UInt16
    us_product_id : UInt16
    us_bcd_device : UInt16
    us_language_id : UInt16
  end
  struct USBSCAN_PIPE_INFORMATION
    maximum_packet_size : UInt16
    endpoint_address : UInt8
    interval : UInt8
    pipe_type : RAW_PIPE_TYPE
  end
  struct USBSCAN_PIPE_CONFIGURATION
    number_of_pipes : UInt32
    pipe_info : USBSCAN_PIPE_INFORMATION[8]*
  end
  struct USBSCAN_TIMEOUT
    timeout_read : UInt32
    timeout_write : UInt32
    timeout_event : UInt32
  end


  # Params # devicehandle : LibC::HANDLE [In],interfacehandle : Void** [In]
  fun WinUsb_Initialize(devicehandle : LibC::HANDLE, interfacehandle : Void**) : LibC::BOOL

  # Params # interfacehandle : Void* [In]
  fun WinUsb_Free(interfacehandle : Void*) : LibC::BOOL

  # Params # interfacehandle : Void* [In],associatedinterfaceindex : UInt8 [In],associatedinterfacehandle : Void** [In]
  fun WinUsb_GetAssociatedInterface(interfacehandle : Void*, associatedinterfaceindex : UInt8, associatedinterfacehandle : Void**) : LibC::BOOL

  # Params # interfacehandle : Void* [In],descriptortype : UInt8 [In],index : UInt8 [In],languageid : UInt16 [In],buffer : UInt8* [In],bufferlength : UInt32 [In],lengthtransferred : UInt32* [In]
  fun WinUsb_GetDescriptor(interfacehandle : Void*, descriptortype : UInt8, index : UInt8, languageid : UInt16, buffer : UInt8*, bufferlength : UInt32, lengthtransferred : UInt32*) : LibC::BOOL

  # Params # interfacehandle : Void* [In],alternateinterfacenumber : UInt8 [In],usbaltinterfacedescriptor : USB_INTERFACE_DESCRIPTOR* [In]
  fun WinUsb_QueryInterfaceSettings(interfacehandle : Void*, alternateinterfacenumber : UInt8, usbaltinterfacedescriptor : USB_INTERFACE_DESCRIPTOR*) : LibC::BOOL

  # Params # interfacehandle : Void* [In],informationtype : UInt32 [In],bufferlength : UInt32* [In],buffer : Void* [In]
  fun WinUsb_QueryDeviceInformation(interfacehandle : Void*, informationtype : UInt32, bufferlength : UInt32*, buffer : Void*) : LibC::BOOL

  # Params # interfacehandle : Void* [In],settingnumber : UInt8 [In]
  fun WinUsb_SetCurrentAlternateSetting(interfacehandle : Void*, settingnumber : UInt8) : LibC::BOOL

  # Params # interfacehandle : Void* [In],settingnumber : UInt8* [In]
  fun WinUsb_GetCurrentAlternateSetting(interfacehandle : Void*, settingnumber : UInt8*) : LibC::BOOL

  # Params # interfacehandle : Void* [In],alternateinterfacenumber : UInt8 [In],pipeindex : UInt8 [In],pipeinformation : WINUSB_PIPE_INFORMATION* [In]
  fun WinUsb_QueryPipe(interfacehandle : Void*, alternateinterfacenumber : UInt8, pipeindex : UInt8, pipeinformation : WINUSB_PIPE_INFORMATION*) : LibC::BOOL

  # Params # interfacehandle : Void* [In],alternatesettingnumber : UInt8 [In],pipeindex : UInt8 [In],pipeinformationex : WINUSB_PIPE_INFORMATION_EX* [In]
  fun WinUsb_QueryPipeEx(interfacehandle : Void*, alternatesettingnumber : UInt8, pipeindex : UInt8, pipeinformationex : WINUSB_PIPE_INFORMATION_EX*) : LibC::BOOL

  # Params # interfacehandle : Void* [In],pipeid : UInt8 [In],policytype : UInt32 [In],valuelength : UInt32 [In],value : Void* [In]
  fun WinUsb_SetPipePolicy(interfacehandle : Void*, pipeid : UInt8, policytype : UInt32, valuelength : UInt32, value : Void*) : LibC::BOOL

  # Params # interfacehandle : Void* [In],pipeid : UInt8 [In],policytype : UInt32 [In],valuelength : UInt32* [In],value : Void* [In]
  fun WinUsb_GetPipePolicy(interfacehandle : Void*, pipeid : UInt8, policytype : UInt32, valuelength : UInt32*, value : Void*) : LibC::BOOL

  # Params # interfacehandle : Void* [In],pipeid : UInt8 [In],buffer : UInt8* [In],bufferlength : UInt32 [In],lengthtransferred : UInt32* [In],overlapped : OVERLAPPED* [In]
  fun WinUsb_ReadPipe(interfacehandle : Void*, pipeid : UInt8, buffer : UInt8*, bufferlength : UInt32, lengthtransferred : UInt32*, overlapped : OVERLAPPED*) : LibC::BOOL

  # Params # interfacehandle : Void* [In],pipeid : UInt8 [In],buffer : UInt8* [In],bufferlength : UInt32 [In],lengthtransferred : UInt32* [In],overlapped : OVERLAPPED* [In]
  fun WinUsb_WritePipe(interfacehandle : Void*, pipeid : UInt8, buffer : UInt8*, bufferlength : UInt32, lengthtransferred : UInt32*, overlapped : OVERLAPPED*) : LibC::BOOL

  # Params # interfacehandle : Void* [In],setuppacket : WINUSB_SETUP_PACKET [In],buffer : UInt8* [In],bufferlength : UInt32 [In],lengthtransferred : UInt32* [In],overlapped : OVERLAPPED* [In]
  fun WinUsb_ControlTransfer(interfacehandle : Void*, setuppacket : WINUSB_SETUP_PACKET, buffer : UInt8*, bufferlength : UInt32, lengthtransferred : UInt32*, overlapped : OVERLAPPED*) : LibC::BOOL

  # Params # interfacehandle : Void* [In],pipeid : UInt8 [In]
  fun WinUsb_ResetPipe(interfacehandle : Void*, pipeid : UInt8) : LibC::BOOL

  # Params # interfacehandle : Void* [In],pipeid : UInt8 [In]
  fun WinUsb_AbortPipe(interfacehandle : Void*, pipeid : UInt8) : LibC::BOOL

  # Params # interfacehandle : Void* [In],pipeid : UInt8 [In]
  fun WinUsb_FlushPipe(interfacehandle : Void*, pipeid : UInt8) : LibC::BOOL

  # Params # interfacehandle : Void* [In],policytype : UInt32 [In],valuelength : UInt32 [In],value : Void* [In]
  fun WinUsb_SetPowerPolicy(interfacehandle : Void*, policytype : UInt32, valuelength : UInt32, value : Void*) : LibC::BOOL

  # Params # interfacehandle : Void* [In],policytype : UInt32 [In],valuelength : UInt32* [In],value : Void* [In]
  fun WinUsb_GetPowerPolicy(interfacehandle : Void*, policytype : UInt32, valuelength : UInt32*, value : Void*) : LibC::BOOL

  # Params # interfacehandle : Void* [In],lpoverlapped : OVERLAPPED* [In],lpnumberofbytestransferred : UInt32* [In],bwait : LibC::BOOL [In]
  fun WinUsb_GetOverlappedResult(interfacehandle : Void*, lpoverlapped : OVERLAPPED*, lpnumberofbytestransferred : UInt32*, bwait : LibC::BOOL) : LibC::BOOL

  # Params # configurationdescriptor : USB_CONFIGURATION_DESCRIPTOR* [In],startposition : Void* [In],interfacenumber : Int32 [In],alternatesetting : Int32 [In],interfaceclass : Int32 [In],interfacesubclass : Int32 [In],interfaceprotocol : Int32 [In]
  fun WinUsb_ParseConfigurationDescriptor(configurationdescriptor : USB_CONFIGURATION_DESCRIPTOR*, startposition : Void*, interfacenumber : Int32, alternatesetting : Int32, interfaceclass : Int32, interfacesubclass : Int32, interfaceprotocol : Int32) : USB_INTERFACE_DESCRIPTOR*

  # Params # descriptorbuffer : Void* [In],totallength : UInt32 [In],startposition : Void* [In],descriptortype : Int32 [In]
  fun WinUsb_ParseDescriptors(descriptorbuffer : Void*, totallength : UInt32, startposition : Void*, descriptortype : Int32) : USB_COMMON_DESCRIPTOR*

  # Params # interfacehandle : Void* [In],currentframenumber : UInt32* [In],timestamp : LARGE_INTEGER* [In]
  fun WinUsb_GetCurrentFrameNumber(interfacehandle : Void*, currentframenumber : UInt32*, timestamp : LARGE_INTEGER*) : LibC::BOOL

  # Params # currentframenumber : UInt32* [In],timestamp : LARGE_INTEGER [In]
  fun WinUsb_GetAdjustedFrameNumber(currentframenumber : UInt32*, timestamp : LARGE_INTEGER) : LibC::BOOL

  # Params # interfacehandle : Void* [In],pipeid : UInt8 [In],buffer : UInt8* [In],bufferlength : UInt32 [In],isochbufferhandle : Void** [In]
  fun WinUsb_RegisterIsochBuffer(interfacehandle : Void*, pipeid : UInt8, buffer : UInt8*, bufferlength : UInt32, isochbufferhandle : Void**) : LibC::BOOL

  # Params # isochbufferhandle : Void* [In]
  fun WinUsb_UnregisterIsochBuffer(isochbufferhandle : Void*) : LibC::BOOL

  # Params # bufferhandle : Void* [In],offset : UInt32 [In],length : UInt32 [In],framenumber : UInt32* [In],overlapped : OVERLAPPED* [In]
  fun WinUsb_WriteIsochPipe(bufferhandle : Void*, offset : UInt32, length : UInt32, framenumber : UInt32*, overlapped : OVERLAPPED*) : LibC::BOOL

  # Params # bufferhandle : Void* [In],offset : UInt32 [In],length : UInt32 [In],framenumber : UInt32* [In],numberofpackets : UInt32 [In],isopacketdescriptors : USBD_ISO_PACKET_DESCRIPTOR* [In],overlapped : OVERLAPPED* [In]
  fun WinUsb_ReadIsochPipe(bufferhandle : Void*, offset : UInt32, length : UInt32, framenumber : UInt32*, numberofpackets : UInt32, isopacketdescriptors : USBD_ISO_PACKET_DESCRIPTOR*, overlapped : OVERLAPPED*) : LibC::BOOL

  # Params # bufferhandle : Void* [In],offset : UInt32 [In],length : UInt32 [In],continuestream : LibC::BOOL [In],overlapped : OVERLAPPED* [In]
  fun WinUsb_WriteIsochPipeAsap(bufferhandle : Void*, offset : UInt32, length : UInt32, continuestream : LibC::BOOL, overlapped : OVERLAPPED*) : LibC::BOOL

  # Params # bufferhandle : Void* [In],offset : UInt32 [In],length : UInt32 [In],continuestream : LibC::BOOL [In],numberofpackets : UInt32 [In],isopacketdescriptors : USBD_ISO_PACKET_DESCRIPTOR* [In],overlapped : OVERLAPPED* [In]
  fun WinUsb_ReadIsochPipeAsap(bufferhandle : Void*, offset : UInt32, length : UInt32, continuestream : LibC::BOOL, numberofpackets : UInt32, isopacketdescriptors : USBD_ISO_PACKET_DESCRIPTOR*, overlapped : OVERLAPPED*) : LibC::BOOL

  # Params # interfacehandle : Void* [In],starttrackinginfo : USB_START_TRACKING_FOR_TIME_SYNC_INFORMATION* [In]
  fun WinUsb_StartTrackingForTimeSync(interfacehandle : Void*, starttrackinginfo : USB_START_TRACKING_FOR_TIME_SYNC_INFORMATION*) : LibC::BOOL

  # Params # interfacehandle : Void* [In],frameqpcinfo : USB_FRAME_NUMBER_AND_QPC_FOR_TIME_SYNC_INFORMATION* [In]
  fun WinUsb_GetCurrentFrameNumberAndQpc(interfacehandle : Void*, frameqpcinfo : USB_FRAME_NUMBER_AND_QPC_FOR_TIME_SYNC_INFORMATION*) : LibC::BOOL

  # Params # interfacehandle : Void* [In],stoptrackinginfo : USB_STOP_TRACKING_FOR_TIME_SYNC_INFORMATION* [In]
  fun WinUsb_StopTrackingForTimeSync(interfacehandle : Void*, stoptrackinginfo : USB_STOP_TRACKING_FOR_TIME_SYNC_INFORMATION*) : LibC::BOOL
end
