require "./../foundation.cr"
require "./../system/io.cr"

module Win32cr::Devices::Usb
  alias USB_IDLE_CALLBACK = Proc(Void*, Void)*

  SHORT_PACKET_TERMINATE = 1_u32
  AUTO_CLEAR_STALL = 2_u32
  PIPE_TRANSFER_TIMEOUT = 3_u32
  IGNORE_SHORT_PACKETS = 4_u32
  ALLOW_PARTIAL_READS = 5_u32
  AUTO_FLUSH = 6_u32
  RAW_IO = 7_u32
  MAXIMUM_TRANSFER_SIZE = 8_u32
  RESET_PIPE_ON_RESUME = 9_u32
  AUTO_SUSPEND = 129_u32
  SUSPEND_DELAY = 131_u32
  DEVICE_SPEED = 1_u32
  LowSpeed = 1_u32
  FullSpeed = 2_u32
  HighSpeed = 3_u32
  IOCTL_GENERICUSBFN_TRANSFER_IN = 2277389_u32
  IOCTL_GENERICUSBFN_TRANSFER_IN_APPEND_ZERO_PKT = 2277393_u32
  IOCTL_GENERICUSBFN_TRANSFER_OUT = 2277398_u32
  IOCTL_GENERICUSBFN_CONTROL_STATUS_HANDSHAKE_IN = 2277400_u32
  IOCTL_GENERICUSBFN_CONTROL_STATUS_HANDSHAKE_OUT = 2277404_u32
  IOCTL_GENERICUSBFN_GET_CLASS_INFO = 2277410_u32
  IOCTL_GENERICUSBFN_GET_PIPE_STATE = 2277414_u32
  IOCTL_GENERICUSBFN_SET_PIPE_STATE = 2277417_u32
  IOCTL_GENERICUSBFN_ACTIVATE_USB_BUS = 2277420_u32
  IOCTL_GENERICUSBFN_DEACTIVATE_USB_BUS = 2277424_u32
  IOCTL_GENERICUSBFN_BUS_EVENT_NOTIFICATION = 2277430_u32
  IOCTL_GENERICUSBFN_GET_CLASS_INFO_EX = 2277434_u32
  IOCTL_GENERICUSBFN_GET_INTERFACE_DESCRIPTOR_SET = 2277438_u32
  IOCTL_GENERICUSBFN_REGISTER_USB_STRING = 2277441_u32
  USBUSER_VERSION = 4_u32
  USBUSER_GET_CONTROLLER_INFO_0 = 1_u32
  USBUSER_GET_CONTROLLER_DRIVER_KEY = 2_u32
  USBUSER_PASS_THRU = 3_u32
  USBUSER_GET_POWER_STATE_MAP = 4_u32
  USBUSER_GET_BANDWIDTH_INFORMATION = 5_u32
  USBUSER_GET_BUS_STATISTICS_0 = 6_u32
  USBUSER_GET_ROOTHUB_SYMBOLIC_NAME = 7_u32
  USBUSER_GET_USB_DRIVER_VERSION = 8_u32
  USBUSER_GET_USB2_HW_VERSION = 9_u32
  USBUSER_USB_REFRESH_HCT_REG = 10_u32
  USBUSER_OP_SEND_ONE_PACKET = 268435457_u32
  USBUSER_OP_RAW_RESET_PORT = 536870913_u32
  USBUSER_OP_OPEN_RAW_DEVICE = 536870914_u32
  USBUSER_OP_CLOSE_RAW_DEVICE = 536870915_u32
  USBUSER_OP_SEND_RAW_COMMAND = 536870916_u32
  USBUSER_SET_ROOTPORT_FEATURE = 536870917_u32
  USBUSER_CLEAR_ROOTPORT_FEATURE = 536870918_u32
  USBUSER_GET_ROOTPORT_STATUS = 536870919_u32
  USBUSER_INVALID_REQUEST = 4294967280_u32
  USBUSER_OP_MASK_DEVONLY_API = 268435456_u32
  USBUSER_OP_MASK_HCTEST_API = 536870912_u32
  USB_PACKETFLAG_LOW_SPEED = 1_u32
  USB_PACKETFLAG_FULL_SPEED = 2_u32
  USB_PACKETFLAG_HIGH_SPEED = 4_u32
  USB_PACKETFLAG_ASYNC_IN = 8_u32
  USB_PACKETFLAG_ASYNC_OUT = 16_u32
  USB_PACKETFLAG_ISO_IN = 32_u32
  USB_PACKETFLAG_ISO_OUT = 64_u32
  USB_PACKETFLAG_SETUP = 128_u32
  USB_PACKETFLAG_TOGGLE0 = 256_u32
  USB_PACKETFLAG_TOGGLE1 = 512_u32
  USB_HC_FEATURE_FLAG_PORT_POWER_SWITCHING = 1_u32
  USB_HC_FEATURE_FLAG_SEL_SUSPEND = 2_u32
  USB_HC_FEATURE_LEGACY_BIOS = 4_u32
  USB_HC_FEATURE_TIME_SYNC_API = 8_u32
  USB_SUBMIT_URB = 0_u32
  USB_RESET_PORT = 1_u32
  USB_GET_ROOTHUB_PDO = 3_u32
  USB_GET_PORT_STATUS = 4_u32
  USB_ENABLE_PORT = 5_u32
  USB_GET_HUB_COUNT = 6_u32
  USB_CYCLE_PORT = 7_u32
  USB_GET_HUB_NAME = 8_u32
  USB_IDLE_NOTIFICATION = 9_u32
  USB_RECORD_FAILURE = 10_u32
  USB_GET_BUS_INFO = 264_u32
  USB_GET_CONTROLLER_NAME = 265_u32
  USB_GET_BUSGUID_INFO = 266_u32
  USB_GET_PARENT_HUB_INFO = 267_u32
  USB_GET_DEVICE_HANDLE = 268_u32
  USB_GET_DEVICE_HANDLE_EX = 269_u32
  USB_GET_TT_DEVICE_HANDLE = 270_u32
  USB_GET_TOPOLOGY_ADDRESS = 271_u32
  USB_IDLE_NOTIFICATION_EX = 272_u32
  USB_REQ_GLOBAL_SUSPEND = 273_u32
  USB_REQ_GLOBAL_RESUME = 274_u32
  USB_GET_HUB_CONFIG_INFO = 275_u32
  USB_FAIL_GET_STATUS = 280_u32
  USB_REGISTER_COMPOSITE_DEVICE = 0_u32
  USB_UNREGISTER_COMPOSITE_DEVICE = 1_u32
  USB_REQUEST_REMOTE_WAKE_NOTIFICATION = 2_u32
  HCD_GET_STATS_1 = 255_u32
  HCD_DIAGNOSTIC_MODE_ON = 256_u32
  HCD_DIAGNOSTIC_MODE_OFF = 257_u32
  HCD_GET_ROOT_HUB_NAME = 258_u32
  HCD_GET_DRIVERKEY_NAME = 265_u32
  HCD_GET_STATS_2 = 266_u32
  HCD_DISABLE_PORT = 268_u32
  HCD_ENABLE_PORT = 269_u32
  HCD_USER_REQUEST = 270_u32
  HCD_TRACE_READ_REQUEST = 275_u32
  USB_GET_NODE_INFORMATION = 258_u32
  USB_GET_NODE_CONNECTION_INFORMATION = 259_u32
  USB_GET_DESCRIPTOR_FROM_NODE_CONNECTION = 260_u32
  USB_GET_NODE_CONNECTION_NAME = 261_u32
  USB_DIAG_IGNORE_HUBS_ON = 262_u32
  USB_DIAG_IGNORE_HUBS_OFF = 263_u32
  USB_GET_NODE_CONNECTION_DRIVERKEY_NAME = 264_u32
  USB_GET_HUB_CAPABILITIES = 271_u32
  USB_GET_NODE_CONNECTION_ATTRIBUTES = 272_u32
  USB_HUB_CYCLE_PORT = 273_u32
  USB_GET_NODE_CONNECTION_INFORMATION_EX = 274_u32
  USB_RESET_HUB = 275_u32
  USB_GET_HUB_CAPABILITIES_EX = 276_u32
  USB_GET_HUB_INFORMATION_EX = 277_u32
  USB_GET_PORT_CONNECTOR_PROPERTIES = 278_u32
  USB_GET_NODE_CONNECTION_INFORMATION_EX_V2 = 279_u32
  USB_GET_TRANSPORT_CHARACTERISTICS = 281_u32
  USB_REGISTER_FOR_TRANSPORT_CHARACTERISTICS_CHANGE = 282_u32
  USB_NOTIFY_ON_TRANSPORT_CHARACTERISTICS_CHANGE = 283_u32
  USB_UNREGISTER_FOR_TRANSPORT_CHARACTERISTICS_CHANGE = 284_u32
  USB_START_TRACKING_FOR_TIME_SYNC = 285_u32
  USB_GET_FRAME_NUMBER_AND_QPC_FOR_TIME_SYNC = 286_u32
  USB_STOP_TRACKING_FOR_TIME_SYNC = 287_u32
  USB_GET_DEVICE_CHARACTERISTICS = 288_u32
  GUID_DEVINTERFACE_USB_HUB = "f18a0e88-c30c-11d0-8815-00a0c906bed8"
  GUID_DEVINTERFACE_USB_BILLBOARD = "5e9adaef-f879-473f-b807-4e5ea77d1b1c"
  GUID_DEVINTERFACE_USB_DEVICE = "a5dcbf10-6530-11d2-901f-00c04fb951ed"
  GUID_DEVINTERFACE_USB_HOST_CONTROLLER = "3abf6f2d-71c4-462a-8a92-1e6861e6af27"
  GUID_USB_WMI_STD_DATA = "4e623b20-cb14-11d1-b331-00a0c959bbd2"
  GUID_USB_WMI_STD_NOTIFICATION = "4e623b20-cb14-11d1-b331-00a0c959bbd2"
  GUID_USB_WMI_DEVICE_PERF_INFO = "66c1aa3c-499f-49a0-a9a5-61e2359f6407"
  GUID_USB_WMI_NODE_INFO = "9c179357-dc7a-4f41-b66b-323b9ddcb5b1"
  GUID_USB_WMI_TRACING = "3a61881b-b4e6-4bf9-ae0f-3cd8f394e52f"
  GUID_USB_TRANSFER_TRACING = "681eb8aa-403d-452c-9f8a-f0616fac9540"
  GUID_USB_PERFORMANCE_TRACING = "d5de77a6-6ae9-425c-b1e2-f5615fd348a9"
  GUID_USB_WMI_SURPRISE_REMOVAL_NOTIFICATION = "9bbbf831-a2f2-43b4-96d1-86944b5914b3"
  FILE_DEVICE_USB = 34_u32
  BMREQUEST_HOST_TO_DEVICE = 0_u32
  BMREQUEST_DEVICE_TO_HOST = 1_u32
  BMREQUEST_STANDARD = 0_u32
  BMREQUEST_CLASS = 1_u32
  BMREQUEST_VENDOR = 2_u32
  BMREQUEST_TO_DEVICE = 0_u32
  BMREQUEST_TO_INTERFACE = 1_u32
  BMREQUEST_TO_ENDPOINT = 2_u32
  BMREQUEST_TO_OTHER = 3_u32
  USB_REQUEST_GET_STATUS = 0_u32
  USB_REQUEST_CLEAR_FEATURE = 1_u32
  USB_REQUEST_SET_FEATURE = 3_u32
  USB_REQUEST_SET_ADDRESS = 5_u32
  USB_REQUEST_GET_DESCRIPTOR = 6_u32
  USB_REQUEST_SET_DESCRIPTOR = 7_u32
  USB_REQUEST_GET_CONFIGURATION = 8_u32
  USB_REQUEST_SET_CONFIGURATION = 9_u32
  USB_REQUEST_GET_INTERFACE = 10_u32
  USB_REQUEST_SET_INTERFACE = 11_u32
  USB_REQUEST_SYNC_FRAME = 12_u32
  USB_REQUEST_GET_FIRMWARE_STATUS = 26_u32
  USB_REQUEST_SET_FIRMWARE_STATUS = 27_u32
  USB_GET_FIRMWARE_ALLOWED_OR_DISALLOWED_STATE = 0_u32
  USB_GET_FIRMWARE_HASH = 1_u32
  USB_DEVICE_FIRMWARE_HASH_LENGTH = 32_u32
  USB_DISALLOW_FIRMWARE_UPDATE = 0_u32
  USB_ALLOW_FIRMWARE_UPDATE = 1_u32
  USB_REQUEST_SET_SEL = 48_u32
  USB_REQUEST_ISOCH_DELAY = 49_u32
  USB_DEVICE_DESCRIPTOR_TYPE = 1_u32
  USB_CONFIGURATION_DESCRIPTOR_TYPE = 2_u32
  USB_STRING_DESCRIPTOR_TYPE = 3_u32
  USB_INTERFACE_DESCRIPTOR_TYPE = 4_u32
  USB_ENDPOINT_DESCRIPTOR_TYPE = 5_u32
  USB_DEVICE_QUALIFIER_DESCRIPTOR_TYPE = 6_u32
  USB_OTHER_SPEED_CONFIGURATION_DESCRIPTOR_TYPE = 7_u32
  USB_INTERFACE_POWER_DESCRIPTOR_TYPE = 8_u32
  USB_OTG_DESCRIPTOR_TYPE = 9_u32
  USB_DEBUG_DESCRIPTOR_TYPE = 10_u32
  USB_INTERFACE_ASSOCIATION_DESCRIPTOR_TYPE = 11_u32
  USB_BOS_DESCRIPTOR_TYPE = 15_u32
  USB_DEVICE_CAPABILITY_DESCRIPTOR_TYPE = 16_u32
  USB_SUPERSPEED_ENDPOINT_COMPANION_DESCRIPTOR_TYPE = 48_u32
  USB_SUPERSPEEDPLUS_ISOCH_ENDPOINT_COMPANION_DESCRIPTOR_TYPE = 49_u32
  USB_RESERVED_DESCRIPTOR_TYPE = 6_u32
  USB_CONFIG_POWER_DESCRIPTOR_TYPE = 7_u32
  USB_FEATURE_ENDPOINT_STALL = 0_u32
  USB_FEATURE_REMOTE_WAKEUP = 1_u32
  USB_FEATURE_TEST_MODE = 2_u32
  USB_FEATURE_FUNCTION_SUSPEND = 0_u32
  USB_FEATURE_U1_ENABLE = 48_u32
  USB_FEATURE_U2_ENABLE = 49_u32
  USB_FEATURE_LTM_ENABLE = 50_u32
  USB_FEATURE_LDM_ENABLE = 53_u32
  USB_FEATURE_BATTERY_WAKE_MASK = 40_u32
  USB_FEATURE_OS_IS_PD_AWARE = 41_u32
  USB_FEATURE_POLICY_MODE = 42_u32
  USB_FEATURE_CHARGING_POLICY = 54_u32
  USB_CHARGING_POLICY_DEFAULT = 0_u32
  USB_CHARGING_POLICY_ICCHPF = 1_u32
  USB_CHARGING_POLICY_ICCLPF = 2_u32
  USB_CHARGING_POLICY_NO_POWER = 3_u32
  USB_STATUS_PORT_STATUS = 0_u32
  USB_STATUS_PD_STATUS = 1_u32
  USB_STATUS_EXT_PORT_STATUS = 2_u32
  USB_GETSTATUS_SELF_POWERED = 1_u32
  USB_GETSTATUS_REMOTE_WAKEUP_ENABLED = 2_u32
  USB_GETSTATUS_U1_ENABLE = 4_u32
  USB_GETSTATUS_U2_ENABLE = 8_u32
  USB_GETSTATUS_LTM_ENABLE = 16_u32
  USB_DEVICE_CLASS_RESERVED = 0_u32
  USB_DEVICE_CLASS_AUDIO = 1_u32
  USB_DEVICE_CLASS_COMMUNICATIONS = 2_u32
  USB_DEVICE_CLASS_HUMAN_INTERFACE = 3_u32
  USB_DEVICE_CLASS_MONITOR = 4_u32
  USB_DEVICE_CLASS_PHYSICAL_INTERFACE = 5_u32
  USB_DEVICE_CLASS_POWER = 6_u32
  USB_DEVICE_CLASS_IMAGE = 6_u32
  USB_DEVICE_CLASS_PRINTER = 7_u32
  USB_DEVICE_CLASS_STORAGE = 8_u32
  USB_DEVICE_CLASS_HUB = 9_u32
  USB_DEVICE_CLASS_CDC_DATA = 10_u32
  USB_DEVICE_CLASS_SMART_CARD = 11_u32
  USB_DEVICE_CLASS_CONTENT_SECURITY = 13_u32
  USB_DEVICE_CLASS_VIDEO = 14_u32
  USB_DEVICE_CLASS_PERSONAL_HEALTHCARE = 15_u32
  USB_DEVICE_CLASS_AUDIO_VIDEO = 16_u32
  USB_DEVICE_CLASS_BILLBOARD = 17_u32
  USB_DEVICE_CLASS_DIAGNOSTIC_DEVICE = 220_u32
  USB_DEVICE_CLASS_WIRELESS_CONTROLLER = 224_u32
  USB_DEVICE_CLASS_MISCELLANEOUS = 239_u32
  USB_DEVICE_CLASS_APPLICATION_SPECIFIC = 254_u32
  USB_DEVICE_CLASS_VENDOR_SPECIFIC = 255_u32
  USB_DEVICE_CAPABILITY_WIRELESS_USB = 1_u32
  USB_DEVICE_CAPABILITY_USB20_EXTENSION = 2_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_USB = 3_u32
  USB_DEVICE_CAPABILITY_CONTAINER_ID = 4_u32
  USB_DEVICE_CAPABILITY_PLATFORM = 5_u32
  USB_DEVICE_CAPABILITY_POWER_DELIVERY = 6_u32
  USB_DEVICE_CAPABILITY_BATTERY_INFO = 7_u32
  USB_DEVICE_CAPABILITY_PD_CONSUMER_PORT = 8_u32
  USB_DEVICE_CAPABILITY_PD_PROVIDER_PORT = 9_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_USB = 10_u32
  USB_DEVICE_CAPABILITY_PRECISION_TIME_MEASUREMENT = 11_u32
  USB_DEVICE_CAPABILITY_BILLBOARD = 13_u32
  USB_DEVICE_CAPABILITY_FIRMWARE_STATUS = 17_u32
  USB_DEVICE_CAPABILITY_USB20_EXTENSION_BMATTRIBUTES_RESERVED_MASK = 4294901985_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_BMATTRIBUTES_RESERVED_MASK = 253_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_BMATTRIBUTES_LTM_CAPABLE = 2_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_SPEEDS_SUPPORTED_RESERVED_MASK = 65520_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_SPEEDS_SUPPORTED_LOW = 1_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_SPEEDS_SUPPORTED_FULL = 2_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_SPEEDS_SUPPORTED_HIGH = 4_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_SPEEDS_SUPPORTED_SUPER = 8_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_U1_DEVICE_EXIT_MAX_VALUE = 10_u32
  USB_DEVICE_CAPABILITY_SUPERSPEED_U2_DEVICE_EXIT_MAX_VALUE = 2047_u32
  USB_DEVICE_CAPABILITY_MAX_U1_LATENCY = 10_u32
  USB_DEVICE_CAPABILITY_MAX_U2_LATENCY = 2047_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_LSE_BPS = 0_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_LSE_KBPS = 1_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_LSE_MBPS = 2_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_LSE_GBPS = 3_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_MODE_SYMMETRIC = 0_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_MODE_ASYMMETRIC = 1_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_DIR_RX = 0_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_DIR_TX = 1_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_PROTOCOL_SS = 0_u32
  USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED_PROTOCOL_SSP = 1_u32
  GUID_USB_MSOS20_PLATFORM_CAPABILITY_ID = "d8dd60df-4589-4cc7-9cd2-659d9e648a9f"
  USB_CONFIG_POWERED_MASK = 192_u32
  USB_CONFIG_BUS_POWERED = 128_u32
  USB_CONFIG_SELF_POWERED = 64_u32
  USB_CONFIG_REMOTE_WAKEUP = 32_u32
  USB_CONFIG_RESERVED = 31_u32
  USB_ENDPOINT_DIRECTION_MASK = 128_u32
  USB_ENDPOINT_ADDRESS_MASK = 15_u32
  USB_ENDPOINT_TYPE_MASK = 3_u32
  USB_ENDPOINT_TYPE_CONTROL = 0_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS = 1_u32
  USB_ENDPOINT_TYPE_BULK = 2_u32
  USB_ENDPOINT_TYPE_INTERRUPT = 3_u32
  USB_ENDPOINT_TYPE_BULK_RESERVED_MASK = 252_u32
  USB_ENDPOINT_TYPE_CONTROL_RESERVED_MASK = 252_u32
  USB_20_ENDPOINT_TYPE_INTERRUPT_RESERVED_MASK = 252_u32
  USB_30_ENDPOINT_TYPE_INTERRUPT_RESERVED_MASK = 204_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_RESERVED_MASK = 192_u32
  USB_30_ENDPOINT_TYPE_INTERRUPT_USAGE_MASK = 48_u32
  USB_30_ENDPOINT_TYPE_INTERRUPT_USAGE_PERIODIC = 0_u32
  USB_30_ENDPOINT_TYPE_INTERRUPT_USAGE_NOTIFICATION = 16_u32
  USB_30_ENDPOINT_TYPE_INTERRUPT_USAGE_RESERVED10 = 32_u32
  USB_30_ENDPOINT_TYPE_INTERRUPT_USAGE_RESERVED11 = 48_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_SYNCHRONIZATION_MASK = 12_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_SYNCHRONIZATION_NO_SYNCHRONIZATION = 0_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_SYNCHRONIZATION_ASYNCHRONOUS = 4_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_SYNCHRONIZATION_ADAPTIVE = 8_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_SYNCHRONIZATION_SYNCHRONOUS = 12_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_USAGE_MASK = 48_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_USAGE_DATA_ENDOINT = 0_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_USAGE_FEEDBACK_ENDPOINT = 16_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_USAGE_IMPLICIT_FEEDBACK_DATA_ENDPOINT = 32_u32
  USB_ENDPOINT_TYPE_ISOCHRONOUS_USAGE_RESERVED = 48_u32
  USB_ENDPOINT_SUPERSPEED_BULK_MAX_PACKET_SIZE = 1024_u32
  USB_ENDPOINT_SUPERSPEED_CONTROL_MAX_PACKET_SIZE = 512_u32
  USB_ENDPOINT_SUPERSPEED_ISO_MAX_PACKET_SIZE = 1024_u32
  USB_ENDPOINT_SUPERSPEED_INTERRUPT_MAX_PACKET_SIZE = 1024_u32
  MAXIMUM_USB_STRING_LENGTH = 255_u32
  USB_SUPERSPEED_ISOCHRONOUS_MAX_MULTIPLIER = 2_u32
  USB_SUPERSPEEDPLUS_ISOCHRONOUS_MIN_BYTESPERINTERVAL = 49153_u32
  USB_SUPERSPEEDPLUS_ISOCHRONOUS_MAX_BYTESPERINTERVAL = 16777215_u32
  USB_20_HUB_DESCRIPTOR_TYPE = 41_u32
  USB_30_HUB_DESCRIPTOR_TYPE = 42_u32
  USB_REQUEST_GET_STATE = 2_u32
  USB_REQUEST_CLEAR_TT_BUFFER = 8_u32
  USB_REQUEST_RESET_TT = 9_u32
  USB_REQUEST_GET_TT_STATE = 10_u32
  USB_REQUEST_STOP_TT = 11_u32
  USB_REQUEST_SET_HUB_DEPTH = 12_u32
  USB_REQUEST_GET_PORT_ERR_COUNT = 13_u32
  USB_PORT_STATUS_CONNECT = 1_u32
  USB_PORT_STATUS_ENABLE = 2_u32
  USB_PORT_STATUS_SUSPEND = 4_u32
  USB_PORT_STATUS_OVER_CURRENT = 8_u32
  USB_PORT_STATUS_RESET = 16_u32
  USB_PORT_STATUS_POWER = 256_u32
  USB_PORT_STATUS_LOW_SPEED = 512_u32
  USB_PORT_STATUS_HIGH_SPEED = 1024_u32
  PORT_LINK_STATE_U0 = 0_u32
  PORT_LINK_STATE_U1 = 1_u32
  PORT_LINK_STATE_U2 = 2_u32
  PORT_LINK_STATE_U3 = 3_u32
  PORT_LINK_STATE_DISABLED = 4_u32
  PORT_LINK_STATE_RX_DETECT = 5_u32
  PORT_LINK_STATE_INACTIVE = 6_u32
  PORT_LINK_STATE_POLLING = 7_u32
  PORT_LINK_STATE_RECOVERY = 8_u32
  PORT_LINK_STATE_HOT_RESET = 9_u32
  PORT_LINK_STATE_COMPLIANCE_MODE = 10_u32
  PORT_LINK_STATE_LOOPBACK = 11_u32
  PORT_LINK_STATE_TEST_MODE = 11_u32
  USB_FEATURE_INTERFACE_POWER_D0 = 2_u32
  USB_FEATURE_INTERFACE_POWER_D1 = 3_u32
  USB_FEATURE_INTERFACE_POWER_D2 = 4_u32
  USB_FEATURE_INTERFACE_POWER_D3 = 5_u32
  USB_SUPPORT_D0_COMMAND = 1_u32
  USB_SUPPORT_D1_COMMAND = 2_u32
  USB_SUPPORT_D2_COMMAND = 4_u32
  USB_SUPPORT_D3_COMMAND = 8_u32
  USB_SUPPORT_D1_WAKEUP = 16_u32
  USB_SUPPORT_D2_WAKEUP = 32_u32
  USBDI_VERSION = 1536_u32
  USB_PORTATTR_NO_CONNECTOR = 1_u32
  USB_PORTATTR_SHARED_USB2 = 2_u32
  USB_PORTATTR_MINI_CONNECTOR = 4_u32
  USB_PORTATTR_OEM_CONNECTOR = 8_u32
  USB_PORTATTR_OWNED_BY_CC = 16777216_u32
  USB_PORTATTR_NO_OVERCURRENT_UI = 33554432_u32
  USB_DEFAULT_DEVICE_ADDRESS = 0_u32
  USB_DEFAULT_ENDPOINT_ADDRESS = 0_u32
  USB_DEFAULT_MAX_PACKET = 64_u32
  URB_FUNCTION_SELECT_CONFIGURATION = 0_u32
  URB_FUNCTION_SELECT_INTERFACE = 1_u32
  URB_FUNCTION_ABORT_PIPE = 2_u32
  URB_FUNCTION_TAKE_FRAME_LENGTH_CONTROL = 3_u32
  URB_FUNCTION_RELEASE_FRAME_LENGTH_CONTROL = 4_u32
  URB_FUNCTION_GET_FRAME_LENGTH = 5_u32
  URB_FUNCTION_SET_FRAME_LENGTH = 6_u32
  URB_FUNCTION_GET_CURRENT_FRAME_NUMBER = 7_u32
  URB_FUNCTION_CONTROL_TRANSFER = 8_u32
  URB_FUNCTION_BULK_OR_INTERRUPT_TRANSFER = 9_u32
  URB_FUNCTION_ISOCH_TRANSFER = 10_u32
  URB_FUNCTION_GET_DESCRIPTOR_FROM_DEVICE = 11_u32
  URB_FUNCTION_SET_DESCRIPTOR_TO_DEVICE = 12_u32
  URB_FUNCTION_SET_FEATURE_TO_DEVICE = 13_u32
  URB_FUNCTION_SET_FEATURE_TO_INTERFACE = 14_u32
  URB_FUNCTION_SET_FEATURE_TO_ENDPOINT = 15_u32
  URB_FUNCTION_CLEAR_FEATURE_TO_DEVICE = 16_u32
  URB_FUNCTION_CLEAR_FEATURE_TO_INTERFACE = 17_u32
  URB_FUNCTION_CLEAR_FEATURE_TO_ENDPOINT = 18_u32
  URB_FUNCTION_GET_STATUS_FROM_DEVICE = 19_u32
  URB_FUNCTION_GET_STATUS_FROM_INTERFACE = 20_u32
  URB_FUNCTION_GET_STATUS_FROM_ENDPOINT = 21_u32
  URB_FUNCTION_RESERVED_0X0016 = 22_u32
  URB_FUNCTION_VENDOR_DEVICE = 23_u32
  URB_FUNCTION_VENDOR_INTERFACE = 24_u32
  URB_FUNCTION_VENDOR_ENDPOINT = 25_u32
  URB_FUNCTION_CLASS_DEVICE = 26_u32
  URB_FUNCTION_CLASS_INTERFACE = 27_u32
  URB_FUNCTION_CLASS_ENDPOINT = 28_u32
  URB_FUNCTION_RESERVE_0X001D = 29_u32
  URB_FUNCTION_SYNC_RESET_PIPE_AND_CLEAR_STALL = 30_u32
  URB_FUNCTION_CLASS_OTHER = 31_u32
  URB_FUNCTION_VENDOR_OTHER = 32_u32
  URB_FUNCTION_GET_STATUS_FROM_OTHER = 33_u32
  URB_FUNCTION_CLEAR_FEATURE_TO_OTHER = 34_u32
  URB_FUNCTION_SET_FEATURE_TO_OTHER = 35_u32
  URB_FUNCTION_GET_DESCRIPTOR_FROM_ENDPOINT = 36_u32
  URB_FUNCTION_SET_DESCRIPTOR_TO_ENDPOINT = 37_u32
  URB_FUNCTION_GET_CONFIGURATION = 38_u32
  URB_FUNCTION_GET_INTERFACE = 39_u32
  URB_FUNCTION_GET_DESCRIPTOR_FROM_INTERFACE = 40_u32
  URB_FUNCTION_SET_DESCRIPTOR_TO_INTERFACE = 41_u32
  URB_FUNCTION_RESERVE_0X002B = 43_u32
  URB_FUNCTION_RESERVE_0X002C = 44_u32
  URB_FUNCTION_RESERVE_0X002D = 45_u32
  URB_FUNCTION_RESERVE_0X002E = 46_u32
  URB_FUNCTION_RESERVE_0X002F = 47_u32
  URB_FUNCTION_GET_MS_FEATURE_DESCRIPTOR = 42_u32
  URB_FUNCTION_SYNC_RESET_PIPE = 48_u32
  URB_FUNCTION_SYNC_CLEAR_STALL = 49_u32
  URB_FUNCTION_CONTROL_TRANSFER_EX = 50_u32
  URB_FUNCTION_RESERVE_0X0033 = 51_u32
  URB_FUNCTION_RESERVE_0X0034 = 52_u32
  URB_FUNCTION_OPEN_STATIC_STREAMS = 53_u32
  URB_FUNCTION_CLOSE_STATIC_STREAMS = 54_u32
  URB_FUNCTION_BULK_OR_INTERRUPT_TRANSFER_USING_CHAINED_MDL = 55_u32
  URB_FUNCTION_ISOCH_TRANSFER_USING_CHAINED_MDL = 56_u32
  URB_FUNCTION_GET_ISOCH_PIPE_TRANSFER_PATH_DELAYS = 61_u32
  URB_FUNCTION_RESET_PIPE = 30_u32
  USBD_SHORT_TRANSFER_OK = 2_u32
  USBD_START_ISO_TRANSFER_ASAP = 4_u32
  USBD_DEFAULT_PIPE_TRANSFER = 8_u32
  USBD_TRANSFER_DIRECTION_OUT = 0_u32
  USBD_TRANSFER_DIRECTION_IN = 1_u32
  USBD_TRANSFER_DIRECTION = 1_u32
  USBD_ISO_START_FRAME_RANGE = 1024_u32
  USBD_DEFAULT_MAXIMUM_TRANSFER_SIZE = 4294967295_u32
  USBD_PF_CHANGE_MAX_PACKET = 1_u32
  USBD_PF_SHORT_PACKET_OPT = 2_u32
  USBD_PF_ENABLE_RT_THREAD_ACCESS = 4_u32
  USBD_PF_MAP_ADD_TRANSFERS = 8_u32
  USBD_PF_VIDEO_PRIORITY = 16_u32
  USBD_PF_VOICE_PRIORITY = 32_u32
  USBD_PF_INTERACTIVE_PRIORITY = 48_u32
  USBD_PF_PRIORITY_MASK = 240_u32
  USBD_PF_HANDLES_SSP_HIGH_BANDWIDTH_ISOCH = 256_u32
  USBD_PF_SSP_HIGH_BANDWIDTH_ISOCH = 65536_u32
  OS_STRING_DESCRIPTOR_INDEX = 238_u32
  MS_GENRE_DESCRIPTOR_INDEX = 1_u32
  MS_POWER_DESCRIPTOR_INDEX = 2_u32
  MS_OS_STRING_SIGNATURE = "MSFT100"
  MS_OS_FLAGS_CONTAINERID = 2_u32
  URB_OPEN_STATIC_STREAMS_VERSION_100 = 256_u32
  KREGUSBFNENUMPATH = "\\Registry\\Machine\\SYSTEM\\CurrentControlSet\\Control\\USBFN\\"
  UREGUSBFNENUMPATH = "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\USBFN\\"
  KREGMANUSBFNENUMPATH = "\\Registry\\Machine\\SYSTEM\\CurrentControlSet\\Control\\ManufacturingMode\\Current\\USBFN\\"
  UREGMANUSBFNENUMPATH = "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\ManufacturingMode\\Current\\USBFN\\"
  MAX_NUM_USBFN_ENDPOINTS = 15_u32
  MAX_CONFIGURATION_NAME_LENGTH = 40_u32
  MAX_USB_STRING_LENGTH = 255_u32
  MAX_SUPPORTED_CONFIGURATIONS = 12_u32
  USBFN_INTERRUPT_ENDPOINT_SIZE_NOT_UPDATEABLE_MASK = 128_u32
  USB_TEST_MODE_TEST_J = 1_u32
  USB_TEST_MODE_TEST_K = 2_u32
  USB_TEST_MODE_TEST_SE0_NAK = 3_u32
  USB_TEST_MODE_TEST_PACKET = 4_u32
  USB_TEST_MODE_TEST_FORCE_ENABLE = 5_u32
  MAX_INTERFACE_NAME_LENGTH = 40_u32
  MAX_ALTERNATE_NAME_LENGTH = 40_u32
  MAX_ASSOCIATION_NAME_LENGTH = 40_u32
  IOCTL_INTERNAL_USB_SUBMIT_URB = 2228227_u32
  IOCTL_INTERNAL_USB_RESET_PORT = 2228231_u32
  IOCTL_INTERNAL_USB_GET_ROOTHUB_PDO = 2228239_u32
  USBD_PORT_ENABLED = 1_u32
  USBD_PORT_CONNECTED = 2_u32
  IOCTL_INTERNAL_USB_GET_PORT_STATUS = 2228243_u32
  IOCTL_INTERNAL_USB_ENABLE_PORT = 2228247_u32
  IOCTL_INTERNAL_USB_GET_HUB_COUNT = 2228251_u32
  IOCTL_INTERNAL_USB_CYCLE_PORT = 2228255_u32
  IOCTL_INTERNAL_USB_GET_HUB_NAME = 2228256_u32
  IOCTL_INTERNAL_USB_GET_BUS_INFO = 2229280_u32
  IOCTL_INTERNAL_USB_GET_CONTROLLER_NAME = 2229284_u32
  IOCTL_INTERNAL_USB_GET_BUSGUID_INFO = 2229288_u32
  IOCTL_INTERNAL_USB_GET_PARENT_HUB_INFO = 2229292_u32
  IOCTL_INTERNAL_USB_SUBMIT_IDLE_NOTIFICATION = 2228263_u32
  IOCTL_INTERNAL_USB_GET_DEVICE_HANDLE = 2229299_u32
  IOCTL_INTERNAL_USB_NOTIFY_IDLE_READY = 2229315_u32
  IOCTL_INTERNAL_USB_REQ_GLOBAL_SUSPEND = 2229319_u32
  IOCTL_INTERNAL_USB_REQ_GLOBAL_RESUME = 2229323_u32
  IOCTL_INTERNAL_USB_RECORD_FAILURE = 2228267_u32
  IOCTL_INTERNAL_USB_GET_DEVICE_HANDLE_EX = 2229303_u32
  IOCTL_INTERNAL_USB_GET_TT_DEVICE_HANDLE = 2229307_u32
  IOCTL_INTERNAL_USB_GET_TOPOLOGY_ADDRESS = 2229311_u32
  IOCTL_INTERNAL_USB_GET_DEVICE_CONFIG_INFO = 2229327_u32
  IOCTL_INTERNAL_USB_REGISTER_COMPOSITE_DEVICE = 4784131_u32
  IOCTL_INTERNAL_USB_UNREGISTER_COMPOSITE_DEVICE = 4784135_u32
  IOCTL_INTERNAL_USB_REQUEST_REMOTE_WAKE_NOTIFICATION = 4784139_u32
  IOCTL_INTERNAL_USB_FAIL_GET_STATUS_FROM_DEVICE = 2229347_u32
  IOCTL_USB_HCD_GET_STATS_1 = 2229244_u32
  IOCTL_USB_HCD_GET_STATS_2 = 2229288_u32
  IOCTL_USB_HCD_DISABLE_PORT = 2229296_u32
  IOCTL_USB_HCD_ENABLE_PORT = 2229300_u32
  IOCTL_USB_DIAGNOSTIC_MODE_ON = 2229248_u32
  IOCTL_USB_DIAGNOSTIC_MODE_OFF = 2229252_u32
  IOCTL_USB_GET_ROOT_HUB_NAME = 2229256_u32
  IOCTL_GET_HCD_DRIVERKEY_NAME = 2229284_u32
  IOCTL_USB_GET_NODE_INFORMATION = 2229256_u32
  IOCTL_USB_GET_NODE_CONNECTION_INFORMATION = 2229260_u32
  IOCTL_USB_GET_DESCRIPTOR_FROM_NODE_CONNECTION = 2229264_u32
  IOCTL_USB_GET_NODE_CONNECTION_NAME = 2229268_u32
  IOCTL_USB_DIAG_IGNORE_HUBS_ON = 2229272_u32
  IOCTL_USB_DIAG_IGNORE_HUBS_OFF = 2229276_u32
  IOCTL_USB_GET_NODE_CONNECTION_DRIVERKEY_NAME = 2229280_u32
  IOCTL_USB_GET_HUB_CAPABILITIES = 2229308_u32
  IOCTL_USB_HUB_CYCLE_PORT = 2229316_u32
  IOCTL_USB_GET_NODE_CONNECTION_ATTRIBUTES = 2229312_u32
  IOCTL_USB_GET_NODE_CONNECTION_INFORMATION_EX = 2229320_u32
  IOCTL_USB_RESET_HUB = 2229324_u32
  IOCTL_USB_GET_HUB_CAPABILITIES_EX = 2229328_u32
  IOCTL_USB_GET_HUB_INFORMATION_EX = 2229332_u32
  IOCTL_USB_GET_PORT_CONNECTOR_PROPERTIES = 2229336_u32
  IOCTL_USB_GET_NODE_CONNECTION_INFORMATION_EX_V2 = 2229340_u32
  IOCTL_USB_GET_TRANSPORT_CHARACTERISTICS = 2229348_u32
  IOCTL_USB_REGISTER_FOR_TRANSPORT_CHARACTERISTICS_CHANGE = 2229352_u32
  IOCTL_USB_NOTIFY_ON_TRANSPORT_CHARACTERISTICS_CHANGE = 2229356_u32
  IOCTL_USB_UNREGISTER_FOR_TRANSPORT_CHARACTERISTICS_CHANGE = 2229360_u32
  IOCTL_USB_START_TRACKING_FOR_TIME_SYNC = 2229364_u32
  IOCTL_USB_GET_FRAME_NUMBER_AND_QPC_FOR_TIME_SYNC = 2229368_u32
  IOCTL_USB_STOP_TRACKING_FOR_TIME_SYNC = 2229372_u32
  IOCTL_USB_GET_DEVICE_CHARACTERISTICS = 2229376_u32
  WMI_USB_DRIVER_INFORMATION = 0_u32
  WMI_USB_DRIVER_NOTIFICATION = 1_u32
  WMI_USB_POWER_DEVICE_ENABLE = 2_u32
  WMI_USB_HUB_NODE_INFORMATION = 4_u32
  WMI_USB_PERFORMANCE_INFORMATION = 1_u32
  WMI_USB_DEVICE_NODE_INFORMATION = 2_u32
  USB_TRANSPORT_CHARACTERISTICS_VERSION_1 = 1_u32
  USB_TRANSPORT_CHARACTERISTICS_LATENCY_AVAILABLE = 1_u32
  USB_TRANSPORT_CHARACTERISTICS_BANDWIDTH_AVAILABLE = 2_u32
  USB_REGISTER_FOR_TRANSPORT_LATENCY_CHANGE = 1_u32
  USB_REGISTER_FOR_TRANSPORT_BANDWIDTH_CHANGE = 2_u32
  USB_DEVICE_CHARACTERISTICS_VERSION_1 = 1_u32
  USB_DEVICE_CHARACTERISTICS_MAXIMUM_PATH_DELAYS_AVAILABLE = 1_u32
  MAX_NUM_PIPES = 8_u32
  BULKIN_FLAG = 128_u32
  FILE_DEVICE_USB_SCAN = 32768_u32
  IOCTL_INDEX = 2048_u32
  IOCTL_GET_VERSION = 2147491840_u32
  IOCTL_CANCEL_IO = 2147491844_u32
  IOCTL_WAIT_ON_DEVICE_EVENT = 2147491848_u32
  IOCTL_READ_REGISTERS = 2147491852_u32
  IOCTL_WRITE_REGISTERS = 2147491856_u32
  IOCTL_GET_CHANNEL_ALIGN_RQST = 2147491860_u32
  IOCTL_GET_DEVICE_DESCRIPTOR = 2147491864_u32
  IOCTL_RESET_PIPE = 2147491868_u32
  IOCTL_GET_USB_DESCRIPTOR = 2147491872_u32
  IOCTL_SEND_USB_REQUEST = 2147491876_u32
  IOCTL_GET_PIPE_CONFIGURATION = 2147491880_u32
  IOCTL_SET_TIMEOUT = 2147491884_u32
  IOCTL_ABORT_PIPE = 2147491844_u32

  enum USB_DEVICE_SPEED
    UsbLowSpeed = 0_i32
    UsbFullSpeed = 1_i32
    UsbHighSpeed = 2_i32
    UsbSuperSpeed = 3_i32
  end
  enum USB_DEVICE_TYPE
    Usb11Device = 0_i32
    Usb20Device = 1_i32
  end
  enum USB_CONTROLLER_FLAVOR
    USB_HcGeneric = 0_i32
    OHCI_Generic = 100_i32
    OHCI_Hydra = 101_i32
    OHCI_NEC = 102_i32
    UHCI_Generic = 200_i32
    UHCI_Piix4 = 201_i32
    UHCI_Piix3 = 202_i32
    UHCI_Ich2 = 203_i32
    UHCI_Reserved204 = 204_i32
    UHCI_Ich1 = 205_i32
    UHCI_Ich3m = 206_i32
    UHCI_Ich4 = 207_i32
    UHCI_Ich5 = 208_i32
    UHCI_Ich6 = 209_i32
    UHCI_Intel = 249_i32
    UHCI_VIA = 250_i32
    UHCI_VIA_x01 = 251_i32
    UHCI_VIA_x02 = 252_i32
    UHCI_VIA_x03 = 253_i32
    UHCI_VIA_x04 = 254_i32
    UHCI_VIA_x0E_FIFO = 264_i32
    EHCI_Generic = 1000_i32
    EHCI_NEC = 2000_i32
    EHCI_Lucent = 3000_i32
    EHCI_NVIDIA_Tegra2 = 4000_i32
    EHCI_NVIDIA_Tegra3 = 4001_i32
    EHCI_Intel_Medfield = 5001_i32
  end
  enum USBD_PIPE_TYPE
    UsbdPipeTypeControl = 0_i32
    UsbdPipeTypeIsochronous = 1_i32
    UsbdPipeTypeBulk = 2_i32
    UsbdPipeTypeInterrupt = 3_i32
  end
  enum USBD_ENDPOINT_OFFLOAD_MODE
    UsbdEndpointOffloadModeNotSupported = 0_i32
    UsbdEndpointOffloadSoftwareAssisted = 1_i32
    UsbdEndpointOffloadHardwareAssisted = 2_i32
  end
  enum USB_USER_ERROR_CODE
    UsbUserSuccess = 0_i32
    UsbUserNotSupported = 1_i32
    UsbUserInvalidRequestCode = 2_i32
    UsbUserFeatureDisabled = 3_i32
    UsbUserInvalidHeaderParameter = 4_i32
    UsbUserInvalidParameter = 5_i32
    UsbUserMiniportError = 6_i32
    UsbUserBufferTooSmall = 7_i32
    UsbUserErrorNotMapped = 8_i32
    UsbUserDeviceNotStarted = 9_i32
    UsbUserNoDeviceConnected = 10_i32
  end
  enum WDMUSB_POWER_STATE
    WdmUsbPowerNotMapped = 0_i32
    WdmUsbPowerSystemUnspecified = 100_i32
    WdmUsbPowerSystemWorking = 101_i32
    WdmUsbPowerSystemSleeping1 = 102_i32
    WdmUsbPowerSystemSleeping2 = 103_i32
    WdmUsbPowerSystemSleeping3 = 104_i32
    WdmUsbPowerSystemHibernate = 105_i32
    WdmUsbPowerSystemShutdown = 106_i32
    WdmUsbPowerDeviceUnspecified = 200_i32
    WdmUsbPowerDeviceD0 = 201_i32
    WdmUsbPowerDeviceD1 = 202_i32
    WdmUsbPowerDeviceD2 = 203_i32
    WdmUsbPowerDeviceD3 = 204_i32
  end
  enum USBFN_EVENT
    UsbfnEventMinimum = 0_i32
    UsbfnEventAttach = 1_i32
    UsbfnEventReset = 2_i32
    UsbfnEventDetach = 3_i32
    UsbfnEventSuspend = 4_i32
    UsbfnEventResume = 5_i32
    UsbfnEventSetupPacket = 6_i32
    UsbfnEventConfigured = 7_i32
    UsbfnEventUnConfigured = 8_i32
    UsbfnEventPortType = 9_i32
    UsbfnEventBusTearDown = 10_i32
    UsbfnEventSetInterface = 11_i32
    UsbfnEventMaximum = 12_i32
  end
  enum USBFN_PORT_TYPE
    UsbfnUnknownPort = 0_i32
    UsbfnStandardDownstreamPort = 1_i32
    UsbfnChargingDownstreamPort = 2_i32
    UsbfnDedicatedChargingPort = 3_i32
    UsbfnInvalidDedicatedChargingPort = 4_i32
    UsbfnProprietaryDedicatedChargingPort = 5_i32
    UsbfnPortTypeMaximum = 6_i32
  end
  enum USBFN_BUS_SPEED
    UsbfnBusSpeedLow = 0_i32
    UsbfnBusSpeedFull = 1_i32
    UsbfnBusSpeedHigh = 2_i32
    UsbfnBusSpeedSuper = 3_i32
    UsbfnBusSpeedMaximum = 4_i32
  end
  enum USBFN_DIRECTION
    UsbfnDirectionMinimum = 0_i32
    UsbfnDirectionIn = 1_i32
    UsbfnDirectionOut = 2_i32
    UsbfnDirectionTx = 1_i32
    UsbfnDirectionRx = 2_i32
    UsbfnDirectionMaximum = 3_i32
  end
  enum USBFN_DEVICE_STATE
    UsbfnDeviceStateMinimum = 0_i32
    UsbfnDeviceStateAttached = 1_i32
    UsbfnDeviceStateDefault = 2_i32
    UsbfnDeviceStateDetached = 3_i32
    UsbfnDeviceStateAddressed = 4_i32
    UsbfnDeviceStateConfigured = 5_i32
    UsbfnDeviceStateSuspended = 6_i32
    UsbfnDeviceStateStateMaximum = 7_i32
  end
  enum PIPE_TYPE
    EVENT_PIPE = 0_i32
    READ_DATA_PIPE = 1_i32
    WRITE_DATA_PIPE = 2_i32
    ALL_PIPE = 3_i32
  end
  enum RAW_PIPE_TYPE
    USBSCAN_PIPE_CONTROL = 0_i32
    USBSCAN_PIPE_ISOCHRONOUS = 1_i32
    USBSCAN_PIPE_BULK = 2_i32
    USBSCAN_PIPE_INTERRUPT = 3_i32
  end

  @[Extern(union: true)]
  record BM_REQUEST_TYPE,
    s : BM_,
    b : UInt8 do

    # Nested Type BM_
    @[Extern]
    record BM_,
      _bitfield : UInt8

  end

  @[Extern]
  record USB_DEFAULT_PIPE_SETUP_PACKET,
    bmRequestType : Win32cr::Devices::Usb::BM_REQUEST_TYPE,
    bRequest : UInt8,
    wValue : Wvalue_,
    wIndex : Windex_,
    wLength : UInt16 do

    # Nested Type Windex_
    @[Extern(union: true)]
    record Windex_,
      anonymous : Anonymous_e__Struct_,
      w : UInt16 do

      # Nested Type Anonymous_e__Struct_
      @[Extern]
      record Anonymous_e__Struct_,
        low_byte : UInt8,
        hi_byte : UInt8

    end


    # Nested Type Wvalue_
    @[Extern(union: true)]
    record Wvalue_,
      anonymous : Anonymous_e__Struct_,
      w : UInt16 do

      # Nested Type Anonymous_e__Struct_
      @[Extern]
      record Anonymous_e__Struct_,
        low_byte : UInt8,
        hi_byte : UInt8

    end

  end

  @[Extern(union: true)]
  record USB_DEVICE_STATUS,
    as_ushort16 : UInt16,
    anonymous : Anonymous_e__Struct_ do

    # Nested Type Anonymous_e__Struct_
    @[Extern]
    record Anonymous_e__Struct_,
      _bitfield : UInt16

  end

  @[Extern(union: true)]
  record USB_INTERFACE_STATUS,
    as_ushort16 : UInt16,
    anonymous : Anonymous_e__Struct_ do

    # Nested Type Anonymous_e__Struct_
    @[Extern]
    record Anonymous_e__Struct_,
      _bitfield : UInt16

  end

  @[Extern(union: true)]
  record USB_ENDPOINT_STATUS,
    as_ushort16 : UInt16,
    anonymous : Anonymous_e__Struct_ do

    # Nested Type Anonymous_e__Struct_
    @[Extern]
    record Anonymous_e__Struct_,
      _bitfield : UInt16

  end

  @[Extern]
  record USB_COMMON_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8

  @[Extern]
  record USB_DEVICE_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bcdUSB : UInt16,
    bDeviceClass : UInt8,
    bDeviceSubClass : UInt8,
    bDeviceProtocol : UInt8,
    bMaxPacketSize0 : UInt8,
    idVendor : UInt16,
    idProduct : UInt16,
    bcdDevice : UInt16,
    iManufacturer : UInt8,
    iProduct : UInt8,
    iSerialNumber : UInt8,
    bNumConfigurations : UInt8

  @[Extern]
  record USB_DEVICE_QUALIFIER_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bcdUSB : UInt16,
    bDeviceClass : UInt8,
    bDeviceSubClass : UInt8,
    bDeviceProtocol : UInt8,
    bMaxPacketSize0 : UInt8,
    bNumConfigurations : UInt8,
    bReserved : UInt8

  @[Extern]
  record USB_BOS_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    wTotalLength : UInt16,
    bNumDeviceCaps : UInt8

  @[Extern]
  record USB_DEVICE_CAPABILITY_USB20_EXTENSION_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bDevCapabilityType : UInt8,
    bmAttributes : Bmattributes_e__union_ do

    # Nested Type Bmattributes_e__union_
    @[Extern(union: true)]
    record Bmattributes_e__union_,
      as_ulong : UInt32,
      anonymous : Anonymous_e__Struct_ do

      # Nested Type Anonymous_e__Struct_
      @[Extern]
      record Anonymous_e__Struct_,
        _bitfield : UInt32

    end

  end

  @[Extern]
  record USB_DEVICE_CAPABILITY_POWER_DELIVERY_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bDevCapabilityType : UInt8,
    bReserved : UInt8,
    bmAttributes : Bmattributes_e__union_,
    bmProviderPorts : UInt16,
    bmConsumerPorts : UInt16,
    bcdBCVersion : UInt16,
    bcdPDVersion : UInt16,
    bcdUSBTypeCVersion : UInt16 do

    # Nested Type Bmattributes_e__union_
    @[Extern(union: true)]
    record Bmattributes_e__union_,
      as_ulong : UInt32,
      anonymous : Anonymous_e__Struct_ do

      # Nested Type Anonymous_e__Struct_
      @[Extern]
      record Anonymous_e__Struct_,
        _bitfield : UInt32

    end

  end

  @[Extern]
  record USB_DEVICE_CAPABILITY_PD_CONSUMER_PORT_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bDevCapabilityType : UInt8,
    bReserved : UInt8,
    bmCapabilities : Bmcapabilities_e__union_,
    wMinVoltage : UInt16,
    wMaxVoltage : UInt16,
    wReserved : UInt16,
    dwMaxOperatingPower : UInt32,
    dwMaxPeakPower : UInt32,
    dwMaxPeakPowerTime : UInt32 do

    # Nested Type Bmcapabilities_e__union_
    @[Extern(union: true)]
    record Bmcapabilities_e__union_,
      as_ushort : UInt16,
      anonymous : Anonymous_e__Struct_ do

      # Nested Type Anonymous_e__Struct_
      @[Extern]
      record Anonymous_e__Struct_,
        _bitfield : UInt16

    end

  end

  @[Extern]
  record USB_DEVICE_CAPABILITY_SUPERSPEED_USB_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bDevCapabilityType : UInt8,
    bmAttributes : UInt8,
    wSpeedsSupported : UInt16,
    bFunctionalitySupport : UInt8,
    bU1DevExitLat : UInt8,
    wU2DevExitLat : UInt16

  @[Extern(union: true)]
  record USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED,
    as_ulong32 : UInt32,
    anonymous : Anonymous_e__Struct_ do

    # Nested Type Anonymous_e__Struct_
    @[Extern]
    record Anonymous_e__Struct_,
      _bitfield : UInt32

  end

  @[Extern]
  record USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_USB_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bDevCapabilityType : UInt8,
    bReserved : UInt8,
    bmAttributes : Bmattributes_e__union_,
    wFunctionalitySupport : Wfunctionalitysupport_e__union_,
    wReserved : UInt16,
    bmSublinkSpeedAttr : Win32cr::Devices::Usb::USB_DEVICE_CAPABILITY_SUPERSPEEDPLUS_SPEED* do

    # Nested Type Wfunctionalitysupport_e__union_
    @[Extern(union: true)]
    record Wfunctionalitysupport_e__union_,
      as_ushort : UInt16,
      anonymous : Anonymous_e__Struct_ do

      # Nested Type Anonymous_e__Struct_
      @[Extern]
      record Anonymous_e__Struct_,
        _bitfield : UInt16

    end


    # Nested Type Bmattributes_e__union_
    @[Extern(union: true)]
    record Bmattributes_e__union_,
      as_ulong : UInt32,
      anonymous : Anonymous_e__Struct_ do

      # Nested Type Anonymous_e__Struct_
      @[Extern]
      record Anonymous_e__Struct_,
        _bitfield : UInt32

    end

  end

  @[Extern]
  record USB_DEVICE_CAPABILITY_CONTAINER_ID_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bDevCapabilityType : UInt8,
    bReserved : UInt8,
    container_id : UInt8[16]

  @[Extern]
  record USB_DEVICE_CAPABILITY_PLATFORM_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bDevCapabilityType : UInt8,
    bReserved : UInt8,
    platform_capability_uuid : LibC::GUID,
    capabilility_data : UInt8*

  @[Extern]
  record USB_DEVICE_CAPABILITY_BILLBOARD_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bDevCapabilityType : UInt8,
    iAddtionalInfoURL : UInt8,
    bNumberOfAlternateModes : UInt8,
    bPreferredAlternateMode : UInt8,
    vconn_power : VconnPower_e__Union_,
    bmConfigured : UInt8[32],
    bReserved : UInt32,
    alternate_mode : Anonymous_e__Struct_* do

    # Nested Type VconnPower_e__Union_
    @[Extern(union: true)]
    record VconnPower_e__Union_,
      as_ushort : UInt16,
      anonymous : Anonymous_e__Struct_ do

      # Nested Type Anonymous_e__Struct_
      @[Extern]
      record Anonymous_e__Struct_,
        _bitfield : UInt16

    end


    # Nested Type Anonymous_e__Struct_
    @[Extern]
    record Anonymous_e__Struct_,
      wSVID : UInt16,
      bAlternateMode : UInt8,
      iAlternateModeSetting : UInt8

  end

  @[Extern]
  record USB_DEVICE_CAPABILITY_FIRMWARE_STATUS_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bDevCapabilityType : UInt8,
    bcdDescriptorVersion : UInt8,
    bmAttributes : Bmattributes_e__union_ do

    # Nested Type Bmattributes_e__union_
    @[Extern(union: true)]
    record Bmattributes_e__union_,
      as_ulong : UInt32,
      anonymous : Anonymous_e__Struct_ do

      # Nested Type Anonymous_e__Struct_
      @[Extern]
      record Anonymous_e__Struct_,
        _bitfield : UInt32

    end

  end

  @[Extern]
  record USB_DEVICE_CAPABILITY_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bDevCapabilityType : UInt8

  @[Extern]
  record USB_CONFIGURATION_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    wTotalLength : UInt16,
    bNumInterfaces : UInt8,
    bConfigurationValue : UInt8,
    iConfiguration : UInt8,
    bmAttributes : UInt8,
    max_power : UInt8

  @[Extern]
  record USB_INTERFACE_ASSOCIATION_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bFirstInterface : UInt8,
    bInterfaceCount : UInt8,
    bFunctionClass : UInt8,
    bFunctionSubClass : UInt8,
    bFunctionProtocol : UInt8,
    iFunction : UInt8

  @[Extern]
  record USB_INTERFACE_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bInterfaceNumber : UInt8,
    bAlternateSetting : UInt8,
    bNumEndpoints : UInt8,
    bInterfaceClass : UInt8,
    bInterfaceSubClass : UInt8,
    bInterfaceProtocol : UInt8,
    iInterface : UInt8

  @[Extern]
  record USB_ENDPOINT_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bEndpointAddress : UInt8,
    bmAttributes : UInt8,
    wMaxPacketSize : UInt16,
    bInterval : UInt8

  @[Extern(union: true)]
  record USB_HIGH_SPEED_MAXPACKET,
    us : UInt16 do

    # Nested Type MP_
    @[Extern]
    record MP_,
      _bitfield : UInt16

  end

  @[Extern]
  record USB_STRING_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bString : UInt16*

  @[Extern]
  record USB_SUPERSPEED_ENDPOINT_COMPANION_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bMaxBurst : UInt8,
    bmAttributes : Bmattributes_e__union_,
    wBytesPerInterval : UInt16 do

    # Nested Type Bmattributes_e__union_
    @[Extern(union: true)]
    record Bmattributes_e__union_,
      as_uchar : UInt8,
      bulk : Bulk_e__Struct_,
      isochronous : Isochronous_e__Struct_ do

      # Nested Type Bulk_e__Struct_
      @[Extern]
      record Bulk_e__Struct_,
        _bitfield : UInt8


      # Nested Type Isochronous_e__Struct_
      @[Extern]
      record Isochronous_e__Struct_,
        _bitfield : UInt8

    end

  end

  @[Extern]
  record USB_SUPERSPEEDPLUS_ISOCH_ENDPOINT_COMPANION_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    wReserved : UInt16,
    dwBytesPerInterval : UInt32

  @[Extern]
  record USB_HUB_DESCRIPTOR,
    bDescriptorLength : UInt8,
    bDescriptorType : UInt8,
    bNumberOfPorts : UInt8,
    wHubCharacteristics : UInt16,
    bPowerOnToPowerGood : UInt8,
    bHubControlCurrent : UInt8,
    bRemoveAndPowerMask : UInt8[64]

  @[Extern]
  record USB_30_HUB_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bNumberOfPorts : UInt8,
    wHubCharacteristics : UInt16,
    bPowerOnToPowerGood : UInt8,
    bHubControlCurrent : UInt8,
    bHubHdrDecLat : UInt8,
    wHubDelay : UInt16,
    device_removable : UInt16

  @[Extern(union: true)]
  record USB_HUB_STATUS,
    as_ushort16 : UInt16,
    anonymous : Anonymous_e__Struct_ do

    # Nested Type Anonymous_e__Struct_
    @[Extern]
    record Anonymous_e__Struct_,
      _bitfield : UInt16

  end

  @[Extern(union: true)]
  record USB_HUB_CHANGE,
    as_ushort16 : UInt16,
    anonymous : Anonymous_e__Struct_ do

    # Nested Type Anonymous_e__Struct_
    @[Extern]
    record Anonymous_e__Struct_,
      _bitfield : UInt16

  end

  @[Extern(union: true)]
  record USB_HUB_STATUS_AND_CHANGE,
    as_ulong32 : UInt32,
    anonymous : Anonymous_e__Struct_ do

    # Nested Type Anonymous_e__Struct_
    @[Extern]
    record Anonymous_e__Struct_,
      hub_status : Win32cr::Devices::Usb::USB_HUB_STATUS,
      hub_change : Win32cr::Devices::Usb::USB_HUB_CHANGE

  end

  @[Extern(union: true)]
  record USB_20_PORT_STATUS,
    as_ushort16 : UInt16,
    anonymous : Anonymous_e__Struct_ do

    # Nested Type Anonymous_e__Struct_
    @[Extern]
    record Anonymous_e__Struct_,
      _bitfield : UInt16

  end

  @[Extern(union: true)]
  record USB_20_PORT_CHANGE,
    as_ushort16 : UInt16,
    anonymous : Anonymous_e__Struct_ do

    # Nested Type Anonymous_e__Struct_
    @[Extern]
    record Anonymous_e__Struct_,
      _bitfield : UInt16

  end

  @[Extern(union: true)]
  record USB_30_PORT_STATUS,
    as_ushort16 : UInt16,
    anonymous : Anonymous_e__Struct_ do

    # Nested Type Anonymous_e__Struct_
    @[Extern]
    record Anonymous_e__Struct_,
      _bitfield : UInt16

  end

  @[Extern(union: true)]
  record USB_30_PORT_CHANGE,
    as_ushort16 : UInt16,
    anonymous : Anonymous_e__Struct_ do

    # Nested Type Anonymous_e__Struct_
    @[Extern]
    record Anonymous_e__Struct_,
      _bitfield : UInt16

  end

  @[Extern(union: true)]
  record USB_PORT_STATUS,
    as_ushort16 : UInt16,
    usb20_port_status : Win32cr::Devices::Usb::USB_20_PORT_STATUS,
    usb30_port_status : Win32cr::Devices::Usb::USB_30_PORT_STATUS

  @[Extern(union: true)]
  record USB_PORT_CHANGE,
    as_ushort16 : UInt16,
    usb20_port_change : Win32cr::Devices::Usb::USB_20_PORT_CHANGE,
    usb30_port_change : Win32cr::Devices::Usb::USB_30_PORT_CHANGE

  @[Extern(union: true)]
  record USB_PORT_EXT_STATUS,
    as_ulong32 : UInt32,
    anonymous : Anonymous_e__Struct_ do

    # Nested Type Anonymous_e__Struct_
    @[Extern]
    record Anonymous_e__Struct_,
      _bitfield : UInt32

  end

  @[Extern(union: true)]
  record USB_PORT_STATUS_AND_CHANGE,
    as_ulong32 : UInt32,
    anonymous : Anonymous_e__Struct_ do

    # Nested Type Anonymous_e__Struct_
    @[Extern]
    record Anonymous_e__Struct_,
      port_status : Win32cr::Devices::Usb::USB_PORT_STATUS,
      port_change : Win32cr::Devices::Usb::USB_PORT_CHANGE

  end

  @[Extern(union: true)]
  record USB_PORT_EXT_STATUS_AND_CHANGE,
    as_ulong64 : UInt64,
    anonymous : Anonymous_e__Struct_ do

    # Nested Type Anonymous_e__Struct_
    @[Extern]
    record Anonymous_e__Struct_,
      port_status_change : Win32cr::Devices::Usb::USB_PORT_STATUS_AND_CHANGE,
      port_ext_status : Win32cr::Devices::Usb::USB_PORT_EXT_STATUS

  end

  @[Extern(union: true)]
  record USB_HUB_30_PORT_REMOTE_WAKE_MASK,
    as_uchar8 : UInt8,
    anonymous : Anonymous_e__Struct_ do

    # Nested Type Anonymous_e__Struct_
    @[Extern]
    record Anonymous_e__Struct_,
      _bitfield : UInt8

  end

  @[Extern(union: true)]
  record USB_FUNCTION_SUSPEND_OPTIONS,
    as_uchar : UInt8,
    anonymous : Anonymous_e__Struct_ do

    # Nested Type Anonymous_e__Struct_
    @[Extern]
    record Anonymous_e__Struct_,
      _bitfield : UInt8

  end

  @[Extern]
  record USB_CONFIGURATION_POWER_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    self_power_consumed_d0 : UInt8[3],
    bPowerSummaryId : UInt8,
    bBusPowerSavingD1 : UInt8,
    bSelfPowerSavingD1 : UInt8,
    bBusPowerSavingD2 : UInt8,
    bSelfPowerSavingD2 : UInt8,
    bBusPowerSavingD3 : UInt8,
    bSelfPowerSavingD3 : UInt8,
    transition_time_from_d1 : UInt16,
    transition_time_from_d2 : UInt16,
    transition_time_from_d3 : UInt16

  @[Extern]
  record USB_INTERFACE_POWER_DESCRIPTOR,
    bLength : UInt8,
    bDescriptorType : UInt8,
    bmCapabilitiesFlags : UInt8,
    bBusPowerSavingD1 : UInt8,
    bSelfPowerSavingD1 : UInt8,
    bBusPowerSavingD2 : UInt8,
    bSelfPowerSavingD2 : UInt8,
    bBusPowerSavingD3 : UInt8,
    bSelfPowerSavingD3 : UInt8,
    transition_time_from_d1 : UInt16,
    transition_time_from_d2 : UInt16,
    transition_time_from_d3 : UInt16

  @[Extern]
  record USBD_VERSION_INFORMATION,
    usbdi_version : UInt32,
    supported_usb_version : UInt32

  @[Extern]
  record USBD_DEVICE_INFORMATION,
    offset_next : UInt32,
    usbd_device_handle : Void*,
    device_descriptor : Win32cr::Devices::Usb::USB_DEVICE_DESCRIPTOR

  @[Extern]
  record USBD_PIPE_INFORMATION,
    maximum_packet_size : UInt16,
    endpoint_address : UInt8,
    interval : UInt8,
    pipe_type : Win32cr::Devices::Usb::USBD_PIPE_TYPE,
    pipe_handle : Void*,
    maximum_transfer_size : UInt32,
    pipe_flags : UInt32

  @[Extern]
  record USBD_ENDPOINT_OFFLOAD_INFORMATION,
    size : UInt32,
    endpoint_address : UInt16,
    resource_id : UInt32,
    mode : Win32cr::Devices::Usb::USBD_ENDPOINT_OFFLOAD_MODE,
    _bitfield1 : UInt32,
    _bitfield2 : UInt32,
    transfer_segment_la : Win32cr::Foundation::LARGE_INTEGER,
    transfer_segment_va : Void*,
    transfer_ring_size : LibC::UIntPtrT,
    transfer_ring_initial_cycle_bit : UInt32,
    message_number : UInt32,
    event_ring_segment_la : Win32cr::Foundation::LARGE_INTEGER,
    event_ring_segment_va : Void*,
    event_ring_size : LibC::UIntPtrT,
    event_ring_initial_cycle_bit : UInt32

  @[Extern]
  record USBD_INTERFACE_INFORMATION,
    length : UInt16,
    interface_number : UInt8,
    alternate_setting : UInt8,
    class__ : UInt8,
    sub_class : UInt8,
    protocol : UInt8,
    reserved : UInt8,
    interface_handle : Void*,
    number_of_pipes : UInt32,
    pipes : Win32cr::Devices::Usb::USBD_PIPE_INFORMATION*

  @[Extern]
  record URB_HCD_AREA_,
    reserved8 : Void*[8]

  @[Extern]
  record URB_HEADER_,
    length : UInt16,
    function : UInt16,
    status : Int32,
    usbd_device_handle : Void*,
    usbd_flags : UInt32

  @[Extern]
  record URB_SELECT_INTERFACE_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    configuration_handle : Void*,
    interface : Win32cr::Devices::Usb::USBD_INTERFACE_INFORMATION

  @[Extern]
  record URB_SELECT_CONFIGURATION_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    configuration_descriptor : Win32cr::Devices::Usb::USB_CONFIGURATION_DESCRIPTOR*,
    configuration_handle : Void*,
    interface : Win32cr::Devices::Usb::USBD_INTERFACE_INFORMATION

  @[Extern]
  record URB_PIPE_REQUEST_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    pipe_handle : Void*,
    reserved : UInt32

  @[Extern]
  record URB_FRAME_LENGTH_CONTROL_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_

  @[Extern]
  record URB_GET_FRAME_LENGTH_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    frame_length : UInt32,
    frame_number : UInt32

  @[Extern]
  record URB_SET_FRAME_LENGTH_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    frame_length_delta : Int32

  @[Extern]
  record URB_GET_CURRENT_FRAME_NUMBER_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    frame_number : UInt32

  @[Extern]
  record URB_CONTROL_DESCRIPTOR_REQUEST_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    reserved : Void*,
    reserved0 : UInt32,
    transfer_buffer_length : UInt32,
    transfer_buffer : Void*,
    transfer_buffer_mdl : Void*,
    urb_link : Win32cr::Devices::Usb::URB*,
    hca : Win32cr::Devices::Usb::URB_HCD_AREA_,
    reserved1 : UInt16,
    index : UInt8,
    descriptor_type : UInt8,
    language_id : UInt16,
    reserved2 : UInt16

  @[Extern]
  record URB_CONTROL_GET_STATUS_REQUEST_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    reserved : Void*,
    reserved0 : UInt32,
    transfer_buffer_length : UInt32,
    transfer_buffer : Void*,
    transfer_buffer_mdl : Void*,
    urb_link : Win32cr::Devices::Usb::URB*,
    hca : Win32cr::Devices::Usb::URB_HCD_AREA_,
    reserved1 : UInt8[4],
    index : UInt16,
    reserved2 : UInt16

  @[Extern]
  record URB_CONTROL_FEATURE_REQUEST_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    reserved : Void*,
    reserved2 : UInt32,
    reserved3 : UInt32,
    reserved4 : Void*,
    reserved5 : Void*,
    urb_link : Win32cr::Devices::Usb::URB*,
    hca : Win32cr::Devices::Usb::URB_HCD_AREA_,
    reserved0 : UInt16,
    feature_selector : UInt16,
    index : UInt16,
    reserved1 : UInt16

  @[Extern]
  record URB_CONTROL_VENDOR_OR_CLASS_REQUEST_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    reserved : Void*,
    transfer_flags : UInt32,
    transfer_buffer_length : UInt32,
    transfer_buffer : Void*,
    transfer_buffer_mdl : Void*,
    urb_link : Win32cr::Devices::Usb::URB*,
    hca : Win32cr::Devices::Usb::URB_HCD_AREA_,
    request_type_reserved_bits : UInt8,
    request : UInt8,
    value : UInt16,
    index : UInt16,
    reserved1 : UInt16

  @[Extern]
  record URB_CONTROL_GET_INTERFACE_REQUEST_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    reserved : Void*,
    reserved0 : UInt32,
    transfer_buffer_length : UInt32,
    transfer_buffer : Void*,
    transfer_buffer_mdl : Void*,
    urb_link : Win32cr::Devices::Usb::URB*,
    hca : Win32cr::Devices::Usb::URB_HCD_AREA_,
    reserved1 : UInt8[4],
    interface : UInt16,
    reserved2 : UInt16

  @[Extern]
  record URB_CONTROL_GET_CONFIGURATION_REQUEST_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    reserved : Void*,
    reserved0 : UInt32,
    transfer_buffer_length : UInt32,
    transfer_buffer : Void*,
    transfer_buffer_mdl : Void*,
    urb_link : Win32cr::Devices::Usb::URB*,
    hca : Win32cr::Devices::Usb::URB_HCD_AREA_,
    reserved1 : UInt8[8]

  @[Extern]
  record OS_STRING,
    bLength : UInt8,
    bDescriptorType : UInt8,
    microsoft_string : UInt16[7],
    bVendorCode : UInt8,
    anonymous : Anonymous_e__Union_ do

    # Nested Type Anonymous_e__Union_
    @[Extern(union: true)]
    record Anonymous_e__Union_,
      bPad : UInt8,
      bFlags : UInt8

  end

  @[Extern]
  record URB_OS_FEATURE_DESCRIPTOR_REQUEST_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    reserved : Void*,
    reserved0 : UInt32,
    transfer_buffer_length : UInt32,
    transfer_buffer : Void*,
    transfer_buffer_mdl : Void*,
    urb_link : Win32cr::Devices::Usb::URB*,
    hca : Win32cr::Devices::Usb::URB_HCD_AREA_,
    _bitfield : UInt8,
    reserved2 : UInt8,
    interface_number : UInt8,
    ms_page_index : UInt8,
    ms_feature_descriptor_index : UInt16,
    reserved3 : UInt16

  @[Extern]
  record URB_CONTROL_TRANSFER_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    pipe_handle : Void*,
    transfer_flags : UInt32,
    transfer_buffer_length : UInt32,
    transfer_buffer : Void*,
    transfer_buffer_mdl : Void*,
    urb_link : Win32cr::Devices::Usb::URB*,
    hca : Win32cr::Devices::Usb::URB_HCD_AREA_,
    setup_packet : UInt8[8]

  @[Extern]
  record URB_CONTROL_TRANSFER_EX_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    pipe_handle : Void*,
    transfer_flags : UInt32,
    transfer_buffer_length : UInt32,
    transfer_buffer : Void*,
    transfer_buffer_mdl : Void*,
    timeout : UInt32,
    hca : Win32cr::Devices::Usb::URB_HCD_AREA_,
    setup_packet : UInt8[8]

  @[Extern]
  record URB_BULK_OR_INTERRUPT_TRANSFER_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    pipe_handle : Void*,
    transfer_flags : UInt32,
    transfer_buffer_length : UInt32,
    transfer_buffer : Void*,
    transfer_buffer_mdl : Void*,
    urb_link : Win32cr::Devices::Usb::URB*,
    hca : Win32cr::Devices::Usb::URB_HCD_AREA_

  @[Extern]
  record USBD_ISO_PACKET_DESCRIPTOR,
    offset : UInt32,
    length : UInt32,
    status : Int32

  @[Extern]
  record URB_ISOCH_TRANSFER_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    pipe_handle : Void*,
    transfer_flags : UInt32,
    transfer_buffer_length : UInt32,
    transfer_buffer : Void*,
    transfer_buffer_mdl : Void*,
    urb_link : Win32cr::Devices::Usb::URB*,
    hca : Win32cr::Devices::Usb::URB_HCD_AREA_,
    start_frame : UInt32,
    number_of_packets : UInt32,
    error_count : UInt32,
    iso_packet : Win32cr::Devices::Usb::USBD_ISO_PACKET_DESCRIPTOR*

  @[Extern]
  record USBD_STREAM_INFORMATION,
    pipe_handle : Void*,
    stream_id : UInt32,
    maximum_transfer_size : UInt32,
    pipe_flags : UInt32

  @[Extern]
  record URB_OPEN_STATIC_STREAMS_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    pipe_handle : Void*,
    number_of_streams : UInt32,
    stream_info_version : UInt16,
    stream_info_size : UInt16,
    streams : Win32cr::Devices::Usb::USBD_STREAM_INFORMATION*

  @[Extern]
  record URB_GET_ISOCH_PIPE_TRANSFER_PATH_DELAYS_,
    hdr : Win32cr::Devices::Usb::URB_HEADER_,
    pipe_handle : Void*,
    maximum_send_path_delay_in_milli_seconds : UInt32,
    maximum_completion_path_delay_in_milli_seconds : UInt32

  @[Extern]
  record URB,
    anonymous : Anonymous_e__Union_ do

    # Nested Type Anonymous_e__Union_
    @[Extern(union: true)]
    record Anonymous_e__Union_,
      urb_header : Win32cr::Devices::Usb::URB_HEADER_,
      urb_select_interface : Win32cr::Devices::Usb::URB_SELECT_INTERFACE_,
      urb_select_configuration : Win32cr::Devices::Usb::URB_SELECT_CONFIGURATION_,
      urb_pipe_request : Win32cr::Devices::Usb::URB_PIPE_REQUEST_,
      urb_frame_length_control : Win32cr::Devices::Usb::URB_FRAME_LENGTH_CONTROL_,
      urb_get_frame_length : Win32cr::Devices::Usb::URB_GET_FRAME_LENGTH_,
      urb_set_frame_length : Win32cr::Devices::Usb::URB_SET_FRAME_LENGTH_,
      urb_get_current_frame_number : Win32cr::Devices::Usb::URB_GET_CURRENT_FRAME_NUMBER_,
      urb_control_transfer : Win32cr::Devices::Usb::URB_CONTROL_TRANSFER_,
      urb_control_transfer_ex : Win32cr::Devices::Usb::URB_CONTROL_TRANSFER_EX_,
      urb_bulk_or_interrupt_transfer : Win32cr::Devices::Usb::URB_BULK_OR_INTERRUPT_TRANSFER_,
      urb_isochronous_transfer : Win32cr::Devices::Usb::URB_ISOCH_TRANSFER_,
      urb_control_descriptor_request : Win32cr::Devices::Usb::URB_CONTROL_DESCRIPTOR_REQUEST_,
      urb_control_get_status_request : Win32cr::Devices::Usb::URB_CONTROL_GET_STATUS_REQUEST_,
      urb_control_feature_request : Win32cr::Devices::Usb::URB_CONTROL_FEATURE_REQUEST_,
      urb_control_vendor_class_request : Win32cr::Devices::Usb::URB_CONTROL_VENDOR_OR_CLASS_REQUEST_,
      urb_control_get_interface_request : Win32cr::Devices::Usb::URB_CONTROL_GET_INTERFACE_REQUEST_,
      urb_control_get_configuration_request : Win32cr::Devices::Usb::URB_CONTROL_GET_CONFIGURATION_REQUEST_,
      urb_os_feature_descriptor_request : Win32cr::Devices::Usb::URB_OS_FEATURE_DESCRIPTOR_REQUEST_,
      urb_open_static_streams : Win32cr::Devices::Usb::URB_OPEN_STATIC_STREAMS_,
      urb_get_isoch_pipe_transfer_path_delays : Win32cr::Devices::Usb::URB_GET_ISOCH_PIPE_TRANSFER_PATH_DELAYS_

  end

  @[Extern]
  record USB_IDLE_CALLBACK_INFO,
    idle_callback : Win32cr::Devices::Usb::USB_IDLE_CALLBACK,
    idle_context : Void*

  @[Extern]
  record USBUSER_REQUEST_HEADER,
    usb_user_request : UInt32,
    usb_user_status_code : Win32cr::Devices::Usb::USB_USER_ERROR_CODE,
    request_buffer_length : UInt32,
    actual_buffer_length : UInt32

  @[Extern]
  record PACKET_PARAMETERS,
    device_address : UInt8,
    endpoint_address : UInt8,
    maximum_packet_size : UInt16,
    timeout : UInt32,
    flags : UInt32,
    data_length : UInt32,
    hub_device_address : UInt16,
    port_tt_number : UInt16,
    error_count : UInt8,
    pad : UInt8[3],
    usbd_status_code : Int32,
    data : UInt8[4]

  @[Extern]
  record USBUSER_SEND_ONE_PACKET,
    header : Win32cr::Devices::Usb::USBUSER_REQUEST_HEADER,
    packet_parameters : Win32cr::Devices::Usb::PACKET_PARAMETERS

  @[Extern]
  record RAW_RESET_PORT_PARAMETERS,
    port_number : UInt16,
    port_status : UInt16

  @[Extern]
  record USBUSER_RAW_RESET_ROOT_PORT,
    header : Win32cr::Devices::Usb::USBUSER_REQUEST_HEADER,
    parameters : Win32cr::Devices::Usb::RAW_RESET_PORT_PARAMETERS

  @[Extern]
  record RAW_ROOTPORT_FEATURE,
    port_number : UInt16,
    port_feature : UInt16,
    port_status : UInt16

  @[Extern]
  record USBUSER_ROOTPORT_FEATURE_REQUEST,
    header : Win32cr::Devices::Usb::USBUSER_REQUEST_HEADER,
    parameters : Win32cr::Devices::Usb::RAW_ROOTPORT_FEATURE

  @[Extern]
  record RAW_ROOTPORT_PARAMETERS,
    port_number : UInt16,
    port_status : UInt16

  @[Extern]
  record USBUSER_ROOTPORT_PARAMETERS,
    header : Win32cr::Devices::Usb::USBUSER_REQUEST_HEADER,
    parameters : Win32cr::Devices::Usb::RAW_ROOTPORT_PARAMETERS

  @[Extern]
  record USB_CONTROLLER_INFO_0,
    pci_vendor_id : UInt32,
    pci_device_id : UInt32,
    pci_revision : UInt32,
    number_of_root_ports : UInt32,
    controller_flavor : Win32cr::Devices::Usb::USB_CONTROLLER_FLAVOR,
    hc_feature_flags : UInt32

  @[Extern]
  record USBUSER_CONTROLLER_INFO_0,
    header : Win32cr::Devices::Usb::USBUSER_REQUEST_HEADER,
    info0 : Win32cr::Devices::Usb::USB_CONTROLLER_INFO_0

  @[Extern]
  record USB_UNICODE_NAME,
    length : UInt32,
    string : UInt16*

  @[Extern]
  record USBUSER_CONTROLLER_UNICODE_NAME,
    header : Win32cr::Devices::Usb::USBUSER_REQUEST_HEADER,
    unicode_name : Win32cr::Devices::Usb::USB_UNICODE_NAME

  @[Extern]
  record USB_PASS_THRU_PARAMETERS,
    function_guid : LibC::GUID,
    parameter_length : UInt32,
    parameters : UInt8[4]

  @[Extern]
  record USBUSER_PASS_THRU_REQUEST,
    header : Win32cr::Devices::Usb::USBUSER_REQUEST_HEADER,
    pass_thru : Win32cr::Devices::Usb::USB_PASS_THRU_PARAMETERS

  @[Extern]
  record USB_POWER_INFO,
    system_state : Win32cr::Devices::Usb::WDMUSB_POWER_STATE,
    hc_device_power_state : Win32cr::Devices::Usb::WDMUSB_POWER_STATE,
    hc_device_wake : Win32cr::Devices::Usb::WDMUSB_POWER_STATE,
    hc_system_wake : Win32cr::Devices::Usb::WDMUSB_POWER_STATE,
    rh_device_power_state : Win32cr::Devices::Usb::WDMUSB_POWER_STATE,
    rh_device_wake : Win32cr::Devices::Usb::WDMUSB_POWER_STATE,
    rh_system_wake : Win32cr::Devices::Usb::WDMUSB_POWER_STATE,
    last_system_sleep_state : Win32cr::Devices::Usb::WDMUSB_POWER_STATE,
    can_wakeup : Win32cr::Foundation::BOOLEAN,
    is_powered : Win32cr::Foundation::BOOLEAN

  @[Extern]
  record USBUSER_POWER_INFO_REQUEST,
    header : Win32cr::Devices::Usb::USBUSER_REQUEST_HEADER,
    power_information : Win32cr::Devices::Usb::USB_POWER_INFO

  @[Extern]
  record USB_OPEN_RAW_DEVICE_PARAMETERS,
    port_status : UInt16,
    max_packet_ep0 : UInt16

  @[Extern]
  record USBUSER_OPEN_RAW_DEVICE,
    header : Win32cr::Devices::Usb::USBUSER_REQUEST_HEADER,
    parameters : Win32cr::Devices::Usb::USB_OPEN_RAW_DEVICE_PARAMETERS

  @[Extern]
  record USB_CLOSE_RAW_DEVICE_PARAMETERS,
    xxx : UInt32

  @[Extern]
  record USBUSER_CLOSE_RAW_DEVICE,
    header : Win32cr::Devices::Usb::USBUSER_REQUEST_HEADER,
    parameters : Win32cr::Devices::Usb::USB_CLOSE_RAW_DEVICE_PARAMETERS

  @[Extern]
  record USB_SEND_RAW_COMMAND_PARAMETERS,
    usb_bm_request : UInt8,
    usb_b_request : UInt8,
    usb_w_vlaue : UInt16,
    usb_w_index : UInt16,
    usb_w_length : UInt16,
    device_address : UInt16,
    maximum_packet_size : UInt16,
    timeout : UInt32,
    data_length : UInt32,
    usbd_status_code : Int32,
    data : UInt8[4]

  @[Extern]
  record USBUSER_SEND_RAW_COMMAND,
    header : Win32cr::Devices::Usb::USBUSER_REQUEST_HEADER,
    parameters : Win32cr::Devices::Usb::USB_SEND_RAW_COMMAND_PARAMETERS

  @[Extern]
  record USB_BANDWIDTH_INFO,
    device_count : UInt32,
    total_bus_bandwidth : UInt32,
    total32sec_bandwidth : UInt32,
    alloced_bulk_and_control : UInt32,
    alloced_iso : UInt32,
    alloced_interrupt_1ms : UInt32,
    alloced_interrupt_2ms : UInt32,
    alloced_interrupt_4ms : UInt32,
    alloced_interrupt_8ms : UInt32,
    alloced_interrupt_16ms : UInt32,
    alloced_interrupt_32ms : UInt32

  @[Extern]
  record USBUSER_BANDWIDTH_INFO_REQUEST,
    header : Win32cr::Devices::Usb::USBUSER_REQUEST_HEADER,
    bandwidth_information : Win32cr::Devices::Usb::USB_BANDWIDTH_INFO

  @[Extern]
  record USB_BUS_STATISTICS_0,
    device_count : UInt32,
    current_system_time : Win32cr::Foundation::LARGE_INTEGER,
    current_usb_frame : UInt32,
    bulk_bytes : UInt32,
    iso_bytes : UInt32,
    interrupt_bytes : UInt32,
    control_data_bytes : UInt32,
    pci_interrupt_count : UInt32,
    hard_reset_count : UInt32,
    worker_signal_count : UInt32,
    common_buffer_bytes : UInt32,
    worker_idle_time_ms : UInt32,
    root_hub_enabled : Win32cr::Foundation::BOOLEAN,
    root_hub_device_power_state : UInt8,
    unused : UInt8,
    name_index : UInt8

  @[Extern]
  record USBUSER_BUS_STATISTICS_0_REQUEST,
    header : Win32cr::Devices::Usb::USBUSER_REQUEST_HEADER,
    bus_statistics0 : Win32cr::Devices::Usb::USB_BUS_STATISTICS_0

  @[Extern]
  record USB_DRIVER_VERSION_PARAMETERS,
    driver_tracking_code : UInt32,
    usbdi_version : UInt32,
    usbuser_version : UInt32,
    checked_port_driver : Win32cr::Foundation::BOOLEAN,
    checked_miniport_driver : Win32cr::Foundation::BOOLEAN,
    usb_version : UInt16

  @[Extern]
  record USBUSER_GET_DRIVER_VERSION,
    header : Win32cr::Devices::Usb::USBUSER_REQUEST_HEADER,
    parameters : Win32cr::Devices::Usb::USB_DRIVER_VERSION_PARAMETERS

  @[Extern]
  record USB_USB2HW_VERSION_PARAMETERS,
    usb2_hw_revision : UInt8

  @[Extern]
  record USBUSER_GET_USB2HW_VERSION,
    header : Win32cr::Devices::Usb::USBUSER_REQUEST_HEADER,
    parameters : Win32cr::Devices::Usb::USB_USB2HW_VERSION_PARAMETERS

  @[Extern]
  record USBUSER_REFRESH_HCT_REG,
    header : Win32cr::Devices::Usb::USBUSER_REQUEST_HEADER,
    flags : UInt32

  @[Extern]
  record WINUSB_PIPE_INFORMATION,
    pipe_type : Win32cr::Devices::Usb::USBD_PIPE_TYPE,
    pipe_id : UInt8,
    maximum_packet_size : UInt16,
    interval : UInt8

  @[Extern]
  record WINUSB_PIPE_INFORMATION_EX,
    pipe_type : Win32cr::Devices::Usb::USBD_PIPE_TYPE,
    pipe_id : UInt8,
    maximum_packet_size : UInt16,
    interval : UInt8,
    maximum_bytes_per_interval : UInt32

  @[Extern]
  record WINUSB_SETUP_PACKET,
    request_type : UInt8,
    request : UInt8,
    value : UInt16,
    index : UInt16,
    length : UInt16

  @[Extern]
  record USB_START_TRACKING_FOR_TIME_SYNC_INFORMATION,
    time_tracking_handle : Win32cr::Foundation::HANDLE,
    is_startup_delay_tolerable : Win32cr::Foundation::BOOLEAN

  @[Extern]
  record USB_STOP_TRACKING_FOR_TIME_SYNC_INFORMATION,
    time_tracking_handle : Win32cr::Foundation::HANDLE

  @[Extern]
  record USB_FRAME_NUMBER_AND_QPC_FOR_TIME_SYNC_INFORMATION,
    time_tracking_handle : Win32cr::Foundation::HANDLE,
    input_frame_number : UInt32,
    input_micro_frame_number : UInt32,
    query_performance_counter_at_input_frame_or_micro_frame : Win32cr::Foundation::LARGE_INTEGER,
    query_performance_counter_frequency : Win32cr::Foundation::LARGE_INTEGER,
    predicted_accuracy_in_micro_seconds : UInt32,
    current_generation_id : UInt32,
    current_query_performance_counter : Win32cr::Foundation::LARGE_INTEGER,
    current_hardware_frame_number : UInt32,
    current_hardware_micro_frame_number : UInt32,
    current_usb_frame_number : UInt32

  @[Extern]
  record ALTERNATE_INTERFACE,
    interface_number : UInt16,
    alternate_interface_number : UInt16

  @[Extern]
  record USBFN_NOTIFICATION,
    event : Win32cr::Devices::Usb::USBFN_EVENT,
    u : U_e__union_ do

    # Nested Type U_e__union_
    @[Extern(union: true)]
    record U_e__union_,
      bus_speed : Win32cr::Devices::Usb::USBFN_BUS_SPEED,
      setup_packet : Win32cr::Devices::Usb::USB_DEFAULT_PIPE_SETUP_PACKET,
      configuration_value : UInt16,
      port_type : Win32cr::Devices::Usb::USBFN_PORT_TYPE,
      alternate_interface : Win32cr::Devices::Usb::ALTERNATE_INTERFACE

  end

  @[Extern]
  record USBFN_PIPE_INFORMATION,
    ep_desc : Win32cr::Devices::Usb::USB_ENDPOINT_DESCRIPTOR,
    pipe_id : UInt32

  @[Extern]
  record USBFN_CLASS_INTERFACE,
    interface_number : UInt8,
    pipe_count : UInt8,
    pipe_arr : Win32cr::Devices::Usb::USBFN_PIPE_INFORMATION[16]

  @[Extern]
  record USBFN_CLASS_INFORMATION_PACKET,
    full_speed_class_interface : Win32cr::Devices::Usb::USBFN_CLASS_INTERFACE,
    high_speed_class_interface : Win32cr::Devices::Usb::USBFN_CLASS_INTERFACE,
    interface_name : UInt16[40],
    interface_guid : UInt16[39],
    has_interface_guid : Win32cr::Foundation::BOOLEAN,
    super_speed_class_interface : Win32cr::Devices::Usb::USBFN_CLASS_INTERFACE

  @[Extern]
  record USBFN_CLASS_INTERFACE_EX,
    base_interface_number : UInt8,
    interface_count : UInt8,
    pipe_count : UInt8,
    pipe_arr : Win32cr::Devices::Usb::USBFN_PIPE_INFORMATION[16]

  @[Extern]
  record USBFN_CLASS_INFORMATION_PACKET_EX,
    full_speed_class_interface_ex : Win32cr::Devices::Usb::USBFN_CLASS_INTERFACE_EX,
    high_speed_class_interface_ex : Win32cr::Devices::Usb::USBFN_CLASS_INTERFACE_EX,
    super_speed_class_interface_ex : Win32cr::Devices::Usb::USBFN_CLASS_INTERFACE_EX,
    interface_name : UInt16[40],
    interface_guid : UInt16[39],
    has_interface_guid : Win32cr::Foundation::BOOLEAN

  @[Extern]
  record USBFN_INTERFACE_INFO,
    interface_number : UInt8,
    speed : Win32cr::Devices::Usb::USBFN_BUS_SPEED,
    size : UInt16,
    interface_descriptor_set : UInt8*

  @[Extern]
  record USBFN_USB_STRING,
    string_index : UInt8,
    usb_string : UInt16[255]

  @[Extern]
  record USBFN_BUS_CONFIGURATION_INFO,
    configuration_name : UInt16[40],
    is_current : Win32cr::Foundation::BOOLEAN,
    is_active : Win32cr::Foundation::BOOLEAN

  @[Extern]
  record DRV_VERSION,
    major : UInt32,
    minor : UInt32,
    internal : UInt32

  @[Extern]
  record IO_BLOCK,
    uOffset : UInt32,
    uLength : UInt32,
    pbyData : UInt8*,
    uIndex : UInt32

  @[Extern]
  record IO_BLOCK_EX,
    uOffset : UInt32,
    uLength : UInt32,
    pbyData : UInt8*,
    uIndex : UInt32,
    bRequest : UInt8,
    bmRequestType : UInt8,
    fTransferDirectionIn : UInt8

  @[Extern]
  record CHANNEL_INFO,
    event_channel_size : UInt32,
    uReadDataAlignment : UInt32,
    uWriteDataAlignment : UInt32

  @[Extern]
  record USBSCAN_GET_DESCRIPTOR,
    descriptor_type : UInt8,
    index : UInt8,
    language_id : UInt16

  @[Extern]
  record DEVICE_DESCRIPTOR,
    usVendorId : UInt16,
    usProductId : UInt16,
    usBcdDevice : UInt16,
    usLanguageId : UInt16

  @[Extern]
  record USBSCAN_PIPE_INFORMATION,
    maximum_packet_size : UInt16,
    endpoint_address : UInt8,
    interval : UInt8,
    pipe_type : Win32cr::Devices::Usb::RAW_PIPE_TYPE

  @[Extern]
  record USBSCAN_PIPE_CONFIGURATION,
    number_of_pipes : UInt32,
    pipe_info : Win32cr::Devices::Usb::USBSCAN_PIPE_INFORMATION[8]

  @[Extern]
  record USBSCAN_TIMEOUT,
    timeout_read : UInt32,
    timeout_write : UInt32,
    timeout_event : UInt32

  @[Link("winusb")]
  lib C
    fun WinUsb_Initialize(device_handle : Win32cr::Foundation::HANDLE, interface_handle : Void**) : Win32cr::Foundation::BOOL

    fun WinUsb_Free(interface_handle : Void*) : Win32cr::Foundation::BOOL

    fun WinUsb_GetAssociatedInterface(interface_handle : Void*, associated_interface_index : UInt8, associated_interface_handle : Void**) : Win32cr::Foundation::BOOL

    fun WinUsb_GetDescriptor(interface_handle : Void*, descriptor_type : UInt8, index : UInt8, language_id : UInt16, buffer : UInt8*, buffer_length : UInt32, length_transferred : UInt32*) : Win32cr::Foundation::BOOL

    fun WinUsb_QueryInterfaceSettings(interface_handle : Void*, alternate_interface_number : UInt8, usb_alt_interface_descriptor : Win32cr::Devices::Usb::USB_INTERFACE_DESCRIPTOR*) : Win32cr::Foundation::BOOL

    fun WinUsb_QueryDeviceInformation(interface_handle : Void*, information_type : UInt32, buffer_length : UInt32*, buffer : Void*) : Win32cr::Foundation::BOOL

    fun WinUsb_SetCurrentAlternateSetting(interface_handle : Void*, setting_number : UInt8) : Win32cr::Foundation::BOOL

    fun WinUsb_GetCurrentAlternateSetting(interface_handle : Void*, setting_number : UInt8*) : Win32cr::Foundation::BOOL

    fun WinUsb_QueryPipe(interface_handle : Void*, alternate_interface_number : UInt8, pipe_index : UInt8, pipe_information : Win32cr::Devices::Usb::WINUSB_PIPE_INFORMATION*) : Win32cr::Foundation::BOOL

    fun WinUsb_QueryPipeEx(interface_handle : Void*, alternate_setting_number : UInt8, pipe_index : UInt8, pipe_information_ex : Win32cr::Devices::Usb::WINUSB_PIPE_INFORMATION_EX*) : Win32cr::Foundation::BOOL

    fun WinUsb_SetPipePolicy(interface_handle : Void*, pipe_id : UInt8, policy_type : UInt32, value_length : UInt32, value : Void*) : Win32cr::Foundation::BOOL

    fun WinUsb_GetPipePolicy(interface_handle : Void*, pipe_id : UInt8, policy_type : UInt32, value_length : UInt32*, value : Void*) : Win32cr::Foundation::BOOL

    fun WinUsb_ReadPipe(interface_handle : Void*, pipe_id : UInt8, buffer : UInt8*, buffer_length : UInt32, length_transferred : UInt32*, overlapped : Win32cr::System::IO::OVERLAPPED*) : Win32cr::Foundation::BOOL

    fun WinUsb_WritePipe(interface_handle : Void*, pipe_id : UInt8, buffer : UInt8*, buffer_length : UInt32, length_transferred : UInt32*, overlapped : Win32cr::System::IO::OVERLAPPED*) : Win32cr::Foundation::BOOL

    fun WinUsb_ControlTransfer(interface_handle : Void*, setup_packet : Win32cr::Devices::Usb::WINUSB_SETUP_PACKET, buffer : UInt8*, buffer_length : UInt32, length_transferred : UInt32*, overlapped : Win32cr::System::IO::OVERLAPPED*) : Win32cr::Foundation::BOOL

    fun WinUsb_ResetPipe(interface_handle : Void*, pipe_id : UInt8) : Win32cr::Foundation::BOOL

    fun WinUsb_AbortPipe(interface_handle : Void*, pipe_id : UInt8) : Win32cr::Foundation::BOOL

    fun WinUsb_FlushPipe(interface_handle : Void*, pipe_id : UInt8) : Win32cr::Foundation::BOOL

    fun WinUsb_SetPowerPolicy(interface_handle : Void*, policy_type : UInt32, value_length : UInt32, value : Void*) : Win32cr::Foundation::BOOL

    fun WinUsb_GetPowerPolicy(interface_handle : Void*, policy_type : UInt32, value_length : UInt32*, value : Void*) : Win32cr::Foundation::BOOL

    fun WinUsb_GetOverlappedResult(interface_handle : Void*, lpOverlapped : Win32cr::System::IO::OVERLAPPED*, lpNumberOfBytesTransferred : UInt32*, bWait : Win32cr::Foundation::BOOL) : Win32cr::Foundation::BOOL

    fun WinUsb_ParseConfigurationDescriptor(configuration_descriptor : Win32cr::Devices::Usb::USB_CONFIGURATION_DESCRIPTOR*, start_position : Void*, interface_number : Int32, alternate_setting : Int32, interface_class : Int32, interface_sub_class : Int32, interface_protocol : Int32) : Win32cr::Devices::Usb::USB_INTERFACE_DESCRIPTOR*

    fun WinUsb_ParseDescriptors(descriptor_buffer : Void*, total_length : UInt32, start_position : Void*, descriptor_type : Int32) : Win32cr::Devices::Usb::USB_COMMON_DESCRIPTOR*

    fun WinUsb_GetCurrentFrameNumber(interface_handle : Void*, current_frame_number : UInt32*, time_stamp : Win32cr::Foundation::LARGE_INTEGER*) : Win32cr::Foundation::BOOL

    fun WinUsb_GetAdjustedFrameNumber(current_frame_number : UInt32*, time_stamp : Win32cr::Foundation::LARGE_INTEGER) : Win32cr::Foundation::BOOL

    fun WinUsb_RegisterIsochBuffer(interface_handle : Void*, pipe_id : UInt8, buffer : UInt8*, buffer_length : UInt32, isoch_buffer_handle : Void**) : Win32cr::Foundation::BOOL

    fun WinUsb_UnregisterIsochBuffer(isoch_buffer_handle : Void*) : Win32cr::Foundation::BOOL

    fun WinUsb_WriteIsochPipe(buffer_handle : Void*, offset : UInt32, length : UInt32, frame_number : UInt32*, overlapped : Win32cr::System::IO::OVERLAPPED*) : Win32cr::Foundation::BOOL

    fun WinUsb_ReadIsochPipe(buffer_handle : Void*, offset : UInt32, length : UInt32, frame_number : UInt32*, number_of_packets : UInt32, iso_packet_descriptors : Win32cr::Devices::Usb::USBD_ISO_PACKET_DESCRIPTOR*, overlapped : Win32cr::System::IO::OVERLAPPED*) : Win32cr::Foundation::BOOL

    fun WinUsb_WriteIsochPipeAsap(buffer_handle : Void*, offset : UInt32, length : UInt32, continue_stream : Win32cr::Foundation::BOOL, overlapped : Win32cr::System::IO::OVERLAPPED*) : Win32cr::Foundation::BOOL

    fun WinUsb_ReadIsochPipeAsap(buffer_handle : Void*, offset : UInt32, length : UInt32, continue_stream : Win32cr::Foundation::BOOL, number_of_packets : UInt32, iso_packet_descriptors : Win32cr::Devices::Usb::USBD_ISO_PACKET_DESCRIPTOR*, overlapped : Win32cr::System::IO::OVERLAPPED*) : Win32cr::Foundation::BOOL

    fun WinUsb_StartTrackingForTimeSync(interface_handle : Void*, start_tracking_info : Win32cr::Devices::Usb::USB_START_TRACKING_FOR_TIME_SYNC_INFORMATION*) : Win32cr::Foundation::BOOL

    fun WinUsb_GetCurrentFrameNumberAndQpc(interface_handle : Void*, frame_qpc_info : Win32cr::Devices::Usb::USB_FRAME_NUMBER_AND_QPC_FOR_TIME_SYNC_INFORMATION*) : Win32cr::Foundation::BOOL

    fun WinUsb_StopTrackingForTimeSync(interface_handle : Void*, stop_tracking_info : Win32cr::Devices::Usb::USB_STOP_TRACKING_FOR_TIME_SYNC_INFORMATION*) : Win32cr::Foundation::BOOL

  end
end