require "../graphics/direct3d.cr"
require "../foundation.cr"
require "../system/com.cr"
require "../graphics/gdi.cr"

@[Link("delayimp")]
@[Link("user32")]
@[Link(ldflags: "/IGNORE:4199")]
@[Link(ldflags: "/DELAYLOAD:d3d9.dll")]
lib LibWin32
  D3DRTYPECOUNT = 8_u32
  D3DCS_LEFT = 1_i32
  D3DCS_RIGHT = 2_i32
  D3DCS_TOP = 4_i32
  D3DCS_BOTTOM = 8_i32
  D3DCS_FRONT = 16_i32
  D3DCS_BACK = 32_i32
  D3DCS_PLANE0 = 64_i32
  D3DCS_PLANE1 = 128_i32
  D3DCS_PLANE2 = 256_i32
  D3DCS_PLANE3 = 512_i32
  D3DCS_PLANE4 = 1024_i32
  D3DCS_PLANE5 = 2048_i32
  D3D_MAX_SIMULTANEOUS_RENDERTARGETS = 4_u32
  D3DWRAP_W = 4_i32
  D3DDMAPSAMPLER = 256_u32
  D3DVERTEXTEXTURESAMPLER0 = 257_u32
  D3DVERTEXTEXTURESAMPLER1 = 258_u32
  D3DVERTEXTEXTURESAMPLER2 = 259_u32
  D3DVERTEXTEXTURESAMPLER3 = 260_u32
  D3DTSS_TCI_SPHEREMAP = 262144_u32
  D3DTA_TEMP = 5_u32
  D3DTA_CONSTANT = 6_u32
  D3DFVF_XYZW = 16386_u32
  D3DFVF_PSIZE = 32_u32
  D3DFVF_LASTBETA_UBYTE4 = 4096_u32
  D3DFVF_LASTBETA_D3DCOLOR = 32768_u32
  MAXD3DDECLUSAGEINDEX = 15_u32
  MAXD3DDECLLENGTH = 64_u32
  D3DSTREAMSOURCE_INDEXEDDATA = 1073741824_u32
  D3DSTREAMSOURCE_INSTANCEDATA = 2147483648_u32
  D3DSI_OPCODE_MASK = 65535_u32
  D3DSI_INSTLENGTH_MASK = 251658240_u32
  D3DSI_INSTLENGTH_SHIFT = 24_u32
  D3DSI_COISSUE = 1073741824_u32
  D3DSP_OPCODESPECIFICCONTROL_MASK = 16711680_u32
  D3DSP_OPCODESPECIFICCONTROL_SHIFT = 16_u32
  D3DSHADER_COMPARISON_SHIFT = 16_u32
  D3DSP_DCL_USAGE_SHIFT = 0_u32
  D3DSP_DCL_USAGE_MASK = 15_u32
  D3DSP_DCL_USAGEINDEX_SHIFT = 16_u32
  D3DSP_DCL_USAGEINDEX_MASK = 983040_u32
  D3DSP_TEXTURETYPE_SHIFT = 27_u32
  D3DSP_TEXTURETYPE_MASK = 2013265920_u32
  D3DSP_REGNUM_MASK = 2047_u32
  D3DSP_WRITEMASK_0 = 65536_u32
  D3DSP_WRITEMASK_1 = 131072_u32
  D3DSP_WRITEMASK_2 = 262144_u32
  D3DSP_WRITEMASK_3 = 524288_u32
  D3DSP_WRITEMASK_ALL = 983040_u32
  D3DSP_DSTMOD_SHIFT = 20_u32
  D3DSP_DSTMOD_MASK = 15728640_u32
  D3DSP_DSTSHIFT_SHIFT = 24_u32
  D3DSP_DSTSHIFT_MASK = 251658240_u32
  D3DSP_REGTYPE_SHIFT = 28_u32
  D3DSP_REGTYPE_SHIFT2 = 8_u32
  D3DSP_REGTYPE_MASK = 1879048192_u32
  D3DSP_REGTYPE_MASK2 = 6144_u32
  D3DVS_ADDRESSMODE_SHIFT = 13_u32
  D3DSHADER_ADDRESSMODE_SHIFT = 13_u32
  D3DVS_SWIZZLE_SHIFT = 16_u32
  D3DVS_SWIZZLE_MASK = 16711680_u32
  D3DSP_SWIZZLE_SHIFT = 16_u32
  D3DSP_SWIZZLE_MASK = 16711680_u32
  D3DSP_SRCMOD_SHIFT = 24_u32
  D3DSP_SRCMOD_MASK = 251658240_u32
  D3DSP_MIN_PRECISION_SHIFT = 14_u32
  D3DSP_MIN_PRECISION_MASK = 49152_u32
  D3DSI_COMMENTSIZE_SHIFT = 16_u32
  D3DSI_COMMENTSIZE_MASK = 2147418112_u32
  D3DPRESENT_RATE_DEFAULT = 0_u32
  D3DPRESENTFLAG_LOCKABLE_BACKBUFFER = 1_u32
  D3DPRESENTFLAG_DISCARD_DEPTHSTENCIL = 2_u32
  D3DPRESENTFLAG_DEVICECLIP = 4_u32
  D3DPRESENTFLAG_VIDEO = 16_u32
  D3DPRESENTFLAG_NOAUTOROTATE = 32_u32
  D3DPRESENTFLAG_UNPRUNEDMODE = 64_u32
  D3DPRESENTFLAG_OVERLAY_LIMITEDRGB = 128_u32
  D3DPRESENTFLAG_OVERLAY_YCbCr_BT709 = 256_u32
  D3DPRESENTFLAG_OVERLAY_YCbCr_xvYCC = 512_u32
  D3DPRESENTFLAG_RESTRICTED_CONTENT = 1024_u32
  D3DPRESENTFLAG_RESTRICT_SHARED_RESOURCE_DRIVER = 2048_u32
  D3DUSAGE_RENDERTARGET = 1_i32
  D3DUSAGE_DEPTHSTENCIL = 2_i32
  D3DUSAGE_DYNAMIC = 512_i32
  D3DUSAGE_NONSECURE = 8388608_i32
  D3DUSAGE_AUTOGENMIPMAP = 1024_i32
  D3DUSAGE_DMAP = 16384_i32
  D3DUSAGE_QUERY_LEGACYBUMPMAP = 32768_i32
  D3DUSAGE_QUERY_SRGBREAD = 65536_i32
  D3DUSAGE_QUERY_FILTER = 131072_i32
  D3DUSAGE_QUERY_SRGBWRITE = 262144_i32
  D3DUSAGE_QUERY_POSTPIXELSHADER_BLENDING = 524288_i32
  D3DUSAGE_QUERY_VERTEXTEXTURE = 1048576_i32
  D3DUSAGE_QUERY_WRAPANDMIP = 2097152_i32
  D3DUSAGE_WRITEONLY = 8_i32
  D3DUSAGE_SOFTWAREPROCESSING = 16_i32
  D3DUSAGE_DONOTCLIP = 32_i32
  D3DUSAGE_POINTS = 64_i32
  D3DUSAGE_RTPATCHES = 128_i32
  D3DUSAGE_NPATCHES = 256_i32
  D3DUSAGE_TEXTAPI = 268435456_i32
  D3DUSAGE_RESTRICTED_CONTENT = 2048_i32
  D3DUSAGE_RESTRICT_SHARED_RESOURCE = 8192_i32
  D3DUSAGE_RESTRICT_SHARED_RESOURCE_DRIVER = 4096_i32
  D3DLOCK_READONLY = 16_i32
  D3DLOCK_DISCARD = 8192_i32
  D3DLOCK_NOOVERWRITE = 4096_i32
  D3DLOCK_NOSYSLOCK = 2048_i32
  D3DLOCK_DONOTWAIT = 16384_i32
  D3DLOCK_NO_DIRTY_UPDATE = 32768_i32
  MAX_DEVICE_IDENTIFIER_STRING = 512_u32
  D3DISSUE_END = 1_u32
  D3DISSUE_BEGIN = 2_u32
  D3DGETDATA_FLUSH = 1_u32
  D3DCOMPOSERECTS_MAXNUMRECTS = 65535_u32
  D3DCONVOLUTIONMONO_MAXWIDTH = 7_u32
  D3DCONVOLUTIONMONO_MAXHEIGHT = 7_u32
  D3DFMT_A1_SURFACE_MAXWIDTH = 8192_u32
  D3DFMT_A1_SURFACE_MAXHEIGHT = 2048_u32
  D3D9_RESOURCE_PRIORITY_MINIMUM = 671088640_u32
  D3D9_RESOURCE_PRIORITY_LOW = 1342177280_u32
  D3D9_RESOURCE_PRIORITY_NORMAL = 2013265920_u32
  D3D9_RESOURCE_PRIORITY_HIGH = 2684354560_u32
  D3D9_RESOURCE_PRIORITY_MAXIMUM = 3355443200_u32
  D3D_OMAC_SIZE = 16_u32
  D3DAUTHENTICATEDQUERY_PROTECTION = "a84eb584-c495-48aa-b94d-8bd2d6fbce05"
  D3DAUTHENTICATEDQUERY_CHANNELTYPE = "bc1b18a5-b1fb-42ab-bd94-b5828b4bf7be"
  D3DAUTHENTICATEDQUERY_DEVICEHANDLE = "ec1c539d-8cff-4e2a-bcc4-f5692f99f480"
  D3DAUTHENTICATEDQUERY_CRYPTOSESSION = "2634499e-d018-4d74-ac17-7f724059528d"
  D3DAUTHENTICATEDQUERY_RESTRICTEDSHAREDRESOURCEPROCESSCOUNT = "0db207b3-9450-46a6-82de-1b96d44f9cf2"
  D3DAUTHENTICATEDQUERY_RESTRICTEDSHAREDRESOURCEPROCESS = "649bbadb-f0f4-4639-a15b-24393fc3abac"
  D3DAUTHENTICATEDQUERY_UNRESTRICTEDPROTECTEDSHAREDRESOURCECOUNT = "012f0bd6-e662-4474-befd-aa53e5143c6d"
  D3DAUTHENTICATEDQUERY_OUTPUTIDCOUNT = "2c042b5e-8c07-46d5-aabe-8f75cbad4c31"
  D3DAUTHENTICATEDQUERY_OUTPUTID = "839ddca3-9b4e-41e4-b053-892bd2a11ee7"
  D3DAUTHENTICATEDQUERY_ACCESSIBILITYATTRIBUTES = "6214d9d2-432c-4abb-9fce-216eea269e3b"
  D3DAUTHENTICATEDQUERY_ENCRYPTIONWHENACCESSIBLEGUIDCOUNT = "b30f7066-203c-4b07-93fc-ceaafd61241e"
  D3DAUTHENTICATEDQUERY_ENCRYPTIONWHENACCESSIBLEGUID = "f83a5958-e986-4bda-beb0-411f6a7a01b7"
  D3DAUTHENTICATEDQUERY_CURRENTENCRYPTIONWHENACCESSIBLE = "ec1791c7-dad3-4f15-9ec3-faa93d60d4f0"
  D3DAUTHENTICATEDCONFIGURE_INITIALIZE = "06114bdb-3523-470a-8dca-fbc2845154f0"
  D3DAUTHENTICATEDCONFIGURE_PROTECTION = "50455658-3f47-4362-bf99-bfdfcde9ed29"
  D3DAUTHENTICATEDCONFIGURE_CRYPTOSESSION = "6346cc54-2cfc-4ad4-8224-d15837de7700"
  D3DAUTHENTICATEDCONFIGURE_SHAREDRESOURCE = "0772d047-1b40-48e8-9ca6-b5f510de9f01"
  D3DAUTHENTICATEDCONFIGURE_ENCRYPTIONWHENACCESSIBLE = "41fff286-6ae0-4d43-9d55-a46e9efd158a"
  D3DVS20CAPS_PREDICATION = 1_u32
  D3DVS20_MAX_DYNAMICFLOWCONTROLDEPTH = 24_u32
  D3DVS20_MIN_DYNAMICFLOWCONTROLDEPTH = 0_u32
  D3DVS20_MAX_NUMTEMPS = 32_u32
  D3DVS20_MIN_NUMTEMPS = 12_u32
  D3DVS20_MAX_STATICFLOWCONTROLDEPTH = 4_u32
  D3DVS20_MIN_STATICFLOWCONTROLDEPTH = 1_u32
  D3DPS20CAPS_ARBITRARYSWIZZLE = 1_u32
  D3DPS20CAPS_GRADIENTINSTRUCTIONS = 2_u32
  D3DPS20CAPS_PREDICATION = 4_u32
  D3DPS20CAPS_NODEPENDENTREADLIMIT = 8_u32
  D3DPS20CAPS_NOTEXINSTRUCTIONLIMIT = 16_u32
  D3DPS20_MAX_DYNAMICFLOWCONTROLDEPTH = 24_u32
  D3DPS20_MIN_DYNAMICFLOWCONTROLDEPTH = 0_u32
  D3DPS20_MAX_NUMTEMPS = 32_u32
  D3DPS20_MIN_NUMTEMPS = 12_u32
  D3DPS20_MAX_STATICFLOWCONTROLDEPTH = 4_u32
  D3DPS20_MIN_STATICFLOWCONTROLDEPTH = 0_u32
  D3DPS20_MAX_NUMINSTRUCTIONSLOTS = 512_u32
  D3DPS20_MIN_NUMINSTRUCTIONSLOTS = 96_u32
  D3DMIN30SHADERINSTRUCTIONS = 512_u32
  D3DMAX30SHADERINSTRUCTIONS = 32768_u32
  D3DOVERLAYCAPS_FULLRANGERGB = 1_u32
  D3DOVERLAYCAPS_LIMITEDRANGERGB = 2_u32
  D3DOVERLAYCAPS_YCbCr_BT601 = 4_u32
  D3DOVERLAYCAPS_YCbCr_BT709 = 8_u32
  D3DOVERLAYCAPS_YCbCr_BT601_xvYCC = 16_u32
  D3DOVERLAYCAPS_YCbCr_BT709_xvYCC = 32_u32
  D3DOVERLAYCAPS_STRETCHX = 64_u32
  D3DOVERLAYCAPS_STRETCHY = 128_u32
  D3DCPCAPS_SOFTWARE = 1_u32
  D3DCPCAPS_HARDWARE = 2_u32
  D3DCPCAPS_PROTECTIONALWAYSON = 4_u32
  D3DCPCAPS_PARTIALDECRYPTION = 8_u32
  D3DCPCAPS_CONTENTKEY = 16_u32
  D3DCPCAPS_FRESHENSESSIONKEY = 32_u32
  D3DCPCAPS_ENCRYPTEDREADBACK = 64_u32
  D3DCPCAPS_ENCRYPTEDREADBACKKEY = 128_u32
  D3DCPCAPS_SEQUENTIAL_CTR_IV = 256_u32
  D3DCPCAPS_ENCRYPTSLICEDATAONLY = 512_u32
  D3DCRYPTOTYPE_AES128_CTR = "9b6bd711-4f74-41c9-9e7b-0be2d7d93b4f"
  D3DCRYPTOTYPE_PROPRIETARY = "ab4e9afd-1d1c-46e6-a72f-0869917b0de8"
  D3DKEYEXCHANGE_RSAES_OAEP = "c1949895-d72a-4a1d-8e5d-ed857d171520"
  D3DKEYEXCHANGE_DXVA = "43d3775c-38e5-4924-8d86-d3fccf153e9b"
  D3DCAPS_OVERLAY = 2048_i32
  D3DCAPS_READ_SCANLINE = 131072_i32
  D3DCAPS2_FULLSCREENGAMMA = 131072_i32
  D3DCAPS2_CANCALIBRATEGAMMA = 1048576_i32
  D3DCAPS2_RESERVED = 33554432_i32
  D3DCAPS2_CANMANAGERESOURCE = 268435456_i32
  D3DCAPS2_DYNAMICTEXTURES = 536870912_i32
  D3DCAPS2_CANAUTOGENMIPMAP = 1073741824_i32
  D3DCAPS2_CANSHARERESOURCE = -2147483648_i32
  D3DCAPS3_RESERVED = -2147483617_i32
  D3DCAPS3_ALPHA_FULLSCREEN_FLIP_OR_DISCARD = 32_i32
  D3DCAPS3_LINEAR_TO_SRGB_PRESENTATION = 128_i32
  D3DCAPS3_COPY_TO_VIDMEM = 256_i32
  D3DCAPS3_COPY_TO_SYSTEMMEM = 512_i32
  D3DCAPS3_DXVAHD = 1024_i32
  D3DCAPS3_DXVAHD_LIMITED = 2048_i32
  D3DPRESENT_INTERVAL_DEFAULT = 0_i32
  D3DPRESENT_INTERVAL_ONE = 1_i32
  D3DPRESENT_INTERVAL_TWO = 2_i32
  D3DPRESENT_INTERVAL_THREE = 4_i32
  D3DPRESENT_INTERVAL_FOUR = 8_i32
  D3DPRESENT_INTERVAL_IMMEDIATE = -2147483648_i32
  D3DCURSORCAPS_COLOR = 1_i32
  D3DCURSORCAPS_LOWRES = 2_i32
  D3DDEVCAPS_PUREDEVICE = 1048576_i32
  D3DDEVCAPS_QUINTICRTPATCHES = 2097152_i32
  D3DDEVCAPS_RTPATCHES = 4194304_i32
  D3DDEVCAPS_RTPATCHHANDLEZERO = 8388608_i32
  D3DDEVCAPS_NPATCHES = 16777216_i32
  D3DPMISCCAPS_COLORWRITEENABLE = 128_i32
  D3DPMISCCAPS_CLIPPLANESCALEDPOINTS = 256_i32
  D3DPMISCCAPS_CLIPTLVERTS = 512_i32
  D3DPMISCCAPS_TSSARGTEMP = 1024_i32
  D3DPMISCCAPS_BLENDOP = 2048_i32
  D3DPMISCCAPS_NULLREFERENCE = 4096_i32
  D3DPMISCCAPS_INDEPENDENTWRITEMASKS = 16384_i32
  D3DPMISCCAPS_PERSTAGECONSTANT = 32768_i32
  D3DPMISCCAPS_FOGANDSPECULARALPHA = 65536_i32
  D3DPMISCCAPS_SEPARATEALPHABLEND = 131072_i32
  D3DPMISCCAPS_MRTINDEPENDENTBITDEPTHS = 262144_i32
  D3DPMISCCAPS_MRTPOSTPIXELSHADERBLENDING = 524288_i32
  D3DPMISCCAPS_FOGVERTEXCLAMPED = 1048576_i32
  D3DPMISCCAPS_POSTBLENDSRGBCONVERT = 2097152_i32
  D3DLINECAPS_TEXTURE = 1_i32
  D3DLINECAPS_ZTEST = 2_i32
  D3DLINECAPS_BLEND = 4_i32
  D3DLINECAPS_ALPHACMP = 8_i32
  D3DLINECAPS_FOG = 16_i32
  D3DLINECAPS_ANTIALIAS = 32_i32
  D3DPRASTERCAPS_COLORPERSPECTIVE = 4194304_i32
  D3DPRASTERCAPS_SCISSORTEST = 16777216_i32
  D3DPRASTERCAPS_SLOPESCALEDEPTHBIAS = 33554432_i32
  D3DPRASTERCAPS_DEPTHBIAS = 67108864_i32
  D3DPRASTERCAPS_MULTISAMPLE_TOGGLE = 134217728_i32
  D3DPBLENDCAPS_BLENDFACTOR = 8192_i32
  D3DPBLENDCAPS_SRCCOLOR2 = 16384_i32
  D3DPBLENDCAPS_INVSRCCOLOR2 = 32768_i32
  D3DPTEXTURECAPS_VOLUMEMAP = 8192_i32
  D3DPTEXTURECAPS_MIPMAP = 16384_i32
  D3DPTEXTURECAPS_MIPVOLUMEMAP = 32768_i32
  D3DPTEXTURECAPS_MIPCUBEMAP = 65536_i32
  D3DPTEXTURECAPS_CUBEMAP_POW2 = 131072_i32
  D3DPTEXTURECAPS_VOLUMEMAP_POW2 = 262144_i32
  D3DPTEXTURECAPS_NOPROJECTEDBUMPENV = 2097152_i32
  D3DPTFILTERCAPS_MINFPYRAMIDALQUAD = 2048_i32
  D3DPTFILTERCAPS_MINFGAUSSIANQUAD = 4096_i32
  D3DPTFILTERCAPS_CONVOLUTIONMONO = 262144_i32
  D3DPTFILTERCAPS_MAGFPYRAMIDALQUAD = 134217728_i32
  D3DPTFILTERCAPS_MAGFGAUSSIANQUAD = 268435456_i32
  D3DPTADDRESSCAPS_MIRRORONCE = 32_i32
  D3DSTENCILCAPS_TWOSIDED = 256_i32
  D3DTEXOPCAPS_MULTIPLYADD = 16777216_i32
  D3DTEXOPCAPS_LERP = 33554432_i32
  D3DFVFCAPS_PSIZE = 1048576_i32
  D3DVTXPCAPS_TWEENING = 64_i32
  D3DVTXPCAPS_TEXGEN_SPHEREMAP = 256_i32
  D3DVTXPCAPS_NO_TEXGEN_NONLOCALVIEWER = 512_i32
  D3DDEVCAPS2_STREAMOFFSET = 1_i32
  D3DDEVCAPS2_DMAPNPATCH = 2_i32
  D3DDEVCAPS2_ADAPTIVETESSRTPATCH = 4_i32
  D3DDEVCAPS2_ADAPTIVETESSNPATCH = 8_i32
  D3DDEVCAPS2_CAN_STRETCHRECT_FROM_TEXTURES = 16_i32
  D3DDEVCAPS2_PRESAMPLEDDMAPNPATCH = 32_i32
  D3DDEVCAPS2_VERTEXELEMENTSCANSHARESTREAMOFFSET = 64_i32
  D3DDTCAPS_UBYTE4 = 1_i32
  D3DDTCAPS_UBYTE4N = 2_i32
  D3DDTCAPS_SHORT2N = 4_i32
  D3DDTCAPS_SHORT4N = 8_i32
  D3DDTCAPS_USHORT2N = 16_i32
  D3DDTCAPS_USHORT4N = 32_i32
  D3DDTCAPS_UDEC3 = 64_i32
  D3DDTCAPS_DEC3N = 128_i32
  D3DDTCAPS_FLOAT16_2 = 256_i32
  D3DDTCAPS_FLOAT16_4 = 512_i32
  D3DSPD_IUNKNOWN = 1_i32
  D3DCREATE_FPU_PRESERVE = 2_i32
  D3DCREATE_MULTITHREADED = 4_i32
  D3DCREATE_PUREDEVICE = 16_i32
  D3DCREATE_SOFTWARE_VERTEXPROCESSING = 32_i32
  D3DCREATE_HARDWARE_VERTEXPROCESSING = 64_i32
  D3DCREATE_MIXED_VERTEXPROCESSING = 128_i32
  D3DCREATE_DISABLE_DRIVER_MANAGEMENT = 256_i32
  D3DCREATE_ADAPTERGROUP_DEVICE = 512_i32
  D3DADAPTER_DEFAULT = 0_u32
  D3DENUM_NO_DRIVERVERSION = 4_i32
  D3DPRESENT_BACK_BUFFERS_MAX = 3_i32
  D3DSGR_NO_CALIBRATION = 0_i32
  D3DSGR_CALIBRATE = 1_i32
  D3DCURSOR_IMMEDIATE_UPDATE = 1_i32
  D3DPRESENT_DONOTWAIT = 1_i32
  D3DPRESENT_LINEAR_CONTENT = 2_i32
  FACD3D = 2166_u32
  D3D_SDK_VERSION = 32_u32
  D3D9b_SDK_VERSION = 31_u32
  D3DCREATE_DISABLE_DRIVER_MANAGEMENT_EX = 1024_i32
  D3DCREATE_NOWINDOWCHANGES = 2048_i32
  D3DCREATE_DISABLE_PSGP_THREADING = 8192_i32
  D3DCREATE_ENABLE_PRESENTSTATS = 16384_i32
  D3DCREATE_DISABLE_PRINTSCREEN = 32768_i32
  D3DCREATE_SCREENSAVER = 268435456_i32
  D3DENUM_WHQL_LEVEL = 2_i32
  D3DPRESENT_BACK_BUFFERS_MAX_EX = 30_i32
  D3DPRESENT_DONOTFLIP = 4_i32
  D3DPRESENT_FLIPRESTART = 8_i32
  D3DPRESENT_VIDEO_RESTRICT_TO_MONITOR = 16_i32
  D3DPRESENT_UPDATEOVERLAYONLY = 32_i32
  D3DPRESENT_HIDEOVERLAY = 64_i32
  D3DPRESENT_UPDATECOLORKEY = 128_i32
  D3DPRESENT_FORCEIMMEDIATE = 256_i32


  enum D3DLIGHTTYPE : Int32
    D3DLIGHT_POINT = 1
    D3DLIGHT_SPOT = 2
    D3DLIGHT_DIRECTIONAL = 3
    D3DLIGHT_FORCE_DWORD = 2147483647
  end

  enum D3DSHADEMODE : Int32
    D3DSHADE_FLAT = 1
    D3DSHADE_GOURAUD = 2
    D3DSHADE_PHONG = 3
    D3DSHADE_FORCE_DWORD = 2147483647
  end

  enum D3DFILLMODE : Int32
    D3DFILL_POINT = 1
    D3DFILL_WIREFRAME = 2
    D3DFILL_SOLID = 3
    D3DFILL_FORCE_DWORD = 2147483647
  end

  enum D3DBLEND : UInt32
    D3DBLEND_ZERO = 1
    D3DBLEND_ONE = 2
    D3DBLEND_SRCCOLOR = 3
    D3DBLEND_INVSRCCOLOR = 4
    D3DBLEND_SRCALPHA = 5
    D3DBLEND_INVSRCALPHA = 6
    D3DBLEND_DESTALPHA = 7
    D3DBLEND_INVDESTALPHA = 8
    D3DBLEND_DESTCOLOR = 9
    D3DBLEND_INVDESTCOLOR = 10
    D3DBLEND_SRCALPHASAT = 11
    D3DBLEND_BOTHSRCALPHA = 12
    D3DBLEND_BOTHINVSRCALPHA = 13
    D3DBLEND_BLENDFACTOR = 14
    D3DBLEND_INVBLENDFACTOR = 15
    D3DBLEND_SRCCOLOR2 = 16
    D3DBLEND_INVSRCCOLOR2 = 17
    D3DBLEND_FORCE_DWORD = 2147483647
  end

  enum D3DBLENDOP : UInt32
    D3DBLENDOP_ADD = 1
    D3DBLENDOP_SUBTRACT = 2
    D3DBLENDOP_REVSUBTRACT = 3
    D3DBLENDOP_MIN = 4
    D3DBLENDOP_MAX = 5
    D3DBLENDOP_FORCE_DWORD = 2147483647
  end

  enum D3DTEXTUREADDRESS : Int32
    D3DTADDRESS_WRAP = 1
    D3DTADDRESS_MIRROR = 2
    D3DTADDRESS_CLAMP = 3
    D3DTADDRESS_BORDER = 4
    D3DTADDRESS_MIRRORONCE = 5
    D3DTADDRESS_FORCE_DWORD = 2147483647
  end

  enum D3DCULL : UInt32
    D3DCULL_NONE = 1
    D3DCULL_CW = 2
    D3DCULL_CCW = 3
    D3DCULL_FORCE_DWORD = 2147483647
  end

  enum D3DCMPFUNC : Int32
    D3DCMP_NEVER = 1
    D3DCMP_LESS = 2
    D3DCMP_EQUAL = 3
    D3DCMP_LESSEQUAL = 4
    D3DCMP_GREATER = 5
    D3DCMP_NOTEQUAL = 6
    D3DCMP_GREATEREQUAL = 7
    D3DCMP_ALWAYS = 8
    D3DCMP_FORCE_DWORD = 2147483647
  end

  enum D3DSTENCILOP : UInt32
    D3DSTENCILOP_KEEP = 1
    D3DSTENCILOP_ZERO = 2
    D3DSTENCILOP_REPLACE = 3
    D3DSTENCILOP_INCRSAT = 4
    D3DSTENCILOP_DECRSAT = 5
    D3DSTENCILOP_INVERT = 6
    D3DSTENCILOP_INCR = 7
    D3DSTENCILOP_DECR = 8
    D3DSTENCILOP_FORCE_DWORD = 2147483647
  end

  enum D3DFOGMODE : Int32
    D3DFOG_NONE = 0
    D3DFOG_EXP = 1
    D3DFOG_EXP2 = 2
    D3DFOG_LINEAR = 3
    D3DFOG_FORCE_DWORD = 2147483647
  end

  enum D3DZBUFFERTYPE : Int32
    D3DZB_FALSE = 0
    D3DZB_TRUE = 1
    D3DZB_USEW = 2
    D3DZB_FORCE_DWORD = 2147483647
  end

  enum D3DPRIMITIVETYPE : Int32
    D3DPT_POINTLIST = 1
    D3DPT_LINELIST = 2
    D3DPT_LINESTRIP = 3
    D3DPT_TRIANGLELIST = 4
    D3DPT_TRIANGLESTRIP = 5
    D3DPT_TRIANGLEFAN = 6
    D3DPT_FORCE_DWORD = 2147483647
  end

  enum D3DTRANSFORMSTATETYPE : Int32
    D3DTS_VIEW = 2
    D3DTS_PROJECTION = 3
    D3DTS_TEXTURE0 = 16
    D3DTS_TEXTURE1 = 17
    D3DTS_TEXTURE2 = 18
    D3DTS_TEXTURE3 = 19
    D3DTS_TEXTURE4 = 20
    D3DTS_TEXTURE5 = 21
    D3DTS_TEXTURE6 = 22
    D3DTS_TEXTURE7 = 23
    D3DTS_FORCE_DWORD = 2147483647
  end

  enum D3DRENDERSTATETYPE : Int32
    D3DRS_ZENABLE = 7
    D3DRS_FILLMODE = 8
    D3DRS_SHADEMODE = 9
    D3DRS_ZWRITEENABLE = 14
    D3DRS_ALPHATESTENABLE = 15
    D3DRS_LASTPIXEL = 16
    D3DRS_SRCBLEND = 19
    D3DRS_DESTBLEND = 20
    D3DRS_CULLMODE = 22
    D3DRS_ZFUNC = 23
    D3DRS_ALPHAREF = 24
    D3DRS_ALPHAFUNC = 25
    D3DRS_DITHERENABLE = 26
    D3DRS_ALPHABLENDENABLE = 27
    D3DRS_FOGENABLE = 28
    D3DRS_SPECULARENABLE = 29
    D3DRS_FOGCOLOR = 34
    D3DRS_FOGTABLEMODE = 35
    D3DRS_FOGSTART = 36
    D3DRS_FOGEND = 37
    D3DRS_FOGDENSITY = 38
    D3DRS_RANGEFOGENABLE = 48
    D3DRS_STENCILENABLE = 52
    D3DRS_STENCILFAIL = 53
    D3DRS_STENCILZFAIL = 54
    D3DRS_STENCILPASS = 55
    D3DRS_STENCILFUNC = 56
    D3DRS_STENCILREF = 57
    D3DRS_STENCILMASK = 58
    D3DRS_STENCILWRITEMASK = 59
    D3DRS_TEXTUREFACTOR = 60
    D3DRS_WRAP0 = 128
    D3DRS_WRAP1 = 129
    D3DRS_WRAP2 = 130
    D3DRS_WRAP3 = 131
    D3DRS_WRAP4 = 132
    D3DRS_WRAP5 = 133
    D3DRS_WRAP6 = 134
    D3DRS_WRAP7 = 135
    D3DRS_CLIPPING = 136
    D3DRS_LIGHTING = 137
    D3DRS_AMBIENT = 139
    D3DRS_FOGVERTEXMODE = 140
    D3DRS_COLORVERTEX = 141
    D3DRS_LOCALVIEWER = 142
    D3DRS_NORMALIZENORMALS = 143
    D3DRS_DIFFUSEMATERIALSOURCE = 145
    D3DRS_SPECULARMATERIALSOURCE = 146
    D3DRS_AMBIENTMATERIALSOURCE = 147
    D3DRS_EMISSIVEMATERIALSOURCE = 148
    D3DRS_VERTEXBLEND = 151
    D3DRS_CLIPPLANEENABLE = 152
    D3DRS_POINTSIZE = 154
    D3DRS_POINTSIZE_MIN = 155
    D3DRS_POINTSPRITEENABLE = 156
    D3DRS_POINTSCALEENABLE = 157
    D3DRS_POINTSCALE_A = 158
    D3DRS_POINTSCALE_B = 159
    D3DRS_POINTSCALE_C = 160
    D3DRS_MULTISAMPLEANTIALIAS = 161
    D3DRS_MULTISAMPLEMASK = 162
    D3DRS_PATCHEDGESTYLE = 163
    D3DRS_DEBUGMONITORTOKEN = 165
    D3DRS_POINTSIZE_MAX = 166
    D3DRS_INDEXEDVERTEXBLENDENABLE = 167
    D3DRS_COLORWRITEENABLE = 168
    D3DRS_TWEENFACTOR = 170
    D3DRS_BLENDOP = 171
    D3DRS_POSITIONDEGREE = 172
    D3DRS_NORMALDEGREE = 173
    D3DRS_SCISSORTESTENABLE = 174
    D3DRS_SLOPESCALEDEPTHBIAS = 175
    D3DRS_ANTIALIASEDLINEENABLE = 176
    D3DRS_MINTESSELLATIONLEVEL = 178
    D3DRS_MAXTESSELLATIONLEVEL = 179
    D3DRS_ADAPTIVETESS_X = 180
    D3DRS_ADAPTIVETESS_Y = 181
    D3DRS_ADAPTIVETESS_Z = 182
    D3DRS_ADAPTIVETESS_W = 183
    D3DRS_ENABLEADAPTIVETESSELLATION = 184
    D3DRS_TWOSIDEDSTENCILMODE = 185
    D3DRS_CCW_STENCILFAIL = 186
    D3DRS_CCW_STENCILZFAIL = 187
    D3DRS_CCW_STENCILPASS = 188
    D3DRS_CCW_STENCILFUNC = 189
    D3DRS_COLORWRITEENABLE1 = 190
    D3DRS_COLORWRITEENABLE2 = 191
    D3DRS_COLORWRITEENABLE3 = 192
    D3DRS_BLENDFACTOR = 193
    D3DRS_SRGBWRITEENABLE = 194
    D3DRS_DEPTHBIAS = 195
    D3DRS_WRAP8 = 198
    D3DRS_WRAP9 = 199
    D3DRS_WRAP10 = 200
    D3DRS_WRAP11 = 201
    D3DRS_WRAP12 = 202
    D3DRS_WRAP13 = 203
    D3DRS_WRAP14 = 204
    D3DRS_WRAP15 = 205
    D3DRS_SEPARATEALPHABLENDENABLE = 206
    D3DRS_SRCBLENDALPHA = 207
    D3DRS_DESTBLENDALPHA = 208
    D3DRS_BLENDOPALPHA = 209
    D3DRS_FORCE_DWORD = 2147483647
  end

  enum D3DMATERIALCOLORSOURCE : Int32
    D3DMCS_MATERIAL = 0
    D3DMCS_COLOR1 = 1
    D3DMCS_COLOR2 = 2
    D3DMCS_FORCE_DWORD = 2147483647
  end

  enum D3DTEXTURESTAGESTATETYPE : Int32
    D3DTSS_COLOROP = 1
    D3DTSS_COLORARG1 = 2
    D3DTSS_COLORARG2 = 3
    D3DTSS_ALPHAOP = 4
    D3DTSS_ALPHAARG1 = 5
    D3DTSS_ALPHAARG2 = 6
    D3DTSS_BUMPENVMAT00 = 7
    D3DTSS_BUMPENVMAT01 = 8
    D3DTSS_BUMPENVMAT10 = 9
    D3DTSS_BUMPENVMAT11 = 10
    D3DTSS_TEXCOORDINDEX = 11
    D3DTSS_BUMPENVLSCALE = 22
    D3DTSS_BUMPENVLOFFSET = 23
    D3DTSS_TEXTURETRANSFORMFLAGS = 24
    D3DTSS_COLORARG0 = 26
    D3DTSS_ALPHAARG0 = 27
    D3DTSS_RESULTARG = 28
    D3DTSS_CONSTANT = 32
    D3DTSS_FORCE_DWORD = 2147483647
  end

  enum D3DSAMPLERSTATETYPE : Int32
    D3DSAMP_ADDRESSU = 1
    D3DSAMP_ADDRESSV = 2
    D3DSAMP_ADDRESSW = 3
    D3DSAMP_BORDERCOLOR = 4
    D3DSAMP_MAGFILTER = 5
    D3DSAMP_MINFILTER = 6
    D3DSAMP_MIPFILTER = 7
    D3DSAMP_MIPMAPLODBIAS = 8
    D3DSAMP_MAXMIPLEVEL = 9
    D3DSAMP_MAXANISOTROPY = 10
    D3DSAMP_SRGBTEXTURE = 11
    D3DSAMP_ELEMENTINDEX = 12
    D3DSAMP_DMAPOFFSET = 13
    D3DSAMP_FORCE_DWORD = 2147483647
  end

  enum D3DTEXTUREOP : Int32
    D3DTOP_DISABLE = 1
    D3DTOP_SELECTARG1 = 2
    D3DTOP_SELECTARG2 = 3
    D3DTOP_MODULATE = 4
    D3DTOP_MODULATE2X = 5
    D3DTOP_MODULATE4X = 6
    D3DTOP_ADD = 7
    D3DTOP_ADDSIGNED = 8
    D3DTOP_ADDSIGNED2X = 9
    D3DTOP_SUBTRACT = 10
    D3DTOP_ADDSMOOTH = 11
    D3DTOP_BLENDDIFFUSEALPHA = 12
    D3DTOP_BLENDTEXTUREALPHA = 13
    D3DTOP_BLENDFACTORALPHA = 14
    D3DTOP_BLENDTEXTUREALPHAPM = 15
    D3DTOP_BLENDCURRENTALPHA = 16
    D3DTOP_PREMODULATE = 17
    D3DTOP_MODULATEALPHA_ADDCOLOR = 18
    D3DTOP_MODULATECOLOR_ADDALPHA = 19
    D3DTOP_MODULATEINVALPHA_ADDCOLOR = 20
    D3DTOP_MODULATEINVCOLOR_ADDALPHA = 21
    D3DTOP_BUMPENVMAP = 22
    D3DTOP_BUMPENVMAPLUMINANCE = 23
    D3DTOP_DOTPRODUCT3 = 24
    D3DTOP_MULTIPLYADD = 25
    D3DTOP_LERP = 26
    D3DTOP_FORCE_DWORD = 2147483647
  end

  enum D3DTEXTUREFILTERTYPE : Int32
    D3DTEXF_NONE = 0
    D3DTEXF_POINT = 1
    D3DTEXF_LINEAR = 2
    D3DTEXF_ANISOTROPIC = 3
    D3DTEXF_PYRAMIDALQUAD = 6
    D3DTEXF_GAUSSIANQUAD = 7
    D3DTEXF_CONVOLUTIONMONO = 8
    D3DTEXF_FORCE_DWORD = 2147483647
  end

  enum D3DDECLUSAGE : Int32
    D3DDECLUSAGE_POSITION = 0
    D3DDECLUSAGE_BLENDWEIGHT = 1
    D3DDECLUSAGE_BLENDINDICES = 2
    D3DDECLUSAGE_NORMAL = 3
    D3DDECLUSAGE_PSIZE = 4
    D3DDECLUSAGE_TEXCOORD = 5
    D3DDECLUSAGE_TANGENT = 6
    D3DDECLUSAGE_BINORMAL = 7
    D3DDECLUSAGE_TESSFACTOR = 8
    D3DDECLUSAGE_POSITIONT = 9
    D3DDECLUSAGE_COLOR = 10
    D3DDECLUSAGE_FOG = 11
    D3DDECLUSAGE_DEPTH = 12
    D3DDECLUSAGE_SAMPLE = 13
  end

  enum D3DDECLMETHOD : Int32
    D3DDECLMETHOD_DEFAULT = 0
    D3DDECLMETHOD_PARTIALU = 1
    D3DDECLMETHOD_PARTIALV = 2
    D3DDECLMETHOD_CROSSUV = 3
    D3DDECLMETHOD_UV = 4
    D3DDECLMETHOD_LOOKUP = 5
    D3DDECLMETHOD_LOOKUPPRESAMPLED = 6
  end

  enum D3DDECLTYPE : Int32
    D3DDECLTYPE_FLOAT1 = 0
    D3DDECLTYPE_FLOAT2 = 1
    D3DDECLTYPE_FLOAT3 = 2
    D3DDECLTYPE_FLOAT4 = 3
    D3DDECLTYPE_D3DCOLOR = 4
    D3DDECLTYPE_UBYTE4 = 5
    D3DDECLTYPE_SHORT2 = 6
    D3DDECLTYPE_SHORT4 = 7
    D3DDECLTYPE_UBYTE4N = 8
    D3DDECLTYPE_SHORT2N = 9
    D3DDECLTYPE_SHORT4N = 10
    D3DDECLTYPE_USHORT2N = 11
    D3DDECLTYPE_USHORT4N = 12
    D3DDECLTYPE_UDEC3 = 13
    D3DDECLTYPE_DEC3N = 14
    D3DDECLTYPE_FLOAT16_2 = 15
    D3DDECLTYPE_FLOAT16_4 = 16
    D3DDECLTYPE_UNUSED = 17
  end

  enum D3DSHADER_INSTRUCTION_OPCODE_TYPE : Int32
    D3DSIO_NOP = 0
    D3DSIO_MOV = 1
    D3DSIO_ADD = 2
    D3DSIO_SUB = 3
    D3DSIO_MAD = 4
    D3DSIO_MUL = 5
    D3DSIO_RCP = 6
    D3DSIO_RSQ = 7
    D3DSIO_DP3 = 8
    D3DSIO_DP4 = 9
    D3DSIO_MIN = 10
    D3DSIO_MAX = 11
    D3DSIO_SLT = 12
    D3DSIO_SGE = 13
    D3DSIO_EXP = 14
    D3DSIO_LOG = 15
    D3DSIO_LIT = 16
    D3DSIO_DST = 17
    D3DSIO_LRP = 18
    D3DSIO_FRC = 19
    D3DSIO_M4x4 = 20
    D3DSIO_M4x3 = 21
    D3DSIO_M3x4 = 22
    D3DSIO_M3x3 = 23
    D3DSIO_M3x2 = 24
    D3DSIO_CALL = 25
    D3DSIO_CALLNZ = 26
    D3DSIO_LOOP = 27
    D3DSIO_RET = 28
    D3DSIO_ENDLOOP = 29
    D3DSIO_LABEL = 30
    D3DSIO_DCL = 31
    D3DSIO_POW = 32
    D3DSIO_CRS = 33
    D3DSIO_SGN = 34
    D3DSIO_ABS = 35
    D3DSIO_NRM = 36
    D3DSIO_SINCOS = 37
    D3DSIO_REP = 38
    D3DSIO_ENDREP = 39
    D3DSIO_IF = 40
    D3DSIO_IFC = 41
    D3DSIO_ELSE = 42
    D3DSIO_ENDIF = 43
    D3DSIO_BREAK = 44
    D3DSIO_BREAKC = 45
    D3DSIO_MOVA = 46
    D3DSIO_DEFB = 47
    D3DSIO_DEFI = 48
    D3DSIO_TEXCOORD = 64
    D3DSIO_TEXKILL = 65
    D3DSIO_TEX = 66
    D3DSIO_TEXBEM = 67
    D3DSIO_TEXBEML = 68
    D3DSIO_TEXREG2AR = 69
    D3DSIO_TEXREG2GB = 70
    D3DSIO_TEXM3x2PAD = 71
    D3DSIO_TEXM3x2TEX = 72
    D3DSIO_TEXM3x3PAD = 73
    D3DSIO_TEXM3x3TEX = 74
    D3DSIO_RESERVED0 = 75
    D3DSIO_TEXM3x3SPEC = 76
    D3DSIO_TEXM3x3VSPEC = 77
    D3DSIO_EXPP = 78
    D3DSIO_LOGP = 79
    D3DSIO_CND = 80
    D3DSIO_DEF = 81
    D3DSIO_TEXREG2RGB = 82
    D3DSIO_TEXDP3TEX = 83
    D3DSIO_TEXM3x2DEPTH = 84
    D3DSIO_TEXDP3 = 85
    D3DSIO_TEXM3x3 = 86
    D3DSIO_TEXDEPTH = 87
    D3DSIO_CMP = 88
    D3DSIO_BEM = 89
    D3DSIO_DP2ADD = 90
    D3DSIO_DSX = 91
    D3DSIO_DSY = 92
    D3DSIO_TEXLDD = 93
    D3DSIO_SETP = 94
    D3DSIO_TEXLDL = 95
    D3DSIO_BREAKP = 96
    D3DSIO_PHASE = 65533
    D3DSIO_COMMENT = 65534
    D3DSIO_END = 65535
    D3DSIO_FORCE_DWORD = 2147483647
  end

  enum D3DSHADER_COMPARISON : Int32
    D3DSPC_RESERVED0 = 0
    D3DSPC_GT = 1
    D3DSPC_EQ = 2
    D3DSPC_GE = 3
    D3DSPC_LT = 4
    D3DSPC_NE = 5
    D3DSPC_LE = 6
    D3DSPC_RESERVED1 = 7
  end

  enum D3DSAMPLER_TEXTURE_TYPE : Int32
    D3DSTT_UNKNOWN = 0
    D3DSTT_2D = 268435456
    D3DSTT_CUBE = 402653184
    D3DSTT_VOLUME = 536870912
    D3DSTT_FORCE_DWORD = 2147483647
  end

  enum D3DSHADER_PARAM_REGISTER_TYPE : Int32
    D3DSPR_TEMP = 0
    D3DSPR_INPUT = 1
    D3DSPR_CONST = 2
    D3DSPR_ADDR = 3
    D3DSPR_TEXTURE = 3
    D3DSPR_RASTOUT = 4
    D3DSPR_ATTROUT = 5
    D3DSPR_TEXCRDOUT = 6
    D3DSPR_OUTPUT = 6
    D3DSPR_CONSTINT = 7
    D3DSPR_COLOROUT = 8
    D3DSPR_DEPTHOUT = 9
    D3DSPR_SAMPLER = 10
    D3DSPR_CONST2 = 11
    D3DSPR_CONST3 = 12
    D3DSPR_CONST4 = 13
    D3DSPR_CONSTBOOL = 14
    D3DSPR_LOOP = 15
    D3DSPR_TEMPFLOAT16 = 16
    D3DSPR_MISCTYPE = 17
    D3DSPR_LABEL = 18
    D3DSPR_PREDICATE = 19
    D3DSPR_FORCE_DWORD = 2147483647
  end

  enum D3DSHADER_MISCTYPE_OFFSETS : Int32
    D3DSMO_POSITION = 0
    D3DSMO_FACE = 1
  end

  enum D3DVS_RASTOUT_OFFSETS : Int32
    D3DSRO_POSITION = 0
    D3DSRO_FOG = 1
    D3DSRO_POINT_SIZE = 2
    D3DSRO_FORCE_DWORD = 2147483647
  end

  enum D3DVS_ADDRESSMODE_TYPE : Int32
    D3DVS_ADDRMODE_ABSOLUTE = 0
    D3DVS_ADDRMODE_RELATIVE = 8192
    D3DVS_ADDRMODE_FORCE_DWORD = 2147483647
  end

  enum D3DSHADER_ADDRESSMODE_TYPE : Int32
    D3DSHADER_ADDRMODE_ABSOLUTE = 0
    D3DSHADER_ADDRMODE_RELATIVE = 8192
    D3DSHADER_ADDRMODE_FORCE_DWORD = 2147483647
  end

  enum D3DSHADER_PARAM_SRCMOD_TYPE : Int32
    D3DSPSM_NONE = 0
    D3DSPSM_NEG = 16777216
    D3DSPSM_BIAS = 33554432
    D3DSPSM_BIASNEG = 50331648
    D3DSPSM_SIGN = 67108864
    D3DSPSM_SIGNNEG = 83886080
    D3DSPSM_COMP = 100663296
    D3DSPSM_X2 = 117440512
    D3DSPSM_X2NEG = 134217728
    D3DSPSM_DZ = 150994944
    D3DSPSM_DW = 167772160
    D3DSPSM_ABS = 184549376
    D3DSPSM_ABSNEG = 201326592
    D3DSPSM_NOT = 218103808
    D3DSPSM_FORCE_DWORD = 2147483647
  end

  enum D3DSHADER_MIN_PRECISION : Int32
    D3DMP_DEFAULT = 0
    D3DMP_16 = 1
    D3DMP_2_8 = 2
  end

  enum D3DBASISTYPE : Int32
    D3DBASIS_BEZIER = 0
    D3DBASIS_BSPLINE = 1
    D3DBASIS_CATMULL_ROM = 2
    D3DBASIS_FORCE_DWORD = 2147483647
  end

  enum D3DDEGREETYPE : Int32
    D3DDEGREE_LINEAR = 1
    D3DDEGREE_QUADRATIC = 2
    D3DDEGREE_CUBIC = 3
    D3DDEGREE_QUINTIC = 5
    D3DDEGREE_FORCE_DWORD = 2147483647
  end

  enum D3DPATCHEDGESTYLE : Int32
    D3DPATCHEDGE_DISCRETE = 0
    D3DPATCHEDGE_CONTINUOUS = 1
    D3DPATCHEDGE_FORCE_DWORD = 2147483647
  end

  enum D3DSTATEBLOCKTYPE : Int32
    D3DSBT_ALL = 1
    D3DSBT_PIXELSTATE = 2
    D3DSBT_VERTEXSTATE = 3
    D3DSBT_FORCE_DWORD = 2147483647
  end

  enum D3DVERTEXBLENDFLAGS : Int32
    D3DVBF_DISABLE = 0
    D3DVBF_1WEIGHTS = 1
    D3DVBF_2WEIGHTS = 2
    D3DVBF_3WEIGHTS = 3
    D3DVBF_TWEENING = 255
    D3DVBF_0WEIGHTS = 256
    D3DVBF_FORCE_DWORD = 2147483647
  end

  enum D3DTEXTURETRANSFORMFLAGS : Int32
    D3DTTFF_DISABLE = 0
    D3DTTFF_COUNT1 = 1
    D3DTTFF_COUNT2 = 2
    D3DTTFF_COUNT3 = 3
    D3DTTFF_COUNT4 = 4
    D3DTTFF_PROJECTED = 256
    D3DTTFF_FORCE_DWORD = 2147483647
  end

  enum D3DDEVTYPE : UInt32
    D3DDEVTYPE_HAL = 1
    D3DDEVTYPE_REF = 2
    D3DDEVTYPE_SW = 3
    D3DDEVTYPE_NULLREF = 4
    D3DDEVTYPE_FORCE_DWORD = 2147483647
  end

  enum D3DMULTISAMPLE_TYPE : Int32
    D3DMULTISAMPLE_NONE = 0
    D3DMULTISAMPLE_NONMASKABLE = 1
    D3DMULTISAMPLE_2_SAMPLES = 2
    D3DMULTISAMPLE_3_SAMPLES = 3
    D3DMULTISAMPLE_4_SAMPLES = 4
    D3DMULTISAMPLE_5_SAMPLES = 5
    D3DMULTISAMPLE_6_SAMPLES = 6
    D3DMULTISAMPLE_7_SAMPLES = 7
    D3DMULTISAMPLE_8_SAMPLES = 8
    D3DMULTISAMPLE_9_SAMPLES = 9
    D3DMULTISAMPLE_10_SAMPLES = 10
    D3DMULTISAMPLE_11_SAMPLES = 11
    D3DMULTISAMPLE_12_SAMPLES = 12
    D3DMULTISAMPLE_13_SAMPLES = 13
    D3DMULTISAMPLE_14_SAMPLES = 14
    D3DMULTISAMPLE_15_SAMPLES = 15
    D3DMULTISAMPLE_16_SAMPLES = 16
    D3DMULTISAMPLE_FORCE_DWORD = 2147483647
  end

  enum D3DFORMAT : UInt32
    D3DFMT_UNKNOWN = 0
    D3DFMT_R8G8B8 = 20
    D3DFMT_A8R8G8B8 = 21
    D3DFMT_X8R8G8B8 = 22
    D3DFMT_R5G6B5 = 23
    D3DFMT_X1R5G5B5 = 24
    D3DFMT_A1R5G5B5 = 25
    D3DFMT_A4R4G4B4 = 26
    D3DFMT_R3G3B2 = 27
    D3DFMT_A8 = 28
    D3DFMT_A8R3G3B2 = 29
    D3DFMT_X4R4G4B4 = 30
    D3DFMT_A2B10G10R10 = 31
    D3DFMT_A8B8G8R8 = 32
    D3DFMT_X8B8G8R8 = 33
    D3DFMT_G16R16 = 34
    D3DFMT_A2R10G10B10 = 35
    D3DFMT_A16B16G16R16 = 36
    D3DFMT_A8P8 = 40
    D3DFMT_P8 = 41
    D3DFMT_L8 = 50
    D3DFMT_A8L8 = 51
    D3DFMT_A4L4 = 52
    D3DFMT_V8U8 = 60
    D3DFMT_L6V5U5 = 61
    D3DFMT_X8L8V8U8 = 62
    D3DFMT_Q8W8V8U8 = 63
    D3DFMT_V16U16 = 64
    D3DFMT_A2W10V10U10 = 67
    D3DFMT_UYVY = 1498831189
    D3DFMT_R8G8_B8G8 = 1195525970
    D3DFMT_YUY2 = 844715353
    D3DFMT_G8R8_G8B8 = 1111970375
    D3DFMT_DXT1 = 827611204
    D3DFMT_DXT2 = 844388420
    D3DFMT_DXT3 = 861165636
    D3DFMT_DXT4 = 877942852
    D3DFMT_DXT5 = 894720068
    D3DFMT_D16_LOCKABLE = 70
    D3DFMT_D32 = 71
    D3DFMT_D15S1 = 73
    D3DFMT_D24S8 = 75
    D3DFMT_D24X8 = 77
    D3DFMT_D24X4S4 = 79
    D3DFMT_D16 = 80
    D3DFMT_D32F_LOCKABLE = 82
    D3DFMT_D24FS8 = 83
    D3DFMT_D32_LOCKABLE = 84
    D3DFMT_S8_LOCKABLE = 85
    D3DFMT_L16 = 81
    D3DFMT_VERTEXDATA = 100
    D3DFMT_INDEX16 = 101
    D3DFMT_INDEX32 = 102
    D3DFMT_Q16W16V16U16 = 110
    D3DFMT_MULTI2_ARGB8 = 827606349
    D3DFMT_R16F = 111
    D3DFMT_G16R16F = 112
    D3DFMT_A16B16G16R16F = 113
    D3DFMT_R32F = 114
    D3DFMT_G32R32F = 115
    D3DFMT_A32B32G32R32F = 116
    D3DFMT_CxV8U8 = 117
    D3DFMT_A1 = 118
    D3DFMT_A2B10G10R10_XR_BIAS = 119
    D3DFMT_BINARYBUFFER = 199
    D3DFMT_FORCE_DWORD = 2147483647
  end

  enum D3DSWAPEFFECT : UInt32
    D3DSWAPEFFECT_DISCARD = 1
    D3DSWAPEFFECT_FLIP = 2
    D3DSWAPEFFECT_COPY = 3
    D3DSWAPEFFECT_OVERLAY = 4
    D3DSWAPEFFECT_FLIPEX = 5
    D3DSWAPEFFECT_FORCE_DWORD = 2147483647
  end

  enum D3DPOOL : UInt32
    D3DPOOL_DEFAULT = 0
    D3DPOOL_MANAGED = 1
    D3DPOOL_SYSTEMMEM = 2
    D3DPOOL_SCRATCH = 3
    D3DPOOL_FORCE_DWORD = 2147483647
  end

  enum D3DBACKBUFFER_TYPE : UInt32
    D3DBACKBUFFER_TYPE_MONO = 0
    D3DBACKBUFFER_TYPE_LEFT = 1
    D3DBACKBUFFER_TYPE_RIGHT = 2
    D3DBACKBUFFER_TYPE_FORCE_DWORD = 2147483647
  end

  enum D3DRESOURCETYPE : Int32
    D3DRTYPE_SURFACE = 1
    D3DRTYPE_VOLUME = 2
    D3DRTYPE_TEXTURE = 3
    D3DRTYPE_VOLUMETEXTURE = 4
    D3DRTYPE_CUBETEXTURE = 5
    D3DRTYPE_VERTEXBUFFER = 6
    D3DRTYPE_INDEXBUFFER = 7
    D3DRTYPE_FORCE_DWORD = 2147483647
  end

  enum D3DCUBEMAP_FACES : Int32
    D3DCUBEMAP_FACE_POSITIVE_X = 0
    D3DCUBEMAP_FACE_NEGATIVE_X = 1
    D3DCUBEMAP_FACE_POSITIVE_Y = 2
    D3DCUBEMAP_FACE_NEGATIVE_Y = 3
    D3DCUBEMAP_FACE_POSITIVE_Z = 4
    D3DCUBEMAP_FACE_NEGATIVE_Z = 5
    D3DCUBEMAP_FACE_FORCE_DWORD = 2147483647
  end

  enum D3DDEBUGMONITORTOKENS : Int32
    D3DDMT_ENABLE = 0
    D3DDMT_DISABLE = 1
    D3DDMT_FORCE_DWORD = 2147483647
  end

  enum D3DQUERYTYPE : Int32
    D3DQUERYTYPE_VCACHE = 4
    D3DQUERYTYPE_RESOURCEMANAGER = 5
    D3DQUERYTYPE_VERTEXSTATS = 6
    D3DQUERYTYPE_EVENT = 8
    D3DQUERYTYPE_OCCLUSION = 9
    D3DQUERYTYPE_TIMESTAMP = 10
    D3DQUERYTYPE_TIMESTAMPDISJOINT = 11
    D3DQUERYTYPE_TIMESTAMPFREQ = 12
    D3DQUERYTYPE_PIPELINETIMINGS = 13
    D3DQUERYTYPE_INTERFACETIMINGS = 14
    D3DQUERYTYPE_VERTEXTIMINGS = 15
    D3DQUERYTYPE_PIXELTIMINGS = 16
    D3DQUERYTYPE_BANDWIDTHTIMINGS = 17
    D3DQUERYTYPE_CACHEUTILIZATION = 18
    D3DQUERYTYPE_MEMORYPRESSURE = 19
  end

  enum D3DCOMPOSERECTSOP : Int32
    D3DCOMPOSERECTS_COPY = 1
    D3DCOMPOSERECTS_OR = 2
    D3DCOMPOSERECTS_AND = 3
    D3DCOMPOSERECTS_NEG = 4
    D3DCOMPOSERECTS_FORCE_DWORD = 2147483647
  end

  enum D3DSCANLINEORDERING : Int32
    D3DSCANLINEORDERING_UNKNOWN = 0
    D3DSCANLINEORDERING_PROGRESSIVE = 1
    D3DSCANLINEORDERING_INTERLACED = 2
  end

  enum D3DDISPLAYROTATION : Int32
    D3DDISPLAYROTATION_IDENTITY = 1
    D3DDISPLAYROTATION_90 = 2
    D3DDISPLAYROTATION_180 = 3
    D3DDISPLAYROTATION_270 = 4
  end

  enum D3DAUTHENTICATEDCHANNELTYPE : Int32
    D3DAUTHENTICATEDCHANNEL_D3D9 = 1
    D3DAUTHENTICATEDCHANNEL_DRIVER_SOFTWARE = 2
    D3DAUTHENTICATEDCHANNEL_DRIVER_HARDWARE = 3
  end

  enum D3DAUTHENTICATEDCHANNEL_PROCESSIDENTIFIERTYPE : Int32
    PROCESSIDTYPE_UNKNOWN = 0
    PROCESSIDTYPE_DWM = 1
    PROCESSIDTYPE_HANDLE = 2
  end

  enum D3DBUSTYPE : Int32
    D3DBUSTYPE_OTHER = 0
    D3DBUSTYPE_PCI = 1
    D3DBUSTYPE_PCIX = 2
    D3DBUSTYPE_PCIEXPRESS = 3
    D3DBUSTYPE_AGP = 4
    D3DBUSIMPL_MODIFIER_INSIDE_OF_CHIPSET = 65536
    D3DBUSIMPL_MODIFIER_TRACKS_ON_MOTHER_BOARD_TO_CHIP = 131072
    D3DBUSIMPL_MODIFIER_TRACKS_ON_MOTHER_BOARD_TO_SOCKET = 196608
    D3DBUSIMPL_MODIFIER_DAUGHTER_BOARD_CONNECTOR = 262144
    D3DBUSIMPL_MODIFIER_DAUGHTER_BOARD_CONNECTOR_INSIDE_OF_NUAE = 327680
    D3DBUSIMPL_MODIFIER_NON_STANDARD = -2147483648
  end

union D3DAUTHENTICATEDCHANNEL_PROTECTION_FLAGS_Anonymous_e__Union
  anonymous : D3DAUTHENTICATEDCHANNEL_PROTECTION_FLAGS_Anonymous_e__Union_Anonymous_e__Struct
  value : UInt32
end

  struct D3DCOLORVALUE
    r : Float32
    g : Float32
    b : Float32
    a : Float32
  end
  struct D3DRECT
    x1 : Int32
    y1 : Int32
    x2 : Int32
    y2 : Int32
  end
  struct D3DVIEWPORT9
    x : UInt32
    y : UInt32
    width : UInt32
    height : UInt32
    min_z : Float32
    max_z : Float32
  end
  struct D3DCLIPSTATUS9
    clip_union : UInt32
    clip_intersection : UInt32
  end
  struct D3DMATERIAL9
    diffuse : D3DCOLORVALUE
    ambient : D3DCOLORVALUE
    specular : D3DCOLORVALUE
    emissive : D3DCOLORVALUE
    power : Float32
  end
  struct D3DLIGHT9
    type : D3DLIGHTTYPE
    diffuse : D3DCOLORVALUE
    specular : D3DCOLORVALUE
    ambient : D3DCOLORVALUE
    position : D3DVECTOR
    direction : D3DVECTOR
    range : Float32
    falloff : Float32
    attenuation0 : Float32
    attenuation1 : Float32
    attenuation2 : Float32
    theta : Float32
    phi : Float32
  end
  struct D3DVERTEXELEMENT9
    stream : UInt16
    offset : UInt16
    type : UInt8
    method : UInt8
    usage : UInt8
    usage_index : UInt8
  end
  struct D3DDISPLAYMODE
    width : UInt32
    height : UInt32
    refresh_rate : UInt32
    format : D3DFORMAT
  end
  struct D3DDEVICE_CREATION_PARAMETERS
    adapter_ordinal : UInt32
    device_type : D3DDEVTYPE
    h_focus_window : HANDLE
    behavior_flags : UInt32
  end
  struct D3DPRESENT_PARAMETERS
    back_buffer_width : UInt32
    back_buffer_height : UInt32
    back_buffer_format : D3DFORMAT
    back_buffer_count : UInt32
    multi_sample_type : D3DMULTISAMPLE_TYPE
    multi_sample_quality : UInt32
    swap_effect : D3DSWAPEFFECT
    h_device_window : HANDLE
    windowed : LibC::BOOL
    enable_auto_depth_stencil : LibC::BOOL
    auto_depth_stencil_format : D3DFORMAT
    flags : UInt32
    full_screen_refresh_rate_in_hz : UInt32
    presentation_interval : UInt32
  end
  struct D3DGAMMARAMP
    red : UInt16[256]*
    green : UInt16[256]*
    blue : UInt16[256]*
  end
  struct D3DVERTEXBUFFER_DESC
    format : D3DFORMAT
    type : D3DRESOURCETYPE
    usage : UInt32
    pool : D3DPOOL
    size : UInt32
    fvf : UInt32
  end
  struct D3DINDEXBUFFER_DESC
    format : D3DFORMAT
    type : D3DRESOURCETYPE
    usage : UInt32
    pool : D3DPOOL
    size : UInt32
  end
  struct D3DSURFACE_DESC
    format : D3DFORMAT
    type : D3DRESOURCETYPE
    usage : UInt32
    pool : D3DPOOL
    multi_sample_type : D3DMULTISAMPLE_TYPE
    multi_sample_quality : UInt32
    width : UInt32
    height : UInt32
  end
  struct D3DVOLUME_DESC
    format : D3DFORMAT
    type : D3DRESOURCETYPE
    usage : UInt32
    pool : D3DPOOL
    width : UInt32
    height : UInt32
    depth : UInt32
  end
  struct D3DLOCKED_RECT
    pitch : Int32
    p_bits : Void*
  end
  struct D3DBOX
    left : UInt32
    top : UInt32
    right : UInt32
    bottom : UInt32
    front : UInt32
    back : UInt32
  end
  struct D3DLOCKED_BOX
    row_pitch : Int32
    slice_pitch : Int32
    p_bits : Void*
  end
  struct D3DRANGE
    offset : UInt32
    size : UInt32
  end
  struct D3DRECTPATCH_INFO
    start_vertex_offset_width : UInt32
    start_vertex_offset_height : UInt32
    width : UInt32
    height : UInt32
    stride : UInt32
    basis : D3DBASISTYPE
    degree : D3DDEGREETYPE
  end
  struct D3DTRIPATCH_INFO
    start_vertex_offset : UInt32
    num_vertices : UInt32
    basis : D3DBASISTYPE
    degree : D3DDEGREETYPE
  end
  struct D3DADAPTER_IDENTIFIER9
    driver : CHAR[512]*
    description : CHAR[512]*
    device_name : CHAR[32]*
    driver_version : LARGE_INTEGER
    vendor_id : UInt32
    device_id : UInt32
    sub_sys_id : UInt32
    revision : UInt32
    device_identifier : Guid
    whql_level : UInt32
  end
  struct D3DRASTER_STATUS
    in_v_blank : LibC::BOOL
    scan_line : UInt32
  end
  struct D3DRESOURCESTATS
    b_thrashing : LibC::BOOL
    approx_bytes_downloaded : UInt32
    num_evicts : UInt32
    num_vid_creates : UInt32
    last_pri : UInt32
    num_used : UInt32
    num_used_in_vid_mem : UInt32
    working_set : UInt32
    working_set_bytes : UInt32
    total_managed : UInt32
    total_bytes : UInt32
  end
  struct D3DDEVINFO_RESOURCEMANAGER
    stats : D3DRESOURCESTATS[8]*
  end
  struct D3DDEVINFO_D3DVERTEXSTATS
    num_rendered_triangles : UInt32
    num_extra_clipping_triangles : UInt32
  end
  struct D3DDEVINFO_VCACHE
    pattern : UInt32
    opt_method : UInt32
    cache_size : UInt32
    magic_number : UInt32
  end
  struct D3DDEVINFO_D3D9PIPELINETIMINGS
    vertex_processing_time_percent : Float32
    pixel_processing_time_percent : Float32
    other_gpu_processing_time_percent : Float32
    gpu_idle_time_percent : Float32
  end
  struct D3DDEVINFO_D3D9INTERFACETIMINGS
    waiting_for_gpu_to_use_application_resource_time_percent : Float32
    waiting_for_gpu_to_accept_more_commands_time_percent : Float32
    waiting_for_gpu_to_stay_within_latency_time_percent : Float32
    waiting_for_gpu_exclusive_resource_time_percent : Float32
    waiting_for_gpu_other_time_percent : Float32
  end
  struct D3DDEVINFO_D3D9STAGETIMINGS
    memory_processing_percent : Float32
    computation_processing_percent : Float32
  end
  struct D3DDEVINFO_D3D9BANDWIDTHTIMINGS
    max_bandwidth_utilized : Float32
    front_end_upload_memory_utilized_percent : Float32
    vertex_rate_utilized_percent : Float32
    triangle_setup_rate_utilized_percent : Float32
    fill_rate_utilized_percent : Float32
  end
  struct D3DDEVINFO_D3D9CACHEUTILIZATION
    texture_cache_hit_rate : Float32
    post_transform_vertex_cache_hit_rate : Float32
  end
  struct D3DMEMORYPRESSURE
    bytes_evicted_from_process : UInt64
    size_of_inefficient_allocation : UInt64
    level_of_efficiency : UInt32
  end
  struct D3DCOMPOSERECTDESC
    x : UInt16
    y : UInt16
    width : UInt16
    height : UInt16
  end
  struct D3DCOMPOSERECTDESTINATION
    src_rect_index : UInt16
    reserved : UInt16
    x : Int16
    y : Int16
  end
  struct D3DPRESENTSTATS
    present_count : UInt32
    present_refresh_count : UInt32
    sync_refresh_count : UInt32
    sync_qpc_time : LARGE_INTEGER
    sync_gpu_time : LARGE_INTEGER
  end
  struct D3DDISPLAYMODEEX
    size : UInt32
    width : UInt32
    height : UInt32
    refresh_rate : UInt32
    format : D3DFORMAT
    scan_line_ordering : D3DSCANLINEORDERING
  end
  struct D3DDISPLAYMODEFILTER
    size : UInt32
    format : D3DFORMAT
    scan_line_ordering : D3DSCANLINEORDERING
  end
  struct D3D_OMAC
    omac : UInt8[16]*
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERY_INPUT
    query_type : Guid
    h_channel : LibC::HANDLE
    sequence_number : UInt32
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT
    omac : D3D_OMAC
    query_type : Guid
    h_channel : LibC::HANDLE
    sequence_number : UInt32
    return_code : HRESULT
  end
  struct D3DAUTHENTICATEDCHANNEL_PROTECTION_FLAGS
    anonymous : D3DAUTHENTICATEDCHANNEL_PROTECTION_FLAGS_Anonymous_e__Union
  end
  struct D3DAUTHENTICATEDCHANNEL_PROTECTION_FLAGS_Anonymous_e__Union_Anonymous_e__Struct
    _bitfield : UInt32
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYPROTECTION_OUTPUT
    output : D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT
    protection_flags : D3DAUTHENTICATEDCHANNEL_PROTECTION_FLAGS
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYCHANNELTYPE_OUTPUT
    output : D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT
    channel_type : D3DAUTHENTICATEDCHANNELTYPE
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYDEVICEHANDLE_OUTPUT
    output : D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT
    device_handle : LibC::HANDLE
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYCRYPTOSESSION_INPUT
    input : D3DAUTHENTICATEDCHANNEL_QUERY_INPUT
    dxva2_decode_handle : LibC::HANDLE
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYCRYPTOSESSION_OUTPUT
    output : D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT
    dxva2_decode_handle : LibC::HANDLE
    crypto_session_handle : LibC::HANDLE
    device_handle : LibC::HANDLE
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYRESTRICTEDSHAREDRESOURCEPROCESSCOUNT_OUTPUT
    output : D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT
    num_restricted_shared_resource_processes : UInt32
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYRESTRICTEDSHAREDRESOURCEPROCESS_INPUT
    input : D3DAUTHENTICATEDCHANNEL_QUERY_INPUT
    process_index : UInt32
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYRESTRICTEDSHAREDRESOURCEPROCESS_OUTPUT
    output : D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT
    process_index : UInt32
    process_identifer : D3DAUTHENTICATEDCHANNEL_PROCESSIDENTIFIERTYPE
    process_handle : LibC::HANDLE
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYUNRESTRICTEDPROTECTEDSHAREDRESOURCECOUNT_OUTPUT
    output : D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT
    num_unrestricted_protected_shared_resources : UInt32
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTIDCOUNT_INPUT
    input : D3DAUTHENTICATEDCHANNEL_QUERY_INPUT
    device_handle : LibC::HANDLE
    crypto_session_handle : LibC::HANDLE
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTIDCOUNT_OUTPUT
    output : D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT
    device_handle : LibC::HANDLE
    crypto_session_handle : LibC::HANDLE
    num_output_i_ds : UInt32
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTID_INPUT
    input : D3DAUTHENTICATEDCHANNEL_QUERY_INPUT
    device_handle : LibC::HANDLE
    crypto_session_handle : LibC::HANDLE
    output_id_index : UInt32
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTID_OUTPUT
    output : D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT
    device_handle : LibC::HANDLE
    crypto_session_handle : LibC::HANDLE
    output_id_index : UInt32
    output_id : UInt64
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYINFOBUSTYPE_OUTPUT
    output : D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT
    bus_type : D3DBUSTYPE
    b_accessible_in_contiguous_blocks : LibC::BOOL
    b_accessible_in_non_contiguous_blocks : LibC::BOOL
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYEVICTIONENCRYPTIONGUIDCOUNT_OUTPUT
    output : D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT
    num_encryption_guids : UInt32
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYEVICTIONENCRYPTIONGUID_INPUT
    input : D3DAUTHENTICATEDCHANNEL_QUERY_INPUT
    encryption_guid_index : UInt32
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYEVICTIONENCRYPTIONGUID_OUTPUT
    output : D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT
    encryption_guid_index : UInt32
    encryption_guid : Guid
  end
  struct D3DAUTHENTICATEDCHANNEL_QUERYUNCOMPRESSEDENCRYPTIONLEVEL_OUTPUT
    output : D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT
    encryption_guid : Guid
  end
  struct D3DAUTHENTICATEDCHANNEL_CONFIGURE_INPUT
    omac : D3D_OMAC
    configure_type : Guid
    h_channel : LibC::HANDLE
    sequence_number : UInt32
  end
  struct D3DAUTHENTICATEDCHANNEL_CONFIGURE_OUTPUT
    omac : D3D_OMAC
    configure_type : Guid
    h_channel : LibC::HANDLE
    sequence_number : UInt32
    return_code : HRESULT
  end
  struct D3DAUTHENTICATEDCHANNEL_CONFIGUREINITIALIZE
    parameters : D3DAUTHENTICATEDCHANNEL_CONFIGURE_INPUT
    start_sequence_query : UInt32
    start_sequence_configure : UInt32
  end
  struct D3DAUTHENTICATEDCHANNEL_CONFIGUREPROTECTION
    parameters : D3DAUTHENTICATEDCHANNEL_CONFIGURE_INPUT
    protections : D3DAUTHENTICATEDCHANNEL_PROTECTION_FLAGS
  end
  struct D3DAUTHENTICATEDCHANNEL_CONFIGURECRYPTOSESSION
    parameters : D3DAUTHENTICATEDCHANNEL_CONFIGURE_INPUT
    dxva2_decode_handle : LibC::HANDLE
    crypto_session_handle : LibC::HANDLE
    device_handle : LibC::HANDLE
  end
  struct D3DAUTHENTICATEDCHANNEL_CONFIGURESHAREDRESOURCE
    parameters : D3DAUTHENTICATEDCHANNEL_CONFIGURE_INPUT
    process_identifer_type : D3DAUTHENTICATEDCHANNEL_PROCESSIDENTIFIERTYPE
    process_handle : LibC::HANDLE
    allow_access : LibC::BOOL
  end
  struct D3DAUTHENTICATEDCHANNEL_CONFIGUREUNCOMPRESSEDENCRYPTION
    parameters : D3DAUTHENTICATEDCHANNEL_CONFIGURE_INPUT
    encryption_guid : Guid
  end
  struct D3DENCRYPTED_BLOCK_INFO
    num_encrypted_bytes_at_beginning : UInt32
    num_bytes_in_skip_pattern : UInt32
    num_bytes_in_encrypt_pattern : UInt32
  end
  struct D3DAES_CTR_IV
    iv : UInt64
    count : UInt64
  end
  struct D3DVSHADERCAPS2_0
    caps : UInt32
    dynamic_flow_control_depth : Int32
    num_temps : Int32
    static_flow_control_depth : Int32
  end
  struct D3DPSHADERCAPS2_0
    caps : UInt32
    dynamic_flow_control_depth : Int32
    num_temps : Int32
    static_flow_control_depth : Int32
    num_instruction_slots : Int32
  end
  struct D3DCAPS9
    device_type : D3DDEVTYPE
    adapter_ordinal : UInt32
    caps : UInt32
    caps2 : UInt32
    caps3 : UInt32
    presentation_intervals : UInt32
    cursor_caps : UInt32
    dev_caps : UInt32
    primitive_misc_caps : UInt32
    raster_caps : UInt32
    z_cmp_caps : UInt32
    src_blend_caps : UInt32
    dest_blend_caps : UInt32
    alpha_cmp_caps : UInt32
    shade_caps : UInt32
    texture_caps : UInt32
    texture_filter_caps : UInt32
    cube_texture_filter_caps : UInt32
    volume_texture_filter_caps : UInt32
    texture_address_caps : UInt32
    volume_texture_address_caps : UInt32
    line_caps : UInt32
    max_texture_width : UInt32
    max_texture_height : UInt32
    max_volume_extent : UInt32
    max_texture_repeat : UInt32
    max_texture_aspect_ratio : UInt32
    max_anisotropy : UInt32
    max_vertex_w : Float32
    guard_band_left : Float32
    guard_band_top : Float32
    guard_band_right : Float32
    guard_band_bottom : Float32
    extents_adjust : Float32
    stencil_caps : UInt32
    fvf_caps : UInt32
    texture_op_caps : UInt32
    max_texture_blend_stages : UInt32
    max_simultaneous_textures : UInt32
    vertex_processing_caps : UInt32
    max_active_lights : UInt32
    max_user_clip_planes : UInt32
    max_vertex_blend_matrices : UInt32
    max_vertex_blend_matrix_index : UInt32
    max_point_size : Float32
    max_primitive_count : UInt32
    max_vertex_index : UInt32
    max_streams : UInt32
    max_stream_stride : UInt32
    vertex_shader_version : UInt32
    max_vertex_shader_const : UInt32
    pixel_shader_version : UInt32
    pixel_shader1x_max_value : Float32
    dev_caps2 : UInt32
    max_npatch_tessellation_level : Float32
    reserved5 : UInt32
    master_adapter_ordinal : UInt32
    adapter_ordinal_in_group : UInt32
    number_of_adapters_in_group : UInt32
    decl_types : UInt32
    num_simultaneous_r_ts : UInt32
    stretch_rect_filter_caps : UInt32
    vs20_caps : D3DVSHADERCAPS2_0
    ps20_caps : D3DPSHADERCAPS2_0
    vertex_texture_filter_caps : UInt32
    max_v_shader_instructions_executed : UInt32
    max_p_shader_instructions_executed : UInt32
    max_vertex_shader30_instruction_slots : UInt32
    max_pixel_shader30_instruction_slots : UInt32
  end


  struct IDirect3D9VTbl
    query_interface : Proc(IDirect3D9*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3D9*, UInt32)
    release : Proc(IDirect3D9*, UInt32)
    register_software_device : Proc(IDirect3D9*, Void*, HRESULT)
    get_adapter_count : Proc(IDirect3D9*, UInt32)
    get_adapter_identifier : Proc(IDirect3D9*, UInt32, UInt32, D3DADAPTER_IDENTIFIER9*, HRESULT)
    get_adapter_mode_count : Proc(IDirect3D9*, UInt32, D3DFORMAT, UInt32)
    enum_adapter_modes : Proc(IDirect3D9*, UInt32, D3DFORMAT, UInt32, D3DDISPLAYMODE*, HRESULT)
    get_adapter_display_mode : Proc(IDirect3D9*, UInt32, D3DDISPLAYMODE*, HRESULT)
    check_device_type : Proc(IDirect3D9*, UInt32, D3DDEVTYPE, D3DFORMAT, D3DFORMAT, LibC::BOOL, HRESULT)
    check_device_format : Proc(IDirect3D9*, UInt32, D3DDEVTYPE, D3DFORMAT, UInt32, D3DRESOURCETYPE, D3DFORMAT, HRESULT)
    check_device_multi_sample_type : Proc(IDirect3D9*, UInt32, D3DDEVTYPE, D3DFORMAT, LibC::BOOL, D3DMULTISAMPLE_TYPE, UInt32*, HRESULT)
    check_depth_stencil_match : Proc(IDirect3D9*, UInt32, D3DDEVTYPE, D3DFORMAT, D3DFORMAT, D3DFORMAT, HRESULT)
    check_device_format_conversion : Proc(IDirect3D9*, UInt32, D3DDEVTYPE, D3DFORMAT, D3DFORMAT, HRESULT)
    get_device_caps : Proc(IDirect3D9*, UInt32, D3DDEVTYPE, D3DCAPS9*, HRESULT)
    get_adapter_monitor : Proc(IDirect3D9*, UInt32, HMONITOR)
    create_device : Proc(IDirect3D9*, UInt32, D3DDEVTYPE, LibC::HANDLE, UInt32, D3DPRESENT_PARAMETERS*, IDirect3DDevice9*, HRESULT)
  end

  struct IDirect3D9
    lpVtbl : IDirect3D9VTbl*
  end

  struct IDirect3DDevice9VTbl
    query_interface : Proc(IDirect3DDevice9*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DDevice9*, UInt32)
    release : Proc(IDirect3DDevice9*, UInt32)
    test_cooperative_level : Proc(IDirect3DDevice9*, HRESULT)
    get_available_texture_mem : Proc(IDirect3DDevice9*, UInt32)
    evict_managed_resources : Proc(IDirect3DDevice9*, HRESULT)
    get_direct3_d : Proc(IDirect3DDevice9*, IDirect3D9*, HRESULT)
    get_device_caps : Proc(IDirect3DDevice9*, D3DCAPS9*, HRESULT)
    get_display_mode : Proc(IDirect3DDevice9*, UInt32, D3DDISPLAYMODE*, HRESULT)
    get_creation_parameters : Proc(IDirect3DDevice9*, D3DDEVICE_CREATION_PARAMETERS*, HRESULT)
    set_cursor_properties : Proc(IDirect3DDevice9*, UInt32, UInt32, IDirect3DSurface9, HRESULT)
    set_cursor_position : Proc(IDirect3DDevice9*, Int32, Int32, UInt32, Void)
    show_cursor : Proc(IDirect3DDevice9*, LibC::BOOL, LibC::BOOL)
    create_additional_swap_chain : Proc(IDirect3DDevice9*, D3DPRESENT_PARAMETERS*, IDirect3DSwapChain9*, HRESULT)
    get_swap_chain : Proc(IDirect3DDevice9*, UInt32, IDirect3DSwapChain9*, HRESULT)
    get_number_of_swap_chains : Proc(IDirect3DDevice9*, UInt32)
    reset : Proc(IDirect3DDevice9*, D3DPRESENT_PARAMETERS*, HRESULT)
    present : Proc(IDirect3DDevice9*, RECT*, RECT*, LibC::HANDLE, RGNDATA*, HRESULT)
    get_back_buffer : Proc(IDirect3DDevice9*, UInt32, UInt32, D3DBACKBUFFER_TYPE, IDirect3DSurface9*, HRESULT)
    get_raster_status : Proc(IDirect3DDevice9*, UInt32, D3DRASTER_STATUS*, HRESULT)
    set_dialog_box_mode : Proc(IDirect3DDevice9*, LibC::BOOL, HRESULT)
    set_gamma_ramp : Proc(IDirect3DDevice9*, UInt32, UInt32, D3DGAMMARAMP*, Void)
    get_gamma_ramp : Proc(IDirect3DDevice9*, UInt32, D3DGAMMARAMP*, Void)
    create_texture : Proc(IDirect3DDevice9*, UInt32, UInt32, UInt32, UInt32, D3DFORMAT, D3DPOOL, IDirect3DTexture9*, LibC::HANDLE*, HRESULT)
    create_volume_texture : Proc(IDirect3DDevice9*, UInt32, UInt32, UInt32, UInt32, UInt32, D3DFORMAT, D3DPOOL, IDirect3DVolumeTexture9*, LibC::HANDLE*, HRESULT)
    create_cube_texture : Proc(IDirect3DDevice9*, UInt32, UInt32, UInt32, D3DFORMAT, D3DPOOL, IDirect3DCubeTexture9*, LibC::HANDLE*, HRESULT)
    create_vertex_buffer : Proc(IDirect3DDevice9*, UInt32, UInt32, UInt32, D3DPOOL, IDirect3DVertexBuffer9*, LibC::HANDLE*, HRESULT)
    create_index_buffer : Proc(IDirect3DDevice9*, UInt32, UInt32, D3DFORMAT, D3DPOOL, IDirect3DIndexBuffer9*, LibC::HANDLE*, HRESULT)
    create_render_target : Proc(IDirect3DDevice9*, UInt32, UInt32, D3DFORMAT, D3DMULTISAMPLE_TYPE, UInt32, LibC::BOOL, IDirect3DSurface9*, LibC::HANDLE*, HRESULT)
    create_depth_stencil_surface : Proc(IDirect3DDevice9*, UInt32, UInt32, D3DFORMAT, D3DMULTISAMPLE_TYPE, UInt32, LibC::BOOL, IDirect3DSurface9*, LibC::HANDLE*, HRESULT)
    update_surface : Proc(IDirect3DDevice9*, IDirect3DSurface9, RECT*, IDirect3DSurface9, POINT*, HRESULT)
    update_texture : Proc(IDirect3DDevice9*, IDirect3DBaseTexture9, IDirect3DBaseTexture9, HRESULT)
    get_render_target_data : Proc(IDirect3DDevice9*, IDirect3DSurface9, IDirect3DSurface9, HRESULT)
    get_front_buffer_data : Proc(IDirect3DDevice9*, UInt32, IDirect3DSurface9, HRESULT)
    stretch_rect : Proc(IDirect3DDevice9*, IDirect3DSurface9, RECT*, IDirect3DSurface9, RECT*, D3DTEXTUREFILTERTYPE, HRESULT)
    color_fill : Proc(IDirect3DDevice9*, IDirect3DSurface9, RECT*, UInt32, HRESULT)
    create_offscreen_plain_surface : Proc(IDirect3DDevice9*, UInt32, UInt32, D3DFORMAT, D3DPOOL, IDirect3DSurface9*, LibC::HANDLE*, HRESULT)
    set_render_target : Proc(IDirect3DDevice9*, UInt32, IDirect3DSurface9, HRESULT)
    get_render_target : Proc(IDirect3DDevice9*, UInt32, IDirect3DSurface9*, HRESULT)
    set_depth_stencil_surface : Proc(IDirect3DDevice9*, IDirect3DSurface9, HRESULT)
    get_depth_stencil_surface : Proc(IDirect3DDevice9*, IDirect3DSurface9*, HRESULT)
    begin_scene : Proc(IDirect3DDevice9*, HRESULT)
    end_scene : Proc(IDirect3DDevice9*, HRESULT)
    clear : Proc(IDirect3DDevice9*, UInt32, D3DRECT*, UInt32, UInt32, Float32, UInt32, HRESULT)
    set_transform : Proc(IDirect3DDevice9*, D3DTRANSFORMSTATETYPE, D3DMATRIX*, HRESULT)
    get_transform : Proc(IDirect3DDevice9*, D3DTRANSFORMSTATETYPE, D3DMATRIX*, HRESULT)
    multiply_transform : Proc(IDirect3DDevice9*, D3DTRANSFORMSTATETYPE, D3DMATRIX*, HRESULT)
    set_viewport : Proc(IDirect3DDevice9*, D3DVIEWPORT9*, HRESULT)
    get_viewport : Proc(IDirect3DDevice9*, D3DVIEWPORT9*, HRESULT)
    set_material : Proc(IDirect3DDevice9*, D3DMATERIAL9*, HRESULT)
    get_material : Proc(IDirect3DDevice9*, D3DMATERIAL9*, HRESULT)
    set_light : Proc(IDirect3DDevice9*, UInt32, D3DLIGHT9*, HRESULT)
    get_light : Proc(IDirect3DDevice9*, UInt32, D3DLIGHT9*, HRESULT)
    light_enable : Proc(IDirect3DDevice9*, UInt32, LibC::BOOL, HRESULT)
    get_light_enable : Proc(IDirect3DDevice9*, UInt32, LibC::BOOL*, HRESULT)
    set_clip_plane : Proc(IDirect3DDevice9*, UInt32, Float32*, HRESULT)
    get_clip_plane : Proc(IDirect3DDevice9*, UInt32, Float32*, HRESULT)
    set_render_state : Proc(IDirect3DDevice9*, D3DRENDERSTATETYPE, UInt32, HRESULT)
    get_render_state : Proc(IDirect3DDevice9*, D3DRENDERSTATETYPE, UInt32*, HRESULT)
    create_state_block : Proc(IDirect3DDevice9*, D3DSTATEBLOCKTYPE, IDirect3DStateBlock9*, HRESULT)
    begin_state_block : Proc(IDirect3DDevice9*, HRESULT)
    end_state_block : Proc(IDirect3DDevice9*, IDirect3DStateBlock9*, HRESULT)
    set_clip_status : Proc(IDirect3DDevice9*, D3DCLIPSTATUS9*, HRESULT)
    get_clip_status : Proc(IDirect3DDevice9*, D3DCLIPSTATUS9*, HRESULT)
    get_texture : Proc(IDirect3DDevice9*, UInt32, IDirect3DBaseTexture9*, HRESULT)
    set_texture : Proc(IDirect3DDevice9*, UInt32, IDirect3DBaseTexture9, HRESULT)
    get_texture_stage_state : Proc(IDirect3DDevice9*, UInt32, D3DTEXTURESTAGESTATETYPE, UInt32*, HRESULT)
    set_texture_stage_state : Proc(IDirect3DDevice9*, UInt32, D3DTEXTURESTAGESTATETYPE, UInt32, HRESULT)
    get_sampler_state : Proc(IDirect3DDevice9*, UInt32, D3DSAMPLERSTATETYPE, UInt32*, HRESULT)
    set_sampler_state : Proc(IDirect3DDevice9*, UInt32, D3DSAMPLERSTATETYPE, UInt32, HRESULT)
    validate_device : Proc(IDirect3DDevice9*, UInt32*, HRESULT)
    set_palette_entries : Proc(IDirect3DDevice9*, UInt32, PALETTEENTRY*, HRESULT)
    get_palette_entries : Proc(IDirect3DDevice9*, UInt32, PALETTEENTRY*, HRESULT)
    set_current_texture_palette : Proc(IDirect3DDevice9*, UInt32, HRESULT)
    get_current_texture_palette : Proc(IDirect3DDevice9*, UInt32*, HRESULT)
    set_scissor_rect : Proc(IDirect3DDevice9*, RECT*, HRESULT)
    get_scissor_rect : Proc(IDirect3DDevice9*, RECT*, HRESULT)
    set_software_vertex_processing : Proc(IDirect3DDevice9*, LibC::BOOL, HRESULT)
    get_software_vertex_processing : Proc(IDirect3DDevice9*, LibC::BOOL)
    set_n_patch_mode : Proc(IDirect3DDevice9*, Float32, HRESULT)
    get_n_patch_mode : Proc(IDirect3DDevice9*, Float32)
    draw_primitive : Proc(IDirect3DDevice9*, D3DPRIMITIVETYPE, UInt32, UInt32, HRESULT)
    draw_indexed_primitive : Proc(IDirect3DDevice9*, D3DPRIMITIVETYPE, Int32, UInt32, UInt32, UInt32, UInt32, HRESULT)
    draw_primitive_up : Proc(IDirect3DDevice9*, D3DPRIMITIVETYPE, UInt32, Void*, UInt32, HRESULT)
    draw_indexed_primitive_up : Proc(IDirect3DDevice9*, D3DPRIMITIVETYPE, UInt32, UInt32, UInt32, Void*, D3DFORMAT, Void*, UInt32, HRESULT)
    process_vertices : Proc(IDirect3DDevice9*, UInt32, UInt32, UInt32, IDirect3DVertexBuffer9, IDirect3DVertexDeclaration9, UInt32, HRESULT)
    create_vertex_declaration : Proc(IDirect3DDevice9*, D3DVERTEXELEMENT9*, IDirect3DVertexDeclaration9*, HRESULT)
    set_vertex_declaration : Proc(IDirect3DDevice9*, IDirect3DVertexDeclaration9, HRESULT)
    get_vertex_declaration : Proc(IDirect3DDevice9*, IDirect3DVertexDeclaration9*, HRESULT)
    set_fvf : Proc(IDirect3DDevice9*, UInt32, HRESULT)
    get_fvf : Proc(IDirect3DDevice9*, UInt32*, HRESULT)
    create_vertex_shader : Proc(IDirect3DDevice9*, UInt32*, IDirect3DVertexShader9*, HRESULT)
    set_vertex_shader : Proc(IDirect3DDevice9*, IDirect3DVertexShader9, HRESULT)
    get_vertex_shader : Proc(IDirect3DDevice9*, IDirect3DVertexShader9*, HRESULT)
    set_vertex_shader_constant_f : Proc(IDirect3DDevice9*, UInt32, Float32*, UInt32, HRESULT)
    get_vertex_shader_constant_f : Proc(IDirect3DDevice9*, UInt32, Float32*, UInt32, HRESULT)
    set_vertex_shader_constant_i : Proc(IDirect3DDevice9*, UInt32, Int32*, UInt32, HRESULT)
    get_vertex_shader_constant_i : Proc(IDirect3DDevice9*, UInt32, Int32*, UInt32, HRESULT)
    set_vertex_shader_constant_b : Proc(IDirect3DDevice9*, UInt32, LibC::BOOL*, UInt32, HRESULT)
    get_vertex_shader_constant_b : Proc(IDirect3DDevice9*, UInt32, LibC::BOOL*, UInt32, HRESULT)
    set_stream_source : Proc(IDirect3DDevice9*, UInt32, IDirect3DVertexBuffer9, UInt32, UInt32, HRESULT)
    get_stream_source : Proc(IDirect3DDevice9*, UInt32, IDirect3DVertexBuffer9*, UInt32*, UInt32*, HRESULT)
    set_stream_source_freq : Proc(IDirect3DDevice9*, UInt32, UInt32, HRESULT)
    get_stream_source_freq : Proc(IDirect3DDevice9*, UInt32, UInt32*, HRESULT)
    set_indices : Proc(IDirect3DDevice9*, IDirect3DIndexBuffer9, HRESULT)
    get_indices : Proc(IDirect3DDevice9*, IDirect3DIndexBuffer9*, HRESULT)
    create_pixel_shader : Proc(IDirect3DDevice9*, UInt32*, IDirect3DPixelShader9*, HRESULT)
    set_pixel_shader : Proc(IDirect3DDevice9*, IDirect3DPixelShader9, HRESULT)
    get_pixel_shader : Proc(IDirect3DDevice9*, IDirect3DPixelShader9*, HRESULT)
    set_pixel_shader_constant_f : Proc(IDirect3DDevice9*, UInt32, Float32*, UInt32, HRESULT)
    get_pixel_shader_constant_f : Proc(IDirect3DDevice9*, UInt32, Float32*, UInt32, HRESULT)
    set_pixel_shader_constant_i : Proc(IDirect3DDevice9*, UInt32, Int32*, UInt32, HRESULT)
    get_pixel_shader_constant_i : Proc(IDirect3DDevice9*, UInt32, Int32*, UInt32, HRESULT)
    set_pixel_shader_constant_b : Proc(IDirect3DDevice9*, UInt32, LibC::BOOL*, UInt32, HRESULT)
    get_pixel_shader_constant_b : Proc(IDirect3DDevice9*, UInt32, LibC::BOOL*, UInt32, HRESULT)
    draw_rect_patch : Proc(IDirect3DDevice9*, UInt32, Float32*, D3DRECTPATCH_INFO*, HRESULT)
    draw_tri_patch : Proc(IDirect3DDevice9*, UInt32, Float32*, D3DTRIPATCH_INFO*, HRESULT)
    delete_patch : Proc(IDirect3DDevice9*, UInt32, HRESULT)
    create_query : Proc(IDirect3DDevice9*, D3DQUERYTYPE, IDirect3DQuery9*, HRESULT)
  end

  struct IDirect3DDevice9
    lpVtbl : IDirect3DDevice9VTbl*
  end

  struct IDirect3DStateBlock9VTbl
    query_interface : Proc(IDirect3DStateBlock9*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DStateBlock9*, UInt32)
    release : Proc(IDirect3DStateBlock9*, UInt32)
    get_device : Proc(IDirect3DStateBlock9*, IDirect3DDevice9*, HRESULT)
    capture : Proc(IDirect3DStateBlock9*, HRESULT)
    apply : Proc(IDirect3DStateBlock9*, HRESULT)
  end

  struct IDirect3DStateBlock9
    lpVtbl : IDirect3DStateBlock9VTbl*
  end

  struct IDirect3DSwapChain9VTbl
    query_interface : Proc(IDirect3DSwapChain9*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DSwapChain9*, UInt32)
    release : Proc(IDirect3DSwapChain9*, UInt32)
    present : Proc(IDirect3DSwapChain9*, RECT*, RECT*, LibC::HANDLE, RGNDATA*, UInt32, HRESULT)
    get_front_buffer_data : Proc(IDirect3DSwapChain9*, IDirect3DSurface9, HRESULT)
    get_back_buffer : Proc(IDirect3DSwapChain9*, UInt32, D3DBACKBUFFER_TYPE, IDirect3DSurface9*, HRESULT)
    get_raster_status : Proc(IDirect3DSwapChain9*, D3DRASTER_STATUS*, HRESULT)
    get_display_mode : Proc(IDirect3DSwapChain9*, D3DDISPLAYMODE*, HRESULT)
    get_device : Proc(IDirect3DSwapChain9*, IDirect3DDevice9*, HRESULT)
    get_present_parameters : Proc(IDirect3DSwapChain9*, D3DPRESENT_PARAMETERS*, HRESULT)
  end

  struct IDirect3DSwapChain9
    lpVtbl : IDirect3DSwapChain9VTbl*
  end

  struct IDirect3DResource9VTbl
    query_interface : Proc(IDirect3DResource9*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DResource9*, UInt32)
    release : Proc(IDirect3DResource9*, UInt32)
    get_device : Proc(IDirect3DResource9*, IDirect3DDevice9*, HRESULT)
    set_private_data : Proc(IDirect3DResource9*, Guid*, Void*, UInt32, UInt32, HRESULT)
    get_private_data : Proc(IDirect3DResource9*, Guid*, Void*, UInt32*, HRESULT)
    free_private_data : Proc(IDirect3DResource9*, Guid*, HRESULT)
    set_priority : Proc(IDirect3DResource9*, UInt32, UInt32)
    get_priority : Proc(IDirect3DResource9*, UInt32)
    pre_load : Proc(IDirect3DResource9*, Void)
    get_type : Proc(IDirect3DResource9*, D3DRESOURCETYPE)
  end

  struct IDirect3DResource9
    lpVtbl : IDirect3DResource9VTbl*
  end

  struct IDirect3DVertexDeclaration9VTbl
    query_interface : Proc(IDirect3DVertexDeclaration9*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DVertexDeclaration9*, UInt32)
    release : Proc(IDirect3DVertexDeclaration9*, UInt32)
    get_device : Proc(IDirect3DVertexDeclaration9*, IDirect3DDevice9*, HRESULT)
    get_declaration : Proc(IDirect3DVertexDeclaration9*, D3DVERTEXELEMENT9*, UInt32*, HRESULT)
  end

  struct IDirect3DVertexDeclaration9
    lpVtbl : IDirect3DVertexDeclaration9VTbl*
  end

  struct IDirect3DVertexShader9VTbl
    query_interface : Proc(IDirect3DVertexShader9*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DVertexShader9*, UInt32)
    release : Proc(IDirect3DVertexShader9*, UInt32)
    get_device : Proc(IDirect3DVertexShader9*, IDirect3DDevice9*, HRESULT)
    get_function : Proc(IDirect3DVertexShader9*, Void*, UInt32*, HRESULT)
  end

  struct IDirect3DVertexShader9
    lpVtbl : IDirect3DVertexShader9VTbl*
  end

  struct IDirect3DPixelShader9VTbl
    query_interface : Proc(IDirect3DPixelShader9*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DPixelShader9*, UInt32)
    release : Proc(IDirect3DPixelShader9*, UInt32)
    get_device : Proc(IDirect3DPixelShader9*, IDirect3DDevice9*, HRESULT)
    get_function : Proc(IDirect3DPixelShader9*, Void*, UInt32*, HRESULT)
  end

  struct IDirect3DPixelShader9
    lpVtbl : IDirect3DPixelShader9VTbl*
  end

  struct IDirect3DBaseTexture9VTbl
    query_interface : Proc(IDirect3DBaseTexture9*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DBaseTexture9*, UInt32)
    release : Proc(IDirect3DBaseTexture9*, UInt32)
    get_device : Proc(IDirect3DBaseTexture9*, IDirect3DDevice9*, HRESULT)
    set_private_data : Proc(IDirect3DBaseTexture9*, Guid*, Void*, UInt32, UInt32, HRESULT)
    get_private_data : Proc(IDirect3DBaseTexture9*, Guid*, Void*, UInt32*, HRESULT)
    free_private_data : Proc(IDirect3DBaseTexture9*, Guid*, HRESULT)
    set_priority : Proc(IDirect3DBaseTexture9*, UInt32, UInt32)
    get_priority : Proc(IDirect3DBaseTexture9*, UInt32)
    pre_load : Proc(IDirect3DBaseTexture9*, Void)
    get_type : Proc(IDirect3DBaseTexture9*, D3DRESOURCETYPE)
    set_lod : Proc(IDirect3DBaseTexture9*, UInt32, UInt32)
    get_lod : Proc(IDirect3DBaseTexture9*, UInt32)
    get_level_count : Proc(IDirect3DBaseTexture9*, UInt32)
    set_auto_gen_filter_type : Proc(IDirect3DBaseTexture9*, D3DTEXTUREFILTERTYPE, HRESULT)
    get_auto_gen_filter_type : Proc(IDirect3DBaseTexture9*, D3DTEXTUREFILTERTYPE)
    generate_mip_sub_levels : Proc(IDirect3DBaseTexture9*, Void)
  end

  struct IDirect3DBaseTexture9
    lpVtbl : IDirect3DBaseTexture9VTbl*
  end

  struct IDirect3DTexture9VTbl
    query_interface : Proc(IDirect3DTexture9*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DTexture9*, UInt32)
    release : Proc(IDirect3DTexture9*, UInt32)
    get_device : Proc(IDirect3DTexture9*, IDirect3DDevice9*, HRESULT)
    set_private_data : Proc(IDirect3DTexture9*, Guid*, Void*, UInt32, UInt32, HRESULT)
    get_private_data : Proc(IDirect3DTexture9*, Guid*, Void*, UInt32*, HRESULT)
    free_private_data : Proc(IDirect3DTexture9*, Guid*, HRESULT)
    set_priority : Proc(IDirect3DTexture9*, UInt32, UInt32)
    get_priority : Proc(IDirect3DTexture9*, UInt32)
    pre_load : Proc(IDirect3DTexture9*, Void)
    get_type : Proc(IDirect3DTexture9*, D3DRESOURCETYPE)
    set_lod : Proc(IDirect3DTexture9*, UInt32, UInt32)
    get_lod : Proc(IDirect3DTexture9*, UInt32)
    get_level_count : Proc(IDirect3DTexture9*, UInt32)
    set_auto_gen_filter_type : Proc(IDirect3DTexture9*, D3DTEXTUREFILTERTYPE, HRESULT)
    get_auto_gen_filter_type : Proc(IDirect3DTexture9*, D3DTEXTUREFILTERTYPE)
    generate_mip_sub_levels : Proc(IDirect3DTexture9*, Void)
    get_level_desc : Proc(IDirect3DTexture9*, UInt32, D3DSURFACE_DESC*, HRESULT)
    get_surface_level : Proc(IDirect3DTexture9*, UInt32, IDirect3DSurface9*, HRESULT)
    lock_rect : Proc(IDirect3DTexture9*, UInt32, D3DLOCKED_RECT*, RECT*, UInt32, HRESULT)
    unlock_rect : Proc(IDirect3DTexture9*, UInt32, HRESULT)
    add_dirty_rect : Proc(IDirect3DTexture9*, RECT*, HRESULT)
  end

  struct IDirect3DTexture9
    lpVtbl : IDirect3DTexture9VTbl*
  end

  struct IDirect3DVolumeTexture9VTbl
    query_interface : Proc(IDirect3DVolumeTexture9*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DVolumeTexture9*, UInt32)
    release : Proc(IDirect3DVolumeTexture9*, UInt32)
    get_device : Proc(IDirect3DVolumeTexture9*, IDirect3DDevice9*, HRESULT)
    set_private_data : Proc(IDirect3DVolumeTexture9*, Guid*, Void*, UInt32, UInt32, HRESULT)
    get_private_data : Proc(IDirect3DVolumeTexture9*, Guid*, Void*, UInt32*, HRESULT)
    free_private_data : Proc(IDirect3DVolumeTexture9*, Guid*, HRESULT)
    set_priority : Proc(IDirect3DVolumeTexture9*, UInt32, UInt32)
    get_priority : Proc(IDirect3DVolumeTexture9*, UInt32)
    pre_load : Proc(IDirect3DVolumeTexture9*, Void)
    get_type : Proc(IDirect3DVolumeTexture9*, D3DRESOURCETYPE)
    set_lod : Proc(IDirect3DVolumeTexture9*, UInt32, UInt32)
    get_lod : Proc(IDirect3DVolumeTexture9*, UInt32)
    get_level_count : Proc(IDirect3DVolumeTexture9*, UInt32)
    set_auto_gen_filter_type : Proc(IDirect3DVolumeTexture9*, D3DTEXTUREFILTERTYPE, HRESULT)
    get_auto_gen_filter_type : Proc(IDirect3DVolumeTexture9*, D3DTEXTUREFILTERTYPE)
    generate_mip_sub_levels : Proc(IDirect3DVolumeTexture9*, Void)
    get_level_desc : Proc(IDirect3DVolumeTexture9*, UInt32, D3DVOLUME_DESC*, HRESULT)
    get_volume_level : Proc(IDirect3DVolumeTexture9*, UInt32, IDirect3DVolume9*, HRESULT)
    lock_box : Proc(IDirect3DVolumeTexture9*, UInt32, D3DLOCKED_BOX*, D3DBOX*, UInt32, HRESULT)
    unlock_box : Proc(IDirect3DVolumeTexture9*, UInt32, HRESULT)
    add_dirty_box : Proc(IDirect3DVolumeTexture9*, D3DBOX*, HRESULT)
  end

  struct IDirect3DVolumeTexture9
    lpVtbl : IDirect3DVolumeTexture9VTbl*
  end

  struct IDirect3DCubeTexture9VTbl
    query_interface : Proc(IDirect3DCubeTexture9*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DCubeTexture9*, UInt32)
    release : Proc(IDirect3DCubeTexture9*, UInt32)
    get_device : Proc(IDirect3DCubeTexture9*, IDirect3DDevice9*, HRESULT)
    set_private_data : Proc(IDirect3DCubeTexture9*, Guid*, Void*, UInt32, UInt32, HRESULT)
    get_private_data : Proc(IDirect3DCubeTexture9*, Guid*, Void*, UInt32*, HRESULT)
    free_private_data : Proc(IDirect3DCubeTexture9*, Guid*, HRESULT)
    set_priority : Proc(IDirect3DCubeTexture9*, UInt32, UInt32)
    get_priority : Proc(IDirect3DCubeTexture9*, UInt32)
    pre_load : Proc(IDirect3DCubeTexture9*, Void)
    get_type : Proc(IDirect3DCubeTexture9*, D3DRESOURCETYPE)
    set_lod : Proc(IDirect3DCubeTexture9*, UInt32, UInt32)
    get_lod : Proc(IDirect3DCubeTexture9*, UInt32)
    get_level_count : Proc(IDirect3DCubeTexture9*, UInt32)
    set_auto_gen_filter_type : Proc(IDirect3DCubeTexture9*, D3DTEXTUREFILTERTYPE, HRESULT)
    get_auto_gen_filter_type : Proc(IDirect3DCubeTexture9*, D3DTEXTUREFILTERTYPE)
    generate_mip_sub_levels : Proc(IDirect3DCubeTexture9*, Void)
    get_level_desc : Proc(IDirect3DCubeTexture9*, UInt32, D3DSURFACE_DESC*, HRESULT)
    get_cube_map_surface : Proc(IDirect3DCubeTexture9*, D3DCUBEMAP_FACES, UInt32, IDirect3DSurface9*, HRESULT)
    lock_rect : Proc(IDirect3DCubeTexture9*, D3DCUBEMAP_FACES, UInt32, D3DLOCKED_RECT*, RECT*, UInt32, HRESULT)
    unlock_rect : Proc(IDirect3DCubeTexture9*, D3DCUBEMAP_FACES, UInt32, HRESULT)
    add_dirty_rect : Proc(IDirect3DCubeTexture9*, D3DCUBEMAP_FACES, RECT*, HRESULT)
  end

  struct IDirect3DCubeTexture9
    lpVtbl : IDirect3DCubeTexture9VTbl*
  end

  struct IDirect3DVertexBuffer9VTbl
    query_interface : Proc(IDirect3DVertexBuffer9*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DVertexBuffer9*, UInt32)
    release : Proc(IDirect3DVertexBuffer9*, UInt32)
    get_device : Proc(IDirect3DVertexBuffer9*, IDirect3DDevice9*, HRESULT)
    set_private_data : Proc(IDirect3DVertexBuffer9*, Guid*, Void*, UInt32, UInt32, HRESULT)
    get_private_data : Proc(IDirect3DVertexBuffer9*, Guid*, Void*, UInt32*, HRESULT)
    free_private_data : Proc(IDirect3DVertexBuffer9*, Guid*, HRESULT)
    set_priority : Proc(IDirect3DVertexBuffer9*, UInt32, UInt32)
    get_priority : Proc(IDirect3DVertexBuffer9*, UInt32)
    pre_load : Proc(IDirect3DVertexBuffer9*, Void)
    get_type : Proc(IDirect3DVertexBuffer9*, D3DRESOURCETYPE)
    lock : Proc(IDirect3DVertexBuffer9*, UInt32, UInt32, Void**, UInt32, HRESULT)
    unlock : Proc(IDirect3DVertexBuffer9*, HRESULT)
    get_desc : Proc(IDirect3DVertexBuffer9*, D3DVERTEXBUFFER_DESC*, HRESULT)
  end

  struct IDirect3DVertexBuffer9
    lpVtbl : IDirect3DVertexBuffer9VTbl*
  end

  struct IDirect3DIndexBuffer9VTbl
    query_interface : Proc(IDirect3DIndexBuffer9*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DIndexBuffer9*, UInt32)
    release : Proc(IDirect3DIndexBuffer9*, UInt32)
    get_device : Proc(IDirect3DIndexBuffer9*, IDirect3DDevice9*, HRESULT)
    set_private_data : Proc(IDirect3DIndexBuffer9*, Guid*, Void*, UInt32, UInt32, HRESULT)
    get_private_data : Proc(IDirect3DIndexBuffer9*, Guid*, Void*, UInt32*, HRESULT)
    free_private_data : Proc(IDirect3DIndexBuffer9*, Guid*, HRESULT)
    set_priority : Proc(IDirect3DIndexBuffer9*, UInt32, UInt32)
    get_priority : Proc(IDirect3DIndexBuffer9*, UInt32)
    pre_load : Proc(IDirect3DIndexBuffer9*, Void)
    get_type : Proc(IDirect3DIndexBuffer9*, D3DRESOURCETYPE)
    lock : Proc(IDirect3DIndexBuffer9*, UInt32, UInt32, Void**, UInt32, HRESULT)
    unlock : Proc(IDirect3DIndexBuffer9*, HRESULT)
    get_desc : Proc(IDirect3DIndexBuffer9*, D3DINDEXBUFFER_DESC*, HRESULT)
  end

  struct IDirect3DIndexBuffer9
    lpVtbl : IDirect3DIndexBuffer9VTbl*
  end

  struct IDirect3DSurface9VTbl
    query_interface : Proc(IDirect3DSurface9*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DSurface9*, UInt32)
    release : Proc(IDirect3DSurface9*, UInt32)
    get_device : Proc(IDirect3DSurface9*, IDirect3DDevice9*, HRESULT)
    set_private_data : Proc(IDirect3DSurface9*, Guid*, Void*, UInt32, UInt32, HRESULT)
    get_private_data : Proc(IDirect3DSurface9*, Guid*, Void*, UInt32*, HRESULT)
    free_private_data : Proc(IDirect3DSurface9*, Guid*, HRESULT)
    set_priority : Proc(IDirect3DSurface9*, UInt32, UInt32)
    get_priority : Proc(IDirect3DSurface9*, UInt32)
    pre_load : Proc(IDirect3DSurface9*, Void)
    get_type : Proc(IDirect3DSurface9*, D3DRESOURCETYPE)
    get_container : Proc(IDirect3DSurface9*, Guid*, Void**, HRESULT)
    get_desc : Proc(IDirect3DSurface9*, D3DSURFACE_DESC*, HRESULT)
    lock_rect : Proc(IDirect3DSurface9*, D3DLOCKED_RECT*, RECT*, UInt32, HRESULT)
    unlock_rect : Proc(IDirect3DSurface9*, HRESULT)
    get_dc : Proc(IDirect3DSurface9*, HDC*, HRESULT)
    release_dc : Proc(IDirect3DSurface9*, HDC, HRESULT)
  end

  struct IDirect3DSurface9
    lpVtbl : IDirect3DSurface9VTbl*
  end

  struct IDirect3DVolume9VTbl
    query_interface : Proc(IDirect3DVolume9*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DVolume9*, UInt32)
    release : Proc(IDirect3DVolume9*, UInt32)
    get_device : Proc(IDirect3DVolume9*, IDirect3DDevice9*, HRESULT)
    set_private_data : Proc(IDirect3DVolume9*, Guid*, Void*, UInt32, UInt32, HRESULT)
    get_private_data : Proc(IDirect3DVolume9*, Guid*, Void*, UInt32*, HRESULT)
    free_private_data : Proc(IDirect3DVolume9*, Guid*, HRESULT)
    get_container : Proc(IDirect3DVolume9*, Guid*, Void**, HRESULT)
    get_desc : Proc(IDirect3DVolume9*, D3DVOLUME_DESC*, HRESULT)
    lock_box : Proc(IDirect3DVolume9*, D3DLOCKED_BOX*, D3DBOX*, UInt32, HRESULT)
    unlock_box : Proc(IDirect3DVolume9*, HRESULT)
  end

  struct IDirect3DVolume9
    lpVtbl : IDirect3DVolume9VTbl*
  end

  struct IDirect3DQuery9VTbl
    query_interface : Proc(IDirect3DQuery9*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DQuery9*, UInt32)
    release : Proc(IDirect3DQuery9*, UInt32)
    get_device : Proc(IDirect3DQuery9*, IDirect3DDevice9*, HRESULT)
    get_type : Proc(IDirect3DQuery9*, D3DQUERYTYPE)
    get_data_size : Proc(IDirect3DQuery9*, UInt32)
    issue : Proc(IDirect3DQuery9*, UInt32, HRESULT)
    get_data : Proc(IDirect3DQuery9*, Void*, UInt32, UInt32, HRESULT)
  end

  struct IDirect3DQuery9
    lpVtbl : IDirect3DQuery9VTbl*
  end

  struct IDirect3D9ExVTbl
    query_interface : Proc(IDirect3D9Ex*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3D9Ex*, UInt32)
    release : Proc(IDirect3D9Ex*, UInt32)
    register_software_device : Proc(IDirect3D9Ex*, Void*, HRESULT)
    get_adapter_count : Proc(IDirect3D9Ex*, UInt32)
    get_adapter_identifier : Proc(IDirect3D9Ex*, UInt32, UInt32, D3DADAPTER_IDENTIFIER9*, HRESULT)
    get_adapter_mode_count : Proc(IDirect3D9Ex*, UInt32, D3DFORMAT, UInt32)
    enum_adapter_modes : Proc(IDirect3D9Ex*, UInt32, D3DFORMAT, UInt32, D3DDISPLAYMODE*, HRESULT)
    get_adapter_display_mode : Proc(IDirect3D9Ex*, UInt32, D3DDISPLAYMODE*, HRESULT)
    check_device_type : Proc(IDirect3D9Ex*, UInt32, D3DDEVTYPE, D3DFORMAT, D3DFORMAT, LibC::BOOL, HRESULT)
    check_device_format : Proc(IDirect3D9Ex*, UInt32, D3DDEVTYPE, D3DFORMAT, UInt32, D3DRESOURCETYPE, D3DFORMAT, HRESULT)
    check_device_multi_sample_type : Proc(IDirect3D9Ex*, UInt32, D3DDEVTYPE, D3DFORMAT, LibC::BOOL, D3DMULTISAMPLE_TYPE, UInt32*, HRESULT)
    check_depth_stencil_match : Proc(IDirect3D9Ex*, UInt32, D3DDEVTYPE, D3DFORMAT, D3DFORMAT, D3DFORMAT, HRESULT)
    check_device_format_conversion : Proc(IDirect3D9Ex*, UInt32, D3DDEVTYPE, D3DFORMAT, D3DFORMAT, HRESULT)
    get_device_caps : Proc(IDirect3D9Ex*, UInt32, D3DDEVTYPE, D3DCAPS9*, HRESULT)
    get_adapter_monitor : Proc(IDirect3D9Ex*, UInt32, HMONITOR)
    create_device : Proc(IDirect3D9Ex*, UInt32, D3DDEVTYPE, LibC::HANDLE, UInt32, D3DPRESENT_PARAMETERS*, IDirect3DDevice9*, HRESULT)
    get_adapter_mode_count_ex : Proc(IDirect3D9Ex*, UInt32, D3DDISPLAYMODEFILTER*, UInt32)
    enum_adapter_modes_ex : Proc(IDirect3D9Ex*, UInt32, D3DDISPLAYMODEFILTER*, UInt32, D3DDISPLAYMODEEX*, HRESULT)
    get_adapter_display_mode_ex : Proc(IDirect3D9Ex*, UInt32, D3DDISPLAYMODEEX*, D3DDISPLAYROTATION*, HRESULT)
    create_device_ex : Proc(IDirect3D9Ex*, UInt32, D3DDEVTYPE, LibC::HANDLE, UInt32, D3DPRESENT_PARAMETERS*, D3DDISPLAYMODEEX*, IDirect3DDevice9Ex*, HRESULT)
    get_adapter_luid : Proc(IDirect3D9Ex*, UInt32, LUID*, HRESULT)
  end

  struct IDirect3D9Ex
    lpVtbl : IDirect3D9ExVTbl*
  end

  struct IDirect3DDevice9ExVTbl
    query_interface : Proc(IDirect3DDevice9Ex*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DDevice9Ex*, UInt32)
    release : Proc(IDirect3DDevice9Ex*, UInt32)
    test_cooperative_level : Proc(IDirect3DDevice9Ex*, HRESULT)
    get_available_texture_mem : Proc(IDirect3DDevice9Ex*, UInt32)
    evict_managed_resources : Proc(IDirect3DDevice9Ex*, HRESULT)
    get_direct3_d : Proc(IDirect3DDevice9Ex*, IDirect3D9*, HRESULT)
    get_device_caps : Proc(IDirect3DDevice9Ex*, D3DCAPS9*, HRESULT)
    get_display_mode : Proc(IDirect3DDevice9Ex*, UInt32, D3DDISPLAYMODE*, HRESULT)
    get_creation_parameters : Proc(IDirect3DDevice9Ex*, D3DDEVICE_CREATION_PARAMETERS*, HRESULT)
    set_cursor_properties : Proc(IDirect3DDevice9Ex*, UInt32, UInt32, IDirect3DSurface9, HRESULT)
    set_cursor_position : Proc(IDirect3DDevice9Ex*, Int32, Int32, UInt32, Void)
    show_cursor : Proc(IDirect3DDevice9Ex*, LibC::BOOL, LibC::BOOL)
    create_additional_swap_chain : Proc(IDirect3DDevice9Ex*, D3DPRESENT_PARAMETERS*, IDirect3DSwapChain9*, HRESULT)
    get_swap_chain : Proc(IDirect3DDevice9Ex*, UInt32, IDirect3DSwapChain9*, HRESULT)
    get_number_of_swap_chains : Proc(IDirect3DDevice9Ex*, UInt32)
    reset : Proc(IDirect3DDevice9Ex*, D3DPRESENT_PARAMETERS*, HRESULT)
    present : Proc(IDirect3DDevice9Ex*, RECT*, RECT*, LibC::HANDLE, RGNDATA*, HRESULT)
    get_back_buffer : Proc(IDirect3DDevice9Ex*, UInt32, UInt32, D3DBACKBUFFER_TYPE, IDirect3DSurface9*, HRESULT)
    get_raster_status : Proc(IDirect3DDevice9Ex*, UInt32, D3DRASTER_STATUS*, HRESULT)
    set_dialog_box_mode : Proc(IDirect3DDevice9Ex*, LibC::BOOL, HRESULT)
    set_gamma_ramp : Proc(IDirect3DDevice9Ex*, UInt32, UInt32, D3DGAMMARAMP*, Void)
    get_gamma_ramp : Proc(IDirect3DDevice9Ex*, UInt32, D3DGAMMARAMP*, Void)
    create_texture : Proc(IDirect3DDevice9Ex*, UInt32, UInt32, UInt32, UInt32, D3DFORMAT, D3DPOOL, IDirect3DTexture9*, LibC::HANDLE*, HRESULT)
    create_volume_texture : Proc(IDirect3DDevice9Ex*, UInt32, UInt32, UInt32, UInt32, UInt32, D3DFORMAT, D3DPOOL, IDirect3DVolumeTexture9*, LibC::HANDLE*, HRESULT)
    create_cube_texture : Proc(IDirect3DDevice9Ex*, UInt32, UInt32, UInt32, D3DFORMAT, D3DPOOL, IDirect3DCubeTexture9*, LibC::HANDLE*, HRESULT)
    create_vertex_buffer : Proc(IDirect3DDevice9Ex*, UInt32, UInt32, UInt32, D3DPOOL, IDirect3DVertexBuffer9*, LibC::HANDLE*, HRESULT)
    create_index_buffer : Proc(IDirect3DDevice9Ex*, UInt32, UInt32, D3DFORMAT, D3DPOOL, IDirect3DIndexBuffer9*, LibC::HANDLE*, HRESULT)
    create_render_target : Proc(IDirect3DDevice9Ex*, UInt32, UInt32, D3DFORMAT, D3DMULTISAMPLE_TYPE, UInt32, LibC::BOOL, IDirect3DSurface9*, LibC::HANDLE*, HRESULT)
    create_depth_stencil_surface : Proc(IDirect3DDevice9Ex*, UInt32, UInt32, D3DFORMAT, D3DMULTISAMPLE_TYPE, UInt32, LibC::BOOL, IDirect3DSurface9*, LibC::HANDLE*, HRESULT)
    update_surface : Proc(IDirect3DDevice9Ex*, IDirect3DSurface9, RECT*, IDirect3DSurface9, POINT*, HRESULT)
    update_texture : Proc(IDirect3DDevice9Ex*, IDirect3DBaseTexture9, IDirect3DBaseTexture9, HRESULT)
    get_render_target_data : Proc(IDirect3DDevice9Ex*, IDirect3DSurface9, IDirect3DSurface9, HRESULT)
    get_front_buffer_data : Proc(IDirect3DDevice9Ex*, UInt32, IDirect3DSurface9, HRESULT)
    stretch_rect : Proc(IDirect3DDevice9Ex*, IDirect3DSurface9, RECT*, IDirect3DSurface9, RECT*, D3DTEXTUREFILTERTYPE, HRESULT)
    color_fill : Proc(IDirect3DDevice9Ex*, IDirect3DSurface9, RECT*, UInt32, HRESULT)
    create_offscreen_plain_surface : Proc(IDirect3DDevice9Ex*, UInt32, UInt32, D3DFORMAT, D3DPOOL, IDirect3DSurface9*, LibC::HANDLE*, HRESULT)
    set_render_target : Proc(IDirect3DDevice9Ex*, UInt32, IDirect3DSurface9, HRESULT)
    get_render_target : Proc(IDirect3DDevice9Ex*, UInt32, IDirect3DSurface9*, HRESULT)
    set_depth_stencil_surface : Proc(IDirect3DDevice9Ex*, IDirect3DSurface9, HRESULT)
    get_depth_stencil_surface : Proc(IDirect3DDevice9Ex*, IDirect3DSurface9*, HRESULT)
    begin_scene : Proc(IDirect3DDevice9Ex*, HRESULT)
    end_scene : Proc(IDirect3DDevice9Ex*, HRESULT)
    clear : Proc(IDirect3DDevice9Ex*, UInt32, D3DRECT*, UInt32, UInt32, Float32, UInt32, HRESULT)
    set_transform : Proc(IDirect3DDevice9Ex*, D3DTRANSFORMSTATETYPE, D3DMATRIX*, HRESULT)
    get_transform : Proc(IDirect3DDevice9Ex*, D3DTRANSFORMSTATETYPE, D3DMATRIX*, HRESULT)
    multiply_transform : Proc(IDirect3DDevice9Ex*, D3DTRANSFORMSTATETYPE, D3DMATRIX*, HRESULT)
    set_viewport : Proc(IDirect3DDevice9Ex*, D3DVIEWPORT9*, HRESULT)
    get_viewport : Proc(IDirect3DDevice9Ex*, D3DVIEWPORT9*, HRESULT)
    set_material : Proc(IDirect3DDevice9Ex*, D3DMATERIAL9*, HRESULT)
    get_material : Proc(IDirect3DDevice9Ex*, D3DMATERIAL9*, HRESULT)
    set_light : Proc(IDirect3DDevice9Ex*, UInt32, D3DLIGHT9*, HRESULT)
    get_light : Proc(IDirect3DDevice9Ex*, UInt32, D3DLIGHT9*, HRESULT)
    light_enable : Proc(IDirect3DDevice9Ex*, UInt32, LibC::BOOL, HRESULT)
    get_light_enable : Proc(IDirect3DDevice9Ex*, UInt32, LibC::BOOL*, HRESULT)
    set_clip_plane : Proc(IDirect3DDevice9Ex*, UInt32, Float32*, HRESULT)
    get_clip_plane : Proc(IDirect3DDevice9Ex*, UInt32, Float32*, HRESULT)
    set_render_state : Proc(IDirect3DDevice9Ex*, D3DRENDERSTATETYPE, UInt32, HRESULT)
    get_render_state : Proc(IDirect3DDevice9Ex*, D3DRENDERSTATETYPE, UInt32*, HRESULT)
    create_state_block : Proc(IDirect3DDevice9Ex*, D3DSTATEBLOCKTYPE, IDirect3DStateBlock9*, HRESULT)
    begin_state_block : Proc(IDirect3DDevice9Ex*, HRESULT)
    end_state_block : Proc(IDirect3DDevice9Ex*, IDirect3DStateBlock9*, HRESULT)
    set_clip_status : Proc(IDirect3DDevice9Ex*, D3DCLIPSTATUS9*, HRESULT)
    get_clip_status : Proc(IDirect3DDevice9Ex*, D3DCLIPSTATUS9*, HRESULT)
    get_texture : Proc(IDirect3DDevice9Ex*, UInt32, IDirect3DBaseTexture9*, HRESULT)
    set_texture : Proc(IDirect3DDevice9Ex*, UInt32, IDirect3DBaseTexture9, HRESULT)
    get_texture_stage_state : Proc(IDirect3DDevice9Ex*, UInt32, D3DTEXTURESTAGESTATETYPE, UInt32*, HRESULT)
    set_texture_stage_state : Proc(IDirect3DDevice9Ex*, UInt32, D3DTEXTURESTAGESTATETYPE, UInt32, HRESULT)
    get_sampler_state : Proc(IDirect3DDevice9Ex*, UInt32, D3DSAMPLERSTATETYPE, UInt32*, HRESULT)
    set_sampler_state : Proc(IDirect3DDevice9Ex*, UInt32, D3DSAMPLERSTATETYPE, UInt32, HRESULT)
    validate_device : Proc(IDirect3DDevice9Ex*, UInt32*, HRESULT)
    set_palette_entries : Proc(IDirect3DDevice9Ex*, UInt32, PALETTEENTRY*, HRESULT)
    get_palette_entries : Proc(IDirect3DDevice9Ex*, UInt32, PALETTEENTRY*, HRESULT)
    set_current_texture_palette : Proc(IDirect3DDevice9Ex*, UInt32, HRESULT)
    get_current_texture_palette : Proc(IDirect3DDevice9Ex*, UInt32*, HRESULT)
    set_scissor_rect : Proc(IDirect3DDevice9Ex*, RECT*, HRESULT)
    get_scissor_rect : Proc(IDirect3DDevice9Ex*, RECT*, HRESULT)
    set_software_vertex_processing : Proc(IDirect3DDevice9Ex*, LibC::BOOL, HRESULT)
    get_software_vertex_processing : Proc(IDirect3DDevice9Ex*, LibC::BOOL)
    set_n_patch_mode : Proc(IDirect3DDevice9Ex*, Float32, HRESULT)
    get_n_patch_mode : Proc(IDirect3DDevice9Ex*, Float32)
    draw_primitive : Proc(IDirect3DDevice9Ex*, D3DPRIMITIVETYPE, UInt32, UInt32, HRESULT)
    draw_indexed_primitive : Proc(IDirect3DDevice9Ex*, D3DPRIMITIVETYPE, Int32, UInt32, UInt32, UInt32, UInt32, HRESULT)
    draw_primitive_up : Proc(IDirect3DDevice9Ex*, D3DPRIMITIVETYPE, UInt32, Void*, UInt32, HRESULT)
    draw_indexed_primitive_up : Proc(IDirect3DDevice9Ex*, D3DPRIMITIVETYPE, UInt32, UInt32, UInt32, Void*, D3DFORMAT, Void*, UInt32, HRESULT)
    process_vertices : Proc(IDirect3DDevice9Ex*, UInt32, UInt32, UInt32, IDirect3DVertexBuffer9, IDirect3DVertexDeclaration9, UInt32, HRESULT)
    create_vertex_declaration : Proc(IDirect3DDevice9Ex*, D3DVERTEXELEMENT9*, IDirect3DVertexDeclaration9*, HRESULT)
    set_vertex_declaration : Proc(IDirect3DDevice9Ex*, IDirect3DVertexDeclaration9, HRESULT)
    get_vertex_declaration : Proc(IDirect3DDevice9Ex*, IDirect3DVertexDeclaration9*, HRESULT)
    set_fvf : Proc(IDirect3DDevice9Ex*, UInt32, HRESULT)
    get_fvf : Proc(IDirect3DDevice9Ex*, UInt32*, HRESULT)
    create_vertex_shader : Proc(IDirect3DDevice9Ex*, UInt32*, IDirect3DVertexShader9*, HRESULT)
    set_vertex_shader : Proc(IDirect3DDevice9Ex*, IDirect3DVertexShader9, HRESULT)
    get_vertex_shader : Proc(IDirect3DDevice9Ex*, IDirect3DVertexShader9*, HRESULT)
    set_vertex_shader_constant_f : Proc(IDirect3DDevice9Ex*, UInt32, Float32*, UInt32, HRESULT)
    get_vertex_shader_constant_f : Proc(IDirect3DDevice9Ex*, UInt32, Float32*, UInt32, HRESULT)
    set_vertex_shader_constant_i : Proc(IDirect3DDevice9Ex*, UInt32, Int32*, UInt32, HRESULT)
    get_vertex_shader_constant_i : Proc(IDirect3DDevice9Ex*, UInt32, Int32*, UInt32, HRESULT)
    set_vertex_shader_constant_b : Proc(IDirect3DDevice9Ex*, UInt32, LibC::BOOL*, UInt32, HRESULT)
    get_vertex_shader_constant_b : Proc(IDirect3DDevice9Ex*, UInt32, LibC::BOOL*, UInt32, HRESULT)
    set_stream_source : Proc(IDirect3DDevice9Ex*, UInt32, IDirect3DVertexBuffer9, UInt32, UInt32, HRESULT)
    get_stream_source : Proc(IDirect3DDevice9Ex*, UInt32, IDirect3DVertexBuffer9*, UInt32*, UInt32*, HRESULT)
    set_stream_source_freq : Proc(IDirect3DDevice9Ex*, UInt32, UInt32, HRESULT)
    get_stream_source_freq : Proc(IDirect3DDevice9Ex*, UInt32, UInt32*, HRESULT)
    set_indices : Proc(IDirect3DDevice9Ex*, IDirect3DIndexBuffer9, HRESULT)
    get_indices : Proc(IDirect3DDevice9Ex*, IDirect3DIndexBuffer9*, HRESULT)
    create_pixel_shader : Proc(IDirect3DDevice9Ex*, UInt32*, IDirect3DPixelShader9*, HRESULT)
    set_pixel_shader : Proc(IDirect3DDevice9Ex*, IDirect3DPixelShader9, HRESULT)
    get_pixel_shader : Proc(IDirect3DDevice9Ex*, IDirect3DPixelShader9*, HRESULT)
    set_pixel_shader_constant_f : Proc(IDirect3DDevice9Ex*, UInt32, Float32*, UInt32, HRESULT)
    get_pixel_shader_constant_f : Proc(IDirect3DDevice9Ex*, UInt32, Float32*, UInt32, HRESULT)
    set_pixel_shader_constant_i : Proc(IDirect3DDevice9Ex*, UInt32, Int32*, UInt32, HRESULT)
    get_pixel_shader_constant_i : Proc(IDirect3DDevice9Ex*, UInt32, Int32*, UInt32, HRESULT)
    set_pixel_shader_constant_b : Proc(IDirect3DDevice9Ex*, UInt32, LibC::BOOL*, UInt32, HRESULT)
    get_pixel_shader_constant_b : Proc(IDirect3DDevice9Ex*, UInt32, LibC::BOOL*, UInt32, HRESULT)
    draw_rect_patch : Proc(IDirect3DDevice9Ex*, UInt32, Float32*, D3DRECTPATCH_INFO*, HRESULT)
    draw_tri_patch : Proc(IDirect3DDevice9Ex*, UInt32, Float32*, D3DTRIPATCH_INFO*, HRESULT)
    delete_patch : Proc(IDirect3DDevice9Ex*, UInt32, HRESULT)
    create_query : Proc(IDirect3DDevice9Ex*, D3DQUERYTYPE, IDirect3DQuery9*, HRESULT)
    set_convolution_mono_kernel : Proc(IDirect3DDevice9Ex*, UInt32, UInt32, Float32*, Float32*, HRESULT)
    compose_rects : Proc(IDirect3DDevice9Ex*, IDirect3DSurface9, IDirect3DSurface9, IDirect3DVertexBuffer9, UInt32, IDirect3DVertexBuffer9, D3DCOMPOSERECTSOP, Int32, Int32, HRESULT)
    present_ex : Proc(IDirect3DDevice9Ex*, RECT*, RECT*, LibC::HANDLE, RGNDATA*, UInt32, HRESULT)
    get_gpu_thread_priority : Proc(IDirect3DDevice9Ex*, Int32*, HRESULT)
    set_gpu_thread_priority : Proc(IDirect3DDevice9Ex*, Int32, HRESULT)
    wait_for_v_blank : Proc(IDirect3DDevice9Ex*, UInt32, HRESULT)
    check_resource_residency : Proc(IDirect3DDevice9Ex*, IDirect3DResource9*, UInt32, HRESULT)
    set_maximum_frame_latency : Proc(IDirect3DDevice9Ex*, UInt32, HRESULT)
    get_maximum_frame_latency : Proc(IDirect3DDevice9Ex*, UInt32*, HRESULT)
    check_device_state : Proc(IDirect3DDevice9Ex*, LibC::HANDLE, HRESULT)
    create_render_target_ex : Proc(IDirect3DDevice9Ex*, UInt32, UInt32, D3DFORMAT, D3DMULTISAMPLE_TYPE, UInt32, LibC::BOOL, IDirect3DSurface9*, LibC::HANDLE*, UInt32, HRESULT)
    create_offscreen_plain_surface_ex : Proc(IDirect3DDevice9Ex*, UInt32, UInt32, D3DFORMAT, D3DPOOL, IDirect3DSurface9*, LibC::HANDLE*, UInt32, HRESULT)
    create_depth_stencil_surface_ex : Proc(IDirect3DDevice9Ex*, UInt32, UInt32, D3DFORMAT, D3DMULTISAMPLE_TYPE, UInt32, LibC::BOOL, IDirect3DSurface9*, LibC::HANDLE*, UInt32, HRESULT)
    reset_ex : Proc(IDirect3DDevice9Ex*, D3DPRESENT_PARAMETERS*, D3DDISPLAYMODEEX*, HRESULT)
    get_display_mode_ex : Proc(IDirect3DDevice9Ex*, UInt32, D3DDISPLAYMODEEX*, D3DDISPLAYROTATION*, HRESULT)
  end

  struct IDirect3DDevice9Ex
    lpVtbl : IDirect3DDevice9ExVTbl*
  end

  struct IDirect3DSwapChain9ExVTbl
    query_interface : Proc(IDirect3DSwapChain9Ex*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDirect3DSwapChain9Ex*, UInt32)
    release : Proc(IDirect3DSwapChain9Ex*, UInt32)
    present : Proc(IDirect3DSwapChain9Ex*, RECT*, RECT*, LibC::HANDLE, RGNDATA*, UInt32, HRESULT)
    get_front_buffer_data : Proc(IDirect3DSwapChain9Ex*, IDirect3DSurface9, HRESULT)
    get_back_buffer : Proc(IDirect3DSwapChain9Ex*, UInt32, D3DBACKBUFFER_TYPE, IDirect3DSurface9*, HRESULT)
    get_raster_status : Proc(IDirect3DSwapChain9Ex*, D3DRASTER_STATUS*, HRESULT)
    get_display_mode : Proc(IDirect3DSwapChain9Ex*, D3DDISPLAYMODE*, HRESULT)
    get_device : Proc(IDirect3DSwapChain9Ex*, IDirect3DDevice9*, HRESULT)
    get_present_parameters : Proc(IDirect3DSwapChain9Ex*, D3DPRESENT_PARAMETERS*, HRESULT)
    get_last_present_count : Proc(IDirect3DSwapChain9Ex*, UInt32*, HRESULT)
    get_present_stats : Proc(IDirect3DSwapChain9Ex*, D3DPRESENTSTATS*, HRESULT)
    get_display_mode_ex : Proc(IDirect3DSwapChain9Ex*, D3DDISPLAYMODEEX*, D3DDISPLAYROTATION*, HRESULT)
  end

  struct IDirect3DSwapChain9Ex
    lpVtbl : IDirect3DSwapChain9ExVTbl*
  end


  # Params # sdkversion : UInt32 [In]
  fun Direct3DCreate9(sdkversion : UInt32) : IDirect3D9

  # Params # col : UInt32 [In],wszname : LibC::LPWSTR [In]
  fun D3DPERF_BeginEvent(col : UInt32, wszname : LibC::LPWSTR) : Int32

  # Params # 
  fun D3DPERF_EndEvent : Int32

  # Params # col : UInt32 [In],wszname : LibC::LPWSTR [In]
  fun D3DPERF_SetMarker(col : UInt32, wszname : LibC::LPWSTR)

  # Params # col : UInt32 [In],wszname : LibC::LPWSTR [In]
  fun D3DPERF_SetRegion(col : UInt32, wszname : LibC::LPWSTR)

  # Params # 
  fun D3DPERF_QueryRepeatFrame : LibC::BOOL

  # Params # dwoptions : UInt32 [In]
  fun D3DPERF_SetOptions(dwoptions : UInt32)

  # Params # 
  fun D3DPERF_GetStatus : UInt32

  # Params # sdkversion : UInt32 [In],param1 : IDirect3D9Ex* [In]
  fun Direct3DCreate9Ex(sdkversion : UInt32, param1 : IDirect3D9Ex*) : HRESULT
end
