require "../foundation.cr"
require "../system/com.cr"

@[Link("delayimp")]
@[Link("user32")]
@[Link(ldflags: "/IGNORE:4199")]
lib LibWin32
  VDS_NF_VOLUME_ARRIVE = 4_u32
  VDS_NF_VOLUME_DEPART = 5_u32
  VDS_NF_VOLUME_MODIFY = 6_u32
  VDS_NF_VOLUME_REBUILDING_PROGRESS = 7_u32
  VDS_NF_PARTITION_ARRIVE = 11_u32
  VDS_NF_PARTITION_DEPART = 12_u32
  VDS_NF_PARTITION_MODIFY = 13_u32
  VDS_NF_SUB_SYSTEM_ARRIVE = 101_u32
  VDS_NF_SUB_SYSTEM_DEPART = 102_u32
  VDS_NF_PORTAL_ARRIVE = 123_u32
  VDS_NF_PORTAL_DEPART = 124_u32
  VDS_NF_PORTAL_MODIFY = 125_u32
  VDS_NF_TARGET_ARRIVE = 126_u32
  VDS_NF_TARGET_DEPART = 127_u32
  VDS_NF_TARGET_MODIFY = 128_u32
  VDS_NF_PORTAL_GROUP_ARRIVE = 129_u32
  VDS_NF_PORTAL_GROUP_DEPART = 130_u32
  VDS_NF_PORTAL_GROUP_MODIFY = 131_u32
  VDS_NF_SUB_SYSTEM_MODIFY = 151_u32
  VDS_NF_DRIVE_LETTER_FREE = 201_u32
  VDS_NF_DRIVE_LETTER_ASSIGN = 202_u32
  VDS_NF_MOUNT_POINTS_CHANGE = 205_u32
  VDS_NF_FILE_SYSTEM_SHRINKING_PROGRESS = 206_u32
  VDS_NF_SERVICE_OUT_OF_SYNC = 301_u32
  GPT_PARTITION_NAME_LENGTH = 36_u32
  VDS_HINT_FASTCRASHRECOVERYREQUIRED = 1_i32
  VDS_HINT_MOSTLYREADS = 2_i32
  VDS_HINT_OPTIMIZEFORSEQUENTIALREADS = 4_i32
  VDS_HINT_OPTIMIZEFORSEQUENTIALWRITES = 8_i32
  VDS_HINT_READBACKVERIFYENABLED = 16_i32
  VDS_HINT_REMAPENABLED = 32_i32
  VDS_HINT_WRITETHROUGHCACHINGENABLED = 64_i32
  VDS_HINT_HARDWARECHECKSUMENABLED = 128_i32
  VDS_HINT_ISYANKABLE = 256_i32
  VDS_HINT_ALLOCATEHOTSPARE = 512_i32
  VDS_HINT_BUSTYPE = 1024_i32
  VDS_HINT_USEMIRROREDCACHE = 2048_i32
  VDS_HINT_READCACHINGENABLED = 4096_i32
  VDS_HINT_WRITECACHINGENABLED = 8192_i32
  VDS_HINT_MEDIASCANENABLED = 16384_i32
  VDS_HINT_CONSISTENCYCHECKENABLED = 32768_i32
  VDS_REBUILD_PRIORITY_MIN = 0_u32
  VDS_REBUILD_PRIORITY_MAX = 16_u32
  VDS_POOL_ATTRIB_RAIDTYPE = 1_i32
  VDS_POOL_ATTRIB_BUSTYPE = 2_i32
  VDS_POOL_ATTRIB_ALLOW_SPINDOWN = 4_i32
  VDS_POOL_ATTRIB_THIN_PROVISION = 8_i32
  VDS_POOL_ATTRIB_NO_SINGLE_POF = 16_i32
  VDS_POOL_ATTRIB_DATA_RDNCY_MAX = 32_i32
  VDS_POOL_ATTRIB_DATA_RDNCY_MIN = 64_i32
  VDS_POOL_ATTRIB_DATA_RDNCY_DEF = 128_i32
  VDS_POOL_ATTRIB_PKG_RDNCY_MAX = 256_i32
  VDS_POOL_ATTRIB_PKG_RDNCY_MIN = 512_i32
  VDS_POOL_ATTRIB_PKG_RDNCY_DEF = 1024_i32
  VDS_POOL_ATTRIB_STRIPE_SIZE = 2048_i32
  VDS_POOL_ATTRIB_STRIPE_SIZE_MAX = 4096_i32
  VDS_POOL_ATTRIB_STRIPE_SIZE_MIN = 8192_i32
  VDS_POOL_ATTRIB_STRIPE_SIZE_DEF = 16384_i32
  VDS_POOL_ATTRIB_NUM_CLMNS = 32768_i32
  VDS_POOL_ATTRIB_NUM_CLMNS_MAX = 65536_i32
  VDS_POOL_ATTRIB_NUM_CLMNS_MIN = 131072_i32
  VDS_POOL_ATTRIB_NUM_CLMNS_DEF = 262144_i32
  VDS_POOL_ATTRIB_DATA_AVL_HINT = 524288_i32
  VDS_POOL_ATTRIB_ACCS_RNDM_HINT = 1048576_i32
  VDS_POOL_ATTRIB_ACCS_DIR_HINT = 2097152_i32
  VDS_POOL_ATTRIB_ACCS_SIZE_HINT = 4194304_i32
  VDS_POOL_ATTRIB_ACCS_LTNCY_HINT = 8388608_i32
  VDS_POOL_ATTRIB_ACCS_BDW_WT_HINT = 16777216_i32
  VDS_POOL_ATTRIB_STOR_COST_HINT = 33554432_i32
  VDS_POOL_ATTRIB_STOR_EFFCY_HINT = 67108864_i32
  VDS_POOL_ATTRIB_CUSTOM_ATTRIB = 134217728_i32
  VDS_ATTACH_VIRTUAL_DISK_FLAG_USE_FILE_ACL = 1_u32
  CLSID_VdsLoader = "9c38ed61-d565-4728-aeee-c80952f0ecde"
  CLSID_VdsService = "7d1933cb-86f6-4a98-8628-01be94c9a575"
  MAX_FS_NAME_SIZE = 8_u32
  MAX_FS_FORMAT_SUPPORT_NAME_SIZE = 32_u32
  MAX_FS_ALLOWED_CLUSTER_SIZES_SIZE = 32_u32
  VER_VDS_LUN_INFORMATION = 1_u32
  VDS_E_NOT_SUPPORTED = -2147212288_i32
  VDS_E_INITIALIZED_FAILED = -2147212287_i32
  VDS_E_INITIALIZE_NOT_CALLED = -2147212286_i32
  VDS_E_ALREADY_REGISTERED = -2147212285_i32
  VDS_E_ANOTHER_CALL_IN_PROGRESS = -2147212284_i32
  VDS_E_OBJECT_NOT_FOUND = -2147212283_i32
  VDS_E_INVALID_SPACE = -2147212282_i32
  VDS_E_PARTITION_LIMIT_REACHED = -2147212281_i32
  VDS_E_PARTITION_NOT_EMPTY = -2147212280_i32
  VDS_E_OPERATION_PENDING = -2147212279_i32
  VDS_E_OPERATION_DENIED = -2147212278_i32
  VDS_E_OBJECT_DELETED = -2147212277_i32
  VDS_E_CANCEL_TOO_LATE = -2147212276_i32
  VDS_E_OPERATION_CANCELED = -2147212275_i32
  VDS_E_CANNOT_EXTEND = -2147212274_i32
  VDS_E_NOT_ENOUGH_SPACE = -2147212273_i32
  VDS_E_NOT_ENOUGH_DRIVE = -2147212272_i32
  VDS_E_BAD_COOKIE = -2147212271_i32
  VDS_E_NO_MEDIA = -2147212270_i32
  VDS_E_DEVICE_IN_USE = -2147212269_i32
  VDS_E_DISK_NOT_EMPTY = -2147212268_i32
  VDS_E_INVALID_OPERATION = -2147212267_i32
  VDS_E_PATH_NOT_FOUND = -2147212266_i32
  VDS_E_DISK_NOT_INITIALIZED = -2147212265_i32
  VDS_E_NOT_AN_UNALLOCATED_DISK = -2147212264_i32
  VDS_E_UNRECOVERABLE_ERROR = -2147212263_i32
  VDS_S_DISK_PARTIALLY_CLEANED = 271386_i32
  VDS_E_DMADMIN_SERVICE_CONNECTION_FAILED = -2147212261_i32
  VDS_E_PROVIDER_INITIALIZATION_FAILED = -2147212260_i32
  VDS_E_OBJECT_EXISTS = -2147212259_i32
  VDS_E_NO_DISKS_FOUND = -2147212258_i32
  VDS_E_PROVIDER_CACHE_CORRUPT = -2147212257_i32
  VDS_E_DMADMIN_METHOD_CALL_FAILED = -2147212256_i32
  VDS_S_PROVIDER_ERROR_LOADING_CACHE = 271393_i32
  VDS_E_PROVIDER_VOL_DEVICE_NAME_NOT_FOUND = -2147212254_i32
  VDS_E_PROVIDER_VOL_OPEN = -2147212253_i32
  VDS_E_DMADMIN_CORRUPT_NOTIFICATION = -2147212252_i32
  VDS_E_INCOMPATIBLE_FILE_SYSTEM = -2147212251_i32
  VDS_E_INCOMPATIBLE_MEDIA = -2147212250_i32
  VDS_E_ACCESS_DENIED = -2147212249_i32
  VDS_E_MEDIA_WRITE_PROTECTED = -2147212248_i32
  VDS_E_BAD_LABEL = -2147212247_i32
  VDS_E_CANT_QUICK_FORMAT = -2147212246_i32
  VDS_E_IO_ERROR = -2147212245_i32
  VDS_E_VOLUME_TOO_SMALL = -2147212244_i32
  VDS_E_VOLUME_TOO_BIG = -2147212243_i32
  VDS_E_CLUSTER_SIZE_TOO_SMALL = -2147212242_i32
  VDS_E_CLUSTER_SIZE_TOO_BIG = -2147212241_i32
  VDS_E_CLUSTER_COUNT_BEYOND_32BITS = -2147212240_i32
  VDS_E_OBJECT_STATUS_FAILED = -2147212239_i32
  VDS_E_VOLUME_INCOMPLETE = -2147212238_i32
  VDS_E_EXTENT_SIZE_LESS_THAN_MIN = -2147212237_i32
  VDS_S_UPDATE_BOOTFILE_FAILED = 271412_i32
  VDS_S_BOOT_PARTITION_NUMBER_CHANGE = 271414_i32
  VDS_E_BOOT_PARTITION_NUMBER_CHANGE = -2147212234_i32
  VDS_E_NO_FREE_SPACE = -2147212233_i32
  VDS_E_ACTIVE_PARTITION = -2147212232_i32
  VDS_E_PARTITION_OF_UNKNOWN_TYPE = -2147212231_i32
  VDS_E_LEGACY_VOLUME_FORMAT = -2147212230_i32
  VDS_E_NON_CONTIGUOUS_DATA_PARTITIONS = -2147212229_i32
  VDS_E_MIGRATE_OPEN_VOLUME = -2147212228_i32
  VDS_E_VOLUME_NOT_ONLINE = -2147212227_i32
  VDS_E_VOLUME_NOT_HEALTHY = -2147212226_i32
  VDS_E_VOLUME_SPANS_DISKS = -2147212225_i32
  VDS_E_REQUIRES_CONTIGUOUS_DISK_SPACE = -2147212224_i32
  VDS_E_BAD_PROVIDER_DATA = -2147212223_i32
  VDS_E_PROVIDER_FAILURE = -2147212222_i32
  VDS_S_VOLUME_COMPRESS_FAILED = 271427_i32
  VDS_E_PACK_OFFLINE = -2147212220_i32
  VDS_E_VOLUME_NOT_A_MIRROR = -2147212219_i32
  VDS_E_NO_EXTENTS_FOR_VOLUME = -2147212218_i32
  VDS_E_DISK_NOT_LOADED_TO_CACHE = -2147212217_i32
  VDS_E_INTERNAL_ERROR = -2147212216_i32
  VDS_S_ACCESS_PATH_NOT_DELETED = 279108_i32
  VDS_E_PROVIDER_TYPE_NOT_SUPPORTED = -2147212214_i32
  VDS_E_DISK_NOT_ONLINE = -2147212213_i32
  VDS_E_DISK_IN_USE_BY_VOLUME = -2147212212_i32
  VDS_S_IN_PROGRESS = 271437_i32
  VDS_E_ASYNC_OBJECT_FAILURE = -2147212210_i32
  VDS_E_VOLUME_NOT_MOUNTED = -2147212209_i32
  VDS_E_PACK_NOT_FOUND = -2147212208_i32
  VDS_E_IMPORT_SET_INCOMPLETE = -2147212207_i32
  VDS_E_DISK_NOT_IMPORTED = -2147212206_i32
  VDS_E_OBJECT_OUT_OF_SYNC = -2147212205_i32
  VDS_E_MISSING_DISK = -2147212204_i32
  VDS_E_DISK_PNP_REG_CORRUPT = -2147212203_i32
  VDS_E_LBN_REMAP_ENABLED_FLAG = -2147212202_i32
  VDS_E_NO_DRIVELETTER_FLAG = -2147212201_i32
  VDS_E_REVERT_ON_CLOSE = -2147212200_i32
  VDS_E_REVERT_ON_CLOSE_SET = -2147212199_i32
  VDS_E_IA64_BOOT_MIRRORED_TO_MBR = -2147212198_i32
  VDS_S_IA64_BOOT_MIRRORED_TO_MBR = 271450_i32
  VDS_S_UNABLE_TO_GET_GPT_ATTRIBUTES = 271451_i32
  VDS_E_VOLUME_TEMPORARILY_DISMOUNTED = -2147212196_i32
  VDS_E_VOLUME_PERMANENTLY_DISMOUNTED = -2147212195_i32
  VDS_E_VOLUME_HAS_PATH = -2147212194_i32
  VDS_E_TIMEOUT = -2147212193_i32
  VDS_E_REPAIR_VOLUMESTATE = -2147212192_i32
  VDS_E_LDM_TIMEOUT = -2147212191_i32
  VDS_E_REVERT_ON_CLOSE_MISMATCH = -2147212190_i32
  VDS_E_RETRY = -2147212189_i32
  VDS_E_ONLINE_PACK_EXISTS = -2147212188_i32
  VDS_S_EXTEND_FILE_SYSTEM_FAILED = 271461_i32
  VDS_E_EXTEND_FILE_SYSTEM_FAILED = -2147212186_i32
  VDS_S_MBR_BOOT_MIRRORED_TO_GPT = 271463_i32
  VDS_E_MAX_USABLE_MBR = -2147212184_i32
  VDS_S_GPT_BOOT_MIRRORED_TO_MBR = -2147212183_i32
  VDS_E_NO_SOFTWARE_PROVIDERS_LOADED = -2147212032_i32
  VDS_E_DISK_NOT_MISSING = -2147212031_i32
  VDS_E_NO_VOLUME_LAYOUT = -2147212030_i32
  VDS_E_CORRUPT_VOLUME_INFO = -2147212029_i32
  VDS_E_INVALID_ENUMERATOR = -2147212028_i32
  VDS_E_DRIVER_INTERNAL_ERROR = -2147212027_i32
  VDS_E_VOLUME_INVALID_NAME = -2147212025_i32
  VDS_S_DISK_IS_MISSING = 271624_i32
  VDS_E_CORRUPT_PARTITION_INFO = -2147212023_i32
  VDS_S_NONCONFORMANT_PARTITION_INFO = 271626_i32
  VDS_E_CORRUPT_EXTENT_INFO = -2147212021_i32
  VDS_E_DUP_EMPTY_PACK_GUID = -2147212020_i32
  VDS_E_DRIVER_NO_PACK_NAME = -2147212019_i32
  VDS_S_SYSTEM_PARTITION = 271630_i32
  VDS_E_BAD_PNP_MESSAGE = -2147212017_i32
  VDS_E_NO_PNP_DISK_ARRIVE = -2147212016_i32
  VDS_E_NO_PNP_VOLUME_ARRIVE = -2147212015_i32
  VDS_E_NO_PNP_DISK_REMOVE = -2147212014_i32
  VDS_E_NO_PNP_VOLUME_REMOVE = -2147212013_i32
  VDS_E_PROVIDER_EXITING = -2147212012_i32
  VDS_E_EXTENT_EXCEEDS_DISK_FREE_SPACE = -2147212011_i32
  VDS_E_MEMBER_SIZE_INVALID = -2147212010_i32
  VDS_S_NO_NOTIFICATION = 271639_i32
  VDS_S_DEFAULT_PLEX_MEMBER_IDS = 271640_i32
  VDS_E_INVALID_DISK = -2147212007_i32
  VDS_E_INVALID_PACK = -2147212006_i32
  VDS_E_VOLUME_ON_DISK = -2147212005_i32
  VDS_E_DRIVER_INVALID_PARAM = -2147212004_i32
  VDS_E_TARGET_PACK_NOT_EMPTY = -2147212003_i32
  VDS_E_CANNOT_SHRINK = -2147212002_i32
  VDS_E_MULTIPLE_PACKS = -2147212001_i32
  VDS_E_PACK_ONLINE = -2147212000_i32
  VDS_E_INVALID_PLEX_COUNT = -2147211999_i32
  VDS_E_INVALID_MEMBER_COUNT = -2147211998_i32
  VDS_E_INVALID_PLEX_ORDER = -2147211997_i32
  VDS_E_INVALID_MEMBER_ORDER = -2147211996_i32
  VDS_E_INVALID_STRIPE_SIZE = -2147211995_i32
  VDS_E_INVALID_DISK_COUNT = -2147211994_i32
  VDS_E_INVALID_EXTENT_COUNT = -2147211993_i32
  VDS_E_SOURCE_IS_TARGET_PACK = -2147211992_i32
  VDS_E_VOLUME_DISK_COUNT_MAX_EXCEEDED = -2147211991_i32
  VDS_E_CORRUPT_NOTIFICATION_INFO = -2147211990_i32
  VDS_E_INVALID_PLEX_GUID = -2147211988_i32
  VDS_E_DISK_NOT_FOUND_IN_PACK = -2147211987_i32
  VDS_E_DUPLICATE_DISK = -2147211986_i32
  VDS_E_LAST_VALID_DISK = -2147211985_i32
  VDS_E_INVALID_SECTOR_SIZE = -2147211984_i32
  VDS_E_ONE_EXTENT_PER_DISK = -2147211983_i32
  VDS_E_INVALID_BLOCK_SIZE = -2147211982_i32
  VDS_E_PLEX_SIZE_INVALID = -2147211981_i32
  VDS_E_NO_EXTENTS_FOR_PLEX = -2147211980_i32
  VDS_E_INVALID_PLEX_TYPE = -2147211979_i32
  VDS_E_INVALID_PLEX_BLOCK_SIZE = -2147211978_i32
  VDS_E_NO_HEALTHY_DISKS = -2147211977_i32
  VDS_E_CONFIG_LIMIT = -2147211976_i32
  VDS_E_DISK_CONFIGURATION_CORRUPTED = -2147211975_i32
  VDS_E_DISK_CONFIGURATION_NOT_IN_SYNC = -2147211974_i32
  VDS_E_DISK_CONFIGURATION_UPDATE_FAILED = -2147211973_i32
  VDS_E_DISK_DYNAMIC = -2147211972_i32
  VDS_E_DRIVER_OBJECT_NOT_FOUND = -2147211971_i32
  VDS_E_PARTITION_NOT_CYLINDER_ALIGNED = -2147211970_i32
  VDS_E_DISK_LAYOUT_PARTITIONS_TOO_SMALL = -2147211969_i32
  VDS_E_DISK_IO_FAILING = -2147211968_i32
  VDS_E_DYNAMIC_DISKS_NOT_SUPPORTED = -2147211967_i32
  VDS_E_FAULT_TOLERANT_DISKS_NOT_SUPPORTED = -2147211966_i32
  VDS_E_GPT_ATTRIBUTES_INVALID = -2147211965_i32
  VDS_E_MEMBER_IS_HEALTHY = -2147211964_i32
  VDS_E_MEMBER_REGENERATING = -2147211963_i32
  VDS_E_PACK_NAME_INVALID = -2147211962_i32
  VDS_E_PLEX_IS_HEALTHY = -2147211961_i32
  VDS_E_PLEX_LAST_ACTIVE = -2147211960_i32
  VDS_E_PLEX_MISSING = -2147211959_i32
  VDS_E_MEMBER_MISSING = -2147211958_i32
  VDS_E_PLEX_REGENERATING = -2147211957_i32
  VDS_E_UNEXPECTED_DISK_LAYOUT_CHANGE = -2147211955_i32
  VDS_E_INVALID_VOLUME_LENGTH = -2147211954_i32
  VDS_E_VOLUME_LENGTH_NOT_SECTOR_SIZE_MULTIPLE = -2147211953_i32
  VDS_E_VOLUME_NOT_RETAINED = -2147211952_i32
  VDS_E_VOLUME_RETAINED = -2147211951_i32
  VDS_E_ALIGN_BEYOND_FIRST_CYLINDER = -2147211949_i32
  VDS_E_ALIGN_NOT_SECTOR_SIZE_MULTIPLE = -2147211948_i32
  VDS_E_ALIGN_NOT_ZERO = -2147211947_i32
  VDS_E_CACHE_CORRUPT = -2147211946_i32
  VDS_E_CANNOT_CLEAR_VOLUME_FLAG = -2147211945_i32
  VDS_E_DISK_BEING_CLEANED = -2147211944_i32
  VDS_E_DISK_NOT_CONVERTIBLE = -2147211943_i32
  VDS_E_DISK_REMOVEABLE = -2147211942_i32
  VDS_E_DISK_REMOVEABLE_NOT_EMPTY = -2147211941_i32
  VDS_E_DRIVE_LETTER_NOT_FREE = -2147211940_i32
  VDS_E_EXTEND_MULTIPLE_DISKS_NOT_SUPPORTED = -2147211939_i32
  VDS_E_INVALID_DRIVE_LETTER = -2147211938_i32
  VDS_E_INVALID_DRIVE_LETTER_COUNT = -2147211937_i32
  VDS_E_INVALID_FS_FLAG = -2147211936_i32
  VDS_E_INVALID_FS_TYPE = -2147211935_i32
  VDS_E_INVALID_OBJECT_TYPE = -2147211934_i32
  VDS_E_INVALID_PARTITION_LAYOUT = -2147211933_i32
  VDS_E_INVALID_PARTITION_STYLE = -2147211932_i32
  VDS_E_INVALID_PARTITION_TYPE = -2147211931_i32
  VDS_E_INVALID_PROVIDER_CLSID = -2147211930_i32
  VDS_E_INVALID_PROVIDER_ID = -2147211929_i32
  VDS_E_INVALID_PROVIDER_NAME = -2147211928_i32
  VDS_E_INVALID_PROVIDER_TYPE = -2147211927_i32
  VDS_E_INVALID_PROVIDER_VERSION_GUID = -2147211926_i32
  VDS_E_INVALID_PROVIDER_VERSION_STRING = -2147211925_i32
  VDS_E_INVALID_QUERY_PROVIDER_FLAG = -2147211924_i32
  VDS_E_INVALID_SERVICE_FLAG = -2147211923_i32
  VDS_E_INVALID_VOLUME_FLAG = -2147211922_i32
  VDS_E_PARTITION_NOT_OEM = -2147211921_i32
  VDS_E_PARTITION_PROTECTED = -2147211920_i32
  VDS_E_PARTITION_STYLE_MISMATCH = -2147211919_i32
  VDS_E_PROVIDER_INTERNAL_ERROR = -2147211918_i32
  VDS_E_SHRINK_SIZE_LESS_THAN_MIN = -2147211917_i32
  VDS_E_SHRINK_SIZE_TOO_BIG = -2147211916_i32
  VDS_E_UNRECOVERABLE_PROVIDER_ERROR = -2147211915_i32
  VDS_E_VOLUME_HIDDEN = -2147211914_i32
  VDS_S_DISMOUNT_FAILED = 271735_i32
  VDS_S_REMOUNT_FAILED = 271736_i32
  VDS_E_FLAG_ALREADY_SET = -2147211911_i32
  VDS_S_RESYNC_NOTIFICATION_TASK_FAILED = 271738_i32
  VDS_E_DISTINCT_VOLUME = -2147211909_i32
  VDS_E_VOLUME_NOT_FOUND_IN_PACK = -2147211908_i32
  VDS_E_PARTITION_NON_DATA = -2147211907_i32
  VDS_E_CRITICAL_PLEX = -2147211906_i32
  VDS_E_VOLUME_SYNCHRONIZING = -2147211905_i32
  VDS_E_VOLUME_REGENERATING = -2147211904_i32
  VDS_S_VSS_FLUSH_AND_HOLD_WRITES = 271745_i32
  VDS_S_VSS_RELEASE_WRITES = 271746_i32
  VDS_S_FS_LOCK = 271747_i32
  VDS_E_READONLY = -2147211900_i32
  VDS_E_INVALID_VOLUME_TYPE = -2147211899_i32
  VDS_E_BAD_BOOT_DISK = -2147211898_i32
  VDS_E_LOG_UPDATE = -2147211897_i32
  VDS_E_VOLUME_MIRRORED = -2147211896_i32
  VDS_E_VOLUME_SIMPLE_SPANNED = -2147211895_i32
  VDS_E_NO_VALID_LOG_COPIES = -2147211894_i32
  VDS_S_PLEX_NOT_LOADED_TO_CACHE = 271755_i32
  VDS_E_PLEX_NOT_LOADED_TO_CACHE = -2147211893_i32
  VDS_E_PARTITION_MSR = -2147211892_i32
  VDS_E_PARTITION_LDM = -2147211891_i32
  VDS_S_WINPE_BOOTENTRY = 271758_i32
  VDS_E_ALIGN_NOT_A_POWER_OF_TWO = -2147211889_i32
  VDS_E_ALIGN_IS_ZERO = -2147211888_i32
  VDS_E_SHRINK_IN_PROGRESS = -2147211887_i32
  VDS_E_CANT_INVALIDATE_FVE = -2147211886_i32
  VDS_E_FS_NOT_DETERMINED = -2147211885_i32
  VDS_E_DISK_NOT_OFFLINE = -2147211883_i32
  VDS_E_FAILED_TO_ONLINE_DISK = -2147211882_i32
  VDS_E_FAILED_TO_OFFLINE_DISK = -2147211881_i32
  VDS_E_BAD_REVISION_NUMBER = -2147211880_i32
  VDS_E_SHRINK_USER_CANCELLED = -2147211879_i32
  VDS_E_SHRINK_DIRTY_VOLUME = -2147211878_i32
  VDS_S_NAME_TRUNCATED = 272128_i32
  VDS_E_NAME_NOT_UNIQUE = -2147211519_i32
  VDS_S_STATUSES_INCOMPLETELY_SET = 272130_i32
  VDS_E_ADDRESSES_INCOMPLETELY_SET = -2147211517_i32
  VDS_E_SECURITY_INCOMPLETELY_SET = -2147211515_i32
  VDS_E_TARGET_SPECIFIC_NOT_SUPPORTED = -2147211514_i32
  VDS_E_INITIATOR_SPECIFIC_NOT_SUPPORTED = -2147211513_i32
  VDS_E_ISCSI_LOGIN_FAILED = -2147211512_i32
  VDS_E_ISCSI_LOGOUT_FAILED = -2147211511_i32
  VDS_E_ISCSI_SESSION_NOT_FOUND = -2147211510_i32
  VDS_E_ASSOCIATED_LUNS_EXIST = -2147211509_i32
  VDS_E_ASSOCIATED_PORTALS_EXIST = -2147211508_i32
  VDS_E_NO_DISCOVERY_DOMAIN = -2147211507_i32
  VDS_E_MULTIPLE_DISCOVERY_DOMAINS = -2147211506_i32
  VDS_E_NO_DISK_PATHNAME = -2147211505_i32
  VDS_E_ISCSI_LOGOUT_INCOMPLETE = -2147211504_i32
  VDS_E_NO_VOLUME_PATHNAME = -2147211503_i32
  VDS_E_PROVIDER_CACHE_OUTOFSYNC = -2147211502_i32
  VDS_E_NO_IMPORT_TARGET = -2147211501_i32
  VDS_S_ALREADY_EXISTS = 272148_i32
  VDS_S_PROPERTIES_INCOMPLETE = 272149_i32
  VDS_S_ISCSI_SESSION_NOT_FOUND_PERSISTENT_LOGIN_REMOVED = 272384_i32
  VDS_S_ISCSI_PERSISTENT_LOGIN_MAY_NOT_BE_REMOVED = 272385_i32
  VDS_S_ISCSI_LOGIN_ALREAD_EXISTS = 272386_i32
  VDS_E_UNABLE_TO_FIND_BOOT_DISK = -2147211261_i32
  VDS_E_INCORRECT_BOOT_VOLUME_EXTENT_INFO = -2147211260_i32
  VDS_E_GET_SAN_POLICY = -2147211259_i32
  VDS_E_SET_SAN_POLICY = -2147211258_i32
  VDS_E_BOOT_DISK = -2147211257_i32
  VDS_S_DISK_MOUNT_FAILED = 272392_i32
  VDS_S_DISK_DISMOUNT_FAILED = 272393_i32
  VDS_E_DISK_IS_OFFLINE = -2147211254_i32
  VDS_E_DISK_IS_READ_ONLY = -2147211253_i32
  VDS_E_PAGEFILE_DISK = -2147211252_i32
  VDS_E_HIBERNATION_FILE_DISK = -2147211251_i32
  VDS_E_CRASHDUMP_DISK = -2147211250_i32
  VDS_E_UNABLE_TO_FIND_SYSTEM_DISK = -2147211249_i32
  VDS_E_INCORRECT_SYSTEM_VOLUME_EXTENT_INFO = -2147211248_i32
  VDS_E_SYSTEM_DISK = -2147211247_i32
  VDS_E_VOLUME_SHRINK_FVE_LOCKED = -2147211246_i32
  VDS_E_VOLUME_SHRINK_FVE_CORRUPT = -2147211245_i32
  VDS_E_VOLUME_SHRINK_FVE_RECOVERY = -2147211244_i32
  VDS_E_VOLUME_SHRINK_FVE = -2147211243_i32
  VDS_E_SHRINK_OVER_DATA = -2147211242_i32
  VDS_E_INVALID_SHRINK_SIZE = -2147211241_i32
  VDS_E_LUN_DISK_MISSING = -2147211240_i32
  VDS_E_LUN_DISK_FAILED = -2147211239_i32
  VDS_E_LUN_DISK_NOT_READY = -2147211238_i32
  VDS_E_LUN_DISK_NO_MEDIA = -2147211237_i32
  VDS_E_LUN_NOT_READY = -2147211236_i32
  VDS_E_LUN_OFFLINE = -2147211235_i32
  VDS_E_LUN_FAILED = -2147211234_i32
  VDS_E_VOLUME_EXTEND_FVE_LOCKED = -2147211233_i32
  VDS_E_VOLUME_EXTEND_FVE_CORRUPT = -2147211232_i32
  VDS_E_VOLUME_EXTEND_FVE_RECOVERY = -2147211231_i32
  VDS_E_VOLUME_EXTEND_FVE = -2147211230_i32
  VDS_E_SECTOR_SIZE_ERROR = -2147211229_i32
  VDS_E_INITIATOR_ADAPTER_NOT_FOUND = -2147211008_i32
  VDS_E_TARGET_PORTAL_NOT_FOUND = -2147211007_i32
  VDS_E_INVALID_PORT_PATH = -2147211006_i32
  VDS_E_INVALID_ISCSI_TARGET_NAME = -2147211005_i32
  VDS_E_SET_TUNNEL_MODE_OUTER_ADDRESS = -2147211004_i32
  VDS_E_ISCSI_GET_IKE_INFO = -2147211003_i32
  VDS_E_ISCSI_SET_IKE_INFO = -2147211002_i32
  VDS_E_SUBSYSTEM_ID_IS_NULL = -2147211001_i32
  VDS_E_ISCSI_INITIATOR_NODE_NAME = -2147211000_i32
  VDS_E_ISCSI_GROUP_PRESHARE_KEY = -2147210999_i32
  VDS_E_ISCSI_CHAP_SECRET = -2147210998_i32
  VDS_E_INVALID_IP_ADDRESS = -2147210997_i32
  VDS_E_REBOOT_REQUIRED = -2147210996_i32
  VDS_E_VOLUME_GUID_PATHNAME_NOT_ALLOWED = -2147210995_i32
  VDS_E_BOOT_PAGEFILE_DRIVE_LETTER = -2147210994_i32
  VDS_E_DELETE_WITH_CRITICAL = -2147210993_i32
  VDS_E_CLEAN_WITH_DATA = -2147210992_i32
  VDS_E_CLEAN_WITH_OEM = -2147210991_i32
  VDS_E_CLEAN_WITH_CRITICAL = -2147210990_i32
  VDS_E_FORMAT_CRITICAL = -2147210989_i32
  VDS_E_NTFS_FORMAT_NOT_SUPPORTED = -2147210988_i32
  VDS_E_FAT32_FORMAT_NOT_SUPPORTED = -2147210987_i32
  VDS_E_FAT_FORMAT_NOT_SUPPORTED = -2147210986_i32
  VDS_E_FORMAT_NOT_SUPPORTED = -2147210985_i32
  VDS_E_COMPRESSION_NOT_SUPPORTED = -2147210984_i32
  VDS_E_VDISK_NOT_OPEN = -2147210983_i32
  VDS_E_VDISK_INVALID_OP_STATE = -2147210982_i32
  VDS_E_INVALID_PATH = -2147210981_i32
  VDS_E_INVALID_ISCSI_PATH = -2147210980_i32
  VDS_E_SHRINK_LUN_NOT_UNMASKED = -2147210979_i32
  VDS_E_LUN_DISK_READ_ONLY = -2147210978_i32
  VDS_E_LUN_UPDATE_DISK = -2147210977_i32
  VDS_E_LUN_DYNAMIC = -2147210976_i32
  VDS_E_LUN_DYNAMIC_OFFLINE = -2147210975_i32
  VDS_E_LUN_SHRINK_GPT_HEADER = -2147210974_i32
  VDS_E_MIRROR_NOT_SUPPORTED = -2147210973_i32
  VDS_E_RAID5_NOT_SUPPORTED = -2147210972_i32
  VDS_E_DISK_NOT_CONVERTIBLE_SIZE = -2147210971_i32
  VDS_E_OFFLINE_NOT_SUPPORTED = -2147210970_i32
  VDS_E_VDISK_PATHNAME_INVALID = -2147210969_i32
  VDS_E_EXTEND_TOO_MANY_CLUSTERS = -2147210968_i32
  VDS_E_EXTEND_UNKNOWN_FILESYSTEM = -2147210967_i32
  VDS_E_SHRINK_UNKNOWN_FILESYSTEM = -2147210966_i32
  VDS_E_VD_DISK_NOT_OPEN = -2147210965_i32
  VDS_E_VD_DISK_IS_EXPANDING = -2147210964_i32
  VDS_E_VD_DISK_IS_COMPACTING = -2147210963_i32
  VDS_E_VD_DISK_IS_MERGING = -2147210962_i32
  VDS_E_VD_IS_ATTACHED = -2147210961_i32
  VDS_E_VD_DISK_ALREADY_OPEN = -2147210960_i32
  VDS_E_VD_DISK_ALREADY_EXPANDING = -2147210959_i32
  VDS_E_VD_ALREADY_COMPACTING = -2147210958_i32
  VDS_E_VD_ALREADY_MERGING = -2147210957_i32
  VDS_E_VD_ALREADY_ATTACHED = -2147210956_i32
  VDS_E_VD_ALREADY_DETACHED = -2147210955_i32
  VDS_E_VD_NOT_ATTACHED_READONLY = -2147210954_i32
  VDS_E_VD_IS_BEING_ATTACHED = -2147210953_i32
  VDS_E_VD_IS_BEING_DETACHED = -2147210952_i32
  VDS_E_NO_POOL = -2147210752_i32
  VDS_E_NO_POOL_CREATED = -2147210751_i32
  VDS_E_NO_MAINTENANCE_MODE = -2147210750_i32
  VDS_E_BLOCK_CLUSTERED = -2147210749_i32
  VDS_E_DISK_HAS_BANDS = -2147210748_i32
  VDS_E_INVALID_STATE = -2147210747_i32
  VDS_E_REFS_FORMAT_NOT_SUPPORTED = -2147210746_i32
  VDS_E_DELETE_WITH_BOOTBACKING = -2147210745_i32
  VDS_E_FORMAT_WITH_BOOTBACKING = -2147210744_i32
  VDS_E_CLEAN_WITH_BOOTBACKING = -2147210743_i32
  VDS_E_SHRINK_EXTEND_UNALIGNED = -2147210496_i32


  enum VDS_NF_PACK : UInt32
    VDS_NF_PACK_ARRIVE = 1
    VDS_NF_PACK_DEPART = 2
    VDS_NF_PACK_MODIFY = 3
  end

  enum VDS_NF_FILE_SYSTEM : UInt32
    VDS_NF_FILE_SYSTEM_MODIFY = 203
    VDS_NF_FILE_SYSTEM_FORMAT_PROGRESS = 204
  end

  enum VDS_NF_CONTROLLER : UInt32
    VDS_NF_CONTROLLER_ARRIVE = 103
    VDS_NF_CONTROLLER_DEPART = 104
    VDS_NF_CONTROLLER_MODIFY = 350
    VDS_NF_CONTROLLER_REMOVED = 351
  end

  enum VDS_NF_DRIVE : UInt32
    VDS_NF_DRIVE_ARRIVE = 105
    VDS_NF_DRIVE_DEPART = 106
    VDS_NF_DRIVE_MODIFY = 107
    VDS_NF_DRIVE_REMOVED = 354
  end

  enum VDS_NF_PORT : UInt32
    VDS_NF_PORT_ARRIVE = 121
    VDS_NF_PORT_DEPART = 122
    VDS_NF_PORT_MODIFY = 352
    VDS_NF_PORT_REMOVED = 353
  end

  enum VDS_NF_LUN : UInt32
    VDS_NF_LUN_ARRIVE = 108
    VDS_NF_LUN_DEPART = 109
    VDS_NF_LUN_MODIFY = 110
  end

  enum VDS_NF_DISK : UInt32
    VDS_NF_DISK_ARRIVE = 8
    VDS_NF_DISK_DEPART = 9
    VDS_NF_DISK_MODIFY = 10
  end

  enum VDS_STORAGE_IDENTIFIER_CODE_SET : Int32
    VDSStorageIdCodeSetReserved = 0
    VDSStorageIdCodeSetBinary = 1
    VDSStorageIdCodeSetAscii = 2
    VDSStorageIdCodeSetUtf8 = 3
  end

  enum VDS_STORAGE_IDENTIFIER_TYPE : Int32
    VDSStorageIdTypeVendorSpecific = 0
    VDSStorageIdTypeVendorId = 1
    VDSStorageIdTypeEUI64 = 2
    VDSStorageIdTypeFCPHName = 3
    VDSStorageIdTypePortRelative = 4
    VDSStorageIdTypeTargetPortGroup = 5
    VDSStorageIdTypeLogicalUnitGroup = 6
    VDSStorageIdTypeMD5LogicalUnitIdentifier = 7
    VDSStorageIdTypeScsiNameString = 8
  end

  enum VDS_STORAGE_BUS_TYPE : Int32
    VDSBusTypeUnknown = 0
    VDSBusTypeScsi = 1
    VDSBusTypeAtapi = 2
    VDSBusTypeAta = 3
    VDSBusType1394 = 4
    VDSBusTypeSsa = 5
    VDSBusTypeFibre = 6
    VDSBusTypeUsb = 7
    VDSBusTypeRAID = 8
    VDSBusTypeiScsi = 9
    VDSBusTypeSas = 10
    VDSBusTypeSata = 11
    VDSBusTypeSd = 12
    VDSBusTypeMmc = 13
    VDSBusTypeMax = 14
    VDSBusTypeVirtual = 14
    VDSBusTypeFileBackedVirtual = 15
    VDSBusTypeSpaces = 16
    VDSBusTypeNVMe = 17
    VDSBusTypeScm = 18
    VDSBusTypeUfs = 19
    VDSBusTypeMaxReserved = 127
  end

  enum VDS_INTERCONNECT_ADDRESS_TYPE : Int32
    VDS_IA_UNKNOWN = 0
    VDS_IA_FCFS = 1
    VDS_IA_FCPH = 2
    VDS_IA_FCPH3 = 3
    VDS_IA_MAC = 4
    VDS_IA_SCSI = 5
  end

  enum VDS_OBJECT_TYPE : Int32
    VDS_OT_UNKNOWN = 0
    VDS_OT_PROVIDER = 1
    VDS_OT_PACK = 10
    VDS_OT_VOLUME = 11
    VDS_OT_VOLUME_PLEX = 12
    VDS_OT_DISK = 13
    VDS_OT_SUB_SYSTEM = 30
    VDS_OT_CONTROLLER = 31
    VDS_OT_DRIVE = 32
    VDS_OT_LUN = 33
    VDS_OT_LUN_PLEX = 34
    VDS_OT_PORT = 35
    VDS_OT_PORTAL = 36
    VDS_OT_TARGET = 37
    VDS_OT_PORTAL_GROUP = 38
    VDS_OT_STORAGE_POOL = 39
    VDS_OT_HBAPORT = 90
    VDS_OT_INIT_ADAPTER = 91
    VDS_OT_INIT_PORTAL = 92
    VDS_OT_ASYNC = 100
    VDS_OT_ENUM = 101
    VDS_OT_VDISK = 200
    VDS_OT_OPEN_VDISK = 201
  end

  enum VDS_PROVIDER_TYPE : Int32
    VDS_PT_UNKNOWN = 0
    VDS_PT_SOFTWARE = 1
    VDS_PT_HARDWARE = 2
    VDS_PT_VIRTUALDISK = 3
    VDS_PT_MAX = 4
  end

  enum VDS_PROVIDER_FLAG : Int32
    VDS_PF_DYNAMIC = 1
    VDS_PF_INTERNAL_HARDWARE_PROVIDER = 2
    VDS_PF_ONE_DISK_ONLY_PER_PACK = 4
    VDS_PF_ONE_PACK_ONLINE_ONLY = 8
    VDS_PF_VOLUME_SPACE_MUST_BE_CONTIGUOUS = 16
    VDS_PF_SUPPORT_DYNAMIC = -2147483648
    VDS_PF_SUPPORT_FAULT_TOLERANT = 1073741824
    VDS_PF_SUPPORT_DYNAMIC_1394 = 536870912
    VDS_PF_SUPPORT_MIRROR = 32
    VDS_PF_SUPPORT_RAID5 = 64
  end

  enum VDS_RECOVER_ACTION : Int32
    VDS_RA_UNKNOWN = 0
    VDS_RA_REFRESH = 1
    VDS_RA_RESTART = 2
  end

  enum VDS_NOTIFICATION_TARGET_TYPE : Int32
    VDS_NTT_UNKNOWN = 0
    VDS_NTT_PACK = 10
    VDS_NTT_VOLUME = 11
    VDS_NTT_DISK = 13
    VDS_NTT_PARTITION = 60
    VDS_NTT_DRIVE_LETTER = 61
    VDS_NTT_FILE_SYSTEM = 62
    VDS_NTT_MOUNT_POINT = 63
    VDS_NTT_SUB_SYSTEM = 30
    VDS_NTT_CONTROLLER = 31
    VDS_NTT_DRIVE = 32
    VDS_NTT_LUN = 33
    VDS_NTT_PORT = 35
    VDS_NTT_PORTAL = 36
    VDS_NTT_TARGET = 37
    VDS_NTT_PORTAL_GROUP = 38
    VDS_NTT_SERVICE = 200
  end

  enum VDS_ASYNC_OUTPUT_TYPE : Int32
    VDS_ASYNCOUT_UNKNOWN = 0
    VDS_ASYNCOUT_CREATEVOLUME = 1
    VDS_ASYNCOUT_EXTENDVOLUME = 2
    VDS_ASYNCOUT_SHRINKVOLUME = 3
    VDS_ASYNCOUT_ADDVOLUMEPLEX = 4
    VDS_ASYNCOUT_BREAKVOLUMEPLEX = 5
    VDS_ASYNCOUT_REMOVEVOLUMEPLEX = 6
    VDS_ASYNCOUT_REPAIRVOLUMEPLEX = 7
    VDS_ASYNCOUT_RECOVERPACK = 8
    VDS_ASYNCOUT_REPLACEDISK = 9
    VDS_ASYNCOUT_CREATEPARTITION = 10
    VDS_ASYNCOUT_CLEAN = 11
    VDS_ASYNCOUT_CREATELUN = 50
    VDS_ASYNCOUT_ADDLUNPLEX = 52
    VDS_ASYNCOUT_REMOVELUNPLEX = 53
    VDS_ASYNCOUT_EXTENDLUN = 54
    VDS_ASYNCOUT_SHRINKLUN = 55
    VDS_ASYNCOUT_RECOVERLUN = 56
    VDS_ASYNCOUT_LOGINTOTARGET = 60
    VDS_ASYNCOUT_LOGOUTFROMTARGET = 61
    VDS_ASYNCOUT_CREATETARGET = 62
    VDS_ASYNCOUT_CREATEPORTALGROUP = 63
    VDS_ASYNCOUT_DELETETARGET = 64
    VDS_ASYNCOUT_ADDPORTAL = 65
    VDS_ASYNCOUT_REMOVEPORTAL = 66
    VDS_ASYNCOUT_DELETEPORTALGROUP = 67
    VDS_ASYNCOUT_FORMAT = 101
    VDS_ASYNCOUT_CREATE_VDISK = 200
    VDS_ASYNCOUT_ATTACH_VDISK = 201
    VDS_ASYNCOUT_COMPACT_VDISK = 202
    VDS_ASYNCOUT_MERGE_VDISK = 203
    VDS_ASYNCOUT_EXPAND_VDISK = 204
  end

  enum VDS_IPADDRESS_TYPE : Int32
    VDS_IPT_TEXT = 0
    VDS_IPT_IPV4 = 1
    VDS_IPT_IPV6 = 2
    VDS_IPT_EMPTY = 3
  end

  enum VDS_HEALTH : Int32
    VDS_H_UNKNOWN = 0
    VDS_H_HEALTHY = 1
    VDS_H_REBUILDING = 2
    VDS_H_STALE = 3
    VDS_H_FAILING = 4
    VDS_H_FAILING_REDUNDANCY = 5
    VDS_H_FAILED_REDUNDANCY = 6
    VDS_H_FAILED_REDUNDANCY_FAILING = 7
    VDS_H_FAILED = 8
    VDS_H_REPLACED = 9
    VDS_H_PENDING_FAILURE = 10
    VDS_H_DEGRADED = 11
  end

  enum VDS_TRANSITION_STATE : Int32
    VDS_TS_UNKNOWN = 0
    VDS_TS_STABLE = 1
    VDS_TS_EXTENDING = 2
    VDS_TS_SHRINKING = 3
    VDS_TS_RECONFIGING = 4
    VDS_TS_RESTRIPING = 5
  end

  enum VDS_FILE_SYSTEM_TYPE : Int32
    VDS_FST_UNKNOWN = 0
    VDS_FST_RAW = 1
    VDS_FST_FAT = 2
    VDS_FST_FAT32 = 3
    VDS_FST_NTFS = 4
    VDS_FST_CDFS = 5
    VDS_FST_UDF = 6
    VDS_FST_EXFAT = 7
    VDS_FST_CSVFS = 8
    VDS_FST_REFS = 9
  end

  enum VDS_HBAPORT_TYPE : Int32
    VDS_HPT_UNKNOWN = 1
    VDS_HPT_OTHER = 2
    VDS_HPT_NOTPRESENT = 3
    VDS_HPT_NPORT = 5
    VDS_HPT_NLPORT = 6
    VDS_HPT_FLPORT = 7
    VDS_HPT_FPORT = 8
    VDS_HPT_EPORT = 9
    VDS_HPT_GPORT = 10
    VDS_HPT_LPORT = 20
    VDS_HPT_PTP = 21
  end

  enum VDS_HBAPORT_STATUS : Int32
    VDS_HPS_UNKNOWN = 1
    VDS_HPS_ONLINE = 2
    VDS_HPS_OFFLINE = 3
    VDS_HPS_BYPASSED = 4
    VDS_HPS_DIAGNOSTICS = 5
    VDS_HPS_LINKDOWN = 6
    VDS_HPS_ERROR = 7
    VDS_HPS_LOOPBACK = 8
  end

  enum VDS_HBAPORT_SPEED_FLAG : Int32
    VDS_HSF_UNKNOWN = 0
    VDS_HSF_1GBIT = 1
    VDS_HSF_2GBIT = 2
    VDS_HSF_10GBIT = 4
    VDS_HSF_4GBIT = 8
    VDS_HSF_NOT_NEGOTIATED = 32768
  end

  enum VDS_PATH_STATUS : Int32
    VDS_MPS_UNKNOWN = 0
    VDS_MPS_ONLINE = 1
    VDS_MPS_FAILED = 5
    VDS_MPS_STANDBY = 7
  end

  enum VDS_LOADBALANCE_POLICY_ENUM : Int32
    VDS_LBP_UNKNOWN = 0
    VDS_LBP_FAILOVER = 1
    VDS_LBP_ROUND_ROBIN = 2
    VDS_LBP_ROUND_ROBIN_WITH_SUBSET = 3
    VDS_LBP_DYN_LEAST_QUEUE_DEPTH = 4
    VDS_LBP_WEIGHTED_PATHS = 5
    VDS_LBP_LEAST_BLOCKS = 6
    VDS_LBP_VENDOR_SPECIFIC = 7
  end

  enum VDS_PROVIDER_LBSUPPORT_FLAG : Int32
    VDS_LBF_FAILOVER = 1
    VDS_LBF_ROUND_ROBIN = 2
    VDS_LBF_ROUND_ROBIN_WITH_SUBSET = 4
    VDS_LBF_DYN_LEAST_QUEUE_DEPTH = 8
    VDS_LBF_WEIGHTED_PATHS = 16
    VDS_LBF_LEAST_BLOCKS = 32
    VDS_LBF_VENDOR_SPECIFIC = 64
  end

  enum VDS_VERSION_SUPPORT_FLAG : Int32
    VDS_VSF_1_0 = 1
    VDS_VSF_1_1 = 2
    VDS_VSF_2_0 = 4
    VDS_VSF_2_1 = 8
    VDS_VSF_3_0 = 16
  end

  enum VDS_HWPROVIDER_TYPE : Int32
    VDS_HWT_UNKNOWN = 0
    VDS_HWT_PCI_RAID = 1
    VDS_HWT_FIBRE_CHANNEL = 2
    VDS_HWT_ISCSI = 3
    VDS_HWT_SAS = 4
    VDS_HWT_HYBRID = 5
  end

  enum VDS_ISCSI_LOGIN_TYPE : Int32
    VDS_ILT_MANUAL = 0
    VDS_ILT_PERSISTENT = 1
    VDS_ILT_BOOT = 2
  end

  enum VDS_ISCSI_AUTH_TYPE : Int32
    VDS_IAT_NONE = 0
    VDS_IAT_CHAP = 1
    VDS_IAT_MUTUAL_CHAP = 2
  end

  enum VDS_ISCSI_IPSEC_FLAG : Int32
    VDS_IIF_VALID = 1
    VDS_IIF_IKE = 2
    VDS_IIF_MAIN_MODE = 4
    VDS_IIF_AGGRESSIVE_MODE = 8
    VDS_IIF_PFS_ENABLE = 16
    VDS_IIF_TRANSPORT_MODE_PREFERRED = 32
    VDS_IIF_TUNNEL_MODE_PREFERRED = 64
  end

  enum VDS_ISCSI_LOGIN_FLAG : Int32
    VDS_ILF_REQUIRE_IPSEC = 1
    VDS_ILF_MULTIPATH_ENABLED = 2
  end

  enum VDS_SUB_SYSTEM_STATUS : Int32
    VDS_SSS_UNKNOWN = 0
    VDS_SSS_ONLINE = 1
    VDS_SSS_NOT_READY = 2
    VDS_SSS_OFFLINE = 4
    VDS_SSS_FAILED = 5
    VDS_SSS_PARTIALLY_MANAGED = 9
  end

  enum VDS_SUB_SYSTEM_FLAG : Int32
    VDS_SF_LUN_MASKING_CAPABLE = 1
    VDS_SF_LUN_PLEXING_CAPABLE = 2
    VDS_SF_LUN_REMAPPING_CAPABLE = 4
    VDS_SF_DRIVE_EXTENT_CAPABLE = 8
    VDS_SF_HARDWARE_CHECKSUM_CAPABLE = 16
    VDS_SF_RADIUS_CAPABLE = 32
    VDS_SF_READ_BACK_VERIFY_CAPABLE = 64
    VDS_SF_WRITE_THROUGH_CACHING_CAPABLE = 128
    VDS_SF_SUPPORTS_FAULT_TOLERANT_LUNS = 512
    VDS_SF_SUPPORTS_NON_FAULT_TOLERANT_LUNS = 1024
    VDS_SF_SUPPORTS_SIMPLE_LUNS = 2048
    VDS_SF_SUPPORTS_SPAN_LUNS = 4096
    VDS_SF_SUPPORTS_STRIPE_LUNS = 8192
    VDS_SF_SUPPORTS_MIRROR_LUNS = 16384
    VDS_SF_SUPPORTS_PARITY_LUNS = 32768
    VDS_SF_SUPPORTS_AUTH_CHAP = 65536
    VDS_SF_SUPPORTS_AUTH_MUTUAL_CHAP = 131072
    VDS_SF_SUPPORTS_SIMPLE_TARGET_CONFIG = 262144
    VDS_SF_SUPPORTS_LUN_NUMBER = 524288
    VDS_SF_SUPPORTS_MIRRORED_CACHE = 1048576
    VDS_SF_READ_CACHING_CAPABLE = 2097152
    VDS_SF_WRITE_CACHING_CAPABLE = 4194304
    VDS_SF_MEDIA_SCAN_CAPABLE = 8388608
    VDS_SF_CONSISTENCY_CHECK_CAPABLE = 16777216
  end

  enum VDS_SUB_SYSTEM_SUPPORTED_RAID_TYPE_FLAG : Int32
    VDS_SF_SUPPORTS_RAID2_LUNS = 1
    VDS_SF_SUPPORTS_RAID3_LUNS = 2
    VDS_SF_SUPPORTS_RAID4_LUNS = 4
    VDS_SF_SUPPORTS_RAID5_LUNS = 8
    VDS_SF_SUPPORTS_RAID6_LUNS = 16
    VDS_SF_SUPPORTS_RAID01_LUNS = 32
    VDS_SF_SUPPORTS_RAID03_LUNS = 64
    VDS_SF_SUPPORTS_RAID05_LUNS = 128
    VDS_SF_SUPPORTS_RAID10_LUNS = 256
    VDS_SF_SUPPORTS_RAID15_LUNS = 512
    VDS_SF_SUPPORTS_RAID30_LUNS = 1024
    VDS_SF_SUPPORTS_RAID50_LUNS = 2048
    VDS_SF_SUPPORTS_RAID51_LUNS = 4096
    VDS_SF_SUPPORTS_RAID53_LUNS = 8192
    VDS_SF_SUPPORTS_RAID60_LUNS = 16384
    VDS_SF_SUPPORTS_RAID61_LUNS = 32768
  end

  enum VDS_INTERCONNECT_FLAG : Int32
    VDS_ITF_PCI_RAID = 1
    VDS_ITF_FIBRE_CHANNEL = 2
    VDS_ITF_ISCSI = 4
    VDS_ITF_SAS = 8
  end

  enum VDS_CONTROLLER_STATUS : Int32
    VDS_CS_UNKNOWN = 0
    VDS_CS_ONLINE = 1
    VDS_CS_NOT_READY = 2
    VDS_CS_OFFLINE = 4
    VDS_CS_FAILED = 5
    VDS_CS_REMOVED = 8
  end

  enum VDS_PORT_STATUS : Int32
    VDS_PRS_UNKNOWN = 0
    VDS_PRS_ONLINE = 1
    VDS_PRS_NOT_READY = 2
    VDS_PRS_OFFLINE = 4
    VDS_PRS_FAILED = 5
    VDS_PRS_REMOVED = 8
  end

  enum VDS_DRIVE_STATUS : Int32
    VDS_DRS_UNKNOWN = 0
    VDS_DRS_ONLINE = 1
    VDS_DRS_NOT_READY = 2
    VDS_DRS_OFFLINE = 4
    VDS_DRS_FAILED = 5
    VDS_DRS_REMOVED = 8
  end

  enum VDS_DRIVE_FLAG : Int32
    VDS_DRF_HOTSPARE = 1
    VDS_DRF_ASSIGNED = 2
    VDS_DRF_UNASSIGNED = 4
    VDS_DRF_HOTSPARE_IN_USE = 8
    VDS_DRF_HOTSPARE_STANDBY = 16
  end

  enum VDS_LUN_TYPE : Int32
    VDS_LT_UNKNOWN = 0
    VDS_LT_DEFAULT = 1
    VDS_LT_FAULT_TOLERANT = 2
    VDS_LT_NON_FAULT_TOLERANT = 3
    VDS_LT_SIMPLE = 10
    VDS_LT_SPAN = 11
    VDS_LT_STRIPE = 12
    VDS_LT_MIRROR = 13
    VDS_LT_PARITY = 14
    VDS_LT_RAID2 = 15
    VDS_LT_RAID3 = 16
    VDS_LT_RAID4 = 17
    VDS_LT_RAID5 = 18
    VDS_LT_RAID6 = 19
    VDS_LT_RAID01 = 20
    VDS_LT_RAID03 = 21
    VDS_LT_RAID05 = 22
    VDS_LT_RAID10 = 23
    VDS_LT_RAID15 = 24
    VDS_LT_RAID30 = 25
    VDS_LT_RAID50 = 26
    VDS_LT_RAID51 = 27
    VDS_LT_RAID53 = 28
    VDS_LT_RAID60 = 29
    VDS_LT_RAID61 = 30
  end

  enum VDS_LUN_STATUS : Int32
    VDS_LS_UNKNOWN = 0
    VDS_LS_ONLINE = 1
    VDS_LS_NOT_READY = 2
    VDS_LS_OFFLINE = 4
    VDS_LS_FAILED = 5
  end

  enum VDS_LUN_FLAG : Int32
    VDS_LF_LBN_REMAP_ENABLED = 1
    VDS_LF_READ_BACK_VERIFY_ENABLED = 2
    VDS_LF_WRITE_THROUGH_CACHING_ENABLED = 4
    VDS_LF_HARDWARE_CHECKSUM_ENABLED = 8
    VDS_LF_READ_CACHE_ENABLED = 16
    VDS_LF_WRITE_CACHE_ENABLED = 32
    VDS_LF_MEDIA_SCAN_ENABLED = 64
    VDS_LF_CONSISTENCY_CHECK_ENABLED = 128
    VDS_LF_SNAPSHOT = 256
  end

  enum VDS_LUN_PLEX_TYPE : Int32
    VDS_LPT_UNKNOWN = 0
    VDS_LPT_SIMPLE = 10
    VDS_LPT_SPAN = 11
    VDS_LPT_STRIPE = 12
    VDS_LPT_PARITY = 14
    VDS_LPT_RAID2 = 15
    VDS_LPT_RAID3 = 16
    VDS_LPT_RAID4 = 17
    VDS_LPT_RAID5 = 18
    VDS_LPT_RAID6 = 19
    VDS_LPT_RAID03 = 21
    VDS_LPT_RAID05 = 22
    VDS_LPT_RAID10 = 23
    VDS_LPT_RAID15 = 24
    VDS_LPT_RAID30 = 25
    VDS_LPT_RAID50 = 26
    VDS_LPT_RAID53 = 28
    VDS_LPT_RAID60 = 29
  end

  enum VDS_LUN_PLEX_STATUS : Int32
    VDS_LPS_UNKNOWN = 0
    VDS_LPS_ONLINE = 1
    VDS_LPS_NOT_READY = 2
    VDS_LPS_OFFLINE = 4
    VDS_LPS_FAILED = 5
  end

  enum VDS_LUN_PLEX_FLAG : Int32
    VDS_LPF_LBN_REMAP_ENABLED = 1
  end

  enum VDS_ISCSI_PORTAL_STATUS : Int32
    VDS_IPS_UNKNOWN = 0
    VDS_IPS_ONLINE = 1
    VDS_IPS_NOT_READY = 2
    VDS_IPS_OFFLINE = 4
    VDS_IPS_FAILED = 5
  end

  enum VDS_STORAGE_POOL_STATUS : Int32
    VDS_SPS_UNKNOWN = 0
    VDS_SPS_ONLINE = 1
    VDS_SPS_NOT_READY = 2
    VDS_SPS_OFFLINE = 4
  end

  enum VDS_STORAGE_POOL_TYPE : Int32
    VDS_SPT_UNKNOWN = 0
    VDS_SPT_PRIMORDIAL = 1
    VDS_SPT_CONCRETE = 2
  end

  enum VDS_MAINTENANCE_OPERATION : Int32
    BlinkLight = 1
    BeepAlarm = 2
    SpinDown = 3
    SpinUp = 4
    Ping = 5
  end

  enum VDS_RAID_TYPE : Int32
    VDS_RT_UNKNOWN = 0
    VDS_RT_RAID0 = 10
    VDS_RT_RAID1 = 11
    VDS_RT_RAID2 = 12
    VDS_RT_RAID3 = 13
    VDS_RT_RAID4 = 14
    VDS_RT_RAID5 = 15
    VDS_RT_RAID6 = 16
    VDS_RT_RAID01 = 17
    VDS_RT_RAID03 = 18
    VDS_RT_RAID05 = 19
    VDS_RT_RAID10 = 20
    VDS_RT_RAID15 = 21
    VDS_RT_RAID30 = 22
    VDS_RT_RAID50 = 23
    VDS_RT_RAID51 = 24
    VDS_RT_RAID53 = 25
    VDS_RT_RAID60 = 26
    VDS_RT_RAID61 = 27
  end

  union VDS_NOTIFICATION_Anonymous_e__Union
    pack : VDS_PACK_NOTIFICATION
    disk : VDS_DISK_NOTIFICATION
    volume : VDS_VOLUME_NOTIFICATION
    partition : VDS_PARTITION_NOTIFICATION
    letter : VDS_DRIVE_LETTER_NOTIFICATION
    file_system : VDS_FILE_SYSTEM_NOTIFICATION
    mount_point : VDS_MOUNT_POINT_NOTIFICATION
    sub_system : VDS_SUB_SYSTEM_NOTIFICATION
    controller : VDS_CONTROLLER_NOTIFICATION
    drive : VDS_DRIVE_NOTIFICATION
    lun : VDS_LUN_NOTIFICATION
    port : VDS_PORT_NOTIFICATION
    portal : VDS_PORTAL_NOTIFICATION
    target : VDS_TARGET_NOTIFICATION
    portal_group : VDS_PORTAL_GROUP_NOTIFICATION
    service : VDS_SERVICE_NOTIFICATION
  end
  union VDS_ASYNC_OUTPUT_Anonymous_e__Union
    cp : VDS_ASYNC_OUTPUT_Anonymous_e__Union_cp
    cv : VDS_ASYNC_OUTPUT_Anonymous_e__Union_cv
    bvp : VDS_ASYNC_OUTPUT_Anonymous_e__Union_bvp
    sv : VDS_ASYNC_OUTPUT_Anonymous_e__Union_sv
    cl : VDS_ASYNC_OUTPUT_Anonymous_e__Union_cl
    ct : VDS_ASYNC_OUTPUT_Anonymous_e__Union_ct
    cpg : VDS_ASYNC_OUTPUT_Anonymous_e__Union_cpg
    cvd : VDS_ASYNC_OUTPUT_Anonymous_e__Union_cvd
  end
  union VDS_PATH_INFO_Anonymous2_e__Union
    hba_port_id : Guid
    initiator_adapter_id : Guid
  end
  union VDS_PATH_INFO_Anonymous1_e__Union
    controller_port_id : Guid
    target_portal_id : Guid
  end
  union VDS_PATH_INFO_Anonymous3_e__Union
    p_hba_port_prop : VDS_HBAPORT_PROP*
    p_initiator_portal_ip_addr : VDS_IPADDRESS*
  end

  struct VDS_STORAGE_IDENTIFIER
    m_code_set : VDS_STORAGE_IDENTIFIER_CODE_SET
    m_type : VDS_STORAGE_IDENTIFIER_TYPE
    m_cb_identifier : UInt32
    m_rgb_identifier : UInt8*
  end
  struct VDS_STORAGE_DEVICE_ID_DESCRIPTOR
    m_version : UInt32
    m_c_identifiers : UInt32
    m_rg_identifiers : VDS_STORAGE_IDENTIFIER*
  end
  struct VDS_INTERCONNECT
    m_address_type : VDS_INTERCONNECT_ADDRESS_TYPE
    m_cb_port : UInt32
    m_pb_port : UInt8*
    m_cb_address : UInt32
    m_pb_address : UInt8*
  end
  struct VDS_LUN_INFORMATION
    m_version : UInt32
    m_device_type : UInt8
    m_device_type_modifier : UInt8
    m_b_command_queueing : LibC::BOOL
    m_bus_type : VDS_STORAGE_BUS_TYPE
    m_sz_vendor_id : UInt8*
    m_sz_product_id : UInt8*
    m_sz_product_revision : UInt8*
    m_sz_serial_number : UInt8*
    m_disk_signature : Guid
    m_device_id_descriptor : VDS_STORAGE_DEVICE_ID_DESCRIPTOR
    m_c_interconnects : UInt32
    m_rg_interconnects : VDS_INTERCONNECT*
  end
  struct VDS_PACK_NOTIFICATION
    ul_event : VDS_NF_PACK
    pack_id : Guid
  end
  struct VDS_DISK_NOTIFICATION
    ul_event : VDS_NF_DISK
    disk_id : Guid
  end
  struct VDS_VOLUME_NOTIFICATION
    ul_event : UInt32
    volume_id : Guid
    plex_id : Guid
    ul_percent_completed : UInt32
  end
  struct VDS_PARTITION_NOTIFICATION
    ul_event : UInt32
    disk_id : Guid
    ull_offset : UInt64
  end
  struct VDS_SERVICE_NOTIFICATION
    ul_event : UInt32
    action : VDS_RECOVER_ACTION
  end
  struct VDS_DRIVE_LETTER_NOTIFICATION
    ul_event : UInt32
    wc_letter : Char
    volume_id : Guid
  end
  struct VDS_FILE_SYSTEM_NOTIFICATION
    ul_event : VDS_NF_FILE_SYSTEM
    volume_id : Guid
    dw_percent_completed : UInt32
  end
  struct VDS_MOUNT_POINT_NOTIFICATION
    ul_event : UInt32
    volume_id : Guid
  end
  struct VDS_SUB_SYSTEM_NOTIFICATION
    ul_event : UInt32
    sub_system_id : Guid
  end
  struct VDS_CONTROLLER_NOTIFICATION
    ul_event : VDS_NF_CONTROLLER
    controller_id : Guid
  end
  struct VDS_DRIVE_NOTIFICATION
    ul_event : VDS_NF_DRIVE
    drive_id : Guid
  end
  struct VDS_LUN_NOTIFICATION
    ul_event : VDS_NF_LUN
    lun_id : Guid
  end
  struct VDS_PORT_NOTIFICATION
    ul_event : VDS_NF_PORT
    port_id : Guid
  end
  struct VDS_PORTAL_NOTIFICATION
    ul_event : UInt32
    portal_id : Guid
  end
  struct VDS_TARGET_NOTIFICATION
    ul_event : UInt32
    target_id : Guid
  end
  struct VDS_PORTAL_GROUP_NOTIFICATION
    ul_event : UInt32
    portal_group_id : Guid
  end
  struct VDS_NOTIFICATION
    object_type : VDS_NOTIFICATION_TARGET_TYPE
    anonymous : VDS_NOTIFICATION_Anonymous_e__Union
  end
  struct VDS_ASYNC_OUTPUT
    type : VDS_ASYNC_OUTPUT_TYPE
    anonymous : VDS_ASYNC_OUTPUT_Anonymous_e__Union
  end
  struct VDS_ASYNC_OUTPUT_Anonymous_e__Union_cpg
    p_portal_group_unk : IUnknown
  end
  struct VDS_ASYNC_OUTPUT_Anonymous_e__Union_cl
    p_lun_unk : IUnknown
  end
  struct VDS_ASYNC_OUTPUT_Anonymous_e__Union_bvp
    p_volume_unk : IUnknown
  end
  struct VDS_ASYNC_OUTPUT_Anonymous_e__Union_cp
    ull_offset : UInt64
    volume_id : Guid
  end
  struct VDS_ASYNC_OUTPUT_Anonymous_e__Union_cvd
    p_v_disk_unk : IUnknown
  end
  struct VDS_ASYNC_OUTPUT_Anonymous_e__Union_sv
    ull_reclaimed_bytes : UInt64
  end
  struct VDS_ASYNC_OUTPUT_Anonymous_e__Union_ct
    p_target_unk : IUnknown
  end
  struct VDS_ASYNC_OUTPUT_Anonymous_e__Union_cv
    p_volume_unk : IUnknown
  end
  struct VDS_PATH_ID
    ull_source_id : UInt64
    ull_path_id : UInt64
  end
  struct VDS_WWN
    rguch_wwn : UInt8[8]*
  end
  struct VDS_IPADDRESS
    type : VDS_IPADDRESS_TYPE
    ipv4_address : UInt32
    ipv6_address : UInt8[16]*
    ul_ipv6_flow_info : UInt32
    ul_ipv6_scope_id : UInt32
    wsz_text_address : Char[257]*
    ul_port : UInt32
  end
  struct VDS_ISCSI_IPSEC_KEY
    p_key : UInt8*
    ul_key_size : UInt32
  end
  struct VDS_ISCSI_SHARED_SECRET
    p_shared_secret : UInt8*
    ul_shared_secret_size : UInt32
  end
  struct VDS_HBAPORT_PROP
    id : Guid
    wwn_node : VDS_WWN
    wwn_port : VDS_WWN
    type : VDS_HBAPORT_TYPE
    status : VDS_HBAPORT_STATUS
    ul_port_speed : UInt32
    ul_supported_port_speed : UInt32
  end
  struct VDS_ISCSI_INITIATOR_ADAPTER_PROP
    id : Guid
    pwsz_name : LibC::LPWSTR
  end
  struct VDS_ISCSI_INITIATOR_PORTAL_PROP
    id : Guid
    address : VDS_IPADDRESS
    ul_port_index : UInt32
  end
  struct VDS_PROVIDER_PROP
    id : Guid
    pwsz_name : LibC::LPWSTR
    guid_version_id : Guid
    pwsz_version : LibC::LPWSTR
    type : VDS_PROVIDER_TYPE
    ul_flags : UInt32
    ul_stripe_size_flags : UInt32
    s_rebuild_priority : Int16
  end
  struct VDS_PATH_INFO
    path_id : VDS_PATH_ID
    type : VDS_HWPROVIDER_TYPE
    status : VDS_PATH_STATUS
    anonymous1 : VDS_PATH_INFO_Anonymous1_e__Union
    anonymous2 : VDS_PATH_INFO_Anonymous2_e__Union
    anonymous3 : VDS_PATH_INFO_Anonymous3_e__Union
  end
  struct VDS_PATH_POLICY
    path_id : VDS_PATH_ID
    b_primary_path : LibC::BOOL
    ul_weight : UInt32
  end
  struct VDS_HINTS
    ull_hint_mask : UInt64
    ull_expected_maximum_size : UInt64
    ul_optimal_read_size : UInt32
    ul_optimal_read_alignment : UInt32
    ul_optimal_write_size : UInt32
    ul_optimal_write_alignment : UInt32
    ul_maximum_drive_count : UInt32
    ul_stripe_size : UInt32
    b_fast_crash_recovery_required : LibC::BOOL
    b_mostly_reads : LibC::BOOL
    b_optimize_for_sequential_reads : LibC::BOOL
    b_optimize_for_sequential_writes : LibC::BOOL
    b_remap_enabled : LibC::BOOL
    b_read_back_verify_enabled : LibC::BOOL
    b_write_through_caching_enabled : LibC::BOOL
    b_hardware_checksum_enabled : LibC::BOOL
    b_is_yankable : LibC::BOOL
    s_rebuild_priority : Int16
  end
  struct VDS_HINTS2
    ull_hint_mask : UInt64
    ull_expected_maximum_size : UInt64
    ul_optimal_read_size : UInt32
    ul_optimal_read_alignment : UInt32
    ul_optimal_write_size : UInt32
    ul_optimal_write_alignment : UInt32
    ul_maximum_drive_count : UInt32
    ul_stripe_size : UInt32
    ul_reserved1 : UInt32
    ul_reserved2 : UInt32
    ul_reserved3 : UInt32
    b_fast_crash_recovery_required : LibC::BOOL
    b_mostly_reads : LibC::BOOL
    b_optimize_for_sequential_reads : LibC::BOOL
    b_optimize_for_sequential_writes : LibC::BOOL
    b_remap_enabled : LibC::BOOL
    b_read_back_verify_enabled : LibC::BOOL
    b_write_through_caching_enabled : LibC::BOOL
    b_hardware_checksum_enabled : LibC::BOOL
    b_is_yankable : LibC::BOOL
    b_allocate_hot_spare : LibC::BOOL
    b_use_mirrored_cache : LibC::BOOL
    b_read_caching_enabled : LibC::BOOL
    b_write_caching_enabled : LibC::BOOL
    b_media_scan_enabled : LibC::BOOL
    b_consistency_check_enabled : LibC::BOOL
    bus_type : VDS_STORAGE_BUS_TYPE
    b_reserved1 : LibC::BOOL
    b_reserved2 : LibC::BOOL
    b_reserved3 : LibC::BOOL
    s_rebuild_priority : Int16
  end
  struct VDS_SUB_SYSTEM_PROP
    id : Guid
    pwsz_friendly_name : LibC::LPWSTR
    pwsz_identification : LibC::LPWSTR
    ul_flags : UInt32
    ul_stripe_size_flags : UInt32
    status : VDS_SUB_SYSTEM_STATUS
    health : VDS_HEALTH
    s_number_of_internal_buses : Int16
    s_max_number_of_slots_each_bus : Int16
    s_max_number_of_controllers : Int16
    s_rebuild_priority : Int16
  end
  struct VDS_SUB_SYSTEM_PROP2
    id : Guid
    pwsz_friendly_name : LibC::LPWSTR
    pwsz_identification : LibC::LPWSTR
    ul_flags : UInt32
    ul_stripe_size_flags : UInt32
    ul_supported_raid_type_flags : UInt32
    status : VDS_SUB_SYSTEM_STATUS
    health : VDS_HEALTH
    s_number_of_internal_buses : Int16
    s_max_number_of_slots_each_bus : Int16
    s_max_number_of_controllers : Int16
    s_rebuild_priority : Int16
    ul_number_of_enclosures : UInt32
  end
  struct VDS_CONTROLLER_PROP
    id : Guid
    pwsz_friendly_name : LibC::LPWSTR
    pwsz_identification : LibC::LPWSTR
    status : VDS_CONTROLLER_STATUS
    health : VDS_HEALTH
    s_number_of_ports : Int16
  end
  struct VDS_DRIVE_PROP
    id : Guid
    ull_size : UInt64
    pwsz_friendly_name : LibC::LPWSTR
    pwsz_identification : LibC::LPWSTR
    ul_flags : UInt32
    status : VDS_DRIVE_STATUS
    health : VDS_HEALTH
    s_internal_bus_number : Int16
    s_slot_number : Int16
  end
  struct VDS_DRIVE_PROP2
    id : Guid
    ull_size : UInt64
    pwsz_friendly_name : LibC::LPWSTR
    pwsz_identification : LibC::LPWSTR
    ul_flags : UInt32
    status : VDS_DRIVE_STATUS
    health : VDS_HEALTH
    s_internal_bus_number : Int16
    s_slot_number : Int16
    ul_enclosure_number : UInt32
    bus_type : VDS_STORAGE_BUS_TYPE
    ul_spindle_speed : UInt32
  end
  struct VDS_DRIVE_EXTENT
    id : Guid
    lun_id : Guid
    ull_size : UInt64
    b_used : LibC::BOOL
  end
  struct VDS_LUN_PROP
    id : Guid
    ull_size : UInt64
    pwsz_friendly_name : LibC::LPWSTR
    pwsz_identification : LibC::LPWSTR
    pwsz_unmasking_list : LibC::LPWSTR
    ul_flags : UInt32
    type : VDS_LUN_TYPE
    status : VDS_LUN_STATUS
    health : VDS_HEALTH
    transition_state : VDS_TRANSITION_STATE
    s_rebuild_priority : Int16
  end
  struct VDS_LUN_PLEX_PROP
    id : Guid
    ull_size : UInt64
    type : VDS_LUN_PLEX_TYPE
    status : VDS_LUN_PLEX_STATUS
    health : VDS_HEALTH
    transition_state : VDS_TRANSITION_STATE
    ul_flags : UInt32
    ul_stripe_size : UInt32
    s_rebuild_priority : Int16
  end
  struct VDS_PORT_PROP
    id : Guid
    pwsz_friendly_name : LibC::LPWSTR
    pwsz_identification : LibC::LPWSTR
    status : VDS_PORT_STATUS
  end
  struct VDS_ISCSI_PORTAL_PROP
    id : Guid
    address : VDS_IPADDRESS
    status : VDS_ISCSI_PORTAL_STATUS
  end
  struct VDS_ISCSI_TARGET_PROP
    id : Guid
    pwsz_iscsi_name : LibC::LPWSTR
    pwsz_friendly_name : LibC::LPWSTR
    b_chap_enabled : LibC::BOOL
  end
  struct VDS_ISCSI_PORTALGROUP_PROP
    id : Guid
    tag : UInt16
  end
  struct VDS_POOL_CUSTOM_ATTRIBUTES
    pwsz_name : LibC::LPWSTR
    pwsz_value : LibC::LPWSTR
  end
  struct VDS_POOL_ATTRIBUTES
    ull_attribute_mask : UInt64
    raid_type : VDS_RAID_TYPE
    bus_type : VDS_STORAGE_BUS_TYPE
    pwsz_intended_usage : LibC::LPWSTR
    b_spin_down : LibC::BOOL
    b_is_thin_provisioned : LibC::BOOL
    ull_provisioned_space : UInt64
    b_no_single_point_of_failure : LibC::BOOL
    ul_data_redundancy_max : UInt32
    ul_data_redundancy_min : UInt32
    ul_data_redundancy_default : UInt32
    ul_package_redundancy_max : UInt32
    ul_package_redundancy_min : UInt32
    ul_package_redundancy_default : UInt32
    ul_stripe_size : UInt32
    ul_stripe_size_max : UInt32
    ul_stripe_size_min : UInt32
    ul_default_stripe_size : UInt32
    ul_number_of_columns : UInt32
    ul_number_of_columns_max : UInt32
    ul_number_of_columns_min : UInt32
    ul_default_numberof_columns : UInt32
    ul_data_availability_hint : UInt32
    ul_access_randomness_hint : UInt32
    ul_access_direction_hint : UInt32
    ul_access_size_hint : UInt32
    ul_access_latency_hint : UInt32
    ul_access_bandwidth_weight_hint : UInt32
    ul_storage_cost_hint : UInt32
    ul_storage_efficiency_hint : UInt32
    ul_num_of_custom_attributes : UInt32
    p_pool_custom_attributes : VDS_POOL_CUSTOM_ATTRIBUTES*
    b_reserved1 : LibC::BOOL
    b_reserved2 : LibC::BOOL
    ul_reserved1 : UInt32
    ul_reserved2 : UInt32
    ull_reserved1 : UInt64
    ull_reserved2 : UInt64
  end
  struct VDS_STORAGE_POOL_PROP
    id : Guid
    status : VDS_STORAGE_POOL_STATUS
    health : VDS_HEALTH
    type : VDS_STORAGE_POOL_TYPE
    pwsz_name : LibC::LPWSTR
    pwsz_description : LibC::LPWSTR
    ull_total_consumed_space : UInt64
    ull_total_managed_space : UInt64
    ull_remaining_free_space : UInt64
  end
  struct VDS_STORAGE_POOL_DRIVE_EXTENT
    id : Guid
    ull_size : UInt64
    b_used : LibC::BOOL
  end


  struct IEnumVdsObjectVTbl
    query_interface : Proc(IEnumVdsObject*, Guid*, Void**, HRESULT)
    add_ref : Proc(IEnumVdsObject*, UInt32)
    release : Proc(IEnumVdsObject*, UInt32)
    next : Proc(IEnumVdsObject*, UInt32, IUnknown*, UInt32*, HRESULT)
    skip : Proc(IEnumVdsObject*, UInt32, HRESULT)
    reset : Proc(IEnumVdsObject*, HRESULT)
    clone : Proc(IEnumVdsObject*, IEnumVdsObject*, HRESULT)
  end

  struct IEnumVdsObject
    lpVtbl : IEnumVdsObjectVTbl*
  end

  struct IVdsAsyncVTbl
    query_interface : Proc(IVdsAsync*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsAsync*, UInt32)
    release : Proc(IVdsAsync*, UInt32)
    cancel : Proc(IVdsAsync*, HRESULT)
    wait : Proc(IVdsAsync*, HRESULT*, VDS_ASYNC_OUTPUT*, HRESULT)
    query_status : Proc(IVdsAsync*, HRESULT*, UInt32*, HRESULT)
  end

  struct IVdsAsync
    lpVtbl : IVdsAsyncVTbl*
  end

  struct IVdsAdviseSinkVTbl
    query_interface : Proc(IVdsAdviseSink*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsAdviseSink*, UInt32)
    release : Proc(IVdsAdviseSink*, UInt32)
    on_notify : Proc(IVdsAdviseSink*, Int32, VDS_NOTIFICATION*, HRESULT)
  end

  struct IVdsAdviseSink
    lpVtbl : IVdsAdviseSinkVTbl*
  end

  struct IVdsProviderVTbl
    query_interface : Proc(IVdsProvider*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsProvider*, UInt32)
    release : Proc(IVdsProvider*, UInt32)
    get_properties : Proc(IVdsProvider*, VDS_PROVIDER_PROP*, HRESULT)
  end

  struct IVdsProvider
    lpVtbl : IVdsProviderVTbl*
  end

  struct IVdsProviderSupportVTbl
    query_interface : Proc(IVdsProviderSupport*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsProviderSupport*, UInt32)
    release : Proc(IVdsProviderSupport*, UInt32)
    get_version_support : Proc(IVdsProviderSupport*, UInt32*, HRESULT)
  end

  struct IVdsProviderSupport
    lpVtbl : IVdsProviderSupportVTbl*
  end

  struct IVdsProviderPrivateVTbl
    query_interface : Proc(IVdsProviderPrivate*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsProviderPrivate*, UInt32)
    release : Proc(IVdsProviderPrivate*, UInt32)
    get_object : Proc(IVdsProviderPrivate*, Guid, VDS_OBJECT_TYPE, IUnknown*, HRESULT)
    on_load : Proc(IVdsProviderPrivate*, LibC::LPWSTR, IUnknown, HRESULT)
    on_unload : Proc(IVdsProviderPrivate*, LibC::BOOL, HRESULT)
  end

  struct IVdsProviderPrivate
    lpVtbl : IVdsProviderPrivateVTbl*
  end

  struct IVdsHwProviderVTbl
    query_interface : Proc(IVdsHwProvider*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsHwProvider*, UInt32)
    release : Proc(IVdsHwProvider*, UInt32)
    query_sub_systems : Proc(IVdsHwProvider*, IEnumVdsObject*, HRESULT)
    reenumerate : Proc(IVdsHwProvider*, HRESULT)
    refresh : Proc(IVdsHwProvider*, HRESULT)
  end

  struct IVdsHwProvider
    lpVtbl : IVdsHwProviderVTbl*
  end

  struct IVdsHwProviderTypeVTbl
    query_interface : Proc(IVdsHwProviderType*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsHwProviderType*, UInt32)
    release : Proc(IVdsHwProviderType*, UInt32)
    get_provider_type : Proc(IVdsHwProviderType*, VDS_HWPROVIDER_TYPE*, HRESULT)
  end

  struct IVdsHwProviderType
    lpVtbl : IVdsHwProviderTypeVTbl*
  end

  struct IVdsHwProviderType2VTbl
    query_interface : Proc(IVdsHwProviderType2*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsHwProviderType2*, UInt32)
    release : Proc(IVdsHwProviderType2*, UInt32)
    get_provider_type2 : Proc(IVdsHwProviderType2*, VDS_HWPROVIDER_TYPE*, HRESULT)
  end

  struct IVdsHwProviderType2
    lpVtbl : IVdsHwProviderType2VTbl*
  end

  struct IVdsHwProviderStoragePoolsVTbl
    query_interface : Proc(IVdsHwProviderStoragePools*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsHwProviderStoragePools*, UInt32)
    release : Proc(IVdsHwProviderStoragePools*, UInt32)
    query_storage_pools : Proc(IVdsHwProviderStoragePools*, UInt32, UInt64, VDS_POOL_ATTRIBUTES*, IEnumVdsObject*, HRESULT)
    create_lun_in_storage_pool : Proc(IVdsHwProviderStoragePools*, VDS_LUN_TYPE, UInt64, Guid, LibC::LPWSTR, VDS_HINTS2*, IVdsAsync*, HRESULT)
    query_max_lun_create_size_in_storage_pool : Proc(IVdsHwProviderStoragePools*, VDS_LUN_TYPE, Guid, VDS_HINTS2*, UInt64*, HRESULT)
  end

  struct IVdsHwProviderStoragePools
    lpVtbl : IVdsHwProviderStoragePoolsVTbl*
  end

  struct IVdsSubSystemVTbl
    query_interface : Proc(IVdsSubSystem*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsSubSystem*, UInt32)
    release : Proc(IVdsSubSystem*, UInt32)
    get_properties : Proc(IVdsSubSystem*, VDS_SUB_SYSTEM_PROP*, HRESULT)
    get_provider : Proc(IVdsSubSystem*, IVdsProvider*, HRESULT)
    query_controllers : Proc(IVdsSubSystem*, IEnumVdsObject*, HRESULT)
    query_luns : Proc(IVdsSubSystem*, IEnumVdsObject*, HRESULT)
    query_drives : Proc(IVdsSubSystem*, IEnumVdsObject*, HRESULT)
    get_drive : Proc(IVdsSubSystem*, Int16, Int16, IVdsDrive*, HRESULT)
    reenumerate : Proc(IVdsSubSystem*, HRESULT)
    set_controller_status : Proc(IVdsSubSystem*, Guid*, Int32, Guid*, Int32, HRESULT)
    create_lun : Proc(IVdsSubSystem*, VDS_LUN_TYPE, UInt64, Guid*, Int32, LibC::LPWSTR, VDS_HINTS*, IVdsAsync*, HRESULT)
    replace_drive : Proc(IVdsSubSystem*, Guid, Guid, HRESULT)
    set_status : Proc(IVdsSubSystem*, VDS_SUB_SYSTEM_STATUS, HRESULT)
    query_max_lun_create_size : Proc(IVdsSubSystem*, VDS_LUN_TYPE, Guid*, Int32, VDS_HINTS*, UInt64*, HRESULT)
  end

  struct IVdsSubSystem
    lpVtbl : IVdsSubSystemVTbl*
  end

  struct IVdsSubSystem2VTbl
    query_interface : Proc(IVdsSubSystem2*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsSubSystem2*, UInt32)
    release : Proc(IVdsSubSystem2*, UInt32)
    get_properties2 : Proc(IVdsSubSystem2*, VDS_SUB_SYSTEM_PROP2*, HRESULT)
    get_drive2 : Proc(IVdsSubSystem2*, Int16, Int16, UInt32, IVdsDrive*, HRESULT)
    create_lun2 : Proc(IVdsSubSystem2*, VDS_LUN_TYPE, UInt64, Guid*, Int32, LibC::LPWSTR, VDS_HINTS2*, IVdsAsync*, HRESULT)
    query_max_lun_create_size2 : Proc(IVdsSubSystem2*, VDS_LUN_TYPE, Guid*, Int32, VDS_HINTS2*, UInt64*, HRESULT)
  end

  struct IVdsSubSystem2
    lpVtbl : IVdsSubSystem2VTbl*
  end

  struct IVdsSubSystemNamingVTbl
    query_interface : Proc(IVdsSubSystemNaming*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsSubSystemNaming*, UInt32)
    release : Proc(IVdsSubSystemNaming*, UInt32)
    set_friendly_name : Proc(IVdsSubSystemNaming*, LibC::LPWSTR, HRESULT)
  end

  struct IVdsSubSystemNaming
    lpVtbl : IVdsSubSystemNamingVTbl*
  end

  struct IVdsSubSystemIscsiVTbl
    query_interface : Proc(IVdsSubSystemIscsi*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsSubSystemIscsi*, UInt32)
    release : Proc(IVdsSubSystemIscsi*, UInt32)
    query_targets : Proc(IVdsSubSystemIscsi*, IEnumVdsObject*, HRESULT)
    query_portals : Proc(IVdsSubSystemIscsi*, IEnumVdsObject*, HRESULT)
    create_target : Proc(IVdsSubSystemIscsi*, LibC::LPWSTR, LibC::LPWSTR, IVdsAsync*, HRESULT)
    set_ipsec_group_preshared_key : Proc(IVdsSubSystemIscsi*, VDS_ISCSI_IPSEC_KEY*, HRESULT)
  end

  struct IVdsSubSystemIscsi
    lpVtbl : IVdsSubSystemIscsiVTbl*
  end

  struct IVdsSubSystemInterconnectVTbl
    query_interface : Proc(IVdsSubSystemInterconnect*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsSubSystemInterconnect*, UInt32)
    release : Proc(IVdsSubSystemInterconnect*, UInt32)
    get_supported_interconnects : Proc(IVdsSubSystemInterconnect*, UInt32*, HRESULT)
  end

  struct IVdsSubSystemInterconnect
    lpVtbl : IVdsSubSystemInterconnectVTbl*
  end

  struct IVdsControllerPortVTbl
    query_interface : Proc(IVdsControllerPort*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsControllerPort*, UInt32)
    release : Proc(IVdsControllerPort*, UInt32)
    get_properties : Proc(IVdsControllerPort*, VDS_PORT_PROP*, HRESULT)
    get_controller : Proc(IVdsControllerPort*, IVdsController*, HRESULT)
    query_associated_luns : Proc(IVdsControllerPort*, IEnumVdsObject*, HRESULT)
    reset : Proc(IVdsControllerPort*, HRESULT)
    set_status : Proc(IVdsControllerPort*, VDS_PORT_STATUS, HRESULT)
  end

  struct IVdsControllerPort
    lpVtbl : IVdsControllerPortVTbl*
  end

  struct IVdsControllerVTbl
    query_interface : Proc(IVdsController*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsController*, UInt32)
    release : Proc(IVdsController*, UInt32)
    get_properties : Proc(IVdsController*, VDS_CONTROLLER_PROP*, HRESULT)
    get_sub_system : Proc(IVdsController*, IVdsSubSystem*, HRESULT)
    get_port_properties : Proc(IVdsController*, Int16, VDS_PORT_PROP*, HRESULT)
    flush_cache : Proc(IVdsController*, HRESULT)
    invalidate_cache : Proc(IVdsController*, HRESULT)
    reset : Proc(IVdsController*, HRESULT)
    query_associated_luns : Proc(IVdsController*, IEnumVdsObject*, HRESULT)
    set_status : Proc(IVdsController*, VDS_CONTROLLER_STATUS, HRESULT)
  end

  struct IVdsController
    lpVtbl : IVdsControllerVTbl*
  end

  struct IVdsControllerControllerPortVTbl
    query_interface : Proc(IVdsControllerControllerPort*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsControllerControllerPort*, UInt32)
    release : Proc(IVdsControllerControllerPort*, UInt32)
    query_controller_ports : Proc(IVdsControllerControllerPort*, IEnumVdsObject*, HRESULT)
  end

  struct IVdsControllerControllerPort
    lpVtbl : IVdsControllerControllerPortVTbl*
  end

  struct IVdsDriveVTbl
    query_interface : Proc(IVdsDrive*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsDrive*, UInt32)
    release : Proc(IVdsDrive*, UInt32)
    get_properties : Proc(IVdsDrive*, VDS_DRIVE_PROP*, HRESULT)
    get_sub_system : Proc(IVdsDrive*, IVdsSubSystem*, HRESULT)
    query_extents : Proc(IVdsDrive*, VDS_DRIVE_EXTENT**, Int32*, HRESULT)
    set_flags : Proc(IVdsDrive*, UInt32, HRESULT)
    clear_flags : Proc(IVdsDrive*, UInt32, HRESULT)
    set_status : Proc(IVdsDrive*, VDS_DRIVE_STATUS, HRESULT)
  end

  struct IVdsDrive
    lpVtbl : IVdsDriveVTbl*
  end

  struct IVdsDrive2VTbl
    query_interface : Proc(IVdsDrive2*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsDrive2*, UInt32)
    release : Proc(IVdsDrive2*, UInt32)
    get_properties2 : Proc(IVdsDrive2*, VDS_DRIVE_PROP2*, HRESULT)
  end

  struct IVdsDrive2
    lpVtbl : IVdsDrive2VTbl*
  end

  struct IVdsLunVTbl
    query_interface : Proc(IVdsLun*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsLun*, UInt32)
    release : Proc(IVdsLun*, UInt32)
    get_properties : Proc(IVdsLun*, VDS_LUN_PROP*, HRESULT)
    get_sub_system : Proc(IVdsLun*, IVdsSubSystem*, HRESULT)
    get_identification_data : Proc(IVdsLun*, VDS_LUN_INFORMATION*, HRESULT)
    query_active_controllers : Proc(IVdsLun*, IEnumVdsObject*, HRESULT)
    extend : Proc(IVdsLun*, UInt64, Guid*, Int32, IVdsAsync*, HRESULT)
    shrink : Proc(IVdsLun*, UInt64, IVdsAsync*, HRESULT)
    query_plexes : Proc(IVdsLun*, IEnumVdsObject*, HRESULT)
    add_plex : Proc(IVdsLun*, Guid, IVdsAsync*, HRESULT)
    remove_plex : Proc(IVdsLun*, Guid, IVdsAsync*, HRESULT)
    recover : Proc(IVdsLun*, IVdsAsync*, HRESULT)
    set_mask : Proc(IVdsLun*, LibC::LPWSTR, HRESULT)
    delete : Proc(IVdsLun*, HRESULT)
    associate_controllers : Proc(IVdsLun*, Guid*, Int32, Guid*, Int32, HRESULT)
    query_hints : Proc(IVdsLun*, VDS_HINTS*, HRESULT)
    apply_hints : Proc(IVdsLun*, VDS_HINTS*, HRESULT)
    set_status : Proc(IVdsLun*, VDS_LUN_STATUS, HRESULT)
    query_max_lun_extend_size : Proc(IVdsLun*, Guid*, Int32, UInt64*, HRESULT)
  end

  struct IVdsLun
    lpVtbl : IVdsLunVTbl*
  end

  struct IVdsLun2VTbl
    query_interface : Proc(IVdsLun2*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsLun2*, UInt32)
    release : Proc(IVdsLun2*, UInt32)
    query_hints2 : Proc(IVdsLun2*, VDS_HINTS2*, HRESULT)
    apply_hints2 : Proc(IVdsLun2*, VDS_HINTS2*, HRESULT)
  end

  struct IVdsLun2
    lpVtbl : IVdsLun2VTbl*
  end

  struct IVdsLunNamingVTbl
    query_interface : Proc(IVdsLunNaming*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsLunNaming*, UInt32)
    release : Proc(IVdsLunNaming*, UInt32)
    set_friendly_name : Proc(IVdsLunNaming*, LibC::LPWSTR, HRESULT)
  end

  struct IVdsLunNaming
    lpVtbl : IVdsLunNamingVTbl*
  end

  struct IVdsLunNumberVTbl
    query_interface : Proc(IVdsLunNumber*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsLunNumber*, UInt32)
    release : Proc(IVdsLunNumber*, UInt32)
    get_lun_number : Proc(IVdsLunNumber*, UInt32*, HRESULT)
  end

  struct IVdsLunNumber
    lpVtbl : IVdsLunNumberVTbl*
  end

  struct IVdsLunControllerPortsVTbl
    query_interface : Proc(IVdsLunControllerPorts*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsLunControllerPorts*, UInt32)
    release : Proc(IVdsLunControllerPorts*, UInt32)
    associate_controller_ports : Proc(IVdsLunControllerPorts*, Guid*, Int32, Guid*, Int32, HRESULT)
    query_active_controller_ports : Proc(IVdsLunControllerPorts*, IEnumVdsObject*, HRESULT)
  end

  struct IVdsLunControllerPorts
    lpVtbl : IVdsLunControllerPortsVTbl*
  end

  struct IVdsLunMpioVTbl
    query_interface : Proc(IVdsLunMpio*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsLunMpio*, UInt32)
    release : Proc(IVdsLunMpio*, UInt32)
    get_path_info : Proc(IVdsLunMpio*, VDS_PATH_INFO**, Int32*, HRESULT)
    get_load_balance_policy : Proc(IVdsLunMpio*, VDS_LOADBALANCE_POLICY_ENUM*, VDS_PATH_POLICY**, Int32*, HRESULT)
    set_load_balance_policy : Proc(IVdsLunMpio*, VDS_LOADBALANCE_POLICY_ENUM, VDS_PATH_POLICY*, Int32, HRESULT)
    get_supported_lb_policies : Proc(IVdsLunMpio*, UInt32*, HRESULT)
  end

  struct IVdsLunMpio
    lpVtbl : IVdsLunMpioVTbl*
  end

  struct IVdsLunIscsiVTbl
    query_interface : Proc(IVdsLunIscsi*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsLunIscsi*, UInt32)
    release : Proc(IVdsLunIscsi*, UInt32)
    associate_targets : Proc(IVdsLunIscsi*, Guid*, Int32, HRESULT)
    query_associated_targets : Proc(IVdsLunIscsi*, IEnumVdsObject*, HRESULT)
  end

  struct IVdsLunIscsi
    lpVtbl : IVdsLunIscsiVTbl*
  end

  struct IVdsLunPlexVTbl
    query_interface : Proc(IVdsLunPlex*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsLunPlex*, UInt32)
    release : Proc(IVdsLunPlex*, UInt32)
    get_properties : Proc(IVdsLunPlex*, VDS_LUN_PLEX_PROP*, HRESULT)
    get_lun : Proc(IVdsLunPlex*, IVdsLun*, HRESULT)
    query_extents : Proc(IVdsLunPlex*, VDS_DRIVE_EXTENT**, Int32*, HRESULT)
    query_hints : Proc(IVdsLunPlex*, VDS_HINTS*, HRESULT)
    apply_hints : Proc(IVdsLunPlex*, VDS_HINTS*, HRESULT)
  end

  struct IVdsLunPlex
    lpVtbl : IVdsLunPlexVTbl*
  end

  struct IVdsIscsiPortalVTbl
    query_interface : Proc(IVdsIscsiPortal*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsIscsiPortal*, UInt32)
    release : Proc(IVdsIscsiPortal*, UInt32)
    get_properties : Proc(IVdsIscsiPortal*, VDS_ISCSI_PORTAL_PROP*, HRESULT)
    get_sub_system : Proc(IVdsIscsiPortal*, IVdsSubSystem*, HRESULT)
    query_associated_portal_groups : Proc(IVdsIscsiPortal*, IEnumVdsObject*, HRESULT)
    set_status : Proc(IVdsIscsiPortal*, VDS_ISCSI_PORTAL_STATUS, HRESULT)
    set_ipsec_tunnel_address : Proc(IVdsIscsiPortal*, VDS_IPADDRESS*, VDS_IPADDRESS*, HRESULT)
    get_ipsec_security : Proc(IVdsIscsiPortal*, VDS_IPADDRESS*, UInt64*, HRESULT)
    set_ipsec_security : Proc(IVdsIscsiPortal*, VDS_IPADDRESS*, UInt64, VDS_ISCSI_IPSEC_KEY*, HRESULT)
  end

  struct IVdsIscsiPortal
    lpVtbl : IVdsIscsiPortalVTbl*
  end

  struct IVdsIscsiTargetVTbl
    query_interface : Proc(IVdsIscsiTarget*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsIscsiTarget*, UInt32)
    release : Proc(IVdsIscsiTarget*, UInt32)
    get_properties : Proc(IVdsIscsiTarget*, VDS_ISCSI_TARGET_PROP*, HRESULT)
    get_sub_system : Proc(IVdsIscsiTarget*, IVdsSubSystem*, HRESULT)
    query_portal_groups : Proc(IVdsIscsiTarget*, IEnumVdsObject*, HRESULT)
    query_associated_luns : Proc(IVdsIscsiTarget*, IEnumVdsObject*, HRESULT)
    create_portal_group : Proc(IVdsIscsiTarget*, IVdsAsync*, HRESULT)
    delete : Proc(IVdsIscsiTarget*, IVdsAsync*, HRESULT)
    set_friendly_name : Proc(IVdsIscsiTarget*, LibC::LPWSTR, HRESULT)
    set_shared_secret : Proc(IVdsIscsiTarget*, VDS_ISCSI_SHARED_SECRET*, LibC::LPWSTR, HRESULT)
    remember_initiator_shared_secret : Proc(IVdsIscsiTarget*, LibC::LPWSTR, VDS_ISCSI_SHARED_SECRET*, HRESULT)
    get_connected_initiators : Proc(IVdsIscsiTarget*, LibC::LPWSTR**, Int32*, HRESULT)
  end

  struct IVdsIscsiTarget
    lpVtbl : IVdsIscsiTargetVTbl*
  end

  struct IVdsIscsiPortalGroupVTbl
    query_interface : Proc(IVdsIscsiPortalGroup*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsIscsiPortalGroup*, UInt32)
    release : Proc(IVdsIscsiPortalGroup*, UInt32)
    get_properties : Proc(IVdsIscsiPortalGroup*, VDS_ISCSI_PORTALGROUP_PROP*, HRESULT)
    get_target : Proc(IVdsIscsiPortalGroup*, IVdsIscsiTarget*, HRESULT)
    query_associated_portals : Proc(IVdsIscsiPortalGroup*, IEnumVdsObject*, HRESULT)
    add_portal : Proc(IVdsIscsiPortalGroup*, Guid, IVdsAsync*, HRESULT)
    remove_portal : Proc(IVdsIscsiPortalGroup*, Guid, IVdsAsync*, HRESULT)
    delete : Proc(IVdsIscsiPortalGroup*, IVdsAsync*, HRESULT)
  end

  struct IVdsIscsiPortalGroup
    lpVtbl : IVdsIscsiPortalGroupVTbl*
  end

  struct IVdsStoragePoolVTbl
    query_interface : Proc(IVdsStoragePool*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsStoragePool*, UInt32)
    release : Proc(IVdsStoragePool*, UInt32)
    get_provider : Proc(IVdsStoragePool*, IVdsProvider*, HRESULT)
    get_properties : Proc(IVdsStoragePool*, VDS_STORAGE_POOL_PROP*, HRESULT)
    get_attributes : Proc(IVdsStoragePool*, VDS_POOL_ATTRIBUTES*, HRESULT)
    query_drive_extents : Proc(IVdsStoragePool*, VDS_STORAGE_POOL_DRIVE_EXTENT**, Int32*, HRESULT)
    query_allocated_luns : Proc(IVdsStoragePool*, IEnumVdsObject*, HRESULT)
    query_allocated_storage_pools : Proc(IVdsStoragePool*, IEnumVdsObject*, HRESULT)
  end

  struct IVdsStoragePool
    lpVtbl : IVdsStoragePoolVTbl*
  end

  struct IVdsMaintenanceVTbl
    query_interface : Proc(IVdsMaintenance*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsMaintenance*, UInt32)
    release : Proc(IVdsMaintenance*, UInt32)
    start_maintenance : Proc(IVdsMaintenance*, VDS_MAINTENANCE_OPERATION, HRESULT)
    stop_maintenance : Proc(IVdsMaintenance*, VDS_MAINTENANCE_OPERATION, HRESULT)
    pulse_maintenance : Proc(IVdsMaintenance*, VDS_MAINTENANCE_OPERATION, UInt32, HRESULT)
  end

  struct IVdsMaintenance
    lpVtbl : IVdsMaintenanceVTbl*
  end

  struct IVdsHwProviderPrivateVTbl
    query_interface : Proc(IVdsHwProviderPrivate*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsHwProviderPrivate*, UInt32)
    release : Proc(IVdsHwProviderPrivate*, UInt32)
    query_if_created_lun : Proc(IVdsHwProviderPrivate*, LibC::LPWSTR, VDS_LUN_INFORMATION*, Guid*, HRESULT)
  end

  struct IVdsHwProviderPrivate
    lpVtbl : IVdsHwProviderPrivateVTbl*
  end

  struct IVdsHwProviderPrivateMpioVTbl
    query_interface : Proc(IVdsHwProviderPrivateMpio*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsHwProviderPrivateMpio*, UInt32)
    release : Proc(IVdsHwProviderPrivateMpio*, UInt32)
    set_all_path_statuses_from_hba_port : Proc(IVdsHwProviderPrivateMpio*, VDS_HBAPORT_PROP, VDS_PATH_STATUS, HRESULT)
  end

  struct IVdsHwProviderPrivateMpio
    lpVtbl : IVdsHwProviderPrivateMpioVTbl*
  end

  struct IVdsAdminVTbl
    query_interface : Proc(IVdsAdmin*, Guid*, Void**, HRESULT)
    add_ref : Proc(IVdsAdmin*, UInt32)
    release : Proc(IVdsAdmin*, UInt32)
    register_provider : Proc(IVdsAdmin*, Guid, Guid, LibC::LPWSTR, VDS_PROVIDER_TYPE, LibC::LPWSTR, LibC::LPWSTR, Guid, HRESULT)
    unregister_provider : Proc(IVdsAdmin*, Guid, HRESULT)
  end

  struct IVdsAdmin
    lpVtbl : IVdsAdminVTbl*
  end

end
