
module Win32cr::System::Search::Common
  extend self

  enum CONDITION_TYPE
    CT_AND_CONDITION = 0_i32
    CT_OR_CONDITION = 1_i32
    CT_NOT_CONDITION = 2_i32
    CT_LEAF_CONDITION = 3_i32
  end
  enum CONDITION_OPERATION
    COP_IMPLICIT = 0_i32
    COP_EQUAL = 1_i32
    COP_NOTEQUAL = 2_i32
    COP_LESSTHAN = 3_i32
    COP_GREATERTHAN = 4_i32
    COP_LESSTHANOREQUAL = 5_i32
    COP_GREATERTHANOREQUAL = 6_i32
    COP_VALUE_STARTSWITH = 7_i32
    COP_VALUE_ENDSWITH = 8_i32
    COP_VALUE_CONTAINS = 9_i32
    COP_VALUE_NOTCONTAINS = 10_i32
    COP_DOSWILDCARDS = 11_i32
    COP_WORD_EQUAL = 12_i32
    COP_WORD_STARTSWITH = 13_i32
    COP_APPLICATION_SPECIFIC = 14_i32
  end

end