require "../../system/com.cr"
require "../../foundation.cr"
require "../../data/xml/msxml.cr"

{% if compare_versions(Crystal::VERSION, "1.8.2") <= 0 %}
@[Link("delayimp")]
{% end %}
@[Link("user32")]
{% if compare_versions(Crystal::VERSION, "1.8.2") <= 0 %}
@[Link(ldflags: "/IGNORE:4199")]
{% end %}
{% if compare_versions(Crystal::VERSION, "1.8.2") <= 0 %}
@[Link(ldflags: "/DELAYLOAD:urlmon.dll")]
{% else %}
@[Link("urlmon")]
{% end %}
lib LibWin32
  MKSYS_URLMONIKER = 6_u32
  URL_MK_LEGACY = 0_u32
  URL_MK_UNIFORM = 1_u32
  URL_MK_NO_CANONICALIZE = 2_u32
  FIEF_FLAG_FORCE_JITUI = 1_u32
  FIEF_FLAG_PEEK = 2_u32
  FIEF_FLAG_SKIP_INSTALLED_VERSION_CHECK = 4_u32
  FIEF_FLAG_RESERVED_0 = 8_u32
  FMFD_DEFAULT = 0_u32
  FMFD_URLASFILENAME = 1_u32
  FMFD_ENABLEMIMESNIFFING = 2_u32
  FMFD_IGNOREMIMETEXTPLAIN = 4_u32
  FMFD_SERVERMIME = 8_u32
  FMFD_RESPECTTEXTPLAIN = 16_u32
  FMFD_RETURNUPDATEDIMGMIMES = 32_u32
  FMFD_RESERVED_1 = 64_u32
  FMFD_RESERVED_2 = 128_u32
  UAS_EXACTLEGACY = 4096_u32
  URLMON_OPTION_USERAGENT = 268435457_u32
  URLMON_OPTION_USERAGENT_REFRESH = 268435458_u32
  URLMON_OPTION_URL_ENCODING = 268435460_u32
  URLMON_OPTION_USE_BINDSTRINGCREDS = 268435464_u32
  URLMON_OPTION_USE_BROWSERAPPSDOCUMENTS = 268435472_u32
  CF_NULL = 0_u32
  MK_S_ASYNCHRONOUS = 262632_i32
  S_ASYNCHRONOUS = 262632_i32
  E_PENDING = -2147483638_i32
  INET_E_INVALID_URL = -2146697214_i32
  INET_E_NO_SESSION = -2146697213_i32
  INET_E_CANNOT_CONNECT = -2146697212_i32
  INET_E_RESOURCE_NOT_FOUND = -2146697211_i32
  INET_E_OBJECT_NOT_FOUND = -2146697210_i32
  INET_E_DATA_NOT_AVAILABLE = -2146697209_i32
  INET_E_DOWNLOAD_FAILURE = -2146697208_i32
  INET_E_AUTHENTICATION_REQUIRED = -2146697207_i32
  INET_E_NO_VALID_MEDIA = -2146697206_i32
  INET_E_CONNECTION_TIMEOUT = -2146697205_i32
  INET_E_INVALID_REQUEST = -2146697204_i32
  INET_E_UNKNOWN_PROTOCOL = -2146697203_i32
  INET_E_SECURITY_PROBLEM = -2146697202_i32
  INET_E_CANNOT_LOAD_DATA = -2146697201_i32
  INET_E_CANNOT_INSTANTIATE_OBJECT = -2146697200_i32
  INET_E_INVALID_CERTIFICATE = -2146697191_i32
  INET_E_REDIRECT_FAILED = -2146697196_i32
  INET_E_REDIRECT_TO_DIR = -2146697195_i32
  INET_E_CANNOT_LOCK_REQUEST = -2146697194_i32
  INET_E_USE_EXTEND_BINDING = -2146697193_i32
  INET_E_TERMINATED_BIND = -2146697192_i32
  INET_E_RESERVED_1 = -2146697190_i32
  INET_E_BLOCKED_REDIRECT_XSECURITYID = -2146697189_i32
  INET_E_DOMINJECTIONVALIDATION = -2146697188_i32
  INET_E_VTAB_SWITCH_FORCE_ENGINE = -2146697187_i32
  INET_E_HSTS_CERTIFICATE_ERROR = -2146697186_i32
  INET_E_RESERVED_2 = -2146697185_i32
  INET_E_RESERVED_3 = -2146697184_i32
  INET_E_RESERVED_4 = -2146697183_i32
  INET_E_RESERVED_5 = -2146697182_i32
  INET_E_ERROR_FIRST = -2146697214_i32
  INET_E_CODE_DOWNLOAD_DECLINED = -2146696960_i32
  INET_E_RESULT_DISPATCHED = -2146696704_i32
  INET_E_CANNOT_REPLACE_SFP_FILE = -2146696448_i32
  INET_E_CODE_INSTALL_SUPPRESSED = -2146696192_i32
  INET_E_CODE_INSTALL_BLOCKED_BY_HASH_POLICY = -2146695936_i32
  INET_E_DOWNLOAD_BLOCKED_BY_INPRIVATE = -2146695935_i32
  INET_E_CODE_INSTALL_BLOCKED_IMMERSIVE = -2146695934_i32
  INET_E_FORBIDFRAMING = -2146695933_i32
  INET_E_CODE_INSTALL_BLOCKED_ARM = -2146695932_i32
  INET_E_BLOCKED_PLUGGABLE_PROTOCOL = -2146695931_i32
  INET_E_BLOCKED_ENHANCEDPROTECTEDMODE = -2146695930_i32
  INET_E_CODE_INSTALL_BLOCKED_BITNESS = -2146695929_i32
  INET_E_DOWNLOAD_BLOCKED_BY_CSP = -2146695928_i32
  INET_E_ERROR_LAST = -2146695928_i32
  Uri_DISPLAY_NO_FRAGMENT = 1_u32
  Uri_PUNYCODE_IDN_HOST = 2_u32
  Uri_DISPLAY_IDN_HOST = 4_u32
  Uri_DISPLAY_NO_PUNYCODE = 8_u32
  Uri_ENCODING_USER_INFO_AND_PATH_IS_PERCENT_ENCODED_UTF8 = 1_u32
  Uri_ENCODING_USER_INFO_AND_PATH_IS_CP = 2_u32
  Uri_ENCODING_HOST_IS_IDN = 4_u32
  Uri_ENCODING_HOST_IS_PERCENT_ENCODED_UTF8 = 8_u32
  Uri_ENCODING_HOST_IS_PERCENT_ENCODED_CP = 16_u32
  Uri_ENCODING_QUERY_AND_FRAGMENT_IS_PERCENT_ENCODED_UTF8 = 32_u32
  Uri_ENCODING_QUERY_AND_FRAGMENT_IS_CP = 64_u32
  UriBuilder_USE_ORIGINAL_FLAGS = 1_u32
  WININETINFO_OPTION_LOCK_HANDLE = 65534_u32
  URLOSTRM_USECACHEDCOPY_ONLY = 1_u32
  URLOSTRM_USECACHEDCOPY = 2_u32
  URLOSTRM_GETNEWESTVERSION = 3_u32
  SET_FEATURE_ON_THREAD = 1_u32
  SET_FEATURE_ON_PROCESS = 2_u32
  SET_FEATURE_IN_REGISTRY = 4_u32
  SET_FEATURE_ON_THREAD_LOCALMACHINE = 8_u32
  SET_FEATURE_ON_THREAD_INTRANET = 16_u32
  SET_FEATURE_ON_THREAD_TRUSTED = 32_u32
  SET_FEATURE_ON_THREAD_INTERNET = 64_u32
  SET_FEATURE_ON_THREAD_RESTRICTED = 128_u32
  GET_FEATURE_FROM_THREAD = 1_u32
  GET_FEATURE_FROM_PROCESS = 2_u32
  GET_FEATURE_FROM_REGISTRY = 4_u32
  GET_FEATURE_FROM_THREAD_LOCALMACHINE = 8_u32
  GET_FEATURE_FROM_THREAD_INTRANET = 16_u32
  GET_FEATURE_FROM_THREAD_TRUSTED = 32_u32
  GET_FEATURE_FROM_THREAD_INTERNET = 64_u32
  GET_FEATURE_FROM_THREAD_RESTRICTED = 128_u32
  INET_E_USE_DEFAULT_PROTOCOLHANDLER = -2146697199_i32
  INET_E_USE_DEFAULT_SETTING = -2146697198_i32
  INET_E_DEFAULT_ACTION = -2146697199_i32
  INET_E_QUERYOPTION_UNKNOWN = -2146697197_i32
  INET_E_REDIRECTING = -2146697196_i32
  PROTOCOLFLAG_NO_PICS_CHECK = 1_u32
  MUTZ_NOSAVEDFILECHECK = 1_u32
  MUTZ_ISFILE = 2_u32
  MUTZ_ACCEPT_WILDCARD_SCHEME = 128_u32
  MUTZ_ENFORCERESTRICTED = 256_u32
  MUTZ_RESERVED = 512_u32
  MUTZ_REQUIRESAVEDFILECHECK = 1024_u32
  MUTZ_DONT_UNESCAPE = 2048_u32
  MUTZ_DONT_USE_CACHE = 4096_u32
  MUTZ_FORCE_INTRANET_FLAGS = 8192_u32
  MUTZ_IGNORE_ZONE_MAPPINGS = 16384_u32
  MAX_SIZE_SECURITY_ID = 512_u32
  URLACTION_MIN = 4096_u32
  URLACTION_DOWNLOAD_MIN = 4096_u32
  URLACTION_DOWNLOAD_SIGNED_ACTIVEX = 4097_u32
  URLACTION_DOWNLOAD_UNSIGNED_ACTIVEX = 4100_u32
  URLACTION_DOWNLOAD_CURR_MAX = 4100_u32
  URLACTION_DOWNLOAD_MAX = 4607_u32
  URLACTION_ACTIVEX_MIN = 4608_u32
  URLACTION_ACTIVEX_RUN = 4608_u32
  URLPOLICY_ACTIVEX_CHECK_LIST = 65536_u32
  URLACTION_ACTIVEX_OVERRIDE_OBJECT_SAFETY = 4609_u32
  URLACTION_ACTIVEX_OVERRIDE_DATA_SAFETY = 4610_u32
  URLACTION_ACTIVEX_OVERRIDE_SCRIPT_SAFETY = 4611_u32
  URLACTION_SCRIPT_OVERRIDE_SAFETY = 5121_u32
  URLACTION_ACTIVEX_CONFIRM_NOOBJECTSAFETY = 4612_u32
  URLACTION_ACTIVEX_TREATASUNTRUSTED = 4613_u32
  URLACTION_ACTIVEX_NO_WEBOC_SCRIPT = 4614_u32
  URLACTION_ACTIVEX_OVERRIDE_REPURPOSEDETECTION = 4615_u32
  URLACTION_ACTIVEX_OVERRIDE_OPTIN = 4616_u32
  URLACTION_ACTIVEX_SCRIPTLET_RUN = 4617_u32
  URLACTION_ACTIVEX_DYNSRC_VIDEO_AND_ANIMATION = 4618_u32
  URLACTION_ACTIVEX_OVERRIDE_DOMAINLIST = 4619_u32
  URLACTION_ACTIVEX_ALLOW_TDC = 4620_u32
  URLACTION_ACTIVEX_CURR_MAX = 4620_u32
  URLACTION_ACTIVEX_MAX = 5119_u32
  URLACTION_SCRIPT_MIN = 5120_u32
  URLACTION_SCRIPT_RUN = 5120_u32
  URLACTION_SCRIPT_JAVA_USE = 5122_u32
  URLACTION_SCRIPT_SAFE_ACTIVEX = 5125_u32
  URLACTION_CROSS_DOMAIN_DATA = 5126_u32
  URLACTION_SCRIPT_PASTE = 5127_u32
  URLACTION_ALLOW_XDOMAIN_SUBFRAME_RESIZE = 5128_u32
  URLACTION_SCRIPT_XSSFILTER = 5129_u32
  URLACTION_SCRIPT_NAVIGATE = 5130_u32
  URLACTION_PLUGGABLE_PROTOCOL_XHR = 5131_u32
  URLACTION_ALLOW_VBSCRIPT_IE = 5132_u32
  URLACTION_ALLOW_JSCRIPT_IE = 5133_u32
  URLACTION_SCRIPT_CURR_MAX = 5133_u32
  URLACTION_SCRIPT_MAX = 5631_u32
  URLACTION_HTML_MIN = 5632_u32
  URLACTION_HTML_SUBMIT_FORMS = 5633_u32
  URLACTION_HTML_SUBMIT_FORMS_FROM = 5634_u32
  URLACTION_HTML_SUBMIT_FORMS_TO = 5635_u32
  URLACTION_HTML_FONT_DOWNLOAD = 5636_u32
  URLACTION_HTML_JAVA_RUN = 5637_u32
  URLACTION_HTML_USERDATA_SAVE = 5638_u32
  URLACTION_HTML_SUBFRAME_NAVIGATE = 5639_u32
  URLACTION_HTML_META_REFRESH = 5640_u32
  URLACTION_HTML_MIXED_CONTENT = 5641_u32
  URLACTION_HTML_INCLUDE_FILE_PATH = 5642_u32
  URLACTION_HTML_ALLOW_INJECTED_DYNAMIC_HTML = 5643_u32
  URLACTION_HTML_REQUIRE_UTF8_DOCUMENT_CODEPAGE = 5644_u32
  URLACTION_HTML_ALLOW_CROSS_DOMAIN_CANVAS = 5645_u32
  URLACTION_HTML_ALLOW_WINDOW_CLOSE = 5646_u32
  URLACTION_HTML_ALLOW_CROSS_DOMAIN_WEBWORKER = 5647_u32
  URLACTION_HTML_ALLOW_CROSS_DOMAIN_TEXTTRACK = 5648_u32
  URLACTION_HTML_ALLOW_INDEXEDDB = 5649_u32
  URLACTION_HTML_MAX = 6143_u32
  URLACTION_SHELL_MIN = 6144_u32
  URLACTION_SHELL_INSTALL_DTITEMS = 6144_u32
  URLACTION_SHELL_MOVE_OR_COPY = 6146_u32
  URLACTION_SHELL_FILE_DOWNLOAD = 6147_u32
  URLACTION_SHELL_VERB = 6148_u32
  URLACTION_SHELL_WEBVIEW_VERB = 6149_u32
  URLACTION_SHELL_SHELLEXECUTE = 6150_u32
  URLACTION_SHELL_EXECUTE_HIGHRISK = 6150_u32
  URLACTION_SHELL_EXECUTE_MODRISK = 6151_u32
  URLACTION_SHELL_EXECUTE_LOWRISK = 6152_u32
  URLACTION_SHELL_POPUPMGR = 6153_u32
  URLACTION_SHELL_RTF_OBJECTS_LOAD = 6154_u32
  URLACTION_SHELL_ENHANCED_DRAGDROP_SECURITY = 6155_u32
  URLACTION_SHELL_EXTENSIONSECURITY = 6156_u32
  URLACTION_SHELL_SECURE_DRAGSOURCE = 6157_u32
  URLACTION_SHELL_REMOTEQUERY = 6158_u32
  URLACTION_SHELL_PREVIEW = 6159_u32
  URLACTION_SHELL_SHARE = 6160_u32
  URLACTION_SHELL_ALLOW_CROSS_SITE_SHARE = 6161_u32
  URLACTION_SHELL_TOCTOU_RISK = 6162_u32
  URLACTION_SHELL_CURR_MAX = 6162_u32
  URLACTION_SHELL_MAX = 6655_u32
  URLACTION_NETWORK_MIN = 6656_u32
  URLACTION_CREDENTIALS_USE = 6656_u32
  URLPOLICY_CREDENTIALS_SILENT_LOGON_OK = 0_u32
  URLPOLICY_CREDENTIALS_MUST_PROMPT_USER = 65536_u32
  URLPOLICY_CREDENTIALS_CONDITIONAL_PROMPT = 131072_u32
  URLPOLICY_CREDENTIALS_ANONYMOUS_ONLY = 196608_u32
  URLACTION_AUTHENTICATE_CLIENT = 6657_u32
  URLPOLICY_AUTHENTICATE_CLEARTEXT_OK = 0_u32
  URLPOLICY_AUTHENTICATE_CHALLENGE_RESPONSE = 65536_u32
  URLPOLICY_AUTHENTICATE_MUTUAL_ONLY = 196608_u32
  URLACTION_COOKIES = 6658_u32
  URLACTION_COOKIES_SESSION = 6659_u32
  URLACTION_CLIENT_CERT_PROMPT = 6660_u32
  URLACTION_COOKIES_THIRD_PARTY = 6661_u32
  URLACTION_COOKIES_SESSION_THIRD_PARTY = 6662_u32
  URLACTION_COOKIES_ENABLED = 6672_u32
  URLACTION_NETWORK_CURR_MAX = 6672_u32
  URLACTION_NETWORK_MAX = 7167_u32
  URLACTION_JAVA_MIN = 7168_u32
  URLACTION_JAVA_PERMISSIONS = 7168_u32
  URLPOLICY_JAVA_PROHIBIT = 0_u32
  URLPOLICY_JAVA_HIGH = 65536_u32
  URLPOLICY_JAVA_MEDIUM = 131072_u32
  URLPOLICY_JAVA_LOW = 196608_u32
  URLPOLICY_JAVA_CUSTOM = 8388608_u32
  URLACTION_JAVA_CURR_MAX = 7168_u32
  URLACTION_JAVA_MAX = 7423_u32
  URLACTION_INFODELIVERY_MIN = 7424_u32
  URLACTION_INFODELIVERY_NO_ADDING_CHANNELS = 7424_u32
  URLACTION_INFODELIVERY_NO_EDITING_CHANNELS = 7425_u32
  URLACTION_INFODELIVERY_NO_REMOVING_CHANNELS = 7426_u32
  URLACTION_INFODELIVERY_NO_ADDING_SUBSCRIPTIONS = 7427_u32
  URLACTION_INFODELIVERY_NO_EDITING_SUBSCRIPTIONS = 7428_u32
  URLACTION_INFODELIVERY_NO_REMOVING_SUBSCRIPTIONS = 7429_u32
  URLACTION_INFODELIVERY_NO_CHANNEL_LOGGING = 7430_u32
  URLACTION_INFODELIVERY_CURR_MAX = 7430_u32
  URLACTION_INFODELIVERY_MAX = 7679_u32
  URLACTION_CHANNEL_SOFTDIST_MIN = 7680_u32
  URLACTION_CHANNEL_SOFTDIST_PERMISSIONS = 7685_u32
  URLPOLICY_CHANNEL_SOFTDIST_PROHIBIT = 65536_u32
  URLPOLICY_CHANNEL_SOFTDIST_PRECACHE = 131072_u32
  URLPOLICY_CHANNEL_SOFTDIST_AUTOINSTALL = 196608_u32
  URLACTION_CHANNEL_SOFTDIST_MAX = 7935_u32
  URLACTION_DOTNET_USERCONTROLS = 8197_u32
  URLACTION_BEHAVIOR_MIN = 8192_u32
  URLACTION_BEHAVIOR_RUN = 8192_u32
  URLPOLICY_BEHAVIOR_CHECK_LIST = 65536_u32
  URLACTION_FEATURE_MIN = 8448_u32
  URLACTION_FEATURE_MIME_SNIFFING = 8448_u32
  URLACTION_FEATURE_ZONE_ELEVATION = 8449_u32
  URLACTION_FEATURE_WINDOW_RESTRICTIONS = 8450_u32
  URLACTION_FEATURE_SCRIPT_STATUS_BAR = 8451_u32
  URLACTION_FEATURE_FORCE_ADDR_AND_STATUS = 8452_u32
  URLACTION_FEATURE_BLOCK_INPUT_PROMPTS = 8453_u32
  URLACTION_FEATURE_DATA_BINDING = 8454_u32
  URLACTION_FEATURE_CROSSDOMAIN_FOCUS_CHANGE = 8455_u32
  URLACTION_AUTOMATIC_DOWNLOAD_UI_MIN = 8704_u32
  URLACTION_AUTOMATIC_DOWNLOAD_UI = 8704_u32
  URLACTION_AUTOMATIC_ACTIVEX_UI = 8705_u32
  URLACTION_ALLOW_RESTRICTEDPROTOCOLS = 8960_u32
  URLACTION_ALLOW_APEVALUATION = 8961_u32
  URLACTION_ALLOW_XHR_EVALUATION = 8962_u32
  URLACTION_WINDOWS_BROWSER_APPLICATIONS = 9216_u32
  URLACTION_XPS_DOCUMENTS = 9217_u32
  URLACTION_LOOSE_XAML = 9218_u32
  URLACTION_LOWRIGHTS = 9472_u32
  URLACTION_WINFX_SETUP = 9728_u32
  URLACTION_INPRIVATE_BLOCKING = 9984_u32
  URLACTION_ALLOW_AUDIO_VIDEO = 9985_u32
  URLACTION_ALLOW_ACTIVEX_FILTERING = 9986_u32
  URLACTION_ALLOW_STRUCTURED_STORAGE_SNIFFING = 9987_u32
  URLACTION_ALLOW_AUDIO_VIDEO_PLUGINS = 9988_u32
  URLACTION_ALLOW_ZONE_ELEVATION_VIA_OPT_OUT = 9989_u32
  URLACTION_ALLOW_ZONE_ELEVATION_OPT_OUT_ADDITION = 9990_u32
  URLACTION_ALLOW_CROSSDOMAIN_DROP_WITHIN_WINDOW = 9992_u32
  URLACTION_ALLOW_CROSSDOMAIN_DROP_ACROSS_WINDOWS = 9993_u32
  URLACTION_ALLOW_CROSSDOMAIN_APPCACHE_MANIFEST = 9994_u32
  URLACTION_ALLOW_RENDER_LEGACY_DXTFILTERS = 9995_u32
  URLACTION_ALLOW_ANTIMALWARE_SCANNING_OF_ACTIVEX = 9996_u32
  URLACTION_ALLOW_CSS_EXPRESSIONS = 9997_u32
  URLPOLICY_ALLOW = 0_u32
  URLPOLICY_QUERY = 1_u32
  URLPOLICY_DISALLOW = 3_u32
  URLPOLICY_NOTIFY_ON_ALLOW = 16_u32
  URLPOLICY_NOTIFY_ON_DISALLOW = 32_u32
  URLPOLICY_LOG_ON_ALLOW = 64_u32
  URLPOLICY_LOG_ON_DISALLOW = 128_u32
  URLPOLICY_MASK_PERMISSIONS = 15_u32
  URLPOLICY_DONTCHECKDLGBOX = 256_u32
  URLZONE_ESC_FLAG = 256_u32
  SECURITY_IE_STATE_GREEN = 0_u32
  SECURITY_IE_STATE_RED = 1_u32
  SOFTDIST_FLAG_USAGE_EMAIL = 1_u32
  SOFTDIST_FLAG_USAGE_PRECACHE = 2_u32
  SOFTDIST_FLAG_USAGE_AUTOINSTALL = 4_u32
  SOFTDIST_FLAG_DELETE_SUBSCRIPTION = 8_u32
  SOFTDIST_ADSTATE_NONE = 0_u32
  SOFTDIST_ADSTATE_AVAILABLE = 1_u32
  SOFTDIST_ADSTATE_DOWNLOADED = 2_u32
  SOFTDIST_ADSTATE_INSTALLED = 3_u32
  CONFIRMSAFETYACTION_LOADOBJECT = 1_u32


  enum IEObjectType : Int32
    IE_EPM_OBJECT_EVENT = 0
    IE_EPM_OBJECT_MUTEX = 1
    IE_EPM_OBJECT_SEMAPHORE = 2
    IE_EPM_OBJECT_SHARED_MEMORY = 3
    IE_EPM_OBJECT_WAITABLE_TIMER = 4
    IE_EPM_OBJECT_FILE = 5
    IE_EPM_OBJECT_NAMED_PIPE = 6
    IE_EPM_OBJECT_REGISTRY = 7
  end

  enum MONIKERPROPERTY : Int32
    MIMETYPEPROP = 0
    USE_SRC_URL = 1
    CLASSIDPROP = 2
    TRUSTEDDOWNLOADPROP = 3
    POPUPLEVELPROP = 4
  end

  enum BINDVERB : Int32
    BINDVERB_GET = 0
    BINDVERB_POST = 1
    BINDVERB_PUT = 2
    BINDVERB_CUSTOM = 3
    BINDVERB_RESERVED1 = 4
  end

  enum BINDF : Int32
    BINDF_ASYNCHRONOUS = 1
    BINDF_ASYNCSTORAGE = 2
    BINDF_NOPROGRESSIVERENDERING = 4
    BINDF_OFFLINEOPERATION = 8
    BINDF_GETNEWESTVERSION = 16
    BINDF_NOWRITECACHE = 32
    BINDF_NEEDFILE = 64
    BINDF_PULLDATA = 128
    BINDF_IGNORESECURITYPROBLEM = 256
    BINDF_RESYNCHRONIZE = 512
    BINDF_HYPERLINK = 1024
    BINDF_NO_UI = 2048
    BINDF_SILENTOPERATION = 4096
    BINDF_PRAGMA_NO_CACHE = 8192
    BINDF_GETCLASSOBJECT = 16384
    BINDF_RESERVED_1 = 32768
    BINDF_FREE_THREADED = 65536
    BINDF_DIRECT_READ = 131072
    BINDF_FORMS_SUBMIT = 262144
    BINDF_GETFROMCACHE_IF_NET_FAIL = 524288
    BINDF_FROMURLMON = 1048576
    BINDF_FWD_BACK = 2097152
    BINDF_PREFERDEFAULTHANDLER = 4194304
    BINDF_ENFORCERESTRICTED = 8388608
    BINDF_RESERVED_2 = -2147483648
    BINDF_RESERVED_3 = 16777216
    BINDF_RESERVED_4 = 33554432
    BINDF_RESERVED_5 = 67108864
    BINDF_RESERVED_6 = 134217728
    BINDF_RESERVED_7 = 1073741824
    BINDF_RESERVED_8 = 536870912
  end

  enum URL_ENCODING : Int32
    URL_ENCODING_NONE = 0
    URL_ENCODING_ENABLE_UTF8 = 268435456
    URL_ENCODING_DISABLE_UTF8 = 536870912
  end

  enum BINDINFO_OPTIONS : Int32
    BINDINFO_OPTIONS_WININETFLAG = 65536
    BINDINFO_OPTIONS_ENABLE_UTF8 = 131072
    BINDINFO_OPTIONS_DISABLE_UTF8 = 262144
    BINDINFO_OPTIONS_USE_IE_ENCODING = 524288
    BINDINFO_OPTIONS_BINDTOOBJECT = 1048576
    BINDINFO_OPTIONS_SECURITYOPTOUT = 2097152
    BINDINFO_OPTIONS_IGNOREMIMETEXTPLAIN = 4194304
    BINDINFO_OPTIONS_USEBINDSTRINGCREDS = 8388608
    BINDINFO_OPTIONS_IGNOREHTTPHTTPSREDIRECTS = 16777216
    BINDINFO_OPTIONS_IGNORE_SSLERRORS_ONCE = 33554432
    BINDINFO_WPC_DOWNLOADBLOCKED = 134217728
    BINDINFO_WPC_LOGGING_ENABLED = 268435456
    BINDINFO_OPTIONS_ALLOWCONNECTDATA = 536870912
    BINDINFO_OPTIONS_DISABLEAUTOREDIRECTS = 1073741824
    BINDINFO_OPTIONS_SHDOCVW_NAVIGATE = -2147483648
  end

  enum BSCF : Int32
    BSCF_FIRSTDATANOTIFICATION = 1
    BSCF_INTERMEDIATEDATANOTIFICATION = 2
    BSCF_LASTDATANOTIFICATION = 4
    BSCF_DATAFULLYAVAILABLE = 8
    BSCF_AVAILABLEDATASIZEUNKNOWN = 16
    BSCF_SKIPDRAINDATAFORFILEURLS = 32
    BSCF_64BITLENGTHDOWNLOAD = 64
  end

  enum BINDSTATUS : Int32
    BINDSTATUS_FINDINGRESOURCE = 1
    BINDSTATUS_CONNECTING = 2
    BINDSTATUS_REDIRECTING = 3
    BINDSTATUS_BEGINDOWNLOADDATA = 4
    BINDSTATUS_DOWNLOADINGDATA = 5
    BINDSTATUS_ENDDOWNLOADDATA = 6
    BINDSTATUS_BEGINDOWNLOADCOMPONENTS = 7
    BINDSTATUS_INSTALLINGCOMPONENTS = 8
    BINDSTATUS_ENDDOWNLOADCOMPONENTS = 9
    BINDSTATUS_USINGCACHEDCOPY = 10
    BINDSTATUS_SENDINGREQUEST = 11
    BINDSTATUS_CLASSIDAVAILABLE = 12
    BINDSTATUS_MIMETYPEAVAILABLE = 13
    BINDSTATUS_CACHEFILENAMEAVAILABLE = 14
    BINDSTATUS_BEGINSYNCOPERATION = 15
    BINDSTATUS_ENDSYNCOPERATION = 16
    BINDSTATUS_BEGINUPLOADDATA = 17
    BINDSTATUS_UPLOADINGDATA = 18
    BINDSTATUS_ENDUPLOADDATA = 19
    BINDSTATUS_PROTOCOLCLASSID = 20
    BINDSTATUS_ENCODING = 21
    BINDSTATUS_VERIFIEDMIMETYPEAVAILABLE = 22
    BINDSTATUS_CLASSINSTALLLOCATION = 23
    BINDSTATUS_DECODING = 24
    BINDSTATUS_LOADINGMIMEHANDLER = 25
    BINDSTATUS_CONTENTDISPOSITIONATTACH = 26
    BINDSTATUS_FILTERREPORTMIMETYPE = 27
    BINDSTATUS_CLSIDCANINSTANTIATE = 28
    BINDSTATUS_IUNKNOWNAVAILABLE = 29
    BINDSTATUS_DIRECTBIND = 30
    BINDSTATUS_RAWMIMETYPE = 31
    BINDSTATUS_PROXYDETECTING = 32
    BINDSTATUS_ACCEPTRANGES = 33
    BINDSTATUS_COOKIE_SENT = 34
    BINDSTATUS_COMPACT_POLICY_RECEIVED = 35
    BINDSTATUS_COOKIE_SUPPRESSED = 36
    BINDSTATUS_COOKIE_STATE_UNKNOWN = 37
    BINDSTATUS_COOKIE_STATE_ACCEPT = 38
    BINDSTATUS_COOKIE_STATE_REJECT = 39
    BINDSTATUS_COOKIE_STATE_PROMPT = 40
    BINDSTATUS_COOKIE_STATE_LEASH = 41
    BINDSTATUS_COOKIE_STATE_DOWNGRADE = 42
    BINDSTATUS_POLICY_HREF = 43
    BINDSTATUS_P3P_HEADER = 44
    BINDSTATUS_SESSION_COOKIE_RECEIVED = 45
    BINDSTATUS_PERSISTENT_COOKIE_RECEIVED = 46
    BINDSTATUS_SESSION_COOKIES_ALLOWED = 47
    BINDSTATUS_CACHECONTROL = 48
    BINDSTATUS_CONTENTDISPOSITIONFILENAME = 49
    BINDSTATUS_MIMETEXTPLAINMISMATCH = 50
    BINDSTATUS_PUBLISHERAVAILABLE = 51
    BINDSTATUS_DISPLAYNAMEAVAILABLE = 52
    BINDSTATUS_SSLUX_NAVBLOCKED = 53
    BINDSTATUS_SERVER_MIMETYPEAVAILABLE = 54
    BINDSTATUS_SNIFFED_CLASSIDAVAILABLE = 55
    BINDSTATUS_64BIT_PROGRESS = 56
    BINDSTATUS_LAST = 56
    BINDSTATUS_RESERVED_0 = 57
    BINDSTATUS_RESERVED_1 = 58
    BINDSTATUS_RESERVED_2 = 59
    BINDSTATUS_RESERVED_3 = 60
    BINDSTATUS_RESERVED_4 = 61
    BINDSTATUS_RESERVED_5 = 62
    BINDSTATUS_RESERVED_6 = 63
    BINDSTATUS_RESERVED_7 = 64
    BINDSTATUS_RESERVED_8 = 65
    BINDSTATUS_RESERVED_9 = 66
    BINDSTATUS_RESERVED_A = 67
    BINDSTATUS_RESERVED_B = 68
    BINDSTATUS_RESERVED_C = 69
    BINDSTATUS_RESERVED_D = 70
    BINDSTATUS_RESERVED_E = 71
    BINDSTATUS_RESERVED_F = 72
    BINDSTATUS_RESERVED_10 = 73
    BINDSTATUS_RESERVED_11 = 74
    BINDSTATUS_RESERVED_12 = 75
    BINDSTATUS_RESERVED_13 = 76
    BINDSTATUS_RESERVED_14 = 77
    BINDSTATUS_LAST_PRIVATE = 77
  end

  enum BINDF2 : Int32
    BINDF2_DISABLEBASICOVERHTTP = 1
    BINDF2_DISABLEAUTOCOOKIEHANDLING = 2
    BINDF2_READ_DATA_GREATER_THAN_4GB = 4
    BINDF2_DISABLE_HTTP_REDIRECT_XSECURITYID = 8
    BINDF2_SETDOWNLOADMODE = 32
    BINDF2_DISABLE_HTTP_REDIRECT_CACHING = 64
    BINDF2_KEEP_CALLBACK_MODULE_LOADED = 128
    BINDF2_ALLOW_PROXY_CRED_PROMPT = 256
    BINDF2_RESERVED_17 = 512
    BINDF2_RESERVED_16 = 1024
    BINDF2_RESERVED_15 = 2048
    BINDF2_RESERVED_14 = 4096
    BINDF2_RESERVED_13 = 8192
    BINDF2_RESERVED_12 = 16384
    BINDF2_RESERVED_11 = 32768
    BINDF2_RESERVED_10 = 65536
    BINDF2_RESERVED_F = 131072
    BINDF2_RESERVED_E = 262144
    BINDF2_RESERVED_D = 524288
    BINDF2_RESERVED_C = 1048576
    BINDF2_RESERVED_B = 2097152
    BINDF2_RESERVED_A = 4194304
    BINDF2_RESERVED_9 = 8388608
    BINDF2_RESERVED_8 = 16777216
    BINDF2_RESERVED_7 = 33554432
    BINDF2_RESERVED_6 = 67108864
    BINDF2_RESERVED_5 = 134217728
    BINDF2_RESERVED_4 = 268435456
    BINDF2_RESERVED_3 = 536870912
    BINDF2_RESERVED_2 = 1073741824
    BINDF2_RESERVED_1 = -2147483648
  end

  enum AUTHENTICATEF : Int32
    AUTHENTICATEF_PROXY = 1
    AUTHENTICATEF_BASIC = 2
    AUTHENTICATEF_HTTP = 4
  end

  enum CIP_STATUS : Int32
    CIP_DISK_FULL = 0
    CIP_ACCESS_DENIED = 1
    CIP_NEWER_VERSION_EXISTS = 2
    CIP_OLDER_VERSION_EXISTS = 3
    CIP_NAME_CONFLICT = 4
    CIP_TRUST_VERIFICATION_COMPONENT_MISSING = 5
    CIP_EXE_SELF_REGISTERATION_TIMEOUT = 6
    CIP_UNSAFE_TO_ABORT = 7
    CIP_NEED_REBOOT = 8
    CIP_NEED_REBOOT_UI_PERMISSION = 9
  end

  enum Uri_HOST_TYPE : Int32
    Uri_HOST_UNKNOWN = 0
    Uri_HOST_DNS = 1
    Uri_HOST_IPV4 = 2
    Uri_HOST_IPV6 = 3
    Uri_HOST_IDN = 4
  end

  enum BINDSTRING : Int32
    BINDSTRING_HEADERS = 1
    BINDSTRING_ACCEPT_MIMES = 2
    BINDSTRING_EXTRA_URL = 3
    BINDSTRING_LANGUAGE = 4
    BINDSTRING_USERNAME = 5
    BINDSTRING_PASSWORD = 6
    BINDSTRING_UA_PIXELS = 7
    BINDSTRING_UA_COLOR = 8
    BINDSTRING_OS = 9
    BINDSTRING_USER_AGENT = 10
    BINDSTRING_ACCEPT_ENCODINGS = 11
    BINDSTRING_POST_COOKIE = 12
    BINDSTRING_POST_DATA_MIME = 13
    BINDSTRING_URL = 14
    BINDSTRING_IID = 15
    BINDSTRING_FLAG_BIND_TO_OBJECT = 16
    BINDSTRING_PTR_BIND_CONTEXT = 17
    BINDSTRING_XDR_ORIGIN = 18
    BINDSTRING_DOWNLOADPATH = 19
    BINDSTRING_ROOTDOC_URL = 20
    BINDSTRING_INITIAL_FILENAME = 21
    BINDSTRING_PROXY_USERNAME = 22
    BINDSTRING_PROXY_PASSWORD = 23
    BINDSTRING_ENTERPRISE_ID = 24
    BINDSTRING_DOC_URL = 25
    BINDSTRING_SAMESITE_COOKIE_LEVEL = 26
  end

  enum PI_FLAGS : Int32
    PI_PARSE_URL = 1
    PI_FILTER_MODE = 2
    PI_FORCE_ASYNC = 4
    PI_USE_WORKERTHREAD = 8
    PI_MIMEVERIFICATION = 16
    PI_CLSIDLOOKUP = 32
    PI_DATAPROGRESS = 64
    PI_SYNCHRONOUS = 128
    PI_APARTMENTTHREADED = 256
    PI_CLASSINSTALL = 512
    PI_PASSONBINDCTX = 8192
    PI_NOMIMEHANDLER = 32768
    PI_LOADAPPDIRECT = 16384
    PD_FORCE_SWITCH = 65536
    PI_PREFERDEFAULTHANDLER = 131072
  end

  enum OIBDG_FLAGS : Int32
    OIBDG_APARTMENTTHREADED = 256
    OIBDG_DATAONLY = 4096
  end

  enum PARSEACTION : Int32
    PARSE_CANONICALIZE = 1
    PARSE_FRIENDLY = 2
    PARSE_SECURITY_URL = 3
    PARSE_ROOTDOCUMENT = 4
    PARSE_DOCUMENT = 5
    PARSE_ANCHOR = 6
    PARSE_ENCODE_IS_UNESCAPE = 7
    PARSE_DECODE_IS_ESCAPE = 8
    PARSE_PATH_FROM_URL = 9
    PARSE_URL_FROM_PATH = 10
    PARSE_MIME = 11
    PARSE_SERVER = 12
    PARSE_SCHEMA = 13
    PARSE_SITE = 14
    PARSE_DOMAIN = 15
    PARSE_LOCATION = 16
    PARSE_SECURITY_DOMAIN = 17
    PARSE_ESCAPE = 18
    PARSE_UNESCAPE = 19
  end

  enum PSUACTION : Int32
    PSU_DEFAULT = 1
    PSU_SECURITY_URL_ONLY = 2
  end

  enum QUERYOPTION : Int32
    QUERY_EXPIRATION_DATE = 1
    QUERY_TIME_OF_LAST_CHANGE = 2
    QUERY_CONTENT_ENCODING = 3
    QUERY_CONTENT_TYPE = 4
    QUERY_REFRESH = 5
    QUERY_RECOMBINE = 6
    QUERY_CAN_NAVIGATE = 7
    QUERY_USES_NETWORK = 8
    QUERY_IS_CACHED = 9
    QUERY_IS_INSTALLEDENTRY = 10
    QUERY_IS_CACHED_OR_MAPPED = 11
    QUERY_USES_CACHE = 12
    QUERY_IS_SECURE = 13
    QUERY_IS_SAFE = 14
    QUERY_USES_HISTORYFOLDER = 15
    QUERY_IS_CACHED_AND_USABLE_OFFLINE = 16
  end

  enum INTERNETFEATURELIST : Int32
    FEATURE_OBJECT_CACHING = 0
    FEATURE_ZONE_ELEVATION = 1
    FEATURE_MIME_HANDLING = 2
    FEATURE_MIME_SNIFFING = 3
    FEATURE_WINDOW_RESTRICTIONS = 4
    FEATURE_WEBOC_POPUPMANAGEMENT = 5
    FEATURE_BEHAVIORS = 6
    FEATURE_DISABLE_MK_PROTOCOL = 7
    FEATURE_LOCALMACHINE_LOCKDOWN = 8
    FEATURE_SECURITYBAND = 9
    FEATURE_RESTRICT_ACTIVEXINSTALL = 10
    FEATURE_VALIDATE_NAVIGATE_URL = 11
    FEATURE_RESTRICT_FILEDOWNLOAD = 12
    FEATURE_ADDON_MANAGEMENT = 13
    FEATURE_PROTOCOL_LOCKDOWN = 14
    FEATURE_HTTP_USERNAME_PASSWORD_DISABLE = 15
    FEATURE_SAFE_BINDTOOBJECT = 16
    FEATURE_UNC_SAVEDFILECHECK = 17
    FEATURE_GET_URL_DOM_FILEPATH_UNENCODED = 18
    FEATURE_TABBED_BROWSING = 19
    FEATURE_SSLUX = 20
    FEATURE_DISABLE_NAVIGATION_SOUNDS = 21
    FEATURE_DISABLE_LEGACY_COMPRESSION = 22
    FEATURE_FORCE_ADDR_AND_STATUS = 23
    FEATURE_XMLHTTP = 24
    FEATURE_DISABLE_TELNET_PROTOCOL = 25
    FEATURE_FEEDS = 26
    FEATURE_BLOCK_INPUT_PROMPTS = 27
    FEATURE_ENTRY_COUNT = 28
  end

  enum PUAF : Int32
    PUAF_DEFAULT = 0
    PUAF_NOUI = 1
    PUAF_ISFILE = 2
    PUAF_WARN_IF_DENIED = 4
    PUAF_FORCEUI_FOREGROUND = 8
    PUAF_CHECK_TIFS = 16
    PUAF_DONTCHECKBOXINDIALOG = 32
    PUAF_TRUSTED = 64
    PUAF_ACCEPT_WILDCARD_SCHEME = 128
    PUAF_ENFORCERESTRICTED = 256
    PUAF_NOSAVEDFILECHECK = 512
    PUAF_REQUIRESAVEDFILECHECK = 1024
    PUAF_DONT_USE_CACHE = 4096
    PUAF_RESERVED1 = 8192
    PUAF_RESERVED2 = 16384
    PUAF_LMZ_UNLOCKED = 65536
    PUAF_LMZ_LOCKED = 131072
    PUAF_DEFAULTZONEPOL = 262144
    PUAF_NPL_USE_LOCKED_IF_RESTRICTED = 524288
    PUAF_NOUIIFLOCKED = 1048576
    PUAF_DRAGPROTOCOLCHECK = 2097152
  end

  enum PUAFOUT : Int32
    PUAFOUT_DEFAULT = 0
    PUAFOUT_ISLOCKZONEPOLICY = 1
  end

  enum SZM_FLAGS : Int32
    SZM_CREATE = 0
    SZM_DELETE = 1
  end

  enum URLZONE : Int32
    URLZONE_INVALID = -1
    URLZONE_PREDEFINED_MIN = 0
    URLZONE_LOCAL_MACHINE = 0
    URLZONE_INTRANET = 1
    URLZONE_TRUSTED = 2
    URLZONE_INTERNET = 3
    URLZONE_UNTRUSTED = 4
    URLZONE_PREDEFINED_MAX = 999
    URLZONE_USER_MIN = 1000
    URLZONE_USER_MAX = 10000
  end

  enum URLTEMPLATE : Int32
    URLTEMPLATE_CUSTOM = 0
    URLTEMPLATE_PREDEFINED_MIN = 65536
    URLTEMPLATE_LOW = 65536
    URLTEMPLATE_MEDLOW = 66816
    URLTEMPLATE_MEDIUM = 69632
    URLTEMPLATE_MEDHIGH = 70912
    URLTEMPLATE_HIGH = 73728
    URLTEMPLATE_PREDEFINED_MAX = 131072
  end

  enum INET_ZONE_MANAGER_CONSTANTS : Int32
    MAX_ZONE_PATH = 260
    MAX_ZONE_DESCRIPTION = 200
  end

  enum ZAFLAGS : Int32
    ZAFLAGS_CUSTOM_EDIT = 1
    ZAFLAGS_ADD_SITES = 2
    ZAFLAGS_REQUIRE_VERIFICATION = 4
    ZAFLAGS_INCLUDE_PROXY_OVERRIDE = 8
    ZAFLAGS_INCLUDE_INTRANET_SITES = 16
    ZAFLAGS_NO_UI = 32
    ZAFLAGS_SUPPORTS_VERIFICATION = 64
    ZAFLAGS_UNC_AS_INTRANET = 128
    ZAFLAGS_DETECT_INTRANET = 256
    ZAFLAGS_USE_LOCKED_ZONES = 65536
    ZAFLAGS_VERIFY_TEMPLATE_SETTINGS = 131072
    ZAFLAGS_NO_CACHE = 262144
  end

  enum URLZONEREG : Int32
    URLZONEREG_DEFAULT = 0
    URLZONEREG_HKLM = 1
    URLZONEREG_HKCU = 2
  end

  enum BINDHANDLETYPES : Int32
    BINDHANDLETYPES_APPCACHE = 0
    BINDHANDLETYPES_DEPENDENCY = 1
    BINDHANDLETYPES_COUNT = 2
  end

  struct REMSECURITY_ATTRIBUTES
    n_length : UInt32
    lp_security_descriptor : UInt32
    b_inherit_handle : LibC::BOOL
  end
  struct RemBINDINFO
    cb_size : UInt32
    sz_extra_info : LibC::LPWSTR
    grf_bind_info_f : UInt32
    dw_bind_verb : UInt32
    sz_custom_verb : LibC::LPWSTR
    cbstgmed_data : UInt32
    dw_options : UInt32
    dw_options_flags : UInt32
    dw_code_page : UInt32
    security_attributes : REMSECURITY_ATTRIBUTES
    iid : Guid
    p_unk : IUnknown
    dw_reserved : UInt32
  end
  struct RemFORMATETC
    cf_format : UInt32
    ptd : UInt32
    dw_aspect : UInt32
    lindex : Int32
    tymed : UInt32
  end
  struct PROTOCOLDATA
    grf_flags : UInt32
    dw_state : UInt32
    p_data : Void*
    cb_data : UInt32
  end
  struct StartParam
    iid : Guid
    p_i_bind_ctx : IBindCtx
    p_itf : IUnknown
  end
  struct ZONEATTRIBUTES
    cb_size : UInt32
    sz_display_name : Char[260]*
    sz_description : Char[200]*
    sz_icon_path : Char[260]*
    dw_template_min_level : UInt32
    dw_template_recommended : UInt32
    dw_template_current_level : UInt32
    dw_flags : UInt32
  end
  struct CODEBASEHOLD
    cb_size : UInt32
    sz_dist_unit : LibC::LPWSTR
    sz_code_base : LibC::LPWSTR
    dw_version_ms : UInt32
    dw_version_ls : UInt32
    dw_style : UInt32
  end
  struct SOFTDISTINFO
    cb_size : UInt32
    dw_flags : UInt32
    dw_ad_state : UInt32
    sz_title : LibC::LPWSTR
    sz_abstract : LibC::LPWSTR
    sz_href : LibC::LPWSTR
    dw_installed_version_ms : UInt32
    dw_installed_version_ls : UInt32
    dw_update_version_ms : UInt32
    dw_update_version_ls : UInt32
    dw_advertised_version_ms : UInt32
    dw_advertised_version_ls : UInt32
    dw_reserved : UInt32
  end
  struct PROTOCOLFILTERDATA
    cb_size : UInt32
    p_protocol_sink : IInternetProtocolSink
    p_protocol : IInternetProtocol
    p_unk : IUnknown
    dw_filter_flags : UInt32
  end
  struct DATAINFO
    ul_total_size : UInt32
    ulavr_packet_size : UInt32
    ul_connect_speed : UInt32
    ul_processor_speed : UInt32
  end
  struct HIT_LOGGING_INFO
    dw_struct_size : UInt32
    lpsz_logged_url_name : PSTR
    start_time : SYSTEMTIME
    end_time : SYSTEMTIME
    lpsz_extended_info : PSTR
  end
  struct CONFIRMSAFETY
    clsid : Guid
    p_unk : IUnknown
    dw_flags : UInt32
  end
  struct PROTOCOL_ARGUMENT
    sz_method : LibC::LPWSTR
    sz_target_url : LibC::LPWSTR
  end


  struct IPersistMonikerVTbl
    query_interface : Proc(IPersistMoniker*, Guid*, Void**, HRESULT)
    add_ref : Proc(IPersistMoniker*, UInt32)
    release : Proc(IPersistMoniker*, UInt32)
    get_class_id : Proc(IPersistMoniker*, Guid*, HRESULT)
    is_dirty : Proc(IPersistMoniker*, HRESULT)
    load : Proc(IPersistMoniker*, LibC::BOOL, IMoniker, IBindCtx, UInt32, HRESULT)
    save : Proc(IPersistMoniker*, IMoniker, IBindCtx, LibC::BOOL, HRESULT)
    save_completed : Proc(IPersistMoniker*, IMoniker, IBindCtx, HRESULT)
    get_cur_moniker : Proc(IPersistMoniker*, IMoniker*, HRESULT)
  end

  IPersistMoniker_GUID = LibC::GUID.new("79eac9c9-baf9-11ce-8c82-00aa004ba90b")
  CLSID_IPersistMoniker = "79eac9c9-baf9-11ce-8c82-00aa004ba90b"
  struct IPersistMoniker
    lpVtbl : IPersistMonikerVTbl*
  end

  struct IMonikerPropVTbl
    query_interface : Proc(IMonikerProp*, Guid*, Void**, HRESULT)
    add_ref : Proc(IMonikerProp*, UInt32)
    release : Proc(IMonikerProp*, UInt32)
    put_property : Proc(IMonikerProp*, MONIKERPROPERTY, LibC::LPWSTR, HRESULT)
  end

  IMonikerProp_GUID = LibC::GUID.new("a5ca5f7f-1847-4d87-9c5b-918509f7511d")
  CLSID_IMonikerProp = "a5ca5f7f-1847-4d87-9c5b-918509f7511d"
  struct IMonikerProp
    lpVtbl : IMonikerPropVTbl*
  end

  struct IBindProtocolVTbl
    query_interface : Proc(IBindProtocol*, Guid*, Void**, HRESULT)
    add_ref : Proc(IBindProtocol*, UInt32)
    release : Proc(IBindProtocol*, UInt32)
    create_binding : Proc(IBindProtocol*, LibC::LPWSTR, IBindCtx, IBinding*, HRESULT)
  end

  IBindProtocol_GUID = LibC::GUID.new("79eac9cd-baf9-11ce-8c82-00aa004ba90b")
  CLSID_IBindProtocol = "79eac9cd-baf9-11ce-8c82-00aa004ba90b"
  struct IBindProtocol
    lpVtbl : IBindProtocolVTbl*
  end

  struct IHttpNegotiateVTbl
    query_interface : Proc(IHttpNegotiate*, Guid*, Void**, HRESULT)
    add_ref : Proc(IHttpNegotiate*, UInt32)
    release : Proc(IHttpNegotiate*, UInt32)
    beginning_transaction : Proc(IHttpNegotiate*, LibC::LPWSTR, LibC::LPWSTR, UInt32, LibC::LPWSTR*, HRESULT)
    on_response : Proc(IHttpNegotiate*, UInt32, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR*, HRESULT)
  end

  IHttpNegotiate_GUID = LibC::GUID.new("79eac9d2-baf9-11ce-8c82-00aa004ba90b")
  CLSID_IHttpNegotiate = "79eac9d2-baf9-11ce-8c82-00aa004ba90b"
  struct IHttpNegotiate
    lpVtbl : IHttpNegotiateVTbl*
  end

  struct IHttpNegotiate2VTbl
    query_interface : Proc(IHttpNegotiate2*, Guid*, Void**, HRESULT)
    add_ref : Proc(IHttpNegotiate2*, UInt32)
    release : Proc(IHttpNegotiate2*, UInt32)
    beginning_transaction : Proc(IHttpNegotiate2*, LibC::LPWSTR, LibC::LPWSTR, UInt32, LibC::LPWSTR*, HRESULT)
    on_response : Proc(IHttpNegotiate2*, UInt32, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR*, HRESULT)
    get_root_security_id : Proc(IHttpNegotiate2*, UInt8*, UInt32*, LibC::UINT_PTR, HRESULT)
  end

  IHttpNegotiate2_GUID = LibC::GUID.new("4f9f9fcb-e0f4-48eb-b7ab-fa2ea9365cb4")
  CLSID_IHttpNegotiate2 = "4f9f9fcb-e0f4-48eb-b7ab-fa2ea9365cb4"
  struct IHttpNegotiate2
    lpVtbl : IHttpNegotiate2VTbl*
  end

  struct IHttpNegotiate3VTbl
    query_interface : Proc(IHttpNegotiate3*, Guid*, Void**, HRESULT)
    add_ref : Proc(IHttpNegotiate3*, UInt32)
    release : Proc(IHttpNegotiate3*, UInt32)
    beginning_transaction : Proc(IHttpNegotiate3*, LibC::LPWSTR, LibC::LPWSTR, UInt32, LibC::LPWSTR*, HRESULT)
    on_response : Proc(IHttpNegotiate3*, UInt32, LibC::LPWSTR, LibC::LPWSTR, LibC::LPWSTR*, HRESULT)
    get_root_security_id : Proc(IHttpNegotiate3*, UInt8*, UInt32*, LibC::UINT_PTR, HRESULT)
    get_serialized_client_cert_context : Proc(IHttpNegotiate3*, UInt8**, UInt32*, HRESULT)
  end

  IHttpNegotiate3_GUID = LibC::GUID.new("57b6c80a-34c2-4602-bc26-66a02fc57153")
  CLSID_IHttpNegotiate3 = "57b6c80a-34c2-4602-bc26-66a02fc57153"
  struct IHttpNegotiate3
    lpVtbl : IHttpNegotiate3VTbl*
  end

  struct IWinInetFileStreamVTbl
    query_interface : Proc(IWinInetFileStream*, Guid*, Void**, HRESULT)
    add_ref : Proc(IWinInetFileStream*, UInt32)
    release : Proc(IWinInetFileStream*, UInt32)
    set_handle_for_unlock : Proc(IWinInetFileStream*, LibC::UINT_PTR, LibC::UINT_PTR, HRESULT)
    set_delete_file : Proc(IWinInetFileStream*, LibC::UINT_PTR, HRESULT)
  end

  IWinInetFileStream_GUID = LibC::GUID.new("f134c4b7-b1f8-4e75-b886-74b90943becb")
  CLSID_IWinInetFileStream = "f134c4b7-b1f8-4e75-b886-74b90943becb"
  struct IWinInetFileStream
    lpVtbl : IWinInetFileStreamVTbl*
  end

  struct IWindowForBindingUIVTbl
    query_interface : Proc(IWindowForBindingUI*, Guid*, Void**, HRESULT)
    add_ref : Proc(IWindowForBindingUI*, UInt32)
    release : Proc(IWindowForBindingUI*, UInt32)
    get_window : Proc(IWindowForBindingUI*, Guid*, HANDLE*, HRESULT)
  end

  IWindowForBindingUI_GUID = LibC::GUID.new("79eac9d5-bafa-11ce-8c82-00aa004ba90b")
  CLSID_IWindowForBindingUI = "79eac9d5-bafa-11ce-8c82-00aa004ba90b"
  struct IWindowForBindingUI
    lpVtbl : IWindowForBindingUIVTbl*
  end

  struct ICodeInstallVTbl
    query_interface : Proc(ICodeInstall*, Guid*, Void**, HRESULT)
    add_ref : Proc(ICodeInstall*, UInt32)
    release : Proc(ICodeInstall*, UInt32)
    get_window : Proc(ICodeInstall*, Guid*, HANDLE*, HRESULT)
    on_code_install_problem : Proc(ICodeInstall*, UInt32, LibC::LPWSTR, LibC::LPWSTR, UInt32, HRESULT)
  end

  ICodeInstall_GUID = LibC::GUID.new("79eac9d1-baf9-11ce-8c82-00aa004ba90b")
  CLSID_ICodeInstall = "79eac9d1-baf9-11ce-8c82-00aa004ba90b"
  struct ICodeInstall
    lpVtbl : ICodeInstallVTbl*
  end

  struct IUriContainerVTbl
    query_interface : Proc(IUriContainer*, Guid*, Void**, HRESULT)
    add_ref : Proc(IUriContainer*, UInt32)
    release : Proc(IUriContainer*, UInt32)
    get_i_uri : Proc(IUriContainer*, IUri*, HRESULT)
  end

  IUriContainer_GUID = LibC::GUID.new("a158a630-ed6f-45fb-b987-f68676f57752")
  CLSID_IUriContainer = "a158a630-ed6f-45fb-b987-f68676f57752"
  struct IUriContainer
    lpVtbl : IUriContainerVTbl*
  end

  struct IUriBuilderFactoryVTbl
    query_interface : Proc(IUriBuilderFactory*, Guid*, Void**, HRESULT)
    add_ref : Proc(IUriBuilderFactory*, UInt32)
    release : Proc(IUriBuilderFactory*, UInt32)
    create_i_uri_builder : Proc(IUriBuilderFactory*, UInt32, LibC::UINT_PTR, IUriBuilder*, HRESULT)
    create_initialized_i_uri_builder : Proc(IUriBuilderFactory*, UInt32, LibC::UINT_PTR, IUriBuilder*, HRESULT)
  end

  IUriBuilderFactory_GUID = LibC::GUID.new("e982ce48-0b96-440c-bc37-0c869b27a29e")
  CLSID_IUriBuilderFactory = "e982ce48-0b96-440c-bc37-0c869b27a29e"
  struct IUriBuilderFactory
    lpVtbl : IUriBuilderFactoryVTbl*
  end

  struct IWinInetInfoVTbl
    query_interface : Proc(IWinInetInfo*, Guid*, Void**, HRESULT)
    add_ref : Proc(IWinInetInfo*, UInt32)
    release : Proc(IWinInetInfo*, UInt32)
    query_option : Proc(IWinInetInfo*, UInt32, Void*, UInt32*, HRESULT)
  end

  IWinInetInfo_GUID = LibC::GUID.new("79eac9d6-bafa-11ce-8c82-00aa004ba90b")
  CLSID_IWinInetInfo = "79eac9d6-bafa-11ce-8c82-00aa004ba90b"
  struct IWinInetInfo
    lpVtbl : IWinInetInfoVTbl*
  end

  struct IHttpSecurityVTbl
    query_interface : Proc(IHttpSecurity*, Guid*, Void**, HRESULT)
    add_ref : Proc(IHttpSecurity*, UInt32)
    release : Proc(IHttpSecurity*, UInt32)
    get_window : Proc(IHttpSecurity*, Guid*, HANDLE*, HRESULT)
    on_security_problem : Proc(IHttpSecurity*, UInt32, HRESULT)
  end

  IHttpSecurity_GUID = LibC::GUID.new("79eac9d7-bafa-11ce-8c82-00aa004ba90b")
  CLSID_IHttpSecurity = "79eac9d7-bafa-11ce-8c82-00aa004ba90b"
  struct IHttpSecurity
    lpVtbl : IHttpSecurityVTbl*
  end

  struct IWinInetHttpInfoVTbl
    query_interface : Proc(IWinInetHttpInfo*, Guid*, Void**, HRESULT)
    add_ref : Proc(IWinInetHttpInfo*, UInt32)
    release : Proc(IWinInetHttpInfo*, UInt32)
    query_option : Proc(IWinInetHttpInfo*, UInt32, Void*, UInt32*, HRESULT)
    query_info : Proc(IWinInetHttpInfo*, UInt32, Void*, UInt32*, UInt32*, UInt32*, HRESULT)
  end

  IWinInetHttpInfo_GUID = LibC::GUID.new("79eac9d8-bafa-11ce-8c82-00aa004ba90b")
  CLSID_IWinInetHttpInfo = "79eac9d8-bafa-11ce-8c82-00aa004ba90b"
  struct IWinInetHttpInfo
    lpVtbl : IWinInetHttpInfoVTbl*
  end

  struct IWinInetHttpTimeoutsVTbl
    query_interface : Proc(IWinInetHttpTimeouts*, Guid*, Void**, HRESULT)
    add_ref : Proc(IWinInetHttpTimeouts*, UInt32)
    release : Proc(IWinInetHttpTimeouts*, UInt32)
    get_request_timeouts : Proc(IWinInetHttpTimeouts*, UInt32*, UInt32*, UInt32*, HRESULT)
  end

  IWinInetHttpTimeouts_GUID = LibC::GUID.new("f286fa56-c1fd-4270-8e67-b3eb790a81e8")
  CLSID_IWinInetHttpTimeouts = "f286fa56-c1fd-4270-8e67-b3eb790a81e8"
  struct IWinInetHttpTimeouts
    lpVtbl : IWinInetHttpTimeoutsVTbl*
  end

  struct IWinInetCacheHintsVTbl
    query_interface : Proc(IWinInetCacheHints*, Guid*, Void**, HRESULT)
    add_ref : Proc(IWinInetCacheHints*, UInt32)
    release : Proc(IWinInetCacheHints*, UInt32)
    set_cache_extension : Proc(IWinInetCacheHints*, LibC::LPWSTR, Void*, UInt32*, UInt32*, UInt32*, HRESULT)
  end

  IWinInetCacheHints_GUID = LibC::GUID.new("dd1ec3b3-8391-4fdb-a9e6-347c3caaa7dd")
  CLSID_IWinInetCacheHints = "dd1ec3b3-8391-4fdb-a9e6-347c3caaa7dd"
  struct IWinInetCacheHints
    lpVtbl : IWinInetCacheHintsVTbl*
  end

  struct IWinInetCacheHints2VTbl
    query_interface : Proc(IWinInetCacheHints2*, Guid*, Void**, HRESULT)
    add_ref : Proc(IWinInetCacheHints2*, UInt32)
    release : Proc(IWinInetCacheHints2*, UInt32)
    set_cache_extension : Proc(IWinInetCacheHints2*, LibC::LPWSTR, Void*, UInt32*, UInt32*, UInt32*, HRESULT)
    set_cache_extension2 : Proc(IWinInetCacheHints2*, LibC::LPWSTR, LibC::LPWSTR, UInt32*, UInt32*, UInt32*, HRESULT)
  end

  IWinInetCacheHints2_GUID = LibC::GUID.new("7857aeac-d31f-49bf-884e-dd46df36780a")
  CLSID_IWinInetCacheHints2 = "7857aeac-d31f-49bf-884e-dd46df36780a"
  struct IWinInetCacheHints2
    lpVtbl : IWinInetCacheHints2VTbl*
  end

  struct IInternetVTbl
    query_interface : Proc(IInternet*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternet*, UInt32)
    release : Proc(IInternet*, UInt32)
  end

  IInternet_GUID = LibC::GUID.new("79eac9e0-baf9-11ce-8c82-00aa004ba90b")
  CLSID_IInternet = "79eac9e0-baf9-11ce-8c82-00aa004ba90b"
  struct IInternet
    lpVtbl : IInternetVTbl*
  end

  struct IInternetBindInfoVTbl
    query_interface : Proc(IInternetBindInfo*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetBindInfo*, UInt32)
    release : Proc(IInternetBindInfo*, UInt32)
    get_bind_info : Proc(IInternetBindInfo*, UInt32*, BINDINFO*, HRESULT)
    get_bind_string : Proc(IInternetBindInfo*, UInt32, LibC::LPWSTR*, UInt32, UInt32*, HRESULT)
  end

  IInternetBindInfo_GUID = LibC::GUID.new("79eac9e1-baf9-11ce-8c82-00aa004ba90b")
  CLSID_IInternetBindInfo = "79eac9e1-baf9-11ce-8c82-00aa004ba90b"
  struct IInternetBindInfo
    lpVtbl : IInternetBindInfoVTbl*
  end

  struct IInternetBindInfoExVTbl
    query_interface : Proc(IInternetBindInfoEx*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetBindInfoEx*, UInt32)
    release : Proc(IInternetBindInfoEx*, UInt32)
    get_bind_info : Proc(IInternetBindInfoEx*, UInt32*, BINDINFO*, HRESULT)
    get_bind_string : Proc(IInternetBindInfoEx*, UInt32, LibC::LPWSTR*, UInt32, UInt32*, HRESULT)
    get_bind_info_ex : Proc(IInternetBindInfoEx*, UInt32*, BINDINFO*, UInt32*, UInt32*, HRESULT)
  end

  IInternetBindInfoEx_GUID = LibC::GUID.new("a3e015b7-a82c-4dcd-a150-569aeeed36ab")
  CLSID_IInternetBindInfoEx = "a3e015b7-a82c-4dcd-a150-569aeeed36ab"
  struct IInternetBindInfoEx
    lpVtbl : IInternetBindInfoExVTbl*
  end

  struct IInternetProtocolRootVTbl
    query_interface : Proc(IInternetProtocolRoot*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetProtocolRoot*, UInt32)
    release : Proc(IInternetProtocolRoot*, UInt32)
    start : Proc(IInternetProtocolRoot*, LibC::LPWSTR, IInternetProtocolSink, IInternetBindInfo, UInt32, HANDLE_PTR, HRESULT)
    continue : Proc(IInternetProtocolRoot*, PROTOCOLDATA*, HRESULT)
    abort : Proc(IInternetProtocolRoot*, HRESULT, UInt32, HRESULT)
    terminate : Proc(IInternetProtocolRoot*, UInt32, HRESULT)
    suspend : Proc(IInternetProtocolRoot*, HRESULT)
    resume : Proc(IInternetProtocolRoot*, HRESULT)
  end

  IInternetProtocolRoot_GUID = LibC::GUID.new("79eac9e3-baf9-11ce-8c82-00aa004ba90b")
  CLSID_IInternetProtocolRoot = "79eac9e3-baf9-11ce-8c82-00aa004ba90b"
  struct IInternetProtocolRoot
    lpVtbl : IInternetProtocolRootVTbl*
  end

  struct IInternetProtocolVTbl
    query_interface : Proc(IInternetProtocol*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetProtocol*, UInt32)
    release : Proc(IInternetProtocol*, UInt32)
    start : Proc(IInternetProtocol*, LibC::LPWSTR, IInternetProtocolSink, IInternetBindInfo, UInt32, HANDLE_PTR, HRESULT)
    continue : Proc(IInternetProtocol*, PROTOCOLDATA*, HRESULT)
    abort : Proc(IInternetProtocol*, HRESULT, UInt32, HRESULT)
    terminate : Proc(IInternetProtocol*, UInt32, HRESULT)
    suspend : Proc(IInternetProtocol*, HRESULT)
    resume : Proc(IInternetProtocol*, HRESULT)
    read : Proc(IInternetProtocol*, Void*, UInt32, UInt32*, HRESULT)
    seek : Proc(IInternetProtocol*, LARGE_INTEGER, UInt32, ULARGE_INTEGER*, HRESULT)
    lock_request : Proc(IInternetProtocol*, UInt32, HRESULT)
    unlock_request : Proc(IInternetProtocol*, HRESULT)
  end

  IInternetProtocol_GUID = LibC::GUID.new("79eac9e4-baf9-11ce-8c82-00aa004ba90b")
  CLSID_IInternetProtocol = "79eac9e4-baf9-11ce-8c82-00aa004ba90b"
  struct IInternetProtocol
    lpVtbl : IInternetProtocolVTbl*
  end

  struct IInternetProtocolExVTbl
    query_interface : Proc(IInternetProtocolEx*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetProtocolEx*, UInt32)
    release : Proc(IInternetProtocolEx*, UInt32)
    start : Proc(IInternetProtocolEx*, LibC::LPWSTR, IInternetProtocolSink, IInternetBindInfo, UInt32, HANDLE_PTR, HRESULT)
    continue : Proc(IInternetProtocolEx*, PROTOCOLDATA*, HRESULT)
    abort : Proc(IInternetProtocolEx*, HRESULT, UInt32, HRESULT)
    terminate : Proc(IInternetProtocolEx*, UInt32, HRESULT)
    suspend : Proc(IInternetProtocolEx*, HRESULT)
    resume : Proc(IInternetProtocolEx*, HRESULT)
    read : Proc(IInternetProtocolEx*, Void*, UInt32, UInt32*, HRESULT)
    seek : Proc(IInternetProtocolEx*, LARGE_INTEGER, UInt32, ULARGE_INTEGER*, HRESULT)
    lock_request : Proc(IInternetProtocolEx*, UInt32, HRESULT)
    unlock_request : Proc(IInternetProtocolEx*, HRESULT)
    start_ex : Proc(IInternetProtocolEx*, IUri, IInternetProtocolSink, IInternetBindInfo, UInt32, HANDLE_PTR, HRESULT)
  end

  IInternetProtocolEx_GUID = LibC::GUID.new("c7a98e66-1010-492c-a1c8-c809e1f75905")
  CLSID_IInternetProtocolEx = "c7a98e66-1010-492c-a1c8-c809e1f75905"
  struct IInternetProtocolEx
    lpVtbl : IInternetProtocolExVTbl*
  end

  struct IInternetProtocolSinkVTbl
    query_interface : Proc(IInternetProtocolSink*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetProtocolSink*, UInt32)
    release : Proc(IInternetProtocolSink*, UInt32)
    switch : Proc(IInternetProtocolSink*, PROTOCOLDATA*, HRESULT)
    report_progress : Proc(IInternetProtocolSink*, UInt32, LibC::LPWSTR, HRESULT)
    report_data : Proc(IInternetProtocolSink*, UInt32, UInt32, UInt32, HRESULT)
    report_result : Proc(IInternetProtocolSink*, HRESULT, UInt32, LibC::LPWSTR, HRESULT)
  end

  IInternetProtocolSink_GUID = LibC::GUID.new("79eac9e5-baf9-11ce-8c82-00aa004ba90b")
  CLSID_IInternetProtocolSink = "79eac9e5-baf9-11ce-8c82-00aa004ba90b"
  struct IInternetProtocolSink
    lpVtbl : IInternetProtocolSinkVTbl*
  end

  struct IInternetProtocolSinkStackableVTbl
    query_interface : Proc(IInternetProtocolSinkStackable*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetProtocolSinkStackable*, UInt32)
    release : Proc(IInternetProtocolSinkStackable*, UInt32)
    switch_sink : Proc(IInternetProtocolSinkStackable*, IInternetProtocolSink, HRESULT)
    commit_switch : Proc(IInternetProtocolSinkStackable*, HRESULT)
    rollback_switch : Proc(IInternetProtocolSinkStackable*, HRESULT)
  end

  IInternetProtocolSinkStackable_GUID = LibC::GUID.new("79eac9f0-baf9-11ce-8c82-00aa004ba90b")
  CLSID_IInternetProtocolSinkStackable = "79eac9f0-baf9-11ce-8c82-00aa004ba90b"
  struct IInternetProtocolSinkStackable
    lpVtbl : IInternetProtocolSinkStackableVTbl*
  end

  struct IInternetSessionVTbl
    query_interface : Proc(IInternetSession*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetSession*, UInt32)
    release : Proc(IInternetSession*, UInt32)
    register_name_space : Proc(IInternetSession*, IClassFactory, Guid*, LibC::LPWSTR, UInt32, LibC::LPWSTR*, UInt32, HRESULT)
    unregister_name_space : Proc(IInternetSession*, IClassFactory, LibC::LPWSTR, HRESULT)
    register_mime_filter : Proc(IInternetSession*, IClassFactory, Guid*, LibC::LPWSTR, HRESULT)
    unregister_mime_filter : Proc(IInternetSession*, IClassFactory, LibC::LPWSTR, HRESULT)
    create_binding : Proc(IInternetSession*, IBindCtx, LibC::LPWSTR, IUnknown, IUnknown*, IInternetProtocol*, UInt32, HRESULT)
    set_session_option : Proc(IInternetSession*, UInt32, Void*, UInt32, UInt32, HRESULT)
    get_session_option : Proc(IInternetSession*, UInt32, Void*, UInt32*, UInt32, HRESULT)
  end

  IInternetSession_GUID = LibC::GUID.new("79eac9e7-baf9-11ce-8c82-00aa004ba90b")
  CLSID_IInternetSession = "79eac9e7-baf9-11ce-8c82-00aa004ba90b"
  struct IInternetSession
    lpVtbl : IInternetSessionVTbl*
  end

  struct IInternetThreadSwitchVTbl
    query_interface : Proc(IInternetThreadSwitch*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetThreadSwitch*, UInt32)
    release : Proc(IInternetThreadSwitch*, UInt32)
    prepare : Proc(IInternetThreadSwitch*, HRESULT)
    continue : Proc(IInternetThreadSwitch*, HRESULT)
  end

  IInternetThreadSwitch_GUID = LibC::GUID.new("79eac9e8-baf9-11ce-8c82-00aa004ba90b")
  CLSID_IInternetThreadSwitch = "79eac9e8-baf9-11ce-8c82-00aa004ba90b"
  struct IInternetThreadSwitch
    lpVtbl : IInternetThreadSwitchVTbl*
  end

  struct IInternetPriorityVTbl
    query_interface : Proc(IInternetPriority*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetPriority*, UInt32)
    release : Proc(IInternetPriority*, UInt32)
    set_priority : Proc(IInternetPriority*, Int32, HRESULT)
    get_priority : Proc(IInternetPriority*, Int32*, HRESULT)
  end

  IInternetPriority_GUID = LibC::GUID.new("79eac9eb-baf9-11ce-8c82-00aa004ba90b")
  CLSID_IInternetPriority = "79eac9eb-baf9-11ce-8c82-00aa004ba90b"
  struct IInternetPriority
    lpVtbl : IInternetPriorityVTbl*
  end

  struct IInternetProtocolInfoVTbl
    query_interface : Proc(IInternetProtocolInfo*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetProtocolInfo*, UInt32)
    release : Proc(IInternetProtocolInfo*, UInt32)
    parse_url : Proc(IInternetProtocolInfo*, LibC::LPWSTR, PARSEACTION, UInt32, LibC::LPWSTR, UInt32, UInt32*, UInt32, HRESULT)
    combine_url : Proc(IInternetProtocolInfo*, LibC::LPWSTR, LibC::LPWSTR, UInt32, LibC::LPWSTR, UInt32, UInt32*, UInt32, HRESULT)
    compare_url : Proc(IInternetProtocolInfo*, LibC::LPWSTR, LibC::LPWSTR, UInt32, HRESULT)
    query_info : Proc(IInternetProtocolInfo*, LibC::LPWSTR, QUERYOPTION, UInt32, Void*, UInt32, UInt32*, UInt32, HRESULT)
  end

  IInternetProtocolInfo_GUID = LibC::GUID.new("79eac9ec-baf9-11ce-8c82-00aa004ba90b")
  CLSID_IInternetProtocolInfo = "79eac9ec-baf9-11ce-8c82-00aa004ba90b"
  struct IInternetProtocolInfo
    lpVtbl : IInternetProtocolInfoVTbl*
  end

  struct IInternetSecurityMgrSiteVTbl
    query_interface : Proc(IInternetSecurityMgrSite*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetSecurityMgrSite*, UInt32)
    release : Proc(IInternetSecurityMgrSite*, UInt32)
    get_window : Proc(IInternetSecurityMgrSite*, HANDLE*, HRESULT)
    enable_modeless : Proc(IInternetSecurityMgrSite*, LibC::BOOL, HRESULT)
  end

  IInternetSecurityMgrSite_GUID = LibC::GUID.new("79eac9ed-baf9-11ce-8c82-00aa004ba90b")
  CLSID_IInternetSecurityMgrSite = "79eac9ed-baf9-11ce-8c82-00aa004ba90b"
  struct IInternetSecurityMgrSite
    lpVtbl : IInternetSecurityMgrSiteVTbl*
  end

  struct IInternetSecurityManagerVTbl
    query_interface : Proc(IInternetSecurityManager*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetSecurityManager*, UInt32)
    release : Proc(IInternetSecurityManager*, UInt32)
    set_security_site : Proc(IInternetSecurityManager*, IInternetSecurityMgrSite, HRESULT)
    get_security_site : Proc(IInternetSecurityManager*, IInternetSecurityMgrSite*, HRESULT)
    map_url_to_zone : Proc(IInternetSecurityManager*, LibC::LPWSTR, UInt32*, UInt32, HRESULT)
    get_security_id : Proc(IInternetSecurityManager*, LibC::LPWSTR, UInt8*, UInt32*, LibC::UINT_PTR, HRESULT)
    process_url_action : Proc(IInternetSecurityManager*, LibC::LPWSTR, UInt32, UInt8*, UInt32, UInt8*, UInt32, UInt32, UInt32, HRESULT)
    query_custom_policy : Proc(IInternetSecurityManager*, LibC::LPWSTR, Guid*, UInt8**, UInt32*, UInt8*, UInt32, UInt32, HRESULT)
    set_zone_mapping : Proc(IInternetSecurityManager*, UInt32, LibC::LPWSTR, UInt32, HRESULT)
    get_zone_mappings : Proc(IInternetSecurityManager*, UInt32, IEnumString*, UInt32, HRESULT)
  end

  IInternetSecurityManager_GUID = LibC::GUID.new("79eac9ee-baf9-11ce-8c82-00aa004ba90b")
  CLSID_IInternetSecurityManager = "79eac9ee-baf9-11ce-8c82-00aa004ba90b"
  struct IInternetSecurityManager
    lpVtbl : IInternetSecurityManagerVTbl*
  end

  struct IInternetSecurityManagerExVTbl
    query_interface : Proc(IInternetSecurityManagerEx*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetSecurityManagerEx*, UInt32)
    release : Proc(IInternetSecurityManagerEx*, UInt32)
    set_security_site : Proc(IInternetSecurityManagerEx*, IInternetSecurityMgrSite, HRESULT)
    get_security_site : Proc(IInternetSecurityManagerEx*, IInternetSecurityMgrSite*, HRESULT)
    map_url_to_zone : Proc(IInternetSecurityManagerEx*, LibC::LPWSTR, UInt32*, UInt32, HRESULT)
    get_security_id : Proc(IInternetSecurityManagerEx*, LibC::LPWSTR, UInt8*, UInt32*, LibC::UINT_PTR, HRESULT)
    process_url_action : Proc(IInternetSecurityManagerEx*, LibC::LPWSTR, UInt32, UInt8*, UInt32, UInt8*, UInt32, UInt32, UInt32, HRESULT)
    query_custom_policy : Proc(IInternetSecurityManagerEx*, LibC::LPWSTR, Guid*, UInt8**, UInt32*, UInt8*, UInt32, UInt32, HRESULT)
    set_zone_mapping : Proc(IInternetSecurityManagerEx*, UInt32, LibC::LPWSTR, UInt32, HRESULT)
    get_zone_mappings : Proc(IInternetSecurityManagerEx*, UInt32, IEnumString*, UInt32, HRESULT)
    process_url_action_ex : Proc(IInternetSecurityManagerEx*, LibC::LPWSTR, UInt32, UInt8*, UInt32, UInt8*, UInt32, UInt32, UInt32, UInt32*, HRESULT)
  end

  IInternetSecurityManagerEx_GUID = LibC::GUID.new("f164edf1-cc7c-4f0d-9a94-34222625c393")
  CLSID_IInternetSecurityManagerEx = "f164edf1-cc7c-4f0d-9a94-34222625c393"
  struct IInternetSecurityManagerEx
    lpVtbl : IInternetSecurityManagerExVTbl*
  end

  struct IInternetSecurityManagerEx2VTbl
    query_interface : Proc(IInternetSecurityManagerEx2*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetSecurityManagerEx2*, UInt32)
    release : Proc(IInternetSecurityManagerEx2*, UInt32)
    set_security_site : Proc(IInternetSecurityManagerEx2*, IInternetSecurityMgrSite, HRESULT)
    get_security_site : Proc(IInternetSecurityManagerEx2*, IInternetSecurityMgrSite*, HRESULT)
    map_url_to_zone : Proc(IInternetSecurityManagerEx2*, LibC::LPWSTR, UInt32*, UInt32, HRESULT)
    get_security_id : Proc(IInternetSecurityManagerEx2*, LibC::LPWSTR, UInt8*, UInt32*, LibC::UINT_PTR, HRESULT)
    process_url_action : Proc(IInternetSecurityManagerEx2*, LibC::LPWSTR, UInt32, UInt8*, UInt32, UInt8*, UInt32, UInt32, UInt32, HRESULT)
    query_custom_policy : Proc(IInternetSecurityManagerEx2*, LibC::LPWSTR, Guid*, UInt8**, UInt32*, UInt8*, UInt32, UInt32, HRESULT)
    set_zone_mapping : Proc(IInternetSecurityManagerEx2*, UInt32, LibC::LPWSTR, UInt32, HRESULT)
    get_zone_mappings : Proc(IInternetSecurityManagerEx2*, UInt32, IEnumString*, UInt32, HRESULT)
    process_url_action_ex : Proc(IInternetSecurityManagerEx2*, LibC::LPWSTR, UInt32, UInt8*, UInt32, UInt8*, UInt32, UInt32, UInt32, UInt32*, HRESULT)
    map_url_to_zone_ex2 : Proc(IInternetSecurityManagerEx2*, IUri, UInt32*, UInt32, LibC::LPWSTR*, UInt32*, HRESULT)
    process_url_action_ex2 : Proc(IInternetSecurityManagerEx2*, IUri, UInt32, UInt8*, UInt32, UInt8*, UInt32, UInt32, LibC::UINT_PTR, UInt32*, HRESULT)
    get_security_id_ex2 : Proc(IInternetSecurityManagerEx2*, IUri, UInt8*, UInt32*, LibC::UINT_PTR, HRESULT)
    query_custom_policy_ex2 : Proc(IInternetSecurityManagerEx2*, IUri, Guid*, UInt8**, UInt32*, UInt8*, UInt32, LibC::UINT_PTR, HRESULT)
  end

  IInternetSecurityManagerEx2_GUID = LibC::GUID.new("f1e50292-a795-4117-8e09-2b560a72ac60")
  CLSID_IInternetSecurityManagerEx2 = "f1e50292-a795-4117-8e09-2b560a72ac60"
  struct IInternetSecurityManagerEx2
    lpVtbl : IInternetSecurityManagerEx2VTbl*
  end

  struct IZoneIdentifierVTbl
    query_interface : Proc(IZoneIdentifier*, Guid*, Void**, HRESULT)
    add_ref : Proc(IZoneIdentifier*, UInt32)
    release : Proc(IZoneIdentifier*, UInt32)
    get_id : Proc(IZoneIdentifier*, UInt32*, HRESULT)
    set_id : Proc(IZoneIdentifier*, UInt32, HRESULT)
    remove : Proc(IZoneIdentifier*, HRESULT)
  end

  IZoneIdentifier_GUID = LibC::GUID.new("cd45f185-1b21-48e2-967b-ead743a8914e")
  CLSID_IZoneIdentifier = "cd45f185-1b21-48e2-967b-ead743a8914e"
  struct IZoneIdentifier
    lpVtbl : IZoneIdentifierVTbl*
  end

  struct IZoneIdentifier2VTbl
    query_interface : Proc(IZoneIdentifier2*, Guid*, Void**, HRESULT)
    add_ref : Proc(IZoneIdentifier2*, UInt32)
    release : Proc(IZoneIdentifier2*, UInt32)
    get_id : Proc(IZoneIdentifier2*, UInt32*, HRESULT)
    set_id : Proc(IZoneIdentifier2*, UInt32, HRESULT)
    remove : Proc(IZoneIdentifier2*, HRESULT)
    get_last_writer_package_family_name : Proc(IZoneIdentifier2*, LibC::LPWSTR*, HRESULT)
    set_last_writer_package_family_name : Proc(IZoneIdentifier2*, LibC::LPWSTR, HRESULT)
    remove_last_writer_package_family_name : Proc(IZoneIdentifier2*, HRESULT)
    get_app_zone_id : Proc(IZoneIdentifier2*, UInt32*, HRESULT)
    set_app_zone_id : Proc(IZoneIdentifier2*, UInt32, HRESULT)
    remove_app_zone_id : Proc(IZoneIdentifier2*, HRESULT)
  end

  IZoneIdentifier2_GUID = LibC::GUID.new("eb5e760c-09ef-45c0-b510-70830ce31e6a")
  CLSID_IZoneIdentifier2 = "eb5e760c-09ef-45c0-b510-70830ce31e6a"
  struct IZoneIdentifier2
    lpVtbl : IZoneIdentifier2VTbl*
  end

  struct IInternetHostSecurityManagerVTbl
    query_interface : Proc(IInternetHostSecurityManager*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetHostSecurityManager*, UInt32)
    release : Proc(IInternetHostSecurityManager*, UInt32)
    get_security_id : Proc(IInternetHostSecurityManager*, UInt8*, UInt32*, LibC::UINT_PTR, HRESULT)
    process_url_action : Proc(IInternetHostSecurityManager*, UInt32, UInt8*, UInt32, UInt8*, UInt32, UInt32, UInt32, HRESULT)
    query_custom_policy : Proc(IInternetHostSecurityManager*, Guid*, UInt8**, UInt32*, UInt8*, UInt32, UInt32, HRESULT)
  end

  IInternetHostSecurityManager_GUID = LibC::GUID.new("3af280b6-cb3f-11d0-891e-00c04fb6bfc4")
  CLSID_IInternetHostSecurityManager = "3af280b6-cb3f-11d0-891e-00c04fb6bfc4"
  struct IInternetHostSecurityManager
    lpVtbl : IInternetHostSecurityManagerVTbl*
  end

  struct IInternetZoneManagerVTbl
    query_interface : Proc(IInternetZoneManager*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetZoneManager*, UInt32)
    release : Proc(IInternetZoneManager*, UInt32)
    get_zone_attributes : Proc(IInternetZoneManager*, UInt32, ZONEATTRIBUTES*, HRESULT)
    set_zone_attributes : Proc(IInternetZoneManager*, UInt32, ZONEATTRIBUTES*, HRESULT)
    get_zone_custom_policy : Proc(IInternetZoneManager*, UInt32, Guid*, UInt8**, UInt32*, URLZONEREG, HRESULT)
    set_zone_custom_policy : Proc(IInternetZoneManager*, UInt32, Guid*, UInt8*, UInt32, URLZONEREG, HRESULT)
    get_zone_action_policy : Proc(IInternetZoneManager*, UInt32, UInt32, UInt8*, UInt32, URLZONEREG, HRESULT)
    set_zone_action_policy : Proc(IInternetZoneManager*, UInt32, UInt32, UInt8*, UInt32, URLZONEREG, HRESULT)
    prompt_action : Proc(IInternetZoneManager*, UInt32, LibC::HANDLE, LibC::LPWSTR, LibC::LPWSTR, UInt32, HRESULT)
    log_action : Proc(IInternetZoneManager*, UInt32, LibC::LPWSTR, LibC::LPWSTR, UInt32, HRESULT)
    create_zone_enumerator : Proc(IInternetZoneManager*, UInt32*, UInt32*, UInt32, HRESULT)
    get_zone_at : Proc(IInternetZoneManager*, UInt32, UInt32, UInt32*, HRESULT)
    destroy_zone_enumerator : Proc(IInternetZoneManager*, UInt32, HRESULT)
    copy_template_policies_to_zone : Proc(IInternetZoneManager*, UInt32, UInt32, UInt32, HRESULT)
  end

  IInternetZoneManager_GUID = LibC::GUID.new("79eac9ef-baf9-11ce-8c82-00aa004ba90b")
  CLSID_IInternetZoneManager = "79eac9ef-baf9-11ce-8c82-00aa004ba90b"
  struct IInternetZoneManager
    lpVtbl : IInternetZoneManagerVTbl*
  end

  struct IInternetZoneManagerExVTbl
    query_interface : Proc(IInternetZoneManagerEx*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetZoneManagerEx*, UInt32)
    release : Proc(IInternetZoneManagerEx*, UInt32)
    get_zone_attributes : Proc(IInternetZoneManagerEx*, UInt32, ZONEATTRIBUTES*, HRESULT)
    set_zone_attributes : Proc(IInternetZoneManagerEx*, UInt32, ZONEATTRIBUTES*, HRESULT)
    get_zone_custom_policy : Proc(IInternetZoneManagerEx*, UInt32, Guid*, UInt8**, UInt32*, URLZONEREG, HRESULT)
    set_zone_custom_policy : Proc(IInternetZoneManagerEx*, UInt32, Guid*, UInt8*, UInt32, URLZONEREG, HRESULT)
    get_zone_action_policy : Proc(IInternetZoneManagerEx*, UInt32, UInt32, UInt8*, UInt32, URLZONEREG, HRESULT)
    set_zone_action_policy : Proc(IInternetZoneManagerEx*, UInt32, UInt32, UInt8*, UInt32, URLZONEREG, HRESULT)
    prompt_action : Proc(IInternetZoneManagerEx*, UInt32, LibC::HANDLE, LibC::LPWSTR, LibC::LPWSTR, UInt32, HRESULT)
    log_action : Proc(IInternetZoneManagerEx*, UInt32, LibC::LPWSTR, LibC::LPWSTR, UInt32, HRESULT)
    create_zone_enumerator : Proc(IInternetZoneManagerEx*, UInt32*, UInt32*, UInt32, HRESULT)
    get_zone_at : Proc(IInternetZoneManagerEx*, UInt32, UInt32, UInt32*, HRESULT)
    destroy_zone_enumerator : Proc(IInternetZoneManagerEx*, UInt32, HRESULT)
    copy_template_policies_to_zone : Proc(IInternetZoneManagerEx*, UInt32, UInt32, UInt32, HRESULT)
    get_zone_action_policy_ex : Proc(IInternetZoneManagerEx*, UInt32, UInt32, UInt8*, UInt32, URLZONEREG, UInt32, HRESULT)
    set_zone_action_policy_ex : Proc(IInternetZoneManagerEx*, UInt32, UInt32, UInt8*, UInt32, URLZONEREG, UInt32, HRESULT)
  end

  IInternetZoneManagerEx_GUID = LibC::GUID.new("a4c23339-8e06-431e-9bf4-7e711c085648")
  CLSID_IInternetZoneManagerEx = "a4c23339-8e06-431e-9bf4-7e711c085648"
  struct IInternetZoneManagerEx
    lpVtbl : IInternetZoneManagerExVTbl*
  end

  struct IInternetZoneManagerEx2VTbl
    query_interface : Proc(IInternetZoneManagerEx2*, Guid*, Void**, HRESULT)
    add_ref : Proc(IInternetZoneManagerEx2*, UInt32)
    release : Proc(IInternetZoneManagerEx2*, UInt32)
    get_zone_attributes : Proc(IInternetZoneManagerEx2*, UInt32, ZONEATTRIBUTES*, HRESULT)
    set_zone_attributes : Proc(IInternetZoneManagerEx2*, UInt32, ZONEATTRIBUTES*, HRESULT)
    get_zone_custom_policy : Proc(IInternetZoneManagerEx2*, UInt32, Guid*, UInt8**, UInt32*, URLZONEREG, HRESULT)
    set_zone_custom_policy : Proc(IInternetZoneManagerEx2*, UInt32, Guid*, UInt8*, UInt32, URLZONEREG, HRESULT)
    get_zone_action_policy : Proc(IInternetZoneManagerEx2*, UInt32, UInt32, UInt8*, UInt32, URLZONEREG, HRESULT)
    set_zone_action_policy : Proc(IInternetZoneManagerEx2*, UInt32, UInt32, UInt8*, UInt32, URLZONEREG, HRESULT)
    prompt_action : Proc(IInternetZoneManagerEx2*, UInt32, LibC::HANDLE, LibC::LPWSTR, LibC::LPWSTR, UInt32, HRESULT)
    log_action : Proc(IInternetZoneManagerEx2*, UInt32, LibC::LPWSTR, LibC::LPWSTR, UInt32, HRESULT)
    create_zone_enumerator : Proc(IInternetZoneManagerEx2*, UInt32*, UInt32*, UInt32, HRESULT)
    get_zone_at : Proc(IInternetZoneManagerEx2*, UInt32, UInt32, UInt32*, HRESULT)
    destroy_zone_enumerator : Proc(IInternetZoneManagerEx2*, UInt32, HRESULT)
    copy_template_policies_to_zone : Proc(IInternetZoneManagerEx2*, UInt32, UInt32, UInt32, HRESULT)
    get_zone_action_policy_ex : Proc(IInternetZoneManagerEx2*, UInt32, UInt32, UInt8*, UInt32, URLZONEREG, UInt32, HRESULT)
    set_zone_action_policy_ex : Proc(IInternetZoneManagerEx2*, UInt32, UInt32, UInt8*, UInt32, URLZONEREG, UInt32, HRESULT)
    get_zone_attributes_ex : Proc(IInternetZoneManagerEx2*, UInt32, ZONEATTRIBUTES*, UInt32, HRESULT)
    get_zone_security_state : Proc(IInternetZoneManagerEx2*, UInt32, LibC::BOOL, UInt32*, LibC::BOOL*, HRESULT)
    get_ie_security_state : Proc(IInternetZoneManagerEx2*, LibC::BOOL, UInt32*, LibC::BOOL*, LibC::BOOL, HRESULT)
    fix_unsecure_settings : Proc(IInternetZoneManagerEx2*, HRESULT)
  end

  IInternetZoneManagerEx2_GUID = LibC::GUID.new("edc17559-dd5d-4846-8eef-8becba5a4abf")
  CLSID_IInternetZoneManagerEx2 = "edc17559-dd5d-4846-8eef-8becba5a4abf"
  struct IInternetZoneManagerEx2
    lpVtbl : IInternetZoneManagerEx2VTbl*
  end

  struct ISoftDistExtVTbl
    query_interface : Proc(ISoftDistExt*, Guid*, Void**, HRESULT)
    add_ref : Proc(ISoftDistExt*, UInt32)
    release : Proc(ISoftDistExt*, UInt32)
    process_soft_dist : Proc(ISoftDistExt*, LibC::LPWSTR, IXMLElement, SOFTDISTINFO*, HRESULT)
    get_first_code_base : Proc(ISoftDistExt*, LibC::LPWSTR*, UInt32*, HRESULT)
    get_next_code_base : Proc(ISoftDistExt*, LibC::LPWSTR*, UInt32*, HRESULT)
    async_install_distribution_unit : Proc(ISoftDistExt*, IBindCtx, Void*, UInt32, CODEBASEHOLD*, HRESULT)
  end

  ISoftDistExt_GUID = LibC::GUID.new("b15b8dc1-c7e1-11d0-8680-00aa00bdcb71")
  CLSID_ISoftDistExt = "b15b8dc1-c7e1-11d0-8680-00aa00bdcb71"
  struct ISoftDistExt
    lpVtbl : ISoftDistExtVTbl*
  end

  struct ICatalogFileInfoVTbl
    query_interface : Proc(ICatalogFileInfo*, Guid*, Void**, HRESULT)
    add_ref : Proc(ICatalogFileInfo*, UInt32)
    release : Proc(ICatalogFileInfo*, UInt32)
    get_catalog_file : Proc(ICatalogFileInfo*, PSTR*, HRESULT)
    get_java_trust : Proc(ICatalogFileInfo*, Void**, HRESULT)
  end

  ICatalogFileInfo_GUID = LibC::GUID.new("711c7600-6b48-11d1-b403-00aa00b92af1")
  CLSID_ICatalogFileInfo = "711c7600-6b48-11d1-b403-00aa00b92af1"
  struct ICatalogFileInfo
    lpVtbl : ICatalogFileInfoVTbl*
  end

  struct IDataFilterVTbl
    query_interface : Proc(IDataFilter*, Guid*, Void**, HRESULT)
    add_ref : Proc(IDataFilter*, UInt32)
    release : Proc(IDataFilter*, UInt32)
    do_encode : Proc(IDataFilter*, UInt32, Int32, UInt8*, Int32, UInt8*, Int32, Int32*, Int32*, UInt32, HRESULT)
    do_decode : Proc(IDataFilter*, UInt32, Int32, UInt8*, Int32, UInt8*, Int32, Int32*, Int32*, UInt32, HRESULT)
    set_encoding_level : Proc(IDataFilter*, UInt32, HRESULT)
  end

  IDataFilter_GUID = LibC::GUID.new("69d14c80-c18e-11d0-a9ce-006097942311")
  CLSID_IDataFilter = "69d14c80-c18e-11d0-a9ce-006097942311"
  struct IDataFilter
    lpVtbl : IDataFilterVTbl*
  end

  struct IEncodingFilterFactoryVTbl
    query_interface : Proc(IEncodingFilterFactory*, Guid*, Void**, HRESULT)
    add_ref : Proc(IEncodingFilterFactory*, UInt32)
    release : Proc(IEncodingFilterFactory*, UInt32)
    find_best_filter : Proc(IEncodingFilterFactory*, LibC::LPWSTR, LibC::LPWSTR, DATAINFO, IDataFilter*, HRESULT)
    get_default_filter : Proc(IEncodingFilterFactory*, LibC::LPWSTR, LibC::LPWSTR, IDataFilter*, HRESULT)
  end

  IEncodingFilterFactory_GUID = LibC::GUID.new("70bdde00-c18e-11d0-a9ce-006097942311")
  CLSID_IEncodingFilterFactory = "70bdde00-c18e-11d0-a9ce-006097942311"
  struct IEncodingFilterFactory
    lpVtbl : IEncodingFilterFactoryVTbl*
  end

  struct IWrappedProtocolVTbl
    query_interface : Proc(IWrappedProtocol*, Guid*, Void**, HRESULT)
    add_ref : Proc(IWrappedProtocol*, UInt32)
    release : Proc(IWrappedProtocol*, UInt32)
    get_wrapper_code : Proc(IWrappedProtocol*, Int32*, LibC::UINT_PTR, HRESULT)
  end

  IWrappedProtocol_GUID = LibC::GUID.new("53c84785-8425-4dc5-971b-e58d9c19f9b6")
  CLSID_IWrappedProtocol = "53c84785-8425-4dc5-971b-e58d9c19f9b6"
  struct IWrappedProtocol
    lpVtbl : IWrappedProtocolVTbl*
  end

  struct IGetBindHandleVTbl
    query_interface : Proc(IGetBindHandle*, Guid*, Void**, HRESULT)
    add_ref : Proc(IGetBindHandle*, UInt32)
    release : Proc(IGetBindHandle*, UInt32)
    get_bind_handle : Proc(IGetBindHandle*, BINDHANDLETYPES, LibC::HANDLE*, HRESULT)
  end

  IGetBindHandle_GUID = LibC::GUID.new("af0ff408-129d-4b20-91f0-02bd23d88352")
  CLSID_IGetBindHandle = "af0ff408-129d-4b20-91f0-02bd23d88352"
  struct IGetBindHandle
    lpVtbl : IGetBindHandleVTbl*
  end

  struct IBindCallbackRedirectVTbl
    query_interface : Proc(IBindCallbackRedirect*, Guid*, Void**, HRESULT)
    add_ref : Proc(IBindCallbackRedirect*, UInt32)
    release : Proc(IBindCallbackRedirect*, UInt32)
    redirect : Proc(IBindCallbackRedirect*, LibC::LPWSTR, Int16*, HRESULT)
  end

  IBindCallbackRedirect_GUID = LibC::GUID.new("11c81bc2-121e-4ed5-b9c4-b430bd54f2c0")
  CLSID_IBindCallbackRedirect = "11c81bc2-121e-4ed5-b9c4-b430bd54f2c0"
  struct IBindCallbackRedirect
    lpVtbl : IBindCallbackRedirectVTbl*
  end

  struct IBindHttpSecurityVTbl
    query_interface : Proc(IBindHttpSecurity*, Guid*, Void**, HRESULT)
    add_ref : Proc(IBindHttpSecurity*, UInt32)
    release : Proc(IBindHttpSecurity*, UInt32)
    get_ignore_cert_mask : Proc(IBindHttpSecurity*, UInt32*, HRESULT)
  end

  IBindHttpSecurity_GUID = LibC::GUID.new("a9eda967-f50e-4a33-b358-206f6ef3086d")
  CLSID_IBindHttpSecurity = "a9eda967-f50e-4a33-b358-206f6ef3086d"
  struct IBindHttpSecurity
    lpVtbl : IBindHttpSecurityVTbl*
  end


  # Params # pmkctx : IMoniker [In],szurl : LibC::LPWSTR [In],ppmk : IMoniker* [In]
  fun CreateURLMoniker(pmkctx : IMoniker, szurl : LibC::LPWSTR, ppmk : IMoniker*) : HRESULT

  # Params # pmkctx : IMoniker [In],szurl : LibC::LPWSTR [In],ppmk : IMoniker* [In],dwflags : UInt32 [In]
  fun CreateURLMonikerEx(pmkctx : IMoniker, szurl : LibC::LPWSTR, ppmk : IMoniker*, dwflags : UInt32) : HRESULT

  # Params # szurl : LibC::LPWSTR [In],pclsid : Guid* [In]
  fun GetClassURL(szurl : LibC::LPWSTR, pclsid : Guid*) : HRESULT

  # Params # reserved : UInt32 [In],pbscb : IBindStatusCallback [In],pefetc : IEnumFORMATETC [In],ppbc : IBindCtx* [In]
  fun CreateAsyncBindCtx(reserved : UInt32, pbscb : IBindStatusCallback, pefetc : IEnumFORMATETC, ppbc : IBindCtx*) : HRESULT

  # Params # pmkctx : IMoniker [In],puri : IUri [In],ppmk : IMoniker* [In],dwflags : UInt32 [In]
  fun CreateURLMonikerEx2(pmkctx : IMoniker, puri : IUri, ppmk : IMoniker*, dwflags : UInt32) : HRESULT

  # Params # pbc : IBindCtx [In],dwoptions : UInt32 [In],pbscb : IBindStatusCallback [In],penum : IEnumFORMATETC [In],ppbc : IBindCtx* [In],reserved : UInt32 [In]
  fun CreateAsyncBindCtxEx(pbc : IBindCtx, dwoptions : UInt32, pbscb : IBindStatusCallback, penum : IEnumFORMATETC, ppbc : IBindCtx*, reserved : UInt32) : HRESULT

  # Params # pbc : IBindCtx [In],szdisplayname : LibC::LPWSTR [In],pcheaten : UInt32* [In],ppmk : IMoniker* [In]
  fun MkParseDisplayNameEx(pbc : IBindCtx, szdisplayname : LibC::LPWSTR, pcheaten : UInt32*, ppmk : IMoniker*) : HRESULT

  # Params # pbc : IBindCtx [In],pbscb : IBindStatusCallback [In],ppbscbprev : IBindStatusCallback* [In],dwreserved : UInt32 [In]
  fun RegisterBindStatusCallback(pbc : IBindCtx, pbscb : IBindStatusCallback, ppbscbprev : IBindStatusCallback*, dwreserved : UInt32) : HRESULT

  # Params # pbc : IBindCtx [In],pbscb : IBindStatusCallback [In]
  fun RevokeBindStatusCallback(pbc : IBindCtx, pbscb : IBindStatusCallback) : HRESULT

  # Params # pbc : IBindCtx [In],szfilename : LibC::LPWSTR [In],pbuffer : Void* [In],cbsize : UInt32 [In],szmime : LibC::LPWSTR [In],dwreserved : UInt32 [In],pclsid : Guid* [In]
  fun GetClassFileOrMime(pbc : IBindCtx, szfilename : LibC::LPWSTR, pbuffer : Void*, cbsize : UInt32, szmime : LibC::LPWSTR, dwreserved : UInt32, pclsid : Guid*) : HRESULT

  # Params # pbc : IBindCtx [In],szurl : LibC::LPWSTR [In],dwreserved : UInt32 [In]
  fun IsValidURL(pbc : IBindCtx, szurl : LibC::LPWSTR, dwreserved : UInt32) : HRESULT

  # Params # rclassid : Guid* [In],szcode : LibC::LPWSTR [In],dwfileversionms : UInt32 [In],dwfileversionls : UInt32 [In],sztype : LibC::LPWSTR [In],pbindctx : IBindCtx [In],dwclscontext : CLSCTX [In],pvreserved : Void* [In],riid : Guid* [In],ppv : Void** [In]
  fun CoGetClassObjectFromURL(rclassid : Guid*, szcode : LibC::LPWSTR, dwfileversionms : UInt32, dwfileversionls : UInt32, sztype : LibC::LPWSTR, pbindctx : IBindCtx, dwclscontext : CLSCTX, pvreserved : Void*, riid : Guid*, ppv : Void**) : HRESULT

  # Params # pdwscope : UInt32* [In]
  fun IEInstallScope(pdwscope : UInt32*) : HRESULT

  # Params # hwnd : LibC::HANDLE [In],pclassspec : Uclsspec* [In],pquery : QUERYCONTEXT* [In],dwflags : UInt32 [In]
  fun FaultInIEFeature(hwnd : LibC::HANDLE, pclassspec : Uclsspec*, pquery : QUERYCONTEXT*, dwflags : UInt32) : HRESULT

  # Params # pclassspec : Uclsspec* [In],ppszcomponentid : PSTR* [In]
  fun GetComponentIDFromCLSSPEC(pclassspec : Uclsspec*, ppszcomponentid : PSTR*) : HRESULT

  # Params # pmk : IMoniker [In]
  fun IsAsyncMoniker(pmk : IMoniker) : HRESULT

  # Params # ctypes : UInt32 [In],rgsztypes : PSTR* [In],rgcftypes : UInt16* [In]
  fun RegisterMediaTypes(ctypes : UInt32, rgsztypes : PSTR*, rgcftypes : UInt16*) : HRESULT

  # Params # rgsztypes : PSTR [In],rgcftypes : UInt16* [In]
  fun FindMediaType(rgsztypes : PSTR, rgcftypes : UInt16*) : HRESULT

  # Params # cfmtetc : UInt32 [In],rgfmtetc : FORMATETC* [In],ppenumfmtetc : IEnumFORMATETC* [In]
  fun CreateFormatEnumerator(cfmtetc : UInt32, rgfmtetc : FORMATETC*, ppenumfmtetc : IEnumFORMATETC*) : HRESULT

  # Params # pbc : IBindCtx [In],pefetc : IEnumFORMATETC [In],reserved : UInt32 [In]
  fun RegisterFormatEnumerator(pbc : IBindCtx, pefetc : IEnumFORMATETC, reserved : UInt32) : HRESULT

  # Params # pbc : IBindCtx [In],pefetc : IEnumFORMATETC [In]
  fun RevokeFormatEnumerator(pbc : IBindCtx, pefetc : IEnumFORMATETC) : HRESULT

  # Params # pbc : IBindCtx [In],ctypes : UInt32 [In],rgsztypes : PSTR* [In],rgclsid : Guid* [In],reserved : UInt32 [In]
  fun RegisterMediaTypeClass(pbc : IBindCtx, ctypes : UInt32, rgsztypes : PSTR*, rgclsid : Guid*, reserved : UInt32) : HRESULT

  # Params # pbc : IBindCtx [In],sztype : PSTR [In],pclsid : Guid* [In],reserved : UInt32 [In]
  fun FindMediaTypeClass(pbc : IBindCtx, sztype : PSTR, pclsid : Guid*, reserved : UInt32) : HRESULT

  # Params # dwoption : UInt32 [In],pbuffer : Void* [In],dwbufferlength : UInt32 [In],dwreserved : UInt32 [In]
  fun UrlMkSetSessionOption(dwoption : UInt32, pbuffer : Void*, dwbufferlength : UInt32, dwreserved : UInt32) : HRESULT

  # Params # dwoption : UInt32 [In],pbuffer : Void* [In],dwbufferlength : UInt32 [In],pdwbufferlengthout : UInt32* [In],dwreserved : UInt32 [In]
  fun UrlMkGetSessionOption(dwoption : UInt32, pbuffer : Void*, dwbufferlength : UInt32, pdwbufferlengthout : UInt32*, dwreserved : UInt32) : HRESULT

  # Params # pbc : IBindCtx [In],pwzurl : LibC::LPWSTR [In],pbuffer : Void* [In],cbsize : UInt32 [In],pwzmimeproposed : LibC::LPWSTR [In],dwmimeflags : UInt32 [In],ppwzmimeout : LibC::LPWSTR* [In],dwreserved : UInt32 [In]
  fun FindMimeFromData(pbc : IBindCtx, pwzurl : LibC::LPWSTR, pbuffer : Void*, cbsize : UInt32, pwzmimeproposed : LibC::LPWSTR, dwmimeflags : UInt32, ppwzmimeout : LibC::LPWSTR*, dwreserved : UInt32) : HRESULT

  # Params # dwoption : UInt32 [In],pszuaout : UInt8* [In],cbsize : UInt32* [In]
  fun ObtainUserAgentString(dwoption : UInt32, pszuaout : UInt8*, cbsize : UInt32*) : HRESULT

  # Params # pbsecurityid1 : UInt8* [In],dwlen1 : UInt32 [In],pbsecurityid2 : UInt8* [In],dwlen2 : UInt32 [In],dwreserved : UInt32 [In]
  fun CompareSecurityIds(pbsecurityid1 : UInt8*, dwlen1 : UInt32, pbsecurityid2 : UInt8*, dwlen2 : UInt32, dwreserved : UInt32) : HRESULT

  # Params # pclsid : Guid* [In],pdwcompatflags : UInt32* [In],pdwmiscstatusflags : UInt32* [In]
  fun CompatFlagsFromClsid(pclsid : Guid*, pdwcompatflags : UInt32*, pdwmiscstatusflags : UInt32*) : HRESULT

  # Params # hobject : LibC::HANDLE [In],ieobjecttype : IEObjectType [In],dwaccessmask : UInt32 [In]
  fun SetAccessForIEAppContainer(hobject : LibC::HANDLE, ieobjecttype : IEObjectType, dwaccessmask : UInt32) : HRESULT

  # Params # sztarget : LibC::LPWSTR [In],szlocation : LibC::LPWSTR [In],sztargetframename : LibC::LPWSTR [In],punk : IUnknown [In],pbc : IBindCtx [In],param5 : IBindStatusCallback [In],grfhlnf : UInt32 [In],dwreserved : UInt32 [In]
  fun HlinkSimpleNavigateToString(sztarget : LibC::LPWSTR, szlocation : LibC::LPWSTR, sztargetframename : LibC::LPWSTR, punk : IUnknown, pbc : IBindCtx, param5 : IBindStatusCallback, grfhlnf : UInt32, dwreserved : UInt32) : HRESULT

  # Params # pmktarget : IMoniker [In],szlocation : LibC::LPWSTR [In],sztargetframename : LibC::LPWSTR [In],punk : IUnknown [In],pbc : IBindCtx [In],param5 : IBindStatusCallback [In],grfhlnf : UInt32 [In],dwreserved : UInt32 [In]
  fun HlinkSimpleNavigateToMoniker(pmktarget : IMoniker, szlocation : LibC::LPWSTR, sztargetframename : LibC::LPWSTR, punk : IUnknown, pbc : IBindCtx, param5 : IBindStatusCallback, grfhlnf : UInt32, dwreserved : UInt32) : HRESULT

  # Params # param0 : IUnknown [In],param1 : PSTR [In],param2 : UInt32 [In],param3 : IBindStatusCallback [In]
  fun URLOpenStreamA(param0 : IUnknown, param1 : PSTR, param2 : UInt32, param3 : IBindStatusCallback) : HRESULT

  # Params # param0 : IUnknown [In],param1 : LibC::LPWSTR [In],param2 : UInt32 [In],param3 : IBindStatusCallback [In]
  fun URLOpenStreamW(param0 : IUnknown, param1 : LibC::LPWSTR, param2 : UInt32, param3 : IBindStatusCallback) : HRESULT

  # Params # param0 : IUnknown [In],param1 : PSTR [In],param2 : UInt32 [In],param3 : IBindStatusCallback [In]
  fun URLOpenPullStreamA(param0 : IUnknown, param1 : PSTR, param2 : UInt32, param3 : IBindStatusCallback) : HRESULT

  # Params # param0 : IUnknown [In],param1 : LibC::LPWSTR [In],param2 : UInt32 [In],param3 : IBindStatusCallback [In]
  fun URLOpenPullStreamW(param0 : IUnknown, param1 : LibC::LPWSTR, param2 : UInt32, param3 : IBindStatusCallback) : HRESULT

  # Params # param0 : IUnknown [In],param1 : PSTR [In],param2 : PSTR [In],param3 : UInt32 [In],param4 : IBindStatusCallback [In]
  fun URLDownloadToFileA(param0 : IUnknown, param1 : PSTR, param2 : PSTR, param3 : UInt32, param4 : IBindStatusCallback) : HRESULT

  # Params # param0 : IUnknown [In],param1 : LibC::LPWSTR [In],param2 : LibC::LPWSTR [In],param3 : UInt32 [In],param4 : IBindStatusCallback [In]
  fun URLDownloadToFileW(param0 : IUnknown, param1 : LibC::LPWSTR, param2 : LibC::LPWSTR, param3 : UInt32, param4 : IBindStatusCallback) : HRESULT

  # Params # param0 : IUnknown [In],param1 : PSTR [In],param2 : UInt8* [In],cchfilename : UInt32 [In],param4 : UInt32 [In],param5 : IBindStatusCallback [In]
  fun URLDownloadToCacheFileA(param0 : IUnknown, param1 : PSTR, param2 : UInt8*, cchfilename : UInt32, param4 : UInt32, param5 : IBindStatusCallback) : HRESULT

  # Params # param0 : IUnknown [In],param1 : LibC::LPWSTR [In],param2 : Char* [In],cchfilename : UInt32 [In],param4 : UInt32 [In],param5 : IBindStatusCallback [In]
  fun URLDownloadToCacheFileW(param0 : IUnknown, param1 : LibC::LPWSTR, param2 : Char*, cchfilename : UInt32, param4 : UInt32, param5 : IBindStatusCallback) : HRESULT

  # Params # param0 : IUnknown [In],param1 : PSTR [In],param2 : IStream* [In],param3 : UInt32 [In],param4 : IBindStatusCallback [In]
  fun URLOpenBlockingStreamA(param0 : IUnknown, param1 : PSTR, param2 : IStream*, param3 : UInt32, param4 : IBindStatusCallback) : HRESULT

  # Params # param0 : IUnknown [In],param1 : LibC::LPWSTR [In],param2 : IStream* [In],param3 : UInt32 [In],param4 : IBindStatusCallback [In]
  fun URLOpenBlockingStreamW(param0 : IUnknown, param1 : LibC::LPWSTR, param2 : IStream*, param3 : UInt32, param4 : IBindStatusCallback) : HRESULT

  # Params # punk : IUnknown [In]
  fun HlinkGoBack(punk : IUnknown) : HRESULT

  # Params # punk : IUnknown [In]
  fun HlinkGoForward(punk : IUnknown) : HRESULT

  # Params # punk : IUnknown [In],sztarget : LibC::LPWSTR [In]
  fun HlinkNavigateString(punk : IUnknown, sztarget : LibC::LPWSTR) : HRESULT

  # Params # punk : IUnknown [In],pmktarget : IMoniker [In]
  fun HlinkNavigateMoniker(punk : IUnknown, pmktarget : IMoniker) : HRESULT

  # Params # pwzurl : LibC::LPWSTR [In],parseaction : PARSEACTION [In],dwflags : UInt32 [In],pszresult : Char* [In],cchresult : UInt32 [In],pcchresult : UInt32* [In],dwreserved : UInt32 [In]
  fun CoInternetParseUrl(pwzurl : LibC::LPWSTR, parseaction : PARSEACTION, dwflags : UInt32, pszresult : Char*, cchresult : UInt32, pcchresult : UInt32*, dwreserved : UInt32) : HRESULT

  # Params # piuri : IUri [In],parseaction : PARSEACTION [In],dwflags : UInt32 [In],pwzresult : Char* [In],cchresult : UInt32 [In],pcchresult : UInt32* [In],dwreserved : LibC::UINT_PTR [In]
  fun CoInternetParseIUri(piuri : IUri, parseaction : PARSEACTION, dwflags : UInt32, pwzresult : Char*, cchresult : UInt32, pcchresult : UInt32*, dwreserved : LibC::UINT_PTR) : HRESULT

  # Params # pwzbaseurl : LibC::LPWSTR [In],pwzrelativeurl : LibC::LPWSTR [In],dwcombineflags : UInt32 [In],pszresult : Char* [In],cchresult : UInt32 [In],pcchresult : UInt32* [In],dwreserved : UInt32 [In]
  fun CoInternetCombineUrl(pwzbaseurl : LibC::LPWSTR, pwzrelativeurl : LibC::LPWSTR, dwcombineflags : UInt32, pszresult : Char*, cchresult : UInt32, pcchresult : UInt32*, dwreserved : UInt32) : HRESULT

  # Params # pbaseuri : IUri [In],pwzrelativeurl : LibC::LPWSTR [In],dwcombineflags : UInt32 [In],ppcombineduri : IUri* [In],dwreserved : LibC::UINT_PTR [In]
  fun CoInternetCombineUrlEx(pbaseuri : IUri, pwzrelativeurl : LibC::LPWSTR, dwcombineflags : UInt32, ppcombineduri : IUri*, dwreserved : LibC::UINT_PTR) : HRESULT

  # Params # pbaseuri : IUri [In],prelativeuri : IUri [In],dwcombineflags : UInt32 [In],ppcombineduri : IUri* [In],dwreserved : LibC::UINT_PTR [In]
  fun CoInternetCombineIUri(pbaseuri : IUri, prelativeuri : IUri, dwcombineflags : UInt32, ppcombineduri : IUri*, dwreserved : LibC::UINT_PTR) : HRESULT

  # Params # pwzurl1 : LibC::LPWSTR [In],pwzurl2 : LibC::LPWSTR [In],dwflags : UInt32 [In]
  fun CoInternetCompareUrl(pwzurl1 : LibC::LPWSTR, pwzurl2 : LibC::LPWSTR, dwflags : UInt32) : HRESULT

  # Params # pwzurl : LibC::LPWSTR [In],pdwflags : UInt32* [In],dwreserved : UInt32 [In]
  fun CoInternetGetProtocolFlags(pwzurl : LibC::LPWSTR, pdwflags : UInt32*, dwreserved : UInt32) : HRESULT

  # Params # pwzurl : LibC::LPWSTR [In],queryoptions : QUERYOPTION [In],dwqueryflags : UInt32 [In],pvbuffer : Void* [In],cbbuffer : UInt32 [In],pcbbuffer : UInt32* [In],dwreserved : UInt32 [In]
  fun CoInternetQueryInfo(pwzurl : LibC::LPWSTR, queryoptions : QUERYOPTION, dwqueryflags : UInt32, pvbuffer : Void*, cbbuffer : UInt32, pcbbuffer : UInt32*, dwreserved : UInt32) : HRESULT

  # Params # dwsessionmode : UInt32 [In],ppiinternetsession : IInternetSession* [In],dwreserved : UInt32 [In]
  fun CoInternetGetSession(dwsessionmode : UInt32, ppiinternetsession : IInternetSession*, dwreserved : UInt32) : HRESULT

  # Params # pwszurl : LibC::LPWSTR [In],ppwszsecurl : LibC::LPWSTR* [In],psuaction : PSUACTION [In],dwreserved : UInt32 [In]
  fun CoInternetGetSecurityUrl(pwszurl : LibC::LPWSTR, ppwszsecurl : LibC::LPWSTR*, psuaction : PSUACTION, dwreserved : UInt32) : HRESULT

  # Params # puri : IUri [In],ppsecuri : IUri* [In],psuaction : PSUACTION [In],dwreserved : LibC::UINT_PTR [In]
  fun CoInternetGetSecurityUrlEx(puri : IUri, ppsecuri : IUri*, psuaction : PSUACTION, dwreserved : LibC::UINT_PTR) : HRESULT

  # Params # featureentry : INTERNETFEATURELIST [In],dwflags : UInt32 [In],fenable : LibC::BOOL [In]
  fun CoInternetSetFeatureEnabled(featureentry : INTERNETFEATURELIST, dwflags : UInt32, fenable : LibC::BOOL) : HRESULT

  # Params # featureentry : INTERNETFEATURELIST [In],dwflags : UInt32 [In]
  fun CoInternetIsFeatureEnabled(featureentry : INTERNETFEATURELIST, dwflags : UInt32) : HRESULT

  # Params # featureentry : INTERNETFEATURELIST [In],dwflags : UInt32 [In],szurl : LibC::LPWSTR [In],psecmgr : IInternetSecurityManager [In]
  fun CoInternetIsFeatureEnabledForUrl(featureentry : INTERNETFEATURELIST, dwflags : UInt32, szurl : LibC::LPWSTR, psecmgr : IInternetSecurityManager) : HRESULT

  # Params # featureentry : INTERNETFEATURELIST [In],dwflags : UInt32 [In],piuri : IUri [In],psecmgr : IInternetSecurityManagerEx2 [In]
  fun CoInternetIsFeatureEnabledForIUri(featureentry : INTERNETFEATURELIST, dwflags : UInt32, piuri : IUri, psecmgr : IInternetSecurityManagerEx2) : HRESULT

  # Params # szfromurl : LibC::LPWSTR [In],sztourl : LibC::LPWSTR [In],psecmgr : IInternetSecurityManager [In],dwflags : UInt32 [In]
  fun CoInternetIsFeatureZoneElevationEnabled(szfromurl : LibC::LPWSTR, sztourl : LibC::LPWSTR, psecmgr : IInternetSecurityManager, dwflags : UInt32) : HRESULT

  # Params # pcstgmedsrc : STGMEDIUM* [In],pstgmeddest : STGMEDIUM* [In]
  fun CopyStgMedium(pcstgmedsrc : STGMEDIUM*, pstgmeddest : STGMEDIUM*) : HRESULT

  # Params # pcbisrc : BINDINFO* [In],pbidest : BINDINFO* [In]
  fun CopyBindInfo(pcbisrc : BINDINFO*, pbidest : BINDINFO*) : HRESULT

  # Params # pbindinfo : BINDINFO* [In]
  fun ReleaseBindInfo(pbindinfo : BINDINFO*)

  # Params # 
  fun IEGetUserPrivateNamespaceName : LibC::LPWSTR

  # Params # psp : IServiceProvider [In],ppsm : IInternetSecurityManager* [In],dwreserved : UInt32 [In]
  fun CoInternetCreateSecurityManager(psp : IServiceProvider, ppsm : IInternetSecurityManager*, dwreserved : UInt32) : HRESULT

  # Params # psp : IServiceProvider [In],ppzm : IInternetZoneManager* [In],dwreserved : UInt32 [In]
  fun CoInternetCreateZoneManager(psp : IServiceProvider, ppzm : IInternetZoneManager*, dwreserved : UInt32) : HRESULT

  # Params # szdistunit : LibC::LPWSTR [In],psdi : SOFTDISTINFO* [In]
  fun GetSoftwareUpdateInfo(szdistunit : LibC::LPWSTR, psdi : SOFTDISTINFO*) : HRESULT

  # Params # szdistunit : LibC::LPWSTR [In],dwadstate : UInt32 [In],dwadvertisedversionms : UInt32 [In],dwadvertisedversionls : UInt32 [In]
  fun SetSoftwareUpdateAdvertisementState(szdistunit : LibC::LPWSTR, dwadstate : UInt32, dwadvertisedversionms : UInt32, dwadvertisedversionls : UInt32) : HRESULT

  # Params # pszurl : PSTR [In]
  fun IsLoggingEnabledA(pszurl : PSTR) : LibC::BOOL

  # Params # pwszurl : LibC::LPWSTR [In]
  fun IsLoggingEnabledW(pwszurl : LibC::LPWSTR) : LibC::BOOL

  # Params # lplogginginfo : HIT_LOGGING_INFO* [In]
  fun WriteHitLogging(lplogginginfo : HIT_LOGGING_INFO*) : LibC::BOOL
end
