require "../../foundation.cr"
require "../../system/time.cr"
require "../../system/com.cr"
require "../../security.cr"

@[Link("delayimp")]
@[Link("user32")]
@[Link(ldflags: "/IGNORE:4199")]
@[Link(ldflags: "/DELAYLOAD:advapi32.dll")]
@[Link(ldflags: "/DELAYLOAD:tdh.dll")]
lib LibWin32
  alias TDH_HANDLE = LibC::IntPtrT

  WNODE_FLAG_ALL_DATA = 1_u32
  WNODE_FLAG_SINGLE_INSTANCE = 2_u32
  WNODE_FLAG_SINGLE_ITEM = 4_u32
  WNODE_FLAG_EVENT_ITEM = 8_u32
  WNODE_FLAG_FIXED_INSTANCE_SIZE = 16_u32
  WNODE_FLAG_TOO_SMALL = 32_u32
  WNODE_FLAG_INSTANCES_SAME = 64_u32
  WNODE_FLAG_STATIC_INSTANCE_NAMES = 128_u32
  WNODE_FLAG_INTERNAL = 256_u32
  WNODE_FLAG_USE_TIMESTAMP = 512_u32
  WNODE_FLAG_PERSIST_EVENT = 1024_u32
  WNODE_FLAG_EVENT_REFERENCE = 8192_u32
  WNODE_FLAG_ANSI_INSTANCENAMES = 16384_u32
  WNODE_FLAG_METHOD_ITEM = 32768_u32
  WNODE_FLAG_PDO_INSTANCE_NAMES = 65536_u32
  WNODE_FLAG_TRACED_GUID = 131072_u32
  WNODE_FLAG_LOG_WNODE = 262144_u32
  WNODE_FLAG_USE_GUID_PTR = 524288_u32
  WNODE_FLAG_USE_MOF_PTR = 1048576_u32
  WNODE_FLAG_NO_HEADER = 2097152_u32
  WNODE_FLAG_SEND_DATA_BLOCK = 4194304_u32
  WNODE_FLAG_VERSIONED_PROPERTIES = 8388608_u32
  WNODE_FLAG_SEVERITY_MASK = 4278190080_u32
  WMIREG_FLAG_EXPENSIVE = 1_u32
  WMIREG_FLAG_INSTANCE_LIST = 4_u32
  WMIREG_FLAG_INSTANCE_BASENAME = 8_u32
  WMIREG_FLAG_INSTANCE_PDO = 32_u32
  WMIREG_FLAG_REMOVE_GUID = 65536_u32
  WMIREG_FLAG_RESERVED1 = 131072_u32
  WMIREG_FLAG_RESERVED2 = 262144_u32
  WMIREG_FLAG_TRACED_GUID = 524288_u32
  WMIREG_FLAG_TRACE_CONTROL_GUID = 4096_u32
  WMIREG_FLAG_EVENT_ONLY_GUID = 64_u32
  WMI_GUIDTYPE_TRACECONTROL = 0_u32
  WMI_GUIDTYPE_TRACE = 1_u32
  WMI_GUIDTYPE_DATA = 2_u32
  WMI_GUIDTYPE_EVENT = 3_u32
  WMIGUID_QUERY = 1_u32
  WMIGUID_SET = 2_u32
  WMIGUID_NOTIFICATION = 4_u32
  WMIGUID_READ_DESCRIPTION = 8_u32
  WMIGUID_EXECUTE = 16_u32
  TRACELOG_CREATE_REALTIME = 32_u32
  TRACELOG_CREATE_ONDISK = 64_u32
  TRACELOG_GUID_ENABLE = 128_u32
  TRACELOG_ACCESS_KERNEL_LOGGER = 256_u32
  TRACELOG_LOG_EVENT = 512_u32
  TRACELOG_CREATE_INPROC = 512_u32
  TRACELOG_ACCESS_REALTIME = 1024_u32
  TRACELOG_REGISTER_GUIDS = 2048_u32
  TRACELOG_JOIN_GROUP = 4096_u32
  WMI_GLOBAL_LOGGER_ID = 1_u32
  MAX_PAYLOAD_PREDICATES = 8_u32
  EventTraceGuid = "68fdd900-4a3e-11d1-84f4-0000f80464e3"
  SystemTraceControlGuid = "9e814aad-3204-11d2-9a82-006008a86939"
  EventTraceConfigGuid = "01853a65-418f-4f36-aefc-dc0f1d2fd235"
  DefaultTraceSecurityGuid = "0811c1af-7a07-4a06-82ed-869455cdf713"
  PrivateLoggerNotificationGuid = "3595ab5c-042a-4c8e-b942-2d059bfeb1b1"
  SystemIoFilterProviderGuid = "fbd09363-9e22-4661-b8bf-e7a34b535b8c"
  SystemObjectProviderGuid = "febd7460-3d1d-47eb-af49-c9eeb1e146f2"
  SystemPowerProviderGuid = "c134884a-32d5-4488-80e5-14ed7abb8269"
  SystemHypervisorProviderGuid = "bafa072a-918a-4bed-b622-bc152097098f"
  SystemLockProviderGuid = "721ddfd3-dacc-4e1e-b26a-a2cb31d4705a"
  SystemConfigProviderGuid = "fef3a8b6-318d-4b67-a96a-3b0f6b8f18fe"
  SystemCpuProviderGuid = "c6c5265f-eae8-4650-aae4-9d48603d8510"
  SystemSchedulerProviderGuid = "599a2a76-4d91-4910-9ac7-7d33f2e97a6c"
  SystemProfileProviderGuid = "bfeb0324-1cee-496f-a409-2ac2b48a6322"
  SystemIoProviderGuid = "3d5c43e3-0f1c-4202-b817-174c0070dc79"
  SystemMemoryProviderGuid = "82958ca9-b6cd-47f8-a3a8-03ae85a4bc24"
  SystemRegistryProviderGuid = "16156bd9-fab4-4cfa-a232-89d1099058e3"
  SystemProcessProviderGuid = "151f55dc-467d-471f-83b5-5f889d46ff66"
  SystemAlpcProviderGuid = "fcb9baaf-e529-4980-92e9-ced1a6aadfdf"
  SystemSyscallProviderGuid = "434286f7-6f1b-45bb-b37e-95f623046c7c"
  SystemInterruptProviderGuid = "d4bbee17-b545-4888-858b-744169015b25"
  SystemTimerProviderGuid = "4f061568-e215-499f-ab2e-eda0ae890a5b"
  MAX_MOF_FIELDS = 16_u32
  SYSTEM_EVENT_TYPE = 1_u32
  EVENT_TRACE_TYPE_INFO = 0_u32
  EVENT_TRACE_TYPE_START = 1_u32
  EVENT_TRACE_TYPE_END = 2_u32
  EVENT_TRACE_TYPE_STOP = 2_u32
  EVENT_TRACE_TYPE_DC_START = 3_u32
  EVENT_TRACE_TYPE_DC_END = 4_u32
  EVENT_TRACE_TYPE_EXTENSION = 5_u32
  EVENT_TRACE_TYPE_REPLY = 6_u32
  EVENT_TRACE_TYPE_DEQUEUE = 7_u32
  EVENT_TRACE_TYPE_RESUME = 7_u32
  EVENT_TRACE_TYPE_CHECKPOINT = 8_u32
  EVENT_TRACE_TYPE_SUSPEND = 8_u32
  EVENT_TRACE_TYPE_WINEVT_SEND = 9_u32
  EVENT_TRACE_TYPE_WINEVT_RECEIVE = 240_u32
  TRACE_LEVEL_NONE = 0_u32
  TRACE_LEVEL_CRITICAL = 1_u32
  TRACE_LEVEL_FATAL = 1_u32
  TRACE_LEVEL_ERROR = 2_u32
  TRACE_LEVEL_WARNING = 3_u32
  TRACE_LEVEL_INFORMATION = 4_u32
  TRACE_LEVEL_VERBOSE = 5_u32
  TRACE_LEVEL_RESERVED6 = 6_u32
  TRACE_LEVEL_RESERVED7 = 7_u32
  TRACE_LEVEL_RESERVED8 = 8_u32
  TRACE_LEVEL_RESERVED9 = 9_u32
  EVENT_TRACE_TYPE_LOAD = 10_u32
  EVENT_TRACE_TYPE_TERMINATE = 11_u32
  EVENT_TRACE_TYPE_IO_READ = 10_u32
  EVENT_TRACE_TYPE_IO_WRITE = 11_u32
  EVENT_TRACE_TYPE_IO_READ_INIT = 12_u32
  EVENT_TRACE_TYPE_IO_WRITE_INIT = 13_u32
  EVENT_TRACE_TYPE_IO_FLUSH = 14_u32
  EVENT_TRACE_TYPE_IO_FLUSH_INIT = 15_u32
  EVENT_TRACE_TYPE_IO_REDIRECTED_INIT = 16_u32
  EVENT_TRACE_TYPE_MM_TF = 10_u32
  EVENT_TRACE_TYPE_MM_DZF = 11_u32
  EVENT_TRACE_TYPE_MM_COW = 12_u32
  EVENT_TRACE_TYPE_MM_GPF = 13_u32
  EVENT_TRACE_TYPE_MM_HPF = 14_u32
  EVENT_TRACE_TYPE_MM_AV = 15_u32
  EVENT_TRACE_TYPE_SEND = 10_u32
  EVENT_TRACE_TYPE_RECEIVE = 11_u32
  EVENT_TRACE_TYPE_CONNECT = 12_u32
  EVENT_TRACE_TYPE_DISCONNECT = 13_u32
  EVENT_TRACE_TYPE_RETRANSMIT = 14_u32
  EVENT_TRACE_TYPE_ACCEPT = 15_u32
  EVENT_TRACE_TYPE_RECONNECT = 16_u32
  EVENT_TRACE_TYPE_CONNFAIL = 17_u32
  EVENT_TRACE_TYPE_COPY_TCP = 18_u32
  EVENT_TRACE_TYPE_COPY_ARP = 19_u32
  EVENT_TRACE_TYPE_ACKFULL = 20_u32
  EVENT_TRACE_TYPE_ACKPART = 21_u32
  EVENT_TRACE_TYPE_ACKDUP = 22_u32
  EVENT_TRACE_TYPE_GUIDMAP = 10_u32
  EVENT_TRACE_TYPE_CONFIG = 11_u32
  EVENT_TRACE_TYPE_SIDINFO = 12_u32
  EVENT_TRACE_TYPE_SECURITY = 13_u32
  EVENT_TRACE_TYPE_DBGID_RSDS = 64_u32
  EVENT_TRACE_TYPE_REGCREATE = 10_u32
  EVENT_TRACE_TYPE_REGOPEN = 11_u32
  EVENT_TRACE_TYPE_REGDELETE = 12_u32
  EVENT_TRACE_TYPE_REGQUERY = 13_u32
  EVENT_TRACE_TYPE_REGSETVALUE = 14_u32
  EVENT_TRACE_TYPE_REGDELETEVALUE = 15_u32
  EVENT_TRACE_TYPE_REGQUERYVALUE = 16_u32
  EVENT_TRACE_TYPE_REGENUMERATEKEY = 17_u32
  EVENT_TRACE_TYPE_REGENUMERATEVALUEKEY = 18_u32
  EVENT_TRACE_TYPE_REGQUERYMULTIPLEVALUE = 19_u32
  EVENT_TRACE_TYPE_REGSETINFORMATION = 20_u32
  EVENT_TRACE_TYPE_REGFLUSH = 21_u32
  EVENT_TRACE_TYPE_REGKCBCREATE = 22_u32
  EVENT_TRACE_TYPE_REGKCBDELETE = 23_u32
  EVENT_TRACE_TYPE_REGKCBRUNDOWNBEGIN = 24_u32
  EVENT_TRACE_TYPE_REGKCBRUNDOWNEND = 25_u32
  EVENT_TRACE_TYPE_REGVIRTUALIZE = 26_u32
  EVENT_TRACE_TYPE_REGCLOSE = 27_u32
  EVENT_TRACE_TYPE_REGSETSECURITY = 28_u32
  EVENT_TRACE_TYPE_REGQUERYSECURITY = 29_u32
  EVENT_TRACE_TYPE_REGCOMMIT = 30_u32
  EVENT_TRACE_TYPE_REGPREPARE = 31_u32
  EVENT_TRACE_TYPE_REGROLLBACK = 32_u32
  EVENT_TRACE_TYPE_REGMOUNTHIVE = 33_u32
  EVENT_TRACE_TYPE_CONFIG_CPU = 10_u32
  EVENT_TRACE_TYPE_CONFIG_PHYSICALDISK = 11_u32
  EVENT_TRACE_TYPE_CONFIG_LOGICALDISK = 12_u32
  EVENT_TRACE_TYPE_CONFIG_NIC = 13_u32
  EVENT_TRACE_TYPE_CONFIG_VIDEO = 14_u32
  EVENT_TRACE_TYPE_CONFIG_SERVICES = 15_u32
  EVENT_TRACE_TYPE_CONFIG_POWER = 16_u32
  EVENT_TRACE_TYPE_CONFIG_NETINFO = 17_u32
  EVENT_TRACE_TYPE_CONFIG_OPTICALMEDIA = 18_u32
  EVENT_TRACE_TYPE_CONFIG_IRQ = 21_u32
  EVENT_TRACE_TYPE_CONFIG_PNP = 22_u32
  EVENT_TRACE_TYPE_CONFIG_IDECHANNEL = 23_u32
  EVENT_TRACE_TYPE_CONFIG_NUMANODE = 24_u32
  EVENT_TRACE_TYPE_CONFIG_PLATFORM = 25_u32
  EVENT_TRACE_TYPE_CONFIG_PROCESSORGROUP = 26_u32
  EVENT_TRACE_TYPE_CONFIG_PROCESSORNUMBER = 27_u32
  EVENT_TRACE_TYPE_CONFIG_DPI = 28_u32
  EVENT_TRACE_TYPE_CONFIG_CI_INFO = 29_u32
  EVENT_TRACE_TYPE_CONFIG_MACHINEID = 30_u32
  EVENT_TRACE_TYPE_CONFIG_DEFRAG = 31_u32
  EVENT_TRACE_TYPE_CONFIG_MOBILEPLATFORM = 32_u32
  EVENT_TRACE_TYPE_CONFIG_DEVICEFAMILY = 33_u32
  EVENT_TRACE_TYPE_CONFIG_FLIGHTID = 34_u32
  EVENT_TRACE_TYPE_CONFIG_PROCESSOR = 35_u32
  EVENT_TRACE_TYPE_CONFIG_VIRTUALIZATION = 36_u32
  EVENT_TRACE_TYPE_CONFIG_BOOT = 37_u32
  EVENT_TRACE_TYPE_OPTICAL_IO_READ = 55_u32
  EVENT_TRACE_TYPE_OPTICAL_IO_WRITE = 56_u32
  EVENT_TRACE_TYPE_OPTICAL_IO_FLUSH = 57_u32
  EVENT_TRACE_TYPE_OPTICAL_IO_READ_INIT = 58_u32
  EVENT_TRACE_TYPE_OPTICAL_IO_WRITE_INIT = 59_u32
  EVENT_TRACE_TYPE_OPTICAL_IO_FLUSH_INIT = 60_u32
  EVENT_TRACE_TYPE_FLT_PREOP_INIT = 96_u32
  EVENT_TRACE_TYPE_FLT_POSTOP_INIT = 97_u32
  EVENT_TRACE_TYPE_FLT_PREOP_COMPLETION = 98_u32
  EVENT_TRACE_TYPE_FLT_POSTOP_COMPLETION = 99_u32
  EVENT_TRACE_TYPE_FLT_PREOP_FAILURE = 100_u32
  EVENT_TRACE_TYPE_FLT_POSTOP_FAILURE = 101_u32
  EVENT_TRACE_FLAG_DEBUG_EVENTS = 4194304_u32
  EVENT_TRACE_FLAG_EXTENSION = 2147483648_u32
  EVENT_TRACE_FLAG_FORWARD_WMI = 1073741824_u32
  EVENT_TRACE_FLAG_ENABLE_RESERVE = 536870912_u32
  EVENT_TRACE_FILE_MODE_NONE = 0_u32
  EVENT_TRACE_FILE_MODE_SEQUENTIAL = 1_u32
  EVENT_TRACE_FILE_MODE_CIRCULAR = 2_u32
  EVENT_TRACE_FILE_MODE_APPEND = 4_u32
  EVENT_TRACE_REAL_TIME_MODE = 256_u32
  EVENT_TRACE_DELAY_OPEN_FILE_MODE = 512_u32
  EVENT_TRACE_BUFFERING_MODE = 1024_u32
  EVENT_TRACE_PRIVATE_LOGGER_MODE = 2048_u32
  EVENT_TRACE_ADD_HEADER_MODE = 4096_u32
  EVENT_TRACE_USE_GLOBAL_SEQUENCE = 16384_u32
  EVENT_TRACE_USE_LOCAL_SEQUENCE = 32768_u32
  EVENT_TRACE_RELOG_MODE = 65536_u32
  EVENT_TRACE_USE_PAGED_MEMORY = 16777216_u32
  EVENT_TRACE_FILE_MODE_NEWFILE = 8_u32
  EVENT_TRACE_FILE_MODE_PREALLOCATE = 32_u32
  EVENT_TRACE_NONSTOPPABLE_MODE = 64_u32
  EVENT_TRACE_SECURE_MODE = 128_u32
  EVENT_TRACE_USE_KBYTES_FOR_SIZE = 8192_u32
  EVENT_TRACE_PRIVATE_IN_PROC = 131072_u32
  EVENT_TRACE_MODE_RESERVED = 1048576_u32
  EVENT_TRACE_NO_PER_PROCESSOR_BUFFERING = 268435456_u32
  EVENT_TRACE_SYSTEM_LOGGER_MODE = 33554432_u32
  EVENT_TRACE_ADDTO_TRIAGE_DUMP = 2147483648_u32
  EVENT_TRACE_STOP_ON_HYBRID_SHUTDOWN = 4194304_u32
  EVENT_TRACE_PERSIST_ON_HYBRID_SHUTDOWN = 8388608_u32
  EVENT_TRACE_INDEPENDENT_SESSION_MODE = 134217728_u32
  EVENT_TRACE_COMPRESSED_MODE = 67108864_u32
  EVENT_TRACE_CONTROL_INCREMENT_FILE = 4_u32
  EVENT_TRACE_CONTROL_CONVERT_TO_REALTIME = 5_u32
  TRACE_MESSAGE_PERFORMANCE_TIMESTAMP = 16_u32
  TRACE_MESSAGE_POINTER32 = 64_u32
  TRACE_MESSAGE_POINTER64 = 128_u32
  TRACE_MESSAGE_FLAG_MASK = 65535_u32
  EVENT_TRACE_USE_PROCTIME = 1_u32
  EVENT_TRACE_USE_NOCPUTIME = 2_u32
  TRACE_HEADER_FLAG_USE_TIMESTAMP = 512_u32
  TRACE_HEADER_FLAG_TRACED_GUID = 131072_u32
  TRACE_HEADER_FLAG_LOG_WNODE = 262144_u32
  TRACE_HEADER_FLAG_USE_GUID_PTR = 524288_u32
  TRACE_HEADER_FLAG_USE_MOF_PTR = 1048576_u32
  SYSTEM_ALPC_KW_GENERAL = 1_u64
  SYSTEM_CONFIG_KW_SYSTEM = 1_u64
  SYSTEM_CONFIG_KW_GRAPHICS = 2_u64
  SYSTEM_CONFIG_KW_STORAGE = 4_u64
  SYSTEM_CONFIG_KW_NETWORK = 8_u64
  SYSTEM_CONFIG_KW_SERVICES = 16_u64
  SYSTEM_CONFIG_KW_PNP = 32_u64
  SYSTEM_CONFIG_KW_OPTICAL = 64_u64
  SYSTEM_CPU_KW_CONFIG = 1_u64
  SYSTEM_CPU_KW_CACHE_FLUSH = 2_u64
  SYSTEM_CPU_KW_SPEC_CONTROL = 4_u64
  SYSTEM_HYPERVISOR_KW_PROFILE = 1_u64
  SYSTEM_HYPERVISOR_KW_CALLOUTS = 2_u64
  SYSTEM_HYPERVISOR_KW_VTL_CHANGE = 4_u64
  SYSTEM_INTERRUPT_KW_GENERAL = 1_u64
  SYSTEM_INTERRUPT_KW_CLOCK_INTERRUPT = 2_u64
  SYSTEM_INTERRUPT_KW_DPC = 4_u64
  SYSTEM_INTERRUPT_KW_DPC_QUEUE = 8_u64
  SYSTEM_INTERRUPT_KW_WDF_DPC = 16_u64
  SYSTEM_INTERRUPT_KW_WDF_INTERRUPT = 32_u64
  SYSTEM_INTERRUPT_KW_IPI = 64_u64
  SYSTEM_IO_KW_DISK = 1_u64
  SYSTEM_IO_KW_DISK_INIT = 2_u64
  SYSTEM_IO_KW_FILENAME = 4_u64
  SYSTEM_IO_KW_SPLIT = 8_u64
  SYSTEM_IO_KW_FILE = 16_u64
  SYSTEM_IO_KW_OPTICAL = 32_u64
  SYSTEM_IO_KW_OPTICAL_INIT = 64_u64
  SYSTEM_IO_KW_DRIVERS = 128_u64
  SYSTEM_IO_KW_CC = 256_u64
  SYSTEM_IO_KW_NETWORK = 512_u64
  SYSTEM_IOFILTER_KW_GENERAL = 1_u64
  SYSTEM_IOFILTER_KW_INIT = 2_u64
  SYSTEM_IOFILTER_KW_FASTIO = 4_u64
  SYSTEM_IOFILTER_KW_FAILURE = 8_u64
  SYSTEM_LOCK_KW_SPINLOCK = 1_u64
  SYSTEM_LOCK_KW_SPINLOCK_COUNTERS = 2_u64
  SYSTEM_LOCK_KW_SYNC_OBJECTS = 4_u64
  SYSTEM_MEMORY_KW_GENERAL = 1_u64
  SYSTEM_MEMORY_KW_HARD_FAULTS = 2_u64
  SYSTEM_MEMORY_KW_ALL_FAULTS = 4_u64
  SYSTEM_MEMORY_KW_POOL = 8_u64
  SYSTEM_MEMORY_KW_MEMINFO = 16_u64
  SYSTEM_MEMORY_KW_PFSECTION = 32_u64
  SYSTEM_MEMORY_KW_MEMINFO_WS = 64_u64
  SYSTEM_MEMORY_KW_HEAP = 128_u64
  SYSTEM_MEMORY_KW_WS = 256_u64
  SYSTEM_MEMORY_KW_CONTMEM_GEN = 512_u64
  SYSTEM_MEMORY_KW_VIRTUAL_ALLOC = 1024_u64
  SYSTEM_MEMORY_KW_FOOTPRINT = 2048_u64
  SYSTEM_MEMORY_KW_SESSION = 4096_u64
  SYSTEM_MEMORY_KW_REFSET = 8192_u64
  SYSTEM_MEMORY_KW_VAMAP = 16384_u64
  SYSTEM_MEMORY_KW_NONTRADEABLE = 32768_u64
  SYSTEM_OBJECT_KW_GENERAL = 1_u64
  SYSTEM_OBJECT_KW_HANDLE = 2_u64
  SYSTEM_POWER_KW_GENERAL = 1_u64
  SYSTEM_POWER_KW_HIBER_RUNDOWN = 2_u64
  SYSTEM_POWER_KW_PROCESSOR_IDLE = 4_u64
  SYSTEM_POWER_KW_IDLE_SELECTION = 8_u64
  SYSTEM_POWER_KW_PPM_EXIT_LATENCY = 16_u64
  SYSTEM_PROCESS_KW_GENERAL = 1_u64
  SYSTEM_PROCESS_KW_INSWAP = 2_u64
  SYSTEM_PROCESS_KW_FREEZE = 4_u64
  SYSTEM_PROCESS_KW_PERF_COUNTER = 8_u64
  SYSTEM_PROCESS_KW_WAKE_COUNTER = 16_u64
  SYSTEM_PROCESS_KW_WAKE_DROP = 32_u64
  SYSTEM_PROCESS_KW_WAKE_EVENT = 64_u64
  SYSTEM_PROCESS_KW_DEBUG_EVENTS = 128_u64
  SYSTEM_PROCESS_KW_DBGPRINT = 256_u64
  SYSTEM_PROCESS_KW_JOB = 512_u64
  SYSTEM_PROCESS_KW_WORKER_THREAD = 1024_u64
  SYSTEM_PROCESS_KW_THREAD = 2048_u64
  SYSTEM_PROCESS_KW_LOADER = 4096_u64
  SYSTEM_PROFILE_KW_GENERAL = 1_u64
  SYSTEM_PROFILE_KW_PMC_PROFILE = 2_u64
  SYSTEM_REGISTRY_KW_GENERAL = 1_u64
  SYSTEM_REGISTRY_KW_HIVE = 2_u64
  SYSTEM_REGISTRY_KW_NOTIFICATION = 4_u64
  SYSTEM_SCHEDULER_KW_XSCHEDULER = 1_u64
  SYSTEM_SCHEDULER_KW_DISPATCHER = 2_u64
  SYSTEM_SCHEDULER_KW_KERNEL_QUEUE = 4_u64
  SYSTEM_SCHEDULER_KW_SHOULD_YIELD = 8_u64
  SYSTEM_SCHEDULER_KW_ANTI_STARVATION = 16_u64
  SYSTEM_SCHEDULER_KW_LOAD_BALANCER = 32_u64
  SYSTEM_SCHEDULER_KW_AFFINITY = 64_u64
  SYSTEM_SCHEDULER_KW_PRIORITY = 128_u64
  SYSTEM_SCHEDULER_KW_IDEAL_PROCESSOR = 256_u64
  SYSTEM_SCHEDULER_KW_CONTEXT_SWITCH = 512_u64
  SYSTEM_SCHEDULER_KW_COMPACT_CSWITCH = 1024_u64
  SYSTEM_SYSCALL_KW_GENERAL = 1_u64
  SYSTEM_TIMER_KW_GENERAL = 1_u64
  SYSTEM_TIMER_KW_CLOCK_TIMER = 2_u64
  SYSTEM_MEMORY_POOL_FILTER_ID = 1_u32
  ETW_NULL_TYPE_VALUE = 0_u32
  ETW_OBJECT_TYPE_VALUE = 1_u32
  ETW_STRING_TYPE_VALUE = 2_u32
  ETW_SBYTE_TYPE_VALUE = 3_u32
  ETW_BYTE_TYPE_VALUE = 4_u32
  ETW_INT16_TYPE_VALUE = 5_u32
  ETW_UINT16_TYPE_VALUE = 6_u32
  ETW_INT32_TYPE_VALUE = 7_u32
  ETW_UINT32_TYPE_VALUE = 8_u32
  ETW_INT64_TYPE_VALUE = 9_u32
  ETW_UINT64_TYPE_VALUE = 10_u32
  ETW_CHAR_TYPE_VALUE = 11_u32
  ETW_SINGLE_TYPE_VALUE = 12_u32
  ETW_DOUBLE_TYPE_VALUE = 13_u32
  ETW_BOOLEAN_TYPE_VALUE = 14_u32
  ETW_DECIMAL_TYPE_VALUE = 15_u32
  ETW_GUID_TYPE_VALUE = 101_u32
  ETW_ASCIICHAR_TYPE_VALUE = 102_u32
  ETW_ASCIISTRING_TYPE_VALUE = 103_u32
  ETW_COUNTED_STRING_TYPE_VALUE = 104_u32
  ETW_POINTER_TYPE_VALUE = 105_u32
  ETW_SIZET_TYPE_VALUE = 106_u32
  ETW_HIDDEN_TYPE_VALUE = 107_u32
  ETW_BOOL_TYPE_VALUE = 108_u32
  ETW_COUNTED_ANSISTRING_TYPE_VALUE = 109_u32
  ETW_REVERSED_COUNTED_STRING_TYPE_VALUE = 110_u32
  ETW_REVERSED_COUNTED_ANSISTRING_TYPE_VALUE = 111_u32
  ETW_NON_NULL_TERMINATED_STRING_TYPE_VALUE = 112_u32
  ETW_REDUCED_ANSISTRING_TYPE_VALUE = 113_u32
  ETW_REDUCED_STRING_TYPE_VALUE = 114_u32
  ETW_SID_TYPE_VALUE = 115_u32
  ETW_VARIANT_TYPE_VALUE = 116_u32
  ETW_PTVECTOR_TYPE_VALUE = 117_u32
  ETW_WMITIME_TYPE_VALUE = 118_u32
  ETW_DATETIME_TYPE_VALUE = 119_u32
  ETW_REFRENCE_TYPE_VALUE = 120_u32
  TRACE_PROVIDER_FLAG_LEGACY = 1_u32
  TRACE_PROVIDER_FLAG_PRE_ENABLE = 2_u32
  ENABLE_TRACE_PARAMETERS_VERSION = 1_u32
  ENABLE_TRACE_PARAMETERS_VERSION_2 = 2_u32
  EVENT_MIN_LEVEL = 0_u32
  EVENT_MAX_LEVEL = 255_u32
  EVENT_ACTIVITY_CTRL_GET_ID = 1_u32
  EVENT_ACTIVITY_CTRL_SET_ID = 2_u32
  EVENT_ACTIVITY_CTRL_CREATE_ID = 3_u32
  EVENT_ACTIVITY_CTRL_GET_SET_ID = 4_u32
  EVENT_ACTIVITY_CTRL_CREATE_SET_ID = 5_u32
  MAX_EVENT_DATA_DESCRIPTORS = 128_u32
  MAX_EVENT_FILTER_DATA_SIZE = 1024_u32
  MAX_EVENT_FILTER_PAYLOAD_SIZE = 4096_u32
  MAX_EVENT_FILTER_EVENT_NAME_SIZE = 4096_u32
  MAX_EVENT_FILTERS_COUNT = 13_u32
  MAX_EVENT_FILTER_PID_COUNT = 8_u32
  MAX_EVENT_FILTER_EVENT_ID_COUNT = 64_u32
  EVENT_FILTER_TYPE_NONE = 0_u32
  EVENT_FILTER_TYPE_SCHEMATIZED = 2147483648_u32
  EVENT_FILTER_TYPE_SYSTEM_FLAGS = 2147483649_u32
  EVENT_FILTER_TYPE_TRACEHANDLE = 2147483650_u32
  EVENT_FILTER_TYPE_PID = 2147483652_u32
  EVENT_FILTER_TYPE_EXECUTABLE_NAME = 2147483656_u32
  EVENT_FILTER_TYPE_PACKAGE_ID = 2147483664_u32
  EVENT_FILTER_TYPE_PACKAGE_APP_ID = 2147483680_u32
  EVENT_FILTER_TYPE_PAYLOAD = 2147483904_u32
  EVENT_FILTER_TYPE_EVENT_ID = 2147484160_u32
  EVENT_FILTER_TYPE_EVENT_NAME = 2147484672_u32
  EVENT_FILTER_TYPE_STACKWALK = 2147487744_u32
  EVENT_FILTER_TYPE_STACKWALK_NAME = 2147491840_u32
  EVENT_FILTER_TYPE_STACKWALK_LEVEL_KW = 2147500032_u32
  EVENT_FILTER_TYPE_CONTAINER = 2147516416_u32
  EVENT_DATA_DESCRIPTOR_TYPE_NONE = 0_u32
  EVENT_DATA_DESCRIPTOR_TYPE_EVENT_METADATA = 1_u32
  EVENT_DATA_DESCRIPTOR_TYPE_PROVIDER_METADATA = 2_u32
  EVENT_DATA_DESCRIPTOR_TYPE_TIMESTAMP_OVERRIDE = 3_u32
  EVENT_WRITE_FLAG_NO_FAULTING = 1_u32
  EVENT_WRITE_FLAG_INPRIVATE = 2_u32
  EVENT_HEADER_EXT_TYPE_RELATED_ACTIVITYID = 1_u32
  EVENT_HEADER_EXT_TYPE_SID = 2_u32
  EVENT_HEADER_EXT_TYPE_TS_ID = 3_u32
  EVENT_HEADER_EXT_TYPE_INSTANCE_INFO = 4_u32
  EVENT_HEADER_EXT_TYPE_STACK_TRACE32 = 5_u32
  EVENT_HEADER_EXT_TYPE_STACK_TRACE64 = 6_u32
  EVENT_HEADER_EXT_TYPE_PEBS_INDEX = 7_u32
  EVENT_HEADER_EXT_TYPE_PMC_COUNTERS = 8_u32
  EVENT_HEADER_EXT_TYPE_PSM_KEY = 9_u32
  EVENT_HEADER_EXT_TYPE_EVENT_KEY = 10_u32
  EVENT_HEADER_EXT_TYPE_EVENT_SCHEMA_TL = 11_u32
  EVENT_HEADER_EXT_TYPE_PROV_TRAITS = 12_u32
  EVENT_HEADER_EXT_TYPE_PROCESS_START_KEY = 13_u32
  EVENT_HEADER_EXT_TYPE_CONTROL_GUID = 14_u32
  EVENT_HEADER_EXT_TYPE_QPC_DELTA = 15_u32
  EVENT_HEADER_EXT_TYPE_CONTAINER_ID = 16_u32
  EVENT_HEADER_EXT_TYPE_STACK_KEY32 = 17_u32
  EVENT_HEADER_EXT_TYPE_STACK_KEY64 = 18_u32
  EVENT_HEADER_EXT_TYPE_MAX = 19_u32
  EVENT_HEADER_PROPERTY_XML = 1_u32
  EVENT_HEADER_PROPERTY_FORWARDED_XML = 2_u32
  EVENT_HEADER_PROPERTY_LEGACY_EVENTLOG = 4_u32
  EVENT_HEADER_PROPERTY_RELOGGABLE = 8_u32
  EVENT_HEADER_FLAG_EXTENDED_INFO = 1_u32
  EVENT_HEADER_FLAG_PRIVATE_SESSION = 2_u32
  EVENT_HEADER_FLAG_STRING_ONLY = 4_u32
  EVENT_HEADER_FLAG_TRACE_MESSAGE = 8_u32
  EVENT_HEADER_FLAG_NO_CPUTIME = 16_u32
  EVENT_HEADER_FLAG_32_BIT_HEADER = 32_u32
  EVENT_HEADER_FLAG_64_BIT_HEADER = 64_u32
  EVENT_HEADER_FLAG_DECODE_GUID = 128_u32
  EVENT_HEADER_FLAG_CLASSIC_HEADER = 256_u32
  EVENT_HEADER_FLAG_PROCESSOR_INDEX = 512_u32
  EVENT_ENABLE_PROPERTY_SID = 1_u32
  EVENT_ENABLE_PROPERTY_TS_ID = 2_u32
  EVENT_ENABLE_PROPERTY_STACK_TRACE = 4_u32
  EVENT_ENABLE_PROPERTY_PSM_KEY = 8_u32
  EVENT_ENABLE_PROPERTY_IGNORE_KEYWORD_0 = 16_u32
  EVENT_ENABLE_PROPERTY_PROVIDER_GROUP = 32_u32
  EVENT_ENABLE_PROPERTY_ENABLE_KEYWORD_0 = 64_u32
  EVENT_ENABLE_PROPERTY_PROCESS_START_KEY = 128_u32
  EVENT_ENABLE_PROPERTY_EVENT_KEY = 256_u32
  EVENT_ENABLE_PROPERTY_EXCLUDE_INPRIVATE = 512_u32
  EVENT_ENABLE_PROPERTY_ENABLE_SILOS = 1024_u32
  EVENT_ENABLE_PROPERTY_SOURCE_CONTAINER_TRACKING = 2048_u32
  PROCESS_TRACE_MODE_REAL_TIME = 256_u32
  PROCESS_TRACE_MODE_RAW_TIMESTAMP = 4096_u32
  PROCESS_TRACE_MODE_EVENT_RECORD = 268435456_u32
  CLSID_TraceRelogger = "7b40792d-05ff-44c4-9058-f440c71f17d4"
  CTraceRelogger = LibC::GUID.new(0x7b40792d_u32, 0x5ff_u16, 0x44c4_u16, StaticArray[0x90_u8, 0x58_u8, 0xf4_u8, 0x40_u8, 0xc7_u8, 0x1f_u8, 0x17_u8, 0xd4_u8])

  alias PEVENT_TRACE_BUFFER_CALLBACKW = Proc(EVENT_TRACE_LOGFILEW*, UInt32)
  alias PEVENT_TRACE_BUFFER_CALLBACKA = Proc(EVENT_TRACE_LOGFILEA*, UInt32)
  alias PEVENT_CALLBACK = Proc(EVENT_TRACE*, Void)
  alias PEVENT_RECORD_CALLBACK = Proc(EVENT_RECORD*, Void)
  alias WMIDPREQUEST = Proc(WMIDPREQUESTCODE, Void*, UInt32*, Void*, UInt32)
  alias PENABLECALLBACK = Proc(Guid*, ENABLECALLBACK_ENABLED_STATE, UInt8, UInt64, UInt64, EVENT_FILTER_DESCRIPTOR*, Void*, Void)


  enum TRACE_MESSAGE_FLAGS : UInt32
    TRACE_MESSAGE_COMPONENTID = 4
    TRACE_MESSAGE_GUID = 2
    TRACE_MESSAGE_SEQUENCE = 1
    TRACE_MESSAGE_SYSTEMINFO = 32
    TRACE_MESSAGE_TIMESTAMP = 8
  end

  enum ENABLECALLBACK_ENABLED_STATE : UInt32
    EVENT_CONTROL_CODE_DISABLE_PROVIDER = 0
    EVENT_CONTROL_CODE_ENABLE_PROVIDER = 1
    EVENT_CONTROL_CODE_CAPTURE_STATE = 2
  end

  enum EVENT_TRACE_CONTROL : UInt32
    EVENT_TRACE_CONTROL_FLUSH = 3
    EVENT_TRACE_CONTROL_QUERY = 0
    EVENT_TRACE_CONTROL_STOP = 1
    EVENT_TRACE_CONTROL_UPDATE = 2
  end

  enum EVENT_TRACE_FLAG : UInt32
    EVENT_TRACE_FLAG_ALPC = 1048576
    EVENT_TRACE_FLAG_CSWITCH = 16
    EVENT_TRACE_FLAG_DBGPRINT = 262144
    EVENT_TRACE_FLAG_DISK_FILE_IO = 512
    EVENT_TRACE_FLAG_DISK_IO = 256
    EVENT_TRACE_FLAG_DISK_IO_INIT = 1024
    EVENT_TRACE_FLAG_DISPATCHER = 2048
    EVENT_TRACE_FLAG_DPC = 32
    EVENT_TRACE_FLAG_DRIVER = 8388608
    EVENT_TRACE_FLAG_FILE_IO = 33554432
    EVENT_TRACE_FLAG_FILE_IO_INIT = 67108864
    EVENT_TRACE_FLAG_IMAGE_LOAD = 4
    EVENT_TRACE_FLAG_INTERRUPT = 64
    EVENT_TRACE_FLAG_JOB = 524288
    EVENT_TRACE_FLAG_MEMORY_HARD_FAULTS = 8192
    EVENT_TRACE_FLAG_MEMORY_PAGE_FAULTS = 4096
    EVENT_TRACE_FLAG_NETWORK_TCPIP = 65536
    EVENT_TRACE_FLAG_NO_SYSCONFIG = 268435456
    EVENT_TRACE_FLAG_PROCESS = 1
    EVENT_TRACE_FLAG_PROCESS_COUNTERS = 8
    EVENT_TRACE_FLAG_PROFILE = 16777216
    EVENT_TRACE_FLAG_REGISTRY = 131072
    EVENT_TRACE_FLAG_SPLIT_IO = 2097152
    EVENT_TRACE_FLAG_SYSTEMCALL = 128
    EVENT_TRACE_FLAG_THREAD = 2
    EVENT_TRACE_FLAG_VAMAP = 32768
    EVENT_TRACE_FLAG_VIRTUAL_ALLOC = 16384
  end

  enum WMIDPREQUESTCODE : Int32
    WMI_GET_ALL_DATA = 0
    WMI_GET_SINGLE_INSTANCE = 1
    WMI_SET_SINGLE_INSTANCE = 2
    WMI_SET_SINGLE_ITEM = 3
    WMI_ENABLE_EVENTS = 4
    WMI_DISABLE_EVENTS = 5
    WMI_ENABLE_COLLECTION = 6
    WMI_DISABLE_COLLECTION = 7
    WMI_REGINFO = 8
    WMI_EXECUTE_METHOD = 9
    WMI_CAPTURE_STATE = 10
  end

  enum ETW_COMPRESSION_RESUMPTION_MODE : Int32
    EtwCompressionModeRestart = 0
    EtwCompressionModeNoDisable = 1
    EtwCompressionModeNoRestart = 2
  end

  enum ETW_PMC_COUNTER_OWNER_TYPE : Int32
    EtwPmcOwnerFree = 0
    EtwPmcOwnerUntagged = 1
    EtwPmcOwnerTagged = 2
    EtwPmcOwnerTaggedWithSource = 3
  end

  enum TRACE_QUERY_INFO_CLASS : Int32
    TraceGuidQueryList = 0
    TraceGuidQueryInfo = 1
    TraceGuidQueryProcess = 2
    TraceStackTracingInfo = 3
    TraceSystemTraceEnableFlagsInfo = 4
    TraceSampledProfileIntervalInfo = 5
    TraceProfileSourceConfigInfo = 6
    TraceProfileSourceListInfo = 7
    TracePmcEventListInfo = 8
    TracePmcCounterListInfo = 9
    TraceSetDisallowList = 10
    TraceVersionInfo = 11
    TraceGroupQueryList = 12
    TraceGroupQueryInfo = 13
    TraceDisallowListQuery = 14
    TraceInfoReserved15 = 15
    TracePeriodicCaptureStateListInfo = 16
    TracePeriodicCaptureStateInfo = 17
    TraceProviderBinaryTracking = 18
    TraceMaxLoggersQuery = 19
    TraceLbrConfigurationInfo = 20
    TraceLbrEventListInfo = 21
    TraceMaxPmcCounterQuery = 22
    TraceStreamCount = 23
    TraceStackCachingInfo = 24
    TracePmcCounterOwners = 25
    TraceUnifiedStackCachingInfo = 26
    MaxTraceSetInfoClass = 27
  end

  enum ETW_PROCESS_HANDLE_INFO_TYPE : Int32
    EtwQueryPartitionInformation = 1
    EtwQueryPartitionInformationV2 = 2
    EtwQueryLastDroppedTimes = 3
    EtwQueryProcessHandleInfoMax = 4
  end

  enum EVENT_INFO_CLASS : Int32
    EventProviderBinaryTrackInfo = 0
    EventProviderSetReserved1 = 1
    EventProviderSetTraits = 2
    EventProviderUseDescriptorType = 3
    MaxEventInfo = 4
  end

  enum ETW_PROVIDER_TRAIT_TYPE : Int32
    EtwProviderTraitTypeGroup = 1
    EtwProviderTraitDecodeGuid = 2
    EtwProviderTraitTypeMax = 3
  end

  enum EVENTSECURITYOPERATION : Int32
    EventSecuritySetDACL = 0
    EventSecuritySetSACL = 1
    EventSecurityAddDACL = 2
    EventSecurityAddSACL = 3
    EventSecurityMax = 4
  end

  enum MAP_FLAGS : Int32
    EVENTMAP_INFO_FLAG_MANIFEST_VALUEMAP = 1
    EVENTMAP_INFO_FLAG_MANIFEST_BITMAP = 2
    EVENTMAP_INFO_FLAG_MANIFEST_PATTERNMAP = 4
    EVENTMAP_INFO_FLAG_WBEM_VALUEMAP = 8
    EVENTMAP_INFO_FLAG_WBEM_BITMAP = 16
    EVENTMAP_INFO_FLAG_WBEM_FLAG = 32
    EVENTMAP_INFO_FLAG_WBEM_NO_MAP = 64
  end

  enum MAP_VALUETYPE : Int32
    EVENTMAP_ENTRY_VALUETYPE_ULONG = 0
    EVENTMAP_ENTRY_VALUETYPE_STRING = 1
  end

  enum TDH_IN_TYPE : Int32
    TDH_INTYPE_NULL = 0
    TDH_INTYPE_UNICODESTRING = 1
    TDH_INTYPE_ANSISTRING = 2
    TDH_INTYPE_INT8 = 3
    TDH_INTYPE_UINT8 = 4
    TDH_INTYPE_INT16 = 5
    TDH_INTYPE_UINT16 = 6
    TDH_INTYPE_INT32 = 7
    TDH_INTYPE_UINT32 = 8
    TDH_INTYPE_INT64 = 9
    TDH_INTYPE_UINT64 = 10
    TDH_INTYPE_FLOAT = 11
    TDH_INTYPE_DOUBLE = 12
    TDH_INTYPE_BOOLEAN = 13
    TDH_INTYPE_BINARY = 14
    TDH_INTYPE_GUID = 15
    TDH_INTYPE_POINTER = 16
    TDH_INTYPE_FILETIME = 17
    TDH_INTYPE_SYSTEMTIME = 18
    TDH_INTYPE_SID = 19
    TDH_INTYPE_HEXINT32 = 20
    TDH_INTYPE_HEXINT64 = 21
    TDH_INTYPE_MANIFEST_COUNTEDSTRING = 22
    TDH_INTYPE_MANIFEST_COUNTEDANSISTRING = 23
    TDH_INTYPE_RESERVED24 = 24
    TDH_INTYPE_MANIFEST_COUNTEDBINARY = 25
    TDH_INTYPE_COUNTEDSTRING = 300
    TDH_INTYPE_COUNTEDANSISTRING = 301
    TDH_INTYPE_REVERSEDCOUNTEDSTRING = 302
    TDH_INTYPE_REVERSEDCOUNTEDANSISTRING = 303
    TDH_INTYPE_NONNULLTERMINATEDSTRING = 304
    TDH_INTYPE_NONNULLTERMINATEDANSISTRING = 305
    TDH_INTYPE_UNICODECHAR = 306
    TDH_INTYPE_ANSICHAR = 307
    TDH_INTYPE_SIZET = 308
    TDH_INTYPE_HEXDUMP = 309
    TDH_INTYPE_WBEMSID = 310
  end

  enum TDH_OUT_TYPE : Int32
    TDH_OUTTYPE_NULL = 0
    TDH_OUTTYPE_STRING = 1
    TDH_OUTTYPE_DATETIME = 2
    TDH_OUTTYPE_BYTE = 3
    TDH_OUTTYPE_UNSIGNEDBYTE = 4
    TDH_OUTTYPE_SHORT = 5
    TDH_OUTTYPE_UNSIGNEDSHORT = 6
    TDH_OUTTYPE_INT = 7
    TDH_OUTTYPE_UNSIGNEDINT = 8
    TDH_OUTTYPE_LONG = 9
    TDH_OUTTYPE_UNSIGNEDLONG = 10
    TDH_OUTTYPE_FLOAT = 11
    TDH_OUTTYPE_DOUBLE = 12
    TDH_OUTTYPE_BOOLEAN = 13
    TDH_OUTTYPE_GUID = 14
    TDH_OUTTYPE_HEXBINARY = 15
    TDH_OUTTYPE_HEXINT8 = 16
    TDH_OUTTYPE_HEXINT16 = 17
    TDH_OUTTYPE_HEXINT32 = 18
    TDH_OUTTYPE_HEXINT64 = 19
    TDH_OUTTYPE_PID = 20
    TDH_OUTTYPE_TID = 21
    TDH_OUTTYPE_PORT = 22
    TDH_OUTTYPE_IPV4 = 23
    TDH_OUTTYPE_IPV6 = 24
    TDH_OUTTYPE_SOCKETADDRESS = 25
    TDH_OUTTYPE_CIMDATETIME = 26
    TDH_OUTTYPE_ETWTIME = 27
    TDH_OUTTYPE_XML = 28
    TDH_OUTTYPE_ERRORCODE = 29
    TDH_OUTTYPE_WIN32ERROR = 30
    TDH_OUTTYPE_NTSTATUS = 31
    TDH_OUTTYPE_HRESULT = 32
    TDH_OUTTYPE_CULTURE_INSENSITIVE_DATETIME = 33
    TDH_OUTTYPE_JSON = 34
    TDH_OUTTYPE_UTF8 = 35
    TDH_OUTTYPE_PKCS7_WITH_TYPE_INFO = 36
    TDH_OUTTYPE_CODE_POINTER = 37
    TDH_OUTTYPE_DATETIME_UTC = 38
    TDH_OUTTYPE_REDUCEDSTRING = 300
    TDH_OUTTYPE_NOPRINT = 301
  end

  enum PROPERTY_FLAGS : Int32
    PropertyStruct = 1
    PropertyParamLength = 2
    PropertyParamCount = 4
    PropertyWBEMXmlFragment = 8
    PropertyParamFixedLength = 16
    PropertyParamFixedCount = 32
    PropertyHasTags = 64
    PropertyHasCustomSchema = 128
  end

  enum DECODING_SOURCE : Int32
    DecodingSourceXMLFile = 0
    DecodingSourceWbem = 1
    DecodingSourceWPP = 2
    DecodingSourceTlg = 3
    DecodingSourceMax = 4
  end

  enum TEMPLATE_FLAGS : Int32
    TEMPLATE_EVENT_DATA = 1
    TEMPLATE_USER_DATA = 2
    TEMPLATE_CONTROL_GUID = 4
  end

  enum PAYLOAD_OPERATOR : Int32
    PAYLOADFIELD_EQ = 0
    PAYLOADFIELD_NE = 1
    PAYLOADFIELD_LE = 2
    PAYLOADFIELD_GT = 3
    PAYLOADFIELD_LT = 4
    PAYLOADFIELD_GE = 5
    PAYLOADFIELD_BETWEEN = 6
    PAYLOADFIELD_NOTBETWEEN = 7
    PAYLOADFIELD_MODULO = 8
    PAYLOADFIELD_CONTAINS = 20
    PAYLOADFIELD_DOESNTCONTAIN = 21
    PAYLOADFIELD_IS = 30
    PAYLOADFIELD_ISNOT = 31
    PAYLOADFIELD_INVALID = 32
  end

  enum EVENT_FIELD_TYPE : Int32
    EventKeywordInformation = 0
    EventLevelInformation = 1
    EventChannelInformation = 2
    EventTaskInformation = 3
    EventOpcodeInformation = 4
    EventInformationMax = 5
  end

  enum TDH_CONTEXT_TYPE : Int32
    TDH_CONTEXT_WPP_TMFFILE = 0
    TDH_CONTEXT_WPP_TMFSEARCHPATH = 1
    TDH_CONTEXT_WPP_GMT = 2
    TDH_CONTEXT_POINTERSIZE = 3
    TDH_CONTEXT_PDB_PATH = 4
    TDH_CONTEXT_MAXIMUM = 5
  end

union WNODE_HEADER_Anonymous2_e__Union
  count_lost : UInt32
  kernel_handle : LibC::HANDLE
  time_stamp : LARGE_INTEGER
end
union WNODE_HEADER_Anonymous1_e__Union
  historical_context : UInt64
  anonymous : WNODE_HEADER_Anonymous1_e__Union_Anonymous_e__Struct
end
union WNODE_ALL_DATA_Anonymous_e__Union
  fixed_instance_size : UInt32
  offset_instance_data_and_length : OFFSETINSTANCEDATAANDLENGTH[0]*
end
union WNODE_EVENT_REFERENCE_Anonymous_e__Union
  target_instance_index : UInt32
  target_instance_name : Char[0]*
end
union WMIREGGUIDW_Anonymous_e__Union
  instance_name_list : UInt32
  base_name_offset : UInt32
  pdo : LibC::UINT_PTR
  instance_info : LibC::UINT_PTR
end
union EVENT_TRACE_HEADER_Anonymous4_e__Union
  anonymous1 : EVENT_TRACE_HEADER_Anonymous4_e__Union_Anonymous1_e__Struct
  processor_time : UInt64
  anonymous2 : EVENT_TRACE_HEADER_Anonymous4_e__Union_Anonymous2_e__Struct
end
union EVENT_TRACE_HEADER_Anonymous2_e__Union
  version : UInt32
  class : EVENT_TRACE_HEADER_Anonymous2_e__Union_Class_e__Struct
end
union EVENT_TRACE_HEADER_Anonymous1_e__Union
  field_type_flags : UInt16
  anonymous : EVENT_TRACE_HEADER_Anonymous1_e__Union_Anonymous_e__Struct
end
union EVENT_TRACE_HEADER_Anonymous3_e__Union
  guid : Guid
  guid_ptr : UInt64
end
union EVENT_INSTANCE_HEADER_Anonymous3_e__Union
  anonymous1 : EVENT_INSTANCE_HEADER_Anonymous3_e__Union_Anonymous1_e__Struct
  processor_time : UInt64
  anonymous2 : EVENT_INSTANCE_HEADER_Anonymous3_e__Union_Anonymous2_e__Struct
end
union EVENT_INSTANCE_HEADER_Anonymous2_e__Union
  version : UInt32
  class : EVENT_INSTANCE_HEADER_Anonymous2_e__Union_Class_e__Struct
end
union EVENT_INSTANCE_HEADER_Anonymous1_e__Union
  field_type_flags : UInt16
  anonymous : EVENT_INSTANCE_HEADER_Anonymous1_e__Union_Anonymous_e__Struct
end
union TRACE_LOGFILE_HEADER_Anonymous2_e__Union
  log_instance_guid : Guid
  anonymous : TRACE_LOGFILE_HEADER_Anonymous2_e__Union_Anonymous_e__Struct
end
union TRACE_LOGFILE_HEADER_Anonymous1_e__Union
  version : UInt32
  version_detail : TRACE_LOGFILE_HEADER_Anonymous1_e__Union_VersionDetail_e__Struct
end
union TRACE_LOGFILE_HEADER32_Anonymous2_e__Union
  log_instance_guid : Guid
  anonymous : TRACE_LOGFILE_HEADER32_Anonymous2_e__Union_Anonymous_e__Struct
end
union TRACE_LOGFILE_HEADER32_Anonymous1_e__Union
  version : UInt32
  version_detail : TRACE_LOGFILE_HEADER32_Anonymous1_e__Union_VersionDetail_e__Struct
end
union TRACE_LOGFILE_HEADER64_Anonymous2_e__Union
  log_instance_guid : Guid
  anonymous : TRACE_LOGFILE_HEADER64_Anonymous2_e__Union_Anonymous_e__Struct
end
union TRACE_LOGFILE_HEADER64_Anonymous1_e__Union
  version : UInt32
  version_detail : TRACE_LOGFILE_HEADER64_Anonymous1_e__Union_VersionDetail_e__Struct
end
union EVENT_TRACE_PROPERTIES_Anonymous_e__Union
  age_limit : Int32
  flush_threshold : Int32
end
union EVENT_TRACE_PROPERTIES_V2_Anonymous3_e__Union
  anonymous : EVENT_TRACE_PROPERTIES_V2_Anonymous3_e__Union_Anonymous_e__Struct
  v2_options : UInt64
end
union EVENT_TRACE_PROPERTIES_V2_Anonymous2_e__Union
  anonymous : EVENT_TRACE_PROPERTIES_V2_Anonymous2_e__Union_Anonymous_e__Struct
  v2_control : UInt32
end
union EVENT_TRACE_PROPERTIES_V2_Anonymous1_e__Union
  age_limit : Int32
  flush_threshold : Int32
end
union ETW_BUFFER_CONTEXT_Anonymous_e__Union
  anonymous : ETW_BUFFER_CONTEXT_Anonymous_e__Union_Anonymous_e__Struct
  processor_index : UInt16
end
union EVENT_TRACE_Anonymous_e__Union
  client_context : UInt32
  buffer_context : ETW_BUFFER_CONTEXT
end
union EVENT_TRACE_LOGFILEW_Anonymous1_e__Union
  log_file_mode : UInt32
  process_trace_mode : UInt32
end
union EVENT_TRACE_LOGFILEW_Anonymous2_e__Union
  event_callback : PEVENT_CALLBACK
  event_record_callback : PEVENT_RECORD_CALLBACK
end
union EVENT_TRACE_LOGFILEA_Anonymous1_e__Union
  log_file_mode : UInt32
  process_trace_mode : UInt32
end
union EVENT_TRACE_LOGFILEA_Anonymous2_e__Union
  event_callback : PEVENT_CALLBACK
  event_record_callback : PEVENT_RECORD_CALLBACK
end
union EVENT_DATA_DESCRIPTOR_Anonymous_e__Union
  reserved : UInt32
  anonymous : EVENT_DATA_DESCRIPTOR_Anonymous_e__Union_Anonymous_e__Struct
end
union EVENT_HEADER_Anonymous_e__Union
  anonymous : EVENT_HEADER_Anonymous_e__Union_Anonymous_e__Struct
  processor_time : UInt64
end
union EVENT_MAP_ENTRY_Anonymous_e__Union
  value : UInt32
  input_offset : UInt32
end
union EVENT_MAP_INFO_Anonymous_e__Union
  map_entry_value_type : MAP_VALUETYPE
  format_string_offset : UInt32
end
union EVENT_PROPERTY_INFO_Anonymous4_e__Union
  reserved : UInt32
  anonymous : EVENT_PROPERTY_INFO_Anonymous4_e__Union_Anonymous_e__Struct
end
union EVENT_PROPERTY_INFO_Anonymous2_e__Union
  count : UInt16
  count_property_index : UInt16
end
union EVENT_PROPERTY_INFO_Anonymous1_e__Union
  non_struct_type : EVENT_PROPERTY_INFO_Anonymous1_e__Union_nonStructType
  struct_type : EVENT_PROPERTY_INFO_Anonymous1_e__Union_structType
  custom_schema_type : EVENT_PROPERTY_INFO_Anonymous1_e__Union_customSchemaType
end
union EVENT_PROPERTY_INFO_Anonymous3_e__Union
  length : UInt16
  length_property_index : UInt16
end
union TRACE_EVENT_INFO_Anonymous3_e__Union
  flags : TEMPLATE_FLAGS
  anonymous : TRACE_EVENT_INFO_Anonymous3_e__Union_Anonymous_e__Struct
end
union TRACE_EVENT_INFO_Anonymous1_e__Union
  event_name_offset : UInt32
  activity_id_name_offset : UInt32
end
union TRACE_EVENT_INFO_Anonymous2_e__Union
  event_attributes_offset : UInt32
  related_activity_id_name_offset : UInt32
end

  struct WNODE_HEADER
    buffer_size : UInt32
    provider_id : UInt32
    anonymous1 : WNODE_HEADER_Anonymous1_e__Union
    anonymous2 : WNODE_HEADER_Anonymous2_e__Union
    guid : Guid
    client_context : UInt32
    flags : UInt32
  end
  struct WNODE_HEADER_Anonymous1_e__Union_Anonymous_e__Struct
    version : UInt32
    linkage : UInt32
  end
  struct OFFSETINSTANCEDATAANDLENGTH
    offset_instance_data : UInt32
    length_instance_data : UInt32
  end
  struct WNODE_ALL_DATA
    wnode_header : WNODE_HEADER
    data_block_offset : UInt32
    instance_count : UInt32
    offset_instance_name_offsets : UInt32
    anonymous : WNODE_ALL_DATA_Anonymous_e__Union
  end
  struct WNODE_SINGLE_INSTANCE
    wnode_header : WNODE_HEADER
    offset_instance_name : UInt32
    instance_index : UInt32
    data_block_offset : UInt32
    size_data_block : UInt32
    variable_data : UInt8[0]*
  end
  struct WNODE_SINGLE_ITEM
    wnode_header : WNODE_HEADER
    offset_instance_name : UInt32
    instance_index : UInt32
    item_id : UInt32
    data_block_offset : UInt32
    size_data_item : UInt32
    variable_data : UInt8[0]*
  end
  struct WNODE_METHOD_ITEM
    wnode_header : WNODE_HEADER
    offset_instance_name : UInt32
    instance_index : UInt32
    method_id : UInt32
    data_block_offset : UInt32
    size_data_block : UInt32
    variable_data : UInt8[0]*
  end
  struct WNODE_EVENT_ITEM
    wnode_header : WNODE_HEADER
  end
  struct WNODE_EVENT_REFERENCE
    wnode_header : WNODE_HEADER
    target_guid : Guid
    target_data_block_size : UInt32
    anonymous : WNODE_EVENT_REFERENCE_Anonymous_e__Union
  end
  struct WNODE_TOO_SMALL
    wnode_header : WNODE_HEADER
    size_needed : UInt32
  end
  struct WMIREGGUIDW
    guid : Guid
    flags : UInt32
    instance_count : UInt32
    anonymous : WMIREGGUIDW_Anonymous_e__Union
  end
  struct WMIREGINFOW
    buffer_size : UInt32
    next_wmi_reg_info : UInt32
    registry_path : UInt32
    mof_resource_name : UInt32
    guid_count : UInt32
    wmi_reg_guid : WMIREGGUIDW[0]*
  end
  struct EVENT_TRACE_HEADER
    size : UInt16
    anonymous1 : EVENT_TRACE_HEADER_Anonymous1_e__Union
    anonymous2 : EVENT_TRACE_HEADER_Anonymous2_e__Union
    thread_id : UInt32
    process_id : UInt32
    time_stamp : LARGE_INTEGER
    anonymous3 : EVENT_TRACE_HEADER_Anonymous3_e__Union
    anonymous4 : EVENT_TRACE_HEADER_Anonymous4_e__Union
  end
  struct EVENT_TRACE_HEADER_Anonymous4_e__Union_Anonymous2_e__Struct
    client_context : UInt32
    flags : UInt32
  end
  struct EVENT_TRACE_HEADER_Anonymous4_e__Union_Anonymous1_e__Struct
    kernel_time : UInt32
    user_time : UInt32
  end
  struct EVENT_TRACE_HEADER_Anonymous2_e__Union_Class_e__Struct
    type : UInt8
    level : UInt8
    version : UInt16
  end
  struct EVENT_TRACE_HEADER_Anonymous1_e__Union_Anonymous_e__Struct
    header_type : UInt8
    marker_flags : UInt8
  end
  struct EVENT_INSTANCE_HEADER
    size : UInt16
    anonymous1 : EVENT_INSTANCE_HEADER_Anonymous1_e__Union
    anonymous2 : EVENT_INSTANCE_HEADER_Anonymous2_e__Union
    thread_id : UInt32
    process_id : UInt32
    time_stamp : LARGE_INTEGER
    reg_handle : UInt64
    instance_id : UInt32
    parent_instance_id : UInt32
    anonymous3 : EVENT_INSTANCE_HEADER_Anonymous3_e__Union
    parent_reg_handle : UInt64
  end
  struct EVENT_INSTANCE_HEADER_Anonymous3_e__Union_Anonymous2_e__Struct
    event_id : UInt32
    flags : UInt32
  end
  struct EVENT_INSTANCE_HEADER_Anonymous3_e__Union_Anonymous1_e__Struct
    kernel_time : UInt32
    user_time : UInt32
  end
  struct EVENT_INSTANCE_HEADER_Anonymous2_e__Union_Class_e__Struct
    type : UInt8
    level : UInt8
    version : UInt16
  end
  struct EVENT_INSTANCE_HEADER_Anonymous1_e__Union_Anonymous_e__Struct
    header_type : UInt8
    marker_flags : UInt8
  end
  struct MOF_FIELD
    data_ptr : UInt64
    length : UInt32
    data_type : UInt32
  end
  struct TRACE_LOGFILE_HEADER
    buffer_size : UInt32
    anonymous1 : TRACE_LOGFILE_HEADER_Anonymous1_e__Union
    provider_version : UInt32
    number_of_processors : UInt32
    end_time : LARGE_INTEGER
    timer_resolution : UInt32
    maximum_file_size : UInt32
    log_file_mode : UInt32
    buffers_written : UInt32
    anonymous2 : TRACE_LOGFILE_HEADER_Anonymous2_e__Union
    logger_name : LibC::LPWSTR
    log_file_name : LibC::LPWSTR
    time_zone : TIME_ZONE_INFORMATION
    boot_time : LARGE_INTEGER
    perf_freq : LARGE_INTEGER
    start_time : LARGE_INTEGER
    reserved_flags : UInt32
    buffers_lost : UInt32
  end
  struct TRACE_LOGFILE_HEADER_Anonymous2_e__Union_Anonymous_e__Struct
    start_buffers : UInt32
    pointer_size : UInt32
    events_lost : UInt32
    cpu_speed_in_m_hz : UInt32
  end
  struct TRACE_LOGFILE_HEADER_Anonymous1_e__Union_VersionDetail_e__Struct
    major_version : UInt8
    minor_version : UInt8
    sub_version : UInt8
    sub_minor_version : UInt8
  end
  struct TRACE_LOGFILE_HEADER32
    buffer_size : UInt32
    anonymous1 : TRACE_LOGFILE_HEADER32_Anonymous1_e__Union
    provider_version : UInt32
    number_of_processors : UInt32
    end_time : LARGE_INTEGER
    timer_resolution : UInt32
    maximum_file_size : UInt32
    log_file_mode : UInt32
    buffers_written : UInt32
    anonymous2 : TRACE_LOGFILE_HEADER32_Anonymous2_e__Union
    logger_name : UInt32
    log_file_name : UInt32
    time_zone : TIME_ZONE_INFORMATION
    boot_time : LARGE_INTEGER
    perf_freq : LARGE_INTEGER
    start_time : LARGE_INTEGER
    reserved_flags : UInt32
    buffers_lost : UInt32
  end
  struct TRACE_LOGFILE_HEADER32_Anonymous2_e__Union_Anonymous_e__Struct
    start_buffers : UInt32
    pointer_size : UInt32
    events_lost : UInt32
    cpu_speed_in_m_hz : UInt32
  end
  struct TRACE_LOGFILE_HEADER32_Anonymous1_e__Union_VersionDetail_e__Struct
    major_version : UInt8
    minor_version : UInt8
    sub_version : UInt8
    sub_minor_version : UInt8
  end
  struct TRACE_LOGFILE_HEADER64
    buffer_size : UInt32
    anonymous1 : TRACE_LOGFILE_HEADER64_Anonymous1_e__Union
    provider_version : UInt32
    number_of_processors : UInt32
    end_time : LARGE_INTEGER
    timer_resolution : UInt32
    maximum_file_size : UInt32
    log_file_mode : UInt32
    buffers_written : UInt32
    anonymous2 : TRACE_LOGFILE_HEADER64_Anonymous2_e__Union
    logger_name : UInt64
    log_file_name : UInt64
    time_zone : TIME_ZONE_INFORMATION
    boot_time : LARGE_INTEGER
    perf_freq : LARGE_INTEGER
    start_time : LARGE_INTEGER
    reserved_flags : UInt32
    buffers_lost : UInt32
  end
  struct TRACE_LOGFILE_HEADER64_Anonymous2_e__Union_Anonymous_e__Struct
    start_buffers : UInt32
    pointer_size : UInt32
    events_lost : UInt32
    cpu_speed_in_m_hz : UInt32
  end
  struct TRACE_LOGFILE_HEADER64_Anonymous1_e__Union_VersionDetail_e__Struct
    major_version : UInt8
    minor_version : UInt8
    sub_version : UInt8
    sub_minor_version : UInt8
  end
  struct EVENT_INSTANCE_INFO
    reg_handle : LibC::HANDLE
    instance_id : UInt32
  end
  struct EVENT_TRACE_PROPERTIES
    wnode : WNODE_HEADER
    buffer_size : UInt32
    minimum_buffers : UInt32
    maximum_buffers : UInt32
    maximum_file_size : UInt32
    log_file_mode : UInt32
    flush_timer : UInt32
    enable_flags : EVENT_TRACE_FLAG
    anonymous : EVENT_TRACE_PROPERTIES_Anonymous_e__Union
    number_of_buffers : UInt32
    free_buffers : UInt32
    events_lost : UInt32
    buffers_written : UInt32
    log_buffers_lost : UInt32
    real_time_buffers_lost : UInt32
    logger_thread_id : LibC::HANDLE
    log_file_name_offset : UInt32
    logger_name_offset : UInt32
  end
  struct EVENT_TRACE_PROPERTIES_V2
    wnode : WNODE_HEADER
    buffer_size : UInt32
    minimum_buffers : UInt32
    maximum_buffers : UInt32
    maximum_file_size : UInt32
    log_file_mode : UInt32
    flush_timer : UInt32
    enable_flags : EVENT_TRACE_FLAG
    anonymous1 : EVENT_TRACE_PROPERTIES_V2_Anonymous1_e__Union
    number_of_buffers : UInt32
    free_buffers : UInt32
    events_lost : UInt32
    buffers_written : UInt32
    log_buffers_lost : UInt32
    real_time_buffers_lost : UInt32
    logger_thread_id : LibC::HANDLE
    log_file_name_offset : UInt32
    logger_name_offset : UInt32
    anonymous2 : EVENT_TRACE_PROPERTIES_V2_Anonymous2_e__Union
    filter_desc_count : UInt32
    filter_desc : EVENT_FILTER_DESCRIPTOR*
    anonymous3 : EVENT_TRACE_PROPERTIES_V2_Anonymous3_e__Union
  end
  struct EVENT_TRACE_PROPERTIES_V2_Anonymous3_e__Union_Anonymous_e__Struct
    _bitfield : UInt32
  end
  struct EVENT_TRACE_PROPERTIES_V2_Anonymous2_e__Union_Anonymous_e__Struct
    _bitfield : UInt32
  end
  struct TRACE_GUID_REGISTRATION
    guid : Guid*
    reg_handle : LibC::HANDLE
  end
  struct TRACE_GUID_PROPERTIES
    guid : Guid
    guid_type : UInt32
    logger_id : UInt32
    enable_level : UInt32
    enable_flags : UInt32
    is_enable : BOOLEAN
  end
  struct ETW_BUFFER_CONTEXT
    anonymous : ETW_BUFFER_CONTEXT_Anonymous_e__Union
    logger_id : UInt16
  end
  struct ETW_BUFFER_CONTEXT_Anonymous_e__Union_Anonymous_e__Struct
    processor_number : UInt8
    alignment : UInt8
  end
  struct TRACE_ENABLE_INFO
    is_enabled : UInt32
    level : UInt8
    reserved1 : UInt8
    logger_id : UInt16
    enable_property : UInt32
    reserved2 : UInt32
    match_any_keyword : UInt64
    match_all_keyword : UInt64
  end
  struct TRACE_PROVIDER_INSTANCE_INFO
    next_offset : UInt32
    enable_count : UInt32
    pid : UInt32
    flags : UInt32
  end
  struct TRACE_GUID_INFO
    instance_count : UInt32
    reserved : UInt32
  end
  struct PROFILE_SOURCE_INFO
    next_entry_offset : UInt32
    source : UInt32
    min_interval : UInt32
    max_interval : UInt32
    reserved : UInt64
    description : Char[0]*
  end
  struct ETW_PMC_COUNTER_OWNER
    owner_type : ETW_PMC_COUNTER_OWNER_TYPE
    profile_source : UInt32
    owner_tag : UInt32
  end
  struct ETW_PMC_COUNTER_OWNERSHIP_STATUS
    processor_number : UInt32
    number_of_counters : UInt32
    counter_owners : ETW_PMC_COUNTER_OWNER[0]*
  end
  struct EVENT_TRACE
    header : EVENT_TRACE_HEADER
    instance_id : UInt32
    parent_instance_id : UInt32
    parent_guid : Guid
    mof_data : Void*
    mof_length : UInt32
    anonymous : EVENT_TRACE_Anonymous_e__Union
  end
  struct EVENT_TRACE_LOGFILEW
    log_file_name : LibC::LPWSTR
    logger_name : LibC::LPWSTR
    current_time : Int64
    buffers_read : UInt32
    anonymous1 : EVENT_TRACE_LOGFILEW_Anonymous1_e__Union
    current_event : EVENT_TRACE
    logfile_header : TRACE_LOGFILE_HEADER
    buffer_callback : PEVENT_TRACE_BUFFER_CALLBACKW
    buffer_size : UInt32
    filled : UInt32
    events_lost : UInt32
    anonymous2 : EVENT_TRACE_LOGFILEW_Anonymous2_e__Union
    is_kernel_trace : UInt32
    context : Void*
  end
  struct EVENT_TRACE_LOGFILEA
    log_file_name : PSTR
    logger_name : PSTR
    current_time : Int64
    buffers_read : UInt32
    anonymous1 : EVENT_TRACE_LOGFILEA_Anonymous1_e__Union
    current_event : EVENT_TRACE
    logfile_header : TRACE_LOGFILE_HEADER
    buffer_callback : PEVENT_TRACE_BUFFER_CALLBACKA
    buffer_size : UInt32
    filled : UInt32
    events_lost : UInt32
    anonymous2 : EVENT_TRACE_LOGFILEA_Anonymous2_e__Union
    is_kernel_trace : UInt32
    context : Void*
  end
  struct ENABLE_TRACE_PARAMETERS_V1
    version : UInt32
    enable_property : UInt32
    control_flags : UInt32
    source_id : Guid
    enable_filter_desc : EVENT_FILTER_DESCRIPTOR*
  end
  struct ENABLE_TRACE_PARAMETERS
    version : UInt32
    enable_property : UInt32
    control_flags : UInt32
    source_id : Guid
    enable_filter_desc : EVENT_FILTER_DESCRIPTOR*
    filter_desc_count : UInt32
  end
  struct CLASSIC_EVENT_ID
    event_guid : Guid
    type : UInt8
    reserved : UInt8[7]*
  end
  struct TRACE_STACK_CACHING_INFO
    enabled : BOOLEAN
    cache_size : UInt32
    bucket_count : UInt32
  end
  struct TRACE_PROFILE_INTERVAL
    source : UInt32
    interval : UInt32
  end
  struct TRACE_VERSION_INFO
    etw_trace_processing_version : UInt32
    reserved : UInt32
  end
  struct TRACE_PERIODIC_CAPTURE_STATE_INFO
    capture_state_frequency_in_seconds : UInt32
    provider_count : UInt16
    reserved : UInt16
  end
  struct ETW_TRACE_PARTITION_INFORMATION
    partition_id : Guid
    parent_id : Guid
    qpc_offset_from_root : Int64
    partition_type : UInt32
  end
  struct ETW_TRACE_PARTITION_INFORMATION_V2
    qpc_offset_from_root : Int64
    partition_type : UInt32
    partition_id : LibC::LPWSTR
    parent_id : LibC::LPWSTR
  end
  struct EVENT_DATA_DESCRIPTOR
    ptr : UInt64
    size : UInt32
    anonymous : EVENT_DATA_DESCRIPTOR_Anonymous_e__Union
  end
  struct EVENT_DATA_DESCRIPTOR_Anonymous_e__Union_Anonymous_e__Struct
    type : UInt8
    reserved1 : UInt8
    reserved2 : UInt16
  end
  struct EVENT_DESCRIPTOR
    id : UInt16
    version : UInt8
    channel : UInt8
    level : UInt8
    opcode : UInt8
    task : UInt16
    keyword : UInt64
  end
  struct EVENT_FILTER_DESCRIPTOR
    ptr : UInt64
    size : UInt32
    type : UInt32
  end
  struct EVENT_FILTER_HEADER
    id : UInt16
    version : UInt8
    reserved : UInt8[5]*
    instance_id : UInt64
    size : UInt32
    next_offset : UInt32
  end
  struct EVENT_FILTER_EVENT_ID
    filter_in : BOOLEAN
    reserved : UInt8
    count : UInt16
    events : UInt16[0]*
  end
  struct EVENT_FILTER_EVENT_NAME
    match_any_keyword : UInt64
    match_all_keyword : UInt64
    level : UInt8
    filter_in : BOOLEAN
    name_count : UInt16
    names : UInt8[0]*
  end
  struct EVENT_FILTER_LEVEL_KW
    match_any_keyword : UInt64
    match_all_keyword : UInt64
    level : UInt8
    filter_in : BOOLEAN
  end
  struct EVENT_HEADER_EXTENDED_DATA_ITEM
    reserved1 : UInt16
    ext_type : UInt16
    anonymous : EVENT_HEADER_EXTENDED_DATA_ITEM_Anonymous_e__Struct
    data_size : UInt16
    data_ptr : UInt64
  end
  struct EVENT_HEADER_EXTENDED_DATA_ITEM_Anonymous_e__Struct
    _bitfield : UInt16
  end
  struct EVENT_EXTENDED_ITEM_INSTANCE
    instance_id : UInt32
    parent_instance_id : UInt32
    parent_guid : Guid
  end
  struct EVENT_EXTENDED_ITEM_RELATED_ACTIVITYID
    related_activity_id : Guid
  end
  struct EVENT_EXTENDED_ITEM_TS_ID
    session_id : UInt32
  end
  struct EVENT_EXTENDED_ITEM_STACK_TRACE32
    match_id : UInt64
    address : UInt32[0]*
  end
  struct EVENT_EXTENDED_ITEM_STACK_TRACE64
    match_id : UInt64
    address : UInt64[0]*
  end
  struct EVENT_EXTENDED_ITEM_STACK_KEY32
    match_id : UInt64
    stack_key : UInt32
    padding : UInt32
  end
  struct EVENT_EXTENDED_ITEM_STACK_KEY64
    match_id : UInt64
    stack_key : UInt64
  end
  struct EVENT_EXTENDED_ITEM_PEBS_INDEX
    pebs_index : UInt64
  end
  struct EVENT_EXTENDED_ITEM_PMC_COUNTERS
    counter : UInt64[0]*
  end
  struct EVENT_EXTENDED_ITEM_PROCESS_START_KEY
    process_start_key : UInt64
  end
  struct EVENT_EXTENDED_ITEM_EVENT_KEY
    key : UInt64
  end
  struct EVENT_HEADER
    size : UInt16
    header_type : UInt16
    flags : UInt16
    event_property : UInt16
    thread_id : UInt32
    process_id : UInt32
    time_stamp : LARGE_INTEGER
    provider_id : Guid
    event_descriptor : EVENT_DESCRIPTOR
    anonymous : EVENT_HEADER_Anonymous_e__Union
    activity_id : Guid
  end
  struct EVENT_HEADER_Anonymous_e__Union_Anonymous_e__Struct
    kernel_time : UInt32
    user_time : UInt32
  end
  struct EVENT_RECORD
    event_header : EVENT_HEADER
    buffer_context : ETW_BUFFER_CONTEXT
    extended_data_count : UInt16
    user_data_length : UInt16
    extended_data : EVENT_HEADER_EXTENDED_DATA_ITEM*
    user_data : Void*
    user_context : Void*
  end
  struct EVENT_MAP_ENTRY
    output_offset : UInt32
    anonymous : EVENT_MAP_ENTRY_Anonymous_e__Union
  end
  struct EVENT_MAP_INFO
    name_offset : UInt32
    flag : MAP_FLAGS
    entry_count : UInt32
    anonymous : EVENT_MAP_INFO_Anonymous_e__Union
    map_entry_array : EVENT_MAP_ENTRY[0]*
  end
  struct EVENT_PROPERTY_INFO
    flags : PROPERTY_FLAGS
    name_offset : UInt32
    anonymous1 : EVENT_PROPERTY_INFO_Anonymous1_e__Union
    anonymous2 : EVENT_PROPERTY_INFO_Anonymous2_e__Union
    anonymous3 : EVENT_PROPERTY_INFO_Anonymous3_e__Union
    anonymous4 : EVENT_PROPERTY_INFO_Anonymous4_e__Union
  end
  struct EVENT_PROPERTY_INFO_Anonymous4_e__Union_Anonymous_e__Struct
    _bitfield : UInt32
  end
  struct EVENT_PROPERTY_INFO_Anonymous1_e__Union_customSchemaType
    in_type : UInt16
    out_type : UInt16
    custom_schema_offset : UInt32
  end
  struct EVENT_PROPERTY_INFO_Anonymous1_e__Union_nonStructType
    in_type : UInt16
    out_type : UInt16
    map_name_offset : UInt32
  end
  struct EVENT_PROPERTY_INFO_Anonymous1_e__Union_structType
    struct_start_index : UInt16
    num_of_struct_members : UInt16
    padding : UInt32
  end
  struct TRACE_EVENT_INFO
    provider_guid : Guid
    event_guid : Guid
    event_descriptor : EVENT_DESCRIPTOR
    decoding_source : DECODING_SOURCE
    provider_name_offset : UInt32
    level_name_offset : UInt32
    channel_name_offset : UInt32
    keywords_name_offset : UInt32
    task_name_offset : UInt32
    opcode_name_offset : UInt32
    event_message_offset : UInt32
    provider_message_offset : UInt32
    binary_xml_offset : UInt32
    binary_xml_size : UInt32
    anonymous1 : TRACE_EVENT_INFO_Anonymous1_e__Union
    anonymous2 : TRACE_EVENT_INFO_Anonymous2_e__Union
    property_count : UInt32
    top_level_property_count : UInt32
    anonymous3 : TRACE_EVENT_INFO_Anonymous3_e__Union
    event_property_info_array : EVENT_PROPERTY_INFO[0]*
  end
  struct TRACE_EVENT_INFO_Anonymous3_e__Union_Anonymous_e__Struct
    _bitfield : UInt32
  end
  struct PROPERTY_DATA_DESCRIPTOR
    property_name : UInt64
    array_index : UInt32
    reserved : UInt32
  end
  struct PAYLOAD_FILTER_PREDICATE
    field_name : LibC::LPWSTR
    compare_op : UInt16
    value : LibC::LPWSTR
  end
  struct PROVIDER_FILTER_INFO
    id : UInt8
    version : UInt8
    message_offset : UInt32
    reserved : UInt32
    property_count : UInt32
    event_property_info_array : EVENT_PROPERTY_INFO[0]*
  end
  struct PROVIDER_FIELD_INFO
    name_offset : UInt32
    description_offset : UInt32
    value : UInt64
  end
  struct PROVIDER_FIELD_INFOARRAY
    number_of_elements : UInt32
    field_type : EVENT_FIELD_TYPE
    field_info_array : PROVIDER_FIELD_INFO[0]*
  end
  struct TRACE_PROVIDER_INFO
    provider_guid : Guid
    schema_source : UInt32
    provider_name_offset : UInt32
  end
  struct PROVIDER_ENUMERATION_INFO
    number_of_providers : UInt32
    reserved : UInt32
    trace_provider_info_array : TRACE_PROVIDER_INFO[0]*
  end
  struct PROVIDER_EVENT_INFO
    number_of_events : UInt32
    reserved : UInt32
    event_descriptors_array : EVENT_DESCRIPTOR[0]*
  end
  struct TDH_CONTEXT
    parameter_value : UInt64
    parameter_type : TDH_CONTEXT_TYPE
    parameter_size : UInt32
  end


  struct ITraceEventVTbl
    query_interface : Proc(ITraceEvent*, Guid*, Void**, HRESULT)
    add_ref : Proc(ITraceEvent*, UInt32)
    release : Proc(ITraceEvent*, UInt32)
    clone : Proc(ITraceEvent*, ITraceEvent*, HRESULT)
    get_user_context : Proc(ITraceEvent*, Void**, HRESULT)
    get_event_record : Proc(ITraceEvent*, EVENT_RECORD**, HRESULT)
    set_payload : Proc(ITraceEvent*, UInt8*, UInt32, HRESULT)
    set_event_descriptor : Proc(ITraceEvent*, EVENT_DESCRIPTOR*, HRESULT)
    set_process_id : Proc(ITraceEvent*, UInt32, HRESULT)
    set_processor_index : Proc(ITraceEvent*, UInt32, HRESULT)
    set_thread_id : Proc(ITraceEvent*, UInt32, HRESULT)
    set_thread_times : Proc(ITraceEvent*, UInt32, UInt32, HRESULT)
    set_activity_id : Proc(ITraceEvent*, Guid*, HRESULT)
    set_time_stamp : Proc(ITraceEvent*, LARGE_INTEGER*, HRESULT)
    set_provider_id : Proc(ITraceEvent*, Guid*, HRESULT)
  end

  struct ITraceEvent
    lpVtbl : ITraceEventVTbl*
  end

  struct ITraceEventCallbackVTbl
    query_interface : Proc(ITraceEventCallback*, Guid*, Void**, HRESULT)
    add_ref : Proc(ITraceEventCallback*, UInt32)
    release : Proc(ITraceEventCallback*, UInt32)
    on_begin_process_trace : Proc(ITraceEventCallback*, ITraceEvent, ITraceRelogger, HRESULT)
    on_finalize_process_trace : Proc(ITraceEventCallback*, ITraceRelogger, HRESULT)
    on_event : Proc(ITraceEventCallback*, ITraceEvent, ITraceRelogger, HRESULT)
  end

  struct ITraceEventCallback
    lpVtbl : ITraceEventCallbackVTbl*
  end

  struct ITraceReloggerVTbl
    query_interface : Proc(ITraceRelogger*, Guid*, Void**, HRESULT)
    add_ref : Proc(ITraceRelogger*, UInt32)
    release : Proc(ITraceRelogger*, UInt32)
    add_logfile_trace_stream : Proc(ITraceRelogger*, UInt8, Void*, UInt64*, HRESULT)
    add_realtime_trace_stream : Proc(ITraceRelogger*, UInt8, Void*, UInt64*, HRESULT)
    register_callback : Proc(ITraceRelogger*, ITraceEventCallback, HRESULT)
    inject : Proc(ITraceRelogger*, ITraceEvent, HRESULT)
    create_event_instance : Proc(ITraceRelogger*, UInt64, UInt32, ITraceEvent*, HRESULT)
    process_trace : Proc(ITraceRelogger*, HRESULT)
    set_output_filename : Proc(ITraceRelogger*, UInt8, HRESULT)
    set_compression_mode : Proc(ITraceRelogger*, BOOLEAN, HRESULT)
    cancel : Proc(ITraceRelogger*, HRESULT)
  end

  struct ITraceRelogger
    lpVtbl : ITraceReloggerVTbl*
  end


  # Params # tracehandle : UInt64* [In],instancename : LibC::LPWSTR [In],properties : EVENT_TRACE_PROPERTIES* [In]
  fun StartTraceW(tracehandle : UInt64*, instancename : LibC::LPWSTR, properties : EVENT_TRACE_PROPERTIES*) : UInt32

  # Params # tracehandle : UInt64* [In],instancename : PSTR [In],properties : EVENT_TRACE_PROPERTIES* [In]
  fun StartTraceA(tracehandle : UInt64*, instancename : PSTR, properties : EVENT_TRACE_PROPERTIES*) : UInt32

  # Params # tracehandle : UInt64 [In],instancename : LibC::LPWSTR [In],properties : EVENT_TRACE_PROPERTIES* [In]
  fun StopTraceW(tracehandle : UInt64, instancename : LibC::LPWSTR, properties : EVENT_TRACE_PROPERTIES*) : UInt32

  # Params # tracehandle : UInt64 [In],instancename : PSTR [In],properties : EVENT_TRACE_PROPERTIES* [In]
  fun StopTraceA(tracehandle : UInt64, instancename : PSTR, properties : EVENT_TRACE_PROPERTIES*) : UInt32

  # Params # tracehandle : UInt64 [In],instancename : LibC::LPWSTR [In],properties : EVENT_TRACE_PROPERTIES* [In]
  fun QueryTraceW(tracehandle : UInt64, instancename : LibC::LPWSTR, properties : EVENT_TRACE_PROPERTIES*) : UInt32

  # Params # tracehandle : UInt64 [In],instancename : PSTR [In],properties : EVENT_TRACE_PROPERTIES* [In]
  fun QueryTraceA(tracehandle : UInt64, instancename : PSTR, properties : EVENT_TRACE_PROPERTIES*) : UInt32

  # Params # tracehandle : UInt64 [In],instancename : LibC::LPWSTR [In],properties : EVENT_TRACE_PROPERTIES* [In]
  fun UpdateTraceW(tracehandle : UInt64, instancename : LibC::LPWSTR, properties : EVENT_TRACE_PROPERTIES*) : UInt32

  # Params # tracehandle : UInt64 [In],instancename : PSTR [In],properties : EVENT_TRACE_PROPERTIES* [In]
  fun UpdateTraceA(tracehandle : UInt64, instancename : PSTR, properties : EVENT_TRACE_PROPERTIES*) : UInt32

  # Params # tracehandle : UInt64 [In],instancename : LibC::LPWSTR [In],properties : EVENT_TRACE_PROPERTIES* [In]
  fun FlushTraceW(tracehandle : UInt64, instancename : LibC::LPWSTR, properties : EVENT_TRACE_PROPERTIES*) : UInt32

  # Params # tracehandle : UInt64 [In],instancename : PSTR [In],properties : EVENT_TRACE_PROPERTIES* [In]
  fun FlushTraceA(tracehandle : UInt64, instancename : PSTR, properties : EVENT_TRACE_PROPERTIES*) : UInt32

  # Params # tracehandle : UInt64 [In],instancename : LibC::LPWSTR [In],properties : EVENT_TRACE_PROPERTIES* [In],controlcode : EVENT_TRACE_CONTROL [In]
  fun ControlTraceW(tracehandle : UInt64, instancename : LibC::LPWSTR, properties : EVENT_TRACE_PROPERTIES*, controlcode : EVENT_TRACE_CONTROL) : UInt32

  # Params # tracehandle : UInt64 [In],instancename : PSTR [In],properties : EVENT_TRACE_PROPERTIES* [In],controlcode : EVENT_TRACE_CONTROL [In]
  fun ControlTraceA(tracehandle : UInt64, instancename : PSTR, properties : EVENT_TRACE_PROPERTIES*, controlcode : EVENT_TRACE_CONTROL) : UInt32

  # Params # propertyarray : EVENT_TRACE_PROPERTIES** [In],propertyarraycount : UInt32 [In],loggercount : UInt32* [In]
  fun QueryAllTracesW(propertyarray : EVENT_TRACE_PROPERTIES**, propertyarraycount : UInt32, loggercount : UInt32*) : UInt32

  # Params # propertyarray : EVENT_TRACE_PROPERTIES** [In],propertyarraycount : UInt32 [In],loggercount : UInt32* [In]
  fun QueryAllTracesA(propertyarray : EVENT_TRACE_PROPERTIES**, propertyarraycount : UInt32, loggercount : UInt32*) : UInt32

  # Params # enable : UInt32 [In],enableflag : UInt32 [In],enablelevel : UInt32 [In],controlguid : Guid* [In],tracehandle : UInt64 [In]
  fun EnableTrace(enable : UInt32, enableflag : UInt32, enablelevel : UInt32, controlguid : Guid*, tracehandle : UInt64) : UInt32

  # Params # providerid : Guid* [In],sourceid : Guid* [In],tracehandle : UInt64 [In],isenabled : UInt32 [In],level : UInt8 [In],matchanykeyword : UInt64 [In],matchallkeyword : UInt64 [In],enableproperty : UInt32 [In],enablefilterdesc : EVENT_FILTER_DESCRIPTOR* [In]
  fun EnableTraceEx(providerid : Guid*, sourceid : Guid*, tracehandle : UInt64, isenabled : UInt32, level : UInt8, matchanykeyword : UInt64, matchallkeyword : UInt64, enableproperty : UInt32, enablefilterdesc : EVENT_FILTER_DESCRIPTOR*) : UInt32

  # Params # tracehandle : UInt64 [In],providerid : Guid* [In],controlcode : UInt32 [In],level : UInt8 [In],matchanykeyword : UInt64 [In],matchallkeyword : UInt64 [In],timeout : UInt32 [In],enableparameters : ENABLE_TRACE_PARAMETERS* [In]
  fun EnableTraceEx2(tracehandle : UInt64, providerid : Guid*, controlcode : UInt32, level : UInt8, matchanykeyword : UInt64, matchallkeyword : UInt64, timeout : UInt32, enableparameters : ENABLE_TRACE_PARAMETERS*) : UInt32

  # Params # tracequeryinfoclass : TRACE_QUERY_INFO_CLASS [In],inbuffer : Void* [In],inbuffersize : UInt32 [In],outbuffer : Void* [In],outbuffersize : UInt32 [In],returnlength : UInt32* [In]
  fun EnumerateTraceGuidsEx(tracequeryinfoclass : TRACE_QUERY_INFO_CLASS, inbuffer : Void*, inbuffersize : UInt32, outbuffer : Void*, outbuffersize : UInt32, returnlength : UInt32*) : UInt32

  # Params # sessionhandle : UInt64 [In],informationclass : TRACE_QUERY_INFO_CLASS [In],traceinformation : Void* [In],informationlength : UInt32 [In]
  fun TraceSetInformation(sessionhandle : UInt64, informationclass : TRACE_QUERY_INFO_CLASS, traceinformation : Void*, informationlength : UInt32) : UInt32

  # Params # sessionhandle : UInt64 [In],informationclass : TRACE_QUERY_INFO_CLASS [In],traceinformation : Void* [In],informationlength : UInt32 [In],returnlength : UInt32* [In]
  fun TraceQueryInformation(sessionhandle : UInt64, informationclass : TRACE_QUERY_INFO_CLASS, traceinformation : Void*, informationlength : UInt32, returnlength : UInt32*) : UInt32

  # Params # reghandle : LibC::HANDLE [In],instinfo : EVENT_INSTANCE_INFO* [In]
  fun CreateTraceInstanceId(reghandle : LibC::HANDLE, instinfo : EVENT_INSTANCE_INFO*) : UInt32

  # Params # tracehandle : UInt64 [In],eventtrace : EVENT_TRACE_HEADER* [In]
  fun TraceEvent(tracehandle : UInt64, eventtrace : EVENT_TRACE_HEADER*) : UInt32

  # Params # tracehandle : UInt64 [In],eventtrace : EVENT_INSTANCE_HEADER* [In],instinfo : EVENT_INSTANCE_INFO* [In],parentinstinfo : EVENT_INSTANCE_INFO* [In]
  fun TraceEventInstance(tracehandle : UInt64, eventtrace : EVENT_INSTANCE_HEADER*, instinfo : EVENT_INSTANCE_INFO*, parentinstinfo : EVENT_INSTANCE_INFO*) : UInt32

  # Params # requestaddress : WMIDPREQUEST [In],requestcontext : Void* [In],controlguid : Guid* [In],guidcount : UInt32 [In],traceguidreg : TRACE_GUID_REGISTRATION* [In],mofimagepath : LibC::LPWSTR [In],mofresourcename : LibC::LPWSTR [In],registrationhandle : UInt64* [In]
  fun RegisterTraceGuidsW(requestaddress : WMIDPREQUEST, requestcontext : Void*, controlguid : Guid*, guidcount : UInt32, traceguidreg : TRACE_GUID_REGISTRATION*, mofimagepath : LibC::LPWSTR, mofresourcename : LibC::LPWSTR, registrationhandle : UInt64*) : UInt32

  # Params # requestaddress : WMIDPREQUEST [In],requestcontext : Void* [In],controlguid : Guid* [In],guidcount : UInt32 [In],traceguidreg : TRACE_GUID_REGISTRATION* [In],mofimagepath : PSTR [In],mofresourcename : PSTR [In],registrationhandle : UInt64* [In]
  fun RegisterTraceGuidsA(requestaddress : WMIDPREQUEST, requestcontext : Void*, controlguid : Guid*, guidcount : UInt32, traceguidreg : TRACE_GUID_REGISTRATION*, mofimagepath : PSTR, mofresourcename : PSTR, registrationhandle : UInt64*) : UInt32

  # Params # guidpropertiesarray : TRACE_GUID_PROPERTIES** [In],propertyarraycount : UInt32 [In],guidcount : UInt32* [In]
  fun EnumerateTraceGuids(guidpropertiesarray : TRACE_GUID_PROPERTIES**, propertyarraycount : UInt32, guidcount : UInt32*) : UInt32

  # Params # registrationhandle : UInt64 [In]
  fun UnregisterTraceGuids(registrationhandle : UInt64) : UInt32

  # Params # buffer : Void* [In]
  fun GetTraceLoggerHandle(buffer : Void*) : UInt64

  # Params # tracehandle : UInt64 [In]
  fun GetTraceEnableLevel(tracehandle : UInt64) : UInt8

  # Params # tracehandle : UInt64 [In]
  fun GetTraceEnableFlags(tracehandle : UInt64) : UInt32

  # Params # logfile : EVENT_TRACE_LOGFILEW* [In]
  fun OpenTraceW(logfile : EVENT_TRACE_LOGFILEW*) : UInt64

  # Params # handlearray : UInt64* [In],handlecount : UInt32 [In],starttime : FILETIME* [In],endtime : FILETIME* [In]
  fun ProcessTrace(handlearray : UInt64*, handlecount : UInt32, starttime : FILETIME*, endtime : FILETIME*) : UInt32

  # Params # tracehandle : UInt64 [In]
  fun CloseTrace(tracehandle : UInt64) : UInt32

  # Params # processinghandle : UInt64 [In],informationclass : ETW_PROCESS_HANDLE_INFO_TYPE [In],inbuffer : Void* [In],inbuffersize : UInt32 [In],outbuffer : Void* [In],outbuffersize : UInt32 [In],returnlength : UInt32* [In]
  fun QueryTraceProcessingHandle(processinghandle : UInt64, informationclass : ETW_PROCESS_HANDLE_INFO_TYPE, inbuffer : Void*, inbuffersize : UInt32, outbuffer : Void*, outbuffersize : UInt32, returnlength : UInt32*) : UInt32

  # Params # logfile : EVENT_TRACE_LOGFILEA* [In]
  fun OpenTraceA(logfile : EVENT_TRACE_LOGFILEA*) : UInt64

  # Params # pguid : Guid* [In],eventcallback : PEVENT_CALLBACK [In]
  fun SetTraceCallback(pguid : Guid*, eventcallback : PEVENT_CALLBACK) : UInt32

  # Params # pguid : Guid* [In]
  fun RemoveTraceCallback(pguid : Guid*) : UInt32

  # Params # loggerhandle : UInt64 [In],messageflags : TRACE_MESSAGE_FLAGS [In],messageguid : Guid* [In],messagenumber : UInt16 [In]
  fun TraceMessage(loggerhandle : UInt64, messageflags : TRACE_MESSAGE_FLAGS, messageguid : Guid*, messagenumber : UInt16) : UInt32

  # Params # loggerhandle : UInt64 [In],messageflags : TRACE_MESSAGE_FLAGS [In],messageguid : Guid* [In],messagenumber : UInt16 [In],messagearglist : Int8* [In]
  fun TraceMessageVa(loggerhandle : UInt64, messageflags : TRACE_MESSAGE_FLAGS, messageguid : Guid*, messagenumber : UInt16, messagearglist : Int8*) : UInt32

  # Params # providerid : Guid* [In],enablecallback : PENABLECALLBACK [In],callbackcontext : Void* [In],reghandle : UInt64* [In]
  fun EventRegister(providerid : Guid*, enablecallback : PENABLECALLBACK, callbackcontext : Void*, reghandle : UInt64*) : UInt32

  # Params # reghandle : UInt64 [In]
  fun EventUnregister(reghandle : UInt64) : UInt32

  # Params # reghandle : UInt64 [In],informationclass : EVENT_INFO_CLASS [In],eventinformation : Void* [In],informationlength : UInt32 [In]
  fun EventSetInformation(reghandle : UInt64, informationclass : EVENT_INFO_CLASS, eventinformation : Void*, informationlength : UInt32) : UInt32

  # Params # reghandle : UInt64 [In],eventdescriptor : EVENT_DESCRIPTOR* [In]
  fun EventEnabled(reghandle : UInt64, eventdescriptor : EVENT_DESCRIPTOR*) : BOOLEAN

  # Params # reghandle : UInt64 [In],level : UInt8 [In],keyword : UInt64 [In]
  fun EventProviderEnabled(reghandle : UInt64, level : UInt8, keyword : UInt64) : BOOLEAN

  # Params # reghandle : UInt64 [In],eventdescriptor : EVENT_DESCRIPTOR* [In],userdatacount : UInt32 [In],userdata : EVENT_DATA_DESCRIPTOR* [In]
  fun EventWrite(reghandle : UInt64, eventdescriptor : EVENT_DESCRIPTOR*, userdatacount : UInt32, userdata : EVENT_DATA_DESCRIPTOR*) : UInt32

  # Params # reghandle : UInt64 [In],eventdescriptor : EVENT_DESCRIPTOR* [In],activityid : Guid* [In],relatedactivityid : Guid* [In],userdatacount : UInt32 [In],userdata : EVENT_DATA_DESCRIPTOR* [In]
  fun EventWriteTransfer(reghandle : UInt64, eventdescriptor : EVENT_DESCRIPTOR*, activityid : Guid*, relatedactivityid : Guid*, userdatacount : UInt32, userdata : EVENT_DATA_DESCRIPTOR*) : UInt32

  # Params # reghandle : UInt64 [In],eventdescriptor : EVENT_DESCRIPTOR* [In],filter : UInt64 [In],flags : UInt32 [In],activityid : Guid* [In],relatedactivityid : Guid* [In],userdatacount : UInt32 [In],userdata : EVENT_DATA_DESCRIPTOR* [In]
  fun EventWriteEx(reghandle : UInt64, eventdescriptor : EVENT_DESCRIPTOR*, filter : UInt64, flags : UInt32, activityid : Guid*, relatedactivityid : Guid*, userdatacount : UInt32, userdata : EVENT_DATA_DESCRIPTOR*) : UInt32

  # Params # reghandle : UInt64 [In],level : UInt8 [In],keyword : UInt64 [In],string : LibC::LPWSTR [In]
  fun EventWriteString(reghandle : UInt64, level : UInt8, keyword : UInt64, string : LibC::LPWSTR) : UInt32

  # Params # controlcode : UInt32 [In],activityid : Guid* [In]
  fun EventActivityIdControl(controlcode : UInt32, activityid : Guid*) : UInt32

  # Params # guid : Guid* [In],operation : UInt32 [In],sid : PSID [In],rights : UInt32 [In],allowordeny : BOOLEAN [In]
  fun EventAccessControl(guid : Guid*, operation : UInt32, sid : PSID, rights : UInt32, allowordeny : BOOLEAN) : UInt32

  # Params # guid : Guid* [In],buffer : SECURITY_DESCRIPTOR* [In],buffersize : UInt32* [In]
  fun EventAccessQuery(guid : Guid*, buffer : SECURITY_DESCRIPTOR*, buffersize : UInt32*) : UInt32

  # Params # guid : Guid* [In]
  fun EventAccessRemove(guid : Guid*) : UInt32

  # Params # providerguid : Guid* [In],eventdescriptor : EVENT_DESCRIPTOR* [In],eventmatchany : BOOLEAN [In],payloadpredicatecount : UInt32 [In],payloadpredicates : PAYLOAD_FILTER_PREDICATE* [In],payloadfilter : Void** [In]
  fun TdhCreatePayloadFilter(providerguid : Guid*, eventdescriptor : EVENT_DESCRIPTOR*, eventmatchany : BOOLEAN, payloadpredicatecount : UInt32, payloadpredicates : PAYLOAD_FILTER_PREDICATE*, payloadfilter : Void**) : UInt32

  # Params # payloadfilter : Void** [In]
  fun TdhDeletePayloadFilter(payloadfilter : Void**) : UInt32

  # Params # payloadfiltercount : UInt32 [In],payloadfilterptrs : Void** [In],eventmatchallflags : BOOLEAN* [In],eventfilterdescriptor : EVENT_FILTER_DESCRIPTOR* [In]
  fun TdhAggregatePayloadFilters(payloadfiltercount : UInt32, payloadfilterptrs : Void**, eventmatchallflags : BOOLEAN*, eventfilterdescriptor : EVENT_FILTER_DESCRIPTOR*) : UInt32

  # Params # eventfilterdescriptor : EVENT_FILTER_DESCRIPTOR* [In]
  fun TdhCleanupPayloadEventFilterDescriptor(eventfilterdescriptor : EVENT_FILTER_DESCRIPTOR*) : UInt32

  # Params # event : EVENT_RECORD* [In],tdhcontextcount : UInt32 [In],tdhcontext : TDH_CONTEXT* [In],buffer : TRACE_EVENT_INFO* [In],buffersize : UInt32* [In]
  fun TdhGetEventInformation(event : EVENT_RECORD*, tdhcontextcount : UInt32, tdhcontext : TDH_CONTEXT*, buffer : TRACE_EVENT_INFO*, buffersize : UInt32*) : UInt32

  # Params # pevent : EVENT_RECORD* [In],pmapname : LibC::LPWSTR [In],pbuffer : EVENT_MAP_INFO* [In],pbuffersize : UInt32* [In]
  fun TdhGetEventMapInformation(pevent : EVENT_RECORD*, pmapname : LibC::LPWSTR, pbuffer : EVENT_MAP_INFO*, pbuffersize : UInt32*) : UInt32

  # Params # pevent : EVENT_RECORD* [In],tdhcontextcount : UInt32 [In],ptdhcontext : TDH_CONTEXT* [In],propertydatacount : UInt32 [In],ppropertydata : PROPERTY_DATA_DESCRIPTOR* [In],ppropertysize : UInt32* [In]
  fun TdhGetPropertySize(pevent : EVENT_RECORD*, tdhcontextcount : UInt32, ptdhcontext : TDH_CONTEXT*, propertydatacount : UInt32, ppropertydata : PROPERTY_DATA_DESCRIPTOR*, ppropertysize : UInt32*) : UInt32

  # Params # pevent : EVENT_RECORD* [In],tdhcontextcount : UInt32 [In],ptdhcontext : TDH_CONTEXT* [In],propertydatacount : UInt32 [In],ppropertydata : PROPERTY_DATA_DESCRIPTOR* [In],buffersize : UInt32 [In],pbuffer : UInt8* [In]
  fun TdhGetProperty(pevent : EVENT_RECORD*, tdhcontextcount : UInt32, ptdhcontext : TDH_CONTEXT*, propertydatacount : UInt32, ppropertydata : PROPERTY_DATA_DESCRIPTOR*, buffersize : UInt32, pbuffer : UInt8*) : UInt32

  # Params # pbuffer : PROVIDER_ENUMERATION_INFO* [In],pbuffersize : UInt32* [In]
  fun TdhEnumerateProviders(pbuffer : PROVIDER_ENUMERATION_INFO*, pbuffersize : UInt32*) : UInt32

  # Params # filter : DECODING_SOURCE [In],buffer : PROVIDER_ENUMERATION_INFO* [In],buffersize : UInt32 [In],bufferrequired : UInt32* [In]
  fun TdhEnumerateProvidersForDecodingSource(filter : DECODING_SOURCE, buffer : PROVIDER_ENUMERATION_INFO*, buffersize : UInt32, bufferrequired : UInt32*) : UInt32

  # Params # pguid : Guid* [In],eventfieldvalue : UInt64 [In],eventfieldtype : EVENT_FIELD_TYPE [In],pbuffer : PROVIDER_FIELD_INFOARRAY* [In],pbuffersize : UInt32* [In]
  fun TdhQueryProviderFieldInformation(pguid : Guid*, eventfieldvalue : UInt64, eventfieldtype : EVENT_FIELD_TYPE, pbuffer : PROVIDER_FIELD_INFOARRAY*, pbuffersize : UInt32*) : UInt32

  # Params # pguid : Guid* [In],eventfieldtype : EVENT_FIELD_TYPE [In],pbuffer : PROVIDER_FIELD_INFOARRAY* [In],pbuffersize : UInt32* [In]
  fun TdhEnumerateProviderFieldInformation(pguid : Guid*, eventfieldtype : EVENT_FIELD_TYPE, pbuffer : PROVIDER_FIELD_INFOARRAY*, pbuffersize : UInt32*) : UInt32

  # Params # guid : Guid* [In],tdhcontextcount : UInt32 [In],tdhcontext : TDH_CONTEXT* [In],filtercount : UInt32* [In],buffer : PROVIDER_FILTER_INFO** [In],buffersize : UInt32* [In]
  fun TdhEnumerateProviderFilters(guid : Guid*, tdhcontextcount : UInt32, tdhcontext : TDH_CONTEXT*, filtercount : UInt32*, buffer : PROVIDER_FILTER_INFO**, buffersize : UInt32*) : UInt32

  # Params # manifest : LibC::LPWSTR [In]
  fun TdhLoadManifest(manifest : LibC::LPWSTR) : UInt32

  # Params # pdata : Void* [In],cbdata : UInt32 [In]
  fun TdhLoadManifestFromMemory(pdata : Void*, cbdata : UInt32) : UInt32

  # Params # manifest : LibC::LPWSTR [In]
  fun TdhUnloadManifest(manifest : LibC::LPWSTR) : UInt32

  # Params # pdata : Void* [In],cbdata : UInt32 [In]
  fun TdhUnloadManifestFromMemory(pdata : Void*, cbdata : UInt32) : UInt32

  # Params # eventinfo : TRACE_EVENT_INFO* [In],mapinfo : EVENT_MAP_INFO* [In],pointersize : UInt32 [In],propertyintype : UInt16 [In],propertyouttype : UInt16 [In],propertylength : UInt16 [In],userdatalength : UInt16 [In],userdata : UInt8* [In],buffersize : UInt32* [In],buffer : LibC::LPWSTR [In],userdataconsumed : UInt16* [In]
  fun TdhFormatProperty(eventinfo : TRACE_EVENT_INFO*, mapinfo : EVENT_MAP_INFO*, pointersize : UInt32, propertyintype : UInt16, propertyouttype : UInt16, propertylength : UInt16, userdatalength : UInt16, userdata : UInt8*, buffersize : UInt32*, buffer : LibC::LPWSTR, userdataconsumed : UInt16*) : UInt32

  # Params # handle : TDH_HANDLE* [In]
  fun TdhOpenDecodingHandle(handle : TDH_HANDLE*) : UInt32

  # Params # handle : TDH_HANDLE [In],tdhcontext : TDH_CONTEXT* [In]
  fun TdhSetDecodingParameter(handle : TDH_HANDLE, tdhcontext : TDH_CONTEXT*) : UInt32

  # Params # handle : TDH_HANDLE [In],tdhcontext : TDH_CONTEXT* [In]
  fun TdhGetDecodingParameter(handle : TDH_HANDLE, tdhcontext : TDH_CONTEXT*) : UInt32

  # Params # handle : TDH_HANDLE [In],eventrecord : EVENT_RECORD* [In],propertyname : LibC::LPWSTR [In],buffersize : UInt32* [In],buffer : UInt8* [In]
  fun TdhGetWppProperty(handle : TDH_HANDLE, eventrecord : EVENT_RECORD*, propertyname : LibC::LPWSTR, buffersize : UInt32*, buffer : UInt8*) : UInt32

  # Params # handle : TDH_HANDLE [In],eventrecord : EVENT_RECORD* [In],buffersize : UInt32* [In],buffer : UInt8* [In]
  fun TdhGetWppMessage(handle : TDH_HANDLE, eventrecord : EVENT_RECORD*, buffersize : UInt32*, buffer : UInt8*) : UInt32

  # Params # handle : TDH_HANDLE [In]
  fun TdhCloseDecodingHandle(handle : TDH_HANDLE) : UInt32

  # Params # binarypath : LibC::LPWSTR [In]
  fun TdhLoadManifestFromBinary(binarypath : LibC::LPWSTR) : UInt32

  # Params # providerguid : Guid* [In],buffer : PROVIDER_EVENT_INFO* [In],buffersize : UInt32* [In]
  fun TdhEnumerateManifestProviderEvents(providerguid : Guid*, buffer : PROVIDER_EVENT_INFO*, buffersize : UInt32*) : UInt32

  # Params # providerguid : Guid* [In],eventdescriptor : EVENT_DESCRIPTOR* [In],buffer : TRACE_EVENT_INFO* [In],buffersize : UInt32* [In]
  fun TdhGetManifestEventInformation(providerguid : Guid*, eventdescriptor : EVENT_DESCRIPTOR*, buffer : TRACE_EVENT_INFO*, buffersize : UInt32*) : UInt32

  # Params # cveid : LibC::LPWSTR [In],additionaldetails : LibC::LPWSTR [In]
  fun CveEventWrite(cveid : LibC::LPWSTR, additionaldetails : LibC::LPWSTR) : Int32
end
