name: Crystal CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ["self-hosted", "Windows"]
    steps:
    - name: crystal version
      shell: pwsh
      run: |
        & "$env:LOCALAPPDATA\Programs\Crystal\crystal.exe" version
    - uses: actions/checkout@v4
    - name: Create json directory
      shell: pwsh
      run: |
        mkdir json
    - uses: actions/checkout@v4
      with:
        repository: marlersoft/win32json
        path: json/win32json
    - name: Install dependencies
      shell: pwsh
      run: |
        & "$env:LOCALAPPDATA\Programs\Crystal\shards.exe" install
    - name: Cleanup src directory
      shell: pwsh
      run: |
        if (Test-Path -Path .\src\win32cr) { Remove-Item -Path src/win32cr -Force -Recurse }
    - name: WinMD version
      shell: cmd
      run: |
        bin\winmd.exe --version
    - name: Generate bindings
      shell: pwsh
      run: |
        & .\bin\winmd.exe generate -d json\win32json\api .
    - name: Run tests
      shell: pwsh
      run: |
        & "$env:LOCALAPPDATA\Programs\Crystal\crystal.exe" spec --error-trace --debug
