name: Crystal Latest CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install latest Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Crystal version
        run: crystal version

      - name: Install dependencies
        run: shards install --skip-postinstall

      - name: Generate bindings
        shell: pwsh
        run: ./build.ps1

      - name: WinMD version
        run: bin\winmd.exe --version

      - name: Run tests
        run: crystal spec --error-trace
