require "./../foundation.cr"
require "./win_sock.cr"

module Win32cr::Networking::WinHttp
  alias WINHTTP_STATUS_CALLBACK = Proc(Void*, LibC::UIntPtrT, UInt32, Void*, UInt32, Void)*

  WINHTTP_FLAG_ASYNC = 268435456_u32
  WINHTTP_FLAG_SECURE_DEFAULTS = 805306368_u32
  SECURITY_FLAG_IGNORE_UNKNOWN_CA = 256_u32
  SECURITY_FLAG_IGNORE_CERT_DATE_INVALID = 8192_u32
  SECURITY_FLAG_IGNORE_CERT_CN_INVALID = 4096_u32
  SECURITY_FLAG_IGNORE_CERT_WRONG_USAGE = 512_u32
  WINHTTP_AUTOPROXY_AUTO_DETECT = 1_u32
  WINHTTP_AUTOPROXY_CONFIG_URL = 2_u32
  WINHTTP_AUTOPROXY_HOST_KEEPCASE = 4_u32
  WINHTTP_AUTOPROXY_HOST_LOWERCASE = 8_u32
  WINHTTP_AUTOPROXY_ALLOW_AUTOCONFIG = 256_u32
  WINHTTP_AUTOPROXY_ALLOW_STATIC = 512_u32
  WINHTTP_AUTOPROXY_ALLOW_CM = 1024_u32
  WINHTTP_AUTOPROXY_RUN_INPROCESS = 65536_u32
  WINHTTP_AUTOPROXY_RUN_OUTPROCESS_ONLY = 131072_u32
  WINHTTP_AUTOPROXY_NO_DIRECTACCESS = 262144_u32
  WINHTTP_AUTOPROXY_NO_CACHE_CLIENT = 524288_u32
  WINHTTP_AUTOPROXY_NO_CACHE_SVC = 1048576_u32
  WINHTTP_AUTOPROXY_SORT_RESULTS = 4194304_u32
  WINHTTP_AUTO_DETECT_TYPE_DHCP = 1_u32
  WINHTTP_AUTO_DETECT_TYPE_DNS_A = 2_u32
  NETWORKING_KEY_BUFSIZE = 128_u32
  WINHTTP_PROXY_TYPE_DIRECT = 1_u32
  WINHTTP_PROXY_TYPE_PROXY = 2_u32
  WINHTTP_PROXY_TYPE_AUTO_PROXY_URL = 4_u32
  WINHTTP_PROXY_TYPE_AUTO_DETECT = 8_u32
  WINHTTP_REQUEST_STAT_FLAG_TCP_FAST_OPEN = 1_u32
  WINHTTP_REQUEST_STAT_FLAG_TLS_SESSION_RESUMPTION = 2_u32
  WINHTTP_REQUEST_STAT_FLAG_TLS_FALSE_START = 4_u32
  WINHTTP_REQUEST_STAT_FLAG_PROXY_TLS_SESSION_RESUMPTION = 8_u32
  WINHTTP_REQUEST_STAT_FLAG_PROXY_TLS_FALSE_START = 16_u32
  WINHTTP_REQUEST_STAT_FLAG_FIRST_REQUEST = 32_u32
  WINHTTP_MATCH_CONNECTION_GUID_FLAG_REQUIRE_MARKED_CONNECTION = 1_u32
  WINHTTP_MATCH_CONNECTION_GUID_FLAGS_MASK = 1_u32
  WINHTTP_RESOLVER_CACHE_CONFIG_FLAG_SOFT_LIMIT = 1_u32
  WINHTTP_RESOLVER_CACHE_CONFIG_FLAG_BYPASS_CACHE = 2_u32
  WINHTTP_RESOLVER_CACHE_CONFIG_FLAG_USE_DNS_TTL = 4_u32
  WINHTTP_RESOLVER_CACHE_CONFIG_FLAG_CONN_USE_TTL = 8_u32
  WINHTTP_TIME_FORMAT_BUFSIZE = 62_u32
  WINHTTP_OPTION_CALLBACK = 1_u32
  WINHTTP_OPTION_RESOLVE_TIMEOUT = 2_u32
  WINHTTP_OPTION_CONNECT_TIMEOUT = 3_u32
  WINHTTP_OPTION_CONNECT_RETRIES = 4_u32
  WINHTTP_OPTION_SEND_TIMEOUT = 5_u32
  WINHTTP_OPTION_RECEIVE_TIMEOUT = 6_u32
  WINHTTP_OPTION_RECEIVE_RESPONSE_TIMEOUT = 7_u32
  WINHTTP_OPTION_HANDLE_TYPE = 9_u32
  WINHTTP_OPTION_READ_BUFFER_SIZE = 12_u32
  WINHTTP_OPTION_WRITE_BUFFER_SIZE = 13_u32
  WINHTTP_OPTION_PARENT_HANDLE = 21_u32
  WINHTTP_OPTION_EXTENDED_ERROR = 24_u32
  WINHTTP_OPTION_SECURITY_FLAGS = 31_u32
  WINHTTP_OPTION_SECURITY_CERTIFICATE_STRUCT = 32_u32
  WINHTTP_OPTION_URL = 34_u32
  WINHTTP_OPTION_SECURITY_KEY_BITNESS = 36_u32
  WINHTTP_OPTION_PROXY = 38_u32
  WINHTTP_OPTION_PROXY_RESULT_ENTRY = 39_u32
  WINHTTP_OPTION_USER_AGENT = 41_u32
  WINHTTP_OPTION_CONTEXT_VALUE = 45_u32
  WINHTTP_OPTION_CLIENT_CERT_CONTEXT = 47_u32
  WINHTTP_OPTION_REQUEST_PRIORITY = 58_u32
  WINHTTP_OPTION_HTTP_VERSION = 59_u32
  WINHTTP_OPTION_DISABLE_FEATURE = 63_u32
  WINHTTP_OPTION_CODEPAGE = 68_u32
  WINHTTP_OPTION_MAX_CONNS_PER_SERVER = 73_u32
  WINHTTP_OPTION_MAX_CONNS_PER_1_0_SERVER = 74_u32
  WINHTTP_OPTION_AUTOLOGON_POLICY = 77_u32
  WINHTTP_OPTION_SERVER_CERT_CONTEXT = 78_u32
  WINHTTP_OPTION_ENABLE_FEATURE = 79_u32
  WINHTTP_OPTION_WORKER_THREAD_COUNT = 80_u32
  WINHTTP_OPTION_PASSPORT_COBRANDING_TEXT = 81_u32
  WINHTTP_OPTION_PASSPORT_COBRANDING_URL = 82_u32
  WINHTTP_OPTION_CONFIGURE_PASSPORT_AUTH = 83_u32
  WINHTTP_OPTION_SECURE_PROTOCOLS = 84_u32
  WINHTTP_OPTION_ENABLETRACING = 85_u32
  WINHTTP_OPTION_PASSPORT_SIGN_OUT = 86_u32
  WINHTTP_OPTION_PASSPORT_RETURN_URL = 87_u32
  WINHTTP_OPTION_REDIRECT_POLICY = 88_u32
  WINHTTP_OPTION_MAX_HTTP_AUTOMATIC_REDIRECTS = 89_u32
  WINHTTP_OPTION_MAX_HTTP_STATUS_CONTINUE = 90_u32
  WINHTTP_OPTION_MAX_RESPONSE_HEADER_SIZE = 91_u32
  WINHTTP_OPTION_MAX_RESPONSE_DRAIN_SIZE = 92_u32
  WINHTTP_OPTION_CONNECTION_INFO = 93_u32
  WINHTTP_OPTION_CLIENT_CERT_ISSUER_LIST = 94_u32
  WINHTTP_OPTION_SPN = 96_u32
  WINHTTP_OPTION_GLOBAL_PROXY_CREDS = 97_u32
  WINHTTP_OPTION_GLOBAL_SERVER_CREDS = 98_u32
  WINHTTP_OPTION_UNLOAD_NOTIFY_EVENT = 99_u32
  WINHTTP_OPTION_REJECT_USERPWD_IN_URL = 100_u32
  WINHTTP_OPTION_USE_GLOBAL_SERVER_CREDENTIALS = 101_u32
  WINHTTP_OPTION_RECEIVE_PROXY_CONNECT_RESPONSE = 103_u32
  WINHTTP_OPTION_IS_PROXY_CONNECT_RESPONSE = 104_u32
  WINHTTP_OPTION_SERVER_SPN_USED = 106_u32
  WINHTTP_OPTION_PROXY_SPN_USED = 107_u32
  WINHTTP_OPTION_SERVER_CBT = 108_u32
  WINHTTP_OPTION_UNSAFE_HEADER_PARSING = 110_u32
  WINHTTP_OPTION_ASSURED_NON_BLOCKING_CALLBACKS = 111_u32
  WINHTTP_OPTION_UPGRADE_TO_WEB_SOCKET = 114_u32
  WINHTTP_OPTION_WEB_SOCKET_CLOSE_TIMEOUT = 115_u32
  WINHTTP_OPTION_WEB_SOCKET_KEEPALIVE_INTERVAL = 116_u32
  WINHTTP_OPTION_DECOMPRESSION = 118_u32
  WINHTTP_OPTION_WEB_SOCKET_RECEIVE_BUFFER_SIZE = 122_u32
  WINHTTP_OPTION_WEB_SOCKET_SEND_BUFFER_SIZE = 123_u32
  WINHTTP_OPTION_TCP_PRIORITY_HINT = 128_u32
  WINHTTP_OPTION_CONNECTION_FILTER = 131_u32
  WINHTTP_OPTION_ENABLE_HTTP_PROTOCOL = 133_u32
  WINHTTP_OPTION_HTTP_PROTOCOL_USED = 134_u32
  WINHTTP_OPTION_KDC_PROXY_SETTINGS = 136_u32
  WINHTTP_OPTION_PROXY_DISABLE_SERVICE_CALLS = 137_u32
  WINHTTP_OPTION_ENCODE_EXTRA = 138_u32
  WINHTTP_OPTION_DISABLE_STREAM_QUEUE = 139_u32
  WINHTTP_OPTION_IPV6_FAST_FALLBACK = 140_u32
  WINHTTP_OPTION_CONNECTION_STATS_V0 = 141_u32
  WINHTTP_OPTION_REQUEST_TIMES = 142_u32
  WINHTTP_OPTION_EXPIRE_CONNECTION = 143_u32
  WINHTTP_OPTION_DISABLE_SECURE_PROTOCOL_FALLBACK = 144_u32
  WINHTTP_OPTION_HTTP_PROTOCOL_REQUIRED = 145_u32
  WINHTTP_OPTION_REQUEST_STATS = 146_u32
  WINHTTP_OPTION_SERVER_CERT_CHAIN_CONTEXT = 147_u32
  WINHTTP_OPTION_CONNECTION_STATS_V1 = 150_u32
  WINHTTP_OPTION_SECURITY_INFO = 151_u32
  WINHTTP_OPTION_TCP_KEEPALIVE = 152_u32
  WINHTTP_OPTION_TCP_FAST_OPEN = 153_u32
  WINHTTP_OPTION_TLS_FALSE_START = 154_u32
  WINHTTP_OPTION_IGNORE_CERT_REVOCATION_OFFLINE = 155_u32
  WINHTTP_OPTION_SOURCE_ADDRESS = 156_u32
  WINHTTP_OPTION_HEAP_EXTENSION = 157_u32
  WINHTTP_OPTION_TLS_PROTOCOL_INSECURE_FALLBACK = 158_u32
  WINHTTP_OPTION_STREAM_ERROR_CODE = 159_u32
  WINHTTP_OPTION_REQUIRE_STREAM_END = 160_u32
  WINHTTP_OPTION_ENABLE_HTTP2_PLUS_CLIENT_CERT = 161_u32
  WINHTTP_OPTION_FAILED_CONNECTION_RETRIES = 162_u32
  WINHTTP_OPTION_SET_GLOBAL_CALLBACK = 163_u32
  WINHTTP_OPTION_HTTP2_KEEPALIVE = 164_u32
  WINHTTP_OPTION_RESOLUTION_HOSTNAME = 165_u32
  WINHTTP_OPTION_SET_TOKEN_BINDING = 166_u32
  WINHTTP_OPTION_TOKEN_BINDING_PUBLIC_KEY = 167_u32
  WINHTTP_OPTION_REFERER_TOKEN_BINDING_HOSTNAME = 168_u32
  WINHTTP_OPTION_HTTP2_PLUS_TRANSFER_ENCODING = 169_u32
  WINHTTP_OPTION_RESOLVER_CACHE_CONFIG = 170_u32
  WINHTTP_OPTION_DISABLE_CERT_CHAIN_BUILDING = 171_u32
  WINHTTP_OPTION_BACKGROUND_CONNECTIONS = 172_u32
  WINHTTP_OPTION_FIRST_AVAILABLE_CONNECTION = 173_u32
  WINHTTP_OPTION_ENABLE_TEST_SIGNING = 174_u32
  WINHTTP_OPTION_NTSERVICE_FLAG_TEST = 175_u32
  WINHTTP_OPTION_DISABLE_PROXY_LINK_LOCAL_NAME_RESOLUTION = 176_u32
  WINHTTP_OPTION_TCP_PRIORITY_STATUS = 177_u32
  WINHTTP_OPTION_CONNECTION_GUID = 178_u32
  WINHTTP_OPTION_MATCH_CONNECTION_GUID = 179_u32
  WINHTTP_OPTION_PROXY_CONFIG_INFO = 180_u32
  WINHTTP_OPTION_AGGREGATE_PROXY_CONFIG = 181_u32
  WINHTTP_OPTION_SELECTED_PROXY_CONFIG_INFO = 182_u32
  WINHTTP_OPTION_HTTP2_RECEIVE_WINDOW = 183_u32
  WINHTTP_LAST_OPTION = 183_u32
  WINHTTP_OPTION_USERNAME = 4096_u32
  WINHTTP_OPTION_PASSWORD = 4097_u32
  WINHTTP_OPTION_PROXY_USERNAME = 4098_u32
  WINHTTP_OPTION_PROXY_PASSWORD = 4099_u32
  WINHTTP_CONNS_PER_SERVER_UNLIMITED = 4294967295_u32
  WINHTTP_CONNECTION_RETRY_CONDITION_408 = 1_u32
  WINHTTP_CONNECTION_RETRY_CONDITION_SSL_HANDSHAKE = 2_u32
  WINHTTP_CONNECTION_RETRY_CONDITION_STALE_CONNECTION = 4_u32
  WINHTTP_DECOMPRESSION_FLAG_GZIP = 1_u32
  WINHTTP_DECOMPRESSION_FLAG_DEFLATE = 2_u32
  WINHTTP_PROTOCOL_FLAG_HTTP2 = 1_u32
  WINHTTP_PROTOCOL_FLAG_HTTP3 = 2_u32
  WINHTTP_AUTOLOGON_SECURITY_LEVEL_MEDIUM = 0_u32
  WINHTTP_AUTOLOGON_SECURITY_LEVEL_LOW = 1_u32
  WINHTTP_AUTOLOGON_SECURITY_LEVEL_HIGH = 2_u32
  WINHTTP_AUTOLOGON_SECURITY_LEVEL_DEFAULT = 0_u32
  WINHTTP_OPTION_REDIRECT_POLICY_NEVER = 0_u32
  WINHTTP_OPTION_REDIRECT_POLICY_DISALLOW_HTTPS_TO_HTTP = 1_u32
  WINHTTP_OPTION_REDIRECT_POLICY_ALWAYS = 2_u32
  WINHTTP_OPTION_REDIRECT_POLICY_LAST = 2_u32
  WINHTTP_OPTION_REDIRECT_POLICY_DEFAULT = 1_u32
  WINHTTP_DISABLE_PASSPORT_AUTH = 0_u32
  WINHTTP_ENABLE_PASSPORT_AUTH = 268435456_u32
  WINHTTP_DISABLE_PASSPORT_KEYRING = 536870912_u32
  WINHTTP_ENABLE_PASSPORT_KEYRING = 1073741824_u32
  WINHTTP_DISABLE_COOKIES = 1_u32
  WINHTTP_DISABLE_REDIRECTS = 2_u32
  WINHTTP_DISABLE_AUTHENTICATION = 4_u32
  WINHTTP_DISABLE_KEEP_ALIVE = 8_u32
  WINHTTP_ENABLE_SSL_REVOCATION = 1_u32
  WINHTTP_ENABLE_SSL_REVERT_IMPERSONATION = 2_u32
  WINHTTP_DISABLE_SPN_SERVER_PORT = 0_u32
  WINHTTP_ENABLE_SPN_SERVER_PORT = 1_u32
  WINHTTP_OPTION_SPN_MASK = 1_u32
  WINHTTP_HANDLE_TYPE_SESSION = 1_u32
  WINHTTP_HANDLE_TYPE_CONNECT = 2_u32
  WINHTTP_HANDLE_TYPE_REQUEST = 3_u32
  WINHTTP_AUTH_SCHEME_PASSPORT = 4_u32
  WINHTTP_AUTH_SCHEME_DIGEST = 8_u32
  WINHTTP_AUTH_TARGET_SERVER = 0_u32
  WINHTTP_AUTH_TARGET_PROXY = 1_u32
  SECURITY_FLAG_SECURE = 1_u32
  SECURITY_FLAG_STRENGTH_WEAK = 268435456_u32
  SECURITY_FLAG_STRENGTH_MEDIUM = 1073741824_u32
  SECURITY_FLAG_STRENGTH_STRONG = 536870912_u32
  WINHTTP_CALLBACK_STATUS_FLAG_CERT_REV_FAILED = 1_u32
  WINHTTP_CALLBACK_STATUS_FLAG_INVALID_CERT = 2_u32
  WINHTTP_CALLBACK_STATUS_FLAG_CERT_REVOKED = 4_u32
  WINHTTP_CALLBACK_STATUS_FLAG_INVALID_CA = 8_u32
  WINHTTP_CALLBACK_STATUS_FLAG_CERT_CN_INVALID = 16_u32
  WINHTTP_CALLBACK_STATUS_FLAG_CERT_DATE_INVALID = 32_u32
  WINHTTP_CALLBACK_STATUS_FLAG_CERT_WRONG_USAGE = 64_u32
  WINHTTP_CALLBACK_STATUS_FLAG_SECURITY_CHANNEL_ERROR = 2147483648_u32
  WINHTTP_FLAG_SECURE_PROTOCOL_SSL2 = 8_u32
  WINHTTP_FLAG_SECURE_PROTOCOL_SSL3 = 32_u32
  WINHTTP_FLAG_SECURE_PROTOCOL_TLS1 = 128_u32
  WINHTTP_FLAG_SECURE_PROTOCOL_TLS1_1 = 512_u32
  WINHTTP_FLAG_SECURE_PROTOCOL_TLS1_2 = 2048_u32
  WINHTTP_FLAG_SECURE_PROTOCOL_TLS1_3 = 8192_u32
  WINHTTP_CALLBACK_STATUS_RESOLVING_NAME = 1_u32
  WINHTTP_CALLBACK_STATUS_NAME_RESOLVED = 2_u32
  WINHTTP_CALLBACK_STATUS_CONNECTING_TO_SERVER = 4_u32
  WINHTTP_CALLBACK_STATUS_CONNECTED_TO_SERVER = 8_u32
  WINHTTP_CALLBACK_STATUS_SENDING_REQUEST = 16_u32
  WINHTTP_CALLBACK_STATUS_REQUEST_SENT = 32_u32
  WINHTTP_CALLBACK_STATUS_RECEIVING_RESPONSE = 64_u32
  WINHTTP_CALLBACK_STATUS_RESPONSE_RECEIVED = 128_u32
  WINHTTP_CALLBACK_STATUS_CLOSING_CONNECTION = 256_u32
  WINHTTP_CALLBACK_STATUS_CONNECTION_CLOSED = 512_u32
  WINHTTP_CALLBACK_STATUS_HANDLE_CREATED = 1024_u32
  WINHTTP_CALLBACK_STATUS_HANDLE_CLOSING = 2048_u32
  WINHTTP_CALLBACK_STATUS_DETECTING_PROXY = 4096_u32
  WINHTTP_CALLBACK_STATUS_REDIRECT = 16384_u32
  WINHTTP_CALLBACK_STATUS_INTERMEDIATE_RESPONSE = 32768_u32
  WINHTTP_CALLBACK_STATUS_SECURE_FAILURE = 65536_u32
  WINHTTP_CALLBACK_STATUS_HEADERS_AVAILABLE = 131072_u32
  WINHTTP_CALLBACK_STATUS_DATA_AVAILABLE = 262144_u32
  WINHTTP_CALLBACK_STATUS_READ_COMPLETE = 524288_u32
  WINHTTP_CALLBACK_STATUS_WRITE_COMPLETE = 1048576_u32
  WINHTTP_CALLBACK_STATUS_REQUEST_ERROR = 2097152_u32
  WINHTTP_CALLBACK_STATUS_SENDREQUEST_COMPLETE = 4194304_u32
  WINHTTP_CALLBACK_STATUS_GETPROXYFORURL_COMPLETE = 16777216_u32
  WINHTTP_CALLBACK_STATUS_CLOSE_COMPLETE = 33554432_u32
  WINHTTP_CALLBACK_STATUS_SHUTDOWN_COMPLETE = 67108864_u32
  WINHTTP_CALLBACK_STATUS_SETTINGS_WRITE_COMPLETE = 268435456_u32
  WINHTTP_CALLBACK_STATUS_SETTINGS_READ_COMPLETE = 536870912_u32
  API_RECEIVE_RESPONSE = 1_u32
  API_QUERY_DATA_AVAILABLE = 2_u32
  API_READ_DATA = 3_u32
  API_WRITE_DATA = 4_u32
  API_SEND_REQUEST = 5_u32
  API_GET_PROXY_FOR_URL = 6_u32
  WINHTTP_CALLBACK_FLAG_DETECTING_PROXY = 4096_u32
  WINHTTP_CALLBACK_FLAG_REDIRECT = 16384_u32
  WINHTTP_CALLBACK_FLAG_INTERMEDIATE_RESPONSE = 32768_u32
  WINHTTP_CALLBACK_FLAG_SECURE_FAILURE = 65536_u32
  WINHTTP_CALLBACK_FLAG_SENDREQUEST_COMPLETE = 4194304_u32
  WINHTTP_CALLBACK_FLAG_HEADERS_AVAILABLE = 131072_u32
  WINHTTP_CALLBACK_FLAG_DATA_AVAILABLE = 262144_u32
  WINHTTP_CALLBACK_FLAG_READ_COMPLETE = 524288_u32
  WINHTTP_CALLBACK_FLAG_WRITE_COMPLETE = 1048576_u32
  WINHTTP_CALLBACK_FLAG_REQUEST_ERROR = 2097152_u32
  WINHTTP_CALLBACK_FLAG_GETPROXYFORURL_COMPLETE = 16777216_u32
  WINHTTP_CALLBACK_FLAG_ALL_NOTIFICATIONS = 4294967295_u32
  WINHTTP_QUERY_MIME_VERSION = 0_u32
  WINHTTP_QUERY_CONTENT_TYPE = 1_u32
  WINHTTP_QUERY_CONTENT_TRANSFER_ENCODING = 2_u32
  WINHTTP_QUERY_CONTENT_ID = 3_u32
  WINHTTP_QUERY_CONTENT_DESCRIPTION = 4_u32
  WINHTTP_QUERY_CONTENT_LENGTH = 5_u32
  WINHTTP_QUERY_CONTENT_LANGUAGE = 6_u32
  WINHTTP_QUERY_ALLOW = 7_u32
  WINHTTP_QUERY_PUBLIC = 8_u32
  WINHTTP_QUERY_DATE = 9_u32
  WINHTTP_QUERY_EXPIRES = 10_u32
  WINHTTP_QUERY_LAST_MODIFIED = 11_u32
  WINHTTP_QUERY_MESSAGE_ID = 12_u32
  WINHTTP_QUERY_URI = 13_u32
  WINHTTP_QUERY_DERIVED_FROM = 14_u32
  WINHTTP_QUERY_COST = 15_u32
  WINHTTP_QUERY_LINK = 16_u32
  WINHTTP_QUERY_PRAGMA = 17_u32
  WINHTTP_QUERY_VERSION = 18_u32
  WINHTTP_QUERY_STATUS_CODE = 19_u32
  WINHTTP_QUERY_STATUS_TEXT = 20_u32
  WINHTTP_QUERY_RAW_HEADERS = 21_u32
  WINHTTP_QUERY_RAW_HEADERS_CRLF = 22_u32
  WINHTTP_QUERY_CONNECTION = 23_u32
  WINHTTP_QUERY_ACCEPT = 24_u32
  WINHTTP_QUERY_ACCEPT_CHARSET = 25_u32
  WINHTTP_QUERY_ACCEPT_ENCODING = 26_u32
  WINHTTP_QUERY_ACCEPT_LANGUAGE = 27_u32
  WINHTTP_QUERY_AUTHORIZATION = 28_u32
  WINHTTP_QUERY_CONTENT_ENCODING = 29_u32
  WINHTTP_QUERY_FORWARDED = 30_u32
  WINHTTP_QUERY_FROM = 31_u32
  WINHTTP_QUERY_IF_MODIFIED_SINCE = 32_u32
  WINHTTP_QUERY_LOCATION = 33_u32
  WINHTTP_QUERY_ORIG_URI = 34_u32
  WINHTTP_QUERY_REFERER = 35_u32
  WINHTTP_QUERY_RETRY_AFTER = 36_u32
  WINHTTP_QUERY_SERVER = 37_u32
  WINHTTP_QUERY_TITLE = 38_u32
  WINHTTP_QUERY_USER_AGENT = 39_u32
  WINHTTP_QUERY_WWW_AUTHENTICATE = 40_u32
  WINHTTP_QUERY_PROXY_AUTHENTICATE = 41_u32
  WINHTTP_QUERY_ACCEPT_RANGES = 42_u32
  WINHTTP_QUERY_SET_COOKIE = 43_u32
  WINHTTP_QUERY_COOKIE = 44_u32
  WINHTTP_QUERY_REQUEST_METHOD = 45_u32
  WINHTTP_QUERY_REFRESH = 46_u32
  WINHTTP_QUERY_CONTENT_DISPOSITION = 47_u32
  WINHTTP_QUERY_AGE = 48_u32
  WINHTTP_QUERY_CACHE_CONTROL = 49_u32
  WINHTTP_QUERY_CONTENT_BASE = 50_u32
  WINHTTP_QUERY_CONTENT_LOCATION = 51_u32
  WINHTTP_QUERY_CONTENT_MD5 = 52_u32
  WINHTTP_QUERY_CONTENT_RANGE = 53_u32
  WINHTTP_QUERY_ETAG = 54_u32
  WINHTTP_QUERY_HOST = 55_u32
  WINHTTP_QUERY_IF_MATCH = 56_u32
  WINHTTP_QUERY_IF_NONE_MATCH = 57_u32
  WINHTTP_QUERY_IF_RANGE = 58_u32
  WINHTTP_QUERY_IF_UNMODIFIED_SINCE = 59_u32
  WINHTTP_QUERY_MAX_FORWARDS = 60_u32
  WINHTTP_QUERY_PROXY_AUTHORIZATION = 61_u32
  WINHTTP_QUERY_RANGE = 62_u32
  WINHTTP_QUERY_TRANSFER_ENCODING = 63_u32
  WINHTTP_QUERY_UPGRADE = 64_u32
  WINHTTP_QUERY_VARY = 65_u32
  WINHTTP_QUERY_VIA = 66_u32
  WINHTTP_QUERY_WARNING = 67_u32
  WINHTTP_QUERY_EXPECT = 68_u32
  WINHTTP_QUERY_PROXY_CONNECTION = 69_u32
  WINHTTP_QUERY_UNLESS_MODIFIED_SINCE = 70_u32
  WINHTTP_QUERY_PROXY_SUPPORT = 75_u32
  WINHTTP_QUERY_AUTHENTICATION_INFO = 76_u32
  WINHTTP_QUERY_PASSPORT_URLS = 77_u32
  WINHTTP_QUERY_PASSPORT_CONFIG = 78_u32
  WINHTTP_QUERY_MAX = 78_u32
  WINHTTP_QUERY_EX_ALL_HEADERS = 21_u32
  WINHTTP_QUERY_CUSTOM = 65535_u32
  WINHTTP_QUERY_FLAG_REQUEST_HEADERS = 2147483648_u32
  WINHTTP_QUERY_FLAG_SYSTEMTIME = 1073741824_u32
  WINHTTP_QUERY_FLAG_NUMBER = 536870912_u32
  WINHTTP_QUERY_FLAG_NUMBER64 = 134217728_u32
  WINHTTP_QUERY_FLAG_TRAILERS = 33554432_u32
  WINHTTP_QUERY_FLAG_WIRE_ENCODING = 16777216_u32
  HTTP_STATUS_CONTINUE = 100_u32
  HTTP_STATUS_SWITCH_PROTOCOLS = 101_u32
  HTTP_STATUS_OK = 200_u32
  HTTP_STATUS_CREATED = 201_u32
  HTTP_STATUS_ACCEPTED = 202_u32
  HTTP_STATUS_PARTIAL = 203_u32
  HTTP_STATUS_NO_CONTENT = 204_u32
  HTTP_STATUS_RESET_CONTENT = 205_u32
  HTTP_STATUS_PARTIAL_CONTENT = 206_u32
  HTTP_STATUS_WEBDAV_MULTI_STATUS = 207_u32
  HTTP_STATUS_AMBIGUOUS = 300_u32
  HTTP_STATUS_MOVED = 301_u32
  HTTP_STATUS_REDIRECT = 302_u32
  HTTP_STATUS_REDIRECT_METHOD = 303_u32
  HTTP_STATUS_NOT_MODIFIED = 304_u32
  HTTP_STATUS_USE_PROXY = 305_u32
  HTTP_STATUS_REDIRECT_KEEP_VERB = 307_u32
  HTTP_STATUS_PERMANENT_REDIRECT = 308_u32
  HTTP_STATUS_BAD_REQUEST = 400_u32
  HTTP_STATUS_DENIED = 401_u32
  HTTP_STATUS_PAYMENT_REQ = 402_u32
  HTTP_STATUS_FORBIDDEN = 403_u32
  HTTP_STATUS_NOT_FOUND = 404_u32
  HTTP_STATUS_BAD_METHOD = 405_u32
  HTTP_STATUS_NONE_ACCEPTABLE = 406_u32
  HTTP_STATUS_PROXY_AUTH_REQ = 407_u32
  HTTP_STATUS_REQUEST_TIMEOUT = 408_u32
  HTTP_STATUS_CONFLICT = 409_u32
  HTTP_STATUS_GONE = 410_u32
  HTTP_STATUS_LENGTH_REQUIRED = 411_u32
  HTTP_STATUS_PRECOND_FAILED = 412_u32
  HTTP_STATUS_REQUEST_TOO_LARGE = 413_u32
  HTTP_STATUS_URI_TOO_LONG = 414_u32
  HTTP_STATUS_UNSUPPORTED_MEDIA = 415_u32
  HTTP_STATUS_RETRY_WITH = 449_u32
  HTTP_STATUS_SERVER_ERROR = 500_u32
  HTTP_STATUS_NOT_SUPPORTED = 501_u32
  HTTP_STATUS_BAD_GATEWAY = 502_u32
  HTTP_STATUS_SERVICE_UNAVAIL = 503_u32
  HTTP_STATUS_GATEWAY_TIMEOUT = 504_u32
  HTTP_STATUS_VERSION_NOT_SUP = 505_u32
  HTTP_STATUS_FIRST = 100_u32
  HTTP_STATUS_LAST = 505_u32
  ICU_NO_ENCODE = 536870912_u32
  ICU_NO_META = 134217728_u32
  ICU_ENCODE_SPACES_ONLY = 67108864_u32
  ICU_BROWSER_MODE = 33554432_u32
  ICU_ENCODE_PERCENT = 4096_u32
  ICU_ESCAPE_AUTHORITY = 8192_u32
  WINHTTP_ADDREQ_INDEX_MASK = 65535_u32
  WINHTTP_ADDREQ_FLAGS_MASK = 4294901760_u32
  WINHTTP_ADDREQ_FLAG_ADD_IF_NEW = 268435456_u32
  WINHTTP_ADDREQ_FLAG_ADD = 536870912_u32
  WINHTTP_ADDREQ_FLAG_COALESCE_WITH_COMMA = 1073741824_u32
  WINHTTP_ADDREQ_FLAG_COALESCE_WITH_SEMICOLON = 16777216_u32
  WINHTTP_ADDREQ_FLAG_COALESCE = 1073741824_u32
  WINHTTP_ADDREQ_FLAG_REPLACE = 2147483648_u32
  WINHTTP_EXTENDED_HEADER_FLAG_UNICODE = 1_u32
  WINHTTP_IGNORE_REQUEST_TOTAL_LENGTH = 0_u32
  WINHTTP_ERROR_BASE = 12000_u32
  ERROR_WINHTTP_OUT_OF_HANDLES = 12001_u32
  ERROR_WINHTTP_TIMEOUT = 12002_u32
  ERROR_WINHTTP_INTERNAL_ERROR = 12004_u32
  ERROR_WINHTTP_INVALID_URL = 12005_u32
  ERROR_WINHTTP_UNRECOGNIZED_SCHEME = 12006_u32
  ERROR_WINHTTP_NAME_NOT_RESOLVED = 12007_u32
  ERROR_WINHTTP_INVALID_OPTION = 12009_u32
  ERROR_WINHTTP_OPTION_NOT_SETTABLE = 12011_u32
  ERROR_WINHTTP_SHUTDOWN = 12012_u32
  ERROR_WINHTTP_LOGIN_FAILURE = 12015_u32
  ERROR_WINHTTP_OPERATION_CANCELLED = 12017_u32
  ERROR_WINHTTP_INCORRECT_HANDLE_TYPE = 12018_u32
  ERROR_WINHTTP_INCORRECT_HANDLE_STATE = 12019_u32
  ERROR_WINHTTP_CANNOT_CONNECT = 12029_u32
  ERROR_WINHTTP_CONNECTION_ERROR = 12030_u32
  ERROR_WINHTTP_RESEND_REQUEST = 12032_u32
  ERROR_WINHTTP_CLIENT_AUTH_CERT_NEEDED = 12044_u32
  ERROR_WINHTTP_CANNOT_CALL_BEFORE_OPEN = 12100_u32
  ERROR_WINHTTP_CANNOT_CALL_BEFORE_SEND = 12101_u32
  ERROR_WINHTTP_CANNOT_CALL_AFTER_SEND = 12102_u32
  ERROR_WINHTTP_CANNOT_CALL_AFTER_OPEN = 12103_u32
  ERROR_WINHTTP_HEADER_NOT_FOUND = 12150_u32
  ERROR_WINHTTP_INVALID_SERVER_RESPONSE = 12152_u32
  ERROR_WINHTTP_INVALID_HEADER = 12153_u32
  ERROR_WINHTTP_INVALID_QUERY_REQUEST = 12154_u32
  ERROR_WINHTTP_HEADER_ALREADY_EXISTS = 12155_u32
  ERROR_WINHTTP_REDIRECT_FAILED = 12156_u32
  ERROR_WINHTTP_AUTO_PROXY_SERVICE_ERROR = 12178_u32
  ERROR_WINHTTP_BAD_AUTO_PROXY_SCRIPT = 12166_u32
  ERROR_WINHTTP_UNABLE_TO_DOWNLOAD_SCRIPT = 12167_u32
  ERROR_WINHTTP_UNHANDLED_SCRIPT_TYPE = 12176_u32
  ERROR_WINHTTP_SCRIPT_EXECUTION_ERROR = 12177_u32
  ERROR_WINHTTP_NOT_INITIALIZED = 12172_u32
  ERROR_WINHTTP_SECURE_FAILURE = 12175_u32
  ERROR_WINHTTP_SECURE_CERT_DATE_INVALID = 12037_u32
  ERROR_WINHTTP_SECURE_CERT_CN_INVALID = 12038_u32
  ERROR_WINHTTP_SECURE_INVALID_CA = 12045_u32
  ERROR_WINHTTP_SECURE_CERT_REV_FAILED = 12057_u32
  ERROR_WINHTTP_SECURE_CHANNEL_ERROR = 12157_u32
  ERROR_WINHTTP_SECURE_INVALID_CERT = 12169_u32
  ERROR_WINHTTP_SECURE_CERT_REVOKED = 12170_u32
  ERROR_WINHTTP_SECURE_CERT_WRONG_USAGE = 12179_u32
  ERROR_WINHTTP_AUTODETECTION_FAILED = 12180_u32
  ERROR_WINHTTP_HEADER_COUNT_EXCEEDED = 12181_u32
  ERROR_WINHTTP_HEADER_SIZE_OVERFLOW = 12182_u32
  ERROR_WINHTTP_CHUNKED_ENCODING_HEADER_SIZE_OVERFLOW = 12183_u32
  ERROR_WINHTTP_RESPONSE_DRAIN_OVERFLOW = 12184_u32
  ERROR_WINHTTP_CLIENT_CERT_NO_PRIVATE_KEY = 12185_u32
  ERROR_WINHTTP_CLIENT_CERT_NO_ACCESS_PRIVATE_KEY = 12186_u32
  ERROR_WINHTTP_CLIENT_AUTH_CERT_NEEDED_PROXY = 12187_u32
  ERROR_WINHTTP_SECURE_FAILURE_PROXY = 12188_u32
  ERROR_WINHTTP_RESERVED_189 = 12189_u32
  ERROR_WINHTTP_HTTP_PROTOCOL_MISMATCH = 12190_u32
  ERROR_WINHTTP_GLOBAL_CALLBACK_FAILED = 12191_u32
  ERROR_WINHTTP_FEATURE_DISABLED = 12192_u32
  WINHTTP_ERROR_LAST = 12192_u32
  WINHTTP_RESET_STATE = 1_u32
  WINHTTP_RESET_SWPAD_CURRENT_NETWORK = 2_u32
  WINHTTP_RESET_SWPAD_ALL = 4_u32
  WINHTTP_RESET_SCRIPT_CACHE = 8_u32
  WINHTTP_RESET_ALL = 65535_u32
  WINHTTP_RESET_NOTIFY_NETWORK_CHANGED = 65536_u32
  WINHTTP_RESET_OUT_OF_PROC = 131072_u32
  WINHTTP_RESET_DISCARD_RESOLVERS = 262144_u32
  WINHTTP_WEB_SOCKET_MAX_CLOSE_REASON_LENGTH = 123_u32
  WINHTTP_WEB_SOCKET_MIN_KEEPALIVE_VALUE = 15000_u32

  enum INTERNET_PORT : UInt32
    INTERNET_DEFAULT_HTTP_PORT = 80_u32
    INTERNET_DEFAULT_HTTPS_PORT = 443_u32
    INTERNET_DEFAULT_PORT = 0_u32
  end
  @[Flags]
  enum WINHTTP_OPEN_REQUEST_FLAGS : UInt32
    WINHTTP_FLAG_BYPASS_PROXY_CACHE = 256_u32
    WINHTTP_FLAG_ESCAPE_DISABLE = 64_u32
    WINHTTP_FLAG_ESCAPE_DISABLE_QUERY = 128_u32
    WINHTTP_FLAG_ESCAPE_PERCENT = 4_u32
    WINHTTP_FLAG_NULL_CODEPAGE = 8_u32
    WINHTTP_FLAG_REFRESH = 256_u32
    WINHTTP_FLAG_SECURE = 8388608_u32
  end
  enum WIN_HTTP_CREATE_URL_FLAGS : UInt32
    ICU_ESCAPE = 2147483648_u32
    ICU_REJECT_USERPWD = 16384_u32
    ICU_DECODE = 268435456_u32
  end
  enum WINHTTP_ACCESS_TYPE : UInt32
    WINHTTP_ACCESS_TYPE_NO_PROXY = 1_u32
    WINHTTP_ACCESS_TYPE_DEFAULT_PROXY = 0_u32
    WINHTTP_ACCESS_TYPE_NAMED_PROXY = 3_u32
    WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY = 4_u32
  end
  enum WINHTTP_CREDS_AUTHSCHEME : UInt32
    WINHTTP_AUTH_SCHEME_BASIC = 1_u32
    WINHTTP_AUTH_SCHEME_NTLM = 2_u32
    WINHTTP_AUTH_SCHEME_NEGOTIATE = 16_u32
  end
  enum WINHTTP_INTERNET_SCHEME : UInt32
    WINHTTP_INTERNET_SCHEME_HTTP = 1_u32
    WINHTTP_INTERNET_SCHEME_HTTPS = 2_u32
    WINHTTP_INTERNET_SCHEME_FTP = 3_u32
    WINHTTP_INTERNET_SCHEME_SOCKS = 4_u32
  end
  enum WINHTTP_REQUEST_TIME_ENTRY
    WinHttpProxyDetectionStart = 0_i32
    WinHttpProxyDetectionEnd = 1_i32
    WinHttpConnectionAcquireStart = 2_i32
    WinHttpConnectionAcquireWaitEnd = 3_i32
    WinHttpConnectionAcquireEnd = 4_i32
    WinHttpNameResolutionStart = 5_i32
    WinHttpNameResolutionEnd = 6_i32
    WinHttpConnectionEstablishmentStart = 7_i32
    WinHttpConnectionEstablishmentEnd = 8_i32
    WinHttpTlsHandshakeClientLeg1Start = 9_i32
    WinHttpTlsHandshakeClientLeg1End = 10_i32
    WinHttpTlsHandshakeClientLeg2Start = 11_i32
    WinHttpTlsHandshakeClientLeg2End = 12_i32
    WinHttpTlsHandshakeClientLeg3Start = 13_i32
    WinHttpTlsHandshakeClientLeg3End = 14_i32
    WinHttpStreamWaitStart = 15_i32
    WinHttpStreamWaitEnd = 16_i32
    WinHttpSendRequestStart = 17_i32
    WinHttpSendRequestHeadersCompressionStart = 18_i32
    WinHttpSendRequestHeadersCompressionEnd = 19_i32
    WinHttpSendRequestHeadersEnd = 20_i32
    WinHttpSendRequestEnd = 21_i32
    WinHttpReceiveResponseStart = 22_i32
    WinHttpReceiveResponseHeadersDecompressionStart = 23_i32
    WinHttpReceiveResponseHeadersDecompressionEnd = 24_i32
    WinHttpReceiveResponseHeadersEnd = 25_i32
    WinHttpReceiveResponseBodyDecompressionDelta = 26_i32
    WinHttpReceiveResponseEnd = 27_i32
    WinHttpProxyTunnelStart = 28_i32
    WinHttpProxyTunnelEnd = 29_i32
    WinHttpProxyTlsHandshakeClientLeg1Start = 30_i32
    WinHttpProxyTlsHandshakeClientLeg1End = 31_i32
    WinHttpProxyTlsHandshakeClientLeg2Start = 32_i32
    WinHttpProxyTlsHandshakeClientLeg2End = 33_i32
    WinHttpProxyTlsHandshakeClientLeg3Start = 34_i32
    WinHttpProxyTlsHandshakeClientLeg3End = 35_i32
    WinHttpRequestTimeLast = 36_i32
    WinHttpRequestTimeMax = 64_i32
  end
  enum WINHTTP_REQUEST_STAT_ENTRY
    WinHttpConnectFailureCount = 0_i32
    WinHttpProxyFailureCount = 1_i32
    WinHttpTlsHandshakeClientLeg1Size = 2_i32
    WinHttpTlsHandshakeServerLeg1Size = 3_i32
    WinHttpTlsHandshakeClientLeg2Size = 4_i32
    WinHttpTlsHandshakeServerLeg2Size = 5_i32
    WinHttpRequestHeadersSize = 6_i32
    WinHttpRequestHeadersCompressedSize = 7_i32
    WinHttpResponseHeadersSize = 8_i32
    WinHttpResponseHeadersCompressedSize = 9_i32
    WinHttpResponseBodySize = 10_i32
    WinHttpResponseBodyCompressedSize = 11_i32
    WinHttpProxyTlsHandshakeClientLeg1Size = 12_i32
    WinHttpProxyTlsHandshakeServerLeg1Size = 13_i32
    WinHttpProxyTlsHandshakeClientLeg2Size = 14_i32
    WinHttpProxyTlsHandshakeServerLeg2Size = 15_i32
    WinHttpRequestStatLast = 16_i32
    WinHttpRequestStatMax = 32_i32
  end
  enum WINHTTP_SECURE_DNS_SETTING
    WinHttpSecureDnsSettingDefault = 0_i32
    WinHttpSecureDnsSettingForcePlaintext = 1_i32
    WinHttpSecureDnsSettingRequireEncryption = 2_i32
    WinHttpSecureDnsSettingTryEncryptionWithFallback = 3_i32
    WinHttpSecureDnsSettingMax = 4_i32
  end
  enum WINHTTP_WEB_SOCKET_OPERATION
    WINHTTP_WEB_SOCKET_SEND_OPERATION = 0_i32
    WINHTTP_WEB_SOCKET_RECEIVE_OPERATION = 1_i32
    WINHTTP_WEB_SOCKET_CLOSE_OPERATION = 2_i32
    WINHTTP_WEB_SOCKET_SHUTDOWN_OPERATION = 3_i32
  end
  enum WINHTTP_WEB_SOCKET_BUFFER_TYPE
    WINHTTP_WEB_SOCKET_BINARY_MESSAGE_BUFFER_TYPE = 0_i32
    WINHTTP_WEB_SOCKET_BINARY_FRAGMENT_BUFFER_TYPE = 1_i32
    WINHTTP_WEB_SOCKET_UTF8_MESSAGE_BUFFER_TYPE = 2_i32
    WINHTTP_WEB_SOCKET_UTF8_FRAGMENT_BUFFER_TYPE = 3_i32
    WINHTTP_WEB_SOCKET_CLOSE_BUFFER_TYPE = 4_i32
  end
  enum WINHTTP_WEB_SOCKET_CLOSE_STATUS
    WINHTTP_WEB_SOCKET_SUCCESS_CLOSE_STATUS = 1000_i32
    WINHTTP_WEB_SOCKET_ENDPOINT_TERMINATED_CLOSE_STATUS = 1001_i32
    WINHTTP_WEB_SOCKET_PROTOCOL_ERROR_CLOSE_STATUS = 1002_i32
    WINHTTP_WEB_SOCKET_INVALID_DATA_TYPE_CLOSE_STATUS = 1003_i32
    WINHTTP_WEB_SOCKET_EMPTY_CLOSE_STATUS = 1005_i32
    WINHTTP_WEB_SOCKET_ABORTED_CLOSE_STATUS = 1006_i32
    WINHTTP_WEB_SOCKET_INVALID_PAYLOAD_CLOSE_STATUS = 1007_i32
    WINHTTP_WEB_SOCKET_POLICY_VIOLATION_CLOSE_STATUS = 1008_i32
    WINHTTP_WEB_SOCKET_MESSAGE_TOO_BIG_CLOSE_STATUS = 1009_i32
    WINHTTP_WEB_SOCKET_UNSUPPORTED_EXTENSIONS_CLOSE_STATUS = 1010_i32
    WINHTTP_WEB_SOCKET_SERVER_ERROR_CLOSE_STATUS = 1011_i32
    WINHTTP_WEB_SOCKET_SECURE_HANDSHAKE_ERROR_CLOSE_STATUS = 1015_i32
  end

  @[Extern]
  record WINHTTP_ASYNC_RESULT,
    dwResult : LibC::UIntPtrT,
    dwError : UInt32

  @[Extern]
  record HTTP_VERSION_INFO,
    dwMajorVersion : UInt32,
    dwMinorVersion : UInt32

  @[Extern]
  record URL_COMPONENTS,
    dwStructSize : UInt32,
    lpszScheme : Win32cr::Foundation::PWSTR,
    dwSchemeLength : UInt32,
    nScheme : Win32cr::Networking::WinHttp::WINHTTP_INTERNET_SCHEME,
    lpszHostName : Win32cr::Foundation::PWSTR,
    dwHostNameLength : UInt32,
    nPort : UInt16,
    lpszUserName : Win32cr::Foundation::PWSTR,
    dwUserNameLength : UInt32,
    lpszPassword : Win32cr::Foundation::PWSTR,
    dwPasswordLength : UInt32,
    lpszUrlPath : Win32cr::Foundation::PWSTR,
    dwUrlPathLength : UInt32,
    lpszExtraInfo : Win32cr::Foundation::PWSTR,
    dwExtraInfoLength : UInt32

  @[Extern]
  record WINHTTP_PROXY_INFO,
    dwAccessType : Win32cr::Networking::WinHttp::WINHTTP_ACCESS_TYPE,
    lpszProxy : Win32cr::Foundation::PWSTR,
    lpszProxyBypass : Win32cr::Foundation::PWSTR

  @[Extern]
  record WINHTTP_AUTOPROXY_OPTIONS,
    dwFlags : UInt32,
    dwAutoDetectFlags : UInt32,
    lpszAutoConfigUrl : Win32cr::Foundation::PWSTR,
    lpvReserved : Void*,
    dwReserved : UInt32,
    fAutoLogonIfChallenged : Win32cr::Foundation::BOOL

  @[Extern]
  record WINHTTP_PROXY_RESULT_ENTRY,
    fProxy : Win32cr::Foundation::BOOL,
    fBypass : Win32cr::Foundation::BOOL,
    proxy_scheme : Win32cr::Networking::WinHttp::WINHTTP_INTERNET_SCHEME,
    pwszProxy : Win32cr::Foundation::PWSTR,
    proxy_port : UInt16

  @[Extern]
  record WINHTTP_PROXY_RESULT,
    cEntries : UInt32,
    pEntries : Win32cr::Networking::WinHttp::WINHTTP_PROXY_RESULT_ENTRY*

  @[Extern]
  record WINHTTP_PROXY_RESULT_EX,
    cEntries : UInt32,
    pEntries : Win32cr::Networking::WinHttp::WINHTTP_PROXY_RESULT_ENTRY*,
    hProxyDetectionHandle : Win32cr::Foundation::HANDLE,
    dwProxyInterfaceAffinity : UInt32

  @[Extern]
  record WinHttpProxyNetworkKey_,
    pbBuffer : UInt8[128]

  @[Extern]
  record WINHTTP_PROXY_SETTINGS,
    dwStructSize : UInt32,
    dwFlags : UInt32,
    dwCurrentSettingsVersion : UInt32,
    pwszConnectionName : Win32cr::Foundation::PWSTR,
    pwszProxy : Win32cr::Foundation::PWSTR,
    pwszProxyBypass : Win32cr::Foundation::PWSTR,
    pwszAutoconfigUrl : Win32cr::Foundation::PWSTR,
    pwszAutoconfigSecondaryUrl : Win32cr::Foundation::PWSTR,
    dwAutoDiscoveryFlags : UInt32,
    pwszLastKnownGoodAutoConfigUrl : Win32cr::Foundation::PWSTR,
    dwAutoconfigReloadDelayMins : UInt32,
    ftLastKnownDetectTime : Win32cr::Foundation::FILETIME,
    dwDetectedInterfaceIpCount : UInt32,
    pdwDetectedInterfaceIp : UInt32*,
    cNetworkKeys : UInt32,
    pNetworkKeys : Win32cr::Networking::WinHttp::WinHttpProxyNetworkKey_*

  @[Extern]
  record WINHTTP_CERTIFICATE_INFO,
    ftExpiry : Win32cr::Foundation::FILETIME,
    ftStart : Win32cr::Foundation::FILETIME,
    lpszSubjectInfo : Win32cr::Foundation::PWSTR,
    lpszIssuerInfo : Win32cr::Foundation::PWSTR,
    lpszProtocolName : Win32cr::Foundation::PWSTR,
    lpszSignatureAlgName : Win32cr::Foundation::PWSTR,
    lpszEncryptionAlgName : Win32cr::Foundation::PWSTR,
    dwKeySize : UInt32

  {% if flag?(:x86_64) || flag?(:arm) %}
  @[Extern]
  record WINHTTP_CONNECTION_INFO,
    cbSize : UInt32,
    local_address : Win32cr::Networking::WinSock::SOCKADDR_STORAGE,
    remote_address : Win32cr::Networking::WinSock::SOCKADDR_STORAGE
  {% end %}

  {% if flag?(:x86_64) || flag?(:arm) %}
  @[Extern]
  record WINHTTP_REQUEST_TIMES,
    cTimes : UInt32,
    rgullTimes : UInt64[64]
  {% end %}

  {% if flag?(:x86_64) || flag?(:arm) %}
  @[Extern]
  record WINHTTP_REQUEST_STATS,
    ullFlags : UInt64,
    ulIndex : UInt32,
    cStats : UInt32,
    rgullStats : UInt64[32]
  {% end %}

  {% if flag?(:x86_64) || flag?(:arm) %}
  @[Extern]
  record WINHTTP_MATCH_CONNECTION_GUID,
    connection_guid : LibC::GUID,
    ullFlags : UInt64
  {% end %}

  @[Extern]
  record WINHTTP_EXTENDED_HEADER,
    anonymous1 : Anonymous1_e__Union_,
    anonymous2 : Anonymous2_e__Union_ do

    # Nested Type Anonymous1_e__Union_
    @[Extern(union: true)]
    record Anonymous1_e__Union_,
      pwszName : Win32cr::Foundation::PWSTR,
      pszName : Win32cr::Foundation::PSTR


    # Nested Type Anonymous2_e__Union_
    @[Extern(union: true)]
    record Anonymous2_e__Union_,
      pwszValue : Win32cr::Foundation::PWSTR,
      pszValue : Win32cr::Foundation::PSTR

  end

  @[Extern(union: true)]
  record WINHTTP_HEADER_NAME,
    pwszName : Win32cr::Foundation::PWSTR,
    pszName : Win32cr::Foundation::PSTR

  {% if flag?(:x86_64) || flag?(:arm) %}
  @[Extern]
  record WINHTTP_RESOLVER_CACHE_CONFIG,
    ulMaxResolverCacheEntries : UInt32,
    ulMaxCacheEntryAge : UInt32,
    ulMinCacheEntryTtl : UInt32,
    secure_dns_setting : Win32cr::Networking::WinHttp::WINHTTP_SECURE_DNS_SETTING,
    ullConnResolutionWaitTime : UInt64,
    ullFlags : UInt64
  {% end %}

  @[Extern]
  record WINHTTP_CONNECTION_GROUP,
    cConnections : UInt32,
    guidGroup : LibC::GUID

  @[Extern]
  record WINHTTP_HOST_CONNECTION_GROUP,
    pwszHost : Win32cr::Foundation::PWSTR,
    cConnectionGroups : UInt32,
    pConnectionGroups : Win32cr::Networking::WinHttp::WINHTTP_CONNECTION_GROUP*

  @[Extern]
  record WINHTTP_QUERY_CONNECTION_GROUP_RESULT,
    cHosts : UInt32,
    pHostConnectionGroups : Win32cr::Networking::WinHttp::WINHTTP_HOST_CONNECTION_GROUP*

  @[Extern]
  record WINHTTP_HTTP2_RECEIVE_WINDOW,
    ulStreamWindow : UInt32,
    ulStreamWindowUpdateDelta : UInt32

  @[Extern]
  record WINHTTP_FAILED_CONNECTION_RETRIES,
    dwMaxRetries : UInt32,
    dwAllowedRetryConditions : UInt32

  @[Extern]
  record WINHTTP_CREDS,
    lpszUserName : Win32cr::Foundation::PSTR,
    lpszPassword : Win32cr::Foundation::PSTR,
    lpszRealm : Win32cr::Foundation::PSTR,
    dwAuthScheme : Win32cr::Networking::WinHttp::WINHTTP_CREDS_AUTHSCHEME,
    lpszHostName : Win32cr::Foundation::PSTR,
    dwPort : UInt32

  @[Extern]
  record WINHTTP_CREDS_EX,
    lpszUserName : Win32cr::Foundation::PSTR,
    lpszPassword : Win32cr::Foundation::PSTR,
    lpszRealm : Win32cr::Foundation::PSTR,
    dwAuthScheme : Win32cr::Networking::WinHttp::WINHTTP_CREDS_AUTHSCHEME,
    lpszHostName : Win32cr::Foundation::PSTR,
    dwPort : UInt32,
    lpszUrl : Win32cr::Foundation::PSTR

  @[Extern]
  record WINHTTP_CURRENT_USER_IE_PROXY_CONFIG,
    fAutoDetect : Win32cr::Foundation::BOOL,
    lpszAutoConfigUrl : Win32cr::Foundation::PWSTR,
    lpszProxy : Win32cr::Foundation::PWSTR,
    lpszProxyBypass : Win32cr::Foundation::PWSTR

  @[Extern]
  record WINHTTP_WEB_SOCKET_ASYNC_RESULT,
    async_result : Win32cr::Networking::WinHttp::WINHTTP_ASYNC_RESULT,
    operation : Win32cr::Networking::WinHttp::WINHTTP_WEB_SOCKET_OPERATION

  @[Extern]
  record WINHTTP_WEB_SOCKET_STATUS,
    dwBytesTransferred : UInt32,
    eBufferType : Win32cr::Networking::WinHttp::WINHTTP_WEB_SOCKET_BUFFER_TYPE

  {% if flag?(:i386) %}
  @[Extern]
  record WINHTTP_CONNECTION_INFO,
    cbSize : UInt32,
    local_address : Win32cr::Networking::WinSock::SOCKADDR_STORAGE,
    remote_address : Win32cr::Networking::WinSock::SOCKADDR_STORAGE
  {% end %}

  {% if flag?(:i386) %}
  @[Extern]
  record WINHTTP_REQUEST_TIMES,
    cTimes : UInt32,
    rgullTimes : UInt64[64]
  {% end %}

  {% if flag?(:i386) %}
  @[Extern]
  record WINHTTP_REQUEST_STATS,
    ullFlags : UInt64,
    ulIndex : UInt32,
    cStats : UInt32,
    rgullStats : UInt64[32]
  {% end %}

  {% if flag?(:i386) %}
  @[Extern]
  record WINHTTP_MATCH_CONNECTION_GUID,
    connection_guid : LibC::GUID,
    ullFlags : UInt64
  {% end %}

  {% if flag?(:i386) %}
  @[Extern]
  record WINHTTP_RESOLVER_CACHE_CONFIG,
    ulMaxResolverCacheEntries : UInt32,
    ulMaxCacheEntryAge : UInt32,
    ulMinCacheEntryTtl : UInt32,
    secure_dns_setting : Win32cr::Networking::WinHttp::WINHTTP_SECURE_DNS_SETTING,
    ullConnResolutionWaitTime : UInt64,
    ullFlags : UInt64
  {% end %}

  @[Link("winhttp")]
  lib C
    fun WinHttpSetStatusCallback(hInternet : Void*, lpfnInternetCallback : Win32cr::Networking::WinHttp::WINHTTP_STATUS_CALLBACK, dwNotificationFlags : UInt32, dwReserved : LibC::UIntPtrT) : Win32cr::Networking::WinHttp::WINHTTP_STATUS_CALLBACK

    fun WinHttpTimeFromSystemTime(pst : Win32cr::Foundation::SYSTEMTIME*, pwszTime : UInt16*) : Win32cr::Foundation::BOOL

    fun WinHttpTimeToSystemTime(pwszTime : Win32cr::Foundation::PWSTR, pst : Win32cr::Foundation::SYSTEMTIME*) : Win32cr::Foundation::BOOL

    fun WinHttpCrackUrl(pwszUrl : UInt16*, dwUrlLength : UInt32, dwFlags : UInt32, lpUrlComponents : Win32cr::Networking::WinHttp::URL_COMPONENTS*) : Win32cr::Foundation::BOOL

    fun WinHttpCreateUrl(lpUrlComponents : Win32cr::Networking::WinHttp::URL_COMPONENTS*, dwFlags : Win32cr::Networking::WinHttp::WIN_HTTP_CREATE_URL_FLAGS, pwszUrl : UInt16*, pdwUrlLength : UInt32*) : Win32cr::Foundation::BOOL

    fun WinHttpCheckPlatform : Win32cr::Foundation::BOOL

    fun WinHttpGetDefaultProxyConfiguration(pProxyInfo : Win32cr::Networking::WinHttp::WINHTTP_PROXY_INFO*) : Win32cr::Foundation::BOOL

    fun WinHttpSetDefaultProxyConfiguration(pProxyInfo : Win32cr::Networking::WinHttp::WINHTTP_PROXY_INFO*) : Win32cr::Foundation::BOOL

    fun WinHttpOpen(pszAgentW : Win32cr::Foundation::PWSTR, dwAccessType : Win32cr::Networking::WinHttp::WINHTTP_ACCESS_TYPE, pszProxyW : Win32cr::Foundation::PWSTR, pszProxyBypassW : Win32cr::Foundation::PWSTR, dwFlags : UInt32) : Void*

    fun WinHttpCloseHandle(hInternet : Void*) : Win32cr::Foundation::BOOL

    fun WinHttpConnect(hSession : Void*, pswzServerName : Win32cr::Foundation::PWSTR, nServerPort : Win32cr::Networking::WinHttp::INTERNET_PORT, dwReserved : UInt32) : Void*

    fun WinHttpReadData(hRequest : Void*, lpBuffer : Void*, dwNumberOfBytesToRead : UInt32, lpdwNumberOfBytesRead : UInt32*) : Win32cr::Foundation::BOOL

    fun WinHttpReadDataEx(hRequest : Void*, lpBuffer : Void*, dwNumberOfBytesToRead : UInt32, lpdwNumberOfBytesRead : UInt32*, ullFlags : UInt64, cbProperty : UInt32, pvProperty : Void*) : UInt32

    fun WinHttpWriteData(hRequest : Void*, lpBuffer : Void*, dwNumberOfBytesToWrite : UInt32, lpdwNumberOfBytesWritten : UInt32*) : Win32cr::Foundation::BOOL

    fun WinHttpQueryDataAvailable(hRequest : Void*, lpdwNumberOfBytesAvailable : UInt32*) : Win32cr::Foundation::BOOL

    fun WinHttpQueryOption(hInternet : Void*, dwOption : UInt32, lpBuffer : Void*, lpdwBufferLength : UInt32*) : Win32cr::Foundation::BOOL

    fun WinHttpSetOption(hInternet : Void*, dwOption : UInt32, lpBuffer : Void*, dwBufferLength : UInt32) : Win32cr::Foundation::BOOL

    fun WinHttpSetTimeouts(hInternet : Void*, nResolveTimeout : Int32, nConnectTimeout : Int32, nSendTimeout : Int32, nReceiveTimeout : Int32) : Win32cr::Foundation::BOOL

    fun WinHttpOpenRequest(hConnect : Void*, pwszVerb : Win32cr::Foundation::PWSTR, pwszObjectName : Win32cr::Foundation::PWSTR, pwszVersion : Win32cr::Foundation::PWSTR, pwszReferrer : Win32cr::Foundation::PWSTR, ppwszAcceptTypes : Win32cr::Foundation::PWSTR*, dwFlags : Win32cr::Networking::WinHttp::WINHTTP_OPEN_REQUEST_FLAGS) : Void*

    fun WinHttpAddRequestHeaders(hRequest : Void*, lpszHeaders : UInt16*, dwHeadersLength : UInt32, dwModifiers : UInt32) : Win32cr::Foundation::BOOL

    fun WinHttpAddRequestHeadersEx(hRequest : Void*, dwModifiers : UInt32, ullFlags : UInt64, ullExtra : UInt64, cHeaders : UInt32, pHeaders : Win32cr::Networking::WinHttp::WINHTTP_EXTENDED_HEADER*) : UInt32

    fun WinHttpSendRequest(hRequest : Void*, lpszHeaders : UInt16*, dwHeadersLength : UInt32, lpOptional : Void*, dwOptionalLength : UInt32, dwTotalLength : UInt32, dwContext : LibC::UIntPtrT) : Win32cr::Foundation::BOOL

    fun WinHttpSetCredentials(hRequest : Void*, auth_targets : UInt32, auth_scheme : UInt32, pwszUserName : Win32cr::Foundation::PWSTR, pwszPassword : Win32cr::Foundation::PWSTR, pAuthParams : Void*) : Win32cr::Foundation::BOOL

    fun WinHttpQueryAuthSchemes(hRequest : Void*, lpdwSupportedSchemes : UInt32*, lpdwFirstScheme : UInt32*, pdwAuthTarget : UInt32*) : Win32cr::Foundation::BOOL

    fun WinHttpReceiveResponse(hRequest : Void*, lpReserved : Void*) : Win32cr::Foundation::BOOL

    fun WinHttpQueryHeaders(hRequest : Void*, dwInfoLevel : UInt32, pwszName : Win32cr::Foundation::PWSTR, lpBuffer : Void*, lpdwBufferLength : UInt32*, lpdwIndex : UInt32*) : Win32cr::Foundation::BOOL

    fun WinHttpQueryHeadersEx(hRequest : Void*, dwInfoLevel : UInt32, ullFlags : UInt64, uiCodePage : UInt32, pdwIndex : UInt32*, pHeaderName : Win32cr::Networking::WinHttp::WINHTTP_HEADER_NAME*, pBuffer : Void*, pdwBufferLength : UInt32*, ppHeaders : Win32cr::Networking::WinHttp::WINHTTP_EXTENDED_HEADER**, pdwHeadersCount : UInt32*) : UInt32

    fun WinHttpQueryConnectionGroup(hInternet : Void*, pGuidConnection : LibC::GUID*, ullFlags : UInt64, ppResult : Win32cr::Networking::WinHttp::WINHTTP_QUERY_CONNECTION_GROUP_RESULT**) : UInt32

    fun WinHttpFreeQueryConnectionGroupResult(pResult : Win32cr::Networking::WinHttp::WINHTTP_QUERY_CONNECTION_GROUP_RESULT*) : Void

    fun WinHttpDetectAutoProxyConfigUrl(dwAutoDetectFlags : UInt32, ppwstrAutoConfigUrl : Win32cr::Foundation::PWSTR*) : Win32cr::Foundation::BOOL

    fun WinHttpGetProxyForUrl(hSession : Void*, lpcwszUrl : Win32cr::Foundation::PWSTR, pAutoProxyOptions : Win32cr::Networking::WinHttp::WINHTTP_AUTOPROXY_OPTIONS*, pProxyInfo : Win32cr::Networking::WinHttp::WINHTTP_PROXY_INFO*) : Win32cr::Foundation::BOOL

    fun WinHttpCreateProxyResolver(hSession : Void*, phResolver : Void**) : UInt32

    fun WinHttpGetProxyForUrlEx(hResolver : Void*, pcwszUrl : Win32cr::Foundation::PWSTR, pAutoProxyOptions : Win32cr::Networking::WinHttp::WINHTTP_AUTOPROXY_OPTIONS*, pContext : LibC::UIntPtrT) : UInt32

    fun WinHttpGetProxyForUrlEx2(hResolver : Void*, pcwszUrl : Win32cr::Foundation::PWSTR, pAutoProxyOptions : Win32cr::Networking::WinHttp::WINHTTP_AUTOPROXY_OPTIONS*, cbInterfaceSelectionContext : UInt32, pInterfaceSelectionContext : UInt8*, pContext : LibC::UIntPtrT) : UInt32

    fun WinHttpGetProxyResult(hResolver : Void*, pProxyResult : Win32cr::Networking::WinHttp::WINHTTP_PROXY_RESULT*) : UInt32

    fun WinHttpGetProxyResultEx(hResolver : Void*, pProxyResultEx : Win32cr::Networking::WinHttp::WINHTTP_PROXY_RESULT_EX*) : UInt32

    fun WinHttpFreeProxyResult(pProxyResult : Win32cr::Networking::WinHttp::WINHTTP_PROXY_RESULT*) : Void

    fun WinHttpFreeProxyResultEx(pProxyResultEx : Win32cr::Networking::WinHttp::WINHTTP_PROXY_RESULT_EX*) : Void

    fun WinHttpResetAutoProxy(hSession : Void*, dwFlags : UInt32) : UInt32

    fun WinHttpGetIEProxyConfigForCurrentUser(pProxyConfig : Win32cr::Networking::WinHttp::WINHTTP_CURRENT_USER_IE_PROXY_CONFIG*) : Win32cr::Foundation::BOOL

    fun WinHttpWriteProxySettings(hSession : Void*, fForceUpdate : Win32cr::Foundation::BOOL, pWinHttpProxySettings : Win32cr::Networking::WinHttp::WINHTTP_PROXY_SETTINGS*) : UInt32

    fun WinHttpReadProxySettings(hSession : Void*, pcwszConnectionName : Win32cr::Foundation::PWSTR, fFallBackToDefaultSettings : Win32cr::Foundation::BOOL, fSetAutoDiscoverForDefaultSettings : Win32cr::Foundation::BOOL, pdwSettingsVersion : UInt32*, pfDefaultSettingsAreReturned : Win32cr::Foundation::BOOL*, pWinHttpProxySettings : Win32cr::Networking::WinHttp::WINHTTP_PROXY_SETTINGS*) : UInt32

    fun WinHttpFreeProxySettings(pWinHttpProxySettings : Win32cr::Networking::WinHttp::WINHTTP_PROXY_SETTINGS*) : Void

    fun WinHttpGetProxySettingsVersion(hSession : Void*, pdwProxySettingsVersion : UInt32*) : UInt32

    fun WinHttpSetProxySettingsPerUser(fProxySettingsPerUser : Win32cr::Foundation::BOOL) : UInt32

    fun WinHttpWebSocketCompleteUpgrade(hRequest : Void*, pContext : LibC::UIntPtrT) : Void*

    fun WinHttpWebSocketSend(hWebSocket : Void*, eBufferType : Win32cr::Networking::WinHttp::WINHTTP_WEB_SOCKET_BUFFER_TYPE, pvBuffer : Void*, dwBufferLength : UInt32) : UInt32

    fun WinHttpWebSocketReceive(hWebSocket : Void*, pvBuffer : Void*, dwBufferLength : UInt32, pdwBytesRead : UInt32*, peBufferType : Win32cr::Networking::WinHttp::WINHTTP_WEB_SOCKET_BUFFER_TYPE*) : UInt32

    fun WinHttpWebSocketShutdown(hWebSocket : Void*, usStatus : UInt16, pvReason : Void*, dwReasonLength : UInt32) : UInt32

    fun WinHttpWebSocketClose(hWebSocket : Void*, usStatus : UInt16, pvReason : Void*, dwReasonLength : UInt32) : UInt32

    fun WinHttpWebSocketQueryCloseStatus(hWebSocket : Void*, pusStatus : UInt16*, pvReason : Void*, dwReasonLength : UInt32, pdwReasonLengthConsumed : UInt32*) : UInt32

  end
end