require "../foundation.cr"
require "../networking/winsock.cr"

{% if compare_versions(Crystal::VERSION, "1.8.2") <= 0 %}
@[Link("delayimp")]
{% end %}
@[Link("user32")]
{% if compare_versions(Crystal::VERSION, "1.8.2") <= 0 %}
@[Link(ldflags: "/IGNORE:4199")]
{% end %}
{% if compare_versions(Crystal::VERSION, "1.8.2") <= 0 %}
@[Link(ldflags: "/DELAYLOAD:winhttp.dll")]
{% else %}
@[Link("winhttp")]
{% end %}
lib LibWin32
  WINHTTP_FLAG_ASYNC = 268435456_u32
  WINHTTP_FLAG_SECURE_DEFAULTS = 805306368_u32
  SECURITY_FLAG_IGNORE_UNKNOWN_CA = 256_u32
  SECURITY_FLAG_IGNORE_CERT_DATE_INVALID = 8192_u32
  SECURITY_FLAG_IGNORE_CERT_CN_INVALID = 4096_u32
  SECURITY_FLAG_IGNORE_CERT_WRONG_USAGE = 512_u32
  WINHTTP_AUTOPROXY_AUTO_DETECT = 1_u32
  WINHTTP_AUTOPROXY_CONFIG_URL = 2_u32
  WINHTTP_AUTOPROXY_HOST_KEEPCASE = 4_u32
  WINHTTP_AUTOPROXY_HOST_LOWERCASE = 8_u32
  WINHTTP_AUTOPROXY_ALLOW_AUTOCONFIG = 256_u32
  WINHTTP_AUTOPROXY_ALLOW_STATIC = 512_u32
  WINHTTP_AUTOPROXY_ALLOW_CM = 1024_u32
  WINHTTP_AUTOPROXY_RUN_INPROCESS = 65536_u32
  WINHTTP_AUTOPROXY_RUN_OUTPROCESS_ONLY = 131072_u32
  WINHTTP_AUTOPROXY_NO_DIRECTACCESS = 262144_u32
  WINHTTP_AUTOPROXY_NO_CACHE_CLIENT = 524288_u32
  WINHTTP_AUTOPROXY_NO_CACHE_SVC = 1048576_u32
  WINHTTP_AUTOPROXY_SORT_RESULTS = 4194304_u32
  WINHTTP_AUTO_DETECT_TYPE_DHCP = 1_u32
  WINHTTP_AUTO_DETECT_TYPE_DNS_A = 2_u32
  NETWORKING_KEY_BUFSIZE = 128_u32
  WINHTTP_PROXY_TYPE_DIRECT = 1_u32
  WINHTTP_PROXY_TYPE_PROXY = 2_u32
  WINHTTP_PROXY_TYPE_AUTO_PROXY_URL = 4_u32
  WINHTTP_PROXY_TYPE_AUTO_DETECT = 8_u32
  WINHTTP_REQUEST_STAT_FLAG_TCP_FAST_OPEN = 1_u32
  WINHTTP_REQUEST_STAT_FLAG_TLS_SESSION_RESUMPTION = 2_u32
  WINHTTP_REQUEST_STAT_FLAG_TLS_FALSE_START = 4_u32
  WINHTTP_REQUEST_STAT_FLAG_PROXY_TLS_SESSION_RESUMPTION = 8_u32
  WINHTTP_REQUEST_STAT_FLAG_PROXY_TLS_FALSE_START = 16_u32
  WINHTTP_REQUEST_STAT_FLAG_FIRST_REQUEST = 32_u32
  WINHTTP_MATCH_CONNECTION_GUID_FLAG_REQUIRE_MARKED_CONNECTION = 1_u32
  WINHTTP_MATCH_CONNECTION_GUID_FLAGS_MASK = 1_u32
  WINHTTP_RESOLVER_CACHE_CONFIG_FLAG_SOFT_LIMIT = 1_u32
  WINHTTP_RESOLVER_CACHE_CONFIG_FLAG_BYPASS_CACHE = 2_u32
  WINHTTP_RESOLVER_CACHE_CONFIG_FLAG_USE_DNS_TTL = 4_u32
  WINHTTP_RESOLVER_CACHE_CONFIG_FLAG_CONN_USE_TTL = 8_u32
  WINHTTP_TIME_FORMAT_BUFSIZE = 62_u32
  WINHTTP_OPTION_CALLBACK = 1_u32
  WINHTTP_OPTION_RESOLVE_TIMEOUT = 2_u32
  WINHTTP_OPTION_CONNECT_TIMEOUT = 3_u32
  WINHTTP_OPTION_CONNECT_RETRIES = 4_u32
  WINHTTP_OPTION_SEND_TIMEOUT = 5_u32
  WINHTTP_OPTION_RECEIVE_TIMEOUT = 6_u32
  WINHTTP_OPTION_RECEIVE_RESPONSE_TIMEOUT = 7_u32
  WINHTTP_OPTION_HANDLE_TYPE = 9_u32
  WINHTTP_OPTION_READ_BUFFER_SIZE = 12_u32
  WINHTTP_OPTION_WRITE_BUFFER_SIZE = 13_u32
  WINHTTP_OPTION_PARENT_HANDLE = 21_u32
  WINHTTP_OPTION_EXTENDED_ERROR = 24_u32
  WINHTTP_OPTION_SECURITY_FLAGS = 31_u32
  WINHTTP_OPTION_SECURITY_CERTIFICATE_STRUCT = 32_u32
  WINHTTP_OPTION_URL = 34_u32
  WINHTTP_OPTION_SECURITY_KEY_BITNESS = 36_u32
  WINHTTP_OPTION_PROXY = 38_u32
  WINHTTP_OPTION_PROXY_RESULT_ENTRY = 39_u32
  WINHTTP_OPTION_USER_AGENT = 41_u32
  WINHTTP_OPTION_CONTEXT_VALUE = 45_u32
  WINHTTP_OPTION_CLIENT_CERT_CONTEXT = 47_u32
  WINHTTP_OPTION_REQUEST_PRIORITY = 58_u32
  WINHTTP_OPTION_HTTP_VERSION = 59_u32
  WINHTTP_OPTION_DISABLE_FEATURE = 63_u32
  WINHTTP_OPTION_CODEPAGE = 68_u32
  WINHTTP_OPTION_MAX_CONNS_PER_SERVER = 73_u32
  WINHTTP_OPTION_MAX_CONNS_PER_1_0_SERVER = 74_u32
  WINHTTP_OPTION_AUTOLOGON_POLICY = 77_u32
  WINHTTP_OPTION_SERVER_CERT_CONTEXT = 78_u32
  WINHTTP_OPTION_ENABLE_FEATURE = 79_u32
  WINHTTP_OPTION_WORKER_THREAD_COUNT = 80_u32
  WINHTTP_OPTION_PASSPORT_COBRANDING_TEXT = 81_u32
  WINHTTP_OPTION_PASSPORT_COBRANDING_URL = 82_u32
  WINHTTP_OPTION_CONFIGURE_PASSPORT_AUTH = 83_u32
  WINHTTP_OPTION_SECURE_PROTOCOLS = 84_u32
  WINHTTP_OPTION_ENABLETRACING = 85_u32
  WINHTTP_OPTION_PASSPORT_SIGN_OUT = 86_u32
  WINHTTP_OPTION_PASSPORT_RETURN_URL = 87_u32
  WINHTTP_OPTION_REDIRECT_POLICY = 88_u32
  WINHTTP_OPTION_MAX_HTTP_AUTOMATIC_REDIRECTS = 89_u32
  WINHTTP_OPTION_MAX_HTTP_STATUS_CONTINUE = 90_u32
  WINHTTP_OPTION_MAX_RESPONSE_HEADER_SIZE = 91_u32
  WINHTTP_OPTION_MAX_RESPONSE_DRAIN_SIZE = 92_u32
  WINHTTP_OPTION_CONNECTION_INFO = 93_u32
  WINHTTP_OPTION_CLIENT_CERT_ISSUER_LIST = 94_u32
  WINHTTP_OPTION_SPN = 96_u32
  WINHTTP_OPTION_GLOBAL_PROXY_CREDS = 97_u32
  WINHTTP_OPTION_GLOBAL_SERVER_CREDS = 98_u32
  WINHTTP_OPTION_UNLOAD_NOTIFY_EVENT = 99_u32
  WINHTTP_OPTION_REJECT_USERPWD_IN_URL = 100_u32
  WINHTTP_OPTION_USE_GLOBAL_SERVER_CREDENTIALS = 101_u32
  WINHTTP_OPTION_RECEIVE_PROXY_CONNECT_RESPONSE = 103_u32
  WINHTTP_OPTION_IS_PROXY_CONNECT_RESPONSE = 104_u32
  WINHTTP_OPTION_SERVER_SPN_USED = 106_u32
  WINHTTP_OPTION_PROXY_SPN_USED = 107_u32
  WINHTTP_OPTION_SERVER_CBT = 108_u32
  WINHTTP_OPTION_UNSAFE_HEADER_PARSING = 110_u32
  WINHTTP_OPTION_ASSURED_NON_BLOCKING_CALLBACKS = 111_u32
  WINHTTP_OPTION_UPGRADE_TO_WEB_SOCKET = 114_u32
  WINHTTP_OPTION_WEB_SOCKET_CLOSE_TIMEOUT = 115_u32
  WINHTTP_OPTION_WEB_SOCKET_KEEPALIVE_INTERVAL = 116_u32
  WINHTTP_OPTION_DECOMPRESSION = 118_u32
  WINHTTP_OPTION_WEB_SOCKET_RECEIVE_BUFFER_SIZE = 122_u32
  WINHTTP_OPTION_WEB_SOCKET_SEND_BUFFER_SIZE = 123_u32
  WINHTTP_OPTION_TCP_PRIORITY_HINT = 128_u32
  WINHTTP_OPTION_CONNECTION_FILTER = 131_u32
  WINHTTP_OPTION_ENABLE_HTTP_PROTOCOL = 133_u32
  WINHTTP_OPTION_HTTP_PROTOCOL_USED = 134_u32
  WINHTTP_OPTION_KDC_PROXY_SETTINGS = 136_u32
  WINHTTP_OPTION_PROXY_DISABLE_SERVICE_CALLS = 137_u32
  WINHTTP_OPTION_ENCODE_EXTRA = 138_u32
  WINHTTP_OPTION_DISABLE_STREAM_QUEUE = 139_u32
  WINHTTP_OPTION_IPV6_FAST_FALLBACK = 140_u32
  WINHTTP_OPTION_CONNECTION_STATS_V0 = 141_u32
  WINHTTP_OPTION_REQUEST_TIMES = 142_u32
  WINHTTP_OPTION_EXPIRE_CONNECTION = 143_u32
  WINHTTP_OPTION_DISABLE_SECURE_PROTOCOL_FALLBACK = 144_u32
  WINHTTP_OPTION_HTTP_PROTOCOL_REQUIRED = 145_u32
  WINHTTP_OPTION_REQUEST_STATS = 146_u32
  WINHTTP_OPTION_SERVER_CERT_CHAIN_CONTEXT = 147_u32
  WINHTTP_OPTION_CONNECTION_STATS_V1 = 150_u32
  WINHTTP_OPTION_SECURITY_INFO = 151_u32
  WINHTTP_OPTION_TCP_KEEPALIVE = 152_u32
  WINHTTP_OPTION_TCP_FAST_OPEN = 153_u32
  WINHTTP_OPTION_TLS_FALSE_START = 154_u32
  WINHTTP_OPTION_IGNORE_CERT_REVOCATION_OFFLINE = 155_u32
  WINHTTP_OPTION_SOURCE_ADDRESS = 156_u32
  WINHTTP_OPTION_HEAP_EXTENSION = 157_u32
  WINHTTP_OPTION_TLS_PROTOCOL_INSECURE_FALLBACK = 158_u32
  WINHTTP_OPTION_STREAM_ERROR_CODE = 159_u32
  WINHTTP_OPTION_REQUIRE_STREAM_END = 160_u32
  WINHTTP_OPTION_ENABLE_HTTP2_PLUS_CLIENT_CERT = 161_u32
  WINHTTP_OPTION_FAILED_CONNECTION_RETRIES = 162_u32
  WINHTTP_OPTION_SET_GLOBAL_CALLBACK = 163_u32
  WINHTTP_OPTION_HTTP2_KEEPALIVE = 164_u32
  WINHTTP_OPTION_RESOLUTION_HOSTNAME = 165_u32
  WINHTTP_OPTION_SET_TOKEN_BINDING = 166_u32
  WINHTTP_OPTION_TOKEN_BINDING_PUBLIC_KEY = 167_u32
  WINHTTP_OPTION_REFERER_TOKEN_BINDING_HOSTNAME = 168_u32
  WINHTTP_OPTION_HTTP2_PLUS_TRANSFER_ENCODING = 169_u32
  WINHTTP_OPTION_RESOLVER_CACHE_CONFIG = 170_u32
  WINHTTP_OPTION_DISABLE_CERT_CHAIN_BUILDING = 171_u32
  WINHTTP_OPTION_BACKGROUND_CONNECTIONS = 172_u32
  WINHTTP_OPTION_FIRST_AVAILABLE_CONNECTION = 173_u32
  WINHTTP_OPTION_ENABLE_TEST_SIGNING = 174_u32
  WINHTTP_OPTION_NTSERVICE_FLAG_TEST = 175_u32
  WINHTTP_OPTION_DISABLE_PROXY_LINK_LOCAL_NAME_RESOLUTION = 176_u32
  WINHTTP_OPTION_TCP_PRIORITY_STATUS = 177_u32
  WINHTTP_OPTION_CONNECTION_GUID = 178_u32
  WINHTTP_OPTION_MATCH_CONNECTION_GUID = 179_u32
  WINHTTP_OPTION_PROXY_CONFIG_INFO = 180_u32
  WINHTTP_OPTION_AGGREGATE_PROXY_CONFIG = 181_u32
  WINHTTP_OPTION_SELECTED_PROXY_CONFIG_INFO = 182_u32
  WINHTTP_OPTION_HTTP2_RECEIVE_WINDOW = 183_u32
  WINHTTP_LAST_OPTION = 183_u32
  WINHTTP_OPTION_USERNAME = 4096_u32
  WINHTTP_OPTION_PASSWORD = 4097_u32
  WINHTTP_OPTION_PROXY_USERNAME = 4098_u32
  WINHTTP_OPTION_PROXY_PASSWORD = 4099_u32
  WINHTTP_CONNS_PER_SERVER_UNLIMITED = 4294967295_u32
  WINHTTP_CONNECTION_RETRY_CONDITION_408 = 1_u32
  WINHTTP_CONNECTION_RETRY_CONDITION_SSL_HANDSHAKE = 2_u32
  WINHTTP_CONNECTION_RETRY_CONDITION_STALE_CONNECTION = 4_u32
  WINHTTP_DECOMPRESSION_FLAG_GZIP = 1_u32
  WINHTTP_DECOMPRESSION_FLAG_DEFLATE = 2_u32
  WINHTTP_PROTOCOL_FLAG_HTTP2 = 1_u32
  WINHTTP_PROTOCOL_FLAG_HTTP3 = 2_u32
  WINHTTP_AUTOLOGON_SECURITY_LEVEL_MEDIUM = 0_u32
  WINHTTP_AUTOLOGON_SECURITY_LEVEL_LOW = 1_u32
  WINHTTP_AUTOLOGON_SECURITY_LEVEL_HIGH = 2_u32
  WINHTTP_AUTOLOGON_SECURITY_LEVEL_DEFAULT = 0_u32
  WINHTTP_OPTION_REDIRECT_POLICY_NEVER = 0_u32
  WINHTTP_OPTION_REDIRECT_POLICY_DISALLOW_HTTPS_TO_HTTP = 1_u32
  WINHTTP_OPTION_REDIRECT_POLICY_ALWAYS = 2_u32
  WINHTTP_OPTION_REDIRECT_POLICY_LAST = 2_u32
  WINHTTP_OPTION_REDIRECT_POLICY_DEFAULT = 1_u32
  WINHTTP_DISABLE_PASSPORT_AUTH = 0_u32
  WINHTTP_ENABLE_PASSPORT_AUTH = 268435456_u32
  WINHTTP_DISABLE_PASSPORT_KEYRING = 536870912_u32
  WINHTTP_ENABLE_PASSPORT_KEYRING = 1073741824_u32
  WINHTTP_DISABLE_COOKIES = 1_u32
  WINHTTP_DISABLE_REDIRECTS = 2_u32
  WINHTTP_DISABLE_AUTHENTICATION = 4_u32
  WINHTTP_DISABLE_KEEP_ALIVE = 8_u32
  WINHTTP_ENABLE_SSL_REVOCATION = 1_u32
  WINHTTP_ENABLE_SSL_REVERT_IMPERSONATION = 2_u32
  WINHTTP_DISABLE_SPN_SERVER_PORT = 0_u32
  WINHTTP_ENABLE_SPN_SERVER_PORT = 1_u32
  WINHTTP_OPTION_SPN_MASK = 1_u32
  WINHTTP_HANDLE_TYPE_SESSION = 1_u32
  WINHTTP_HANDLE_TYPE_CONNECT = 2_u32
  WINHTTP_HANDLE_TYPE_REQUEST = 3_u32
  WINHTTP_AUTH_SCHEME_PASSPORT = 4_u32
  WINHTTP_AUTH_SCHEME_DIGEST = 8_u32
  WINHTTP_AUTH_TARGET_SERVER = 0_u32
  WINHTTP_AUTH_TARGET_PROXY = 1_u32
  SECURITY_FLAG_SECURE = 1_u32
  SECURITY_FLAG_STRENGTH_WEAK = 268435456_u32
  SECURITY_FLAG_STRENGTH_MEDIUM = 1073741824_u32
  SECURITY_FLAG_STRENGTH_STRONG = 536870912_u32
  WINHTTP_CALLBACK_STATUS_FLAG_CERT_REV_FAILED = 1_u32
  WINHTTP_CALLBACK_STATUS_FLAG_INVALID_CERT = 2_u32
  WINHTTP_CALLBACK_STATUS_FLAG_CERT_REVOKED = 4_u32
  WINHTTP_CALLBACK_STATUS_FLAG_INVALID_CA = 8_u32
  WINHTTP_CALLBACK_STATUS_FLAG_CERT_CN_INVALID = 16_u32
  WINHTTP_CALLBACK_STATUS_FLAG_CERT_DATE_INVALID = 32_u32
  WINHTTP_CALLBACK_STATUS_FLAG_CERT_WRONG_USAGE = 64_u32
  WINHTTP_CALLBACK_STATUS_FLAG_SECURITY_CHANNEL_ERROR = 2147483648_u32
  WINHTTP_FLAG_SECURE_PROTOCOL_SSL2 = 8_u32
  WINHTTP_FLAG_SECURE_PROTOCOL_SSL3 = 32_u32
  WINHTTP_FLAG_SECURE_PROTOCOL_TLS1 = 128_u32
  WINHTTP_FLAG_SECURE_PROTOCOL_TLS1_1 = 512_u32
  WINHTTP_FLAG_SECURE_PROTOCOL_TLS1_2 = 2048_u32
  WINHTTP_FLAG_SECURE_PROTOCOL_TLS1_3 = 8192_u32
  WINHTTP_CALLBACK_STATUS_RESOLVING_NAME = 1_u32
  WINHTTP_CALLBACK_STATUS_NAME_RESOLVED = 2_u32
  WINHTTP_CALLBACK_STATUS_CONNECTING_TO_SERVER = 4_u32
  WINHTTP_CALLBACK_STATUS_CONNECTED_TO_SERVER = 8_u32
  WINHTTP_CALLBACK_STATUS_SENDING_REQUEST = 16_u32
  WINHTTP_CALLBACK_STATUS_REQUEST_SENT = 32_u32
  WINHTTP_CALLBACK_STATUS_RECEIVING_RESPONSE = 64_u32
  WINHTTP_CALLBACK_STATUS_RESPONSE_RECEIVED = 128_u32
  WINHTTP_CALLBACK_STATUS_CLOSING_CONNECTION = 256_u32
  WINHTTP_CALLBACK_STATUS_CONNECTION_CLOSED = 512_u32
  WINHTTP_CALLBACK_STATUS_HANDLE_CREATED = 1024_u32
  WINHTTP_CALLBACK_STATUS_HANDLE_CLOSING = 2048_u32
  WINHTTP_CALLBACK_STATUS_DETECTING_PROXY = 4096_u32
  WINHTTP_CALLBACK_STATUS_REDIRECT = 16384_u32
  WINHTTP_CALLBACK_STATUS_INTERMEDIATE_RESPONSE = 32768_u32
  WINHTTP_CALLBACK_STATUS_SECURE_FAILURE = 65536_u32
  WINHTTP_CALLBACK_STATUS_HEADERS_AVAILABLE = 131072_u32
  WINHTTP_CALLBACK_STATUS_DATA_AVAILABLE = 262144_u32
  WINHTTP_CALLBACK_STATUS_READ_COMPLETE = 524288_u32
  WINHTTP_CALLBACK_STATUS_WRITE_COMPLETE = 1048576_u32
  WINHTTP_CALLBACK_STATUS_REQUEST_ERROR = 2097152_u32
  WINHTTP_CALLBACK_STATUS_SENDREQUEST_COMPLETE = 4194304_u32
  WINHTTP_CALLBACK_STATUS_GETPROXYFORURL_COMPLETE = 16777216_u32
  WINHTTP_CALLBACK_STATUS_CLOSE_COMPLETE = 33554432_u32
  WINHTTP_CALLBACK_STATUS_SHUTDOWN_COMPLETE = 67108864_u32
  WINHTTP_CALLBACK_STATUS_SETTINGS_WRITE_COMPLETE = 268435456_u32
  WINHTTP_CALLBACK_STATUS_SETTINGS_READ_COMPLETE = 536870912_u32
  API_RECEIVE_RESPONSE = 1_u32
  API_QUERY_DATA_AVAILABLE = 2_u32
  API_READ_DATA = 3_u32
  API_WRITE_DATA = 4_u32
  API_SEND_REQUEST = 5_u32
  API_GET_PROXY_FOR_URL = 6_u32
  WINHTTP_CALLBACK_FLAG_DETECTING_PROXY = 4096_u32
  WINHTTP_CALLBACK_FLAG_REDIRECT = 16384_u32
  WINHTTP_CALLBACK_FLAG_INTERMEDIATE_RESPONSE = 32768_u32
  WINHTTP_CALLBACK_FLAG_SECURE_FAILURE = 65536_u32
  WINHTTP_CALLBACK_FLAG_SENDREQUEST_COMPLETE = 4194304_u32
  WINHTTP_CALLBACK_FLAG_HEADERS_AVAILABLE = 131072_u32
  WINHTTP_CALLBACK_FLAG_DATA_AVAILABLE = 262144_u32
  WINHTTP_CALLBACK_FLAG_READ_COMPLETE = 524288_u32
  WINHTTP_CALLBACK_FLAG_WRITE_COMPLETE = 1048576_u32
  WINHTTP_CALLBACK_FLAG_REQUEST_ERROR = 2097152_u32
  WINHTTP_CALLBACK_FLAG_GETPROXYFORURL_COMPLETE = 16777216_u32
  WINHTTP_CALLBACK_FLAG_ALL_NOTIFICATIONS = 4294967295_u32
  WINHTTP_QUERY_MIME_VERSION = 0_u32
  WINHTTP_QUERY_CONTENT_TYPE = 1_u32
  WINHTTP_QUERY_CONTENT_TRANSFER_ENCODING = 2_u32
  WINHTTP_QUERY_CONTENT_ID = 3_u32
  WINHTTP_QUERY_CONTENT_DESCRIPTION = 4_u32
  WINHTTP_QUERY_CONTENT_LENGTH = 5_u32
  WINHTTP_QUERY_CONTENT_LANGUAGE = 6_u32
  WINHTTP_QUERY_ALLOW = 7_u32
  WINHTTP_QUERY_PUBLIC = 8_u32
  WINHTTP_QUERY_DATE = 9_u32
  WINHTTP_QUERY_EXPIRES = 10_u32
  WINHTTP_QUERY_LAST_MODIFIED = 11_u32
  WINHTTP_QUERY_MESSAGE_ID = 12_u32
  WINHTTP_QUERY_URI = 13_u32
  WINHTTP_QUERY_DERIVED_FROM = 14_u32
  WINHTTP_QUERY_COST = 15_u32
  WINHTTP_QUERY_LINK = 16_u32
  WINHTTP_QUERY_PRAGMA = 17_u32
  WINHTTP_QUERY_VERSION = 18_u32
  WINHTTP_QUERY_STATUS_CODE = 19_u32
  WINHTTP_QUERY_STATUS_TEXT = 20_u32
  WINHTTP_QUERY_RAW_HEADERS = 21_u32
  WINHTTP_QUERY_RAW_HEADERS_CRLF = 22_u32
  WINHTTP_QUERY_CONNECTION = 23_u32
  WINHTTP_QUERY_ACCEPT = 24_u32
  WINHTTP_QUERY_ACCEPT_CHARSET = 25_u32
  WINHTTP_QUERY_ACCEPT_ENCODING = 26_u32
  WINHTTP_QUERY_ACCEPT_LANGUAGE = 27_u32
  WINHTTP_QUERY_AUTHORIZATION = 28_u32
  WINHTTP_QUERY_CONTENT_ENCODING = 29_u32
  WINHTTP_QUERY_FORWARDED = 30_u32
  WINHTTP_QUERY_FROM = 31_u32
  WINHTTP_QUERY_IF_MODIFIED_SINCE = 32_u32
  WINHTTP_QUERY_LOCATION = 33_u32
  WINHTTP_QUERY_ORIG_URI = 34_u32
  WINHTTP_QUERY_REFERER = 35_u32
  WINHTTP_QUERY_RETRY_AFTER = 36_u32
  WINHTTP_QUERY_SERVER = 37_u32
  WINHTTP_QUERY_TITLE = 38_u32
  WINHTTP_QUERY_USER_AGENT = 39_u32
  WINHTTP_QUERY_WWW_AUTHENTICATE = 40_u32
  WINHTTP_QUERY_PROXY_AUTHENTICATE = 41_u32
  WINHTTP_QUERY_ACCEPT_RANGES = 42_u32
  WINHTTP_QUERY_SET_COOKIE = 43_u32
  WINHTTP_QUERY_COOKIE = 44_u32
  WINHTTP_QUERY_REQUEST_METHOD = 45_u32
  WINHTTP_QUERY_REFRESH = 46_u32
  WINHTTP_QUERY_CONTENT_DISPOSITION = 47_u32
  WINHTTP_QUERY_AGE = 48_u32
  WINHTTP_QUERY_CACHE_CONTROL = 49_u32
  WINHTTP_QUERY_CONTENT_BASE = 50_u32
  WINHTTP_QUERY_CONTENT_LOCATION = 51_u32
  WINHTTP_QUERY_CONTENT_MD5 = 52_u32
  WINHTTP_QUERY_CONTENT_RANGE = 53_u32
  WINHTTP_QUERY_ETAG = 54_u32
  WINHTTP_QUERY_HOST = 55_u32
  WINHTTP_QUERY_IF_MATCH = 56_u32
  WINHTTP_QUERY_IF_NONE_MATCH = 57_u32
  WINHTTP_QUERY_IF_RANGE = 58_u32
  WINHTTP_QUERY_IF_UNMODIFIED_SINCE = 59_u32
  WINHTTP_QUERY_MAX_FORWARDS = 60_u32
  WINHTTP_QUERY_PROXY_AUTHORIZATION = 61_u32
  WINHTTP_QUERY_RANGE = 62_u32
  WINHTTP_QUERY_TRANSFER_ENCODING = 63_u32
  WINHTTP_QUERY_UPGRADE = 64_u32
  WINHTTP_QUERY_VARY = 65_u32
  WINHTTP_QUERY_VIA = 66_u32
  WINHTTP_QUERY_WARNING = 67_u32
  WINHTTP_QUERY_EXPECT = 68_u32
  WINHTTP_QUERY_PROXY_CONNECTION = 69_u32
  WINHTTP_QUERY_UNLESS_MODIFIED_SINCE = 70_u32
  WINHTTP_QUERY_PROXY_SUPPORT = 75_u32
  WINHTTP_QUERY_AUTHENTICATION_INFO = 76_u32
  WINHTTP_QUERY_PASSPORT_URLS = 77_u32
  WINHTTP_QUERY_PASSPORT_CONFIG = 78_u32
  WINHTTP_QUERY_MAX = 78_u32
  WINHTTP_QUERY_EX_ALL_HEADERS = 21_u32
  WINHTTP_QUERY_CUSTOM = 65535_u32
  WINHTTP_QUERY_FLAG_REQUEST_HEADERS = 2147483648_u32
  WINHTTP_QUERY_FLAG_SYSTEMTIME = 1073741824_u32
  WINHTTP_QUERY_FLAG_NUMBER = 536870912_u32
  WINHTTP_QUERY_FLAG_NUMBER64 = 134217728_u32
  WINHTTP_QUERY_FLAG_TRAILERS = 33554432_u32
  WINHTTP_QUERY_FLAG_WIRE_ENCODING = 16777216_u32
  HTTP_STATUS_CONTINUE = 100_u32
  HTTP_STATUS_SWITCH_PROTOCOLS = 101_u32
  HTTP_STATUS_OK = 200_u32
  HTTP_STATUS_CREATED = 201_u32
  HTTP_STATUS_ACCEPTED = 202_u32
  HTTP_STATUS_PARTIAL = 203_u32
  HTTP_STATUS_NO_CONTENT = 204_u32
  HTTP_STATUS_RESET_CONTENT = 205_u32
  HTTP_STATUS_PARTIAL_CONTENT = 206_u32
  HTTP_STATUS_WEBDAV_MULTI_STATUS = 207_u32
  HTTP_STATUS_AMBIGUOUS = 300_u32
  HTTP_STATUS_MOVED = 301_u32
  HTTP_STATUS_REDIRECT = 302_u32
  HTTP_STATUS_REDIRECT_METHOD = 303_u32
  HTTP_STATUS_NOT_MODIFIED = 304_u32
  HTTP_STATUS_USE_PROXY = 305_u32
  HTTP_STATUS_REDIRECT_KEEP_VERB = 307_u32
  HTTP_STATUS_PERMANENT_REDIRECT = 308_u32
  HTTP_STATUS_BAD_REQUEST = 400_u32
  HTTP_STATUS_DENIED = 401_u32
  HTTP_STATUS_PAYMENT_REQ = 402_u32
  HTTP_STATUS_FORBIDDEN = 403_u32
  HTTP_STATUS_NOT_FOUND = 404_u32
  HTTP_STATUS_BAD_METHOD = 405_u32
  HTTP_STATUS_NONE_ACCEPTABLE = 406_u32
  HTTP_STATUS_PROXY_AUTH_REQ = 407_u32
  HTTP_STATUS_REQUEST_TIMEOUT = 408_u32
  HTTP_STATUS_CONFLICT = 409_u32
  HTTP_STATUS_GONE = 410_u32
  HTTP_STATUS_LENGTH_REQUIRED = 411_u32
  HTTP_STATUS_PRECOND_FAILED = 412_u32
  HTTP_STATUS_REQUEST_TOO_LARGE = 413_u32
  HTTP_STATUS_URI_TOO_LONG = 414_u32
  HTTP_STATUS_UNSUPPORTED_MEDIA = 415_u32
  HTTP_STATUS_RETRY_WITH = 449_u32
  HTTP_STATUS_SERVER_ERROR = 500_u32
  HTTP_STATUS_NOT_SUPPORTED = 501_u32
  HTTP_STATUS_BAD_GATEWAY = 502_u32
  HTTP_STATUS_SERVICE_UNAVAIL = 503_u32
  HTTP_STATUS_GATEWAY_TIMEOUT = 504_u32
  HTTP_STATUS_VERSION_NOT_SUP = 505_u32
  HTTP_STATUS_FIRST = 100_u32
  HTTP_STATUS_LAST = 505_u32
  ICU_NO_ENCODE = 536870912_u32
  ICU_NO_META = 134217728_u32
  ICU_ENCODE_SPACES_ONLY = 67108864_u32
  ICU_BROWSER_MODE = 33554432_u32
  ICU_ENCODE_PERCENT = 4096_u32
  ICU_ESCAPE_AUTHORITY = 8192_u32
  WINHTTP_ADDREQ_INDEX_MASK = 65535_u32
  WINHTTP_ADDREQ_FLAGS_MASK = 4294901760_u32
  WINHTTP_ADDREQ_FLAG_ADD_IF_NEW = 268435456_u32
  WINHTTP_ADDREQ_FLAG_ADD = 536870912_u32
  WINHTTP_ADDREQ_FLAG_COALESCE_WITH_COMMA = 1073741824_u32
  WINHTTP_ADDREQ_FLAG_COALESCE_WITH_SEMICOLON = 16777216_u32
  WINHTTP_ADDREQ_FLAG_COALESCE = 1073741824_u32
  WINHTTP_ADDREQ_FLAG_REPLACE = 2147483648_u32
  WINHTTP_EXTENDED_HEADER_FLAG_UNICODE = 1_u32
  WINHTTP_IGNORE_REQUEST_TOTAL_LENGTH = 0_u32
  WINHTTP_ERROR_BASE = 12000_u32
  ERROR_WINHTTP_OUT_OF_HANDLES = 12001_u32
  ERROR_WINHTTP_TIMEOUT = 12002_u32
  ERROR_WINHTTP_INTERNAL_ERROR = 12004_u32
  ERROR_WINHTTP_INVALID_URL = 12005_u32
  ERROR_WINHTTP_UNRECOGNIZED_SCHEME = 12006_u32
  ERROR_WINHTTP_NAME_NOT_RESOLVED = 12007_u32
  ERROR_WINHTTP_INVALID_OPTION = 12009_u32
  ERROR_WINHTTP_OPTION_NOT_SETTABLE = 12011_u32
  ERROR_WINHTTP_SHUTDOWN = 12012_u32
  ERROR_WINHTTP_LOGIN_FAILURE = 12015_u32
  ERROR_WINHTTP_OPERATION_CANCELLED = 12017_u32
  ERROR_WINHTTP_INCORRECT_HANDLE_TYPE = 12018_u32
  ERROR_WINHTTP_INCORRECT_HANDLE_STATE = 12019_u32
  ERROR_WINHTTP_CANNOT_CONNECT = 12029_u32
  ERROR_WINHTTP_CONNECTION_ERROR = 12030_u32
  ERROR_WINHTTP_RESEND_REQUEST = 12032_u32
  ERROR_WINHTTP_CLIENT_AUTH_CERT_NEEDED = 12044_u32
  ERROR_WINHTTP_CANNOT_CALL_BEFORE_OPEN = 12100_u32
  ERROR_WINHTTP_CANNOT_CALL_BEFORE_SEND = 12101_u32
  ERROR_WINHTTP_CANNOT_CALL_AFTER_SEND = 12102_u32
  ERROR_WINHTTP_CANNOT_CALL_AFTER_OPEN = 12103_u32
  ERROR_WINHTTP_HEADER_NOT_FOUND = 12150_u32
  ERROR_WINHTTP_INVALID_SERVER_RESPONSE = 12152_u32
  ERROR_WINHTTP_INVALID_HEADER = 12153_u32
  ERROR_WINHTTP_INVALID_QUERY_REQUEST = 12154_u32
  ERROR_WINHTTP_HEADER_ALREADY_EXISTS = 12155_u32
  ERROR_WINHTTP_REDIRECT_FAILED = 12156_u32
  ERROR_WINHTTP_AUTO_PROXY_SERVICE_ERROR = 12178_u32
  ERROR_WINHTTP_BAD_AUTO_PROXY_SCRIPT = 12166_u32
  ERROR_WINHTTP_UNABLE_TO_DOWNLOAD_SCRIPT = 12167_u32
  ERROR_WINHTTP_UNHANDLED_SCRIPT_TYPE = 12176_u32
  ERROR_WINHTTP_SCRIPT_EXECUTION_ERROR = 12177_u32
  ERROR_WINHTTP_NOT_INITIALIZED = 12172_u32
  ERROR_WINHTTP_SECURE_FAILURE = 12175_u32
  ERROR_WINHTTP_SECURE_CERT_DATE_INVALID = 12037_u32
  ERROR_WINHTTP_SECURE_CERT_CN_INVALID = 12038_u32
  ERROR_WINHTTP_SECURE_INVALID_CA = 12045_u32
  ERROR_WINHTTP_SECURE_CERT_REV_FAILED = 12057_u32
  ERROR_WINHTTP_SECURE_CHANNEL_ERROR = 12157_u32
  ERROR_WINHTTP_SECURE_INVALID_CERT = 12169_u32
  ERROR_WINHTTP_SECURE_CERT_REVOKED = 12170_u32
  ERROR_WINHTTP_SECURE_CERT_WRONG_USAGE = 12179_u32
  ERROR_WINHTTP_AUTODETECTION_FAILED = 12180_u32
  ERROR_WINHTTP_HEADER_COUNT_EXCEEDED = 12181_u32
  ERROR_WINHTTP_HEADER_SIZE_OVERFLOW = 12182_u32
  ERROR_WINHTTP_CHUNKED_ENCODING_HEADER_SIZE_OVERFLOW = 12183_u32
  ERROR_WINHTTP_RESPONSE_DRAIN_OVERFLOW = 12184_u32
  ERROR_WINHTTP_CLIENT_CERT_NO_PRIVATE_KEY = 12185_u32
  ERROR_WINHTTP_CLIENT_CERT_NO_ACCESS_PRIVATE_KEY = 12186_u32
  ERROR_WINHTTP_CLIENT_AUTH_CERT_NEEDED_PROXY = 12187_u32
  ERROR_WINHTTP_SECURE_FAILURE_PROXY = 12188_u32
  ERROR_WINHTTP_RESERVED_189 = 12189_u32
  ERROR_WINHTTP_HTTP_PROTOCOL_MISMATCH = 12190_u32
  ERROR_WINHTTP_GLOBAL_CALLBACK_FAILED = 12191_u32
  ERROR_WINHTTP_FEATURE_DISABLED = 12192_u32
  WINHTTP_ERROR_LAST = 12192_u32
  WINHTTP_RESET_STATE = 1_u32
  WINHTTP_RESET_SWPAD_CURRENT_NETWORK = 2_u32
  WINHTTP_RESET_SWPAD_ALL = 4_u32
  WINHTTP_RESET_SCRIPT_CACHE = 8_u32
  WINHTTP_RESET_ALL = 65535_u32
  WINHTTP_RESET_NOTIFY_NETWORK_CHANGED = 65536_u32
  WINHTTP_RESET_OUT_OF_PROC = 131072_u32
  WINHTTP_RESET_DISCARD_RESOLVERS = 262144_u32
  WINHTTP_WEB_SOCKET_MAX_CLOSE_REASON_LENGTH = 123_u32
  WINHTTP_WEB_SOCKET_MIN_KEEPALIVE_VALUE = 15000_u32

  alias WINHTTP_STATUS_CALLBACK = Proc(Void*, LibC::UINT_PTR, UInt32, Void*, UInt32, Void)
  alias LPWINHTTP_STATUS_CALLBACK = Proc(Void)


  enum INTERNET_PORT : UInt32
    INTERNET_DEFAULT_HTTP_PORT = 80
    INTERNET_DEFAULT_HTTPS_PORT = 443
    INTERNET_DEFAULT_PORT = 0
  end

  enum WINHTTP_OPEN_REQUEST_FLAGS : UInt32
    WINHTTP_FLAG_BYPASS_PROXY_CACHE = 256
    WINHTTP_FLAG_ESCAPE_DISABLE = 64
    WINHTTP_FLAG_ESCAPE_DISABLE_QUERY = 128
    WINHTTP_FLAG_ESCAPE_PERCENT = 4
    WINHTTP_FLAG_NULL_CODEPAGE = 8
    WINHTTP_FLAG_REFRESH = 256
    WINHTTP_FLAG_SECURE = 8388608
  end

  enum WIN_HTTP_CREATE_URL_FLAGS : UInt32
    ICU_ESCAPE = 2147483648
    ICU_REJECT_USERPWD = 16384
    ICU_DECODE = 268435456
  end

  enum WINHTTP_ACCESS_TYPE : UInt32
    WINHTTP_ACCESS_TYPE_NO_PROXY = 1
    WINHTTP_ACCESS_TYPE_DEFAULT_PROXY = 0
    WINHTTP_ACCESS_TYPE_NAMED_PROXY = 3
    WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY = 4
  end

  enum WINHTTP_CREDS_AUTHSCHEME : UInt32
    WINHTTP_AUTH_SCHEME_BASIC = 1
    WINHTTP_AUTH_SCHEME_NTLM = 2
    WINHTTP_AUTH_SCHEME_NEGOTIATE = 16
  end

  enum WINHTTP_INTERNET_SCHEME : UInt32
    WINHTTP_INTERNET_SCHEME_HTTP = 1
    WINHTTP_INTERNET_SCHEME_HTTPS = 2
    WINHTTP_INTERNET_SCHEME_FTP = 3
    WINHTTP_INTERNET_SCHEME_SOCKS = 4
  end

  enum WINHTTP_REQUEST_TIME_ENTRY : Int32
    WinHttpProxyDetectionStart = 0
    WinHttpProxyDetectionEnd = 1
    WinHttpConnectionAcquireStart = 2
    WinHttpConnectionAcquireWaitEnd = 3
    WinHttpConnectionAcquireEnd = 4
    WinHttpNameResolutionStart = 5
    WinHttpNameResolutionEnd = 6
    WinHttpConnectionEstablishmentStart = 7
    WinHttpConnectionEstablishmentEnd = 8
    WinHttpTlsHandshakeClientLeg1Start = 9
    WinHttpTlsHandshakeClientLeg1End = 10
    WinHttpTlsHandshakeClientLeg2Start = 11
    WinHttpTlsHandshakeClientLeg2End = 12
    WinHttpTlsHandshakeClientLeg3Start = 13
    WinHttpTlsHandshakeClientLeg3End = 14
    WinHttpStreamWaitStart = 15
    WinHttpStreamWaitEnd = 16
    WinHttpSendRequestStart = 17
    WinHttpSendRequestHeadersCompressionStart = 18
    WinHttpSendRequestHeadersCompressionEnd = 19
    WinHttpSendRequestHeadersEnd = 20
    WinHttpSendRequestEnd = 21
    WinHttpReceiveResponseStart = 22
    WinHttpReceiveResponseHeadersDecompressionStart = 23
    WinHttpReceiveResponseHeadersDecompressionEnd = 24
    WinHttpReceiveResponseHeadersEnd = 25
    WinHttpReceiveResponseBodyDecompressionDelta = 26
    WinHttpReceiveResponseEnd = 27
    WinHttpProxyTunnelStart = 28
    WinHttpProxyTunnelEnd = 29
    WinHttpProxyTlsHandshakeClientLeg1Start = 30
    WinHttpProxyTlsHandshakeClientLeg1End = 31
    WinHttpProxyTlsHandshakeClientLeg2Start = 32
    WinHttpProxyTlsHandshakeClientLeg2End = 33
    WinHttpProxyTlsHandshakeClientLeg3Start = 34
    WinHttpProxyTlsHandshakeClientLeg3End = 35
    WinHttpRequestTimeLast = 36
    WinHttpRequestTimeMax = 64
  end

  enum WINHTTP_REQUEST_STAT_ENTRY : Int32
    WinHttpConnectFailureCount = 0
    WinHttpProxyFailureCount = 1
    WinHttpTlsHandshakeClientLeg1Size = 2
    WinHttpTlsHandshakeServerLeg1Size = 3
    WinHttpTlsHandshakeClientLeg2Size = 4
    WinHttpTlsHandshakeServerLeg2Size = 5
    WinHttpRequestHeadersSize = 6
    WinHttpRequestHeadersCompressedSize = 7
    WinHttpResponseHeadersSize = 8
    WinHttpResponseHeadersCompressedSize = 9
    WinHttpResponseBodySize = 10
    WinHttpResponseBodyCompressedSize = 11
    WinHttpProxyTlsHandshakeClientLeg1Size = 12
    WinHttpProxyTlsHandshakeServerLeg1Size = 13
    WinHttpProxyTlsHandshakeClientLeg2Size = 14
    WinHttpProxyTlsHandshakeServerLeg2Size = 15
    WinHttpRequestStatLast = 16
    WinHttpRequestStatMax = 32
  end

  enum WINHTTP_SECURE_DNS_SETTING : Int32
    WinHttpSecureDnsSettingDefault = 0
    WinHttpSecureDnsSettingForcePlaintext = 1
    WinHttpSecureDnsSettingRequireEncryption = 2
    WinHttpSecureDnsSettingTryEncryptionWithFallback = 3
    WinHttpSecureDnsSettingMax = 4
  end

  enum WINHTTP_WEB_SOCKET_OPERATION : Int32
    WINHTTP_WEB_SOCKET_SEND_OPERATION = 0
    WINHTTP_WEB_SOCKET_RECEIVE_OPERATION = 1
    WINHTTP_WEB_SOCKET_CLOSE_OPERATION = 2
    WINHTTP_WEB_SOCKET_SHUTDOWN_OPERATION = 3
  end

  enum WINHTTP_WEB_SOCKET_BUFFER_TYPE : Int32
    WINHTTP_WEB_SOCKET_BINARY_MESSAGE_BUFFER_TYPE = 0
    WINHTTP_WEB_SOCKET_BINARY_FRAGMENT_BUFFER_TYPE = 1
    WINHTTP_WEB_SOCKET_UTF8_MESSAGE_BUFFER_TYPE = 2
    WINHTTP_WEB_SOCKET_UTF8_FRAGMENT_BUFFER_TYPE = 3
    WINHTTP_WEB_SOCKET_CLOSE_BUFFER_TYPE = 4
  end

  enum WINHTTP_WEB_SOCKET_CLOSE_STATUS : Int32
    WINHTTP_WEB_SOCKET_SUCCESS_CLOSE_STATUS = 1000
    WINHTTP_WEB_SOCKET_ENDPOINT_TERMINATED_CLOSE_STATUS = 1001
    WINHTTP_WEB_SOCKET_PROTOCOL_ERROR_CLOSE_STATUS = 1002
    WINHTTP_WEB_SOCKET_INVALID_DATA_TYPE_CLOSE_STATUS = 1003
    WINHTTP_WEB_SOCKET_EMPTY_CLOSE_STATUS = 1005
    WINHTTP_WEB_SOCKET_ABORTED_CLOSE_STATUS = 1006
    WINHTTP_WEB_SOCKET_INVALID_PAYLOAD_CLOSE_STATUS = 1007
    WINHTTP_WEB_SOCKET_POLICY_VIOLATION_CLOSE_STATUS = 1008
    WINHTTP_WEB_SOCKET_MESSAGE_TOO_BIG_CLOSE_STATUS = 1009
    WINHTTP_WEB_SOCKET_UNSUPPORTED_EXTENSIONS_CLOSE_STATUS = 1010
    WINHTTP_WEB_SOCKET_SERVER_ERROR_CLOSE_STATUS = 1011
    WINHTTP_WEB_SOCKET_SECURE_HANDSHAKE_ERROR_CLOSE_STATUS = 1015
  end

  union WINHTTP_EXTENDED_HEADER_Anonymous1_e__Union
    pwsz_name : LibC::LPWSTR
    psz_name : PSTR
  end
  union WINHTTP_EXTENDED_HEADER_Anonymous2_e__Union
    pwsz_value : LibC::LPWSTR
    psz_value : PSTR
  end
  union WINHTTP_HEADER_NAME
    pwsz_name : LibC::LPWSTR
    psz_name : PSTR
  end

  struct WINHTTP_ASYNC_RESULT
    dw_result : LibC::UINT_PTR
    dw_error : UInt32
  end
  struct HTTP_VERSION_INFO
    dw_major_version : UInt32
    dw_minor_version : UInt32
  end
  struct URL_COMPONENTS
    dw_struct_size : UInt32
    lpsz_scheme : LibC::LPWSTR
    dw_scheme_length : UInt32
    n_scheme : WINHTTP_INTERNET_SCHEME
    lpsz_host_name : LibC::LPWSTR
    dw_host_name_length : UInt32
    n_port : UInt16
    lpsz_user_name : LibC::LPWSTR
    dw_user_name_length : UInt32
    lpsz_password : LibC::LPWSTR
    dw_password_length : UInt32
    lpsz_url_path : LibC::LPWSTR
    dw_url_path_length : UInt32
    lpsz_extra_info : LibC::LPWSTR
    dw_extra_info_length : UInt32
  end
  struct WINHTTP_PROXY_INFO
    dw_access_type : WINHTTP_ACCESS_TYPE
    lpsz_proxy : LibC::LPWSTR
    lpsz_proxy_bypass : LibC::LPWSTR
  end
  struct WINHTTP_AUTOPROXY_OPTIONS
    dw_flags : UInt32
    dw_auto_detect_flags : UInt32
    lpsz_auto_config_url : LibC::LPWSTR
    lpv_reserved : Void*
    dw_reserved : UInt32
    f_auto_logon_if_challenged : LibC::BOOL
  end
  struct WINHTTP_PROXY_RESULT_ENTRY
    f_proxy : LibC::BOOL
    f_bypass : LibC::BOOL
    proxy_scheme : WINHTTP_INTERNET_SCHEME
    pwsz_proxy : LibC::LPWSTR
    proxy_port : UInt16
  end
  struct WINHTTP_PROXY_RESULT
    c_entries : UInt32
    p_entries : WINHTTP_PROXY_RESULT_ENTRY*
  end
  struct WINHTTP_PROXY_RESULT_EX
    c_entries : UInt32
    p_entries : WINHTTP_PROXY_RESULT_ENTRY*
    h_proxy_detection_handle : LibC::HANDLE
    dw_proxy_interface_affinity : UInt32
  end
  struct WinHttpProxyNetworkKey
    pb_buffer : UInt8[128]*
  end
  struct WINHTTP_PROXY_SETTINGS
    dw_struct_size : UInt32
    dw_flags : UInt32
    dw_current_settings_version : UInt32
    pwsz_connection_name : LibC::LPWSTR
    pwsz_proxy : LibC::LPWSTR
    pwsz_proxy_bypass : LibC::LPWSTR
    pwsz_autoconfig_url : LibC::LPWSTR
    pwsz_autoconfig_secondary_url : LibC::LPWSTR
    dw_auto_discovery_flags : UInt32
    pwsz_last_known_good_auto_config_url : LibC::LPWSTR
    dw_autoconfig_reload_delay_mins : UInt32
    ft_last_known_detect_time : FILETIME
    dw_detected_interface_ip_count : UInt32
    pdw_detected_interface_ip : UInt32*
    c_network_keys : UInt32
    p_network_keys : WinHttpProxyNetworkKey*
  end
  struct WINHTTP_CERTIFICATE_INFO
    ft_expiry : FILETIME
    ft_start : FILETIME
    lpsz_subject_info : LibC::LPWSTR
    lpsz_issuer_info : LibC::LPWSTR
    lpsz_protocol_name : LibC::LPWSTR
    lpsz_signature_alg_name : LibC::LPWSTR
    lpsz_encryption_alg_name : LibC::LPWSTR
    dw_key_size : UInt32
  end
  struct WINHTTP_CONNECTION_INFO
    cb_size : UInt32
    local_address : SOCKADDR_STORAGE
    remote_address : SOCKADDR_STORAGE
  end
  struct WINHTTP_REQUEST_TIMES
    c_times : UInt32
    rgull_times : UInt64[64]*
  end
  struct WINHTTP_REQUEST_STATS
    ull_flags : UInt64
    ul_index : UInt32
    c_stats : UInt32
    rgull_stats : UInt64[32]*
  end
  struct WINHTTP_MATCH_CONNECTION_GUID
    connection_guid : Guid
    ull_flags : UInt64
  end
  struct WINHTTP_EXTENDED_HEADER
    anonymous1 : WINHTTP_EXTENDED_HEADER_Anonymous1_e__Union
    anonymous2 : WINHTTP_EXTENDED_HEADER_Anonymous2_e__Union
  end
  struct WINHTTP_RESOLVER_CACHE_CONFIG
    ul_max_resolver_cache_entries : UInt32
    ul_max_cache_entry_age : UInt32
    ul_min_cache_entry_ttl : UInt32
    secure_dns_setting : WINHTTP_SECURE_DNS_SETTING
    ull_conn_resolution_wait_time : UInt64
    ull_flags : UInt64
  end
  struct WINHTTP_CONNECTION_GROUP
    c_connections : UInt32
    guid_group : Guid
  end
  struct WINHTTP_HOST_CONNECTION_GROUP
    pwsz_host : LibC::LPWSTR
    c_connection_groups : UInt32
    p_connection_groups : WINHTTP_CONNECTION_GROUP*
  end
  struct WINHTTP_QUERY_CONNECTION_GROUP_RESULT
    c_hosts : UInt32
    p_host_connection_groups : WINHTTP_HOST_CONNECTION_GROUP*
  end
  struct WINHTTP_HTTP2_RECEIVE_WINDOW
    ul_stream_window : UInt32
    ul_stream_window_update_delta : UInt32
  end
  struct WINHTTP_FAILED_CONNECTION_RETRIES
    dw_max_retries : UInt32
    dw_allowed_retry_conditions : UInt32
  end
  struct WINHTTP_CREDS
    lpsz_user_name : PSTR
    lpsz_password : PSTR
    lpsz_realm : PSTR
    dw_auth_scheme : WINHTTP_CREDS_AUTHSCHEME
    lpsz_host_name : PSTR
    dw_port : UInt32
  end
  struct WINHTTP_CREDS_EX
    lpsz_user_name : PSTR
    lpsz_password : PSTR
    lpsz_realm : PSTR
    dw_auth_scheme : WINHTTP_CREDS_AUTHSCHEME
    lpsz_host_name : PSTR
    dw_port : UInt32
    lpsz_url : PSTR
  end
  struct WINHTTP_CURRENT_USER_IE_PROXY_CONFIG
    f_auto_detect : LibC::BOOL
    lpsz_auto_config_url : LibC::LPWSTR
    lpsz_proxy : LibC::LPWSTR
    lpsz_proxy_bypass : LibC::LPWSTR
  end
  struct WINHTTP_WEB_SOCKET_ASYNC_RESULT
    async_result : WINHTTP_ASYNC_RESULT
    operation : WINHTTP_WEB_SOCKET_OPERATION
  end
  struct WINHTTP_WEB_SOCKET_STATUS
    dw_bytes_transferred : UInt32
    e_buffer_type : WINHTTP_WEB_SOCKET_BUFFER_TYPE
  end


  # Params # hinternet : Void* [In],lpfninternetcallback : WINHTTP_STATUS_CALLBACK [In],dwnotificationflags : UInt32 [In],dwreserved : LibC::UINT_PTR [In]
  fun WinHttpSetStatusCallback(hinternet : Void*, lpfninternetcallback : WINHTTP_STATUS_CALLBACK, dwnotificationflags : UInt32, dwreserved : LibC::UINT_PTR) : WINHTTP_STATUS_CALLBACK

  # Params # pst : SYSTEMTIME* [In],pwsztime : Char* [In]
  fun WinHttpTimeFromSystemTime(pst : SYSTEMTIME*, pwsztime : Char*) : LibC::BOOL

  # Params # pwsztime : LibC::LPWSTR [In],pst : SYSTEMTIME* [In]
  fun WinHttpTimeToSystemTime(pwsztime : LibC::LPWSTR, pst : SYSTEMTIME*) : LibC::BOOL

  # Params # pwszurl : Char* [In],dwurllength : UInt32 [In],dwflags : UInt32 [In],lpurlcomponents : URL_COMPONENTS* [In]
  fun WinHttpCrackUrl(pwszurl : Char*, dwurllength : UInt32, dwflags : UInt32, lpurlcomponents : URL_COMPONENTS*) : LibC::BOOL

  # Params # lpurlcomponents : URL_COMPONENTS* [In],dwflags : WIN_HTTP_CREATE_URL_FLAGS [In],pwszurl : Char* [In],pdwurllength : UInt32* [In]
  fun WinHttpCreateUrl(lpurlcomponents : URL_COMPONENTS*, dwflags : WIN_HTTP_CREATE_URL_FLAGS, pwszurl : Char*, pdwurllength : UInt32*) : LibC::BOOL

  # Params # 
  fun WinHttpCheckPlatform : LibC::BOOL

  # Params # pproxyinfo : WINHTTP_PROXY_INFO* [In]
  fun WinHttpGetDefaultProxyConfiguration(pproxyinfo : WINHTTP_PROXY_INFO*) : LibC::BOOL

  # Params # pproxyinfo : WINHTTP_PROXY_INFO* [In]
  fun WinHttpSetDefaultProxyConfiguration(pproxyinfo : WINHTTP_PROXY_INFO*) : LibC::BOOL

  # Params # pszagentw : LibC::LPWSTR [In],dwaccesstype : WINHTTP_ACCESS_TYPE [In],pszproxyw : LibC::LPWSTR [In],pszproxybypassw : LibC::LPWSTR [In],dwflags : UInt32 [In]
  fun WinHttpOpen(pszagentw : LibC::LPWSTR, dwaccesstype : WINHTTP_ACCESS_TYPE, pszproxyw : LibC::LPWSTR, pszproxybypassw : LibC::LPWSTR, dwflags : UInt32) : Void*

  # Params # hinternet : Void* [In]
  fun WinHttpCloseHandle(hinternet : Void*) : LibC::BOOL

  # Params # hsession : Void* [In],pswzservername : LibC::LPWSTR [In],nserverport : INTERNET_PORT [In],dwreserved : UInt32 [In]
  fun WinHttpConnect(hsession : Void*, pswzservername : LibC::LPWSTR, nserverport : INTERNET_PORT, dwreserved : UInt32) : Void*

  # Params # hrequest : Void* [In],lpbuffer : Void* [In],dwnumberofbytestoread : UInt32 [In],lpdwnumberofbytesread : UInt32* [In]
  fun WinHttpReadData(hrequest : Void*, lpbuffer : Void*, dwnumberofbytestoread : UInt32, lpdwnumberofbytesread : UInt32*) : LibC::BOOL

  # Params # hrequest : Void* [In],lpbuffer : Void* [In],dwnumberofbytestoread : UInt32 [In],lpdwnumberofbytesread : UInt32* [In],ullflags : UInt64 [In],cbproperty : UInt32 [In],pvproperty : Void* [In]
  fun WinHttpReadDataEx(hrequest : Void*, lpbuffer : Void*, dwnumberofbytestoread : UInt32, lpdwnumberofbytesread : UInt32*, ullflags : UInt64, cbproperty : UInt32, pvproperty : Void*) : UInt32

  # Params # hrequest : Void* [In],lpbuffer : Void* [In],dwnumberofbytestowrite : UInt32 [In],lpdwnumberofbyteswritten : UInt32* [In]
  fun WinHttpWriteData(hrequest : Void*, lpbuffer : Void*, dwnumberofbytestowrite : UInt32, lpdwnumberofbyteswritten : UInt32*) : LibC::BOOL

  # Params # hrequest : Void* [In],lpdwnumberofbytesavailable : UInt32* [In]
  fun WinHttpQueryDataAvailable(hrequest : Void*, lpdwnumberofbytesavailable : UInt32*) : LibC::BOOL

  # Params # hinternet : Void* [In],dwoption : UInt32 [In],lpbuffer : Void* [In],lpdwbufferlength : UInt32* [In]
  fun WinHttpQueryOption(hinternet : Void*, dwoption : UInt32, lpbuffer : Void*, lpdwbufferlength : UInt32*) : LibC::BOOL

  # Params # hinternet : Void* [In],dwoption : UInt32 [In],lpbuffer : Void* [In],dwbufferlength : UInt32 [In]
  fun WinHttpSetOption(hinternet : Void*, dwoption : UInt32, lpbuffer : Void*, dwbufferlength : UInt32) : LibC::BOOL

  # Params # hinternet : Void* [In],nresolvetimeout : Int32 [In],nconnecttimeout : Int32 [In],nsendtimeout : Int32 [In],nreceivetimeout : Int32 [In]
  fun WinHttpSetTimeouts(hinternet : Void*, nresolvetimeout : Int32, nconnecttimeout : Int32, nsendtimeout : Int32, nreceivetimeout : Int32) : LibC::BOOL

  # Params # hconnect : Void* [In],pwszverb : LibC::LPWSTR [In],pwszobjectname : LibC::LPWSTR [In],pwszversion : LibC::LPWSTR [In],pwszreferrer : LibC::LPWSTR [In],ppwszaccepttypes : LibC::LPWSTR* [In],dwflags : WINHTTP_OPEN_REQUEST_FLAGS [In]
  fun WinHttpOpenRequest(hconnect : Void*, pwszverb : LibC::LPWSTR, pwszobjectname : LibC::LPWSTR, pwszversion : LibC::LPWSTR, pwszreferrer : LibC::LPWSTR, ppwszaccepttypes : LibC::LPWSTR*, dwflags : WINHTTP_OPEN_REQUEST_FLAGS) : Void*

  # Params # hrequest : Void* [In],lpszheaders : Char* [In],dwheaderslength : UInt32 [In],dwmodifiers : UInt32 [In]
  fun WinHttpAddRequestHeaders(hrequest : Void*, lpszheaders : Char*, dwheaderslength : UInt32, dwmodifiers : UInt32) : LibC::BOOL

  # Params # hrequest : Void* [In],dwmodifiers : UInt32 [In],ullflags : UInt64 [In],ullextra : UInt64 [In],cheaders : UInt32 [In],pheaders : WINHTTP_EXTENDED_HEADER* [In]
  fun WinHttpAddRequestHeadersEx(hrequest : Void*, dwmodifiers : UInt32, ullflags : UInt64, ullextra : UInt64, cheaders : UInt32, pheaders : WINHTTP_EXTENDED_HEADER*) : UInt32

  # Params # hrequest : Void* [In],lpszheaders : Char* [In],dwheaderslength : UInt32 [In],lpoptional : Void* [In],dwoptionallength : UInt32 [In],dwtotallength : UInt32 [In],dwcontext : LibC::UINT_PTR [In]
  fun WinHttpSendRequest(hrequest : Void*, lpszheaders : Char*, dwheaderslength : UInt32, lpoptional : Void*, dwoptionallength : UInt32, dwtotallength : UInt32, dwcontext : LibC::UINT_PTR) : LibC::BOOL

  # Params # hrequest : Void* [In],authtargets : UInt32 [In],authscheme : UInt32 [In],pwszusername : LibC::LPWSTR [In],pwszpassword : LibC::LPWSTR [In],pauthparams : Void* [In]
  fun WinHttpSetCredentials(hrequest : Void*, authtargets : UInt32, authscheme : UInt32, pwszusername : LibC::LPWSTR, pwszpassword : LibC::LPWSTR, pauthparams : Void*) : LibC::BOOL

  # Params # hrequest : Void* [In],lpdwsupportedschemes : UInt32* [In],lpdwfirstscheme : UInt32* [In],pdwauthtarget : UInt32* [In]
  fun WinHttpQueryAuthSchemes(hrequest : Void*, lpdwsupportedschemes : UInt32*, lpdwfirstscheme : UInt32*, pdwauthtarget : UInt32*) : LibC::BOOL

  # Params # hrequest : Void* [In],lpreserved : Void* [In]
  fun WinHttpReceiveResponse(hrequest : Void*, lpreserved : Void*) : LibC::BOOL

  # Params # hrequest : Void* [In],dwinfolevel : UInt32 [In],pwszname : LibC::LPWSTR [In],lpbuffer : Void* [In],lpdwbufferlength : UInt32* [In],lpdwindex : UInt32* [In]
  fun WinHttpQueryHeaders(hrequest : Void*, dwinfolevel : UInt32, pwszname : LibC::LPWSTR, lpbuffer : Void*, lpdwbufferlength : UInt32*, lpdwindex : UInt32*) : LibC::BOOL

  # Params # hrequest : Void* [In],dwinfolevel : UInt32 [In],ullflags : UInt64 [In],uicodepage : UInt32 [In],pdwindex : UInt32* [In],pheadername : WINHTTP_HEADER_NAME* [In],pbuffer : Void* [In],pdwbufferlength : UInt32* [In],ppheaders : WINHTTP_EXTENDED_HEADER** [In],pdwheaderscount : UInt32* [In]
  fun WinHttpQueryHeadersEx(hrequest : Void*, dwinfolevel : UInt32, ullflags : UInt64, uicodepage : UInt32, pdwindex : UInt32*, pheadername : WINHTTP_HEADER_NAME*, pbuffer : Void*, pdwbufferlength : UInt32*, ppheaders : WINHTTP_EXTENDED_HEADER**, pdwheaderscount : UInt32*) : UInt32

  # Params # hinternet : Void* [In],pguidconnection : Guid* [In],ullflags : UInt64 [In],ppresult : WINHTTP_QUERY_CONNECTION_GROUP_RESULT** [In]
  fun WinHttpQueryConnectionGroup(hinternet : Void*, pguidconnection : Guid*, ullflags : UInt64, ppresult : WINHTTP_QUERY_CONNECTION_GROUP_RESULT**) : UInt32

  # Params # presult : WINHTTP_QUERY_CONNECTION_GROUP_RESULT* [In]
  fun WinHttpFreeQueryConnectionGroupResult(presult : WINHTTP_QUERY_CONNECTION_GROUP_RESULT*)

  # Params # dwautodetectflags : UInt32 [In],ppwstrautoconfigurl : LibC::LPWSTR* [In]
  fun WinHttpDetectAutoProxyConfigUrl(dwautodetectflags : UInt32, ppwstrautoconfigurl : LibC::LPWSTR*) : LibC::BOOL

  # Params # hsession : Void* [In],lpcwszurl : LibC::LPWSTR [In],pautoproxyoptions : WINHTTP_AUTOPROXY_OPTIONS* [In],pproxyinfo : WINHTTP_PROXY_INFO* [In]
  fun WinHttpGetProxyForUrl(hsession : Void*, lpcwszurl : LibC::LPWSTR, pautoproxyoptions : WINHTTP_AUTOPROXY_OPTIONS*, pproxyinfo : WINHTTP_PROXY_INFO*) : LibC::BOOL

  # Params # hsession : Void* [In],phresolver : Void** [In]
  fun WinHttpCreateProxyResolver(hsession : Void*, phresolver : Void**) : UInt32

  # Params # hresolver : Void* [In],pcwszurl : LibC::LPWSTR [In],pautoproxyoptions : WINHTTP_AUTOPROXY_OPTIONS* [In],pcontext : LibC::UINT_PTR [In]
  fun WinHttpGetProxyForUrlEx(hresolver : Void*, pcwszurl : LibC::LPWSTR, pautoproxyoptions : WINHTTP_AUTOPROXY_OPTIONS*, pcontext : LibC::UINT_PTR) : UInt32

  # Params # hresolver : Void* [In],pcwszurl : LibC::LPWSTR [In],pautoproxyoptions : WINHTTP_AUTOPROXY_OPTIONS* [In],cbinterfaceselectioncontext : UInt32 [In],pinterfaceselectioncontext : UInt8* [In],pcontext : LibC::UINT_PTR [In]
  fun WinHttpGetProxyForUrlEx2(hresolver : Void*, pcwszurl : LibC::LPWSTR, pautoproxyoptions : WINHTTP_AUTOPROXY_OPTIONS*, cbinterfaceselectioncontext : UInt32, pinterfaceselectioncontext : UInt8*, pcontext : LibC::UINT_PTR) : UInt32

  # Params # hresolver : Void* [In],pproxyresult : WINHTTP_PROXY_RESULT* [In]
  fun WinHttpGetProxyResult(hresolver : Void*, pproxyresult : WINHTTP_PROXY_RESULT*) : UInt32

  # Params # hresolver : Void* [In],pproxyresultex : WINHTTP_PROXY_RESULT_EX* [In]
  fun WinHttpGetProxyResultEx(hresolver : Void*, pproxyresultex : WINHTTP_PROXY_RESULT_EX*) : UInt32

  # Params # pproxyresult : WINHTTP_PROXY_RESULT* [In]
  fun WinHttpFreeProxyResult(pproxyresult : WINHTTP_PROXY_RESULT*)

  # Params # pproxyresultex : WINHTTP_PROXY_RESULT_EX* [In]
  fun WinHttpFreeProxyResultEx(pproxyresultex : WINHTTP_PROXY_RESULT_EX*)

  # Params # hsession : Void* [In],dwflags : UInt32 [In]
  fun WinHttpResetAutoProxy(hsession : Void*, dwflags : UInt32) : UInt32

  # Params # pproxyconfig : WINHTTP_CURRENT_USER_IE_PROXY_CONFIG* [In]
  fun WinHttpGetIEProxyConfigForCurrentUser(pproxyconfig : WINHTTP_CURRENT_USER_IE_PROXY_CONFIG*) : LibC::BOOL

  # Params # hsession : Void* [In],fforceupdate : LibC::BOOL [In],pwinhttpproxysettings : WINHTTP_PROXY_SETTINGS* [In]
  fun WinHttpWriteProxySettings(hsession : Void*, fforceupdate : LibC::BOOL, pwinhttpproxysettings : WINHTTP_PROXY_SETTINGS*) : UInt32

  # Params # hsession : Void* [In],pcwszconnectionname : LibC::LPWSTR [In],ffallbacktodefaultsettings : LibC::BOOL [In],fsetautodiscoverfordefaultsettings : LibC::BOOL [In],pdwsettingsversion : UInt32* [In],pfdefaultsettingsarereturned : LibC::BOOL* [In],pwinhttpproxysettings : WINHTTP_PROXY_SETTINGS* [In]
  fun WinHttpReadProxySettings(hsession : Void*, pcwszconnectionname : LibC::LPWSTR, ffallbacktodefaultsettings : LibC::BOOL, fsetautodiscoverfordefaultsettings : LibC::BOOL, pdwsettingsversion : UInt32*, pfdefaultsettingsarereturned : LibC::BOOL*, pwinhttpproxysettings : WINHTTP_PROXY_SETTINGS*) : UInt32

  # Params # pwinhttpproxysettings : WINHTTP_PROXY_SETTINGS* [In]
  fun WinHttpFreeProxySettings(pwinhttpproxysettings : WINHTTP_PROXY_SETTINGS*)

  # Params # hsession : Void* [In],pdwproxysettingsversion : UInt32* [In]
  fun WinHttpGetProxySettingsVersion(hsession : Void*, pdwproxysettingsversion : UInt32*) : UInt32

  # Params # fproxysettingsperuser : LibC::BOOL [In]
  fun WinHttpSetProxySettingsPerUser(fproxysettingsperuser : LibC::BOOL) : UInt32

  # Params # hrequest : Void* [In],pcontext : LibC::UINT_PTR [In]
  fun WinHttpWebSocketCompleteUpgrade(hrequest : Void*, pcontext : LibC::UINT_PTR) : Void*

  # Params # hwebsocket : Void* [In],ebuffertype : WINHTTP_WEB_SOCKET_BUFFER_TYPE [In],pvbuffer : Void* [In],dwbufferlength : UInt32 [In]
  fun WinHttpWebSocketSend(hwebsocket : Void*, ebuffertype : WINHTTP_WEB_SOCKET_BUFFER_TYPE, pvbuffer : Void*, dwbufferlength : UInt32) : UInt32

  # Params # hwebsocket : Void* [In],pvbuffer : Void* [In],dwbufferlength : UInt32 [In],pdwbytesread : UInt32* [In],pebuffertype : WINHTTP_WEB_SOCKET_BUFFER_TYPE* [In]
  fun WinHttpWebSocketReceive(hwebsocket : Void*, pvbuffer : Void*, dwbufferlength : UInt32, pdwbytesread : UInt32*, pebuffertype : WINHTTP_WEB_SOCKET_BUFFER_TYPE*) : UInt32

  # Params # hwebsocket : Void* [In],usstatus : UInt16 [In],pvreason : Void* [In],dwreasonlength : UInt32 [In]
  fun WinHttpWebSocketShutdown(hwebsocket : Void*, usstatus : UInt16, pvreason : Void*, dwreasonlength : UInt32) : UInt32

  # Params # hwebsocket : Void* [In],usstatus : UInt16 [In],pvreason : Void* [In],dwreasonlength : UInt32 [In]
  fun WinHttpWebSocketClose(hwebsocket : Void*, usstatus : UInt16, pvreason : Void*, dwreasonlength : UInt32) : UInt32

  # Params # hwebsocket : Void* [In],pusstatus : UInt16* [In],pvreason : Void* [In],dwreasonlength : UInt32 [In],pdwreasonlengthconsumed : UInt32* [In]
  fun WinHttpWebSocketQueryCloseStatus(hwebsocket : Void*, pusstatus : UInt16*, pvreason : Void*, dwreasonlength : UInt32, pdwreasonlengthconsumed : UInt32*) : UInt32
end
